### ISSUE TITLE
Conda: what is the difference between `dv_make_examples.py` and `python make_examples.zip`?

### ISSUE THREAD

**Issue by PhilPalmer** [google/deepvariant#101]
Hi,

I am working on a [deepvariant pipeline](https://github.com/nf-core/deepvariant/tree/dev) written in nextflow which installs deepvariant via conda. The command for `make_examples` will evaluate to something like this:
```bash
    time seq 0 !{numberShardsMinusOne} | \
    parallel --eta --halt 2 \
      python /opt/conda/pkgs/deepvariant-0.7.0-py27h5d9141f_0/share/deepvariant-0.7.0-0/binaries/DeepVariant/0.7.0/DeepVariant-0.7.0+cl-208818123/make_examples.zip \
      --mode calling \
      --ref chr20.fa.gz \
      --reads test.bam \
      --examples shardedExamples/examples.tfrecord@2.gz
      --task {}
```

I noticed that there is `dv_make_examples.py` on the PATH. Does this executable carry out the same/similar function as `python make_examples.zip`. If so how could I modify the code above to make it work?

Many thanks in advance

**Comment by pichuan** [comment]
Is the one you install on conda this one?
https://bioconda.github.io/recipes/deepvariant/README.html
If it's that, I believe it's recently updated to 0.7. 
This package actually isn't manage by the team at Google. But the owner (chapmanb@) has updated to the latest version (0.7). A quick search of `dv_make_examples.py` seems to be pointed to this file
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deepvariant/dv_make_examples.py
which it does call python make_examples.zip.

**Comment by chapmanb** [comment]
Phil and Pi-Chuan;
That's exactly right, `dv_make_examples.py` is a simple wrapper for `make_examples.zip` to make it directly callable and is part of the conda packaging process, not a default script from the Google team. If it's not useful, feel free to call directly at the standard installs, it just tries to avoid needing to know the full install path and other details about the parallelization so the command line syntax is simplified. For your example you'd use it like:
```
dv_make_examples.py
      --ref chr20.fa.gz \
      --reads test.bam \
      --examples shardedExamples/examples.tfrecord@2.gz \
      --regions regions.bed \
      --sample test \
      --logdir location/to/place/logfiles
      --cores 1
```
Hope this helps.
