### ISSUE TITLE
.io

### ISSUE THREAD

**Issue by GhisF** [google/deepvariant#108]

**Comment by pgrosu** [comment]
This must be the perfect issue I have ever encountered!  Just as a precaution before assuming it's resolved, by any chance @GhisF did you actually forget to post your issue?

Thanks,
~p

**Comment by GhisF** [comment]
Yes it is solved, just a small problem between my chair and my screen, seems to be fixed with a good coffee now.

Sorry for the noise.

**Comment by pgrosu** [comment]
No worries - we're friendly over here - happens to me as well :)

**Comment by pichuan** [comment]
Yup, no worries. I'll close this issue. If there are other questions, feel to file another one.
