### ISSUE TITLE
deepvariant on ubuntu - httplib.ResponseNotReady

### ISSUE THREAD

**Issue by tstokowy** [google/deepvariant#11]
Hi, I try to setup deepvariant on my ubuntu, following instructionsin section Download binaries, models, and test data, listed here.
https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.mddy

I get httplib.ResponseNotReady error.
![screenshot from 2017-12-11 13-31-30](https://user-images.githubusercontent.com/16382685/33831300-c7d8b290-de77-11e7-957f-748aadf16347.png)

I was able to run the repository docker, but I would like to use this variant caller on machine without internet access. Is this possible?

Kind regards,

--
Tomasz

**Comment by pichuan** [comment]
Hi Tomasz,
this issue might be the same as an earlier one. See this comment for a temporary solution:
https://github.com/google/deepvariant/issues/7#issuecomment-350528251

We are currently working on a fix, and will post an update to this github issue when it's fully fixed. Meanwhile, please let us know if you're having problems with the temporary fix.

**Comment by tstokowy** [comment]
Hi,
This temporary fixed worked out:
1. Set TF_NEED_GCP in settings.sh to 0
export TF_NEED_GCP=0
2. Comment out line in make_examples.py
# htslib_gcp_oauth.init()
3. build_and_test.sh works
4. I am able to run 
python-bazel-bin/deepvariant/make_examples --mode calling --ref ../input/ucsc.hg19.chr20.unittest.fasta --reads ../input/NA12878_S1.chr20.10_10p1mb.bam --regions "chr20:10,000,000-10,010,000" --examples ../output/output.examples.tfrecord

Thank you!

**Comment by depristo** [comment]
@tstokowy thanks for the pointer. We have a fix for this internally and it will arrive in the OSS version on our next push to the repo.

**Comment by scott7z** [comment]
This should be fixed in the most recent 0.4.1 binaries, and the HEAD of the r0.4 branch.
