### ISSUE TITLE
visualiszing_example, list index (0) out of range.

### ISSUE THREAD

**Issue by solokopi** [google/deepvariant#110]
@pichuan hi, i tried running the visualizing example, but at this stage keeps giving this error below. what could have been the problem. thank you.

<class 'tensorflow.core.example.example_pb2.Example'>
Traceback (most recent call last):
  File "visualize.py", line 70, in <module>
    visualize_example(example)
  File "visualize.py", line 48, in visualize_example
    titles = ["reconstructed RGBA (label=%s)" % get_label(example), "read base", "base quality", "mapping quality", "strand",
  File "visualize.py", line 29, in get_label
    return get_int64_list(example, 'label')[0]
IndexError: list index (0) out of range

**Comment by pichuan** [comment]
Hi,
I found a bug in the visualizing ipynb and fixed it internally already. It will come out in the next release (which I'm hoping will be soon).

For now, please update the `channels_to_rgb` function to this:

```
def channels_to_rgb(channels):
    # Reconstruct the original channels
    base = channels[0]
    qual = np.minimum(channels[1], channels[2])
    strand = channels[3]
    alpha = np.multiply(
        channels[4] / 254.0,
        channels[5] / 254.0)
    return np.multiply(
        np.stack([base, qual, strand]),
        alpha).astype(np.uint8).transpose([1, 2, 0])
```

It was actually a pretty obvious mistake. I wish I unit tested my notebook.

**Comment by pichuan** [comment]
And, when it's called in the notebook, it should have been:

```
    # Prepend an image: RGBA image reconstructed from the 6-channels
    channels.insert(0, channels_to_rgb(channels))
```

Let me know if this resolves your problem or not.

**Comment by pichuan** [comment]
After taking a look at your error, it might also be a different problem.

You might want to see what came out from you `get_int64_list(example, 'label')`. Is it possible that your example don't have a `'label'`? If you created your examples with `calling` mode in `make_examples`, they probably don't have a label, and might have resulted in that error.

**Comment by pgrosu** [comment]
Close :)  It's more indicative that `read_tfrecords` is not probably working properly, since `examples` is an empty list to iterate from.  So probably an issue with the installed version of Tensorflow.

**Comment by solokopi** [comment]
@pichuan thank you for the swift response, yes my make example was in `calling` in calling mode. i tried the training mode but it keeps telling me that "no index file found for the vcf file" meanwhile i have all in the same folder

**Comment by solokopi** [comment]
fixed, i got an example  in training mode, and it ran. thank you.
