### ISSUE TITLE
sharding call_variants

### ISSUE THREAD

**Issue by mclaugsf** [google/deepvariant#113]
I am exploring sharding the `call_variants` step and I came across this comment that I can simply concatenate TF records together with the `cat` Unix utility:

https://github.com/google/deepvariant/issues/49#issuecomment-366848143

I have a couple of questions if you could please answer.

*Q1:* Can I also use the `cat` utility to concatenate GVCF output shards?

Suppose I name the `call_variants` outputs: callvariants-00056-of-00064.gz

*Q2:* Could I pass along `callvariants@64.gz` to the `--infile` option of `postprocess_variants`?

**Comment by pichuan** [comment]
Q1: Yes. You can concatenate gzipped tfrecord files.
Q2: Yes, you should be able to do that.

If these don't work, feel free to reopen and let us know what issues you're encountering.
