### ISSUE TITLE
Can I use this to investigate SNP in bacteria genome?

### ISSUE THREAD

**Issue by yingeddi2008** [google/deepvariant#114]
Hi Google Hackers,

I am just curious, can I use this to investigate SNP in between different bacteria genomes?

Thanks,

Eddi

**Comment by AndrewCarroll** [comment]
This is a very interesting question, and the answers to it are complex. I assume for the sake of the question that you have FASTQ data from sequencing a single bacterial colony (so this is not a metagenomics question).

Let's divide the question between "can it technically be done" and "will the answers be scientifically valid"

To the question "can it technically be done", the answer is probably yes. I am not aware that we have specifically attempted this in bacteria. But if you have a FASTA file with a reference for a species and FASTQ reads, you should be able to generate variant calls for it.

To the question "will the answers be scientifically valid", it is important to note calling variants in bacterial genomes is an area of open research. Using DeepVariant is reasonable, but I don't think you'll able to consider the output of any method (DeepVariant or other) as certain to give you fully correct results on this problem right out of the box. You'll want to use a few methods (use Freebayes and GATK) and compare between them with metrics you can independently validate, then decide what works and doesn't for your use case.

One way to do this could be that for a clonal lineage you expect variants to all be called as 1/1 for the non-plasmid genome sequence. Ryan Poplin used this measure in a similar way to compare DeepVariant and other methods on inbred rice strains from the 3000 Rice Genomes Project.

We would be quite interested to receive your feedback on how DeepVariant performs in this use case, as this may help us understand the value of DeepVariant and improve it for the community.

**Comment by yingeddi2008** [comment]
Hi Andrew,
Thanks for answering my questions.It is very informative.
Currently I am using the GATK pipeline to identify any novel strains for a
particular bacteria genus. So far it makes sense, meaning the known mutated
locations on the genome can be found using the pipeline. However, there are
a lot of possible false positives, which could be either potential new
SNPs, or just sequencing error. That's what prompted me to explore
DeepVarient in the first place, to minimize false positives from sequencing
error.
As I understand that GATK has a step to incorporate known variants to
correct for downstream analysis. But bacteria in general do not have those
information. I am wondering do you have any toolbox on this topic?
I'd love to perform some comparisons between different variant detection of
bacteria genomes in the near future. Will keep you posted if I find
anything interesting.

**Comment by AndrewCarroll** [comment]
When you refer to the method GATK has to incorporate known variants for quality control, I believe that you are referring to VQSR (variant quality score recalibrator). You are correct that this requires a set of ground truth information. It seems likely to me that VQSR and similar systems would not behave correctly on bacterial data even if ground truth were available.

To understand whether events are false positives or real SNPs, I think you will want to get some orthogonal measure of whether they are accurate. It probably makes sense to look at the reads data for some of these sites in a tool like IGV to get a feel for whether they look reliable or not.

One nice thing about DeepVariant is that the quality scores for variants calls are generally normally distributed and predict the human variant quality confidence quite well. One approach you can take is to see what the distribution of DeepVariant quality scores is for the variants you know are real and see whether the new variants have a similar confidence distribution.

**Comment by harrismia** [comment]
We are also interested in exploring the possibility of using DeepVariant to call SNPs in bacterial genomes.  For our current pipeline we are using  BWA to map reads to the reference and then PILON from the Broad to call variants.  Specifically we are working on the Tuberculosis genome.

**Comment by yingeddi2008** [comment]
Thanks Michael, I'd love to know what conclusions about how the accuracy
and background noise detection you have on the TB genome. If it is not too
much trouble, can you keep me posted? Or you have some blog/post or paper I
can follow up on?

You guys are totally rocking it!! Very exciting study!!

**Comment by pichuan** [comment]
I'm happy to see that this forum has sparked potential research collaborations!
I'm going to close this issue for now so it's easier for me to track what issues still need our attention.

Feel free to post further updates on this topic if you like. If you have more questions for the DeepVariant team, also feel free to open more issues. Thanks!
