### ISSUE TITLE
Localize BED file passed via --region flag

### ISSUE THREAD

**Issue by nmousavi** [google/deepvariant#119]
Context: issue #116 

Htslib integration with GCS doesn't load app default credential from worker, and thus is only able to read from public bucket. The workaround is to localize BED file into VM worker prior running make_examples.

**Comment by nmousavi** [comment]
The fix is done, and will be included in the next release. 

For the ref: Htslib is not able to read from private gcs bucket and there is a TODO for it. 

https://github.com/samtools/htslib/blob/9cd85ab512a74fe42af31fc6321c70203d161ed6/hfile_gcs.c#L75

**Comment by pichuan** [comment]
This fixed is included in v0.7.2 release:
https://github.com/google/deepvariant/releases/tag/v0.7.2
