### ISSUE TITLE
Job failed with error (reason: FAILED_PRECONDITION) 

### ISSUE THREAD

**Issue by phhsieh1329** [google/deepvariant#120]
Dear Deepvariant team,

I was attempting to run Deepvariant on GCP by following the sample scripts from the tutorials, but it failed. I have checked the configuration regarding the Compute Engine quota and it should meet the requirements (i.e. CPU, Persistent Disk and In-use IP addresses).

The error message from the log is like:
"RuntimeError: Job failed with error "run": operation "projects/deepvariant-phh/operations/7761698599878123803" failed: executing pipeline: Execution failed: action 2: unexpected exit status 1 was not ignored (reason: FAILED_PRECONDITION)"

I have read some of the related discussed issues but still can't solve my problem. The log files and my script file are attached. Your help is appreciated. 

[staging_temp%2Frunner_logs_20181118_014355.log](https://github.com/google/deepvariant/files/2592663/staging_temp.2Frunner_logs_20181118_014355.log)
[log.txt](https://github.com/google/deepvariant/files/2592666/log.txt)

[script.txt](https://github.com/google/deepvariant/files/2592665/script.txt)

**Comment by pichuan** [comment]
Hi, can you provide the worker log as well?
(See this example : https://github.com/google/deepvariant/issues/118#issuecomment-437114999 )

**Comment by phhsieh1329** [comment]
Dear Pi-Chuan,

Thanks for pointing out the worker log files since I didn't realize the files are log files. 
It is really helpful!

The error comes from the inappropriate bam index file name I used (*.bai instead of *.bam.bai) as the log file describes: 
CommandException: No URLs matched: gs://input_bam/IO_045.sam_sorted_dedup.bam.bai

After changing the bam index file name, the pipeline seems to work now! 
Thank you so much for your help.
