### ISSUE TITLE
Will Deepvariant work for non-diploid genome?

### ISSUE THREAD

**Issue by phhsieh1329** [google/deepvariant#121]
Dear Deepvariant team,

My collection of data contains samples with non-diploid genomes. As Deepvariant model was built and trained based on diploid data, I am wondering if the team have evaluated how Deepvariant performs on non-diploid dataset (e.g. triploid or tetrapliod)? Thanks.

**Comment by pichuan** [comment]
Hi,
Our team has not used or trained DeepVariant on non-diploid data.
I think a similar question might have been asked before, so it's worth doing a quick search to see if there are relevant ideas. But nothing specific from the DeepVariant team. Thanks.
