### ISSUE TITLE
Building DeepVariant on Power 8 with nvidia-docker

### ISSUE THREAD

**Issue by DiableJambe** [google/deepvariant#122]
I am trying to install DeepVariant on an IBM Power 8 system within a docker container.

The docker container has the following Bazel version installed: 0.15.0- (https://github.com/bazelbuild/bazel/releases/tag/0.15.0) 

I installed tensorflow r1.11 from source inside the docker container for CPU-only execution. This same source-code is placed so that it is seen by the build-prereq.sh script.

I set the `export DV_USE_PREINSTALLED_TF=1`.

In settings.sh, I changed DV_BAZEL_VERSION to DV_BAZEL_VERSION="0.15.0-" (to match the bazel version above). I also removed the corei7 option in DV_COPT_FLAGS. 

In build-prereq.sh, I hard-coded the following in: `DV_PLATFORM="ubuntu-16"`, since `lsb_release` didn't match the case statement conditions there. The following is the result `lsb_release`.
root@1f07cee05809:~/deepvariant# lsb_release
LSB Version:    core-9.20160110ubuntu0.2-noarch:core-9.20160110ubuntu0.2-ppc64el:security-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-ppc64el

After these changes, build-prereq.sh runs fine. However, build_and_test.sh fails with the following error:
(03:21:40) ERROR: /root/deepvariant/third_party/nucleus/protos/BUILD:424:1: ClifProtoLibraryGeneration third_party/nucleus/protos/reads_pyclif.h failed (Exit 2): proto failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/8422bf851bfac3671a35809acde131a7/execroot/com_google_deepvariant && \
  exec env - \
  bazel-out/host/bin/external/clif/proto -c bazel-out/ppc-opt/genfiles/third_party/nucleus/protos/reads_pyclif.cc -h bazel-out/ppc-opt/genfiles/third_party/nucleus/protos/reads_pyclif.h '--strip_dir=bazel
-out/ppc-opt/genfiles' '--source_dir='\''.'\''' third_party/nucleus/protos/reads.proto)
bazel-out/host/bin/external/clif/proto: 3: bazel-out/host/bin/external/clif/proto: __requires__: not found
bazel-out/host/bin/external/clif/proto: 4: bazel-out/host/bin/external/clif/proto: import: not found
bazel-out/host/bin/external/clif/proto: 5: bazel-out/host/bin/external/clif/proto: import: not found
bazel-out/host/bin/external/clif/proto: 6: bazel-out/host/bin/external/clif/proto: from: not found
bazel-out/host/bin/external/clif/proto: 9: bazel-out/host/bin/external/clif/proto: Syntax error: "(" unexpected (expecting "then")

It would be great if I can get some help on this. Thanks!

**Comment by pichuan** [comment]
We built CLIF for a few versions of Linux. By hard coding DV_PLATFORM it would mean you're using that version. Unfortunately we don't support all versions of Unix. You can see if you can build clif yourself.
This is unfortunately outside our support scope right now.
