### ISSUE TITLE
Import meta graph error

### ISSUE THREAD

**Issue by koido** [google/deepvariant#127]
Hi,

I want to load pre-trained DeepVariant model (DeepVariant-inception_v3-0.7.0+data-wgs_standard).
However, loading model.ckpt.meta file produced some error.
Analyzing environment was google collaboratory (python2, GPU).

My purpose is to use the pre-trained model in Keras.

I used model.ckpt.meta file as follows:

`import tensorflow as tf`
`pretrian_model_path='/content/drive/My Drive/DeepVariant-inception_v3-0.7.0+data-wgs_standard'`
`saver = tf.train.import_meta_graph(pretrian_model_path + '/model.ckpt.meta', clear_devices=True)`

This produced:

> ValueErrorTraceback (most recent call last)
<ipython-input-9-8883daf94bd3> in <module>()
      1 with tf.Session() as sess:
----> 2   saver = tf.train.import_meta_graph(pretrian_model_path + '/model.ckpt.meta', clear_devices=True)
>
>/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in import_meta_graph(meta_graph_or_file, clear_devices, import_scope, **kwargs)
   1672   """  # pylint: disable=g-doc-exception
   1673   return _import_meta_graph_with_return_elements(
-> 1674       meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
   1675 
   1676 
>
>/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.pyc in _import_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, import_scope, return_elements, **kwargs)
   1694           import_scope=import_scope,
   1695           return_elements=return_elements,
-> 1696           **kwargs))
   1697 
   1698   saver = _create_saver_from_imported_meta_graph(
>
>/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.pyc in import_scoped_meta_graph_with_return_elements(meta_graph_or_file, clear_devices, graph, import_scope, input_map, unbound_inputs_col_name, restore_collections_predicate, return_elements)
    804         input_map=input_map,
    805         producer_op_list=producer_op_list,
--> 806         return_elements=return_elements)
    807 
    808     # Restores all the other collections.
>
>/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.pyc in new_func(*args, **kwargs)
    486                 'in a future version' if date is None else ('after %s' % date),
    487                 instructions)
--> 488       return func(*args, **kwargs)
    489     return tf_decorator.make_decorator(func, new_func, 'deprecated',
    490                                        _add_deprecated_arg_notice_to_docstring(
>
>/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.pyc in import_graph_def(graph_def, input_map, return_elements, name, op_dict, producer_op_list)
    420       except errors.InvalidArgumentError as e:
    421         # Convert to ValueError for backwards compatibility.
--> 422         raise ValueError(str(e))
    423 
    424     # Create _DefinedFunctions for any imported functions.
>
>ValueError: NodeDef expected inputs 'float, int32' do not match 1 inputs specified; Op<name=CrossReplicaSum; signature=input:T, group_assignment:int32 -> output:T; attr=T:type,allowed=[DT_BFLOAT16, DT_FLOAT]>; NodeDef: {{node CrossReplicaSum}} = CrossReplicaSum[T=DT_FLOAT, _class=["loc:@gradi...s_grad/mul"], _output_shapes=[[3,3,6,32]], _tpu_replicate="cluster"](gradients/AddN_109)

Best Regards,

Masaru

**Comment by pichuan** [comment]
Hi Masaru,
we have not tried loading the model checkpoints this way before.
Since it's a colab, can you share the colab so we can try it out as well?

I might have some older colab lying around that loads the checkpoint, but probably not using Keras. Would that be helpful? If so I can try to find it again.

Thanks.

**Comment by koido** [comment]
Hi,

Thank you for your comments.
I prepared the colab in https://colab.research.google.com/drive/1eYpUciVLEwR5YujPJ2NyH0hfRRCZ3Vg2 .

Actually, I'm basically a Pytorch user and a beginner of Keras and tensorflow. 
Then if i/we can use DeepVariant easily, I think it would be helpful for many users!

Best.

**Comment by pichuan** [comment]
I assign this to my self, but --
since we're not using Keras in DeepVariant, it will take a uncertain amount time for me to prioritize this on my list of things. I will also open an internal bug to track, but this is something that we likely won't be able to help with in the short term.

If you want to take a look at how we load the checkpoint, you can find examples in the inference code here:
https://github.com/google/deepvariant/blob/r0.7/deepvariant/call_variants.py#L346
And for training, in order to start from a checkpoint, you can see code in this:
https://github.com/google/deepvariant/blob/r0.7/deepvariant/modeling.py#L408

We use the Estimator API. So, another possibility to find more information for things like this:
https://github.com/keras-team/keras/issues/5273
(I don't know if this one helps, but worth a look)

I will keep this issue open for a while. Please feel free to share back if you find anything. I'll also update if I find anything useful.

**Comment by koido** [comment]
Thank you so much.
In my current understanding, if I use the pre-trained parameters for DeepVariant in Keras or other deep learning frameworks, building the equivalent model in each library is required.
Anyway, I'll try which approach is the easiest for my aim.

Please let another confirmation.
For saving the checkpoints "DeepVariant-inception_v3-0.7.0+data-wgs_standard", did you used the function in this?:
https://github.com/google/deepvariant/blob/3c43de4541c45673e30d14daef742fca68fdf69b/deepvariant/testing/tf_test_utils.py#L48

Best.

**Comment by pichuan** [comment]
Hi @koido ,
sorry that it took me a while to get back to this again.
Our training uses the Estimator API, so the place where model checkpoints are saved are actually done by estimator.train:
https://github.com/google/deepvariant/blob/c2167e7c90f016905f309f118eb3897935ee7c5f/deepvariant/model_train.py#L227
And the location where the checkpoints are saved was specified earlier:
https://github.com/google/deepvariant/blob/c2167e7c90f016905f309f118eb3897935ee7c5f/deepvariant/model_train.py#L200

The place you pointed to was not related to the main code - it is in the test util, and it is used to create a fake checkpoint so we can do unit tests.

**Comment by koido** [comment]
Hi @pichuan,

Thank you very much.

I got to understand your excellent codes of deepvariant by learning tensorflow slim and Estimator API.
Although I still think that this topic is very useful for many users (deep learning beginners), please close this issue if your prioritization in list of things is low.

Best regards,

Masaru

**Comment by pichuan** [comment]
Hi Masaru,
I've filed an internal issue to track - we'll keep usability for beginners in mind for future API change.
