### ISSUE TITLE
make_examples: ValueError: Reference contigs span ### bases but only 0 bases (0.00%) were found

### ISSUE THREAD

**Issue by mosh305** [google/deepvariant#128]
Hi,
I'm trying to train the network on my local machine with long reads but I get this error when trying to make examples out of the reads:

```
2018-12-10 17:04:46.071140: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I1210 17:04:46.071218 140037815584512 genomics_reader.py:174] Reading project-retraining/testdata/aligned_reads.bam with NativeSamReader
I1210 17:04:46.072298 140037815584512 make_examples.py:1024] Preparing inputs
2018-12-10 17:04:46.072535: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I1210 17:04:46.072572 140037815584512 genomics_reader.py:174] Reading project-retraining/testdata/aligned_reads.bam with NativeSamReader
[W::bcf_hdr_register_hrec] An INFO field has no Type defined. Assuming String
[W::bcf_hdr_register_hrec] An INFO field has no Number defined. Assuming '.'
[W::bcf_hdr_register_hrec] An INFO field has no Type defined. Assuming String
[W::bcf_hdr_register_hrec] An INFO field has no Number defined. Assuming '.'
I1210 17:04:46.072917 140037815584512 genomics_reader.py:174] Reading project-retraining/testdata/variants.vcf.gz with NativeVcfReader
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1120, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1110, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1025, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 945, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 455, in _ensure_consistent_contigs
    min_coverage_fraction)
  File "/tmp/Bazel.runfiles_1gjjersh/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 527, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 4641652 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "NC_000913.3" is 4641652 bp and IS MISSING
```

My reference is "E.coli K-12 substr. MG1655" from NCBI - https://www.ncbi.nlm.nih.gov/nuccore/NC_000913.3
And my reads are from PacBio - https://github.com/PacificBiosciences/DevNet/wiki/E-coli-K12-MG1655-Resequencing
I used the reference from NCBI as a REF, the reads from PacBio as BAM (also tried to index the bam again), and the variants as BED and VCF (also tried to index the vcf again).

I read in many issues here that the name of the contigs in the bai, fai, bed and vcf should be the same so I tried to change them all to "NC_000913.3" but still no help. I'm not sure what I'm doing wrong, can anyone help?

Thank you

**Comment by akolesnikov** [comment]
Most likely what happens is that your BAM file (or truth file) has contig names that do not match contig names of the reference. Could you list all the arguments you used for running make_examples? Also, could you print the header of 'project-retraining/testdata/aligned_reads.bam'?

**Comment by mosh305** [comment]
my command line for running make_examples was:

```
python bin/make_examples.zip \
	  --mode training   \
	  --ref "project-retraining/testdata/sequence.fasta"   \
	  --reads "project-retraining/testdata/aligned_reads.bam" \
	  --examples "project-retraining/training-examples/training_set.with_label.tfrecord.gz" \
	  --confident_regions "project-retraining/testdata/variants.bed" \
	  --truth_variants "project-retraining/testdata/variants.vcf.gz" > "project-retraining/logs/make_examples.log" 2>&1
```

and the header of the `aligned_reads.bam` file is:

```
@HD	VN:1.3
@SQ	SN:NC_000913.3	LN:4639675	M5:05dc7a37701cdc6bcf154344a227983d
@RG	ID:343cd2783e	SM:c100278822550000001523007907041295	PU:m120131_103014_sidney_c100278822550000001523007907041295_s1_p0	PL:PacBio_RS	DT:2012-01-31T10:30:14
@PG	ID:/mnt/secondary/Smrtanalysis/opt/smrtanalysis/analysis/bin/SAMIO.py	VN:1.2.0.SF	CL:-b -o /mnt/secondary/Smrtanalysis/opt/smrtanalysis/common/jobs/034/034822/data/aligned_reads.sam -p /mnt/secondary/Smrtanalysis/opt/smrtanalysis/common/references/ecoli /mnt/secondary/Smrtanalysis/opt/smrtanalysis/common/jobs/034/034822/data/aligned_reads.cmp.h5
@CO	READS:39496
```

**Comment by akolesnikov** [comment]
Let's try to output contig names from all 3 input files. In order to do that you would need to modify make_examples.py:
Insert the code from the [gist](https://gist.github.com/akolesnikov/9a4b019e89087dc21cf9ba0b12eece00) at line 488 (right before calling validate_reference_contig_coverage) in make_examples.py.

You would need to clone the source code first:
```
git clone https://github.com/google/deepvariant.git
cd deepvariant/
./build-prereq.sh
```
Once you modify make_exmaples.py run ./build_release_binaries.sh from deepvariant directory to rebuild binaries.

Then run make_examples and check the output.

**Comment by akolesnikov** [comment]
Once you build new binaries make_examples.zip can be found at ./bazel-bin/deepvariant/make_examples.zip (the path is relative to your deepvariant directory)

**Comment by mosh305** [comment]
@akolesnikov This is what I get in the terminal when trying to build the binaries even without modifying the `make_examples.py` file:

```
(18:45:18) WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
(18:45:18) INFO: Current date is 2018-12-17
(18:45:40) INFO: Analysed target //:binaries (88 packages loaded).
(18:45:40) INFO: Found 1 target...
(18:45:40) ERROR: missing input file '@clif//:clif/bin/pyclif_proto'
(18:45:41) ERROR: /home/moshvm/DeepVariant/deepvariant/third_party/nucleus/protos/BUILD:424:1: //third_party/nucleus/protos:reads_pyclif_clif_rule: missing input file '@clif//:clif/bin/pyclif_proto'
Target //:binaries failed to build
(18:45:41) ERROR: /home/moshvm/DeepVariant/deepvariant/third_party/nucleus/protos/BUILD:424:1 1 input file(s) do not exist
(18:45:41) INFO: Elapsed time: 22.910s, Critical Path: 0.43s
(18:45:41) INFO: 0 processes.
(18:45:41) FAILED: Build did NOT complete successfully
(18:45:43) WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
(18:45:43) INFO: Current date is 2018-12-17
(18:45:48) INFO: Analysed target //:licenses_zip (14 packages loaded).
(18:45:48) INFO: Found 1 target...
Target //:licenses_zip up-to-date:
  bazel-genfiles/licenses.zip
(18:45:49) INFO: Elapsed time: 6.388s, Critical Path: 0.10s
(18:45:49) INFO: 0 processes.
(18:45:49) INFO: Build completed successfully, 1 total action
```

**Comment by akolesnikov** [comment]
You already printed contigs for your BAM file. You have one contig there: NC_000913.3
Reference and truth files are text format so you just need to peek inside. In VCF file first lines should contain the list of contigs. Something like this:
```
##contig=<ID=chr1,length=248956422>
```

Make sure that reference, VCF and BED contain contig 'NC_000913.3'

**Comment by mosh305** [comment]
@akolesnikov I can see that my VCF file doesn't have a line that resemble the line you wrote.
I attach the original `variants.vcf` and `variants.bed` files, I tried to change the name 'chr' to 'NC_000913.3' in both of them but that didn't work.
Maybe I need to insert a line similar to the one you wrote to the VCF file?

[variants.vcf.txt](https://github.com/google/deepvariant/files/2687815/variants.vcf.txt)
[variants.bed.txt](https://github.com/google/deepvariant/files/2687816/variants.bed.txt)

**Comment by akolesnikov** [comment]
In your variants.vcf.txt and variants.bed.txt contigs have name 'chr' when BAM file has contig name 'NC_000913.3'
Contig names should match. Looking at [VCF Specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf) it looks like '#contig' header is optional, but I think Nucleous library (that is used by DeepVariant to read VCF) relies on that field.

**Comment by mosh305** [comment]
> In your variants.vcf.txt and variants.bed.txt contigs have name 'chr' when BAM file has contig name 'NC_000913.3'
> Contig names should match. Looking at [VCF Specs](https://samtools.github.io/hts-specs/VCFv4.2.pdf) it looks like '#contig' header is optional, but I think Nucleous library (that is used by DeepVariant to read VCF) relies on that field.

@akolesnikov first, thank you very much for your help!
I renamed all the contig names in the VCF and BED to "NC_000913.3" and added a "##contig" header to the VCF file, I indexed again the FASTA, BAM and BED files, but it still doesn't work.

I used the command `samtools faidx sequence.fasta` to create `sequence.fasta.fai` file.
I used the command `samtools index aligned_reads.bam` to create `aligned_reads.bam.bai` file.
And I used the command `tabix -p vcf variants.vcf.gz` to create `variants.vcf.gz.tbi` file.

This is my command line:

```
python bin/make_examples.zip \
  --mode training \
  --ref "project-retraining/testdata/sequence.fasta" \
  --reads "project-retraining/testdata/aligned_reads.bam" \
  --examples "project-retraining/training_examples" \
  --confident_regions "project-retraining/testdata/variants.bed" \
  --truth_variants "project-retraining/testdata/variants.vcf.gz" > "project-retraining/logs/make_examples.log" 2>&1
```

and I get the same ValueError as before (from `make_examples.log` file):

```
2018-12-18 13:54:44.725754: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I1218 13:54:44.725832 140314139805440 genomics_reader.py:174] Reading project-retraining/testdata/aligned_reads.bam with NativeSamReader
I1218 13:54:44.726912 140314139805440 make_examples.py:1024] Preparing inputs
2018-12-18 13:54:44.727156: W third_party/nucleus/io/sam_reader.cc:531] Unrecognized SAM header type, ignoring: 
I1218 13:54:44.727194 140314139805440 genomics_reader.py:174] Reading project-retraining/testdata/aligned_reads.bam with NativeSamReader
[W::bcf_hdr_register_hrec] An INFO field has no Type defined. Assuming String
[W::bcf_hdr_register_hrec] An INFO field has no Number defined. Assuming '.'
[W::bcf_hdr_register_hrec] An INFO field has no Type defined. Assuming String
[W::bcf_hdr_register_hrec] An INFO field has no Number defined. Assuming '.'
[W::hts_idx_load2] The index file is older than the data file: project-retraining/testdata/variants.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: project-retraining/testdata/variants.vcf.gz.tbi
I1218 13:54:44.727533 140314139805440 genomics_reader.py:174] Reading project-retraining/testdata/variants.vcf.gz with NativeVcfReader
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1120, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1110, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1025, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 945, in processing_regions_from_options
    options.min_shared_contigs_basepairs)
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 455, in _ensure_consistent_contigs
    min_coverage_fraction)
  File "/tmp/Bazel.runfiles_qt8ycuy4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 527, in validate_reference_contig_coverage
    ref_bp, common_bp, coverage, format_contig_matches()))
ValueError: Reference contigs span 4641652 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "NC_000913.3" is 4641652 bp and IS MISSING
```

I am attaching here all the files I used (the BAM file is too big so I attach only the header).


[sequence.fasta.txt](https://github.com/google/deepvariant/files/2690298/sequence.fasta.txt)
[sequence.fasta.fai.txt](https://github.com/google/deepvariant/files/2690309/sequence.fasta.fai.txt)
[aligned_reads_header.sam.txt](https://github.com/google/deepvariant/files/2690312/aligned_reads_header.sam.txt)
[variants.bed.txt](https://github.com/google/deepvariant/files/2690313/variants.bed.txt)
[variants.vcf.gz](https://github.com/google/deepvariant/files/2690314/variants.vcf.gz)
[make_examples.log](https://github.com/google/deepvariant/files/2690369/make_examples.log)

**Comment by pichuan** [comment]
Hi @mosh305 
I quickly glanced through the files you have. If you're planning to train, the files you passed to `truth_variants` needs to have `GT` field (providing as true labels to the training examples). I'm not sure if this is the reason why you're having the errors you have. But either way, the variants.vcf.gz file you're providing here won't be the right input for `--truth_variants`.

**Comment by mosh305** [comment]
> Hi @mosh305
> I quickly glanced through the files you have. If you're planning to train, the files you passed to `truth_variants` needs to have `GT` field (providing as true labels to the training examples). I'm not sure if this is the reason why you're having the errors you have. But either way, the variants.vcf.gz file you're providing here won't be the right input for `--truth_variants`.

@pichuan Thank you for pointing that out, I am not so familiar with bioinformatics so I don't really know how to continue from here.
Where can I find the right input for `--truth_variants` for my reference?

**Comment by mosh305** [comment]
@pichuan My goal is to use **long reads** of E.Coli in order to evaluate the variant calling from such type of reads. Most of my knowledge on bioinformatics came from reading the [quick-start](https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-quick-start.md) and [model training](https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-model-training.md) of DeepVariant, and a little on the internet.

From what you wrote to me earlier I understand there's a problem with my `truth_variant` files, since it doesn't have GT fields. In that case what I need to do next so I could run the training successfully?
Do I need to find a different source for the VCF and BED files? Do I need to find new reads too? Do the `truth_variants` and `reads` depend on each other in any way?

I hope this explains my situation.
