### ISSUE TITLE
Convert docker image to singularity

### ISSUE THREAD

**Issue by chrisfleisch** [google/deepvariant#132]
Our cluster environment only allows us to run Singularity containers (due to not running as root) instead of Docker containers. I've been converting the DeepVariant provided docker images to Singularity using version 0.7.0 which worked well. With version 0.7.2 the python imports break due to the location of where the python packages are installed. In version 0.7.0 the python requirements were installed in /usr/local/lib/python2.7/dist-packages/, but now the requirements are installed into /root/.local/lib/python2.7/site-packages/ which does not get copied over into the Singularity container. This might be because of Singularity being designed to run not as root.

Would you be able to change the install location back to /usr/local/lib/python2.7/dist-packages/ or provide working Singularity containers?

**Comment by pichuan** [comment]
Assigning to @nmousavi for some feedback on why this path changed.

**Comment by melkerdawy** [comment]
Is there any update regarding this issue? I am also trying to build a singularity container for deepvariant 0.7.2 and I am producing the same error. Will this be fixed on later versions?

I assume a lot of teams don't have a root access when using HPC. It will be awesome if you add support for building singularity containers in your documentations as this will things a lot easier when using deepvariant on HPC either for calling or training.

**Comment by pichuan** [comment]
@melkerdawy Thanks for checking back.
I talked to @nmousavi a while ago and he didn't recall any changes, but said that he'll look into it. I'll ping him again. I can also spend some time later (I'm currently on vacation).

We're not familiar with Singularity container, and don't currently plan to provide that yet. But we can certainly look into why the installation location changes.

**Comment by melkerdawy** [comment]
@pichuan  Thank you for the quick reply. I will wait for any new updates.

**Comment by melkerdawy** [comment]
Also, @chrisfleisch  is the singularity container you build for version 0.7.0 still working? If so, can you please share with me the definition file you used or any documentation you have about it?

This can be very helpful for me as when I try to build a singularity container for 0.7.0, it gives me the same error in regards of needing access to the path of site-packages

Thanks!

**Comment by chrisfleisch** [comment]
I'm using Singularity 2.6.0. Below is what I've been using for my Singularity.spec file for version 0.7.0 which still works for me. Changing the version number of DeepVariant to 0.7.2 gives me the ImportError: No module named numpy when trying to run make_examples.

```
Bootstrap: localimage
From: deepvariant-0.7.0.simg

# Modified from: https://gist.github.com/pansapiens/717efcdefb51fa0ce1a6abf092bcb2f4
# Install Google Cloud SDK for the gcloud tool, then:
# We grab the official Docker image, push it to a locally running container repo, then get
# Singularity to pull it back.
# docker pull gcr.io/deepvariant-docker/deepvariant:0.7.0
# docker tag gcr.io/deepvariant-docker/deepvariant:0.7.0 localhost:5000/deepvariant:0.7.0
# docker run -d -p 5000:5000 --restart=always --name registry registry:2
# docker push localhost:5000/deepvariant:0.7.0
# sudo SINGULARITY_NOHTTPS=1 singularity pull docker://localhost:5000/deepvariant:0.7.0
#
# Then use that container image to make this customized one
# sudo singularity build deepvariant-custom.simg Singularity.spec

%environment
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    DV_GPU_BUILD=0
    export PATH DV_GPU_BUILD

%apprun download_testdata
    BUCKET="gs://deepvariant"
    DATA_BUCKET="${BUCKET}/quickstart-testdata/*"
    mkdir -p input
    gsutil cp -R "${DATA_BUCKET}" input/

%apprun make_examples
    exec /opt/deepvariant/bin/make_examples \
    --mode calling \
    --ref /dv2/input/ucsc.hg19.chr20.unittest.fasta.gz \
    --reads /dv2/input/NA12878_S1.chr20.10_10p1mb.bam \
    --examples output.examples.tfrecord \
    --regions "chr20:10,000,000-10,010,000"

%apprun call_variants
    exec /opt/deepvariant/bin/call_variants \
    --outfile call_variants_output.tfrecord \
    --examples output.examples.tfrecord \
    --checkpoint /models/wgs/model.ckpt

%apprun postprocess_variants
 exec /opt/deepvariant/bin/postprocess_variants \
    --ref /dv2/input/ucsc.hg19.chr20.unittest.fasta.gz \
    --infile call_variants_output.tfrecord \
    --outfile output.vcf


%runscript
if [ $# -eq 0 ]; then
    echo '''Example Usage:

    # download data to input and models
    singularity run --app download_testdata deepvariant-custom.simg

    # make the examples, mapping inputs
    singularity run --bind input:/dv2/input/ --app make_examples deepvariant-custom.simg

    # call variants, mapping models
    singularity run --app call_variants deepvariant-custom.simg

    # postprocess variants
    singularity run --bind input:/dv2/input/ --app postprocess_variants deepvariant-custom.simg

    # https://github.com/google/deepvariant/blob/master/docs/deepvariant-docker.md
'''
else
    exec "$@"
fi


%post
    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
    apt-get -y update && apt-get install -y google-cloud-sdk parallel wget
    rm -rf /var/lib/apt/lists/*

    # https://github.com/google/deepvariant/blob/r0.5/deepvariant/docker/Dockerfile
    BASH_HEADER='#!/bin/bash' && \
    printf "%s\n%s\n" \
        "${BASH_HEADER}" \
        'python /opt/deepvariant/bin/make_examples.zip "$@"' > \
        /opt/deepvariant/bin/make_examples && \
    printf "%s\n%s\n" \
        "${BASH_HEADER}" \
        'python /opt/deepvariant/bin/call_variants.zip "$@"' > \
        /opt/deepvariant/bin/call_variants && \
    printf "%s\n%s\n" \
        "${BASH_HEADER}" \
        'python /opt/deepvariant/bin/postprocess_variants.zip "$@"' > \
        /opt/deepvariant/bin/postprocess_variants && \
    printf "%s\n%s\n" \
        "${BASH_HEADER}" \
        'python /opt/deepvariant/bin/model_train.zip "$@"' > \
        /opt/deepvariant/bin/model_train && \
    printf "%s\n%s\n" \
        "${BASH_HEADER}" \
        'python /opt/deepvariant/bin/model_eval.zip "$@"' > \
        /opt/deepvariant/bin/model_eval && \
    chmod +x /opt/deepvariant/bin/make_examples \
             /opt/deepvariant/bin/call_variants \
             /opt/deepvariant/bin/postprocess_variants \
             /opt/deepvariant/bin/model_train \
             /opt/deepvariant/bin/model_eval

     mkdir -p /models/wgs
     mkdir -p /models/wes
     BIN_VERSION="0.7.0"
     MODEL_VERSION=$BIN_VERSION
     BUCKET="gs://deepvariant"
     MODEL_NAME_WGS="DeepVariant-inception_v3-${MODEL_VERSION}+data-wgs_standard"
     MODEL_NAME_WES="DeepVariant-inception_v3-${MODEL_VERSION}+data-wes_standard"
     MODEL_BUCKET_WGS="${BUCKET}/models/DeepVariant/${MODEL_VERSION}/${MODEL_NAME_WGS}/*"
     MODEL_BUCKET_WES="${BUCKET}/models/DeepVariant/${MODEL_VERSION}/${MODEL_NAME_WES}/*"
     gsutil cp -R "${MODEL_BUCKET_WGS}" /models/wgs/
     gsutil cp -R "${MODEL_BUCKET_WES}" /models/wes/
```

**Comment by melkerdawy** [comment]
@chrisfleisch  this is really awesome! thanks a lot. you made my life a lot easier now :D 

I will try to modify this definition file to be working on training too and I will share it here. maybe it will help somebody with the same problem I am having.

**Comment by chrisfleisch** [comment]
Singularity recommends to install packages, programs, data, and files into operating system locations (e.g. not /home, /tmp , or any other directories that might get commonly binded on (like /root)). It would be great if the DeepVariant container would work nicely with Singularity in this way.

**Comment by pichuan** [comment]
Thanks @nmousavi @chrisfleisch @melkerdawy 
For now, please see if the workaround that @nmousavi suggested can be used.

@chrisfleisch I'm actually already planning to take a closer look at the way we build the docker image. Thanks for your feedback. I will take this into account when I do that. I'll add the information in your last comment to our internal tracking bug. Note that this might be a little low on my priority list. But I'll try to get to it soon, and I might check back with you directly to make sure things work for you.
I'll leave this GitHub issue open!!

**Comment by pgrosu** [comment]
I think the easiest way to do it is as follows:
1. Install VirtualBox on your laptop, then Ubuntu, then Docker.
2. Pull the DeepVariant image, and then follow the instructions at the following link on how to modify the image and committing it:
  https://www.techrepublic.com/article/how-to-commit-changes-to-a-docker-image/
3. Perform `docker save` to be able to transfer it so you can convert it to a Singularity image - with a link provided below on how to use `docker save`:
   https://docs.docker.com/engine/reference/commandline/save/

Hope it helps,
~p

**Comment by pichuan** [comment]
Hi @chrisfleisch 
I want to follow up on this issue. The path change earlier was actually due to this commit back in Oct 2018:
https://github.com/google/deepvariant/commit/f3207bb2e4db50f858343b97fa8bdec0fb908ab7

Because we added `--user` to pip install (even when the user is root), that's what caused the change you observed.

In our upcoming release, we will plan to change this so that we won't pip install with `--user` when the user is root, I have tested internally that our new docker image will be convertible to a singularity image. I will also plan to document the steps of the conversion, which is basically what you mentioned in in earlier comment in this thread.

Thank you for pointing out this issue. I will close this issue now. When v0.8.0 comes out, if you're still encountering any issues, please feel free to file another issue.

**Comment by pichuan** [comment]
@chrisfleisch 
We have released v0.8.0 today :)

This time, I made sure to try out Singularity as well. Here are some my personal notes when I tried to pull our Docker image and build Singularity image, based on the suggestion on your comment above.

I'm still new to Singularity, so I'd really appreciate more feedback if any of the following doesn't make sense, or if any of these can be improved to be more similar to what users are used to.

Once this becomes more mature (and if they become a popular use case), our team can consider adding them for official support in the future as well.

------

# @pichuan 's notes on building DeepVariant Singularity images for CPU and GPU

If you don't have singularity on your computer, install it first:
https://singularity.lbl.gov/install-linux

Once you do, you can pull the DeepVariant Docker image and convert it to a Singularity image.

## CPU image

```
sudo docker pull gcr.io/deepvariant-docker/deepvariant:0.8.0
sudo docker tag gcr.io/deepvariant-docker/deepvariant:0.8.0 localhost:5000/deepvariant:latest
sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo docker push localhost:5000/deepvariant:latest
SINGULARITY_NOHTTPS=1 singularity build deepvariant.simg docker://localhost:5000/deepvariant:latest
```

To run [Quick Start](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md), instead of using the docker command, you can use this command instead:

```
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz   
```
(The extra flags for singularity was added because of the locale issue: https://github.com/BioContainers/containers/issues/206#issuecomment-448698033)

## GPU image
```
sudo nvidia-docker pull gcr.io/deepvariant-docker/deepvariant_gpu:0.8.0
sudo nvidia-docker tag gcr.io/deepvariant-docker/deepvariant_gpu:0.8.0 localhost:5000/deepvariant_gpu:latest
sudo nvidia-docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo nvidia-docker push localhost:5000/deepvariant_gpu:latest
SINGULARITY_NOHTTPS=1 singularity build deepvariant_gpu.simg docker://localhost:5000/deepvariant_gpu:latest
```

Running through Quick Start just to make sure nothing wrong:
```
singularity -s exec --nv -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant_gpu.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz   
```

I do see this issue though:
https://github.com/sylabs/singularity/issues/1916
with the
```
awk: warning: escape sequence `\.' treated as plain `.'
```
messages.

**Comment by chrisfleisch** [comment]
This is fantastic! Thank you

**Comment by williamrowell** [comment]
I converted the new 0.8.0 release docker to a singularity image on a Digital Ocean Centos 7 droplet and took notes, in case it's useful to anyone else.  The instructions were based on [the notes](https://github.com/google/deepvariant/issues/132#issuecomment-482430728) from @pichuan above, but includes instructions for installing docker, nvidia-docker, and singularity, as well as parameters specific to singularity v3.1.1.

```
# install docker
sudo yum check-update
curl -fsSL https://get.docker.com/ | sh

# install nvidia-docker
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | \
  sudo tee /etc/yum.repos.d/nvidia-docker.repo
sudo yum install -y nvidia-docker2
semanage fcontext -a -f f -t container_runtime_exec_t -s system_u /usr/bin/nvidia-docker
sudo restorecon -v /usr/bin/nvidia-docker

# start docker
sudo systemctl start docker
sudo systemctl status docker
sudo systemctl enable docker

# install deps
sudo yum groupinstall -y 'Development Tools' && \
  sudo yum install -y epel-release && \
  sudo yum install -y golang openssl-devel libuuid-devel libseccomp-devel squashfs-tools
echo 'export GOPATH=${HOME}/go' >> ~/.bashrc && \
  echo 'export PATH=/usr/local/go/bin:${PATH}:${GOPATH}/bin' >> ~/.bashrc && \
  source ~/.bashrc

# install singularity
mkdir -p ${GOPATH}/src/github.com/sylabs && \
  cd ${GOPATH}/src/github.com/sylabs && \
  git clone https://github.com/sylabs/singularity.git && \
  cd singularity
git checkout v3.1.1
cd ${GOPATH}/src/github.com/sylabs/singularity && \
  ./mconfig && \
  cd ./builddir && \
  make && \
  sudo make install
  
DVVER=0.8.0
# make deepvariant CPU image
sudo docker pull gcr.io/deepvariant-docker/deepvariant:${DVVER}
sudo docker tag gcr.io/deepvariant-docker/deepvariant:${DVVER} localhost:5000/deepvariant:latest
sudo docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo docker push localhost:5000/deepvariant:latest
singularity build --nohttps deepvariant.${DVVER}.simg docker://localhost:5000/deepvariant:latest
  
# make deepvariant GPU image
sudo nvidia-docker pull gcr.io/deepvariant-docker/deepvariant_gpu:${DVVER}
sudo nvidia-docker tag gcr.io/deepvariant-docker/deepvariant_gpu:${DVVER} localhost:5000/deepvariant_gpu:latest
sudo nvidia-docker run -d -p 5000:5000 --restart=always --name registry registry:2
sudo nvidia-docker push localhost:5000/deepvariant_gpu:latest
singularity build --nohttps deepvariant_gpu.${DVVER}.simg docker://localhost:5000/deepvariant_gpu:latest
```

**Comment by kokyriakidis** [comment]
@williamrowell WOW, this is really helpful! THANK YOU very much!

**Comment by drtamermansour** [comment]
We created a CPU image on an Amazon instance as described here and the example code was running fine. Then we tried to use the same image on a super computer (where we do not have root privileges), we get this error:  

singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/    deepvariant.simg   /opt/deepvariant/bin/run_deepvariant   --model_type=WGS   --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta   --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam   --regions "chr20:10,000,000-10,010,000"   --output_vcf=output.vcf.gz   --output_gvcf=output.g.vcf.gz

***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/mnt/gs18/scratch/users/mansourt/Tamer2/kerdawy/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/mnt/gs18/scratch/users/mansourt/Tamer2/kerdawy/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

ImportError: No module named _multiarray_umath
ImportError: No module named _multiarray_umath
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-04-14 11:40:35.568961: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

real    0m2.359s
user    0m0.767s
sys     0m0.949s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/mnt/gs18/scratch/users/mansourt/Tamer2/kerdawy/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/mnt/gs18/scratch/users/mansourt/Tamer2/kerdawy/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}' returned non-zero exit status 1

**Comment by pichuan** [comment]
@drtamermansour I have not tried saving an image and running it somewhere I don't have root permission. I'll have to think about how to test that better. But before I do that, can I have you provide a few more information, such as:
What is the OS version of the super computer you're on, and what is the singularity version (`singularity --version`) on your AWS machine and your super computer?

Thanks!

**Comment by drtamermansour** [comment]
@pichuan Thank you for taking the time to help on this 
The super computer has an OS CentOS Linux release 7.6.1810 (LSB Version: core-4.1-amd64:core-4.1-noarch) and singularity version 2.5.2
I created the image on Amazon instance with Ubuntu 16.04. I tried using singularity version 2.5.2 & 2.6.0 but both did not help

**Comment by williamrowell** [comment]
For comparison, I created images on Centos 7 using singularity 3.1.1, and I'm running the images on Centos 6 and Lentos 7 using singularity 3.0.1.
