### ISSUE TITLE
training using bioconda build 

### ISSUE THREAD

**Issue by melkerdawy** [google/deepvariant#139]
Hello team,

First, i really want to thank you for your gigantic effort in building and documenting deepvariant. I personally learned (and still learning) a lot from you.

I am interested in training deepvariant on a cluster with no root privileges, so the docker image is not an option for me. Conda is my most efficient way to go, however, I am having the same I am having the exact same error described in  issue #137 Is there is any update in regards of this error?

My other question is the training scripts available on the conda build or not? If not, what do you think is the best way to go with training if I have no root privileges?  

thank you again!

**Comment by chapmanb** [comment]
Thanks much for this report. For the conda issue, the short answer might be that you're using a python 3 environment rather than python 2 (https://github.com/google/deepvariant/issues/137#issuecomment-452831730). Does tha thelp explain the issue and get things working for you?

**Comment by melkerdawy** [comment]
Thanks for the reply. To be honest, things did not get working till now. I dont think you can help me in this issue more than this. I left it to my supervisor to sort it out.

I just want to a confirmation that training scripts like model_train.zip and model_eval.zip is available in the conda build in order to not invest more time into sorting the error out without a reason. 

Thanks so much again. You can close the issue now please.

**Comment by pichuan** [comment]
I'm closing this issue now. If there more we can help with, please feel free to open another issue.
