### ISSUE TITLE
ValueError: Not found: Could not open BAM file

### ISSUE THREAD

**Issue by hmkim** [google/deepvariant#141]
Hi, I got the error in below.

```
# docker run \
   -v ${HOME}:${HOME} \
   gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
   /opt/deepvariant/bin/make_examples \
   --logging_level DEBUG \
   --mode calling   \
   --ref "${REF}"   \
   --reads /data/home/dhflanrnr/Deep_data/Bam_data/sample.printrecal.bam \
   --examples "${OUTPUT_DIR}/examples.tfrecord.gz"
```

> [E::hts_open_format] Failed to open file /data/home/dhflanrnr/Deep_data/Bam_data/sample.printrecal.bam
> Traceback (most recent call last):
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1205, in <module>
>     tf.app.run()
>   File "/root/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1156, in main
>     options = default_options(add_flags=True, flags_obj=FLAGS)
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 287, in default_options
>     with sam.SamReader(flags_obj.reads) as sam_reader:
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 211, in __init__
>     self._reader = self._native_reader(input_path, **kwargs)
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 249, in _native_reader
>     return NativeSamReader(input_path, **kwargs)
>   File "/tmp/Bazel.runfiles_VAS8eS/runfiles/com_google_deepvariant/third_party/nucleus/io/sam.py", line 227, in __init__
>     random_seed=random_seed))
> ValueError: Not found: Could not open /data/home/dhflanrnr/Deep_data/Bam_data/sample.printrecal.bam

Example BAM  header
![2019-01-15 15 24 32](https://user-images.githubusercontent.com/4966343/51162512-cf83c500-18d9-11e9-900a-24418b2a82cd.png)

My BAM header
![2019-01-15 15 24 38](https://user-images.githubusercontent.com/4966343/51162515-d27eb580-18d9-11e9-9076-b635d17ea87b.png)

How can I solve this issue?

**Comment by sidharthgoel** [comment]
Hi @hmkim - your BAM header looks okay to me.

The first line `[E::hts_open_format] Failed to open file ...` indicates it may be an underlying samtools issue (since that seems to be an error message from htslib/samtools), are there any other lines from the error message, outputted earlier? Assuming that the path is correct, it should work. 

The only thing I can think of with the provided info is to check that you have read permissions on the file.

**Comment by hmkim** [comment]
@sidharthgoel OK, I'll check it.

**Comment by pgrosu** [comment]
@hmkim I'm assuming `${HOME}` is `/data/home/dhflanrnr`.  Can you run an interactive Bash session inside the container - with the `-v ${HOME}:${HOME}` - and see if `${HOME}` directory is preserved inside the container?

**Comment by hmkim** [comment]
@pgrosu  Oh! I see. I'll check it.

Now my colleagues remove them (bam files). so after the restore the bam, I'll try and report it again.

Thank you @sidharthgoel , @pgrosu

**Comment by hmkim** [comment]
Yes, The problem caused by  $HOME variable in bash.
