### ISSUE TITLE
CLIF binary for Ubuntu 18 does not exist

### ISSUE THREAD

**Issue by andrewrech** [google/deepvariant#146]
Should be: `https://storage.googleapis.com/deepvariant/packages/oss_clif.ubuntu-18.latest.tgz`

Not: `https://storage.googleapis.com/deepvariant/packages/oss_clif/oss_clif.ubuntu-18.latest.tgz`

**Comment by gunjanbaid** [comment]
@andrewrech Thanks for reporting this! How are you running DeepVariant? Could you post the full output of the error message you saw because of this issue? Thanks!

**Comment by andrewrech** [comment]
Thank you @gunjanbaid 

I was just building DV from source. I realized the path was wrong and just corrected for my build.

**Comment by gunjanbaid** [comment]
@andrewrech The file has been moved to `https://storage.googleapis.com/deepvariant/packages/oss_clif/oss_clif.ubuntu-18.latest.tgz`, as expected by the script. 

You may want to change your build path back to the original path. The file at `https://storage.googleapis.com/deepvariant/packages/oss_clif.ubuntu-18.latest.tgz` will eventually be removed. Thanks again for reporting this!

**Comment by andrewrech** [comment]
Thanks
