### ISSUE TITLE
Swelling memory usage in training DeepVariant?

### ISSUE THREAD

**Issue by koido** [google/deepvariant#147]
Hi,

I observed that CPU memory usage in training DeepVariant is very high and increased by proceeding training.

I used DeepVariant v0.7.1 via docker.
The tested server (standalone, in house server) has 512GB memory with 56CPU, 8GB swap region without GPU/TPU.
I followed your tutorials and made tfrecords including 241,896 pileup images from our data.

I tested the following 3 patterns of training and observed increasing memory usage in all cases:

- When batch size=32,
　- Training was successfully finished (total 50,000 steps)
　- Memory usage at the end of this training was 268GB
![batch_size32 mem](https://user-images.githubusercontent.com/16730135/52196627-ddf14b00-289f-11e9-90dc-05eff144191d.jpg)
 - When batch size=64 (source code default),
　- At ~16,000 steps, all memory (512 GB) was completely used
　- At ~19,000 steps, all swap region was used (and killed)
![batch_size64 mem](https://user-images.githubusercontent.com/16730135/52196624-ddf14b00-289f-11e9-983a-5dcc3de48227.jpg)
 - When batch size=512 (tutorial default),
　- At ~3,900 steps, all memory (512 GB) was completely used
　- At ~4,200 steps, all swap region was used (and killed)
![batch_size512 mem](https://user-images.githubusercontent.com/16730135/52196626-ddf14b00-289f-11e9-8910-67a7c64b324d.jpg)

Are these swelling memory usage due to tensorflow itself or some memory leak?
I want to know how to prevent these.

Best,

Masaru

**Comment by pgrosu** [comment]
Hi Masaru,

Check out my analysis from a while ago on the link below, and I think you'll see where this is stemming from :)

[Generalized performance analysis between the versions](https://github.com/google/deepvariant/issues/50)

Hope it helps,
Paul

**Comment by koido** [comment]
Hi Paul,

Thanks for your kind comment.
I don't know how to resolve my issue (time-dependent increasing memory usage) by your analysis (CPU usage? I'm sorry for my beginner comment...)

Best,
Masaru

**Comment by pichuan** [comment]
Hi @koido 
thanks for your report. Currently our internal setup as well as [our training tutorial on GitHub](https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-tpu-training-case-study.md) are both done with TPU training. Getting training to work on CPU isn't really a priority of the DeepVariant team right now.  Using the default for the TPU tutorial will likely not work for CPU. (Not just the batch size, but also other hyper parameters as well). It will also likely be too slow to be practical.

Another suggestion:
You might know that the Google Cloud team has a GCP runner here: https://cloud.google.com/genomics/docs/tutorials/deepvariant
Currently this is only for calling variants with pre-trained models. But the Cloud team will be interested in understand more external training use cases, so they can understand whether they can build an analogous training pipeline on GCP. If you're interested in getting in touch with the Cloud team, please reach out to @nmousavi.

I'll close this bug for now. If you have question about training, this might also be a question for the TensorFlow team.
