### ISSUE TITLE
Validating WGS outputs

### ISSUE THREAD

**Issue by ekofman** [google/deepvariant#153]
Hi, for a 168GB bam the make_examples step produces a total of 48 GB of tf records (sharded, so this is split over 64 different files). Does this seem like a reasonable intermediate output load to pass to call_variants?

**Comment by sidharthgoel** [comment]
Hi @ekofman, yes that's a reasonable output size. For reference, our 110 GB BAM produces an intermediate output of 42 GB, during the make_examples step.
