### ISSUE TITLE
Less variants were called than expected with deepvariant 0.5.0 exome model 

### ISSUE THREAD

**Issue by fcunihd** [google/deepvariant#158]
Hi deepvariant developer,
I used deepvariant v0.5.0 for calling variants in exome target regions of a exemplary sequenced sample by using similar commands as described in the exome case study. After successfully executing make_variants, call_variants and post process_variants I ended up with a dataset of about 12,000 called variants in the exome of my sample, rather than the expected 20,000 to 30,000 possible variants in the human exome.
I used the following commands in docker:

python ../binaries/make_examples.zip \
      --mode calling \
      --ref /Volumes/workspace/output_mac8/Homo_sapiens_hg38.fa \
      --reads /Volumes/workspace/output_mac8/Sample_NoIndex_R1.recal.bam \
      --examples /Volumes/workspace/output_mac8/Sample.tfrecord@8.gz \
      --regions /Volumes/workspace/output_mac8/S07604514_Regions_nochr_noheader.bed \
      --gvcf /Volumes/workspace/output_mac8/Sample.gvcf.tfrecord@8.gz \
      --task 0

python ../bin/call_variants.zip \
          --outfile /Volumes/workspace/output_mac8/Sample.vcf.gz \
          --examples /Volumes/workspace/output_mac8/Sample.tfrecord@8.gz \
          --checkpoint ../models/model.ckpt \
          --batch_size 32

python ../bin/postprocess_variants.zip \
             --ref /Volumes/workspace/output_mac8/Homo_sapiens_hg38.fa \
             --infile /Volumes/workspace/output_mac8/Sample.vcf.gz \
             --outfile /Volumes/workspace/output_mac8/Sample.final.vcf.gz

How can I improve the variant calling or what could be a possible mistake, while executing the commands? Could be the reason for receiving less variants, that I used an older deepvariant version?

Many Thanks in advance
Ferdinand

**Comment by AndrewCarroll** [comment]
Hello Ferdinand,

I have a few questions which may help us to understand whether this would be expected or not. First, can you tell me how many variants are Refcall in this sample (zcat Sample.final.vcf.gz | grep RefCall | wc -l) and how many variants are PASS in this sample (zcat Sample.final.vcf.gz | grep PASS | wc -l)

Second, is it possible for you to point me to the capture regions that you used (the S07604514 BED file) or, if that is not possible, for you to tell me how many bases it covers.

Knowing this information will help understand whether the number of variants are within expectations, whether they are a function of something about the sample, or whether there is some other issue to address. Generally, the commands do not seem in error.

Thanks,
Andrew

**Comment by pgrosu** [comment]
Probably it would be better to use version 0.7.2 of DV as there was a bugfix for gVCF creation in 0.5.2 from 0.5.0

**Comment by fcunihd** [comment]
> Hello Ferdinand,
> 
> I have a few questions which may help us to understand whether this would be expected or not. First, can you tell me how many variants are Refcall in this sample (zcat Sample.final.vcf.gz | grep RefCall | wc -l) and how many variants are PASS in this sample (zcat Sample.final.vcf.gz | grep PASS | wc -l)
> 
> Second, is it possible for you to point me to the capture regions that you used (the S07604514 BED file) or, if that is not possible, for you to tell me how many bases it covers.
> 
> Knowing this information will help understand whether the number of variants are within expectations, whether they are a function of something about the sample, or whether there is some other issue to address. Generally, the commands do not seem in error.
> 
> Thanks,
> Andrew

Thanks for your quick response.

I have 1191 RefCall variants and 10972 PASS variants in the final VCF file.  We sequenced the sample NA12878 from the HapMap project, for benchmarking it with hap.py against the GIAB reference data.
As you mentioned we used the Agilent SureSelect Human All Exon V6 r2 Bedfile (S07604514 BED file), which is also attached to this message.


[S07604514_Regions.txt.gz](https://github.com/google/deepvariant/files/2914627/S07604514_Regions.txt.gz)

**Comment by AndrewCarroll** [comment]
Hi Ferdinand,

Thank you for the region files. I was looking through your command, and I think I realize the source of the fewer number of variants. 

In your make examples command, you have --task 0. Your make examples script indicates that there will be 8 shards, but this will only run the first of those shards. You will need to run all 8 tasks (and can do so in parallel).

You can see the way we use gnu parallel in the exome case study script (https://github.com/google/deepvariant/blob/r0.7/scripts/run_wes_case_study_docker.sh)

As a result, with the current way you execute the script, this will only call variants in 1/8 of the examples. 

Please let me know if you have questions about this, or about how to run with the tasks with gnu parallel.

Thanks,
Andrew

**Comment by pichuan** [comment]
Hi @fcunihd , please let us know if Andrew's answer resolved your issue? I'm closing this issue, but if it's not resolved, please feel free to re-open.
