### ISSUE TITLE
No function of Docker container for DeepVariant

### ISSUE THREAD

**Issue by windwang1** [google/deepvariant#16]
Hi，
When I execute the commands nothing happens.
![image](https://user-images.githubusercontent.com/25972546/33919918-27ab53f6-dff6-11e7-8058-bf91b9f6a981.png)

So, i tried unzip this *.zip, then i found this question.
![image](https://user-images.githubusercontent.com/25972546/33920090-0bf36d3c-dff7-11e7-9dc1-860fef3809b2.png)
![image](https://user-images.githubusercontent.com/25972546/33920110-21e2cf02-dff7-11e7-883b-69928107516b.png)
![image](https://user-images.githubusercontent.com/25972546/33920131-3a2a71be-dff7-11e7-85c2-2324e07a9a9a.png)
I used this dockerfile [https://github.com/google/deepvariant/tree/r0.4/deepvariant/docker](url) on my cloud platform(Not GCP).
Is there any problem with my environment?

**Comment by scott7z** [comment]
If you could describe your environment in more detail (which OS, CPU), and the full sequence of operations you performed (copy and paste the text from the terminal), it will help us to diagnose the problem.

**Comment by windwang1** [comment]
Thank you for your reply @scott7z 

CPU and OS infomation:
`uname -a
Linux 6562232b4f47 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
head -n 1 /etc/issue
Ubuntu 16.04.1 LTS \n \l`

First, when I ran a container for deepvariant and executed the `make_examples` command
`./make_examples`
Nothing happened
`python make_examples.zip`
Still nothing happened

`unzip make_examples.zip
cd runfiles/genomics/deepvariant
#Add deepvariant to PYTHONPATH
echo "export PYTHONPATH=\$PYTHONPATH:/opt/deepvariant/bin/runfiles/genomics" >> /root/.bashrc
source /root/.bashrc
python make_examples.py`
Then I got 
"Illegal instruction (core dumped)"

This are dockerfile, run-prereq.sh and setting.sh, for reference.
[Dockerfile.zip](https://github.com/google/deepvariant/files/1554693/Dockerfile.zip)

**Comment by windwang1** [comment]
Thank you for your reply @scott7z

CPU and OS infomation:
`uname -a`
Linux 6562232b4f47 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux 
`head -n 1 /etc/issue`
Ubuntu 16.04.1 LTS \n \l

First, when I ran a container for deepvariant and executed the make_examples command
`./make_examples`
Nothing happened
`python make_examples.zip`
Still nothing happened

`unzip make_examples.zip`
`cd runfiles/genomics/deepvariant` 
#Add deepvariant to PYTHONPATH 
`echo "export PYTHONPATH=\$PYTHONPATH:/opt/deepvariant/bin/runfiles/genomics" >> /root/.bashrc` `source /root/.bashrc` 
`python make_examples.py`
Then I got
"Illegal instruction (core dumped)"

This are dockerfile, run-prereq.sh and setting.sh, for reference.
[Dockerfile.zip](https://github.com/google/deepvariant/files/1554745/Dockerfile.zip)

**Comment by scott7z** [comment]
OK, still trying to follow what is happening.   Can you give us the full sequence of commands you typed to get the docker image and then run it?

You shouldn't have to unzip any files; python knows how to execute them.

**Comment by windwang1** [comment]
This directory here contains `dockerfile` and other files that need to be `ADD` to the image
![image](https://user-images.githubusercontent.com/25972546/33970607-df14b3b2-e0ae-11e7-8aea-0509ae0c9c61.png)
`docker build -f dockerfile -t deepvariant_1214 .`
`Successfully built b829b45a9401`

This directory contains the deepvariant `models` and `quickstart-testdata` files downloaded from [https://console.cloud.google.com/storage/browser/deepvariant](url)
![image](https://user-images.githubusercontent.com/25972546/33970996-1a4e378a-e0b1-11e7-8852-9b63cb477f47.png)
`docker run --name deepvariant_test_1214 -v /***/bioinfo/wangwd/workflow/deepvariant/data:/data -it b829b45a9401 /bin/bash`
Then I `cd /opt/deepvariant/bin/`
![image](https://user-images.githubusercontent.com/25972546/33971209-4789bc8c-e0b2-11e7-833c-95f440712240.png)
`./make_examples \
  --mode calling \
  --ref /data/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta \
  --reads /data/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --examples /data/quickstart-output/examples.tfrecord.gz`
When I finished executing this command, I did not get any result.

**Comment by arostamianfar** [comment]
Thanks for the updates. It looks like you are building a customized docker image. Before we can debug that, could you please confirm whether you can:

- Run quickstart on your machine (without using docker)? https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md
- Run DeepVariant using our provided docker image from gcr.io/deepvariant-docker/deepvariant:0.4.1? https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-docker.md

**Comment by scott7z** [comment]
Also, if you can show us the output of
  cat /proc/cpuinfo
that will help.   It's possible the pre-compiled binaries require a newer CPU than you are using,
which could explain the illegal instruction message.

**Comment by windwang1** [comment]
Cloud Platform CPU Information：
![image](https://user-images.githubusercontent.com/25972546/34021423-c8d9a4a6-e174-11e7-8a3d-a34bf1acd12d.png)

I installed a Ubuntu 16.04.3 virtual machine on my laptop and it works with or without docker @arostamianfar 
Laptop CPU information：
![image](https://user-images.githubusercontent.com/25972546/34021793-a91f9614-e176-11e7-98ad-b3c948578613.png)
![image](https://user-images.githubusercontent.com/25972546/34021800-b6b94d10-e176-11e7-8110-623c2d7a73c4.png)

**Comment by scott7z** [comment]
It looks to me like the first CPU (the cloud platform one) doesn't support AVX,
while the second (your laptop) does.

Our precompiled binarines require that from the CPU, so it looks like you'll need
to run on a different platform, or will need to compile everything from source
(DeepVariant, and Tensorflow, and probably CLIF,).

**Comment by scott7z** [comment]
I'm going to close this issue, since we seem to have gotten to the bottom of it.

**Comment by windwang1** [comment]
Thanks for your help @scott7z  @arostamianfar 
According to your suggestion I compiled DeepVariant, Tensorflow, and CLIF from the source.
But nothing changed, still can not get the result.
Then, I ran on another platform which support AVX2 and got the result.

**Comment by scott7z** [comment]
Did you edit settings.sh?  Look where it says:

export DV_COPT_FLAGS="--copt=-msse4.1 --copt=-msse4.2 --copt=-mavx --copt=-O3"

you have to remove the options your CPU doesn't support.  Something like this, for a minimal case

export DV_COPT_FLAGS=""

or this for something tuned to your particular CPU.

export DV_COPT_FLAGS="--copt=-march=native"

The DV_COPT_FLAGS variable is used by our scripts to pass flags to the build system.
The --copt= construction is a flag for Bazel, the build system that passes flags to the compiler,
The "-march=native" part is a flag for GCC or Clang that says to try to auto-detect the architecture.
So read the GCC manual to see what other options are available.

**Comment by scott7z** [comment]
You'll probably need to do something similar when building Tensorflow, too.

**Comment by windwang1** [comment]
Thanks for your reminder @scott7z 
I ignored what you mentioned.
But for now I do not plan to make any further changes.
I've converted to a platform that supports AVX2 and completed a 'quick-start' test.
