### ISSUE TITLE
build-prereq.sh only checks for a single location of PYCLIF

### ISSUE THREAD

**Issue by aditya-88** [google/deepvariant#160]
I am currently trying to install DeepVariant on Pop!_OS 18.10, which is based on Ubuntu 18.10.
I installed Google CLIF from sources but the "build-prereq.sh" kept complaining that the PYCLIF isn't installed.
On looking into the code of "build-prereq.sh", I found that the code only looks for a single location of PYCLIF:

`if [[ -e /usr/local/clif/bin/pyclif ]];`

While my PYCLIF was installed by default to:

`/usr/local/bin/pyclif`

I suggest, maybe, you could use something similar to Python disutils.spawn ?

Additionally, there is a small mistake in the error message output:

`"CLIF is not installed on this machine and a prebuilt binary is not
unavailable for this platform. Please install CLIF at
https://github.com/google/clif before continuing."`

The error message says, **"not unavailable"**, maybe make it **"unavailable"** or **"not available"**.
A tiny cosmetic error, but can be easily fixed.

Thank you!

**Comment by gunjanbaid** [comment]
Hi @aditya-88, thanks for filing this bug! I will look into both 1) using disutils.spawn and 2) improving the error message.

**Comment by aditya-88** [comment]
> Hi @aditya-88, thanks for filing this bug! We will look into both 1) using disutils.spawn and 2) improving the error message.

Thank you!
It'll make things easier for the prospective users.

**Comment by gunjanbaid** [comment]
Hi @aditya-88, I looked into this issue a bit further. Unfortunately, I don't think using a `disutils.spawn`-style solution will be possible here. There are a few different things to point out. First, we need not just the `pyclif` binary, but other files that get created when you install CLIF. Here are all the files present in my `clif` directory:

```
$ ls clif
bin  clang  examples  include  lib  local  pip-selfcheck.json  python  share
```

Second, even if you did obtain all the needed CLIF files, we still cannot check for them to present at other paths. In our [`WORKSPACE` file](https://github.com/google/deepvariant/blob/r0.7/WORKSPACE#L78) for Bazel, we create a `new_local_repository` for CLIF. Creating this `new_local_repository` requires specifying a full absolute path in advance (more details in [the docs](https://docs.bazel.build/versions/master/be/workspace.html#new_local_repository)). Two solutions for you to get around this would be:
1. Create a symlink to your CLIF directory via `ln -s $SOME_PATH/clif /usr/local/clif`
OR
2. Modify the path in the [`WORKSPACE` file](https://github.com/google/deepvariant/blob/r0.7/WORKSPACE#L81). For example, if your files are at `/home/my_account/clif/`, you can change the path to `/home/my_account`.

We can definitely make this more clear in our documentation in the future.
@pichuan Feel free to add on if I missed anything.
