### ISSUE TITLE
Training model with GPU

### ISSUE THREAD

**Issue by bdongucdavis** [google/deepvariant#162]
I tried to train the DeepVariant on CPU and it was very slow. I now have access to a google cloud instance with GPUs. I am new with google cloud and I am not sure how I can accelerate the training process with GPUs.

According to the [Case Study](https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-tpu-training-case-study.md), I can use the use_tpu flag to accelerate the training process with TPUs, but I don't know if I can do the same thing with GPUs.

**Comment by pichuan** [comment]
Hi @bdongucdavis , thank you for your interest in training DeepVariant models.
Training on CPU is indeed going to be very slow. With GPUs, you can speed it up compared to CPUs. For example, this old tutorial that I wrote has an example: http://bit.ly/train-deepvariant

If you are using Google Cloud Platform, I would strongly recommend that you get TPU quota and try following the steps in the [Advanced Case Study: Train a customized SNP and small indel variant caller for BGISEQ-500 data](https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-tpu-training-case-study.md) to use **TPU**s (which is different from GPUs), which should be much faster than GPUs.

One thing on our TODO lists is to look into whether we can utilize multiple GPUs better , which we think will be particularly useful for the training use case. However, it's not on the top of our priority list right now. Hopefully we'll get there soon!

And, to clarify, the `use_tpu` flag is specifically for TPU, which is a different kind of hardware from GPU or CPU.

I will close this issue, but if you have relevant follow up questions, feel free to reopen.
