### ISSUE TITLE
multi-gpu support?

### ISSUE THREAD

**Issue by jrvanalstine** [google/deepvariant#163]
Is there any multi-gpu support? Would it be a waste to run DV on instances with multiple GPUs?

**Comment by pichuan** [comment]
Hi,
Currently, only the call_variants step can utilize GPU. And it currently only uses one GPU. Our team is actively looking into getting it to work with multi-gpu. Hopefully we'll have an update soon.

**Comment by gunjanbaid** [comment]
Hi @jrvanalstine! Unfortunately, the TensorFlow Estimator API does not support running prediction on multiple GPUs, so `call_variants.py` currently uses only 1 GPU at prediction time. That said, the API does support running training and evaluation (both steps require labels) with multiple GPUs through distribution strategies (i.e. `MirroredStrategy`). We hope to look into this and will post an update if we are able to run these steps using multiple GPUs. I'll close this issue for now but feel free to reopen if you have any other questions. Thanks!
