### ISSUE TITLE
bad_alloc (memory?) issue postprocess_variants

### ISSUE THREAD

**Issue by cwarden45** [google/deepvariant#167]
Hi,

As a follow-up to my [previous question](https://github.com/google/deepvariant/issues/166), I am trying to run the **postprocess_variants** command for DeepVariant from a Docker container on an AWS instance.

I am getting the following error message:

```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I thought this might have been an issue with memory allocation, but I have been testing the same command with increasing computational resources (I am currently using a m5.4xlarge instance).

**1)** Am I totally wrong about the underlying cause?  If so, is there anything you can suggest to troubleshoot this issue?

**2)** Based upon my Google searches, it seemed like this might have something to do with using TensorFlow.  Is it easy to tell if that is correct?  If so, does that mean you are still doing variant calling/prediction from the **postprocess_variants** command?

This is the command that I am running:

```

OUTPUT_DIR=/mnt/efs-genome/Charles_Human/Genos_Exome/Genos_Alignment/DeepVariant
REF=/mnt/efs-genome/Ref/hg19.gatk.fasta

CALL_VARIANTS_OUTPUT="${OUTPUT_DIR}/call_variants_output.tfrecord.gz"

FINAL_OUTPUT_VCF="${OUTPUT_DIR}/output.vcf.gz"

sudo docker run \
  -v /mnt/efs-genome:/mnt/efs-genome \
  gcr.io/deepvariant-docker/deepvariant \
  /opt/deepvariant/bin/postprocess_variants \
  --ref "${REF}" \
  --infile "${CALL_VARIANTS_OUTPUT}" \
  --outfile "${FINAL_OUTPUT_VCF}"
```

Thank you very much for your assistance!

Sincerely,
Charles

**Comment by pichuan** [comment]
Hi Charles,
the bad_alloc error could indicate that you're running out of memory on this machine.
It seemes like m5.4xlarge have 64 GB RAM? Currently postprocess_variants reads in everything in memory and sorts them, which can take quite a lot of memory depending on how many records the previous step generated.
I suggest trying this step on a machine with more RAM, or keep an an eye on whether the memory usage is an issue. Currently for our WGS Case Study , we recommend getting a machine with 128GB RAM.

**Comment by cwarden45** [comment]
Thank you - I will look into this.  I was definitely not using 128 GB of RAM on AWS, so I will keep increasing this.

I think you almost have to use a Cloud Resource or High-Performance Computing Cluster/Server for that: definitely not my personal home computer :(

While I also have WGS data, this is Exome data.

I thought the _call_variants_ output seemed kind of small, but I don't know what is the typical size for this program.

**Comment by cwarden45** [comment]
Also, to answer your earlier question:

I may be still in the learning phase about some AWS things, but _m5.4xlarge_ (which is what I was using when I submitted the ticket) is supposed to have 16 cores and 64 GB of RAM.

I am currently testing running on an _r4.8xlarge_ EC2 instance (part of an ECS cluster, which has Docker installed) is supposed to have 32 cores and 244 GB of RAM.

If that doesn't work, I think I need to take more time to either look into other strategies (like keep trying to get things set up to run in "Batch," where requirements are specified in a different way, and I don't have an instance) and/or go ahead and start my Google Cloud comparison.  While I want to be fair and clear, I've already spent more than $250 in ~2 weeks trying to test deepvariant in the AWS system.  So, in order for this to be a viable option over GATK (which I can run on my local computer for WGS data with 4 cores and 8 GB of ram), I need to be able to confirm that I can in fact perform Exome analysis on Google Cloud for $0.20 (and while ~25 min is not essential, I think you would need to update your page if those two metrics didn't apply to typical usage).

Still running that postprocess_variants command on AWS, but I will keep you posted until the issue is fixed!

**Comment by akolesnikov** [comment]
Hi Charles,

In addition to what Pi-Chuan said. We run a case study for exome on 128G instance (https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-exome-case-study.md)

postprocess_variants simply converts variants from internal format to VCF format. This error is very generic and from the information you provided there is no way to say it is related to TensorFlow.
It would be helpful if you could provide logs for postprocess_variants.

**Comment by cwarden45** [comment]
Thank you for the reply about TensorFlow.

I'll double-check when I get home (I have limited IP access to my AWS Cloud account), but the call_variants file seemed much smaller than I would expect for a file format.  However, maybe the issue is that it is a binary file (otherwise, it seems too small to contain the information in variant .vcf file).

 However, the proportions of run time does match my own experience (the "call_variants" step ran the most quickly).  I apologize that it will take me a little while to look into all of these things, but I do plan on comparing Google Cloud at some point (possibly for this particular issue).

Using Docker made a huge difference for me for usability.  However, at a later point, I am very grateful that you have all of the code open-source (so, if I wanted, I could use DeepVariant to better understand how to use TensorFlow in other applications).  For example, even if they don't use COHCAP directly, you can use the [source code](https://github.com/cwarden45/COHCAP/tree/master/src) to see how the Boost libraries for [statistical distributions](https://www.boost.org/doc/libs/1_67_0/libs/math/doc/html/dist.html) (rather than parallel operation) can substantially decrease the run time (relative to the R-base functions). [I apologize for being a bit off topic, but that is the best analogy that I can think of]

**Comment by pichuan** [comment]
Hi Charles,
there are a few 3rd party Cloud orchestrations for DeepVariant that you can consider. I'll provide the links below. To get the most accurate information, please visit their websites. (Our team does not maintain these).

* [Running DeepVariant on Google Cloud Platform](https://cloud.google.com/genomics/docs/tutorials/deepvariant)                                                                                                                                                                                                                                                                                                             | Docker-based pipelines optimized for cost and speed. Code can be found [here](https://github.com/googlegenomics/gcp-deepvariant-runner).
* [DeepVariant-on-spark from ATGENOMIX](https://github.com/atgenomix/deepvariant-on-spark)                                                                                                                                                                                                                                                                                                                                 | A germline short variant calling pipeline that runs DeepVariant on Apache Spark at scale with support for multi-GPU clusters (e.g. NVIDIA DGX-1).
* [Parabricks](https://docs.parabricks.com/standalone-tools/deepvariant)                                                                                                                                                                                                                                                                                                                                                   | An accelerated DeepVariant pipeline with multi-GPU support that runs our WGS pipeline in just 40 minutes, at a cost of $2-$3 per sample. This provides a 7.5x speedup over a 64-core CPU-only machine at lower cost.
* [DNAnexus DeepVariant App](https://platform.dnanexus.com/app/deepvariant_germline)                                                                                                                                                                                                                                                                                                                                       | Offers parallelized execution with a GUI interface (requires platform account).
* [Nextflow Pipeline](https://github.com/nf-core/deepvariant)                                                                                                                                                                                                                                                                                                                                                              | Offers parallel processing of multiple BAMs and Docker support.
* [DNAstack Pipeline](https://app.dnastack.com/auth/realms/DNAstack/protocol/openid-connect/auth?client_id=dnastack-client&redirect_uri=https%3A%2F%2Fapp.dnastack.com%2F%3Fredirect_fragment%3D%252Forg%252F473079%252Fproj%252F473096%252Fapp%252Fworkflow%252F425685%252Frun&state=42231553-9fbc-4d71-a10e-d6ce42415c01&nonce=daf2568d-4fe7-48e2-ab60-858937244a87&response_mode=query&response_type=code&scope=openid) | Cost-optimized DeepVariant pipeline (requires platform account).


However, I'm quite curious why 64G didn't work for you. I will need to check back to see how much our postprocess_variants use for the HG002 Case Study. I don't think it should need 64G of RAM. But it would certainly depends on your data and the size of the input.

A few things to follow up:
(1) If you can let me know how big is the input file for postprocess_variants (output from call_variants), that might be useful information.

(2) I'll follow up with you through a message to see what we can do in order to diagnose this particular run.

**Comment by cwarden45** [comment]
Hi Pi-Chuan,

I'm still not back home yet (so, I apologize that I'm not 100% answering your question).  However, I can say this:

Even thought I would expect the direct command-line analysis (in AWS or Google Cloud) should cost less, I did briefly look into DNAnexus and Seven Bridges.  However, DNAnexus requires that you create an account with an institutional e-mail, and I was checking about what were options for people who want to re-analyze that that is directly provided to them (who may not be scientists).  I also didn't see a way to create a Seven Bridges account with a G-mail address, but both companies gave me an initial reply about my account creation question within 24 hours.

That said, I am also currently working on uploading my data to PrecisionFDA (which uses DNAnexus, but I can't use my PrecisionFDA account to sign into DNAnexus).  For the user, I think this would be free, and it provides a way to test results provided by companies (**and** I could create an account with a Gmail address).  However, PrecisionFDA doesn't currently have a DeepVariant App.  I passed along an earlier version of this thread to them, but I will also now ask if it might be helpful that DNAnexus already has a DeepVariant app (to see how easily that can be applied within PrecisionFDA).

I'll upload the call_variants file when I get home.  Unless there is something obvious that you can see, I think it would probably be more fair for your time to start a Google Cloud test (although that means you may have to wait a little while before I get to the same step on another platform).

Thank you again for all of your prompt replies!

Sincerely,
Charles

**Comment by cwarden45** [comment]
I've attached the output from the _call_variants_ step.

I'm not sure how much may have to do with having a total of ~2 weeks AWS experience, but the current situation may be kind of interesting:

1) I believe I started running **postprocess_variants** this morning
2) After an 1-2 hours I would have expected to see that error message with the previous runs.
3) Using _r4.8xlarge_ EC2 instance launched from the ECS cluster (listed as having have 32 cores and 244 GB of RAM), **postprocess_variants** step is still running.

I was admittedly surprised with I had problems with 64 GB of RAM (and submitted this ticket).  However, using 244 GB of RAM seems to have gotten around the memory issue (at least after having been running for ~12 hours), but the run-time seems extraordinarily long (if I correctly understand that this step is supposed to be  just file reformatting, for an Exome dataset).  I kind of want to see if the job is capable of finishing running (and giving the expected result).  However, my AWS costs for today alone was over $20.  So, I think I need to either figure out what is going on or test other options (since I want to test an alternative .bam alignment for that Exome file, as well as testing 2 alignments for my WGS data).

[call_variants_output.tfrecord.gz](https://github.com/google/deepvariant/files/3041631/call_variants_output.tfrecord.gz)

**Comment by pichuan** [comment]
Thanks for sharing the file! We'll take a look soon and get back to you.

**Comment by cwarden45** [comment]
You are very welcome - thank you for your help!

FYI, the script recently stopped with the same error message.  So, unless that file gives you another troubleshooting idea, I may look into other possible strategies (and/or look into more AWS documentation) and return to this issue when I get to the same stage with running DeepVariant (or at least report the alternative solution that I worked out).

**Comment by pichuan** [comment]
Hi Charles,
I had a chance to try this on a GCE (Google Compute Engine) instance. First, when I looked at your file, I suspect it won't take much resource and time at all. And from my experiment below, it matches my expectation.

Quick summary:
It took me about **24 seconds**, on a [n1-standard-1](https://cloud.google.com/compute/docs/machine-types#standard_machine_types) instance (which has **3.75GB** RAM) to run postprocess_variants on your file.

Below, I will share all the steps I used to produce the result.
And, my next step (which won't be today) will be to try to run this on an AWS instance. 

Here are the steps I've done:

1. On my machine, I used this command to get a GCE instance:
```
gcloud compute instances create "${USER}-1" \
  --image-family "ubuntu-1604-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "n1-standard-1" \
  --zone "us-west1-b"
```

2. I ssh'ed into the machine using this command:
```
gcloud compute ssh "${USER}-1"
```

3. I downloaded the input file needed:
```
# Downloading the reference file takes a while.
# It's only used for the header in postprocess_variants.
wget ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg19/ucsc.hg19.fasta.gz
gunzip ucsc.hg19.fasta.gz
wget ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg19/ucsc.hg19.fasta.fai.gz
gunzip ucsc.hg19.fasta.fai.gz

# Download the output from call_variants step:
wget https://github.com/google/deepvariant/files/3041631/call_variants_output.tfrecord.gz
```

4. I pull the docker image, and run the command:
```
sudo docker pull gcr.io/deepvariant-docker/deepvariant:0.7.2

time sudo docker run \
  -v ${PWD}:/data \
  gcr.io/deepvariant-docker/deepvariant:0.7.2 \
  /opt/deepvariant/bin/postprocess_variants \
  --ref /data/ucsc.hg19.fasta \
  --infile /data/call_variants_output.tfrecord.gz \
  --outfile /data/output.vcf.gz
```

As I mentioned, this took:
```
real    0m24.779s
user    0m0.033s
sys     0m0.022s
```

I used `top` to keep an eye on the memory usage. The highest I've noticed is roughly the following:
```
  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND
 4882 root      20   0 1445956 229032 103824 R 99.3  6.1   0:22.46 python
```

This produced 90,359 total lines, of which 78,085 are actual variant calls (PASS)
```
$ zcat output.vcf.gz | grep -v '^#' | wc -l
90359

$ zcat output.vcf.gz | grep -v '^#' | grep PASS | wc -l
78085
```

**Comment by cwarden45** [comment]
Thank you - I think these commands will be helpful as I learn about using Google Cloud.

Please don't rush the AWS test - I am guessing I will have to wait until at least Sunday to be able to set up an account and confirm that using Google Cloud can resolve this issue.

**Comment by pichuan** [comment]
No problem.

I will still want to make sure there isn't a problem on AWS though. Our team develop DeepVariant to run everywhere (with a compatible OS). We mostly test on Ubuntu 16.04 so far because we haven't had much resource to test much more broadly. But a Ubuntu either on GCP or AWS shouldn't be an issue. And if it is, I think our team needs to know why.
Once I have a chance to test and confirm, I'll report back here as well.

**Comment by pichuan** [comment]
@cwarden45 
I got a `t1.micro` machine on AWS , and I basically repeated what I did in https://github.com/google/deepvariant/issues/167#issuecomment-480150395

With the same command:
```
sudo docker pull gcr.io/deepvariant-docker/deepvariant:0.7.2

time sudo docker run \
  -v ${PWD}:/data \
  gcr.io/deepvariant-docker/deepvariant:0.7.2 \
  /opt/deepvariant/bin/postprocess_variants \
  --ref /data/ucsc.hg19.fasta \
  --infile /data/call_variants_output.tfrecord.gz \
  --outfile /data/output.vcf.gz
```

It took me:
```
real    0m24.779s
user    0m0.033s
sys     0m0.022s
```
on a t1.micro AWS instance. A few differences from my GCP experience is:
(1) I had to use yum (instead of apt) to install docker.
(2) I had to first run `sudo service docker start` before I pull and run the docker image.

Other than these, everything seems mostly the same.

At this point I have one more question for you -- where are your files located? In your command in the original post, they're from `/mnt`. Where are these files mounted from?

In my setting, I wget all the files first. So that could be one difference that I can think of now.

**Comment by cwarden45** [comment]
Thank you again for your reply, especially on the weekend.

While I'd like to have a way to run all of the steps, thank you for this feedback.  As a sort of similar test, I had a m3.large instance open, so I tested running the command from my home directory.

For some reason, I don't get the same error message when I do this, but I also don't get any output and no output files are created.  Nevertheless, this did gives me some ideas of other thing that I can try.

In general, maybe there are a couple things that I need to explain:

**1)** I am using an EC2 instance launched from ECS: https://aws.amazon.com/ecs/

This means Docker is already installed.

When I create an instance through ECS, I don't think I have the option to create a micro instance (but that isn't my biggest problem).

I thought I created the instance with an extra 100 GB of storage (just in case something extra was needed on the local hard drive, beyond RAM).  But I don't think this should be the issue for this last step.

There may be some other issue that I am not understanding, but I could run the 1st two steps this way (although with an admittedly longer run-time than I expected), but the **postprocess_variants** is what I can't get to work.

I also received a reply about converting the regular docker image to an[ ECR](https://aws.amazon.com/ecr/) image (submitted on 4/2), to run in AWS [Batch](https://aws.amazon.com/batch/).  If that ends up being helpful, I will let you know.  If they at least resolve that issue, the next ticket that I submitted (on 4/4) was for this exact issue (but I haven't heard any feedback from that yet).

**2)** I want to be able to have my files (.bam, .fastq, etc.) accessible between instances.  While I think Google created a way to do with with S3 buckets, my understanding was that I was supposed to do this with an EFS file system: https://aws.amazon.com/efs/

So, _/mnt/efs-genome_ is the EFS file system that contains my .fastq and .bam files (and DeepVariant output).  I have to mount it whenever I create a new instance, but I don't have to re-upload the files.

**Comment by cwarden45** [comment]
FYI, I'm not sure if this is the best solution, but I noticed that running in my home directory avoids the need to use _sudo_.

While I am still encountering the same result (and I thought I encountered some issue with running Docker interactively at another step, I do have the ability to launch Docker in my home directory in interactive mode:

`docker run -it -v /mnt/efs-genome:/mnt/efs-genome gcr.io/deepvariant-docker/deepvariant`


and then run the commands for :

```
OUTPUT_DIR=/mnt/efs-genome/Charles_Human/Genos_Exome/Genos_Alignment/DeepVariant
REF=/mnt/efs-genome/Ref/hg19.gatk.fasta
CALL_VARIANTS_OUTPUT="${OUTPUT_DIR}/call_variants_output.tfrecord.gz"
FINAL_OUTPUT_VCF="${OUTPUT_DIR}/output.vcf.gz"

 /opt/deepvariant/bin/postprocess_variants \
  --ref "${REF}" \
  --infile "${CALL_VARIANTS_OUTPUT}" \
  --outfile "${FINAL_OUTPUT_VCF}"
```

Again, I am neither seeing an error message or a result file.  However, if this provides a useful option for troubleshooting, I thought I should mention it.

Also, I am starting the Google Cloud testing, but I am currently only at the file upload stage (I want to make sure I can run the 1st two steps, before checking that as a solution for the 3rd step).

Thank you very much for your help!

**Comment by cwarden45** [comment]
While AWS was better than my local computer (with 8 GB of RAM and 4 cores) for running the 1st step (_make_examples_), I can likewise try running the Docker container in interactive mode on my own computer:

`docker run -it -v /c/Users/Charles/Documents/WGS_Exome_Analysis/My_Veritas_WGS:/mnt/wgs gcr.io/deepvariant-docker/deepvariant`

followed by moving to the appropriate directory and running the following script:

```
OUTPUT_DIR=Genos_Provided
REF=../hg19.gatk.fasta

CALL_VARIANTS_OUTPUT="${OUTPUT_DIR}/call_variants_output.tfrecord.gz"
FINAL_OUTPUT_VCF="${OUTPUT_DIR}/output.vcf.gz"

/opt/deepvariant/bin/postprocess_variants \
  --ref "${REF}" \
  --infile "${CALL_VARIANTS_OUTPUT}" \
  --outfile "${FINAL_OUTPUT_VCF}"
```

This is different than running interactive mode for **postprocess_variants** on AWS (which almost immediately ends, without error message or results file), but it has been running for more than one hour.  So, I will provide an update if this works, but this sounds different than your experience with the t1.micro AWS instance.

**Comment by cwarden45** [comment]
Also, if I try to follow your instructions for an EC2 instance, I can't actually create a _t1.micro_ EC2 instance, but I can create a **t2.micro** EC2 instance (with 1 vCPU and 1 GB of RAM).

I remember spending some effort to try and install Docker on the EC2 instance.  That installation is quite quick, and I almost wondered if I hadn't somehow didn't tested `sudo yum install docker`.  However, there was slow-down after pulling the docker image (possibly due to the type of instance?).

I am waiting to see what happens with the terminal where I pulled the Docker image.  However, if I sign into another terminal and try to run `docker images` (to confirm that everything worked OK), I get the following error message:

`Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.38/images/json: dial unix /var/run/docker.sock: connect: permission denied`

Strictly speaking, I was running the script rather than just the pull command.  So, when the 1st terminal stopped running (in approximately 5-10 minutes), I still got the same error message that I started with:

```
sudo sh run_deepvariant.sh
Unable to find image 'gcr.io/deepvariant-docker/deepvariant:latest' locally
latest: Pulling from deepvariant-docker/deepvariant
18d680d61657: Pull complete
0addb6fece63: Pull complete
78e58219b215: Pull complete
eb6959a66df2: Pull complete
54de1d38bbd7: Pull complete
d17c3563217d: Pull complete
ba1bdbdefce9: Pull complete
94eba53c4ad9: Pull complete
413f494b0501: Pull complete
4d89363e7fb4: Pull complete
e9213d1ccf36: Pull complete
fb6121657d6b: Pull complete
Digest: sha256:705523e7bc241e0d3e1e57d4d338c83e289d51a8231c09b0d2dee03c015cee0f
Status: Downloaded newer image for gcr.io/deepvariant-docker/deepvariant:latest
docker images
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

_[I entered "docker images" when I didn't see anything, so that is input, not output]_

However, I then get that "docker.sock" error message if I try to run `docker ps -a` after the script stopped from that error message.  So, that puts me back where I started, and I actually have that extra error message over trying to use Docker from the instance launched via ECS.

Nevertheless, if I make any additional progress, I will let you know.

**Comment by cwarden45** [comment]
It took about 8 hours, but I could run the **postprocess_variants** step on my local computer (using the commands [specified above](https://github.com/google/deepvariant/issues/167#issuecomment-480640009)).

If Official Amazon Support doesn't have a solution for running this program on AWS, I might cross-post this on StackExchange (to see if I can figure out if there is some sort of configuration issue on AWS, and/or if I am not using ECS efficiently/correctly).

However, I realize you have a lot of support to provide, so I will close this ticket and provide the successful output from my local computer:

```
2019-04-07 21:06:30.591035: I deepvariant/postprocess_variants.cc:88] Read from: Genos_Provided/call_variants_output.tfrecord.gz
2019-04-07 21:06:33.504711: I deepvariant/postprocess_variants.cc:97] Done reading: Genos_Provided/call_variants_output.tfrecord.gz. #entries in single_site_calls = 91732
2019-04-07 21:06:33.505181: I deepvariant/postprocess_variants.cc:101] Total #entries in single_site_calls = 91732
2019-04-07 21:06:33.505270: I deepvariant/postprocess_variants.cc:103] Start SortSingleSiteCalls
2019-04-07 21:06:34.914308: I deepvariant/postprocess_variants.cc:105] Done SortSingleSiteCalls
I0407 21:06:36.217032 139687245461248 postprocess_variants.py:596] Writing output to VCF file: Genos_Provided/output.vcf.gz
I0407 21:06:36.221911 139687245461248 genomics_writer.py:163] Writing Genos_Provided/output.vcf.gz with NativeVcfWriter
I0407 21:06:36.231071 139687245461248 postprocess_variants.py:601] 1 variants written.
```

**Comment by cwarden45** [comment]
Also, while I am still doing some extra testing, I figured out the cause of my problem (which was actually very simple):

**1)** The error message changed a little bit (so, I was focusing on the memory, when there was actually another error:

```
terminate called after throwing an instance of 'std::system_error'
  what():  Resource temporarily unavailable
```

**2)** I was providing the relevant parts of the code on GitHub without realizing that everything from step #2 (**call_variants**) was commented out, which _included_  the CALL_VARIANTS_OUTPUT variable (which is the _input_ file for **postprocess_variants**).  After uncommenting that line, the file reformatting ran within a minute (on an AWS ECS m5.2xlarge instance).

I am very sorry that it took so many messages (and time) for me to eventually figure out this problem, but I hope this helps with other people seeing a similar error message.

**Comment by pichuan** [comment]
No problem. Glad to hear that the mystery is resolved.

**Comment by cwarden45** [comment]
Yes - thank you again for your help!
