### ISSUE TITLE
Make_examples using GPU?

### ISSUE THREAD

**Issue by tstokowy** [google/deepvariant#168]
Hi, I am using DeepVariant 0.7.2 on my local machine (nvidia-docker). I managed to significantly accelerate call_variants using GPU (5-10x faster using relatively cheap graphics card).

I wonder if it is possible to accelerate make_examples using GPU - for now I am using parallel CPU threads as suggested: seq 0 $((N_SHARDS-1)) | parallel (...).

--
Tomasz Stokowy

**Comment by sidharthgoel** [comment]
Hi Tomasz,
We currently do not support running make_examples on GPUs, just the parallelized threads that you are currently using. However, you could consider [this external solution](https://docs.parabricks.com/standalone-tools/deepvariant) from Parabricks, which provides multi-GPU support for running our pipelines. Please note that we are not involved with creating or maintaining this.
