### ISSUE TITLE
Soooo hard to install 

### ISSUE THREAD

**Issue by hmyh1202** [google/deepvariant#169]
I had tried install the soft using conda， but it was failed finally.

Besides dose GPU necessary ？

**Comment by sidharthgoel** [comment]
Please provide more details on the issue (commands run, the error you saw, etc.) You can start with the [quickstart doc](https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-quick-start.md) or one of the case studies (linked on the top-level page) to better understand how to install and run DeepVariant.
