### ISSUE TITLE
Cannot install DeepVariant

### ISSUE THREAD

**Issue by mrliuw** [google/deepvariant#17]
I have try to install the DeepVariant, but failed. I cannot install the GoogleCloud at first, and then cannot also install the software. I come from China. Any solutions to the problem. I hope you can give some help. Thank you.

I downloaded a versioned archive for Cloud SDK. When installing googlecloud, some module error pops. 
File "xxxxx/install.py", line 8, in <module> import bootstrapping
File "xxxxx/install.py", line 9, in <module> import setup
File "xxxxx/install.py", line 38, in <module> from googlecloudsdk.core.util import platforms
ImportError: No module named googlecloudsdk.core.util
I also tried the apt-get install, however due to network striction, I cannot install it by online command.

**Comment by pichuan** [comment]
It is not a requirement to use Google Cloud or its SDK. You should be able to still use DeepVariant without having to install anything related to Google Cloud.
One issue here is that we put our data (including pre-built binaries) on Google Cloud storage. So you might not have access to them. You can try the browser version to see if you can view or download the data: https://pantheon.corp.google.com/storage/browser/deepvariant. But even if that doesn't work, you should still be able to build the binary from scratch:
https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-build-test.md

The example input data (such as FASTA, BAM files) can be found on their original sites. For example, in the Case Study we listed where we got the files: https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-case-study.md#test-data

**Comment by scott7z** [comment]
Does this work to fetch a single file?

`curl http://storage.googleapis.com/deepvariant/binaries/DeepVariant/0.4.1/DeepVariant-0.4.1+cl-178668854/make_examples.zip  >make_examples.zip`

**Comment by scott7z** [comment]
I'm going to close this issue, since it seems to boil down to either a network issue or a problem installing gsutil.

**Comment by mrliuw** [comment]
Thank you sirs. Busy these days. I will try again.

2017-12-19 8:51 GMT+08:00 scott7z <notifications@github.com>:
