### ISSUE TITLE
Running batch analysis

### ISSUE THREAD

**Issue by jaqueytw** [google/deepvariant#170]
Hi there!

I tried to combine the deepvariant's gvcf files using GATK and it returned a error because of the "NON_REF".
Do you have any other recommendation? Or did you tested your gvcf in GATK?

This is the error that I got using GATK:
A USER ERROR has occurred: The list of input alleles must contain <NON_REF> as an allele but that is not the case at position 10325413; please use the Haplotype Caller with gVCF output to generate appropriate records

The DeepVariant "<NON_REF>" allele is "<*>"

_Originally posted by @jaqueytw in https://github.com/google/deepvariant/issues/45#issuecomment-481414559_

**Comment by sidharthgoel** [comment]
Hi @jaqueytw, thanks for the question. If I'm understanding correctly, [this issue from earlier](https://github.com/google/deepvariant/issues/83) has a solution to your problem. I will check internally whether this is something we want to change now.

If the above solution doesn't work, feel free to re-open this bug.

**Comment by jaqueytw** [comment]
Hi @sidharthgoel.

I did the substitution and used the GATK CombineGVCF and GenotypeGVCF. After that, I separated only the variants where the sample was genotyped with the alternate allele.
The thing is that when I compared with the variants that deepvariant discovered in the single sample, it was different from the combined (see figure).
Maybe, when we use another tool to process the gvcf created by deepvariant, some information are changed. I think that's not a good alternative.

![image](https://user-images.githubusercontent.com/45243234/55978465-3fe67c00-5c66-11e9-8bc3-a6dae36c7525.png)

**Comment by xunjieli** [comment]
@jaqueytw  could you elaborate on how the differences between DeepVariant single-sample calls and the merged cohort are derived? Are you comparing the genotypes, variant representations, or both?

**Comment by jaqueytw** [comment]
@xunjieli yes, I can.

I only extracted the variants where the analyzed sample had the alternative allele (genotype 1/1,0/1,./1). I did this for the single vcf obtained from deepvariant and for the combined vcf (obtained from gatk using the gvcf created with deepvariant).
Then, I compared only the variants (chromosome, position, reference and alternate allele) of this two sets.

Is it clear?

**Comment by xunjieli** [comment]
When you say "_when we use another tool to process the gvcf created by deepvariant, some information are changed_," it might worth figuring out what exactly is changed. Without that info, the feedback isn't actionable.

**Comment by jaqueytw** [comment]
@xunjieli 
Yes, I understand. I will look it further.
Additionally, you should not encourage people to use GATK tools to process your vcf files, since it is changing the genotypes given originally by deepvariant.

**Comment by pichuan** [comment]
Thanks @jaqueytw . I don't believe we're currently encouraging our users to use GATK tools to process our files. But if you find any documentation that mentioned/encouraged that, please do let me know and I'd like to fix it.

We're actively working on coming up with our own recommendation for best practice. Your analysis and feedback is very valuable. Thank you!

**Comment by jaqueytw** [comment]
@pichuan I followed the comment at issue #45 
Thank you!

**Comment by AndrewCarroll** [comment]
Hi @jaqueytw 

I wanted to update this issue with recent developments for cohort merging. With the DeepVariant v0.9 release, we recommend [Best practices for multi-sample variant calling with DeepVariant](https://github.com/google/deepvariant/blob/r0.9/docs/trio-merge-case-study.md)

We encourage you or other users interested in multi-sample calling to follow these recommendations to combine multiple DeepVariant gVCFs

Thank you.
