### ISSUE TITLE
--sample_name input option for run_deepvariant

### ISSUE THREAD

**Issue by zstephens** [google/deepvariant#173]
Greetings, with 0.7.2 I had been using make_examples on BAMs without readgroups using the --sample_name input option, but this didn't seem to carry over into the streamlined run_deepvariant tool introduced in 0.8.0. Is there a way to use run_deepvariant on such a BAM, or is it expected now that the input will contain this metadata?

This is a very minor concern obviously, as it's easy to impute read groups and sample names, but I figured it wouldn't hurt to ask.

Thanks!

**Comment by gunjanbaid** [comment]
Hi @zstephens, thanks for reaching out! The goal of `run_deepvariant` was to provide users with a single command they could use to run DeepVariant using Docker. For the sake of simplicity, this approach only accepts [a few different flags](https://github.com/google/deepvariant/blob/r0.8/scripts/run_deepvariant.py#L53).

We still do support the `sample_name` flag for `make_examples`, but it is not possible to use with `run_deepvariant`. To use this and other flags, I would suggest using separate commands for each step of DeepVariant (`make_examples`, `call_variants`, or `postprocess_variants`). Each of these binaries is included in the Docker image and can be run using a command such as below (with any additional desired flags).

```
sudo docker run gcr.io/deepvariant-docker/deepvariant:0.8.0\ 
  /opt/deepvariant/bin/make_examples
```

I'll close this issue for now, but feel free to reopen if you have any other questions!
