### ISSUE TITLE
Dataset used to train PacBio model

### ISSUE THREAD

**Issue by pjedge** [google/deepvariant#174]
I'm looking for a pre-trained Deepvariant model for PacBio CLR.
I found this (https://console.cloud.google.com/storage/browser/deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-pacbio_standard/?pli=1)
What dataset was used to train this model?

**Comment by akolesnikov** [comment]
Hi Peter,
We used multiple HG002 samples generated with PacBio (CCS mode). We didn't test this model for CLR reads.

**Comment by pjedge** [comment]
ok, thanks!

**Comment by pjedge** [comment]
Hi, so I noticed in the Deepvariant manuscript supplementary text that the 44x NA12878 CLR data (sorted_final_merged.bam) from GIAB was used for benchmarking Deepvariant with PacBio CLR reads (specifically, that chroms 1-19 were used for training and testing was performed on chroms 20-22). Would it be possible for me to access the result VCF for chroms 20-22 (and ideally also the trained model used in the manuscript)? The reason I'm interested in this is that we have developed our own CLR variant calling method and I would like to fairly compare it with Deepvariant. If I have the VCF, then I can be sure that our precision/recall calculations on chr20-22 are exactly the same, and if I have the trained model then I also have the option to run Deepvariant myself on other CLR data. Unfortunately, the training procedure for Deepvariant seems to be complicated at this time and requires significant compute resources. I would be very grateful if it would be possible to meet this request -- you can reach me by email at pedge AT eng.ucsd.edu

**Comment by AndrewCarroll** [comment]
Hi Peter, 

Following up by email. Thank you!
