### ISSUE TITLE
Is there a way to disable downsampling?

### ISSUE THREAD

**Issue by yingchen69** [google/deepvariant#176]
Hi,

I just wonder if Is there a way to disable downsampling? I work with high depth data from targeted tumor panel. The depth could be as high as 20,000x. With deepvariant 8.0, we miss some variants with low maf such as 0.05, 0.02...

Thanks a lot for rhe help!

Best,

Sean

**Comment by pichuan** [comment]
Hi @yingchen69 
from your questions, it seems like you're asking whether you can change the height of the pileup image.
I believe this previous GitHub issue is very similar, and it has a bunch of in-depth discussion: https://github.com/google/deepvariant/issues/62

A direct answer to your question:
DeepVariant is currently a germline variant caller. Our released models are trained for that purpose. The models are trained on data that are 221x100x6 in dimension (221 bases wide, 100 reads deep, 6 channels). You can see an example for visualization [here](https://github.com/google/deepvariant/blob/master/docs/visualizing_examples.ipynb).

From [my answer in the earlier issue](https://github.com/google/deepvariant/issues/62#issuecomment-379107194), it is possible to change the pileup image height. However, even if you do that, it won't just work out of the box for you. I'm closing this issue, but feel free to ask if you have more questions.
