### ISSUE TITLE
Singularity issue on a super computer CentOS 7

### ISSUE THREAD

**Issue by pichuan** [google/deepvariant#178]
I'm opening another issue to follow up on:
https://github.com/google/deepvariant/issues/132#issuecomment-482956117
(The original thread is getting a bit too long, and this issue seems more specific)

Relevant system information in another comment:
https://github.com/google/deepvariant/issues/132#issuecomment-483551683
"The super computer has an OS CentOS Linux release 7.6.1810 (LSB Version: core-4.1-amd64:core-4.1-noarch) and singularity version 2.5.2
I created the image on Amazon instance with Ubuntu 16.04. I tried using singularity version 2.5.2 & 2.6.0 but both did not help"

Adding @drtamermansour here as well.

**Comment by pichuan** [comment]
Hi @drtamermansour,
In my first attempt to reproduce this, I wasn't able to reproduce the issue with the following setting:

1. I got a CentOS 7 machine with:
```
gcloud beta compute instances create "${USER}-centos-singularity" \
--scopes "compute-rw,storage-full,cloud-platform" \
--image=centos-7-drawfork-v20181102 \
--image-project=eip-images \
--machine-type "n1-standard-32" \
--zone "us-west1-b"
```

2. On the machine, I installed Singularity 2.5.2 with instructions on: https://github.com/sylabs/singularity/blob/2.5.2/INSTALL.md

3. I copied a Singularity image that I built with [the instructions I posted before](https://github.com/google/deepvariant/issues/132#issuecomment-482430728) on a Ubutun 16.04 machine to this CentOS 7 machine. Then I got the [Quick Start](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md) data and run the command:
```
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
  deepvariant.simg \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta \
  --reads=${INPUT_DIR}/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=output.vcf.gz \
  --output_gvcf=output.g.vcf.gz   
```

The run completed without an issue.

My CentOS machine has:
```
$ lsb_release 
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
```
```
$ cat /etc/centos-release
CentOS Linux release 7.6.1810 (Core) 
```

---

From the original error message:
`ImportError: No module named _multiarray_umath`
It seems like an issue with numpy installation. But given we're using a singularity image, I am having a hard time thinking why this would be the case. (Unless it's not created correctly?)

@drtamermansour 
Two questions for you:
(a) When you create the image, can you try to run it on the machine where you create it to make sure it worked there? 
(b)  Do you think it'll help if either I or @williamrowell share our *simg file with you to try it out?

**Comment by drtamermansour** [comment]
@pichuan Thank you for taking the time to address this issue.
(a) The example code was running fine on the Amazon instance. Only failed to run on our CentOS machine
(b) I think this is a very good idea (specially the one made by @williamrowell which was created on a CentOS machine). I think these images might be helpful to our users as well   

BTW, we used your code in #132 successfully on a similar Amazon machine to create a simg file using DeepVariant 0.7.0. However, the process was not easy. We had to add ```--bind input:${INPUT_DIR}``` only on the CentOS machine to make it run. Also non of the deepvariant commands will run with genomic regions (e.g. chr20:10000000-10010000) or even multiple chromosomes (e.g. chr20 chr21 chr22). Only ```--regions "chr20"``` was accepted

**Comment by pichuan** [comment]
Hi @drtamermansour 
I have not tried building Singularity before this latest release, so I can't guarantee how easy it would be. Regarding your issue with `--regions`, I'm pretty sure it's because the intervaltree version issue. Please see this comment for a solution if you have to build from DeepVariant before 0.8.0:
https://github.com/google/deepvariant/issues/131#issuecomment-449034956

We highly recommend building from the latest one (0.8.0) if possible, though. 

In terms of sharing file, we'll see if @williamrowell can share his file. I can also see if I can find a reasonable place to share mine (which is also built on a CentOS machine on GCP)

**Comment by williamrowell** [comment]
Sorry, I've been traveling the past week without a solid network connection.  I've uploaded my simg to google drive at the address below.  This will likely not be a permanent link, but you can use it for testing now.

https://drive.google.com/open?id=12NZKJwRTroKofGB6KrZ4JVyN36DRbPuF

**Comment by pichuan** [comment]
Thank you @williamrowell !
@drtamermansour can you try it out and let us know whether Billy's image worked for you?

**Comment by pichuan** [comment]
Update: I've emailed @drtamermansour but haven't back from him. I'll close this bug for now.

If anyone had a chance to try @williamrowell 's image above, let us know how it wokr.s
If anyone else is encountering the same issue, please feel free to comment on this issue again.

I will close it now since there's no information right now.

**Comment by drtamermansour** [comment]
Sorry for the late replay. Unfortunately, it did not work. The error message says:
ERROR  : Unknown image format/type: deepvariant.0.8.0.simg
ABORT  : Retval = 255

**Comment by pichuan** [comment]
Hmm interesting. 
@williamrowell FYI  - I tried out your image you shared, and I'm having the same issue as well.

@drtamermansour Thanks for testing it out. Let me rebuild with the steps I shared in https://github.com/google/deepvariant/issues/178#issuecomment-487218238 and see if you can try mine as well. I'll follow up soon.

**Comment by pichuan** [comment]
@drtamermansour 
Here is a simg file I just built:
https://drive.google.com/file/d/1P768MjXLa4xPmqj12UZqnmDqUZsUpbNh/view?usp=sharing
(which should be a file with the name `deepvariant.0.8.0.issue-178.simg`)

I built this with the instruction here: https://github.com/google/deepvariant/issues/132#issuecomment-482430728
and tested with the steps here: https://github.com/google/deepvariant/issues/178#issuecomment-487218238

Please let me know if this works for you or not.
