### ISSUE TITLE
glibc causes segmentation fault 

### ISSUE THREAD

**Issue by aubcar** [google/deepvariant#179]
Hey guys,

I got deepvariant installed with conda fine, but my run failed by needing glibc, when I installed glibc all processes get a segmentation fault, if I remove glibc it works until failing needing the dependency. Any advice?  We can't install docker images on our HPC,  I haven't tried converting docker to singularity, as I have no experience with that but I'm comfortable compiling from source, but couldn't find the right files/instructions.

Cheers

**Comment by gunjanbaid** [comment]
Hi @aubcar, were you able to resolve the problem? There are some tips for `glibc` in #137.

**Comment by aubcar** [comment]
Turns out I was on some nodes of the HPC that hadn't been updated, issue solved itself when on current nodes. Thanks!
