### ISSUE TITLE
ref variable path is not being found in deep variant run

### ISSUE THREAD

**Issue by ashraf123456789** [google/deepvariant#181]
Hello, 

I working through the DeepVariant set up workflow under the docker umbrella, but the variable "ref" indicating the path of the reference .fasta is not responding properly. 

sudo docker run \
>   -v "${INPUT_DIR}":"/input" \
>   -v "${OUTPUT_DIR}:/output" \
>   gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \ 
**<cmd-b>FATAL Flags parsing error: flag --ref=None: Flag --ref must have a value other than None.</cmd-b>**
Pass --helpshort or --helpfull to see help on flags.
shaba033$  <cmd-b> --ref=/input/ucsc.hg19.chr20.unittest.fasta </cmd-b>\
>   --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf=/output/output.vcf.gz \
>   --output_gvcf=/output/output.g.vcf.gz \
>   --num_shards=4
-bash: --ref=/input/ucsc.hg19.chr20.unittest.fasta: No such file or directory

**Comment by ashraf123456789** [comment]
thank you!

**Comment by gunjanbaid** [comment]
Hi @ashraf123456789, you will need to reformat the command as it got split into two commands. Does the following work for you?

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --num_shards=4
```

**Comment by ashraf123456789** [comment]
Thanks @gunjanbaid! , it's now one command but I still received a error:

sudo docker run \
>   -v "${INPUT_DIR}":"/input" \
>   -v "${OUTPUT_DIR}:/output" \
>   gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
>   /opt/deepvariant/bin/run_deepvariant \
>   --model_type=WGS \
>   --ref=/input/ucsc.hg19.chr20.unittest.fasta \
>   --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
>   --regions "chr20:10,000,000-10,010,000" \
>   --output_vcf=/output/output.vcf.gz \
>   --output_gvcf=/output/output.g.vcf.gz \
>   --num_shards=4
docker: invalid reference format.
See 'docker run --help'.

These commands are being run in a Unix shell, do you think the commands vary between Linux and Unix?

Best,

-Ashraf

**Comment by gunjanbaid** [comment]
@ashraf123456789 I don't think the commands should vary. Could you check that you have set `${BIN_VERSION}`? I have seen this error message when the variable is not set, causing the image name to be incorrect. You could try running the following:

```
BIN_VERSION="0.8.0"

sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --num_shards=4
```

**Comment by ashraf123456789** [comment]
Yes, thank you!

**Comment by Jyoti-Mridha** [comment]
Hello,
I am using docker command first time, so not much aware of it, i am trying to run deepvariant, tried out almost all possible method to make changes in my command, but i might be missing some minor error in my command, which i may not be able to rectify, The error i am getting is docker: invalid reference format.
See 'docker run --help'.  (**For this i followed the given parameter format in run_deepvariant " --ref: Required. Genome reference to use. Must have an associated FAI index as well. Supports text or gzipped references. Should match the reference used to align the BAM file
    provided to --reads.
")**
it would be great help if anyone help me to sort out this issue.
I am attaching my command here.

docker run -v /media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/Batch1_3runs/1_minimap2_freebayes_Final/Direct_minimap/Bam/run3:/media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/Batch1_3runs/1_minimap2_freebayes_Final/Direct_minimap/Bam/run3 -v /media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/deepvariants_Trial/deepvariant_result:/media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/deepvariants_Trial/deepvariant_result -v /media/manish/Data/Jyoti_Mridha_AIC/My_S/Nanopore_Mito/Mito_Genome_hg38/zip_ref_docker:/media/manish/Data/Jyoti_Mridha_AIC/My_S/Nanopore_Mito/Mito_Genome_hg38/zip_ref_docker google/deepvariant:{BIN_VERSION="1.6.1"} python /media/manish/Data/Jyoti_Mridha_AIC/Program/deepvariant-1.6.1/scripts/run_deepvariant.py --reads /media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/Batch1_3runs/1_minimap2_freebayes_Final/Direct_minimap/Bam/run3/MITO60_sorted.bam --ref /media/manish/Data/Jyoti_Mridha_AIC/My_S/Nanopore_Mito/Mito_Genome_hg38/zip_ref_docker/hg38_chrM.fa.gz --report_title MITO60_Stats --sample_name MITO60 --output_vcf /media/manish/Data/Jyoti_Mridha_AIC/Nanopore_Sequencing/Jyoti_mito_Analysis_GATK/1_FINAL_NANOPORE/deepvariants_Trial/deepvariant_result/ --model_type ONT_R104
docker: invalid reference format.
See 'docker run --help'.
