### ISSUE TITLE
Visualizing Examples colab for TF2

### ISSUE THREAD

**Issue by TerjeNorderhaug** [google/deepvariant#182]
The [visualizing_examples.ipynb colab](docs/visualizing_examples.ipynb) builds on tensorflow 1.13.1 but a small change will make it forward compatible with tensorflow 2.0.0-alpha0: Replace all calls to `tf.FixedLenFeature` with `tf.io.FixedLenFeature` and `tf.parse_single_example` with `tf.io.parse_single_example`. 

Also, optionally replace `xrange` with `range` for compatibility with Python 3.

**Comment by gunjanbaid** [comment]
Hi @TerjeNorderhaug, thanks for the suggestions! We will push out an updated version of the notebook by the next release.
