### ISSUE TITLE
DeepVarient for haploid (bacterial) WGS?

### ISSUE THREAD

**Issue by oschwengers** [google/deepvariant#183]
Dear DeepVariant team,
congrats for this excellent software. Are there any plans to train/offer DeepVariant (or a fork) for haploid (bacterial) genomes? 

As the diploid results are fantastic, I think this might be a very helpful and valuable contribution to the microbial bioinformatics community as well!

In particular, for SNP detection in bacterial pathogens this might be very interesting!

Best regards!

**Comment by AndrewCarroll** [comment]
Hi @oschwengers 

Thank you for your suggestion. I am curious if you have tried to run DeepVariant on haploid bacteria yet? We have investigated in-bred rice strains and found that it has a strong tendency to call homozygous sites as expected from the genome structure.

I was curious if you have evaluated running DeepVariant on bacterial sequencing and seeing whether the results are reasonable. This could be valuable feedback to understand the differences in current performance versus expectations of the field.

There may be some additional complexity in understanding how to express subclonal variants (these might manifest as HET calls). I don't have an intuition about the preferences of the field.

**Comment by oschwengers** [comment]
Hi @AndrewCarroll ,
thanks for your reply and the additional info. I'd love to conduct some deeper investigations but unfortunately, I don't have the time.

So if you could provide some more bacteria related test results, this would be highly appreciated.
Thanks a lot and best regards!

**Comment by mbhall88** [comment]
@oschwengers DeepVariant was included in [this bacterial variant calling benchmark](https://doi.org/10.1093%2Fgigascience%2Fgiaa007).

**Comment by splaisan** [comment]
Dear @oschwengers,

I will soon have to call variants from E.coli bacteria genomes and ONT SUP reads and wonder if I can use the newly introduced haploid option to tell Deepvariant that my bacterial reference genome is haploid, like shown in [this page for X and Y](https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-xy-calling-case-study.md)

`--haploid_contigs "<Ecoli_chromosome>" `

Also, will the _ONT_R104_ model be affected by this extra argument?

The paper referred to above by @mbhall88 dates from 2020 and may not be accurate anymore for the haploid aspect of variant calling in bacteria if DeepVariant has evolved in that domain.

Thanks for your feedback
