### ISSUE TITLE
is it possible to get haplotype sequences fom deep variant?

### ISSUE THREAD

**Issue by dhwani2410** [google/deepvariant#188]
Hello 

Can we get haplotype sequences of the mapped region from deep variant tool

**Comment by akolesnikov** [comment]
Hi dhwani2410,

That functionality is not available. If you could tell me what exactly you're trying to achieve I may have some suggestions for you.

Thank you
Alexey

**Comment by dhwani2410** [comment]
Hi,

I have a region of my interest and I would like to know the haplotype sequence for the same. The region is around 300 bp .

**Comment by akolesnikov** [comment]
Hi,

What you may try is to use other tools to assemble haplotypes from VCF and reads. Here is what I found, for example https://www.biostars.org/p/298635/ (see comment #7)

**Comment by gunjanbaid** [comment]
@dhwani2410 I'll mark this issue as resolved, but feel free to reopen if you have any other questions.
