### ISSUE TITLE
NotImplementedError: can't find current frequency file

### ISSUE THREAD

**Issue by PhilPalmer** [google/deepvariant#191]
Hi,

If I run the following command:
```bash
 dv_make_examples.py \
--cores 16 \
--sample ISO_349.bam \
--ref PlasmoDB-41_Pfalciparum3D7_Genome.fasta.gz \
--reads ISO_349.bam \
--regions PlasmoDB-41_Pfalciparum3D7_Genome_ISO_349.per-base.bed.gz \
--logdir logs \
--examples ISO_349_shardedExamples
```

I get the following output/error:
```bash
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 
  ETA: 0s Left: 16 AVG: 0.00s  local:16/0/100%/0.0s 2019-06-13 12:05:15.630247: W third_party/nucleus/io/sam_reader.cc:537] Unrecognized SAM header type, ignoring: 
  I0613 12:05:15.631112 47747793808000 genomics_reader.py:213] Reading ISO_349.bam with NativeSamReader
  Traceback (most recent call last):
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1188, in <module>
      tf.app.run()
    File "/opt/conda/envs/nf-core-deepvariant-1.0/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
      _sys.exit(main(argv))
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1178, in main
      make_examples_runner(options)
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1074, in make_examples_runner
      resource_monitor = resources.ResourceMonitor().start()
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/resources.py", line 59, in __init__
      self.metrics_pb = self._initial_metrics_protobuf()
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/resources.py", line 72, in _initial_metrics_protobuf
      cpu_frequency_mhz=_get_cpu_frequency(),
    File "/state/partition1/job-1690025/Bazel.runfiles_ISl2VA/runfiles/com_google_deepvariant/deepvariant/resources.py", line 158, in _get_cpu_frequency
      freq = psutil.cpu_freq()
    File "/opt/conda/envs/nf-core-deepvariant-1.0/lib/python2.7/site-packages/psutil/__init__.py", line 1853, in cpu_freq
      ret = _psplatform.cpu_freq()
    File "/opt/conda/envs/nf-core-deepvariant-1.0/lib/python2.7/site-packages/psutil/_pslinux.py", line 701, in cpu_freq
      "can't find current frequency file")
  NotImplementedError: can't find current frequency file
  parallel: This job failed:
  /opt/conda/envs/nf-core-deepvariant-1.0/bin/python /opt/conda/envs/nf-core-deepvariant-1.0/share/deepvariant-0.7.0-0/binaries/DeepVariant/0.7.0/DeepVariant-0.7.0+cl-208818123/make_examples.zip --mode calling --ref PlasmoDB-41_Pfalciparum3D7_Genome.fasta.gz --reads ISO_349.bam --regions PlasmoDB-41_Pfalciparum3D7_Genome_ISO_349.per-base.bed.gz --examples ISO_349_shardedExamples/ISO_349.bam.tfrecord@16.gz --task 10
```

This is using the Nextflow wrapper script [nf-core/deepvariant](https://github.com/nf-core/deepvariant). The pipeline works with other input data. So it seems unlikely that it is a problem with installation or parameters. DeepVariant was installed using Conda & is using v0.7.0. 

Any ideas what the problem is? 

Could it be a problem to do with the input data? Perhaps the organism being used? What is the frequency file which it is referring to?

Any help would be much appreciated

Many thanks in advance,
Phil

**Comment by pichuan** [comment]
Hi Phil,
it doesn't seem like this is relevant to our codebase. I suspect this is something from the wrapper from nf-core. I see that you're also asking on the nf-core GitHub issues, which is likely the right place to ask. 
If you think there might still be some issues related to the DeepVariant codebase, please feel free to add more information and reopen.

**Comment by PhilPalmer** [comment]
Hi,

Sorry, I could be wrong but I suspect this may be relevant to the codebase.

The nf-core script is responsible for passing the parameters correctly to `dv_make_examples.py`. Here the parameters seem to have been passed correctly and the `dv_make_examples.py` script throws an error. 

Do you know why this is the case? Could it be to do with the data? Is it okay that the organism is a *Plasmodium*? Do you know what the frequency file is which it is referring to?

Thanks again,
Phil

**Comment by pichuan** [comment]
Hi Phil,
as you can see from the log you posted, the error actually came from:
```
    File "/opt/conda/envs/nf-core-deepvariant-1.0/lib/python2.7/site-packages/psutil/_pslinux.py", line 701, in cpu_freq
      "can't find current frequency file")
```
If I read this correctly, "frequency" isn't referring to anything DeepVariant related, but is referring to "cpu_freq". I also did a search in the DeepVariant codebase for the string "can't find current frequency file" and I can confirm that error message does not come from us.

It is still possible that this is related to some interaction with the DeepVariant code, but from the information you provide, it's not clear to me how.
And, given that this is at the system level, I don't think it's related to what organism you're providing as the input data.

To understand whether your input data works on DeepVariant code or not, the best way is probably to try it with just the DeepVariant code. If that doesn't work, it'll be more clear whether there might be different issues.

If the data you're running on is publicly accessible, I'm also happy to try running DeepVariant on it. Let me know.

**Comment by pichuan** [comment]
Hi Phil,
an update:
@cmclean pointed out that it comes from this line of our code:
https://github.com/google/deepvariant/blob/aff131aac3bd0cb63ee8314e32bcbf5590987fb8/deepvariant/resources.py#L158

We're getting this information for debugging purpose only (DeepVariant outputs some information about the run in case developers need to remember how the run was done). 
I suspect your run was done on a system where the method wasn't implemented.

One possible fix is to make our code more robust is to:
```
  try:
    freq = psutil.cpu_freq()
    return freq.current if freq is not None else 0.0
  except NotImplementedError:
    return 0.0
```

We'll fix this internally soon, and it should come out next time we make a release.

Thanks for reporting the issue!
