### ISSUE TITLE
Model_train output

### ISSUE THREAD

**Issue by melkerdawy** [google/deepvariant#192]
I am trying to make sense of the output of model_train. The models generated by model_train has an index at the end of it. What does this index mean?

In other words, If I have a model named model.ckpt-4854. What does this 4854 refer to?

Thanks in advance!

**Comment by pichuan** [comment]
The number is referring to the number of steps in training when this checkpoint is saved.
You can see https://www.tensorflow.org/guide/checkpoints for more information.

**Comment by melkerdawy** [comment]
I am working with singularity on HPC and it is so slow compared with DeepVariant docker image. It took 3 days to reach model.ckpt-4854. Do you have any recommendations to change some parameters (like the batch size, keep_checkpoint_every_n_hours, or save_interval_secs) in order to speed up model_train? 
 
The parameters I am using is here: 

`INPUT_DIR="${PWD}/input"
OUTPUT_DIR="${PWD}/output"
LOG_DIR="${OUTPUT_DIR}/logs"
OUTPUT_DIR_TRAINING = "${OUTPUT_DIR}/training_output"
mkdir -p "{OUTPUT_DIR_TRAINING}"
WES_PRETRAINED_MODEL = "${PWD}/models/wes/model.ckpt"

singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/ --bind
input:${OUTPUT_DIR}/ \
deepvariant.simg \
/opt/deepvariant/bin//model_train \
--dataset_config_pbtxt = "${OUTPUT_DIR}/training_set.dataset_config.pbtxt" \
--train_dir = "${OUTPUT_DIR_TRAINING}" \
--keep_checkpoint_every_n_hours = 0.05 \
--model_name="inception_v3" \
--number_of_steps=50000 \
--save_interval_secs=300 \
--batch_size=512 \
--learning_rate=0.01 \
--start_from_checkpoint = "${WES_PRETRAINED_MODEL}" >
"${LOG_DIR}/train.log" 2>&1 &`

**Comment by pichuan** [comment]
Hi @melkerdawy 
are you using CPUs only? There is a reason why our current training case study uses TPU. If you can't run with TPU, at least considering using GPUs to train. Fundamentally you need a powerful enough processing unit to train an inception v3 model.

**Comment by melkerdawy** [comment]
I will try to use GPUs. Thanks for the advice. I have one more question. I just wanted to make sure that model_train use all the available CPUs or GPUs in the machine I am using by default. In other words, If I dont use GNU parallel with model_train and model_eval, it wont utilize only one core by default.

**Comment by pichuan** [comment]
Hi @melkerdawy ,
currently our code doesn't support training with multiple GPUs. I haven't really tried training with CPUs, so I don't know whether model_train automatically utilize multiple CPUs or not. (We know that `call_variants` does. But I've never used CPU for training.)
If you want, you can try running it and see how many CPUs it utilizes. However, I don't recommend training with CPUs becaues I think it'll be really slow.

And, using GPU parallel with training also won't work. In the case if training, it's not easily parallelizable like inference.

The most practical path forward is probably to get a really powerful GPU and see how well that works for you. I've been hoping to benchmark for training on GPU as well, but haven't got time to do so. If you have some results you want to share, that will be great.
