### ISSUE TITLE
Running with gVCF output on Google Cloud

### ISSUE THREAD

**Issue by saliksyed** [google/deepvariant#193]
I'm trying to output gVCF's via DeepVariant as described by the tutorial here: https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-gvcf-support.md  

Is there a way that I could just modify the gcp_deepvariant_runner.py script (linked below) rather than having to manually run the commands step by step? I have many BAM files to process and running the pipeline manually is intractable.

https://github.com/googlegenomics/gcp-deepvariant-runner/blob/master/gcp_deepvariant_runner.py

I'm guessing I would need to fork the gcp-deepvariant-runner repo, edit the python file, then push the new repo to some sort of container registry? Any guidance here would be much appreciated.

**Comment by samanvp** [comment]
> Is there a way that I could just modify the gcp_deepvariant_runner.py script 

Yes, you can easily make deepvariant_runner to generate gVCF output by using `--gvcf_outfile` flag, please refer to [our documentation](https://cloud.google.com/genomics/docs/tutorials/deepvariant#genomic_vcf_gvcf_configuration) for more details.

> I'm guessing I would need to fork the gcp-deepvariant-runner repo

That's one way to do it, however, the easier way is to use our docker image; in that case launching DeepVariant will be as simple as running a `gcloud ...` command. Again please refer to [our documentations](https://cloud.google.com/genomics/docs/tutorials/deepvariant#before_you_begin) for more details.
The only issue at the moment is that deepvariant_runner is still working with previous version of DeepVariant (0.7.2) and we are in the process of releasing a new docker image that will be compatible with the latest DeepVairant (0.8.8).

Please let me know if you have any difficulties with deepvariant_runner.

**Comment by pichuan** [comment]
Thanks @samanvp for the answer!

@saliksyed the GCP runner is actually in a separate repo. To ensure the developers notice your questions, you might consider posting future questions related to GCP runner in https://github.com/googlegenomics/gcp-deepvariant-runner/issues . 

I'll close this issue now.

**Comment by saliksyed** [comment]
Thank you guys. Yes I can use 0.7.2 for my purpose. Thanks for the followup. I will post future questions on the runner forum.
