### ISSUE TITLE
Using model_eval after model_train not simultaneously 

### ISSUE THREAD

**Issue by melkerdawy** [google/deepvariant#198]
I know now that I should have run model_eval simultaneously with model_train. However, I did not do that and it is so hard for me to repeat the model_train step given limited computational resources.

Now, I have a folder full of models but when I run model_evelm it just evaluates only the last model. 

Is there any parameters to change or a turn around this issue to make model_eval evaluate multiple models after model_train is finished.

I really appreciate your help and support

**Comment by akolesnikov** [comment]
Hi,

Evaluation is done using [Estimator class](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#evaluate)

You may create a simple script calling Estimator.evaluate in a loop passing different checkpoints.

> checkpoint_path: Path of a specific checkpoint to evaluate. If None, the latest checkpoint in model_dir is used. If there are no checkpoints in model_dir, evaluation is run with newly initialized Variables instead of ones restored from checkpoint.

Hope it helps.
Alexey
