### ISSUE TITLE
Documentation on how to use DeepVariant without Google Cloud

### ISSUE THREAD

**Issue by Arkanosis** [google/deepvariant#2]
Hi,

All documentation linked from the README.md mentions Google Cloud platform, but I've found no indication on how to use DeepVariant on a local computer only. Is it because Google Cloud is mandatory (then it would be great to mention it right from the beginning of the documentation)? Or would it be possible to add a quickstart for non-Google Cloud usage?

Thanks,

**Comment by pichuan** [comment]
Hi Arkanosis,
thanks for your question!
It is not mandatory to run DeepVariant on Google Cloud. We use Google Cloud Platform as an example in our quick start and case study to show how you can get a machine easily and install DeepVariant correctly. But you should be able to use DeepVariant outside Google Cloud as well.
However, note that the current instructions are for Ubuntu 16. If you're on different OS or different versions of Ubuntu, it is possible you need to make some changes to install things correctly. Please feel free to let us know if you encounter any issues.
Thanks!
-pichuan

**Comment by Arkanosis** [comment]
Hi @pichuan, thank you very much for your kind response!

That's great to hear, and Ubuntu 16 is a fine target. I'm eager to see how it compares to regular callers on our data.

Thanks again :)
