### ISSUE TITLE
Is it useful to plants？

### ISSUE THREAD

**Issue by fengcong3** [google/deepvariant#200]
Is it useful to plants？Such as wheat

**Comment by AndrewCarroll** [comment]
Hi @fengcong3 

DeepVariant has been applied to plant species. In the case of rice, there was good evidence of high accuracy superior [some results in this blog](https://cloud.google.com/blog/products/data-analytics/analyzing-3024-rice-genomes-characterized-by-deepvariant)

However, these rice genomes were diploid and with a similar variant density of humans.

DeepVariant is currently written to be a diploid variant caller. So in cases with polyploid organisms (which includes wheat), it is not yet clear how DeepVariant will perform. However, I am also not sure how other variant callers perform on polyploid samples. If you (or anyone) knows current polyploid callers for wheat, I would like to know and to run benchmarks between the two.

Finally, it is possible to train DeepVariant models for a specific genome. We have a previous example of this in mosquitos [see our blog](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/). We hope to explore training a general plant model or a general non-human model in the future.

**Comment by tyrserleu** [comment]
@AndrewCarroll Excuse me, I was wondering if it is possible to use DV to call SNPs and indels in plum resequencing data in 2025?

**Comment by AndrewCarroll** [comment]
Hi @tyrserleu 

Yes, it should be possible. And for the plum genome characteristics I am aware of (small genome of ~250 Mb), I think it should work well. I see a 2025 paper with resequencing reporting ~2M variants per sample, which implies ~4x the variant density seen in humans. That seems quite reasonable. I think the default model will work.

If you try DeepVariant on plum I'd be interested in your findings. 

Thank you,
Andrew
