### ISSUE TITLE
PacBio evaluation

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#201]
I ran an eval on chr20 of HG002 for PacBio CCS Sequel 2 data downloaded from https://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_SequelII_CCS_11kb/

The results are different from that given in the following blog:
https://google.github.io/deepvariant/posts/2019-01-14-highly-accurate-snp-and-indel-calling-on-pacbio-ccs-with-deepvariant/

Specifically, the indel results are improved by ~4% (F1 is 0.982) and SNV results are largely unchanged. I wonder what is the reason for the difference in the results. Are the two datasets (the one I mentioned, and the one in the blog) the same? If they are the same, has the model been improved since the publication of the blog?

**Comment by AndrewCarroll** [comment]
Hi @anands-repo 

Thank you for running the evaluation! The work detailed in the blog and in the publication (https://www.biorxiv.org/content/biorxiv/early/2019/01/23/519025.full.pdf) represent our initial efforts to train a model on PacBio data.

Subsequent to that publication, PacBio generated more extensive training Sequel II data. We used this data to build more robust training datasets across a diverse range of coverage, insert sizes, and machine runs. This is the model which has been released in version 0.8.

**Comment by anands-repo** [comment]
Thanks for the clarification.

Is the new PacBio training data openly available? I apologize if this is described somewhere and I didn't find it.

**Comment by AndrewCarroll** [comment]
The full content of that data is not publicly available. There are additional datasets available at the Genome in a Bottle FTP. These include:

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/AshkenazimTrio/HG002_NA24385_son/PacBio_SequelII_CCS_11kb/

which represents the BAM file used in our case study evaluation. This data is used for training (excluding chr20 for evaluation)

And HG005 - 
 
ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/ChineseTrio/HG005_NA24631_son/PacBio_SequelII_CCS_11kb/

And HG001/NA12878 -

ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/PacBio_SequelII_CCS_11kb/

The above files for HG001 and HG005 are not used for training or evaluation of DeepVariant at this time.

**Comment by anands-repo** [comment]
Apologize for the late response. Thanks for the information. I will look into these.
