### ISSUE TITLE
Same site, different calls (non deterministic behaviour?)

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#202]
Hello! 
I am comparing 2 vcf files of 2 different samples. I noticed that deepvariant had a tendency, for the same site and the same genomic variant, present in the 2 samples (as visually checked by looking at the bam alignment) to call the site differently for each sample. 
Here is what I mean, the site of interest is highlighted with ** 
Sample1: 
```
Chrom_6       5425277 .       G       A       47.5    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:48:101:45,54:0.534653:47,0,68
Chrom_6 5425341 .       T       C       15.3    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:15:105:51,53:0.504762:15,0,54
Chrom_6 5425342 .       A       T       34.2    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:34:104:50,53:0.509615:34,0,150
Chrom_6 5425399 .       TGG     T       33.2    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:33:108:47,58:0.537037:33,0,61
Chrom_6 **5425403**    .       T       TTC     36.2    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:36:105:47,57:0.542857:36,0,61
Chrom_6 5425421 .       T       C       39.4    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:39:105:46,59:0.561905:39,0,62
Chrom_6 5425460 .       G       A       30.4    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:30:106:46,56:0.528302:30,0,65
Chrom_6 5425539 .       A       C       17.5    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:17:96:44,52:0.541667:17,0,47
Chrom_6 5425544 .       TA      T       37.6    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:37:94:45,48:0.510638:37,0,52

```
Sample 2 
```
Chrom_6     5425208 .       C       T       44.3    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:44:42:22,20:0.47619:44,0,56
Chrom_6 5425277 .       G       A       32      PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:32:45:28,17:0.377778:31,0,57
Chrom_6 **5425401** .       G       T       30.1    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:30:60:46,14:0.233333:30,0,50
Chrom_6 **5425402** .       G       T       18.3    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:18:59:46,13:0.220339:18,0,47
Chrom_6 **5425403**    .       T       C       13.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:14:59:46,13:0.220339:13,0,45
Chrom_6 5425421 .       T       C       6.8     PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:7:63:50,13:0.206349:5,0,40
Chrom_6 5425460 .       G       A       8.4     PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:8:61:48,12:0.196721:7,0,40
Chrom_6 5425539 .       A       C       14.7    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:15:45:36,9:0.2:14,0,45
Chrom_6 5425555 .       G       A       20.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:21:44:34,10:0.227273:20,0,50
```
As you see, the event which is a change of 3 consecutive nucleotides, is called in one sample as a single T to TTC event and in the other sample as 3 SNPs. 
This is annoying if one wants to compare the 2 samples, as simple comparison scripts will not understand those events are in fact identical. 

We ran GATK in parallel and GATK calls the event in both sample as T to TTC. 

The only difference between the 2 samples is the sequencing coverage which is higher in Sample1. 
I also looked into the gVCF and the same phenomenom happens.
Sample 1:
```
Chrom_6	5425343	.	G	<*>	0	.	END=5425398	GT:GQ:MIN_DP:PL	0/0:50:104:0,300,2999
Chrom_6	5425399	.	TGG	T,<*>	33.2	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:33:108:47,58,0:0.537037,0:33,0,61,990,990,990
Chrom_6	5425402	.	G	<*>	0	.	END=5425402	GT:GQ:MIN_DP:PL	0/0:50:106:0,180,2759
Chrom_6	**5425403**	.	T	TTC,<*>	36.2	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:36:105:47,57,0:0.542857,0:36,0,61,990,990,990
Chrom_6	5425404	.	A	<*>	0	.	END=5425420	GT:GQ:MIN_DP:PL	0/0:50:106:0,300,2999
Chrom_6	5425421	.	T	C,<*>	39.4	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:39:105:46,59,0:0.561905,0:39,0,62,990,990,990
Chrom_6	5425422	.	C	<*>	0	.	END=5425459	GT:GQ:MIN_DP:PL	0/0:50:105:0,180,2759
Chrom_6	5425460	.	G	A,<*>	30.4	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:30:106:46,56,0:0.528302,0:30,0,65,990,990,990
```
Sample 2:

```
Chrom_6	5425342	.	A	T,<*>	3	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:3:49:34,15,0:0.306122,0:0,0,41,990,990,990
Chrom_6	5425343	.	G	<*>	0	.	END=5425400	GT:GQ:MIN_DP:PL	0/0:50:64:0,192,1919
Chrom_6	**5425401**	.	G	T,<*>	30.1	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:30:60:46,14,0:0.233333,0:30,0,50,990,990,990
Chrom_6	**5425402**	.	G	T,<*>	18.3	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:18:59:46,13,0:0.220339,0:18,0,47,990,990,990
Chrom_6	**5425403**	.	T	C,<*>	13.9	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:14:59:46,13,0:0.220339,0:13,0,45,990,990,990
Chrom_6	5425404	.	A	<*>	0	.	END=5425420	GT:GQ:MIN_DP:PL	0/0:50:73:0,189,2129
Chrom_6	5425421	.	T	C,<*>	6.8	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:7:63:50,13,0:0.206349,0:5,0,40,990,990,990
Chrom_6	5425422	.	C	<*>	0	.	END=5425459	GT:GQ:MIN_DP:PL	0/0:50:72:0,228,2279
Chrom_6	5425460	.	G	A,<*>	8.4	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:8:61:48,12,0:0.196721,0:7,0,40,990,990,990
```
Is it normal/expected from deepvariant?

**Comment by pichuan** [comment]
Hi @aderzelle 
First of all, when I first think of "deterministic" behavior, I usually think about whether the exact same input yields the same results. Which we've made effort to make sure that running on the same input on the same machine should have deterministic behavior. If you have noticed non-deterministic behavior on the same sample, please do let us know.

That said, you're absolutely right. These two represent the exact same event, but simple comparison scripts will not understand those events are in fact identical.

```
90123
TGGGT
T--GTTC  <-- Sample 1
TGTTC    <-- Sample 2
```

I think other users have reported to us in the past. So far we haven't looked closely into the code logic yet, because we mostly rely on tools such as `hap.py` for normalizing these during evaluation. So, this is a known behavior but haven't been investigated yet. And I do agree that it'll be good if we can behavior more consistently. 

I will file an internal issue to track this (if we don't have one already). I can't guarantee when it'll be addressed though. If you have more suggestions on whether one representation might be better than the other, let me know.

I'm closing this issue, but feel free to add your thoughts here. Thank you for reporting this!

**Comment by aderzelle** [comment]
thanks for you reply, 
I am just commenting to say that indeed, the use of "non deterministic" was not adequate.
