### ISSUE TITLE
How is QUAL calculated?

### ISSUE THREAD

**Issue by bballew** [google/deepvariant#206]
Hi there!

How is the QUAL score calculated when using DeepVariant?  E.g., with GATK, it's the phred-scaled posterior probability of a variant being homozygous ref.   I've been comparing known true positives detected by both HaplotypeCaller and DeepVariant, and found that DV's QUAL score is approximately correlated with HC's QualByDepth, so I'm wondering whether the QUAL score is already normalized by depth or is calculated in some other way.

Thanks!
Bari

**Comment by akolesnikov** [comment]
Hi Bari,

QUAL score is not normalized by depth. It is calculated exactly as you defined. You could see it in the code in postprocess_variants.py, compute_quals function.

Thanks.
Alex

**Comment by gunjanbaid** [comment]
@bballew I will close this issue for now, but feel free to reopen if you have any other questions. [Here is a link](https://github.com/google/deepvariant/blob/r0.8/deepvariant/postprocess_variants.py#L308) to the `compute_quals` function.
