### ISSUE TITLE
make_examples Runtime with CCS

### ISSUE THREAD

**Issue by wharvey31** [google/deepvariant#208]
I am currently running DeepVariant on CCS data after installing via Docker on an AWS instance. The make_examples step of the pipeline is taking much longer than expected. I have performed this in the past with 30X Illumina Data, and it has taken a few hours. This has been running for about a week on 23X coverage PacBio HiFi with a 16 core machine (CPU optimized), and I was wondering if that was expected. Below, I have the command issued:

`sudo time seq 0 $((N_SHARDS-1)) |   sudo parallel --eta --halt 2 --joblog "${LOGDIR}"/log --res "${LOGDIR}"   sudo docker run   -v ${HOME}:${HOME}   -v "${INPUT_DIR}":"/input"   -v "${OUTPUT_DIR}:/output"   gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}"   /opt/deepvariant/bin/make_examples   --mode calling   --ref=/input/ucsc.hg38.no_alts.fasta   --reads=/input/hg00733_ccs_to_hg38.bam   --examples "${OUTPUT_DIR}/examples.tfrecord@${N_SHARDS}.gz"   --task {}`

All variables listed have been set as expected. When I ssh in to the node I can see that it is running python in parallel and writing to the proper output files, but it is just taking forever to process anything.

Any help would be greatly appreciated!

**Comment by akolesnikov** [comment]
PacBio reads are too long to perform a local assembly on them, therefore --norealign_reads flag has to be added.

**Comment by akolesnikov** [comment]
There is a case study for PacBio data which may be helpful https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-pacbio-model-case-study.md

**Comment by wharvey31** [comment]
Thank you!!
