### ISSUE TITLE
CPU with SSE (Streaming SIMD Extensions) instruction

### ISSUE THREAD

**Issue by hamidqaedi** [google/deepvariant#212]
HI,
In spite of great interest, desecrated to use DeepVariant because of the CPU issue.

I found to have a machine with  Intel(R) Xeon(R) CPU E7- 8870  @ 2.40GHz processors. As I found on the company webpage it is not an AVX -rather to be SSE- processor.
Is there any way/trick to use DeepVariant on such machine?
Thank you in advance

**Comment by sidharthgoel** [comment]
Hi, I'm not sure I fully understand the question -- do any of the [3 Official Solutions](https://github.com/google/deepvariant#official-solutions) work for you? Using [the docker image](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md) is the recommended way, but there are other options listed as well.
If you don't want that, and the pre-built binary option (option 3) doesn't work, there is also the option of building your own binary from source (option 2).

**Comment by pgrosu** [comment]
@hamidqaedi Just update the architecture to  `--copt=-march=native` in [settings.sh](https://github.com/google/deepvariant/blob/r0.8/settings.sh#L102), and use the same option when compiling Tensorflow from source and you should be fine.

**Comment by hamidqaedi** [comment]
Hi @pgrosu ,
Thank you for reply. Iwill check and let you know about.

@sidharthgoel ,
Actually the question is , Does Deepvariant works on a cpu like what i have on my machine (Intel(R) Xeon(R) CPU E7- 8870 @ 2.40GHz processors)?  

Thank you guys for your time
Hamid
