### ISSUE TITLE
Regarding treating ambiguous/partially overlapping read alignments

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#213]
I have two questions. 

The first is about ambiguous read alignments. This can happen, for example, in a region of homopolymer repeats (or other short repeats).

ACTGTACTAC**X**GGGGGGAT    (Reference sequence: "X" indicates an inserted base)
ACTGTACTACGGGGGGGAT          (Read0)
ACTGTACTACGGG                        (Read1)

In this case, Read1 could be interpreted to either support the insertion or not. BWA would choose to ignore the insertion, since it would be penalized in SW alignment. I understand that DeepVariant does internal realignment of reads. However, even after realignment, Read1 would support one or the other allele (reference/insertion) exclusively. In reality, we cannot attribute Read1's support to either allele exclusively (prior to variant calling) because we do not have sufficient information.

Could you please confirm that in these cases DeepVariant counts the support from the ambiguous read (Read1 in this case) for only one of the alleles, and not both? I am not speaking about the CNN itself, but the algorithms in DeepVariant up until the construction of the input feature maps for the CNN.

The second question I have is regarding reads which partially overlap alleles. In allelecounter.cc, I find that supports for alleles are determined based on their cigar strings. However, for insertion alleles that are, say 30-50 bp long, there may be a plurality of reads which partially overlap with the non-reference allele, because a read terminates or starts its alignment within the allele. In these cases, cigar strings do not indicate support for the complete allele, but only for a part of it. Are these reads considered to be non-supporting? If, instead of counting support from cigar strings, the original contigs in the local reassembly were used, such problems wouldn't arise. However, my understanding of allelecounter.cc code is that such information is not used. Also, I believe this problem, if it exists, wouldn't affect deletions, because the partial overlap would then be with the reference allele. Please correct me if I am wrong.

Thanks for your patience.

**Comment by akolesnikov** [comment]
HI,

1) DeepVariant does not treat homopolymer repeats differently. So, to answer your question DeepVariant assign read to one of the alleles in this case. It is a known problem and we have plans to address it. If read does not completely overlap a homopolymer repeat then it should not be counted.

2) DeepVariant does local reassembly for some regions (decided by algorithm). In that case reads are realigned to the haplotype, not the reference. In your example with long insertion realigned read cigar will correctly support part of the insertion, and then allele_counter will work with the "correct" cigar.

**Comment by anands-repo** [comment]
It is an interesting point about homopolymer reads that they shouldn't be considered at all. I will think about it further. My thoughts were that the CNN probably filters out such information, and no additional gain would be available by doing this.

Thanks for confirming that partial insertions are considered and not discarded. However, there are still cases where a site has two alternative insertion alleles (say, CT, and CTCTTT; both alleles are supported by reads covering both the left and right positions of the insertion), where it may not be possible to determine which allele a partially overlapping read supports (the read terminates with an insertion of CT). But this may be an extremely rare occurrence and one that is not considered relevant.

**Comment by akolesnikov** [comment]
Resulting image that is fed into CNN contains multiple layers. Two of those are 'Read supports allele', and 'Read supports ref'. By removing an ambiguous read we may slightly  improve the accuracy (in theory)

Yes, your last example is difficult to make it right and we don't have a near future plans to address those.

**Comment by anands-repo** [comment]
I see. Thank you. Your responses are very helpful.
