### ISSUE TITLE
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine

### ISSUE THREAD

**Issue by hamidqaedi** [google/deepvariant#217]
Dear Developer,

I am going to use DeepVariant for variant calling. I have followed the instruction provided [here](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md), to install the tool. After downloading the all needed sample data I run the command:
```
sudo docker run \
> -v "${INPUT_DIR}":"/input" \
> -v "${OUTPUT_DIR}:/output" \
> gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
> /opt/deepvariant/bin/run_deepvariant \
> --model_type=WGS \
> --ref=/input/ucsc.hg19.chr20.unittest.fasta \
> --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
> --regions "chr20:10,000,000-10,010,000" \
> --output_vcf=/output/output.vcf.gz \
> --output_gvcf=/output/output.g.vcf.gz \
> --num_shards=1 
```
I faced the error:
```
***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}

2019-09-11 14:44:44.030589: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

real	0m2.456s
user	0m1.443s
sys	0m1.926s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 235, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 215, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/ucsc.hg19.chr20.unittest.fasta" --reads "/input/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --task {}' returned non-zero exit status 1
```

I googled for solution also asked you before and found may be compiling from source code would works for me. I FAILED TO DO THIS.
Is still any chance to use install and work with DeepVariant?

Please consider that a number of potential users -like me-  are biologist with limited knowledge of informatics. 
Thanks in advance.
Hamid

**Comment by akolesnikov** [comment]
Hi Hamid,

**Short answer**: There is no pre-built docker that would work on an old hardware (with no AVX support).

**Long answer**: It may be possible to run DeepVariant with custom TensorFlow library (this is what I found online https://stackoverflow.com/questions/53723217/is-there-a-version-of-tensorflow-not-compiled-for-avx-instructions). Then you may follow directions [here](https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-build-test.md) to manually build DeepVariant and then follow instructions to run DeepVariant without docker [here](https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-quick-start.md). To use custom version of TensorFlow you would need to modify ./run-prereq.sh. Unfortunately there is no guaranty this will work. 

Another option is to try running DeepVariant Quick Study on Google Cloud Platform. It is fairly straight forward to set up a project and start creating virtual machines on Google Cloud. You may start from [here](https://cloud.google.com/compute/docs/instances/create-start-instance).
