### ISSUE TITLE
import error for GLIBCXX_3.4.21

### ISSUE THREAD

**Issue by ZihuaLiu666** [google/deepvariant#22]
When I run make-example.zip, the error shows up... Please fix it for me ;- )

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/Bazel.runfiles_YSzuwd/runfiles/protobuf_archive/python/google/protob
uf/pyext/_message.so)

**Comment by ThomasColthurst** [comment]
What OS & version are you running?  (i.e., what is the output of uname -a ?)

This error frequently shows up when using something other than Ubuntu 16.

-Thomas C

**Comment by ZihuaLiu666** [comment]
Hi, Thomas
The output of uname -a is

Linux cs-6000-devshell-vm-d5fc574d-7d85-4a60-b2ee-5248f8d10e41 3.16.0-4-amd64 #1 SMP Debian 3.16.51-2 (2017-12-03) x86_64 GNU/Linux

I run it on Google Cloud Platform

**Comment by ThomasColthurst** [comment]
Yeah, that's a Debian instance.  You will need an Ubuntu 16 instance.

There are instructions for configuring an Ubuntu 16 instance in
https://github.com/google/deepvariant/blob/master/docs/deepvariant-case-study.md

The relevant command is

gcloud beta compute instances create "${USER}-deepvariant-casestudy"  \
--scopes "compute-rw,storage-full,cloud-platform" \
--image-family "ubuntu-1604-lts" --image-project "ubuntu-os-cloud" \
--machine-type "custom-64-131072" \
--boot-disk-size "300" --boot-disk-type "pd-ssd" \
--boot-disk-device-name "deepvariant-casestudy" \
--zone "us-west1-b"

**Comment by ZihuaLiu666** [comment]
Thanks for your quick replies!
