### ISSUE TITLE
De novo variant calling

### ISSUE THREAD

**Issue by bopohdr** [google/deepvariant#220]
I am using Deepvariant (v.0.7.2) for germline calling and now I have a trio, for which I need to identify de novo variants. 

I am bit concerned, as based on this pre-print, it seems like Deepvariant is extremely bad for de novo variant calling:
https://www.biorxiv.org/content/10.1101/456103v1.full 

Are there any recommendations how to better do it ? Or maybe somebody has an experience with that ? 

I was thinking of combining gVCFs using GLnexus and then try out GATK genotype refinement and de novo annotating.

Thanks !

**Comment by AndrewCarroll** [comment]
Hi @bopohdr 

I cannot speak to the dataset referenced in this paper, as it is not available, and I am not sure how merging would have been performed, and the paper references an earlier DeepVariant version. However, a higher de novo rate of DeepVariant relative to other callers is not something that we observe in the investigations we have conducted.

I am attaching (if they will upload) two VCF files for the Oslo University HG002-HG003-HG004 trio available in Genome in a Bottle FTP. The DeepVariant trio is called with DeepVariant exome model and merged with GLnexus. The GATK4 trio is called with HaplotypeCaller and merged with GenotypeGVCFs.

In these trios, DeepVariant has 87 de novo calls where the child is not 0/0 but both parents are 0/0
The GATK4 trio has 270 de novo cases with the same criteria.

We have a set of documentation for best practices in merging a trio that we are hoping to release in the near future. If you would like me to share that with you privately now, you can reach out directly at awcarroll@google.com

Thanks,
Andrew

[deepvariant.cohort.vcf.gz](https://github.com/google/deepvariant/files/3623783/deepvariant.cohort.vcf.gz)
[gatk4.cohort.vcf.gz](https://github.com/google/deepvariant/files/3623784/gatk4.cohort.vcf.gz)
