### ISSUE TITLE
DeepVariant docker image doesn't find the reference genome. 

### ISSUE THREAD

**Issue by rogeriobioinfo** [google/deepvariant#223]
Dears,
 I'm working on Ubuntu 16.04.5 LTS, and Docker API version 1.39,
I have downloaded the data according to the script:

INPUT_DIR="${PWD}/quickstart-testdata"
DATA_HTTP_DIR="https://storage.googleapis.com/deepvariant/quickstart-testdata"

mkdir -p ${INPUT_DIR}
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/NA12878_S1.chr20.10_10p1mb.bam
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/NA12878_S1.chr20.10_10p1mb.bam.bai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.bed
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.fai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz.fai
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/ucsc.hg19.chr20.unittest.fasta.gz.gzi

I have installed the DeepVariant image according to: 

BIN_VERSION="0.8.0"
sudo apt -y update
sudo apt-get -y install docker.io
sudo docker pull gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}"

When I run the script test:  

OUTPUT_DIR="${PWD}/quickstart-output"
INPUT_DIR="${PWD}/quickstart-testdata"
mkdir -p "${OUTPUT_DIR}"

BIN_VERSION="0.8.0"
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}"
 \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \ 
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --num_shards=1

The following error happens:

FATAL Flags parsing error: flag --ref=None: Flag --ref must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.
./run_deepvariant.sh: line 12: --ref=/input/ucsc.hg19.chr20.unittest.fasta: No such file or directory

I tried it on three different computers, and the error was the same.
There is a previous issue in this forum (https://github.com/google/deepvariant/issues/181) where the user did not set BIN_VERSION variable correctly, and **IT IS NOT MY CASE**!!!!

I tested if the volumes were mounted correctly, according to the script:
OUTPUT_DIR="${PWD}/quickstart-output"
INPUT_DIR="${PWD}/quickstart-testdata"
sudo docker run \
  -i \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  gcr.io/deepvariant-docker/deepvariant:0.8.0 \
  find /input

And the result was:
/input/NA12878_S1.chr20.10_10p1mb.bam
/input/NA12878_S1.chr20.10_10p1mb.bam.bai
/input/test_nist.b37_chr20_100kbp_at_10mb.bed
/input/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz
/input/test_nist.b37_chr20_100kbp_at_10mb.vcf.gz.tbi
/input/ucsc.hg19.chr20.unittest.fasta
/input/ucsc.hg19.chr20.unittest.fasta.fai
/input/ucsc.hg19.chr20.unittest.fasta.gz
/input/ucsc.hg19.chr20.unittest.fasta.gz.fai
/input/ucsc.hg19.chr20.unittest.fasta.gz.gzi

It means that all files are in the mounted Docker volume /input 

Thanks so much for any help,
Rogério

**Comment by weisystak** [comment]
There is some invisible char behind `\` that  immediately before `--ref` .  You should delete it.

**Comment by pichuan** [comment]
Thanks @rogeriobioinfo for a detailed report.
I was able to run with your setup, and
```
sudo docker run \
-v "${INPUT_DIR}":"/input" \
-v "${OUTPUT_DIR}:/output" \
gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=/input/ucsc.hg19.chr20.unittest.fasta \
--reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
--regions "chr20:10,000,000-10,010,000" \
--output_vcf=/output/output.vcf.gz \
--output_gvcf=/output/output.g.vcf.gz \
--num_shards=1
```
works for me as well.

As @weisystak suggested, can you check for the invisible char and try again? Thanks!

**Comment by rogeriobioinfo** [comment]
Dears, 
I eliminate all "\" and ran the script in a single command line, it works now
thanks a lot
