### ISSUE TITLE
ValueError: Reference contigs span 3270284521 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. 

### ISSUE THREAD

**Issue by matthale16** [google/deepvariant#225]
Attempting to run variant analysis on bam file aligned to GRCh38.p13 using GRCh38.p13 as the reference but receiving the error below from make_examples.  Running in Google Cloud with the following script.sh:

#!/bin/bash
set -euo pipefail
# Set common settings.
PROJECT_ID=mbh-deepvariant-1
OUTPUT_BUCKET=gs://mbh-deepvariant-ouput-vcf
STAGING_FOLDER_NAME=staging_folder1
OUTPUT_FILE_NAME=HR090610illuminagr38DeepVariant.vcf
# Model for calling whole genome sequencing data.
MODEL=gs://deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-wgs_standard
IMAGE_VERSION=0.8.0
DOCKER_IMAGE=gcr.io/deepvariant-docker/deepvariant:"${IMAGE_VERSION}"
COMMAND="/opt/deepvariant_runner/bin/gcp_deepvariant_runner \
  --project ${PROJECT_ID} \
  --zones us-west2-* \
  --docker_image ${DOCKER_IMAGE} \
  --outfile ${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME} \
  --staging ${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME} \
  --model ${MODEL} \
  --bam gs://mbh-bam-files1/HR090610.final.bam \
  --bai gs://mbh-bam-files1/HR090610.final.bam.bai \
  --ref gs://mbh-bam-files1/GCA_000001405.28_GRCh38.p13_genomic.fa \
  --shards 224 \
  --make_examples_workers 7 \
  --make_examples_cores_per_worker 32 \
  --make_examples_ram_per_worker_gb 60 \
  --make_examples_disk_per_worker_gb 200 \
  --call_variants_workers 7 \
  --call_variants_cores_per_worker 32 \
  --call_variants_ram_per_worker_gb 60 \
  --call_variants_disk_per_worker_gb 200 \
  --gcsfuse"
# Run the pipeline.
gcloud alpha genomics pipelines run \
    --project "${PROJECT_ID}" \
    --service-account-scopes="https://www.googleapis.com/auth/cloud-platform" \
    --logging "${OUTPUT_BUCKET}/${STAGING_FOLDER_NAME}/runner_logs_$(date +%Y%m%d_%H%M%S).log" \
    --regions us-west2 \
    --docker-image gcr.io/cloud-lifesciences/gcp-deepvariant-runner \
    --command-line "${COMMAND}"

The log file is attached, but part of it is also pasted below.  Is it saying that there is a mismatch between the .fai and .fa files for the reference or between the reference and the bam file? The .fai file was created from the .fa file using samtools index command. 

ValueError: Reference contigs span 3270284521 bases but only 0 bases (0.00%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: "CM000663.2" is 248956422 bp and IS MISSING, "KI270706.1" is 175055 bp and IS MISSING, "KI270707.1" is 32032 bp and IS MISSING, "KI270708.1" is 127682 bp and IS MISSING, "KI270709.1" is 66860 bp and IS MISSING, "KI270710.1" is 40176 bp and IS MISSING...

Any feedback would be appreciated.  Thanks, -Matt

[staging_folder1_logs_make_examples_7.txt](https://github.com/google/deepvariant/files/3700231/staging_folder1_logs_make_examples_7.txt)

**Comment by akolesnikov** [comment]
Contig names in reference and input BAM files have to match. What happened is basically no common contigs between reference and BAM were found.
