### ISSUE TITLE
Question about channels

### ISSUE THREAD

**Issue by yexiao2016z** [google/deepvariant#23]
Hi

I have some ideals about the channels in your model, but i don't know which files to modify, could you give me some advice?

**Comment by depristo** [comment]
Hi @yexiao2016z, that's very exciting to hear. The best place to start is https://github.com/google/deepvariant/blob/r0.4/deepvariant/pileup_image.py#L244 which is the python function build_pileup() that we use to create the pileup tensor. Going down the function call stack will show you everything needed to build the tensors. There's a high-performance C++ piece of code that actually constructs the tensor from a pile of reads here as https://github.com/google/deepvariant/blob/r0.4/deepvariant/pileup_image_native.cc that will ultimately be called by pileup_image.py.
