### ISSUE TITLE
while installing im getting an bazel error 

### ISSUE THREAD

**Issue by mano2991** [google/deepvariant#231]
./build-prereq.sh 
========== Load config settings.
========== [Tue Oct 29 17:26:45 IST 2019] Stage 'Install the runtime packages' starting
========== Load config settings.
========== [Tue Oct 29 17:26:45 IST 2019] Stage 'Misc setup' starting
========== [Tue Oct 29 17:26:45 IST 2019] Stage 'Update package list' starting
[sudo] password for bioinformatics: 
W: GPG error: https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
W: The repository 'https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/ InRelease' is not signed.
========== [Tue Oct 29 17:28:53 IST 2019] Stage 'Install development packages' starting
========== [Tue Oct 29 17:28:54 IST 2019] Stage 'Install python packaging infrastructure' starting
Python 2.7.16 :: Anaconda, Inc.

pip 19.3.1 from /home/bioinformatics/.local/lib/python2.7/site-packages/pip (python 2.7)
========== [Tue Oct 29 17:28:57 IST 2019] Stage 'Install python packages' starting
========== [Tue Oct 29 17:29:14 IST 2019] Stage 'Install TensorFlow pip package' starting
Installing Intel's CPU-only MKL TensorFlow wheel
========== [Tue Oct 29 17:29:15 IST 2019] Stage 'Install other packages' starting
========== [Tue Oct 29 17:29:16 IST 2019] Stage 'run-prereq.sh complete' starting
========== [Tue Oct 29 17:29:16 IST 2019] Stage 'Update package list' starting
W: GPG error: https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/ InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 51716619E084DAB9
W: The repository 'https://cloud.r-project.org/bin/linux/ubuntu xenial-cran35/ InRelease' is not signed.
========== [Tue Oct 29 17:29:24 IST 2019] Stage 'Install development packages' starting
========== [Tue Oct 29 17:29:25 IST 2019] Stage 'Install bazel' starting
[bazel INFO src/main/cpp/option_processor.cc:388] Looking for the following rc files: /etc/bazel.bazelrc,/home/bioinformatics/Downloads/deepvariant-r0.8/.bazelrc,/home/bioinformatics/.bazelrc,/dev/null
[bazel INFO src/main/cpp/rc_file.cc:56] Parsing the RcFile /home/bioinformatics/Downloads/deepvariant-r0.8/.bazelrc
[bazel INFO src/main/cpp/rc_file.cc:56] Parsing the RcFile /home/bioinformatics/Downloads/deepvariant-r0.8/../tensorflow/.bazelrc
[bazel FATAL src/main/cpp/blaze.cc:1311] Unexpected error reading .blazerc file '/home/bioinformatics/Downloads/deepvariant-r0.8/../tensorflow/.bazelrc'
~/bazel ~/Downloads/deepvariant-r0.8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

**Comment by pichuan** [comment]
Hi @mano2991 , Two questions:
(1) Can you tell me what environment (e.g., OS, version) you're running this on? 
There are also a few unexpected warnings (like the "GPG error" ones) before the bazel error, which I don't see when I test in my run.
(2)
Can you try rerunning with:
`bash -x build-prereq.sh` which should give you a bit more context on what was executed around the error?

**Comment by gunjanbaid** [comment]
@mano2991 I'll close this issue for now, but feel free to reopen if you are still running into this error. Thanks!
