### ISSUE TITLE
Unable to run vcf stats report

### ISSUE THREAD

**Issue by sabrinacamp2** [google/deepvariant#235]
Hi Deep Variant team,

I receive the below error when attempting to follow the [VCF stats report documentation](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-vcf-stats-report.md); however, attempting to run vcf stats report interactively inside of the docker yielded an error message that was a bit more informative, telling me that the .py file does not exist.

Error message from following the documentation 
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/opt/deepvariant/bin/vcf_stats_report\": permission denied": unknown.

Error message from inside the docker
> python: can't open file '/opt/deepvariant/bin/vcf_stats_report.py': [Errno 2] No such file or directory.

It seems that [lines 79 to 81 of the Dockerfile](https://github.com/google/deepvariant/blob/r0.9/Dockerfile#L79-L82) create the file called, /opt/deepvariant/bin/vcf_stats_report, but the underlying python script does not seem to be copied into the Docker. It looks like other files in the /opt/deepvariant/bin directory are copied over in [lines 42 to 50](https://github.com/google/deepvariant/blob/r0.9/Dockerfile#L42-L50), maybe a similar line needs to be added for vcf_stats_report?

Thank you for the 0.9.0 release and for being so active on Github. I’m looking forward to using this tool for my research.

**Comment by MariaNattestad** [comment]
Hi! Thanks for bringing this to our attention. We are working on a fix and will get back to you soon!

**Comment by MariaNattestad** [comment]
Thank you for your patience!
We have fixed the issue and refreshed the 0.9.0 Docker images. Please try it again and let us know if it works for you.
If you did `docker pull` before and have a local copy, you will just need to run `sudo docker pull google/deepvariant:0.9.0` to refresh your local copy, otherwise `sudo docker run` should use the latest version automatically.

Thanks for alerting us to this issue!

**Comment by MariaNattestad** [comment]
I'm going to close this issue, but please let us know whether the updated Docker image works for you. Thanks!

**Comment by sabrinacamp2** [comment]
Hi Maria,

The updated Docker image made the module work perfectly. I appreciate the quick fix and response. Thanks!

**Comment by MariaNattestad** [comment]
Excellent! Thanks for trying out the new VCF stats report!
