### ISSUE TITLE
How to get the Capture target BED file "agilent_sureselect_human_all_exon_v5_b37_targets.bed"

### ISSUE THREAD

**Issue by xiaoledeng** [google/deepvariant#237]
I have searched at the [Evaluation regions for HG002 · Issue #15 · google/deepvariant](https://github.com/google/deepvariant/issues/15), but the website is not available. Here is the non-intersected BED file:

https://dl.dnanex.us/F/D/y61fXf4qz5G8F4QvXz14bkYQ5Q9Yy5q5JPf1K3kg/agilent_sureselect_human_all_exon_v5_b37_targets.bed

Would you please offer the reachable site of the file "agilent_sureselect_human_all_exon_v5_b37_targets.bed"?

Thanks a lot.

**Comment by AndrewCarroll** [comment]
Hi Xiaoledeng,

Thanks for bringing this to our attention. I am attaching the capture regions BED file to this issue. I will also edit the earlier comments to correct for the expired link

[agilent_sureselect_human_all_exon_v5_b37_targets.bed.gz](https://github.com/google/deepvariant/files/3875975/agilent_sureselect_human_all_exon_v5_b37_targets.bed.gz)

Thank you

**Comment by xiaoledeng** [comment]
Thank you very much.
