### ISSUE TITLE
make_examples ERROR

### ISSUE THREAD

**Issue by huboyue** [google/deepvariant#24]
Hello ！
  
![image](https://user-images.githubusercontent.com/34881972/34375365-21791992-eb21-11e7-913e-5796551352d2.png)
The picture shows the error,how can I solve this problem?
Thank you !

**Comment by depristo** [comment]
Did you build yourself from scratch? We've never seen this error before. Can you confirm that you can run the prebuilt binary on this machine? It's possible that TensorFlow and ABSL have updated their code on github in a way that's breaking our build.

**Comment by depristo** [comment]
Closing as there's been no update to this thread in 9 days. Please reopen if necessary.
