### ISSUE TITLE
GPU Selection

### ISSUE THREAD

**Issue by aardes** [google/deepvariant#240]
Dear,

Apology for a not really related software issue,

Do you have any suggestions for the minimum specs needed for a GPU?
For example, I would like to know PNY Quadro P5000, is able to handle the tasks.

Thanks in advance
Amin

**Comment by sidharthgoel** [comment]
Hi @aardes, we have reported [this runtime](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-case-study.md#runtime) for running DeepVariant WGS on a GPU. The specs for that GPU are listed at the bottom of the [page](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-details.md#command-for-a-gpu-machine-on-google-cloud-platform).

I'm not sure how your specific GPU type would perform, but those numbers should give you a point of comparison.
