### ISSUE TITLE
Somatic calls (and performance in general)

### ISSUE THREAD

**Issue by mikael-christensen** [google/deepvariant#241]
Hi,

Are there any plans to extend DeepVariant to somatic variant calling? The current model seems to be inherently diploid.

What is the training time for the released versions of DeepVariant? The Supplementary information from the Nature paper mentions something about "80 hours" but does not specify which kind of hardware was used?

Do you have any numbers on how much the neural network improves the accuracy as compared to the raw (over-sensitive) variant calls output after the haplotype-aware realignment step?

**Comment by AndrewCarroll** [comment]
Hi @mikael-christensen 

For somatic calling, we have a version of DeepVariant designed to call somatic variants. This performs well in simulated benchmarks and in benchmarks with COLO829. However, we want to get more feedback from external groups about its performance across real data for more cancer types before we feel comfortable generally releasing it.

The time to train DeepVariant internally is a function of the amount and prioritization of training jobs on internal infrastructure. Generally it takes a few days to train the WGS model and is shorter for the WES and PacBio models. Training uses TPUs. I am not sure of the exact resource requirements in the production runs. However, external groups who have successfully trained DeepVariant have generally done so with much less data than what we train for in production, and often warmstart from one of our production models and re-train for their data. External groups have shown improvements for their workflows using GPUs and (I believe) on the order of a day or less of re-training time.

The candidates created by the very sensitive caller are not genotyped, so comparing accuracy of the sensitive caller in the same way isn't quite possible. DeepVariant's VCF output will write every position which is generated a candidate for.

For a 50x PCR-Free Illumina HG002 run, DeepVariant produced:

0/0 calls - 934,097 
./. calls - 150,238
0/1 calls - 2,793,521
1/1 calls - 1,851,566
1/2 calls - 78,194

This means that for about 19% of the positions which the sensitive caller proposes, DeepVariant does not believe there is sufficient evidence for a variant.

**Comment by mikael-christensen** [comment]
Thank you for the speedy reply! This is very helpful - Best, Mikael.

**Comment by kokyriakidis** [comment]
You! You should also evaluate in on blood liquid biopsy samples! Having a tool that can call accurate variants in these samples would be extremely useful in the clinical practice.

**Comment by sjin09** [comment]
I am also waiting for somatic variant calling using deepvariant on both Hiseq and PacBio reads!

**Comment by williambrandler** [comment]
@AndrewCarroll , what data was used for training the somatic caller? And how do you generate the simulated benchmarks? Could you point me to more information on this?
