### ISSUE TITLE
Non-unique names of temp files

### ISSUE THREAD

**Issue by ptrebert** [google/deepvariant#242]
Running several DeepVariant jobs (v0.9.0) on the same server, e.g., by splitting a dataset via the `--regions` option, results in corrupted files (DataLossError) because of non-unique file names for the temp files generated under `/tmp` on the server (confirmed, see below)

> I just checked the code, and you're right that the temp file names will be the same:
> https://github.com/google/deepvariant/blob/r0.9/scripts/run_deepvariant.py#L264-L266
> For now, please pass in different `intermediate_results_dir` for each run.
> For example:
> `--intermediate_results_dir="/tmp/deepvariant_tmp_output/chr1"` for chr1, and so on.

> I'll think about how we want to improve this in the future. I can think of a few options for future improvements, such as :

> 1. Use a random name for the internal /tmp files. Given that these are not exposed to the users anyway.
> 2. Use a unique name derived from the output VCF file, instead of calling all temp files the same name.

> For now, using the `--intermediate_results_dir` should hopefully resolve your issue. Let me know if it works. If you have a suggestion on what's the best future improvement for better user experience, please let me know.

_Originally posted by @pichuan in https://github.com/google/deepvariant/issues/175#issuecomment-560625427_

@pichuan
I think as an immediate step, updating the docs and making this explicit (also the option of using the `intermediate_results_dir`) would be reasonable.

Concerning a proper solution, creating a randomly named temp dir for all temp files of the job (which then could have non-random names) seems like a very straightforward way; ideally, this should also take care of the clean-up, e.g.,as it is provided by Python's `tempfile` module. I assume basic functionality like this exists in all relevant programming languages.

+Peter

**Comment by pichuan** [comment]
Thanks @ptrebert .
I added this as a future improvement that we'll work on and include in the next release. I'll leave this open.

**Comment by pichuan** [comment]
Hi @ptrebert 
Thanks for the suggestion. I have fixed this in our internal version, and the fix will come out in the next release.
