### ISSUE TITLE
Question on resolving overlapping variants

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#247]
Hi, My question is regarding the following comment: https://github.com/google/deepvariant/blob/43e54207bbf37dc511d3ea092cc84cd0476e5efe/deepvariant/haplotypes.py#L335

Does "biallelic deletion ... and inside it a biallelic SNP" refer to something like this?
```
REF:   ACATTACGATC
READ1  AC----CGA
READ2  ACAGTACG
```
where we have the combined variant; ref = CATTA -> C/CAGTA

In this case, following the comment, it seems the recommended variant representation is (assuming reference starts at position 1 (1-based index for VCF))
```
POS     REF           ALT       GT field
2       CATTA          C         0/1
4       T              G         0/1
```

However, I am wondering whether this is a valid VCF representation, since at position 4, we do not have the ref allele, but 0/1 indicates that ref allele is present at position 4.

Apologize if this is down to my misunderstanding of the VCF format.

**Comment by AndrewCarroll** [comment]
This question is complex enough that it cuts to some of the fundamental issues of VCF. I expect that across the community, opinions will differ as to whether this represents troubling inconsistency as opposed to a strange edge case.

The heart of this question is whether people will tend to interpret a 0/1 as "I have evidence for a reference allele and evidence for the 1st alternate allele" or as "I have evidence for one copy of the ALT allele but for one non-REF position".

This could be fully expressed with REF: CATTA || ALT: C, CAGTA || GT: 1/2

I expect that the majority of programs don't do this sort of normalization, and I expect the majority of downstream tools operate in a way that doesn't assume that the two lines you post introduce inconsistency (that is most probably assume "REF" more like "Evidence for at least one copy that is non-ALT, other lines may clarify if an additional non-REF allele is present).

However,  if you want to dig into this question further, I would encourage you to ask on one of the GA4GH forums about variant representations. I don't consider myself knowledgable enough to give definitive statements on edge cases like this.

**Comment by anands-repo** [comment]
I guess the core question for the variant caller is, (whether or not fully normalized as you have written) whether the raw calls can be interpreted without contradictions by a downstream method (notwithstanding the VCF standard). Considering GT=0 to be "non-ALT" instead of "REF allele" for such call clusters does seem to work in these cases (though I am not aware of a standardization of such an interpretation). The code I have referenced from DeepVariant above seems to try to filter out cases that do not make sense for such clusters of calls, so a downstream method that assumes GT=0 to imply "non-ALT" might work smoothly almost all the time (except perhaps when the algorithm aborts).

I also didn't have an idea as to whether, as a method developer, you considered these to be corner cases, and your comment above has provided an answer to that. I myself do not have any measurements on how prevalent these types of cases are, but I encountered some of these cases recently.

I will make another post here if I learn anything further about this, but I understand the point-of-view behind the original piece of code that I posted.

Thanks!

**Comment by cmclean** [comment]
Hi @anands-repo,

Thanks for the question. You are correct that in these cases we are semantically treating GT=0 to be "non-ALT"; the goal of the haplotypes.py library is to try to resolve cases where the raw calls indicate more than two alternate alleles at a single base pair. This can occur because DeepVariant processes each candidate variant independently, and sometimes candidates overlap the same stretch of the reference genome. As you observed in the code, the haplotypes.py library is even still just a "best effort" and there are cases where > 2 alternate alleles will still be emitted by the algorithm.

Regarding your prevalence comment, empirically on the Genome in a Bottle HG002 sample we observed this library reduce the number of regions with > 2 alternate alleles from ~3000 to ~300 when it was first introduced. (The numbers may be slightly different now due to subsequent improvements in variant discovery and calling).

regards,
Cory

**Comment by anands-repo** [comment]
@cmclean Thanks for the additional explanation. So the cases to be filtered out are those with more than 2 alleles predicted per reference position. Also, 300 out of millions of variants does seem to indicate that these cases are really rare after the use of this functionality.

@AndrewCarroll @cmclean Thank you for your patience and the helpful explanations.
