### ISSUE TITLE
docker image fails with quick start data

### ISSUE THREAD

**Issue by aedavids** [google/deepvariant#248]
Any idea why I can not run the docker?

The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine

In the quick start guide https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-quick-start.md . They show using sudo to run the docker. I do not have sudo permission on this machine. The machine is set up to use the group permission. I do not think this is the issue. 

Any suggestions would be greatly appreciated

Andy

```
(base) -bash-4.2$ groups
giuser kimlab docker
(base) -bash-4.2$ 
```

```
docker run -v /public/home/dkim142/quickstart-testdata:/input \
-v /public/home/dkim142/quickstart-output:/output google/deepvariant:0.9.0 \
/opt/deepvariant/bin/run_deepvariant --model_type=WGS \
--ref=/public/home/dkim142/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta \
--reads=/public/home/dkim142/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam \
--regions chr20:10,000,000-10,010,000 \
--output_vcf=/public/home/dkim142/quickstart-output/output.vcf.gz \
--output_gvcf=/public/home/dkim142/quickstart-output/output.g.vcf.gz \
--num_shards=1

***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling \
--ref "/public/home/dkim142/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/public/home/dkim142/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

2019-12-08 02:35:44.105906: F tensorflow/core/platform/cpu_feature_guard.cc:37] 
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.

real	0m1.146s
user	0m1.709s
sys	0m4.191s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/public/home/dkim142/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/public/home/dkim142/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}' returned non-zero exit status 1
(base) -bash-4.2$ 
```

**Comment by rssfed23** [comment]
if you run:
cat /proc/cpuinfo | grep avx
do you see anything?

As if not, then your machine doesn't have avx instructions so that image won't work and as per the home page you'll have to compile or use a non-avx version yourself.

If you DO have the right instructions you'll see something like this:```
(bioinfo) [root@virtbio deepvariant_tmp_output]# cat /proc/cpuinfo | grep avx
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx hypervisor lahf_lm cpuid_fault ibrs ibpb stibp tsc_adjust xsaveopt arat umip md_clear arch_capabilities```

**Comment by aedavids** [comment]
Thanks rssfed23

my server does not have the avx instruction.

I might be nice to add this to to the quick start documentation

Andy

**Comment by akolesnikov** [comment]
Thank you for the comment! We will look into it and see how we can improve quick start documentation.

**Comment by gunjanbaid** [comment]
We have updated the documentation to mention that AVX instructions are needed. These changes will come out with the next release. Thank you for the feedback!

**Comment by pgrosu** [comment]
@gunjanbaid It's been part of the instructions here:

https://github.com/google/deepvariant/blob/159eee27084f495b7aa145c2cfa5d913e25cf5b7/README.md
