### ISSUE TITLE
Unable to run make_examples.zip when using a virtual environment

### ISSUE THREAD

**Issue by stevendavis** [google/deepvariant#25]
I would rather not install the DeepVariant dependencies into my global python environment.  When the python dependencies are installed into a virtual environment, make_examples.zip cannot find tensorflow.  The steps below show the error.  Any suggestions?

```
$ mkvirtualenv -p /usr/bin/python2.7  DeepVariant.2.7
(DeepVariant.2.7) $ cd bin; bash run-prereq.sh; cd -

(DeepVariant.2.7) $ python bin/make_examples.zip   --mode calling     --ref "${REF}"     --reads "${BAM}"   --regions "chr20:10,000,000-10,010,000"   --examples "${OUTPUT_DIR}/examples.tfrecord.gz"
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_r1oZvM/runfiles/genomics/deepvariant/make_examples.py", line 38, in <module>
    import tensorflow as tf
ImportError: No module named tensorflow
```

**Comment by depristo** [comment]
We haven't tried yet to make DeepVariant accessible via pip or in a virtualenv, so unfortunately we don't have any advice for you on this topic. I'm not even sure its possible to get it to work, but if you do decide to work it through please let us know how you do it and we can consider adding official support for working inside of a virtualenv. 

Our current recommendations, if you don't want to install DeepVariant dependencies on your machine, is to either (1) run on a cloud instance or (2) run it in a docker container. We build an official docker container for DeepVariant and you can build your own here: https://github.com/google/deepvariant/tree/master/deepvariant/docker

@arostamianfar I don't see any docs on how to access the prebuilt DeepVariant docker image. Could we add a link to it here and add it to the general docs as well?

**Comment by stevendavis** [comment]
@depristo Thanks for the prompt reply.  I will let you know if I find a way to get DV working with virtualenvs.  I will also try running from a Docker container.

**Comment by arostamianfar** [comment]
@depristo RE docker docs: I can update the README in https://github.com/google/deepvariant/tree/master/deepvariant/docker to include a link to https://github.com/google/deepvariant/tree/master/docs/deepvariant-docker.md (note that this README is include inside the prebuild image as well). I think that page has all the instructions needed to use our prebuilt image.
