### ISSUE TITLE
Redirect output to another program

### ISSUE THREAD

**Issue by PlatonB** [google/deepvariant#253]
Is there a way to redirect the DeepVariant output to another program? For example, to any annotation tool.

I tried this command:
```
sudo -S docker run -v "/home/platon/_0_Диссертация/Exp/seq1/bowtie2/":"/ref" -v "/home/platon/_0_Диссертация/Exp/Рез/новая_папка/SRR062634.filt/":"/trg" \
> google/deepvariant /opt/deepvariant/bin/run_deepvariant \
> --num_shards=4 --model_type=WGS \
> --ref=/ref/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz \
> --reads=/trg/SRR062634.filt_srtd.bam |
> sudo docker run -a stdin -v $HOME/vep_data:/opt/vep/.vep -v "$HOME/_0_Диссертация/Exp/Рез/новая_папка/SRR062634.filt/":"/SRR062634_filt" \
> ensemblorg/ensembl-vep ./vep \
> --tab --quiet --no_stats --offline --cache --dir_cache /opt/vep/.vep/ \
> -o /SRR062634_filt/SRR062634.filt_ann.tsv
```

Then an error message appears:
`FATAL Flags parsing error: flag --output_vcf=None: Flag --output_vcf must have a value other than None.`

**Comment by gunjanbaid** [comment]
@PlatonB if I understand correctly, you want to pipe the contents of the final VCF to another program? If so, DeepVariant does not write the VCF to stdout, so you cannot directly pipe the VCF contents to another program. However, you can operate on the final VCF, which gets written to the path specifed by `--output_vcf`.

**Comment by PlatonB** [comment]
> if I understand correctly, you want to pipe the contents of the final VCF to another program?

Yes.

> DeepVariant does not write the VCF to stdout

Then let it be like a feature request.

**Comment by gunjanbaid** [comment]
@PlatonB thanks for the suggestion! DeepVariant can produce both a VCF and GVCF (along with other output files), so we want to give users the choice of which file to use downstream. stdout is reserved for just logging outputs so users can monitor the status of the run.
