### ISSUE TITLE
Does deepvariant support python3?

### ISSUE THREAD

**Issue by golubnikova** [google/deepvariant#258]
Hi!
According to [README.md](https://github.com/google/deepvariant/blob/r0.9/README.md) deepvariant is still using python 2.7, is it true?
I'm questioning because support of python2 officially stopped January 1 2020.

**Comment by AndrewCarroll** [comment]
Hello @golubnikova 

The current release of DeepVariant does use Python2.7. We anticipate that our next release will migrate to python3, alongside some other updates in the TensorFlow libraries used. Using DeepVariant from the Docker image distributed should work regardless of your current python dependencies.

Thank you,
Andrew

**Comment by llllaaaa** [comment]
Hi @AndrewCarroll 

Is there an estimated date for next release?

**Comment by akolesnikov** [comment]
Estimated timeline for the next release is Q2 2020.

**Comment by pichuan** [comment]
Hi @llllaaaa , to give you an update:
We're now aiming for an earlier release in March.
