### ISSUE TITLE
Documentation: Incorrect hyperlinks in deepvariant-docker.md

### ISSUE THREAD

**Issue by stevendavis** [google/deepvariant#26]
See this page:
https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-docker.md

Refer to the Setup section.  The following links do not function as intended. The #fragments do not exist anymore.

https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md#set_up_a_google_cloud_account

https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md#request_access_to_our_shared_cloud_storage_bucket

https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md#install_the_google_cloud_sdk

**Comment by arostamianfar** [comment]
Thank you for the report! Setting up Google Cloud is actually not required to use the docker images (if running locally or on a dedicated VM). So just completing the quick start should be enough. I'll remove the extra links from the page.

**Comment by depristo** [comment]
I believe this is fixed, yes?

**Comment by arostamianfar** [comment]
Correct.
