### ISSUE TITLE
Any recommendation on normalization?

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#261]
Hello,

For comparing call on different samples made with Deepvariant, is vcf normalization required? There seems to be many opinions on that question ... and the answer seems to vary also if you want to use the vcf OR the gvcf. 

So, in your experience, what would be recommended with DeepVariant? 
Bcftools norm with the fasta reference to provide a left-aligned and parsimonious representation? 

would this also be needed for the gvcf? 

Thank you :)

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

This is a good question. VCF normalization is a very complicated area. DeepVariant does attempt to normalize VCF entries, for example by left-aligning indels. This is normalizing within a single sample. Normalizing multiple samples can become quite difficult, as this becomes a combinatorial explosion of alleles to consider and the single sample doesn't see the information of other samples at the time of initial harmonization.

For comparing between samples, if possible, I would recommend using our [Best practices for multi-sample variant calling with DeepVariant](https://github.com/google/deepvariant/blob/r0.9/docs/trio-merge-case-study.md), which will take multiple gVCFs, and can harmonize the representation of all entries together.
