### ISSUE TITLE
Error running quickstart test command

### ISSUE THREAD

**Issue by cnavery** [google/deepvariant#262]
I don't have much experience using containers so it's difficult for me to troubleshoot the error I'm getting back when I run the test DeepVariant command:

`/usr/bin/docker-current: Error response from daemon: invalid volume spec ":/input": invalid volume specification: ':/input'.
See '/usr/bin/docker-current run --help'`

As it might be relevant, the OS i'm using is CentOS Linux 7.

Thank you!

**Comment by akolesnikov** [comment]
Hi cnavery,

Could you please include your full command?

Thank you.

**Comment by cnavery** [comment]
```
sudo docker run \
-v "${INPUT_DIR}":"/input" \
-v "${OUTPUT_DIR}:/output" \
google/deepvariant:"0.9.0" \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=/input/ucsc.hg19.chr20.unittest.fasta \
--reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
--regions "chr20:10,000,000-10,010,000" \
--output_vcf=/output/output.vcf.gz \
--output_gvcf=/output/output.g.vcf.gz \
--num_shards=1 \
```

It is more or less a copy-paste of the command in the documentation.

**Comment by akolesnikov** [comment]
What is the value of your ${INPUT_DIR} and ${OUTPUT_DIR} ? What is the output of 
echo $INPUT_DIR

**Comment by akolesnikov** [comment]
Also, you may try to replace 
`"${INPUT_DIR}":"/input"`
with
`"${INPUT_DIR}:/input"`

**Comment by cnavery** [comment]
```
INPUT_DIR="${PWD}/quickstart-testdata"
OUTPUT_DIR="${PWD}/quickstart-output"
```

`echo $INPUT_DIR`
returns /ybod2/cavery/deepvariant_run/quickstart-testdata

I am executing commands from the "deepvariant_run" directory.

I made the change you suggested and received a new error:
`/usr/bin/docker-current: Error response from daemon: invalid volume spec ":/output": invalid volume specification: ':/output'.`

**Comment by akolesnikov** [comment]
Make sure that you have exacly:
`"${OUTPUT_DIR}:/output"'

**Comment by cnavery** [comment]
`-v "${OUTPUT_DIR}:/output" \`

is a direct copy and paste from my command prompt. I can't spot any differences...

**Comment by akolesnikov** [comment]
It looks like you version of docker doesn't parse -v argument the same way as it is parsed on Ubuntu. The volume specification should be "/output", instead it is ":/output" in your case. Check `/usr/bin/docker-current run --help'` to see how to properly specify volume for your version of docker.

**Comment by cnavery** [comment]
I linearized the command and it ran. I'm not sure why it couldn't run with the new lines. I'll look into volume specification if I run into an issue with my data. 
Thank you!
