### ISSUE TITLE
DeepVariant with Singularity image: ImportErrors

### ISSUE THREAD

**Issue by ksw9** [google/deepvariant#265]
Hi @pichuan,
Thank you for posting these Singularity images. I tested them on a computing cluster on the test data, following the instructions above and ran into errors similar to those posted in another issue, below. I'm wondering if you have any suggestions for workarounds? Thank you in advance for your help! (I realized posting in a new issue made more sense than adding to a closed issue). 
Best,
```

***** Running the command:*****
time seq 0 0 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/labs/jandr/walter/tb/test/deepV/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/labs/jandr/walter/tb/test/deepV/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@1.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {}

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

ImportError: No module named _multiarray_umath
ImportError: No module named _multiarray_umath
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2020-01-28 19:06:29.164168: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

real	0m4.153s
user	0m0.699s
sys	0m1.614s

```

_Originally posted by @ksw9 in https://github.com/google/deepvariant/issues/243#issuecomment-579406829_

**Comment by pichuan** [comment]
Hi @ksw9 ,
the issue you reported seems to be the same as:
https://github.com/google/deepvariant/issues/132#issuecomment-482956117
At the time, I opened a follow-up issue here: https://github.com/google/deepvariant/issues/178

I just read through the issue at the time. I don't think we really pinpointed the issue, and it seems like at the time I rebuilt an image.

Can you provide the following information:
1) Your OS version.
2) Your Singularity version.
3) Your numpy version (I'm not sure whether this affects singularity)
4) Just to confirm, which *simg file are you using? The command you run? Was this with or without GPU?

Thanks. I'm currently on vacation. I'll get to this after next week.

**Comment by ksw9** [comment]
Hi @pichuan,
Thanks for getting back to me! Any suggestions would be great. 

1. Your OS version.
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"

2. Your Singularity version.
singularity version 3.4.1-1.2.el7
3. Your numpy version (I'm not sure whether this affects singularity)
1.17.5
4. Just to confirm, which *simg file are you using? The command you run? Was this with or without GPU?

I tried using the deepvariant-0.9.0.simg image from here with and without GPU: `https://storage.googleapis.com/deepvariant/singularity_images`
# Pull Singularity images
INPUT_DIR='singularity'
DATA_HTTP_DIR="https://storage.googleapis.com/deepvariant/singularity_images"
# Non-gpu image
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/deepvariant-0.9.0.simg
# GPU image
wget -P ${INPUT_DIR} "${DATA_HTTP_DIR}"/deepvariant-0.9.0-gpu.simg

# Test Singularity DeepVariant0.9.0 image on test data
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
${INPUT_DIR}/deepvariant-${BIN_VERSION}.simg \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=ucsc.hg19.chr20.unittest.fasta \
--reads=NA12878_S1.chr20.10_10p1mb.bam \
--regions "chr20:10,000,000-10,010,000" \
--output_vcf=output.vcf.gz \
--output_gvcf=output.g.vcf.gz  

# Errors:

ImportError: No module named _multiarray_umath
ImportError: No module named _multiarray_umath
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2020-01-31 01:37:29.333483: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 

# Test Singularity DeepVariant0.9.0 GPU image on test data
singularity -s exec -B /usr/lib/locale/:/usr/lib/locale/  \
${INPUT_DIR}/deepvariant-${BIN_VERSION}-gpu.simg \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=ucsc.hg19.chr20.unittest.fasta \
--reads=NA12878_S1.chr20.10_10p1mb.bam \
--regions "chr20:10,000,000-10,010,000" \
--output_vcf=output.vcf.gz \
--output_gvcf=output.g.vcf.gz  

# Errors: 
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_0Ul6DZ/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 43, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory



I additionally tried using docker to run the docker images (which worked for me with DeepVariant v.7.0.0, but not 9.0.0): 
`# Pull the deep variant docker image.
sregistry pull docker://gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}"
​

# Test running docker interactively w/Singularity. 
BIN_VERSION="0.9.0"
singularity shell --bind '/labs/jandr/walter/tb/test' /home/kwalter/.singularity/shub/deepvariant-docker-deepvariant:${BIN_VERSION}.simg;

/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=ucsc.hg19.chr20.unittest.fasta \
--reads=NA12878_S1.chr20.10_10p1mb.bam \
--regions "chr20:10,000,000-10,010,000" \
--output_vcf=output.vcf.gz \
--output_gvcf=output.g.vcf.gz  
`
I got the same errors with this test. It seems like there is some issue with numpy/tensorflow in this most recent version of the image that makes it incompatible with running via Singularity. Any suggestions or advice would be great. Thank you in advance!

**Comment by pichuan** [comment]
Hi @ksw9 ,
It seems like you're using Numpy 1.17.5, which requires Python 3.5-3.8:
https://numpy.org/devdocs/release/1.17.5-notes.html
Currently, DeepVariant is still supporting only Python2. We plan to make a release with Python3 support in Q2.

If you're running with docker, I don't expect that use case to be affected though. If you're seeing issues with running strictly with docker, let me know. I'm going to close this issue for now, given that the issue (Python2 vs 3) is a known issue that we'll address in the next release.

**Comment by pichuan** [comment]
FYI:
I plan to remove the gs://deepvariant/singularity_images directory , and suggest our users to directly pull from our Docker image instead. Example:
```
BIN_VERSION="1.0.0"
singularity pull docker://google/deepvariant:"${BIN_VERSION}"
```
