### ISSUE TITLE
Thread usage

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#274]
Hello, follow-up ... I was not able to make it work, also we noticed, even when it's not taking all the threads, when it's running with the numbers of threads given by the shards argument, other processes (so, not DeepVariant) are on S as shown in htop. Is it that DeepVariant co-opt all the threads even when it doesn't currently need them? 

Got it. Thanks for the context! If you end up tweaking the config, let me know whether it works for you or not.
I'll close this issue now.

_Originally posted by @pichuan in https://github.com/google/deepvariant/issues/271#issuecomment-586523576_

**Comment by pichuan** [comment]
Hi @aderzelle 
It might take me a while to prioritize this. But I will get back to this later. 

As mentioned before, our call_variants behavior is based on how TensorFlow works. If you need this to be resolved soon, it might help to look into how to adjust TensorFlow's behavior first.
Thanks for reporting the issue.

**Comment by chrisfleisch** [comment]
We've started testing DeepVariant on a machine with 128 cores from AMD. Setting --num_shards=$(nproc) results in this error:

> OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8254915 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable

It seems to create way more threads than the machine can handle.

Setting num_shards=40 will work on the AMD machine, but the number of shards it creates is variable and much more than 40. I've seen 81, 116, and 101 intermediate shards created. From what I remember, in all our previous usage on machines with 40 cores or less the number of shards always matched the number of cores when using num_shards=$(nproc).

The AMD machine with num_shards=40 also runs much slower compared to our Skylake machines with 40 cores and num_shards=$(nproc). The AMD machine takes over 7 hours per WGS file compared to less then 5 hours with the Skylake machine. It looks like when we try to run on the AMD machine it creates 2x as many tasks than available processors which might explain the slowdown.

**Comment by pichuan** [comment]
Thanks @chrisfleisch for following up on this issue.
If I understand correctly, you're also talking specifically about the `call_variants` step, not the `make_examples` step, right?

I can try to see if I can get a AMD machine to test it out. I actually have not made any progress on this issue yet.

**Comment by chrisfleisch** [comment]
I ran `/opt/deepvariant/bin/run_deepvariant` and I believe it ran out of threads during the `make_examples` step when I tried to use all the cores on the AMD machine.

Here's more of the error

> OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8254915 max
> OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
> OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 8254915 max
> Traceback (most recent call last):
>   File "/tmp/Bazel.runfiles_XqQaQr/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 42, in <module>
>     import numpy as np
>   File "/usr/local/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
>     from . import core
>   File "/usr/local/lib/python2.7/dist-packages/numpy/core/__init__.py", line 47, in <module>
>     raise ImportError(msg)
> ImportError:
> 
> IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
> 
> Importing the multiarray numpy extension module failed.  Most
> likely you are trying to import a failed build of numpy.
> Here is how to proceed:
> - If you're working with a numpy git repository, try `git clean -xdf`
>   (removes all files not under version control) and rebuild numpy.
> - If you are simply trying to use the numpy version that you have installed:
>   your installation is broken - please reinstall numpy.
> - If you have already reinstalled and that did not fix the problem, then:
>   1. Check that you are using the Python you expect (you're using /usr/bin/python),
>      and that you have no directories in your PATH or PYTHONPATH that can
>      interfere with the Python and numpy versions you're trying to use.
>   2. If (1) looks fine, you can open a new issue at
>      https://github.com/numpy/numpy/issues.  Please include details on:
>      - how you installed Python
>      - how you installed numpy
>      - your operating system
>      - whether or not you have multiple versions of Python installed
>      - if you built from source, your compiler versions and ideally a build log
> 
>      Note: this error has many possible causes, so please don't comment on
>      an existing issue about this - open a new one instead.
> 
> Original error was: PyCapsule_Import could not import module "datetime"
> 
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
>     "__main__", fname, loader, pkg_name)
>   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 223, in <module>
>   File "/opt/deepvariant/bin/make_examples.zip/__main__.py", line 204, in Main
>   File "/usr/lib/python2.7/subprocess.py", line 523, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1235, in _execute_child
>     self.pid = os.fork()
> OSError: [Errno 11] Resource temporarily unavailable: '/usr/bin/python'
> 
> real    19m19.271s
> user    1084m5.580s
> sys     17m12.750s
> Traceback (most recent call last):
>   File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
>     app.run(main)
>   File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
>     subprocess.check_call(command, shell=True, executable='/bin/bash')
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'time seq 0 127 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode callin
> g --ref "/my_path.fa" --reads "/my_path.cram" --examples "/tmp_data/my_path/make_examples.tfrecord@128.gz" --gvcf "/my_path/gvcf.tfrecord@128.gz" --task {}' return
> ed non-zero exit status 67

**Comment by pichuan** [comment]
Hi @chrisfleisch , sorry it took me a while to find some time to try this.

I just got an AMD machine on Google Cloud to test. But, I'm unable to reproduce your issue in the `make_examples` step.
I'll post what I did below (which didn't reproduce your error).
But, maybe this Stackoverflow issue could be related?
https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable
Specifically, can you try the suggestion in https://stackoverflow.com/a/54746150 and let me know if that worked for you?

---

For completeness, here is what I tried:

I got a AMD machine:

```
gcloud compute instances create "${USER}-amd" \
--scopes "compute-rw,storage-full,cloud-platform" \
--image-family "ubuntu-1604-lts"   --image-project "ubuntu-os-cloud" \
--machine-type "n2d-standard-16"   --boot-disk-size "100"  \
--zone "europe-west4-b"
```

On that machine, I ran:
```
$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7B12
Stepping:              0
CPU MHz:               2249.998
BogoMIPS:              4499.99
Hypervisor vendor:     KVM
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2 smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save umip rdpid
```

Then, I just directly run the WES case study with docker:
```
$ curl https://raw.githubusercontent.com/google/deepvariant/r0.9/scripts/run_wes_case_study_docker.sh | bash -x 
```

Once make_examples started running, I used “top” to look at the jobs:
![image](https://user-images.githubusercontent.com/471813/76821677-da7f0180-67cb-11ea-9caa-5cdd01378c00.png)

Because I have 16 cores, as expected, 16 python jobs were running. All seem to take close to 100% CPU.

**Comment by chrisfleisch** [comment]
Thank you for trying. I'm not able to reproduce on any cloud instance so it must be a local issue.

I did run into a different performance issue with AMD during the call_variants.py step in my testing.

I setup an Intel 48 core instance and an AMD 48 core instance. Both in AWS.

> intel:~$ lscpu
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              48
> On-line CPU(s) list: 0-47
> Thread(s) per core:  2
> Core(s) per socket:  24
> Socket(s):           1
> NUMA node(s):        1
> Vendor ID:           GenuineIntel
> CPU family:          6
> Model:               85
> Model name:          Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz
> Stepping:            4
> CPU MHz:             1520.299
> BogoMIPS:            4999.99
> Hypervisor vendor:   KVM
> Virtualization type: full
> L1d cache:           32K
> L1i cache:           32K
> L2 cache:            1024K
> L3 cache:            33792K
> NUMA node0 CPU(s):   0-47
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke

> amd:~$ lscpu
> Architecture:        x86_64
> CPU op-mode(s):      32-bit, 64-bit
> Byte Order:          Little Endian
> CPU(s):              48
> On-line CPU(s) list: 0-47
> Thread(s) per core:  2
> Core(s) per socket:  24
> Socket(s):           1
> NUMA node(s):        3
> Vendor ID:           AuthenticAMD
> CPU family:          23
> Model:               1
> Model name:          AMD EPYC 7571
> Stepping:            2
> CPU MHz:             2524.374
> BogoMIPS:            4399.90
> Hypervisor vendor:   KVM
> Virtualization type: full
> L1d cache:           32K
> L1i cache:           64K
> L2 cache:            512K
> L3 cache:            8192K
> NUMA node0 CPU(s):   0-7,24-31
> NUMA node1 CPU(s):   8-15,32-39
> NUMA node2 CPU(s):   16-23,40-47
> Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid amd_dcm aperfmperf tsc_known_freq pni pclmulqdq ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch topoext perfctr_core vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero xsaveerptr arat npt nrip_save

When I run run_wes_case_study_docker.sh on the Intel instance make_examples.py load avg is 48, call_variants.py load avg is 36 (takes about 1.5 minutes), and the it completes in about 13-15 minutes.

Using the AMD instance make_examples.py load avg is 48, call_variants.py load avg is 86 (takes about 6 minutes), and it completes in about 20-23 minutes

It looks like when using AMD it slows down considerably during the call_variants.py step.

**Comment by pichuan** [comment]
Posting an answer for @akolesnikov : 

---

Hi @chrisfleisch ,

Your observations are very inline with our performance evaluations. We had a great improvement in performance of call_variants when we enabled Intel MKL library (see [blog](https://google.github.io/deepvariant/posts/2019-04-30-the-power-of-building-on-an-accelerating-platform-how-deepVariant-uses-intels-avx-512-optimizations/). As far as I understand AMD does not support MKL and therefore cannot take advantage of this optimization (I found this [discussion](https://www.reddit.com/r/Amd/comments/9rx0rj/is_amd_working_on_an_alternative_to_intel_mkl_or/) on that topic.

**Comment by pichuan** [comment]
Hi @aderzelle, I kept this open all this time because I think there was something I wanted to try.

But then it was open for too long and I forgot what I was trying to do. :-/ 

@aderzelle If you still have any request/questions, can you open another issue and we can restart from there? Sorry that this has lagged for too long.
