### ISSUE TITLE
Information used in PacBio models

### ISSUE THREAD

**Issue by ptrebert** [google/deepvariant#275]
Hi,
I have a question about the information used by DeepVariant (v0.9.0) with the model `PACBIO`: does this model rely on/benefit from the additional quality information contained in "PacBio-native" BAM files? In other words, are the variant calls identical for a dataset that is processed (i) using the PacBio-native BAM as input, requiring the alignment to be done with pbmm2 to keep said information intact; and (ii), using FASTQ as input (w/o the additional quality information), and the alignment is performed with minimap2 (since pbmm2 is essentially just a wrapper around minimap2, let's assume the resulting alignments are identical)? Thanks for the clarification.
Best,
Peter

**Comment by akolesnikov** [comment]
Hi Peter,
I'm not sure what do you mean by "additional quality information". May be if you could clarify that I will be able to give a better answer. DeepVariant uses base quality scores as well as mapping quality scores from an input BAM file. 
Although using different mappers may affect the output of DeepVariant, candidate variants are calculated by DeepVariant by counting alleles at each position inside of a region of interest. So, if resulting alignments are identical (as well as base quality scores and mapping scores) then DeepVariant should output the identical variant calls.

Alexey

**Comment by AndrewCarroll** [comment]
Hi @ptrebert 

I'd like to extend on Alexey's answer. DeepVariant takes only the base quality scores from the QUAL field of the BAM. At this time, it does not use additional data tags for PacBio sequencing. So if you have pbmm2 reads mapped from FASTQ, this should be identical in behavior to the BAM entry (assuming mapping is fully deterministic). 

I have not see BAM files for HiFi reads contain some of the tags I saw in previous CLR files. I just want to confirm that you are starting from the output of CCS (i.e. that these reads are HiFi). This version of DeepVariant doesn't call variants in uncorrected CLR reads.

Thanks,
Andrew

**Comment by ptrebert** [comment]
Hi @akolesnikov and @AndrewCarroll ,
thanks for your sharing your insights. We have one collaboration where (at least some) HiFi/CCS reads were shipped as PacBio-native BAMs; hence, I just wanted to make sure that I am not omitting necessary information from DeepVariant by not using pbmm2 together with the PacBio-native BAMs to generate the input alignments. Thanks for clarifying.
Best,
Peter
