### ISSUE TITLE
Can I use this caller to run on long read samples

### ISSUE THREAD

**Issue by archanaraja** [google/deepvariant#277]
Hi,

We have long read data. Does this version run successfully on long read data? If it does  , what are the long read sequencing platforms that are currently supported ? Also do you recommend a certain sequence coverage to get good results from long reads?

Thanks,
Archana

**Comment by AndrewCarroll** [comment]
Hi @archanaraja 

DeepVariant can run on PacBio HiFi (CCS) data (see this paper for details: https://www.nature.com/articles/s41587-019-0217-9 or biorxiv: https://www.biorxiv.org/content/10.1101/519025v1)

To do this, you would run with the --model_type=PACBIO option (see the [Quickstart](https://github.com/google/deepvariant/blob/r0.9/docs/deepvariant-quick-start.md)

However, the current version of DeepVariant does not work with continuous long reads (CLR).  

PacBio recommends 15x coverage of CCS data in their best practices.

**Comment by archanaraja** [comment]
Thank you! Can it run on Promethion data?

**Comment by MariaNattestad** [comment]
No. Currently PacBio HiFi/CCS data is the only long-read sequencing type supported. ONT reads, including PromethIon, have a much higher error rate (same for PacBio CLR) and would therefore need special treatment.

**Comment by archanaraja** [comment]
Thank you!
