### ISSUE TITLE
Strange false positive call 

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#280]
Hello, (me again sorry), I am eyeballing bam files for evaluation of candidates. Mostly it's fine (I open a lot of issues but I want to stress that most reported variants seem correct). But here is a very, very strange case to my eyes. 

Here is the gvcf line
```
chromosome_1	17434065	.	C	T,<*>	29.1	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:29:64:38,26,0:0.40625,0:29,0,99,990,990,990
```
That looks all right to me, seems like a "solid" candidate. But now, let's look at the bam 

![CT](https://user-images.githubusercontent.com/23341393/75540193-d4db9a80-5a1b-11ea-92a6-ba9da3def9f1.png)
the relevant position is the first C starting from the right. As you see, there is not a single T base there. The site seems perfectly homozygous for C:C. 

However, a bit on the left, you can see that many of the mapped reads abruptly end at the same position with a T. It's not a variant but something a bit strange seems to happen in that region.

So far it's the only such case I have. Do you have any idea of what's going on?

Here are the lines from the gVCF before the site. The abrupt T position is at 17434056, so in a block with no candidate. But just right after, for a few bases, DeepVariant threw a few calls that are completely not supported by the mapping.

```
zgrep -w -C8 "17434065" H4A4.g.vcf.gz
chromosome_1	17434049	.	T	G,<*>	29.2	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:29:62:36,25,0:0.403226,0:29,0,99,990,990,990
chromosome_1	17434050	.	G	<*>	0	.	END=17434056	GT:GQ:MIN_DP:PL	0/0:50:59:0,186,1859
chromosome_1	17434057	.	G	T,<*>	25.7	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:26:59:33,26,0:0.440678,0:25,0,71,990,990,990
chromosome_1	17434058	.	T	<*>	0	.	END=17434058	GT:GQ:MIN_DP:PL	0/0:50:63:0,189,1889
chromosome_1	17434059	.	G	T,<*>	25	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:25:63:37,26,0:0.412698,0:25,0,77,990,990,990
chromosome_1	17434060	.	A	<*>	0	.	END=17434062	GT:GQ:MIN_DP:PL	0/0:50:64:0,165,1889
chromosome_1	17434063	.	G	C,<*>	26.2	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:26:64:38,25,0:0.390625,0:26,0,99,990,990,990
chromosome_1	17434064	.	A	<*>	0	.	END=17434064	GT:GQ:MIN_DP:PL	0/0:50:64:0,192,1919
chromosome_1	17434065	.	C	T,<*>	29.1	PASS	.	GT:GQ:DP:AD:VAF:PL	0/1:29:64:38,26,0:0.40625,0:29,0,99,990,990,990

```

any idea of what's going on there? It's a bit annoying in the sense that I don't know how I could have caught that without eyeballing the alignment. In my experiment I plan to eyeball all my candidates anyway (because there are less than 100 of them).

**Comment by aderzelle** [comment]
Ok, I found some other cases, everytime in the vicinity of an abrupt mapping ending
![W1](https://user-images.githubusercontent.com/23341393/75542735-ab713d80-5a20-11ea-9d71-adb22bfcb841.png)
![W2](https://user-images.githubusercontent.com/23341393/75542798-cb086600-5a20-11ea-9514-4eb573f68f9a.png)

Is DeepVariant catching what are reference genome misassemblies?

**Comment by gunjanbaid** [comment]
@aderzelle DeepVariant performs local realignment by default (can be disabled with `--norealign_reads` for the `make_examples` step). Realignment may cause this region to look a bit different than what you see in the original BAM, explaining the candidates that are generated. DeepVariant can output the realigned reads in file called `realigned_reads.bam`, and flags for doing so are below. These can be added to the `make_examples` step so that you can inspect the realigned data.

`--emit_realigned_reads` - enables writing out of realigned reads
`--realigner_diagnostics=/path/to/dir` -  path to which the reads will be written

**Comment by aderzelle** [comment]
Thank you,

How exactly does it perform the realignment? How does it differ from, let's say, bwa mem?

**Comment by MariaNattestad** [comment]
DeepVariant uses Smith-Waterman for realignment, specifically this library: https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library.

**Comment by serge2016** [comment]
Hello!
But what behavior is correct for the two examples in this issue? It seems that this "local realignment" breaks the correct one and produces incorrect calls!

**Comment by MariaNattestad** [comment]
I suspect the abrupt read-ending is due to misassembly or a structural variant that is causing reads to be split. The realigner does a local alignment where it will force realignment of the whole read, including the part of the read that did not map well to this locus. While realignment is usually beneficial to DeepVariant's accuracy, in this particular case it looks like it is creating some artifacts because of the misassembly (or SV). You may want to experiment with turning realignment off by using the `--norealign_reads` flag. If you get a chance to try that, please let us know what happens.

**Comment by aderzelle** [comment]
Hello, 
isn't it a case of ... "well, here we need wetlab Sanger sequencing"? 
I certainly can share, but I need to find a time slot to relaunch DeepVariant with the production of evidence bam. I will be on it because I am curious. @MariaNattestad  where can I send you the bam?

**Comment by MariaNattestad** [comment]
Hi @aderzelle 
If the question is why a variant is getting called when you see no sign of it in the original bam, then that can only be answered by inspecting the realigned bam, not by additional sequencing. It seems likely given the split reads that you are seeing the signal of some kind of misassembly or structural variant (if the genomes producing the bam and the reference are not the same). If seeing the realigned bam does not answer your question, then you can send the files to marianattestad@google.com and I can take a look. I would need to see the original bam, the realigned bam, the reference genome, and the position of the variant you are asking about.

**Comment by aderzelle** [comment]
> @aderzelle DeepVariant performs local realignment by default (can be disabled with `--norealign_reads` for the `make_examples` step). Realignment may cause this region to look a bit different than what you see in the original BAM, explaining the candidates that are generated.
> 
> By default, the realigned reads do not get written out, but you can use the flags below to output the realigned reads to a file called `realigned_reads.bam`. These flags can be added to the `make_examples` step so that you can inspect the realigned data.
> 
> `--emit_realigned_reads` - enables writing out of realigned reads
> `--realigner_diagnostics=/path/to/dir` - path to which the reads will be written

Hello, how are we supposed to pass those arguments with the one-step wrapper script?

**Comment by aderzelle** [comment]
It's running all right but 
´´´
docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}:/output" google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/A_vaga.NDPD.fasta --reads="/input/${SAMPLE}.sorted.bam" --output_vcf=/output/${SAMPLE}.vcf.gz --output_gvcf=/output/${SAMPLE}.g.vcf.gz --num_shards="${N_SHARDS}" --customized_model="/input/mosquito_model/model.ckpt-97700" --make_examples_extra_args=emit_realigned_reads=true,realigner_diagnostics=/media/urbe/MyADrive/12-03-2020_DeepVariant_NDPD/bam_diagnostics
´´´
but it doesn't seem to write anything in the bam_diagnostics directory. Does it only print some specific cases?

**Comment by thedam** [comment]
I have the same situation: the realigner injects ALT bases not present in the input alignment.

NovaSeq X Plus, WES, hg38. DeepVariant calls homozygous-ALT with zero support in the original BAM:

```
19      40396714        .       T       C       13.9    LowQual .       GT:GQ:DP:AD:VAF:PL      1/1:13:34:1,33:0.970588:13,20,0
19      40396735        .       C       T       18      LowQual .       GT:GQ:DP:AD:VAF:PL      1/1:17:72:0,72:1:17,23,0
19      40396746        .       T       C       25      PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:22:89:0,89:1:24,24,0
19      40396752        .       G       A       22.5    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:20:97:0,97:1:22,24,0
19      40396758        .       T       C       12.1    LowQual .       GT:GQ:DP:AD:VAF:PL      1/1:12:114:0,114:1:11,21,0
19      40396774        .       C       T       23.6    PASS    .       GT:GQ:DP:AD:VAF:PL      1/1:21:174:26,148:0.850575:23,23,0
19      40396784        .       A       G       5.4     LowQual .       GT:GQ:DP:AD:VAF:PL      1/1:5:207:46,161:0.777778:3,17,0
```

Screenshot (top = realigned_reads.bam, bottom = original BAM, chr19:40,396,700–800): the mismatch columns in the top track don't exist in the bottom (reference) track; coverage also drops just left of the cluster.

<img width="2956" height="1923" alt="Image" src="https://github.com/user-attachments/assets/74fc73a6-c023-41d0-98b3-c80bac86c704" />

--norealign_reads removes the entire cluster, while a genuine SNP at 40396589 (reads truly carry ALT) is still called.

Env: Parabricks 4.7.0-1 WES model (--use-wes-model --disable-use-window-selector-model); also reproduced with google/deepvariant:1.10.0 --model_type=WES. BWA-MEM, no BQSR.

**Comment by thedam** [comment]
ok, without this option "--disable-use-window-selector-mode" FPs are not called

**Comment by pichuan** [comment]
I'm not sure if @danielecook opened this bug because he plans to do something or not. But it has been a long time since there's any new activities on this, so I'll close.

If there were any action items that I missed, feel free to reopen and remind me what they are.
