### ISSUE TITLE
--gvcf_gq_binsize to 0? 

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#282]
Hello, would setting --gvcf_gq_binsize=0 produce a gvcf with a single line per site? (similar to GATK "allsites")? 

thank you

**Comment by aderzelle** [comment]
Mmmm actually it runs into "gq resolution must be a non negative integer".

**Comment by cmclean** [comment]
Setting it to 1 will produce the desired effect.

**Comment by aderzelle** [comment]
Great, thank you!

**Comment by jaspez** [comment]
> Hi @jaspez yeah my apologies - when I read your comment more carefully, it seemed like you used `1`, so I removed my previous answer. `--gvcf_gq_binsize=1` will only merge records when they have identical GQ values, so there would be no loss of information at least in terms of GQ, but as you already saw this will not be exactly the same as what you specified (single line per position).
> 
> Unfortunately we do not currently have an option to keep every single non-variant position, as this would make the gVCF files extremely large. In general I'd recommend not doing this anyway, since this will eventually slow down any downstream processing of the gVCFs such as merging gVCFs using GLnexus, etc. I think the easiest way to achieve this would be by post-processing the gVCFs generated with `--gvcf_gq_binsize=1`. For example, the `break_blocks` option in [gvcftools](https://sites.google.com/site/gvcftools/home/configuration-and-analysis) seems to do this, based on an answer in this [forum](https://www.biostars.org/p/136461/).
> 
> May I ask what is your use case that prefers every non-variant position to be written?
> 
> Best, Ted

Thanks @tedyun for your reply. I'm interested not only in non-variant positions but also variant positions to be written individually. Some surrounding variants with the same GQ are written in the same line with  `--gvcf_gq_binsize=1`, losing other important information fields.

Best,
David.

**Comment by tedyun** [comment]
@jaspez Could you provide an example record for the issue about variant positions? In DeepVariant's gVCF outputs all SNP positions should be recorded separately, and insertion/deletion records will naturally span multiple positions.
