### ISSUE TITLE
strange mutation

### ISSUE THREAD

**Issue by aardes** [google/deepvariant#284]
Dear,

We are facing an issue with one of our samples, there is a mutation in both the vcf and gvcf files which does not exist in the bam file. (chr14:50605480 C > - ) which makes a frameshift.

If it helps I can send the igv link to Andrew.

Kind regards

<img width="1668" alt="Screenshot 2020-03-16 at 11 18 23" src="https://user-images.githubusercontent.com/12953535/76746670-299b4700-6778-11ea-9ca1-8773c885d103.png">

**Comment by pichuan** [comment]
Hi @aardes ,
This might be similar to this issue: https://github.com/google/deepvariant/issues/280
In short, DeepVariant runs an internal realignment step on short reads. I recommend you try the flags in this answer: https://github.com/google/deepvariant/issues/280#issuecomment-593558131
And see if you can find the call in the realigned BAM. It'll be great if you can post another IGV of the realigned BAM here so we can take a look.

Thank you!

**Comment by aardes** [comment]
Dear @pichuan ,

thanks a lot for your kind reply, and sorry  for the late reply,

As you said I did the realigned flag active and I can confirm that the indel exists in the realignment file. This makes me more confused, should I trust my BAM or the Variants in the VCF? 

Is there a way to flag the variant in the VCF file. This will help a lot, and we can easily find them.

Kind regards.
<img width="1659" alt="Screenshot 2020-03-19 at 14 49 27" src="https://user-images.githubusercontent.com/12953535/77074721-88b7c080-69f1-11ea-8723-22e6b2fb252f.png">

**Comment by pichuan** [comment]
Hi @aardes 
Currently, realignment step in DeepVariant is important to get accurate Indel calls for short reads.
It's not guaranteed to be always correct, but systematically, turning it on significantly improves our Indel accuracy.

If you have the reference samples (e.g., HG001, HG002) in your runs, you can try turning realignment on/off and see what accuracy you're observing. Our recommendation is that for short reads, you should keep realignment on by default.

**Comment by pichuan** [comment]
@akolesnikov also added:
"Realignment is done to the haplotypes created by building DeBruijn graph from input reads. Initial mapping by design cannot align reads correctly in some cases, which we try to mitigate with local realignment."
