### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by matthdsm** [google/deepvariant#285]
Hi,

Are there any plans to upgrade to python3? Py2 has been deprecated, which makes deepvariant kind of obsolete..

Thanks
M

**Comment by pichuan** [comment]
Hi @matthdsm , we're actively working on a new release that will be using Python3.
We haven't updated out GitHub code, but you can find the Docker images on `google/deepvariant:0.10.0` already. If you have a chance to try it out, let us know if you encounter any issues.

We'll have a release on GitHub soon.
