### ISSUE TITLE
no output.visual_report.html?

### ISSUE THREAD

**Issue by meghanasp21** [google/deepvariant#290]
Hi. 

I recently ran deep variant with a collection of WGS samples. It seems to have run through the whole pipeline producing the g.vcf.gz and vcf.gz files, however there was no visual_report.html file? 

/nrnb/opt/singularity-3.3.0/bin/singularity run --nv /nrnb/opt/singularity-containers/deepvariant_gpu_0.8.0.sif /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=$ref --reads=$bam --regions $chr --output_vcf=$x.$chr.vcf.gz --output_gvcf=$x.$chr.g.vcf.gz --num_shards=3

Do I have to include a specific output tag in order to get the file? Based on the docs, it should automatically be produced?

Thanks.

**Comment by AndrewCarroll** [comment]
Hi @meghanasp21 

Thank you for your question. The visualization capability was released with the v0.9 version of DeepVariant. In your run, you are using the v0.8 version. Are you able to update to v0.9? If so, the visualization outputs should be present.

Thanks.

**Comment by pichuan** [comment]
It should also be available in the v0.10.0 release. If not, please let us know.

**Comment by MariaNattestad** [comment]
In case you don't want to rerun DeepVariant with the newer version to get the report, you can use this script to generate the VCF stats report from an existing VCF file: https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-vcf-stats-report.md
The script is only available in version 0.9+, but this way you won't have to rerun the whole pipeline.

**Comment by leorippel** [comment]
Hi, I'm running the deepvariant_1.0.0.sif and I cannot visualize the output of the file. Has to be open from the same file folder?

**Comment by pichuan** [comment]
Hi @leorippel , can you provide more information on your run?
For example, can you try commands similar to https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md , and let us know what commands you ran, and what files you expected that are not there?
I understand that you're running with Singularity. It'll help us look into your issue if you provide more details. 
Thanks!

**Comment by leorippel** [comment]
Yes, sorry about the blunt message.

 I ran deepvariant with a subset of my data to test. All right with the outputs, but I cannot visualize the visual_report.html. I have the file, but when I open with chrome or firefox nothing is show.

I changed the permissions of the files, didn't help.

I even tried to generate  again usin the just the VCF stats report alone using as  input the vcf file generated by DV

This is how I set the commands:


BIN_VERSION="1.0.0"
BASE="${PWD}/deepvariant-run"
INPUT_DIR="${BASE}/input"
REF="10consensus.fasta"
BAM="268_041_m10.sorted.bam"
OUTPUT_DIR="${BASE}/output"
DATA_DIR="${INPUT_DIR}/data"
OUTPUT_VCF="M10.output.vcf.gz"
OUTPUT_GVCF="M10.output.g.vcf.gz"
mkdir -p "${OUTPUT_DIR}"
mkdir -p "${INPUT_DIR}"
mkdir -p "${DATA_DIR}"


sudo docker run --gpus 1 \
-v "${DATA_DIR}":"/input" \
-v "${OUTPUT_DIR}:/output" \
google/deepvariant:"${BIN_VERSION}-gpu" \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref="/input/${REF}" \
--reads="/input/${BAM}" \
--output_vcf=/output/${OUTPUT_VCF} \
--output_gvcf=/output/${OUTPUT_GVCF} \
--intermediate_results_dir /output/intermediate_results_dir \
--num_shards=32

[output.visual_report.zip](https://github.com/google/deepvariant/files/5265027/output.visual_report.zip)



Thanks.

**Comment by pichuan** [comment]
From the output.visual_report.zip file you attached, I got the HTML file, and can view it:
![image](https://user-images.githubusercontent.com/471813/94210366-5943ae00-fe83-11ea-8931-528607cc5bc8.png)

Do you mean it looks just completely empty to you? Can you try a different computer, or tell us which browser version you're using?
+ @MariaNattestad FYI.

**Comment by leorippel** [comment]
Wow.

Yes, it looks completely empty for me. 

I tried in both chrome and firefox.
google-chrome --version
Google Chrome 85.0.4183.83

firefox --version
Mozilla Firefox 80.0.1

Changed computer and tried on explorer. Completely blank.
Internet Explorer 11
version 11.1726.17134.0

**Comment by leorippel** [comment]
I got it.

Looking at the source code:

  <script type="text/javascript" src="https://storage.googleapis.com/deepvariant/lib/vega/vega@5"></script>
  <script type="text/javascript" src="https://storage.googleapis.com/deepvariant/lib/vega/vega-lite@3.4.0"></script>
  <script type="text/javascript" src="https://storage.googleapis.com/deepvariant/lib/vega/vega-embed@4"></script>

unfortunately the "https://storage.googleapis.com" is blocked here for "security reasons" :( . I open in my mobile using external network and I can see the complete output.

Thanks for the feedback.
