### ISSUE TITLE
Low coverage PacBio calling

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#294]
Hi,
Will DeepVariant still perform on very low coverage (1x, 2x, 3x) highly accurate PacBio CCS reads? Or would GATK be better for lower coverage libraries?

Thanks.

**Comment by AndrewCarroll** [comment]
Hi @gevro,

DeepVariant uses some heuristics to identify candidate sites for calling by the neural network. These heuristics require at least 2 reads to support a variant for that to be a candidate. As a result, at very low coverages (1x-3x), many of the variants won't have enough support to cross this threshold. I would recommend something like 4x-5x coverage for CCS for DeepVariant.

I am not sure how GATK will behave at such low coverages.
