### ISSUE TITLE
Best alignment tool for PacBio data

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#295]
Hi,
What is the recommended aligner for Pacbio data before running DeepVariant? bwa? pbmm2?
Thanks.

**Comment by AndrewCarroll** [comment]
Hi @gevro,

Early in building the PacBio models, we benchmarked on both NGMLR and Minimap2/pbmm2 and found that they gave similar quality of variant calls. We train with data from Minimap2/pbmm2, and I would recommend using pbmm2 for the mapper.
