### ISSUE TITLE
TMPDIR cleanup

### ISSUE THREAD

**Issue by meghanasp21** [google/deepvariant#296]
Hi.

I started using the new version of deepvariant (0:10:0-gpu) and have been getting the following error: 

parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.

It seems like running deepvariant leaves behind temporary files that are taking up a lot of disk space and I was wondering if there is a post run cleaning you recommend to remove these sort of items or some flags to do it?

Thanks for the help!

**Comment by AndrewCarroll** [comment]
Hi @meghanasp21 

I suspect that what is occurring is that previous, no longer used Docker containers from DeepVariant runs are taking up space on your filesystem. Can you run 

**docker system prune** (https://docs.docker.com/config/pruning/)

This should clean up those images. I will also make a note for us to remove intermediate files from within the Docker image after runs (this would only come out in future releases) which should decrease the impact of previous Docker images on storage space.

Thank you,
Andrew

**Comment by meghanasp21** [comment]
Thanks, Andrew.

I actually have been running deepvariant with singularity.

Is there a singularity equivalent to that?

Thanks,
Meghana

**Comment by pichuan** [comment]
Hi @meghanasp21 
If you're running with Singularity, I suspect a temp directory has been created directly under your /tmp/.

The line of code that created the tempdir is this line:

https://github.com/google/deepvariant/blob/r0.10/scripts/run_deepvariant.py#L234

In the logs as you run, it should give you the name of the corresponding directory under `/tmp/`. You can manually remove the directory after your run is finished.

**Comment by meghanasp21** [comment]
Perfect. Will do.

Is there a way to control the name of the temp directory? I think this would be useful especially because I'm parallelizing my runs and don't want to delete tmp directories from active running jobs.

Thanks,
Meghana

**Comment by pichuan** [comment]
Yes, You can use the `--intermediate_results_dir` flag in run_deepvariant to specify the directory:
https://github.com/google/deepvariant/blob/r0.10/scripts/run_deepvariant.py#L73

**Comment by simoncchu** [comment]
I am having the same issue with singularity. 
Here is my commands:
```
ulimit -u 10000 # https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable/54746150#54746150
BIN_VERSION="1.1.0"
mkdir -p deepvariant_m9
mkdir -p deepvariant_m9/intermediate_results_dir

singularity exec --bind /DATA/transfer:/mnt \
  docker://google/deepvariant:${BIN_VERSION} \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref /mnt/asm.ctg.fa \
    --reads /mnt/BAM/DNA/m9.sorted.bam \
    --output_vcf deepvariant_m9/m9.vcf.gz \
    --num_shards 16 \
    --intermediate_results_dir /mnt/deepvariant_tmp/
```
As suggested, I set the `--intermediate_results_dir `. Any comments or suggestions? @pichuan  Thank you!

**Comment by pichuan** [comment]
@simoncchu can you provide more details: your singularity version and operating system version, the actual error message you're seeing, etc.
Anything that will help us reproduce or understand your issue will be helpful.

**Comment by simoncchu** [comment]
singularity version 3.7.0-1.el8

**Comment by pichuan** [comment]
@simoncchu If you ran with:
```
singularity exec --bind /DATA/transfer:/mnt \
```
and
```
    --intermediate_results_dir /mnt/deepvariant_tmp/
```
I think the intermediate output should be in  `/DATA/transfer/deepvariant_tmp` ?
If this run succeeded, can you check what you have under /DATA/transfer and /DATA/transfer/deepvariant_tmp ?

**Comment by simoncchu** [comment]
Yes @pichuan, the intermediate output will be under `/DATA/transfer/deepvariant_tmp`. But the same `no space left` error will pop up. And if I set `tmp/`, then no this error.

**Comment by simoncchu** [comment]
Yes @pichuan, the intermediate output will be under `/DATA/transfer/deepvariant_tmp`. But the same `no space left` error will pop up. And if I set `tmp/`, then no this error.

**Comment by pichuan** [comment]
@simoncchu 
Is there a "tmp" directory under your current working directory then?

**Comment by simoncchu** [comment]
@pichuan 
no such a "tmp" folder.

**Comment by pichuan** [comment]
Hi @simoncchu ,
I tried to run a small Quick Start using the same Singularity and OS version as you. 
With the small tests, I'm not able to see the issue that you observed.

And, when I ran with `--intermediate_results_dir tmp/`, I actually do see a "tmp" directory created at my current working directory.

Given that I'm not able to reproduce your issue, I'm not sure what's the best next step for me. If you're able to share more detailed setting for me so I can reproduce your issue, that'll be helpful. I'm not super familiar with Singularity, so I wonder if there are some other setting (other than the version) that could affect this.

I'll share my steps below so you can take a look.  

----

Here are my steps trying to test Singularity on CentOS 8.

Get a machine:
```
gcloud compute instances create "${USER}-centos8" \
--scopes "compute-rw,storage-full,cloud-platform" \
--image-family "centos-8" \
--image-project "centos-cloud" \
--machine-type "e2-standard-16" \
--boot-disk-size "200G" \
--zone "us-west1-b"
```

ssh into the machine:
```
gcloud compute ssh ${USER}-centos8
```

Check OS version:
```
[pichuan@pichuan-centos8 ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

I installed singularity on the machine following instructions on https://sylabs.io/guides/3.7/admin-guide/installation.html#installation-on-linux

Confirmed the version:
```
[pichuan@pichuan-centos8 ~]$ singularity --version
singularity version 3.7.0-1.el8
```

I'm using the data in Quick Start to test. I downloaded data in the Quick Start: https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md

Then, I ran:
```
BIN_VERSION=1.1.0

singularity build deepvariant.sif docker://google/deepvariant:${BIN_VERSION}

singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
 deepvariant.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --num_shards=1
```

After this, examine the content in "${OUTPUT_DIR}/intermediate_results_dir"

```
[pichuan@pichuan-centos8 ~]$ ls -1 "${OUTPUT_DIR}/intermediate_results_dir"
call_variants_output.tfrecord.gz
gvcf.tfrecord-00000-of-00001.gz
make_examples.tfrecord-00000-of-00001.gz
```

Next, I want to try running with `--intermediate_results_dir tmp/`. First checking the directories in the current working directory:
```
[pichuan@pichuan-centos8 ~]$ ls -1
deepvariant.sif
quickstart-output
quickstart-testdata
```

Then I ran:
```
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
 deepvariant.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
  --reads="${INPUT_DIR}"/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir tmp/ \
  --num_shards=1
```

Now I check the current directory again:
```
[pichuan@pichuan-centos8 ~]$ ls -1
deepvariant.sif
quickstart-output
quickstart-testdata
tmp
```

and I see the intermediate results in the directory:

```
[pichuan@pichuan-centos8 ~]$ ls -1 tmp/
call_variants_output.tfrecord.gz
gvcf.tfrecord-00000-of-00001.gz
make_examples.tfrecord-00000-of-00001.gz
```

**Comment by splaisan** [comment]
Re-opennig this after running two docker jobs and seeing that the tmpdir files of the first run are still there while running the second run.
My docker commands included `--intermediate_results_dir /tmp_dir \` pointing to a local folder.

my question is: should I add a `rm tmpdir/*` after each job to clean this place?

thanks

**Comment by pgrosu** [comment]
@splaisan The intermediate directory is mainly used to generate and store [`TFRecord`](https://www.tensorflow.org/tutorials/load_data/tfrecord) files that are used among the `make_examples`, `call_variants` and `postprocess_variants` steps (performed by the `run_deepvariant` command above) to eventually generate the VCF and gVCF files used for downstream analysis.  So you don't need them after a successfully completed DeepVariant run, as most folks are only interested in the resulting VCF and gVCF files.

**Comment by splaisan** [comment]
Thanks, in that case it would be nice if the command would end with cleaning them unless the user sets some argument to keep them. They are taking a lot of space.

**Comment by pgrosu** [comment]
@splaisan Understood, though what should work as an automatic cleanup in the meantime is if you remove the following two lines:
```
-v "${tmpdir}":"/tmp_dir" \
--intermediate_results_dir /tmp_dir \
```
As that triggers a call to `intermediate_results_dir = tempfile.mkdtemp()`, which creates a temporary directory inside the Docker container that cleans itself up after `run_deepvariant` completes.  Though Docker itself also creates additional files over time that require periodic cleanups.

**Comment by splaisan** [comment]
great, thanks Paul, 
I added these lines because I did not want to overfill the container and was afraid it would write in the /tmp of my host which is very small.
I will try this at the next run
cheers

**Comment by pgrosu** [comment]
Gladly Stephane, and that's understandable though Docker containers usually reside under `/var/lib/docker`:

```
$ docker info | grep Root
 Docker Root Dir: /var/lib/docker
$
```

Since Docker is container-based it doesn't see the operating system outside of its own isolated environment.  That's why the `-v` parameter maps (bind-mounts) a folder from the outside, to be visible inside.  Basically if you don't map in `/tmp`, the container is not aware of it at runtime, and continues to use space under `/var/lib/docker`, by creating new temporary layers of changes to it running image.

In any case, give it a try and someone will be here to help you out if you run into any issues.

Hope it helps,
~p

**Comment by splaisan** [comment]
Thank you for your time and great explanation.
Makes perfect sense now
Cheers

**Comment by pichuan** [comment]
Hi @splaisan ,
like earlier comments mentioned, if you don't specify intermediate_results_dir, it won't be saved separately.

A few more tricks:
1. https://docs.docker.com/config/pruning/ has information about how to clean up for Docker.
2. If you run Docker with `--rm` , I believe it'll also clean up after your run completes.

**Comment by splaisan** [comment]
I already use the -rm option in all my docker runs, thanks for your tips.
