### ISSUE TITLE
Naming evidence bam folders

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#297]
Hello,

not a bug, just a suggestion that might be useful. At the moment when the user request the evidence bams, folders are named

Chrom_1:2000-3000 
It seems the ":" colon is creating problems when one wants to copy the directory somewhere else, on an external drive for example. Of course, it's not that difficult to work around, you can make an archive, or rename all the directories. 

But you might think of a new way to name the folder. 

Cheers

**Comment by aderzelle** [comment]
Okay it's actually really long to rename all the folders X) So that would be great that it names the folders without the use of colon ^^

**Comment by MariaNattestad** [comment]
In bash, you can put quotes around it or escape the ":", e.g. `'chr1:1000-3000'` or `chr1\:1000-3000`.

**Comment by aderzelle** [comment]
Ah yes you are absolutely right, I was just pointing out that it might be easier for the end user if special characters were not present.

**Comment by MariaNattestad** [comment]
Thanks for the suggestion!

**Comment by aderzelle** [comment]
Hello again,

actually the evidence bam folder is borderline unusable, there are so many folders that the file explorer tries to commit suicide every time I attempt to navigate it, same for the "built-in" explorer of bam viewers, for example Tablet is simply unusable, it systematically crashes. 

I don't know how feasible this is computationally but maybe it would be best if DeepVariant produced a single bam per sample. Or even a single bam per sample per chromosome. If the user wants to subsequently split the bam that's not too complicated (otherwise the bam files themselves are neat I am happy with the results ^^). 

Thank you

**Comment by MariaNattestad** [comment]
The feature for outputting the realigned reads is mostly meant for looking deeper and troubleshooting issues in small regions, but we will keep this in mind as a feature request. 

If you do want to use it more broadly for every locus in your sample, you could use `samtools merge` to merge all the bams together from the command-line right away before working with them. Would that help?
