### ISSUE TITLE
Is there an ONNX example?

### ISSUE THREAD

**Issue by tonyreina** [google/deepvariant#299]
Is there an example of converting DeepVariant to ONNX and running inference?

**Comment by pichuan** [comment]
Hi @tonyreina 
We don't have one, but if you or other users want to share an example, that will be great.
I can keep this issue open for another week to see if there's any comments.

**Comment by pichuan** [comment]
(assigning to myself so I can monitor activity of this issue, and close after a week of inactivity)

**Comment by pichuan** [comment]
Closing this one because inactivity.
If anyone wants to provide an example, feel free to add here. Thank you!
