### ISSUE TITLE
Recommendations for Index/fai and reads Alignement/bam

### ISSUE THREAD

**Issue by animesh** [google/deepvariant#3]
Dear Developers, this project sounds awesome and thanks for opening up to the whole community. I have a de-novo assembly of a bacterial strain against whom i would like to align another set of an assembly representing different strains and then hopefully be able to use your pipeline. Wondering what recommendations you have to getting those fai and bam files, tools, settings etc... ?

**Comment by depristo** [comment]
Hi animesh,

Thanks for writing. If you want to use DeepVariant to call variants from reads from a new strain, aligning to your de-novo assembly and applying DeepVariant may work. Unfortunately we don't have any specific recommendations for how you should do that.

**Comment by animesh** [comment]
Thanks for the response @depristo :+1:

**Comment by virpatel524** [comment]
Just following up on this, is the CNN optimized solely for human variant calling or should it deliver similar success on non-model organisms such as bacteria or protists?

**Comment by depristo** [comment]
Our experience is the model works well across a variety of species. But we have not tested it on bacteria or other haploid organisms so we'd love to hear about any results you get there.

**Comment by stevendavis** [comment]
If anyone is interested, I've recently tried DeepVariant on a bacterial dataset.

When the alternate allele frequency is high enough, it makes a genotype call like this:
GT:GQ:DP:AD:VAF:PL      1/1:9:13:[1, 10]:0.769231:[9, 19, 0]

When the alternate allele frequency is too low, the genotype call looks like this (heterozygous):
GT:GQ:DP:AD:VAF:PL      0/1:7:8:[6, 2]:0.25:[6, 0, 35]

One possible solution for haploid organisms is to add a post-processing step to filter the calls where the alternate allele frequency is below some threshold.
