### ISSUE TITLE
Tensorflow .whl is not installing during build

### ISSUE THREAD

**Issue by machomachopadre** [google/deepvariant#30]
### Issue
When running the build-prereq shell script, I'm getting an error when the Tensorflow install begins.

### Error message
```
Installing Google Cloud Platform optimized CPU-only TensorFlow wheel
Copying gs://deepvariant/packages/tensorflow/tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl...
- [1 files][ 41.1 MiB/ 41.1 MiB]    1.0 MiB/s                                   
Operation completed over 1 objects/41.1 MiB.                                     
tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.
```

### Debugging efforts
After browsing around a bit, I discovered that this issue was solved for some through installing the .whl separately. So, I download the whl from the [GCloud bucket](https://console.cloud.google.com/storage/browser/deepvariant/packages/tensorflow/) and executed `sudo python2.7 pip install <name of .whl file>` through the terminal. It ran, just to tell me “.dist-info directory not found”.

I think this might be due to some inconsistency in the packages installed through the build-prereq.sh script, because I can see that all the packages that it installed (e.g. numpy) are for Python 3.5, but the Tensorflow version it's trying to get is for cp27 (Python 2.7).

Not sure about where to go from here, would love some assistance :).

### System details
OS: Ubuntu 16.04 LTS
Python interpreters: Default with Ubuntu (2.7 and 3.5.2)
Deep Variant version: Installed it today from the main repo, so probably r0.4.1

Thank you

**Comment by depristo** [comment]
Thanks @machomachopadre for your report. Just so I'm 100% clear, you've got python 2.7 and 3.5 on the machine, and our build-prereqs.sh script is installing some packages into python 3.5 and some into 2.7? I don't think we've been clear before about this, but DeepVariant is intended for python 2.7 only, as we've never tested it using python3. 

Can you confirm that you can install DeepVariant on a clean Ubuntu 16 instance in the cloud?

**Comment by machomachopadre** [comment]
@depristo This might be happening because I'd aliased the "python3" command as "python", which is supposed to be for python 2.7 by default. Any idea as to how I could reset everything such that it installs only for python 2.7 (I've already removed the alias)?

**Comment by depristo** [comment]
Unfortunately I'm not really sure how to do that. It sounds like you've resolved the issue w.r.t. DeepVariant though. I'm closing this bug.
