### ISSUE TITLE
DeepVariant calling 10-fold more variants than GATK

### ISSUE THREAD

**Issue by meghanasp21** [google/deepvariant#300]
Hi.

I have been using deepvariant to call germline and somatic variants from WGS samples. For calling germline variants, I have been running GATK 3.8 side by side. By just looking at the number of variants, deepvariant calls 10x more variants for chromosome 1 than GATK (see attached) when filtering for PASS.
![deepvariantvgatk](https://user-images.githubusercontent.com/45370974/79917221-13784a80-83f8-11ea-93c3-8ccc972aeb62.png)

I have tried to see if setting a GQ filter would improve the overlap and it does not. I am wondering if this is an issue because I am trying to call germline variants from normal bams (not tumor bams). I also have the command that I used to run deepvariant below. Is there a flag I may be missing?

singularity run --nv deepvariant_0.10.0-gpu.sif /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=$ref --reads=$bam --regions $chr --output_vcf=$x.$chr.vcf.gz --intermediate_results_dir /tmp/$USER/$SLURM_JOB_ID/$SLURM_ARRAY_TASK_ID --output_gvcf=$x.$chr.g.vcf.gz --num_shards=3

Also as a follow-up question, what is the gold standard way to call germline vs somatic variants? I can't seem to find the documentation on how to include the matched normal for somatic variant calling.

Thanks again for the help.

**Comment by pichuan** [comment]
Hi @meghanasp21 
DeepVariant is a germline variant caller. In the version on GitHub, it is not designed to call somatic variants.

Looking at your numbers in the images, it seems to indicate that DeepVariant calls about 340k germline variants on chromosome 1 on a WGS sample. This is consistent with my understanding of the number of germline variants in human.

Is there any reason that you're expecting 10x less than that on average?

Thanks.

**Comment by meghanasp21** [comment]
Thanks for clarifying.

I was just curious, because when I used GATK to call germline variants, it gave me 10x less, so I just was curious about the large discrepancy. But, perhaps this is more of a GATK pipeline issue.

So, the "PASS" variants should be the final filtered germline variants?

Thanks.

**Comment by pichuan** [comment]
Hi @meghanasp21 

Yes - "PASS" variants are the ones that DeepVariant has made a call and indicate that DeepVariant thinks there is a germline variant at the position.
You can also refer to : https://samtools.github.io/hts-specs/VCFv4.2.pdf
```
FILTER - filter status: PASS if this position has passed all filters, i.e., a call is made at this position. 
```
Other than the conventional "PASS" to indicate that the tool has made a call, you might also see many other values being filled into this field. Especially if you have run somatic callers, you might notice people use it for various reasons why they filter out a variant.

Currently, in DeepVariant, you might see another value "RefCall" - this means that DeepVariant identifies a position as a potential candidate early on, but the machine learning model decided that it is actually Ref (0/0). 

So yes, for DeepVariant, you should just look at the ones that has "PASS".

**Comment by AndrewCarroll** [comment]
Hi @meghanasp21 

Your number of candidates (both PASS and the filtered ones) for DeepVariant are unusual. Do you know what sample preparation was used? I can think of a few that might cause an increase in number of candidates, for example FFPE. The other question is what coverage are these normal BAMs at?

To your second question, are you asking for best practices for tumor+normal calling in general (beyond DeepVariant but to other methods like Mutect or Strelka)? DeepVariant is not intended as a somatic caller and we don't have recommendations for this.

Thanks,
Andrew
