### ISSUE TITLE
High density SNPs call in some but not all samples

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#303]
Hello, 
I used DeepVariant with the mosquito trained model, on 11 samples, then performed joint calling with GLnexus. In the following track, in the first sample it calls 2 SNP G/A and T/C (corresponding to the 2 last blue box) in the D2A1 sample. However, in the D5B3 sample the sites are called as 0/0. There is no "RefCall" either so I think it means it did not even generate candidates. 
Point to note: I have no idea if there are, or not, SNPs at those 2 loci. But from the alignment, it is not at clear to me why in one case it thought there were SNPs, and in the other case it thought not. 

For the same sites, GATK joint caller decided the site was 0/0 for all samples (again, I don't know which one is the true genotype there).

The bam I am showing here are the diagnostic bams emitted by DeepVariant, so my understanding is that I see what it saw.

![igv_snapshot](https://user-images.githubusercontent.com/23341393/80101296-7e995c80-8571-11ea-8e3d-37e306442888.png)

As you might notice, the coverage depth across my samples is not always identical. So I wonder if it's not simply a question of coverage (though my lowest average coverage value is 30, which is ok I think). 

Would you have any clue of what might be happening? 

Thank a lot

EDIT: I can get rid of those regions by filtering on QUAL on the GLnexus pVCF, however. But I am still curious, as I might want to keep them and filter them otherwise (not easy to reach a spot where you get read of FP without removing all the TP).

**Comment by pichuan** [comment]
Posting on behalf of @akolesnikov 
---
Candidates are generated when the following criterias are met:
(1) Base quality is greater than the threshold;
(2) Number of reads supporting alt allele are greater than the threshold;
(3) Ration of reads supporting alt allele to all the reads is greater than the threshold (it is 0.12 for SNPs)

From the IGV image it looks like the coverage is much greater than what we can see on the picture. It is not possible to pinpoint the exact reason for candidate not generated in the second sample unless we can see the entire picture.

**Comment by aderzelle** [comment]
Hello, 

thanks for the reply (and sorry for delay getting back in touchà. It's indeed a question of coverage, as this sample has a lot of coverage, this somehow create a significant amount of bogus mapping in some regions.
