### ISSUE TITLE
Pileup images for insersions

### ISSUE THREAD

**Issue by jumpyknight** [google/deepvariant#306]
Hi, I'm trying to visualize the pileup images generated by DeepVariant. The images for SNP sites and deletions seem to be straightforward, but I found those for insertions are rather confusing.

The reference lines for insertion sites are still continuous, and at the point where the insertion happens, the bases on the sequenced reads are set to 0. Here's part of an example of a homozygous "A->AATAAAAT" variant, the top 5 lines are the reference lines.

250 | 30 | 180 | 250 | 250 | 100 | 250
250 | 30 | 180 | 250 | 250 | 100 | 250
250 | 30 | 180 | 250 | 250 | 100 | 250
250 | 30 | 180 | 250 | 250 | 100 | 250
250 | 30 | 180 | 250 | 250 | 100 | 250
250 | 30 | 180 |     0 | 250 | 100 | 250
250 | 30 | 180 |     0 | 250 | 100 | 250
250 | 30 | 180 |     0 | 250 | 100 | 250
250 | 30 | 180 |     0 | 250 | 100 | 250

The problem is these images are not presenting detailed infomation for the inserted sequence, and on sites where multiple insertions happen, the "supports variant" channel might become the only useful infomation to distinguish them.
Also, on the "base quality" channel, the qualities for these 0-bases are not zeros, how are these values determined?

I'm wondering if other structures of pileup images on these sites can achieve better performance, like adding 0s on the reference lines?

**Comment by AndrewCarroll** [comment]
Hi @jumpyknight 

You are correct, and this description shows a good amount of thought and analysis about what DeepVariant sees. The full insert information is not present, meaning that for insertions (especially long ones or at multi-allelic sites), the supports variant channel becomes very important. 

We have made a similar observation and are currently working on an improvement that will allow capturing more information about these insertions. I hope that this will go out in the next release version of DeepVariant.

I believe that the base quality present at these insertion positions reflects the base quality of the base overlapping the reference base just prior to the insertion.

**Comment by jumpyknight** [comment]
Thanks for the reply, and it's great to hear about your plan on improving the pileup images of these insertions.

**Comment by yonatansc97** [comment]
Hi,
I too am trying to deepen my understanding of DeepVariant (pun unintended).
If I understand the discussion above correctly, whenever there is an insertion, the insertion itself will not be present in the pileup image, and the preceding pixel will be zero'd out.

So if we have a cigar 6M3I1M such as:
ref: ACGCCT      T
alt: ACGCCTCCCT
this will actually be represented in the pileup as:
ref: ACGCCTT
alt: ACGCC0T

I visualized the examples you provided in testdata, and on the 3rd example [fig1] (chr20:10001436-10001436) there is a case in which an insertion occurs right after the variant's position. Following the above logic, the center column should be zero'd out. However, it  seems to not be the case. What happens instead is that the last channels center column indicates a diversion from the reference genome (a pixel is 'lit' up). So it looks like the bam read is a basic SNP, even though it actually is a length 5 insertion (the bam is an indel and the variant in the vcf is an snp).
In fact, I haven't seen any case of zero'd out pixels which aren't deletions.
Some options are:
1. Did I not understand the insertions logic correctly?
2. Am I possibly working with the wrong files? I use the NA12878_S1.chr20.10_10p1mb.bam/.bai bam file with the golden.training_examples.tfrecord for your examples.

Sorry for the long post, I hope I was clear but let me know if more information/explanations are needed.
![fig1](https://user-images.githubusercontent.com/52149642/98434406-e7908e00-20d7-11eb-8097-bf853b8a6851.png)
