### ISSUE TITLE
Cram support errors

### ISSUE THREAD

**Issue by Roj4ck** [google/deepvariant#307]
I'm currently attempting to run Deepvariant 0.10.0 utilizing a cram file with a reference file.  Everything else appears to be properly coded but it seems to fail upon reading the fa file.  After failing it tries to fallback to an fai file that doesn't exist.  I've tried it both compressed and uncompressed and it still seems to give the same error.  Any ideas on what I should do here? 

For reference Here is the command i'm running from Docker
sudo docker run \
    -v "${DATA_DIR}":"/input" \
    -v "${OUTPUT_DIR}:/output" \
    gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type=WES \
    --ref="/input/${REF}" \
    --reads="/input/${BAM}" \
    --output_vcf=/output/${OUTPUT_VCF} \
    --output_gvcf=/output/${OUTPUT_GVCF} \
    --num_shards=$(nproc)
 
and here is the error i'm seeing right before crashing:
I0509 06:55:24.592304 140264323651328 genomics_reader.py:223] Reading /input/2009617.cram with NativeSamReader
I0509 06:55:24.597789 140264323651328 make_examples.py:535] Task 2/16: Preparing inputs
[E::fai_load3_core] Failed to open FASTA index /input/hg19.fa.gz.fai: No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1510, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1500, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1358, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1264, in processing_regions_from_options
    options.reference_filename).header.contigs
  File "/tmp/Bazel.runfiles_2jmg0cod/runfiles/com_google_deepvariant/third_party/nucleus/io/fasta.py", line 106, in __init__
    fasta_path, fai_path, options)
ValueError: Not found: could not load fasta and/or fai for fasta /input/hg19.fa.gz
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/hg19.fa.gz --reads /input/2009617.cram --examples /tmp/tmpr2hdz82_/make_examples.tfrecord@16.gz --gvcf /tmp/tmpr2hdz82_/gvcf.tfrecord
@16.gz --task 1
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/hg19.fa.gz --reads /input/2009617.cram --examples /tmp/tmpr2hdz82_/make_examples.tfrecord@16.gz --gvcf /tmp/tmpr2hdz82_/gvcf.tfrecord
@16.gz --task 4
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /input/hg19.fa.gz --reads /input/2009617.cram --examples /tmp/tmpr2hdz82_/make_examples.tfrecord@16.gz --gvcf /tmp/tmpr2hdz82_/gvcf.tfrecord
@16.gz --task 7
real    0m5.299s
user    0m12.412s
sys     0m3.014s
I0509 06:55:25.059437 140033813915392 run_deepvariant.py:321] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 15 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/hg19.fa.gz" --reads "/input/2009617.cram" --
examples "/tmp/tmpr2hdz82_/make_examples.tfrecord@16.gz" --gvcf "/tmp/tmpr2hdz82_/gvcf.tfrecord@16.gz" --task {}' returned non-zero exit status 1.

**Comment by MariaNattestad** [comment]
Hi @Roj4ck 
Does the $REF you provide also have a $REF.fai index file with the same prefix?
This is required by DeepVariant. See https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-details.md

**Comment by Roj4ck** [comment]
Thanks for the response Dr. Nattestad.  I was only given the hg19.fa files along with the cram files. 
Initially I discovered I was using an old version of Samtools so once I updated I tried using use the hg19.fa.   I have updated and rebuilt my fai files using the command samtools faidx hg19.fa .  I've set my environment variables as the following:
BIN_VERSION="0.10.0"
BASE="${HOME}/deepvariant-run"
INPUT_DIR="${BASE}/input"
REF="hg19.fa"
BAM="2009617.cram"
OUTPUT_DIR="${BASE}/output"
DATA_DIR="${INPUT_DIR}/data"
OUTPUT_VCF="2009617.vcf.gz"
OUTPUT_GVCF="2009617.bam.g.vcf.gz"
OUTPUT_GVCF="2009617.bam.g.vcf.gz"
Here is the command to execute deepvariant:
sudo docker run \
    -v "${DATA_DIR}":"/input" \
    -v "${OUTPUT_DIR}:/output" \
    gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type=WES \
    --ref="/input/${REF}" \
    --reads="/input/${BAM}" \
    --output_vcf=/output/${OUTPUT_VCF} \
    --output_gvcf=/output/${OUTPUT_GVCF} \
    --num_shards=$(nproc)
and here is the new errors I'm seeing:
ValueError: Failed precondition: Cannot query without an index
parallel: This job failed:

Which eventually leads to the following errors where the process fails and ends: Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 332, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 319, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 15 | parallel --halt 2 --line-buffer /opt/deepvariant/bin/make_examples
 --mode calling --ref "/input/hg19.fa" --reads "/input/2009617.cram" --examples "/tmp/tmp1cb8k6ly/make_examples.tfrecord@1
6.gz" --gvcf "/tmp/tmp1cb8k6ly/gvcf.tfrecord@16.gz" --task {}' returned non-zero exit status 1.

**Comment by MariaNattestad** [comment]
The error message says "Cannot query without an index", so I'm guessing your CRAM file might be missing its index too. See: http://www.htslib.org/doc/samtools-index.html
Again see the [documentation](https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-details.md).

**Comment by Roj4ck** [comment]
You were completely correct after some working through some index issues with cram( which for future reference for anyone dealing with the same issues was done here https://github.com/samtools/htslib/issues/1069 ) all seems to be running smoothly.  Thank you again for your time!
