### ISSUE TITLE
Failed to open FASTA index

### ISSUE THREAD

**Issue by colsen** [google/deepvariant#310]
Hello,

I get an error about a missing index file for the used fasta. But it is available in the specified folder

BIN_VERSION="0.10.0"

 docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}:/output" gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/input/hg19.fasta --reads=/input/input.bam --output_vcf=/output/output.vcf.gz --output_gvcf=/output/output.g.vcf.gz --num_shards=15

I0529 12:24:27.041167 139828907894528 make_examples.py:535] Task 5/15: Preparing inputs
[E::fai_load3_core] Failed to open FASTA index /input/hg19.fasta.fai: No such file or directory

Do you have any idea why this happens?

**Comment by Roj4ck** [comment]
The error messages sounds like it's not seeing your fasta index file.  Since you are utilizing environment variables I would suggest verifying that those are accurate and that both your fasta and it's corresponding index file are present in that same directory.

**Comment by pichuan** [comment]
Thank you @Roj4ck !

@colsen , what @Roj4ck said is exactly right. :) 
In your case, you should make sure there is a index file for your hg19.fasta file, under your $INPUT_DIR directory. The name is usually hg19.fasta.fai. If you really don't have a fai file, you can run `samtools faidx hg19.fasta` to create it.

I'll close this issue. Feel free to open new ones if you have more questions.

**Comment by colsen** [comment]
@pichuan @Roj4ck thanks for your quick reply. However the index is available in the same directory. I also tried removing it and recreating it with the samtools command. This didn't resolve the problem.

**Comment by pichuan** [comment]
Hi @colsen 
thanks for confirming that the file was there. At this point I don't have a clear next guess on what could have been wrong. But can you check these two things:

1. Confirm that docker see this file:
Run a similar command:

docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}:/output" gcr.io/deepvariant-docker/deepvariant:"${BIN_VERSION}" ls /input/hg19.fasta*

This can confirm that docker actually sees the file. (should have both hg19.fasta and hg19.fasta.fai)

2. Run another program to make sure the the fasta file is well-formed.

Given that you have tried samtools faidx it without issue, I think this is probably not the issue, but might still be good to check.

@Roj4ck if you have more suggestions on this, please feel free to chime in!

**Comment by colsen** [comment]
@pichuan with the ls command inside the docker I could figure out the problem. Replacing /input/${REF} with /input/input/${REF} in --ref solved the problem. Thanks for your help!
