### ISSUE TITLE
High number of Indeterminate consistency in merged VCF

### ISSUE THREAD

**Issue by Roj4ck** [google/deepvariant#311]
I recently took four cram files (one family) and put them through the deep variant pipeline in accordance with the documentation.  I then followed the instructions for "Best practices for multi-sample variant calling with DeepVariant (WES trio demonstration)" and tried two sets of of "trios" and one comparison containing all four.  Each of them however came up with a substanial amount of mendelian constraints which I'll list below:

Checking: /home/username/deepvariant-run/output/RBAs.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2115432]
12 non-pass records were skipped
Concordance 2115432: F:127216/127862 (99.49%)  M:121292/121882 (99.52%)  F+M:79650/80917 (98.43%)
Sample 2115432 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
4249/338863 (1.25%) records did not conform to expected call ploidy
228759/338863 (67.51%) records were variant in at least 1 family member and checked for Mendelian constraints
147067/228759 (64.29%) records had indeterminate consistency status due to incomplete calls
1838/228759 (0.80%) records contained a violation of Mendelian constraints

Checking: /home/username/deepvariant-run/output/RBNs.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617]
18 non-pass records were skipped
Concordance 2009617: F:124581/125097 (99.59%)  M:120027/120545 (99.57%)  F+M:79289/80523 (98.47%)
Sample 2009617 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
3705/295693 (1.25%) records did not conform to expected call ploidy
184648/295693 (62.45%) records were variant in at least 1 family member and checked for Mendelian constraints
103541/184648 (56.07%) records had indeterminate consistency status due to incomplete calls
1603/184648 (0.87%) records contained a violation of Mendelian constraints

Checking: /home/username/deepvariant-run/output/RBNAs.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617, 2115432]
24 non-pass records were skipped
Concordance 2009617: F:125675/126263 (99.53%)  M:121023/121623 (99.51%)  F+M:79766/81139 (98.31%)
Sample 2009617 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
Concordance 2115432: F:128175/128895 (99.44%)  M:122173/122833 (99.46%)  F+M:80026/81440 (98.26%)
Sample 2115432 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
4510/361421 (1.25%) records did not conform to expected call ploidy
286909/361421 (79.38%) records were variant in at least 1 family member and checked for Mendelian constraints
197595/286909 (68.87%) records had indeterminate consistency status due to incomplete calls
3231/286909 (1.13%) records contained a violation of Mendelian constraints

I'm not sure if the issue is within the deepvariant scan or perhaps the merge within RTG tools.  If you have seen this problem before i'm open to any suggestions.  Additionally if this issue is more so on the RTG tools side if things please feel free to close this out and I'll open the issue there.  Thank you for your time and have a great day.

**Comment by Roj4ck** [comment]
Just realized my code was pointing towards the .vcf.gz files and not to .g.vcf.gz files.  After making that changes my indeterminate consisentcy dropped to between 5-7% but my violations of Mendelian constraints have increased significantly as well.  Are the values listed here fairly normal or is there perhaps something else you would recommend.  LIsted below are the results from my latest merge:

Checking: /home/username/deepvariant-run/output/RBA2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2115432]
12 non-pass records were skipped
Concordance 2115432: F:261458/309172 (84.57%)  M:267986/314085 (85.32%)  F+M:219733/301071 (72.98%)
Sample 2115432 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
7460/338863 (2.20%) records did not conform to expected call ploidy
323711/338863 (95.53%) records were variant in at least 1 family member and checked for Mendelian constraints
17278/323711 (5.34%) records had indeterminate consistency status due to incomplete calls
86448/323711 (26.71%) records contained a violation of Mendelian constraints

Checking: /home/username/deepvariant-run/output/RBN2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617]
18 non-pass records were skipped
Concordance 2009617: F:244269/268058 (91.13%)  M:251439/272790 (92.17%)  F+M:219530/260889 (84.15%)
Sample 2009617 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
5804/295693 (1.96%) records did not conform to expected call ploidy
281378/295693 (95.16%) records were variant in at least 1 family member and checked for Mendelian constraints
16563/281378 (5.89%) records had indeterminate consistency status due to incomplete calls
45031/281378 (16.00%) records contained a violation of Mendelian constraints

Checking: /home/username/deepvariant-run/output/RBNA2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617, 2115432]
24 non-pass records were skipped
Concordance 2009617: F:254730/275763 (92.37%)  M:261777/280640 (93.28%)  F+M:228534/267907 (85.30%)
Sample 2009617 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
Concordance 2115432: F:275692/314566 (87.64%)  M:282207/319606 (88.30%)  F+M:227816/305838 (74.49%)
Sample 2115432 has less than 99.0 concordance with both parents. Check for incorrect pedigree or sample mislabelling.
8113/361421 (2.24%) records did not conform to expected call ploidy
358380/361421 (99.16%) records were variant in at least 1 family member and checked for Mendelian constraints
25958/358380 (7.24%) records had indeterminate consistency status due to incomplete calls
103177/358380 (28.79%) records contained a violation of Mendelian constraints

**Comment by pichuan** [comment]
Hi @Roj4ck , 
can you provide more detail on what kind of data are you applying DeepVariant on? For example:
What type of sequencing data, what depths, what organism, anything noticeably different from the data we used in case studies, etc.

And, my guess is that the "incomplete calls" are referring to calls that DeepVariant as `./.`.
It'll be great if you can also report: how many number of calls in your VCFs, how many GTs are in each calls (e.g., how many calls are `./.`)?

This will help us get a better idea to help answer your question.

And, if your data is public, you can point to us and we can take a look.

Adding @tedyun for your thoughts (Ted is the first author of our [cohort manuscript](https://doi.org/10.1101/2020.02.10.942086)]
Adding @akolesnikov who's on rotation this week as an FYI.

**Comment by Roj4ck** [comment]
Thank you for the quick response!
I'd be glad to provide more information (the information listed below is from the original datasets / metrics provided from the genetic testing company that performed the tests utilizing their own tooling.)
What type of sequencing data?  Diagnostic Testing / XomeDx / Clinical Exome Sequence Analysis (provided in cram format with md5 hg19 as reference and the accompanying vcfs from said company) 
what depths - 152x mean depth of coverage with a quality threshold of 98.6
what organism - Humans using hg19 as reference (family of 4 two affected female probands two unaffected parents)
Anything noticeably different from the data we used in case studies - nothing that i'm aware of at this time

It'll be great if you can also report: how many number of calls in your VCFs, how many GTs are in each calls (e.g., how many calls are ./.)? -I'm not completely sure where this is located but I believe I can find it.

This will help us get a better idea to help answer your question.

And, if your data is public, you can point to us and we can take a look.  - The data is not available publicly yet but I would be glad to share it with you and your team.  It has been submitted for public sharing with mygene2 (at least I'm pretty sure they are not online yet).  I do, however,  plan on sharing them online with Genome Connect and the rest of genetic community in the near future.

**Comment by tedyun** [comment]
Hi @Roj4ck I think it cloud be helpful to add the flag `-o output_rtg_annotated.vcf.gz` flag when running `rtg mendelian`, and to manually inspect the output by `zless output_rtg_annotated.vcf.gz`. This file should have a specific annotation for calls with indeterminate consistency status. As @pichuan mentioned above they're most likely due to incomplete genotypes like `./.`. You can also manually inspect a few number of calls violating Mendelian consistency and try to find patterns among them. You can find more instructions about the RTG Tools in their documentation: https://cdn.rawgit.com/RealTimeGenomics/rtg-tools/master/installer/resources/tools/RTGOperationsManual/rtg_command_reference.html#mendelian

It'll be also useful to know how many samples are included in the cohort VCF file.

**Comment by Roj4ck** [comment]
The amount of values in each cohort are in my earlier post with more details but in summary.  (3 in the first (2 parents 1 affected proband) 3 in the second (2 parents and the other affected proband) and 4 in the third (both parents and both affected probands).  I'll try running that command and see what type of or results I get and report back ASAP.  Thank you both for your assistance.

**Comment by Roj4ck** [comment]
I reviewed the anotated vcf.gz files (just utilized a simple search in a text editor for counts and I identified the following counts:

Checking: /home/username/deepvariant-run/output/RBA2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2115432]
17278/323711 (5.34%) records had indeterminate consistency status due to incomplete calls
64534 of the values were ./.

Checking: /home/username/deepvariant-run/output/RBN2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617]
25958/358380 (7.24%) records had indeterminate consistency status due to incomplete calls
59210 of the values were ./.

Checking: /home/username/deepvariant-run/output/RBNA2s.cohort.vcf.gz
Family: [2114337 + 2114302] -> [2009617, 2115432]
25958/358380 (7.24%) records had indeterminate consistency status due to incomplete calls
118840 of the values were ./.

**Comment by Roj4ck** [comment]
I'm going to try sifting through this to see if there is anything in here.  If I run into any other issues I'll let your teams know.  Thank you both for your time (and if you have any recommendations for sifting deep variant called vcfs I'll glady take them :-).
