### ISSUE TITLE
Conda: dv_make_example.py execution error. 

### ISSUE THREAD

**Issue by tetsuro90** [google/deepvariant#314]
Hi, 

I had trouble running Deepvariant using conda.

I ran the following command.
```
dv_make_examples.py --sample {MY_SAMPLE} --ref {MY_FASTA}.fasta --reads {MY_BAM}.bam --logdir ./log/ --examples examples/
```

and I got an error like this:
```
ETA: 0s Left: 1 AVG: 0.00s  local:1/0/100%/0.0s sh: 1: unzip: not found
Traceback (most recent call last):
  File "/opt/conda/envs/deepvariant/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/deepvariant/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/conda/envs/deepvariant/share/deepvariant-0.10.0-3/binaries/DeepVariant/0.10.0/DeepVariant-0.10.0/make_examples.zip/__main__.py", line 252, in <module>
  File "/opt/conda/envs/deepvariant/share/deepvariant-0.10.0-3/binaries/DeepVariant/0.10.0/DeepVariant-0.10.0/make_examples.zip/__main__.py", line 187, in Main
  File "/opt/conda/envs/deepvariant/share/deepvariant-0.10.0-3/binaries/DeepVariant/0.10.0/DeepVariant-0.10.0/make_examples.zip/__main__.py", line 138, in GetRepositoriesImports
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/Bazel.runfiles_qwsw52c7/runfiles'
parallel: This job failed:
/opt/conda/envs/deepvariant/bin/python /opt/conda/envs/deepvariant/share/deepvariant-0.10.0-3/binaries/DeepVariant/0.10.0/DeepVariant-0.10.0/make_examples.zip --mode calling --ref E.coli_K12_MG1655.fa --reads SRR1770413.bam --examples examples//SRR1770413.tfrecord@1.gz --task 0
```

When I installed unzip by `conda install`, the command worked fine.

When using conda to install deepvariant, should it not have to be installed together?

Thanks,

**Comment by tetsuro90** [comment]
This command was excuted in a docker container.

Host:
macOS Catalina 10.15.5
Docker version 19.03.8, build afacb8b

container
ubuntu:18.04
conda 4.8.3
conda env channnel: bioconda, conda-forge
deepvariant:0.10.0

**Comment by chapmanb** [comment]
Thanks for trying out the conda deepvariant package and apologies about the issue. unzip is a dependency on the bioconda recipe, and my guess is that it's available in the environmental bin directory ( `/opt/conda/envs/deepvariant/bin/`) but this is not present on your PATH within the docker container so it's not being found. If you add that to the PATH for the container environment, it'll hopefully resolve the problem. Hope this helps.

**Comment by tetsuro90** [comment]
@chapmanb 
Thank you for your reply!

I checked the container PATH.
```
~$ echo $PATH
/opt/conda/envs/deepvariant/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

and I tried to find out if unzip exists in the bin directory.
```
~$ ls /opt/conda/envs/deepvariant/bin/
.
.
.
-rwxrwxr-x  2 root root    22480 Dec 11  2018 toe*
-rwxrwxr-x  2 root root    22512 Dec 11  2018 tput*
-rwxrwxr-x  2 root root    30680 Dec 11  2018 tset*
lrwxrwxrwx  1 root root        3 Jun  3 00:24 unlz4 -> lz4*
lrwxrwxrwx  1 root root        2 Jun  3 00:24 unlzma -> xz*
-rwxrwxr-x  2 root root   238086 May 18 15:34 unpack200*
lrwxrwxrwx  1 root root        2 Jun  3 00:24 unxz -> xz*
lrwxrwxrwx  1 root root        4 Jun  3 00:24 unzstd -> zstd*
-rwxrwxr-x  2 root root    25904 Dec 18 17:04 uuclient*
-rwxr-xr-x  1 root root      236 Jun  3 00:24 wheel*
lrwxrwxrwx  1 root root        7 Jun  3 00:24 wish -> wish8.6*
.
.
.
```

The unzip itself doesn't seem to be installed during `conda install` .
Is this a problem that only happens to me?

Thanks!

**Comment by chapmanb** [comment]
Thanks for reporting back and sorry my guess wasn't very helpful for resolving the problem. I'm a bit confused as to why it doesn't get unzip as a requirement since it's listed in the host dependencies in the conda recipe (https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deepvariant/meta.yaml#L28). On the next iteration of the recipe we could add it to the `run` requirements to try and avoid this. In the short term, does adding `unzip` to your conda package install for the environment when building the Docker container avoid the issue and get things running? If you have other missing dependencies please let us know and we could have a similar treatment to fix them. Hope this helps.

**Comment by tetsuro90** [comment]
@chapmanb 
Thank you for your reply. 
I have seen the conda recipi. It is indeed strange. Maybe there's something wrong with my running environment.
OK, I'll deal with it by installing `unzip` directly in `apt` or `conda`.
Thanks a lot!
