### ISSUE TITLE
conda: where is the run_deepvariant command

### ISSUE THREAD

**Issue by yiolino** [google/deepvariant#316]
Hi, @chapmanb
Sorry for asking so many questions.

 I looked for the `run_deepvariant` command in the conda package, but the I couldn't find it.
So to generate the vcf file, I created the following code

```
dv_make_examples.py \
    --cores {threads} \
    --ref {ref} \
    --reads {bam} \
    --sample {samplename} \
    --examples {output_dir}/{samplename} \
    --logdir {log_dir} 

dv_call_variants.py \
    --cores {threads} \
    --outfile {output_dir}/{samplename}.tmp \
    --sample {samplename} \
    --examples {output_dir}/{samplename} \
    --model {model} 

dv_postprocess_variants.py \
    --ref {ref} \
    --infile {output_dir}/{samplename}.tmp \
    --outfile {vcf}
```

Or is there a way to run the `run_deepvariant` command that I am just not aware of?
I'd like to generate a gvcf file if possible.

**Comment by gunjanbaid** [comment]
Hi @tetsuro90, `run_deepvariant` is only available for Docker and not for Conda. You can reference [this doc](https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-gvcf-support.md) for the flags needed to write out GVCFs.
