### ISSUE TITLE
Why are mitochondrial chromosomes excluded?

### ISSUE THREAD

**Issue by williamrowell** [google/deepvariant#323]
https://github.com/google/deepvariant/blob/4b937f03a1336d1dc6fd4c0eef727e1f83d2152a/deepvariant/exclude_contigs.py#L43

I just noticed that mitochondrial chromosomes are blacklisted along with alt contigs.  I just wondered what the reasoning was behind this.  Is this because of the much higher coverage, the different ploidy expectations, or something else I'm not thinking of.  Also, is it possible to override the blacklist?

**Comment by gunjanbaid** [comment]
Hi @williamrowell, there is no flag for changing which contigs are excluded, but you could modify `exclude_contigs.py` and rebuild the Docker image / binaries. As for the MT, one of the main reasons is that MT variants can be heteroplasmic, and in these cases variant calling resembles somatic calling. It's unclear that we would be able to generate candidates well for such variants or that the network would be to handle them correctly.

**Comment by gunjanbaid** [comment]
@williamrowell I'll close this issue, but feel free to reopen if there are any followup questions.
