### ISSUE TITLE
VQSR and truth sets

### ISSUE THREAD

**Issue by leorippel** [google/deepvariant#324]
Hello,

There is a way to perform some kind of VQSR or use truth sets for calling on Deepvariant?

Cheers.

**Comment by gunjanbaid** [comment]
Hi @leorippel, we don't recommend running VQSR on DeepVariant callsets. As for the truth sets, at what stage do you wish to use the truth sets for calling? Truth sets are required for training the model, but not needed needed for running inference.

**Comment by leorippel** [comment]
Hi,

I see.
Yes, I was willing to try on training models.  So, those models trained with truth sets are later used on inference or goes as input a single run_deepvariant run?  


Cheers.

**Comment by gunjanbaid** [comment]
That's correct, we provide the models trained with Genome in a Bottle truth sets as part of our Docker image and also in [this directory](https://pantheon.corp.google.com/storage/browser/deepvariant/models%2FDeepVariant%2F). The truth sets are available publicly at ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/release/. 

All of the models we provide can be used for inference for the respective data types (WGS, WES, PacBio). When running inference, you can specify which model you would like to use. You can use any one of our provided models, or you can train your own models and use those.

**Comment by leorippel** [comment]
Ok, 

Thanks for clarifying that. 

If I dont specify "--genome " or specific model using just "--model wgs" what model is used? I'm currently using deepvariant to variant calling for a pinus genome project. My input was Pinus.fasta and Pinus.fai for the genome part, for that I'm assuming that deepvariant is not using any of human trained data. I'm correct in assuming this?

How can I train my data using a set of truth variants?

Cheers.


"
$ run_deepvariant.py --model_type=WGS --ref=Pinus.fasta --reads=mapped.sorted.bam --output_vcf=output/output.vcf.gz --output_gvcf=output/output.g.vcf.gz --num_shards=16

""

**Comment by AndrewCarroll** [comment]
Hi @leorippel 

If you are referring specifically to the process of VQSR, we do not recommend this step. In our benchmarks for VQSR, at both the cohort and individual level, recall and overall accuracy are substantially worse (see Figure3 of https://www.biorxiv.org/content/10.1101/2020.02.10.942086v1.full.pdf or Table 1 of https://www.nature.com/articles/nbt.4235).

If you would like to further filter variant calls to increase precision, we recommend instead filtering based on genotype quality instead, with something like a cutoff of GQ>10 being reasonable (this implies the lowest retained variant has at least a 90% chance of being correctly called).

The model specified in the command line here is the model used for the calling process itself. It is, in theory, possible to retrain this model, but you would need to have a set of confident sites generated through a process with better accuracy, for example deep PacBio HiFi data and using those sites to train an Illumina model. This process is technically involved as well, so my recommendation is that if you would like higher precision, you can apply a filter on the GQ value for calls.

Thanks,
Andrew

**Comment by leorippel** [comment]
Hello @AndrewCarroll ,

Thanks for you know-how, valuable suggestion. VQSR seems now something to be forgot. 

How much benefit would I  have using a truth set for my analysis, without training? Worth the trouble?

I will have a slightly refined truth set soon enough following excluding a small proportion of SNP in the QTL population maps. 


Cheers.

**Comment by gunjanbaid** [comment]
Hi @leorippel, I am assuming you are asking about using the truth set for final assessment of the calls produced by DeepVariant. If you have confidence in the quality of your truth set, it makes to use this for additional analysis. I'll go ahead and close this issue, but feel free to reopen if you have additional questions!
