### ISSUE TITLE
Ask for definite CNN structure

### ISSUE THREAD

**Issue by X1angyang** [google/deepvariant#328]
Hi!
I am new in variant detection, especially detection in deep learning.  I want to implement the process from bam file to output file for deepening the  knowledge . but it's difficlut to find the definite network structure in the code,  so, is there a cnn structure like the function,"model.summary()", result in tensorflow2? That will help me a lot!
thanks!

**Comment by MariaNattestad** [comment]
Hi @X1angyang 

The model is InceptionV3. You can see the layers of one of the DeepVariant models like this:
```
import tensorflow as tf

!gsutil cp gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model* /tmp/
checkpoint_path = '/tmp/model.ckpt'

reader = tf.compat.v1.train.NewCheckpointReader(checkpoint_path)
shape_map_for_layers = reader.get_variable_to_shape_map()
print(shape_map_for_layers)
```
I just tested that in Colab (https://colab.research.google.com/).

However, reimplementing all of DeepVariant from bam to output VCF would be a huge project. If you are interested in something smaller to get started, I'd like to bring this blog post to your attention: https://google.github.io/deepvariant/posts/2019-01-31-using-nucleus-and-tensorflow-for-dna-sequencing-error-correction/.
It has an associated Colab notebook that walks through some smaller but still challenging examples of how to use genomic data in machine learning using TensorFlow and Nucleus.

I hope that helps!
Maria

**Comment by X1angyang** [comment]
> Hi @X1angyang
> 
> The model is InceptionV3. You can see the layers of one of the DeepVariant models like this:
> 
> ```
> import tensorflow as tf
> 
> !gsutil cp gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model* /tmp/
> checkpoint_path = '/tmp/model.ckpt'
> 
> reader = tf.compat.v1.train.NewCheckpointReader(checkpoint_path)
> shape_map_for_layers = reader.get_variable_to_shape_map()
> print(shape_map_for_layers)
> ```
> 
> I just tested that in Colab (https://colab.research.google.com/).
> 
> However, reimplementing all of DeepVariant from bam to output VCF would be a huge project. If you are interested in something smaller to get started, I'd like to bring this blog post to your attention: https://google.github.io/deepvariant/posts/2019-01-31-using-nucleus-and-tensorflow-for-dna-sequencing-error-correction/.
> It has an associated Colab notebook that walks through some smaller but still challenging examples of how to use genomic data in machine learning using TensorFlow and Nucleus.
> 
> I hope that helps!
> Maria

Thanks!
