### ISSUE TITLE
Question about mapping quality

### ISSUE THREAD

**Issue by X1angyang** [google/deepvariant#331]
I read the paper published in 2018， there are 3 channeles in a image. The quality channel is combined base qualities and mapping quality. It is easy to understand that each base has a different pixel. But in the newest version, like shown in https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/, deepvariant  separates the old channel into 2 channels，base quality and mapping quality channel. We know that there is only one mapping quality for a read. But i found that there are different mapping qualities with different bases in a single read. How do you process the mapping quality into different quilities in a single read?
sorry for my poor english.

**Comment by MariaNattestad** [comment]
There should only be a single mapping quality for each read. Where did you see different mapping qualities for different bases in the same read?

**Comment by MariaNattestad** [comment]
I should also mention that DeepVariant has had 6 (or more) channels since the first open source release (v0.4). The type of image mentioned in the 2018 paper was only used in the very first version of DeepVariant before the software was rewritten for open-source.
