### ISSUE TITLE
Report version of Deepvariant

### ISSUE THREAD

**Issue by marchoeppner** [google/deepvariant#332]
**Describe the issue:**
I have been using DV via the official Docker container; and I have not found a way yet to make DV tell me its version. The Docker container is versioned, obviously, but the included tools have no "--version" flag - which makes it a bit tricky to dump out version information at run time (for logging purposes, for example). 

**Setup**
  Any system would have this issue, I think

**Steps to reproduce:**
  N/A

**Comment by pichuan** [comment]
Thank you @marchoeppner . We have added a version information to the VCF file to our internal codebase, and it'll come out in the next release.
After our next release, your VCF output will have a line that looks like this:
```
##DeepVariant_version=1.0.0
```

What you're requesting seems to be a commandline. If I understand correctly, is this something you're looking for:
```
docker run  google/deepvariant:"${BIN_VERSION}" --version
```
to output the current version?

I can see this being particularly helpful especially if you're trying to use google/deepvariant:latest. I can add that.

Thanks for the suggestion.

**Comment by pichuan** [comment]
I filed an issue internally to track. In our code release you should have both the version in VCF and the `--version` flag.
