### ISSUE TITLE
Document "exclude" list

### ISSUE THREAD

**Issue by marchoeppner** [google/deepvariant#333]
**Describe the issue:**
Apparently DeepVariant will not call variants on certain regions, irrespective of the "calling intervals" I pass it via BED file. 

First of all, I only found this out after googling it and coming across a closed issue. This seems like it is "important" information. I spent a fair amount of time trying to figure out why my calls were missing MT information...

Secondly, while I "get" that the results may not be highly reliable, MT variant calling is still useful (and commonly done) for some applications; so if I pass the Mitochondrion as a calling target, I would expect to get MT variant calls. This is a bit of an odd behavior, I think. 

Solutions: Clearly document this on github (sorry if I didn't see it, if it is already there). And maybe allow users to overwrite this through their BED file targets - maybe with a warning (unless MT variants are never trained so the algorithm is simply unable to call them). 

**Setup**
  Any

**Steps to reproduce:**
 N/A

**Comment by pichuan** [comment]
Hi @marchoeppner 
Thank you for reporting this. Currently, MT is excluded in this code:
https://github.com/google/deepvariant/blob/4b937f03a1336d1dc6fd4c0eef727e1f83d2152a/deepvariant/exclude_contigs.py

We actually got many requests that they want to be able to call MT. So, we have already made the internal change to remove MT and chrM from that `exclude_contigs.py` file already. In our next release, you'll be able to call MT by default!

For the current codebase, if you want to call it, you'll need to remove it from code and build your own binaries. Sorry that we don't have a flag for it.

**Comment by pichuan** [comment]
Hi @marchoeppner 
To give you an update, this file now doesn't have MT https://github.com/google/deepvariant/blob/r1.0/deepvariant/exclude_contigs.py, which means you should be able to call MT now with version 1.0.0.

It's removed in this commit: https://github.com/google/deepvariant/commit/7f4f2885059f7efebf83a098f187e32f87b0836a.
