### ISSUE TITLE
Op type not registered LegacyParallelInterleaveDatasetV2

### ISSUE THREAD

**Issue by jaydevshelat** [google/deepvariant#339]
**Describe the issue:**
I Build the docker image
Inside Docker image: I am reading the checkpoint files to create a frozen graph
When doing "import_meta_graph" I get the error. Below is the stack trace
`tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'LegacyParallelInterleaveDatasetV2' in binary running on bbfd0038f901. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`

**Setup**
  - Operating system: Ubuntu 18.04 on Intel i7 CPU (no GPU or TPU)
  - DeepVariant version: r-0.10
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:  
  - Error trace: 
`2020-08-26 18:04:05.695108: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "tf2_mipso_convert.py", line 35, in <module>
    saver = tf.compat.v1.train.import_meta_graph(meta_path)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'LegacyParallelInterleaveDatasetV2' in binary running on bbfd0038f901. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed`

**Does the quick start test work on your system?** 
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
Quick start works on my system -- I can perform make_examples, call_variants and post_processing

**Any additional context:**
(e.g. Tensorflow version, cuDNN version, NVIDIA Driver information from running `nvidia-smi`)

Code snippet :
`import tensorflow as tf

meta_path   = '/opt/models/wgs/model.ckpt.meta'

ckpt_folder = '/opt/models/wgs'

with tf.compat.v1.Session() as sess:

  saver = tf.compat.v1.train.import_meta_graph(meta_path)

  print("\n**Import Sucessful\n**")

  saver.restore(sess,tf.compat.v1.train.latest_checkpoint(ckpt_folder))
`

**Comment by MariaNattestad** [comment]
It looks like you are trying to analyze the graph outside of DeepVariant, which we don't currently have documentation on, since it isn't needed to run DeepVariant or even train it. But we do have some interpretability research we are working on, so stay tuned for that on the blog!

In the meantime, can you give a bit more context on what you are trying to do? Where did you find that code snippet?

**Comment by jaydevshelat** [comment]
Hi Maria,

Thanks for the response.  My Intent is to generate frozen graph from the available checkpoints.  The code snippet is my own.  Do you think it needs any fixing / addition? 

Is there anyone who can provide steps/methods/guidance?  I even tried Google Colab with different Hardware configurations -- i.e. combination of CPU, GPU, TPU.  And also with different TF versions.  I am never able to import the meta graph and restore the checkpoint.  I always get "No Op Kernel was registered" with different Op names

Additional question:  for training:

- Can I train on the "quickstart-testdata" provided in deepvariant? 
- And how do I produce a frozen graph during a training run?

**Comment by MariaNattestad** [comment]
Hi @jaydevshelat 

DeepVariant's checkpoints are based on InceptionV3 and use slim, see https://github.com/google-research/tf-slim.

I can share with you some code that @pichuan has written to read the checkpoints, but if you have any further questions on that, please consult the documentation for tensorflow or tf-slim.
```
! pip install tf-slim

import tensorflow.compat.v1 as tf
import os
import tf_slim as slim
from tf_slim.nets import inception_v3

!gsutil cp gs://deepvariant/models/DeepVariant/0.8.0/DeepVariant-inception_v3-0.8.0+data-wgs_standard/model* /tmp/
ckpt_file = '/tmp/model.ckpt'

graph = tf.Graph()

with graph.as_default():
  images = tf.placeholder(tf.float32, shape=(None, 100, 221, 6))

  with slim.arg_scope(inception_v3.inception_v3_arg_scope()):
    _, end_points = inception_v3.inception_v3(images, is_training=False, 
                                              num_classes=3,
                                              create_aux_logits=False)
    
    print("end_points:")
    print(end_points.keys())
    # Restore the checkpoint
    sess = tf.Session(graph=graph)
    saver = tf.train.Saver()
    saver.restore(sess, ckpt_file)
```

For training, you would need a lot more training data than the quickstart-testdata, as in multiple samples of WGS worth of sequencing data. For more information on training, see the documentation: https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-training-case-study.md.
