### ISSUE TITLE
Seeking Advice / Info :  rel 0.8 : build and run local

### ISSUE THREAD

**Issue by jaydevshelat** [google/deepvariant#340]
**Describe the issue:**
Hello,  I want to know what is an efficient way to build and run locally. My intent:  make a change in call_variant.py and observe the effect. 
Do I have to always build the docker? 
OR which shell scripts can I use to achieve my purpose?

**Setup**
  - Operating system:  Ubuntu 18.04 LTS
  - DeepVariant version: 0.8.0
  - Installation method:  build from source
  - Type of data: NA

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
(e.g. Tensorflow version, cuDNN version, NVIDIA Driver information from running `nvidia-smi`)

**Comment by sgoe1** [comment]
Hi @jaydevshelat, this [doc](https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-build-test.md) shows you how to build from source. Note that it mentions support for  Ubuntu 14 and 16, so you may need to make some changes in order for it to work on your OS. Feel free to followup if you hit any issues.
