### ISSUE TITLE
Version 0.8  run_examples giving error inside Docker

### ISSUE THREAD

**Issue by jaydevshelat** [google/deepvariant#342]
**Describe the issue:**

- I setup version 0.8.  ( I have to stick to TF1.x  )
- Modified the run-prereq.sh :  to install some dependencies before installing tensor2tensor
- Modified the setings.sh :  "DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=1.14"  (the 1.13.1 was giving errors)
- Followed [instruction ](https://github.com/google/deepvariant/blob/r0.8/docs/deepvariant-quick-start.md) to setup the INPUT_DIR & OUTPUT_DIR. 
- Then built the docker using "docker run ." 
- When inside docker, I run  :   

/opt/deepvariant/bin/make_examples --mode calling --ref "/INPUT/ucsc.hg19.chr20.unittest.fasta" --reads "/INPUT/NA12878_S1.chr20.10_10p1mb.bam" --examples "/OUTPUT/tmp0cv1ybnt/make_examples.tfrecord@8.gz" --gvcf "/OUTPUT/tmp0cv1ybnt/gvcf.tfrecord@8.gz" --regions "chr20:10,000,000-10,010,000"

But, I get error shown in stack trace section (below).

I can manually import tensorflow and print version on the terminal. 

Please help! 

**Setup**
  - Operating system: Ubuntu 18.04
  - DeepVariant version: 0.8
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace:
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_B0iKHl/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 42, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 17, in <module>
    from tensorflow.core.framework import function_pb2 as tensorflow_dot_core_dot_framework_dot_function__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/function_pb2.py", line 18, in <module>
    from tensorflow.core.framework import op_def_pb2 as tensorflow_dot_core_dot_framework_dot_op__def__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/op_def_pb2.py", line 210, in <module>
    serialized_options=None, file=DESCRIPTOR),
  File "/tmp/Bazel.runfiles_B0iKHl/runfiles/protobuf_archive/python/google/protobuf/descriptor.py", line 534, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field tensorflow.OpDef.control_output"

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
(e.g. Tensorflow version, cuDNN version, NVIDIA Driver information from running `nvidia-smi`)

**Comment by pichuan** [comment]
Hi @jaydevshelat 
Can you clarify - did you rebuild your docker image, or did you pull our 0.8 image?
You mentioned 

> Then built the docker using "docker run ."

Did you mean docker build?

If you're rebuilding your own, can you first confirm whether directly running our 0.8 image worked for you or not?

**Comment by pichuan** [comment]
Hi @jaydevshelat  if you want to follow up on this question, feel free to open it again. For now, I'll close this issue due to inactivity.

**Comment by Mipsology** [comment]
Apologies for no/late response.  And Thank You for following-up.  

My issue was :  the failure to do "docker build" after git clone of the repo.   

However, I am successful in getting the 0.8 docker image --> install the SW pre-reqs to recompile binaries inside docker --> export to new image for future use. 

This issue should be closed.

**Comment by pichuan** [comment]
@Mipsology Thanks for the update. I'll keep this issue closed.
