### ISSUE TITLE
deepvariant as a python package

### ISSUE THREAD

**Issue by JakeHagen** [google/deepvariant#344]
Hi,
I am trying to borrow some of the code from deepvariants, specifically importing realigner. What is the best way to do this?
Thank you

**Comment by pichuan** [comment]
Hi @JakeHagen 
Currently there isn't a very clean way to do this. You can modify the code and build DeepVariant from source: https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-build-test.md

I'm personally interested in learning more about what you're trying to do - what is the expected input and output. If there's general enough use cases, maybe in the future we can make things easier to import, even though we don't currently have plans for that.

**Comment by JakeHagen** [comment]
I am doing some work that needs read modification based on variants. These variants come from deepvariant so I was hoping to use the realigner to modify the reads as deepvariant sees them. I often struggle with python imports so I thought I was just missing something. I will look into extracting that code and building.
Thank you
