### ISSUE TITLE
CLR PacBio data

### ISSUE THREAD

**Issue by jdmontenegro** [google/deepvariant#347]
Hi team, 

I am very interested in using DeepVariant on my dataset to identify novel SNV and Indels from a diploid plant. However, I will probably need the ability to identify non-reference heterozygous SNVs (1/2 variants). is DeepVariant able to discover these variants, or does it need one of the variants to be the same as the ref?
Second, I read in the main page that you support Illumina, HiFi PacBio and ONT, but did not find any information on CLR PacBio, do you not support this kind of reads anymore?

Kind regards,

Juan D. Montenegro

**Comment by AndrewCarroll** [comment]
Hi @jdmontenegro 

For the question about multi-allelic heterozygous calls - yes, DeepVariant is able to all 1/2 events, and will represent these in one line as a GT 1/2 call in the VCF.

For CLR calling in DeepVariant. It is theoretically possible for us to make a model for DeepVariant that can call CLR data. However, this requires us to write a special candidate generation logic to deal with the higher error rate. Based on what we perceive for the direction of future use in the genomics community, we think that data generated will be increasingly HiFi, so we have not been able to highly prioritize CLR models. Feedback from users like yourself will be useful to us in evaluating if that prioritization makes sense. For now, I can't commit to a timeframe under which we would support a PacBio CLR model.

**Comment by jdmontenegro** [comment]
Dear Andrew,

Thank you for your quick reply. I agree with you that most sequencing and
resequencing projects will move towards HiFi reads rather than CLR reads.
However, there is a lot of CLR sequencing data that has been generated in
the past couple of years and continues to be produced currently and could
still be useful for groups without the means to resequence using the novel
HiFi reads. So, I definitely see a niche in a large part of the
bioinformatics community that do a lot of data reusing (nowadays data
parasites). So, if there is anything we can do to help you n development,
please feel free to let me know how we can collaborate.

Kind regards,

Juan D. Montenegro

**Comment by AndrewCarroll** [comment]
Hi @jdmontenegro 

I am going to close this issue for now. I will make a note to send you a message if/when we can revisit the CLR model. Thank you for your perspective on what data the community has and what will be valuable to them.

**Comment by starskyzheng** [comment]
Hi, @AndrewCarroll
  Any new about CLR PacBio reads? 
  Recently we meet a same situation to process published data which contains many CLR PacBio reads.
Thanks a low.
