### ISSUE TITLE
Is there potential for somatic variant calling?

### ISSUE THREAD

**Issue by ahgillmo** [google/deepvariant#351]
With the release of version 1.0.0, it is stated that DeepVariant will not support somatic variant calling because the only genotypes supported are hom-alt, het, and hom-ref. 

Is there the potential for a deep variant somatic variant caller in the future? 
or 
Could individuals produce somatic variants using a matched-normal approach? ie by calling variants on the germline and tumor(s) and extracting variants found in the tumor only?
Thank you for your time

**Comment by AndrewCarroll** [comment]
Hi @ahgillmo 

We do have a prototype implementation for somatic calling, which can take a tumor and normal BAM and call subclonal variants. However, we don't yet have enough confidence in the available truth sets, and that they come from a diverse enough sampling of cancers with mutational profiles, for us be certain in releasing something of high quality. 

We're watching developments in the area of these truth sets and hope to be able to further develop the somatic caller in the future.

**Comment by canna1998** [comment]
> Hi @ahgillmo
> 
> We do have a prototype implementation for somatic calling, which can take a tumor and normal BAM and call subclonal variants. However, we don't yet have enough confidence in the available truth sets, and that they come from a diverse enough sampling of cancers with mutational profiles, for us be certain in releasing something of high quality.
> 
> We're watching developments in the area of these truth sets and hope to be able to further develop the somatic caller in the future.

Where can I find the prototype and try it out?

**Comment by pichuan** [comment]
Hi @canna1998 , please reach out to Andrew at awcarroll@google.com and we can go from there.

**Comment by chilampoon** [comment]
Hi there, I also wanted to try the prototype and have reached out to Dr. Carroll :)

**Comment by forericksonetalsubmission1** [comment]
>We're watching developments in the area of these truth sets and hope to be able to further develop the somatic caller in the future.
Hi, I think I have a decent set of multi-tumor samples that would allow us to define ground truth sets for somatic clonal and somatic sub-clonal mutations, (and also pick up on potential noise from our inhouse variant caller). 
@AndrewCarroll, @pichuan - I would be interested in testing out a prototype version of your somatic caller, or perhaps collaborating to see how it performs.

**Comment by AndrewCarroll** [comment]
Hi @chilampoon and @forericksonetalsubmission1 

Thank you to both for your interest, and @forericksonetalsubmission1 this does seem like a valuable resource. Unfortunately, I'll have to defer an offer to help with somatic calling for at least awhile. We currently have too many active demands for near-term development work, and I have to preserve more bandwidth to make sure we can deliver well on those. I am sorry and hope we can revisit this question sometime in the future.

Thanks and apologies,
Andrew
