### ISSUE TITLE
Outdated Singularity Containers

### ISSUE THREAD

**Issue by DiDeoxy** [google/deepvariant#353]
Hi,

The singularity containers are on version 0.9.0, can these be updated to 1.0.0?

Cheers,

Max H.

**Comment by gunjanbaid** [comment]
Hi @DiDeoxy, here are [our instructions](https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md#notes-on-singularity) for running DeepVariant 1.0.0 with Singularity. Specifically, the below commands should get you the 1.0.0 image. 

```
BIN_VERSION="1.0.0"
singularity pull docker://google/deepvariant:"${BIN_VERSION}"
```

Where are you seeing the singularity containers at 0.9.0? If you could share a link or paste the commands used, I'll look into that. Thanks!

**Comment by DiDeoxy** [comment]
Hey,

Thanks, I did that yesterday and got it working. 

I was finding the 0.9.0 singularity imagers at: https://console.cloud.google.com/storage/browser/deepvariant/singularity_images?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false

Cheers,

Max H.

**Comment by gunjanbaid** [comment]
@DiDeoxy glad to hear you were able to get it working, and thanks for the pointer! We will plan remove the `gs://deepvariant/singularity_images` folder to make things less confusing. The recommended approach is the set of commands mentioned earlier:

```
BIN_VERSION="1.0.0"
singularity pull docker://google/deepvariant:"${BIN_VERSION}"
```

I'll close this issue now, but feel free to reopen if you have any other questions.

**Comment by pichuan** [comment]
Thanks for reporting this. 
I removed the gs://deepvariant/singularity_images directory to avoid future confusion.
