### ISSUE TITLE
Build from source: issue with java

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#355]
Hi, I am trying to build DeepVariant from source, and I encounter the following issue in build_and_test. I have bazel 0.26.1 compiled from source as well.

```
(16:39:00) ERROR: Analysis of target '//deepvariant:make_examples_utils_test' failed; build aborted: 

/root/.cache/bazel/_bazel_root/8422bf851bfac3671a35809acde131a7/external/bazel_tools/tools/jdk/BUILD:487:14: Configurable attribute "actual" doesn't match this configuration: Could not find a JDK for host execution environment, please explicitly provide one using `--host_javabase.`
```
I tried passing the argument "--host_javabase=@local_jdk//:jdk" to bazel to no avail.

Java:
```
# java -version
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)
```

**Comment by gunjanbaid** [comment]
Hi @anands-repo, can you share more details on the following?

- Operating system
- DeepVariant version - I'm assuming you are building 1.0.0 from source, but please let me know if it's a different version
- Command used to build
- Error trace after passing `--host_javabase=@local_jdk//:jdk`

**Comment by anands-repo** [comment]
Hi @gunjanbaid I do not see the same issue now. I switched to openjdk-11. However, I still need to pass the --host_javabase option, which is not present by default in the build scripts.

I do see another issue. The trace is as follows
```
(02:26:24) ERROR: /root/deepvariant/third_party/nucleus/protos/BUILD:413:1: ClifProtoLibraryGeneration third_party/nucleus/protos/bedgraph_pyclif.h failed (Exit 1): proto failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/8422bf851bfac3671a35809acde131a7/execroot/com_google_deepvariant && \
  exec env - \
  bazel-out/host/bin/external/clif/proto -c bazel-out/ppc-opt/bin/third_party/nucleus/protos/bedgraph_pyclif.cc -h bazel-out/ppc-opt/bin/third_party/nucleus/protos/bedgraph_pyclif.h '--strip_dir=bazel-out/ppc-opt/bin' '--source_dir='\''.'\''' third_party/nucleus/protos/bedgraph.proto)

Execution platform: @bazel_tools//platforms:host_platform               
Traceback (most recent call last):                                       
  File "bazel-out/host/bin/external/clif/proto", line 5, in <module>
    from clif.python.proto import start                           
  File "/root/opt/clif/lib64/python3.6/site-packages/clif/python/proto.py", line 29, in <module>
    from clif.python.utils import proto_util            
ImportError: libprotobuf.so.24: cannot open shared object file: No such file or directory

```

This is for the following command from build_and_test.sh:
```
bazel test --host_javabase=@local_jdk//:jdk -c opt --local_test_jobs=1 ${DV_COPT_FLAGS} "$@" \
    deepvariant/...
```

Why is bazel running ```exec env -``` here? This is invalidating library paths (LD_LIBRARY_PATH variable) where it would find ```libprotobuf.so```. As expected, when I run the failing command from the trace without ```exec env -```, it is fine.

**Comment by anands-repo** [comment]
Installing everything to standard path or updating ldconf solves the issue. I still do not have the whole build working, because bazel is looking for standard python libraries (which is not what I am using) to be used. Overall it seems the installation expects everything to be in standard paths which I believe is a little too stringent, and it may be possible to fix that without too much trouble may be.

But my original issues are no longer issues, so closing this ...
