### ISSUE TITLE
Working with non human data

### ISSUE THREAD

**Issue by leorippel** [google/deepvariant#357]
Hi,

I have a big load of data to genotype and I did some tests using subsets of my data. My question is if will work use DV default parameter to a Plant genome.

I have no gold set for training model. There is any suggestions?

Cheers.

**Comment by gunjanbaid** [comment]
Hi @leorippel, DeepVariant has previously been applied to plant species. In the case of rice, there was good evidence of high accuracy. You can see [some results in this blog post](https://cloud.google.com/blog/products/data-analytics/analyzing-3024-rice-genomes-characterized-by-deepvariant). However, these rice genomes were diploid and with a similar variant density of humans.

DeepVariant is currently written to be a diploid variant caller. So if the plant species you are working with is polyploid, it is not yet clear how DeepVariant will perform. That said, I am also not sure how other variant callers perform on polyploid samples.

It would be possible to train DeepVariant models for a specific genome, but this would require a gold set for the training. We have a previous example of this in mosquitos [in this blog post](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/).

**Comment by leorippel** [comment]
Hi!

I read both of blog posts, and I could see that even the  primary goal is working with human data, DV is very robust. My specie is diploid, so Iguess it helps, and the variant density should no be too  different from humam or rice. 

I Actually have two datasets; one is the megagametophyte (1n) of the same individuals (2n). Unfortunatelly, at this point, I don't have a gold dataset to train the data. I'm trying to get at least a truth set to help me in this quest. 


Thanks for enlightening

**Comment by gunjanbaid** [comment]
@leorippel since your data is diploid and of similar variant density to human data, you could try applying the released DeepVariant models. That said, we can't be sure how well the models will perform on this data. I'll close this issue for now, but feel free to reopen if you have any other questions. Thanks!
