### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [google/deepvariant#36]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like deepvariant, deleted the software history during the transition to open-source.

https://github.com/google/deepvariant/commit/8b84eabcc3c7b1adff3dfa6951963527eb673c29

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask deepvariant developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by depristo** [comment]
> Why did you decide to not keep the software history?

DeepVariant was originally developed within Google, using our internal systems. The original paths, content, etc from the earliest commits may contain information we cannot share, so upon releasing DeepVariant we squashed the history.

> Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
> How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?
> Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?

No, because our history is complete within Google.

**Comment by gustavopinto** [comment]
Hi @depristo, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
