### ISSUE TITLE
Is there still no way to limit the cpu usage?

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#361]
Hello,

whatever the number of shards, DeepVariant invariably ends up taking the whole 48 threads on our machine. Is there a fix or a planned fix for that?

**Comment by pichuan** [comment]
Hi @aderzelle ,
I was planning to look into this today and reply. I think it is possible that there are some options in tensorflow. 
I noticed that you just closed this issue. If you already found an answer, can you reply here for future reference? Thank you!

**Comment by aderzelle** [comment]
Hi @pichuan 

oh no I haven't found a way ... I closed because rereading my phrasing I was afraid it sounded like a non-constructive complain. 
Difficult for me to express it in English ... basically I was afraid opening this issue the way I did was not polite. 

(but yes, it would be a cool option)

**Comment by pichuan** [comment]
No problem :) let me take a look today and get back to you.

**Comment by pichuan** [comment]
Hi @aderzelle ,
I think you can use the TensorFlow config string to constraint the CPU use of the call_variants step.

For example, this discussion talked about how to run TF on one core:
https://medium.com/@liyin2015/tensorflow-cpus-and-gpus-configuration-9c223436d4ef

If you're running call_variants directly, you can add a flag like `--config_string "device_count {key: 'cpu' value: 1} intra_op_parallelism_threads:1 inter_op_parallelism_threads:1"`
For example:

```
sudo docker run   -v "${INPUT_DIR}":"/input"   -v "${OUTPUT_DIR}":"/output" \
google/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/call_variants \
--outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" \
--examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" \
--checkpoint "/opt/models/wgs/model.ckpt" \
--config_string "device_count {key: 'cpu' value: 1} intra_op_parallelism_threads:1 inter_op_parallelism_threads:1"
```

With this extra arg, I do see that:
```
I1015 19:57:25.812590 140110048159488 estimator.py:212] Using config: {'_model_dir': '/tmp/tmpt8af___k', '_tf_random_seed': None, '_save_summary_steps': 10
0, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': device_count {
  key: "cpu" 
  value: 1
}
intra_op_parallelism_threads: 1
inter_op_parallelism_threads: 1
```
But I'm not 100% sure that TensorFlow actually fully follow the instructions here or not.

If you're using the one-step script (`run_deepvariant`), you can add:
`--call_variants_extra_args= --config_string "device_count {key: 'cpu' value: 1} intra_op_parallelism_threads:1 inter_op_parallelism_threads:1"`

**Comment by pichuan** [comment]
@aderzelle Now I'll actually close this issue. 
If you try it out, let me know whether it worked or not. Thanks!

**Comment by pichuan** [comment]
Hi @aderzelle ,
Another approach is to use `docker run --cpus=$THREADS` to constrain the number of CPUs.
Hopefully this approach should work even if the previous one didn't.
