### ISSUE TITLE
error running help command

### ISSUE THREAD

**Issue by loipf** [google/deepvariant#362]
I downloaded your docker ( `docker pull google/deepvariant:1.0.0` ) and it runs perfectly and I am really happy with it.

However, I wanted to check out some options, so I run your readme command:
`docker run google/deepvariant:1.0.0 --help`
which lead to following error:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"--help\": executable file not found in $PATH": unknown.
ERRO[0000] error waiting for container: context canceled
```
should I change the command or is it an error with the image ? 

do not worry it is not urgent, but I would be really keen on checking out more options.
thank you !

**Comment by pichuan** [comment]
Hi @loipf , 
You can use `--help` with the different binaries, for example:

```
docker run google/deepvariant:1.0.0 /opt/deepvariant/bin/run_deepvariant --help
```

To see the various binaries, you can use:
```
docker run google/deepvariant:1.0.0 ls /opt/deepvariant/bin/
```
to list all the binaries.

Then, for example, you can run:

```
docker run google/deepvariant:1.0.0 /opt/deepvariant/bin/show_examples --help
```

or any other binaries.

I understand your point though. It might be easier if we have a more clear help page without knowing the structure. I'll think about this and see if we can improve in the future.

**Comment by pichuan** [comment]
Hi @loipf 
I've made changes in internal code. It'll come out in the next release.
After the next release, feel free to let us know if have more feedback.

**Comment by loipf** [comment]
very nice! makes it a lot easier for new people and well documented

**Comment by pichuan** [comment]
Thanks @loipf for your helpful suggestion :)
