### ISSUE TITLE
Where is deepvariant_pb2

### ISSUE THREAD

**Issue by xuxif** [google/deepvariant#368]
When I go through the make_example.py I can not find where is the deepvariant_pb2 ?

**Comment by akolesnikov** [comment]
deepvariant_pb2 is a generated file. You need to build make_examples in order for this file to be generated.

**Comment by pichuan** [comment]
Hi @xuxif ,
Adding on to @akolesnikov 's answer, you can find the original proto definition here:
https://github.com/google/deepvariant/blob/r1.0/deepvariant/protos/deepvariant.proto

**Comment by gunjanbaid** [comment]
Marking this as resolved, but feel free to reopen if you have other questions @xuxif.
