### ISSUE TITLE
Question on Haplotag sorting for PacBio and Hybrid data

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#369]
My understanding is that DeepVariant requires two steps to call variants for PacBio data. First step is to call variants directly on the BAM files and haplotag the BAM file with this first order call set, and the second step is to call variants on the haplotagged BAM files. Based on this, I have a few questions on how data is prepared for training.

1. For PacBio v1.0 training data, are haplotagged bams prepared based on v0.10 DeepVariant variant calls?
2. Are both haplotagged and non-haplotagged BAM files passed to DeepVariant to prepare two different sets of training data? Or can Deepvariant (make_examples) prepare two types of training data (haplotag sorted and unsorted images) based on a the same haplotagged BAM input?
3. For Hybrid variant calling, are pacbio reads haplotagged based on v0.10 DeepVariant? If the BAM preparation steps are shown that would be great.
4. How is training data prepared for hybrid - does it also have both haplotag sorted and unsorted images, and is this taken care-of by make_examples, or is this manually accomplished?
5. What are the genomes used to train the hybrid model (e.g., is it all of HG001-HG007)?

Thanks!

**Comment by akolesnikov** [comment]
Hi,

Below are the answer for the first 3 questions. The rest will be answered later.
1. Yes.
2. I'm not sure I fully understand the question. But, DeepVariant is trained on a mix of sorted and unsorted data. You may run DeepVariant make_examples with either hap-sorted or unsorted BAMs. There are 2 flags that need to be set in order for DeepVariant to take advantage of hap-sorted data. 
3. Yes. If you haven't already you may check the case study for PacBio data [here](https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-pacbio-model-case-study.md). In that tutorial the process of preparing hap-sorted BAM files is explained.
4,5. Will be answered later...

**Comment by anands-repo** [comment]
Hi @akolesnikov , thanks for the responses. A follow-up - if a model is not intended to be used for generating the haplotagging VCF, but only intended for the final variant call, then is it acceptable to train using only haplotagged images?

**Comment by gunjanbaid** [comment]
@anands-repo if you wish to only train with HP sorted images, that is a reasonable design decision. In our case, we could have trained two models, one model only with HP sorted images, the other model without sorting by HP. Based on empirical evidence, we find that mixing the training data and training one model was reasonable. That also allowed us to distribute one model, rather than two separate ones.

4. PacBio training data for the hybrid model contains training examples with HP sorted images and unsorted images. Sorting by HP is done in make_examples.
5. The genomes used include HG002, HG004-HG007.

**Comment by anands-repo** [comment]
Thanks for the explanations @gunjanbaid . It makes sense to have a single model for PacBio for both haplotagging and variant calling. I will close the issue for now.
