### ISSUE TITLE
ValueError: The middle base of reference sequence in the window (A at base 110) doesn't match first character of variant.reference_bases (T).

### ISSUE THREAD

**Issue by MorganHow** [google/deepvariant#372]
I've never encountered this error previously and I cannot figure out what is causing the issue. Looks like something to do with the reference file?

user@node1784:~/MyData$ /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=./hg19.fa --reads=./NA12878_S1.bam --output_vcf=./NA12878_DeepVariant_output.vcf.gz --num_shards=1 
I1027 14:35:49.384760 139774463268608 run_deepvariant.py:273] Re-using the directory for intermediate results in /tmp/tmps6oyff7s

***** Intermediate results will be written to /tmp/tmps6oyff7s in docker. ****

***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "./hg19.fa" --reads "./NA12878_S1.bam" --examples "/tmp/tmps6oyff7s/make_examples.tfrecord@1.gz" --task {}

Academic tradition requires you to cite works you base your article on.
When using programs that use GNU Parallel to process data for publication
please cite:

  O. Tange (2011): GNU Parallel - The Command-Line Power Tool,
  ;login: The USENIX Magazine, February 2011:42-47.

This helps funding further development; AND IT WON'T COST YOU A CENT.
If you pay 10000 EUR you should feel free to use GNU Parallel without citing.

To silence this citation notice: run 'parallel --citation'.

I1027 14:35:51.541710 140702132172544 genomics_reader.py:223] Reading ./NA12878_S1.bam with NativeSamReader
I1027 14:35:51.552782 140702132172544 make_examples.py:587] Preparing inputs
I1027 14:35:51.576705 140702132172544 genomics_reader.py:223] Reading ./NA12878_S1.bam with NativeSamReader
I1027 14:35:51.590540 140702132172544 make_examples.py:587] Common contigs are ['chrM', 'chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY']
I1027 14:35:56.576697 140702132172544 make_examples.py:587] Writing examples to /tmp/tmps6oyff7s/make_examples.tfrecord-00000-of-00001.gz
I1027 14:35:56.577845 140702132172544 make_examples.py:587] Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2020-10-27 14:35:56.578184: I third_party/nucleus/io/sam_reader.cc:662] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1027 14:35:56.653103 140702132172544 genomics_reader.py:223] Reading ./NA12878_S1.bam with NativeSamReader
I1027 14:35:56.683220 140702132172544 genomics_reader.py:223] Reading ./NA12878_S1.bam with NativeSamReader
W1027 14:35:58.065773 140702132172544 make_examples.py:1773] Could not create PileupImage for candidate at chrM:72
I1027 14:35:58.091689 140702132172544 make_examples.py:587] 6 candidates (5 examples) [1.51s elapsed]
W1027 14:36:44.979548 140702132172544 make_examples.py:1773] Could not create PileupImage for candidate at chrM:16520
I1027 14:36:47.744649 140702132172544 make_examples.py:587] 472 candidates (516 examples) [49.65s elapsed]
I1027 14:36:48.139883 140702132172544 make_examples.py:587] 690 candidates (734 examples) [0.39s elapsed]
I1027 14:36:49.490540 140702132172544 make_examples.py:587] 1365 candidates (1411 examples) [1.35s elapsed]
I1027 14:36:49.878772 140702132172544 make_examples.py:587] 1568 candidates (1614 examples) [0.39s elapsed]
I1027 14:36:51.591806 140702132172544 make_examples.py:587] 2288 candidates (2336 examples) [1.71s elapsed]
I1027 14:36:54.569629 140702132172544 make_examples.py:587] 3057 candidates (3119 examples) [2.98s elapsed]
I1027 14:36:56.450915 140702132172544 make_examples.py:587] 3726 candidates (3792 examples) [1.88s elapsed]
I1027 14:36:56.585570 140702132172544 make_examples.py:587] 3818 candidates (3884 examples) [0.13s elapsed]
I1027 14:36:57.334101 140702132172544 make_examples.py:587] 4278 candidates (4348 examples) [0.75s elapsed]
I1027 14:36:58.220093 140702132172544 make_examples.py:587] 4705 candidates (4781 examples) [0.89s elapsed]
I1027 14:36:58.647889 140702132172544 make_examples.py:587] 4902 candidates (4978 examples) [0.43s elapsed]
I1027 14:36:58.910644 140702132172544 make_examples.py:587] 5045 candidates (5121 examples) [0.26s elapsed]
I1027 14:36:59.095998 140702132172544 make_examples.py:587] 5155 candidates (5231 examples) [0.19s elapsed]
I1027 14:36:59.252589 140702132172544 make_examples.py:587] 5214 candidates (5292 examples) [0.16s elapsed]
I1027 14:37:00.007773 140702132172544 make_examples.py:587] 5708 candidates (5788 examples) [0.75s elapsed]
I1027 14:37:00.259803 140702132172544 make_examples.py:587] 5867 candidates (5947 examples) [0.25s elapsed]
I1027 14:37:00.531860 140702132172544 make_examples.py:587] 6073 candidates (6153 examples) [0.27s elapsed]
I1027 14:37:00.821030 140702132172544 make_examples.py:587] 6229 candidates (6309 examples) [0.29s elapsed]
I1027 14:37:02.440546 140702132172544 make_examples.py:587] 6906 candidates (6998 examples) [1.62s elapsed]
I1027 14:37:03.863318 140702132172544 make_examples.py:587] 7632 candidates (7726 examples) [1.42s elapsed]
I1027 14:37:05.586354 140702132172544 make_examples.py:587] 8367 candidates (8461 examples) [1.72s elapsed]
I1027 14:37:07.514431 140702132172544 make_examples.py:587] 9099 candidates (9197 examples) [1.93s elapsed]
I1027 14:37:09.049840 140702132172544 make_examples.py:587] 9819 candidates (9919 examples) [1.54s elapsed]
I1027 14:37:09.783628 140702132172544 make_examples.py:587] 10300 candidates (10400 examples) [0.73s elapsed]
I1027 14:37:10.211517 140702132172544 make_examples.py:587] 10544 candidates (10644 examples) [0.43s elapsed]
I1027 14:37:11.778766 140702132172544 make_examples.py:587] 11247 candidates (11359 examples) [1.57s elapsed]
I1027 14:37:13.667338 140702132172544 make_examples.py:587] 11967 candidates (12083 examples) [1.89s elapsed]
I1027 14:37:13.906970 140702132172544 make_examples.py:587] 12077 candidates (12193 examples) [0.24s elapsed]
I1027 14:37:15.383114 140702132172544 make_examples.py:587] 12826 candidates (12948 examples) [1.48s elapsed]
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2136, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2126, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2003, in make_examples_runner
    candidates, examples, gvcfs = region_processor.process(region)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1503, in process
    example for candidate in candidates
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1504, in <listcomp>
    for example in self.create_pileup_examples(candidate)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1768, in create_pileup_examples
    haplotype_sequences=haplotype_sequences)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 507, in create_pileup_images
    pileup = _pileup_for_pair_of_alts(alts)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 467, in _pileup_for_pair_of_alts
    alt_alleles=alt_alleles)
  File "/tmp/Bazel.runfiles_e62sjnjy/runfiles/com_google_deepvariant/deepvariant/pileup_image.py", line 345, in build_pileup
    dv_call.variant.reference_bases))
ValueError: The middle base of reference sequence in the window (A at base 110) doesn't match first character of variant.reference_bases (T).
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref ./hg19.fa --reads ./NA12878_S1.bam --examples /tmp/tmps6oyff7s/make_examples.tfrecord@1.gz --task 0

real	1m26.899s
user	1m25.200s
sys	0m1.679s
I1027 14:37:16.286230 139774463268608 run_deepvariant.py:364] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 369, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 362, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "./hg19.fa" --reads "./NA12878_S1.bam" --examples "/tmp/tmps6oyff7s/make_examples.tfrecord@1.gz" --task {}' returned non-zero exit status 1.

**Comment by gunjanbaid** [comment]
@MorganHow does your reference match the BAM file you are using? From looking at this error message, my first thought is that your BAM file is mapped to a different reference.

**Comment by MorganHow** [comment]
I believe that was the issue due to some poor naming on my end. Thanks again
