### ISSUE TITLE
Make_Example fail because of bed.file content

### ISSUE THREAD

**Issue by YanJiunLiu** [google/deepvariant#374]
**Describe the issue:**
Make_Example fail because of bed.file

**Setup**
  - Operating system:ubuntu18.04
  - DeepVariant version:v1.0.0
  - Installation method (Docker, built from source, etc.):Docker
  - Type of data: same as case study

**Steps to reproduce:**
  - Command:
      /usr/local/seqslab/deepvariant/bazel-bin/deepvariant/make_examples \
     --mode calling \
     --ref /opt/command/test_dir/ref.fa \
     --reads /opt/command/test_dir/0-0.bam \
    --regions /opt/command/test_dir/part_0.bed \
    --examples /opt/command/test_dir/expl_tfrecord \
    --gvcf /opt/command/test_dir/gvcf_tfrecord 
  - Error trace: (if applicable)
[E::idx_find_and_load] Could not retrieve index file for '/opt/command/test_dir/0-0.bam'
I1028 05:56:59.842471 139811846457152 genomics_reader.py:223] Reading /opt/command/test_dir/0-0.bam with NativeSamReader
I1028 05:56:59.844546 139811846457152 make_examples.py:587] Preparing inputs
[E::idx_find_and_load] Could not retrieve index file for '/opt/command/test_dir/0-0.bam'
I1028 05:56:59.845231 139811846457152 genomics_reader.py:223] Reading /opt/command/test_dir/0-0.bam with NativeSamReader
I1028 05:56:59.854553 139811846457152 make_examples.py:587] Common contigs are ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y', 'MT']
[E::hts_hopen] Failed to open file /opt/command/test_dir/part_0.bed
[E::hts_open_format] Failed to open file "/opt/command/test_dir/part_0.bed" : Exec format error
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2136, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 2126, in main
    make_examples_runner(options)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1984, in make_examples_runner
    regions = processing_regions_from_options(options)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1879, in processing_regions_from_options
    options.exclude_calling_regions)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 1065, in build_calling_regions
    ranges.RangeSet.from_regions(regions_to_include, contig_dict))
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 161, in from_regions
    return cls(ranges=from_regions(regions, contig_map=contig_map))
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 113, in __init__
    for i, range_ in enumerate(ranges):
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 493, in from_regions
    for elt in reader(region):
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/util/ranges.py", line 458, in bed_parser
    with bed.BedReader(filename) as fin:
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 221, in __init__
    self._reader = self._native_reader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 127, in _native_reader
    return NativeBedReader(input_path, **kwargs)
  File "/tmp/Bazel.runfiles_qccapoh4/runfiles/com_google_deepvariant/third_party/nucleus/io/bed.py", line 104, in __init__
    self._reader = bed_reader.BedReader.from_file(bed_path, options)
ValueError: Not found: Could not open /opt/command/test_dir/part_0.bed
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
My part_0.bed has 5 columns and goes error
chrm  start       end     name   (option)
   1        0       1005000   0         5000
But when I change my part_0.bed to 4 columns , it works
chrm  start       end     name   
   1        0       1005000   0

**Comment by gunjanbaid** [comment]
@YanJiunLiu you may want to check that the BED file is correctly formatted with the extra column. For example, does `bcftools view part_0.bed` work without issues when you have 5 columns? I'll post an update if I think of any other reasons this error could be happening.

**Comment by gunjanbaid** [comment]
@YanJiunLiu could you attach a small snippet of the BED file that is not working for you? Perhaps there is some formatting issue.

**Comment by YanJiunLiu** [comment]
> @YanJiunLiu could you attach a small snippet of the BED file that is not working for you? Perhaps there is some formatting issue.
This is the bed file that execute make example fail
![Uploading 截圖 2020-10-29 上午11.12.18.png…]()

**Comment by YanJiunLiu** [comment]
This is the bed file that execute make example fail 
<img width="672" alt="截圖 2020-10-29 上午11 12 18" src="https://user-images.githubusercontent.com/63279862/97521250-23409f00-19d8-11eb-8489-f0d0968d872d.png">

**Comment by YanJiunLiu** [comment]
Ｗhen I delete the “5000” , it works
<img width="672" alt="截圖 2020-10-29 上午11 24 34" src="https://user-images.githubusercontent.com/63279862/97521833-5afc1680-19d9-11eb-8427-0c2b1abb7316.png">

**Comment by pichuan** [comment]
I'll plan to take a look but might be later this week. Thanks.

**Comment by pichuan** [comment]
My current investigation shows that this went down the path here:
https://github.com/samtools/htslib/blob/1.10.2/hts.c#L460-L463

which ended up identify this file as an FAI format.

And then this format gets into this switch:
https://github.com/samtools/htslib/blob/1.10.2/hts.c#L1069-L1105
But FAI format doesn't get read here, so it got into the last branch of the switch:
```
    default:
        errno = EFTYPE;
        goto error;
```

One potential solution here is that we can change the Nucleus BedReader to always read file as BED (and not using htslib's format detection). This could cause other issues (for example, unable to read bed.gz. (Although, I personally have not tried using bed.gz files yet)

Another potential solution : maybe newer version of htslib would work. I have not tried that either.

For now, please preprocess the file and remove the last column. I'll discuss with teammates to see if it makes sense to change the BedReader implementation in Nucleus for this.

Thank you for reporting the issue!

**Comment by pichuan** [comment]
One thing I will propose to do is at least to update the Nucleus message to say something more than just "Not found", so that even it fails, the error message will be more uderstandable.
