### ISSUE TITLE
HG002-HG003-HG004 trio deepvariant and de novo mutation calling

### ISSUE THREAD

**Issue by sjin09** [google/deepvariant#377]
**_Describe the issue:_**
I was wondering if the authors have recommended method for generating a set of high-confidence de novo germline mutations from trio-deepvariant vcf files.

I have used DeepVariant 0.9.0 version for calling the germline mutations and I have merged HG002, HG003 and HG004 .g.vcf.gz files using GLnexus. If there isn't a recommendation calling de novo germline mutations from trio-deepvariant vcf files, I am hoping to implement the method described in DeNovoGear: de novo indel and point mutation discovery and phasing.

_**Miscellaneous**_
- I was hoping to use GATK GenotypeGVCFs for merging the HG002, HG003 and HG004 .g.vcf.gz files, but deepvariant .g.vcf.gz file is not compatible with GATK GenotypeGVCFs. 
- I was hoping to use the HG002-HG003-HG004 trio vcf file as input towards strelka2 de novo mutation caller, but the vcf file was again not compatible.

**_Setup_**

Operating system: Ubuntu
DeepVariant version: 0.9.0
Installation method (Docker, built from source, etc.): Docker
Type of data: sample: HG002, HG003 and HG004 PacBio CCS fastq

**_Steps to reproduce:_**

**_Any additional context:_**

Regards,
Sangjin

**Comment by AndrewCarroll** [comment]
Hi @sjin09 

Thank you for your question. We are actively working on a solution for this area (trio calling) and expect to have something in the timeframe of a few months from now. For now, the most accurate way to identify de novos with DeepVariant is to run DeepVariant v1.0, use GLnexus to merge the inputs, and identify de novo variants from the joint call file.

Thank you,
Andrew

**Comment by sjin09** [comment]
Hello @AndrewCarroll 

We look forward to the development. We will create a custom de novo mutation caller for now.

Many thanks,
Sangjin

**Comment by samkleeman1** [comment]
Any updates regarding this?

**Comment by MariaNattestad** [comment]
Yes! DeepTrio was launched as part of DeepVariant 1.1: https://github.com/google/deepvariant/blob/r1.1/docs/deeptrio-details.md
