### ISSUE TITLE
Training: How to reevaluate all checkpoints?

### ISSUE THREAD

**Issue by anands-repo** [google/deepvariant#378]
I launched a training run, but the evaluation run wasn't launched concurrently. When I launch it, it simply evaluates the final checkpoint, not all the checkpoints in between. Is there an option force evaluation of all checkpoints in model_eval?

**Comment by pichuan** [comment]
There isn't an option right now but it should be possible to make changes to the code to do this. Unfortunately this is not a highly prioritized feature (even internally), so we won't plan to implement it anytime soon. If you end up implementing it, let us know! Thank you.

**Comment by anands-repo** [comment]
Hi @pichuan 

Here is a helper shell script for that: https://raw.githubusercontent.com/anands-repo/deepvariant/r1.0/tools/post_eval.sh

Steps to use:
1. Create a target empty working directory: $WORKDIR
2. Launch model_eval with checkpoint directory = $WORKDIR, and direct output logs to $WORKDIR/eval.log
3. Launch post_eval.sh as: post_eval.sh $TRAINING_DIRECTORY $WORKDIR

The post_eval script copies one checkpoint after another to $WORKDIR from $TRAINING_DIRECTORY (original directory where checkpoints were dumped by model_train), in coordination with model_eval.
