### ISSUE TITLE
CRAM file support?

### ISSUE THREAD

**Issue by jjfarrell** [google/deepvariant#38]
Does the deepvariant software also read cram files?

**Comment by depristo** [comment]
We are 80% of the way there on CRAM support. Under the hood DeepVariant uses htslib to read it's reads datasets, which supports cram. But we need to extend the IO systems to pass in the reference genome to read a CRAM file, and that's not possible right now. We are hopeful that the community would extend DeepVariant to handle CRAM files, so please feel free to contribute a pull request with the functionality if you decide to add it.

**Comment by jjfarrell** [comment]
Samtools use this approach to pass the reference needed for reading  the cram file. Pysam uses a similar approach. 

**The REF_PATH and REF_CACHE**
One of the key concepts in CRAM is that it is uses reference based compression. This means that Samtools needs the reference genome sequence in order to decode a CRAM file. Samtools uses the MD5 sum of the each reference sequence as the key to link a CRAM file to the reference genome used to generate it. By default Samtools checks the reference MD5 sums (@SQ “M5” auxiliary tag) in the directory pointed to by $REF_PATH environment variable (if it exists), falling back to querying the European Bioinformatics Institute (EBI) reference genome server, and further falling back to the @SQ “UR” field if these are not found.

While the EBI have an MD5 reference server for downloading reference sequences over http, we recommend use of a local MD5 cache. We have provided with Samtools a basic script (misc/seq_cache_populate.pl) to convert your local yeast.fasta to a directory tree of reference sequence MD5 sums:

<samtools_src_dir>/misc/seq_cache_populate.pl -root /some_dir/cache yeast.fasta
export REF_PATH=/some_dir/cache/%2s/%2s/%s:http://www.ebi.ac.uk/ena/cram/md5/%s
export REF_CACHE=/some_dir/cache/%2s/%2s/%s
REF_PATH is a colon separated list of directories in which to search for files named after the sequence M5 field. The : in http:// is not considered to be a separator. Hence using the above setting, any CRAM files that are not cached locally may still be looked up remotely.

In this example “%2s/%2s/%s” means the first two digits of the M5 field followed by slash, the next two digits and slash, and then the remaining 28 digits. This helps to avoid one large directory with thousands of files in it.

The REF_CACHE environment variable is used to indicate that any downloaded reference sequences should be stored locally in this directory in order to avoid subsequent downloads. This should normally be set to the same location as the first directory in REF_PATH.
