### ISSUE TITLE
Cannot build on Centos 7 due to CLIF dependency 

### ISSUE THREAD

**Issue by narendrachaudhary51** [google/deepvariant#380]
**Describe the issue:**

I am trying to build deepvariant on my machine that has Centos 7 and it seems there are no instructions to do that. All the instructions are based on Ubuntu operation system. I install all the dependencies but it seems there is no version of CLIF for Centos 7. So I tried building CLIF on my machine using clang/llvm 11.0.0. I get the following error during installation of that. Is it possible to have instruction for building deepvariant on Centos 7. 

CLIF building error - I get the following error during installation using ./INSTALL.sh. 

Scanning dependencies of target clif-matcher
[100%] Building CXX object clif/backend/CMakeFiles/clif-matcher.dir/matcher_main.cc.o
[100%] Linking CXX executable clif-matcher
CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE[_ZTIN4llvm2cl4listINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbNS0_6parserIS7_EEEE]+0x18): undefined reference to typeinfo for llvm::cl::Option' CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyIbEE[_ZTIN4llvm2cl15OptionValueCopyIbEE]+0x10): undefined reference to typeinfo for llvm:🆑:GenericOptionValue'
CMakeFiles/clif-matcher.dir/matcher_main.cc.o:(.data.rel.ro._ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE[_ZTIN4llvm2cl15OptionValueCopyINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEE]+0x10): undefined reference to typeinfo for llvm::cl::GenericOptionValue' libclifMatcher.a(ast.cc.o):(.data.rel.ro._ZTIN4clif18TranslationUnitAST24ConversionFunctionFinderE[_ZTIN4clif18TranslationUnitAST24ConversionFunctionFinderE]+0x10): undefined reference to typeinfo for clang::ast_matchers::MatchFinder::MatchCallback'

**Setup**
  - Operating system: Centos 7
  - DeepVariant version: Latest github version
  - Installation method (Docker, built from source, etc.): building from source
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by sgoe1** [comment]
Hi @narendrachaudhary51, thanks for the question.

The recommended way to run DeepVariant is with our Docker image (see [quickstart](https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md)).

We don't explicitly support building from source on CentOS 7, although it should be possible with some modifications. I can refer you to issues #95 and #29, which you may find useful. Closing this bug for now, feel free to reopen or submit new issue.
