### ISSUE TITLE
PCR duplicates

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#384]
Hi, Does Deepvariant filter out (i.e. exclude) read duplicates, assuming they are flagged in the BAM/CRAM file? This is not mentioned in the documentation.

**Comment by AndrewCarroll** [comment]
Hi @gevro 

Yes, DeepVariant excludes reads that are marked with the duplicate flag in the BAM file. Empirically, we have found that marking duplicates makes very little difference in the samples we have looked at for 30x+ coverage. But it does have a slight effect on 15x-25x coverage range.
