### ISSUE TITLE
REFCALL and GLnexus merging

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#386]
Hi,  Two questions:
1) What does REFCALL mean? I saw another issue explaining it, but I'm still not understanding. If Deepvariant thinks a site is reference, why is it being reported at all? gVCF is supposed to report reference calls, but per VCF specifications, Deepvariant should not report reference calls. Furthermore, if it is a reference call, why is there an ALT allele?

2) Does your GLNexus merging/multi-sample genotyping workflow know to exclude REFCALL variants?

Thanks.

**Comment by AndrewCarroll** [comment]
Hi @gevro 

DeepVariant has two steps in calling variants. In the first (**make_examples**) a fairly simple, human-written heuristic identifies positions that are potentially variant and creates pileup examples of them. In the second stage (**call_variants**), a neural network classifies whether those positions are real variants or not and genotypes them.

A RefCall entry occurs when a candidate variant is proposed and then is specifically rejected as non-variant. In addition, the model provides an estimate of its confidence (expressed as the QUAL and GQ fields for the entry).

In the gVCF, a separate process determines the confidence for regions of the genome where no candidate is proposed and combines this with the information of the positions that have received a RefCall.

For GLnexus, the genotyping is able to include the knowledge that these positions have a proposed alternate allele, but received a reference call.

**Comment by gevro** [comment]
Thank you! I'm still curious-- if RefCall entries are rejected by 'call_variants', why are they still reported in the final VCF? Do they enable some sort of helpful QC checks? If so, which? Since any downstream application would filter these out, I'm a bit unclear why an internal variant nomination process is included in the final output.

**Comment by AndrewCarroll** [comment]
Hi @gevro

The inclusion of RefCall allows us to have a full record of every variant that DeepVariant was asked to classify. This is useful for QC (helping to distinguish between not enough coverage to nominate a candidate versus some other issue making the position difficult. Since the confidence values of DeepVariant are well-calibrated, It allows users to select for different filtering criteria in the event they want to increase recall.

**Comment by gevro** [comment]
Thank you very much for explaining.
