### ISSUE TITLE
make_examples fails to process data within docker container

### ISSUE THREAD

**Issue by holgerbrandl** [google/deepvariant#39]
I've setup deepvariant via `gsutil` as described under https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-docker.md

When running the first step `make_examples` as indicated in the reference within the docker container, it runs without any complaints, and terminates after around a second. However it does not create an output file nor does it output any error, nor does it care if I provide invalid input file names.

The downstream tools `call_variants` and `postprocess_variants` behave similar, they run without error, but accept any input arguments (including invalid ones) and fail to create any output.

Any help would be appreciated.

**Comment by arostamianfar** [comment]
This looks similar to #16 and may be a hardware compatibility issue. Could you please clarify if you're able to run the [quickstart](https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md) binaries without using the docker image?

**Comment by holgerbrandl** [comment]
No luck either. I figured it seems that the Xeon CPU on my machine does not support AVX (according to /proc/cpuinfo). Some informative error message would be nice in such a situation.

Couldn't the docker container be built without assuming avx presence? It would be slower I guess but easier to explore the tool.

**Comment by arostamianfar** [comment]
@scott7z Is it possible to add an error message for this? Seems to be a common issue among users.

@holgerbrandl as mentioned in #16, you can build the image from source that conforms to your environment. We prefer to provide 1 image with reasonable optimization settings. You may also consider using [Container-optimized OS](https://cloud.google.com/container-optimized-os/docs/) on Google Cloud to easily explore the tool.
