### ISSUE TITLE
conda installed deepvariant libm.so.6: version `GLIBC_2.23' not found

### ISSUE THREAD

**Issue by masen0407** [google/deepvariant#391]
Hello,
first of all ,i do not have the permission to run docker on my machine or sudo update or install. And as i work on cluster service,so i hardly can try to tell the Administrator to update some tools because there are other users and any update to key tools may cause them some troublesome.AS i know,many people work on bioinformation use cluster service and do not have permission to do sudo update or maybe not have a docker in service,but conda can do.
so i try search conda deepvariant,and i try conda install -c bioconda deepvariant=1.0.0(on python3,and i also try other version on python2),and i find dv_make_examples.py, and i see many other guys also try conda.(https://github.com/google/deepvariant/issues/9).
when i run dv_make_examples.py  on python3,i get ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /var/tmp/Bazel.runfiles_okfco2gt/runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so)
and i know it is wrong with GLIBC and the solution  is to update GLIBC to GLIBC_2.23 ,but i can not . i ask my Administrator and he say the glibc is too important and update it on  cluster service may cause other users bug. 

so is there any chance i can use deepvatiant ? and again,i can not install from source(no permission to sudo ) or docker(don't have docker on cluster service ),and i can't update glibc .
And the info are like this:
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /var/tmp/Bazel.runfiles_okfco2gt/runfiles/com_google_protobuf/python/google/protobuf/pyext/_message.so)
and strings /lib64/libc.so.6 |grep GLIBC:
GLIBC_2.2.5
GLIBC_2.2.6
GLIBC_2.3
GLIBC_2.3.2
GLIBC_2.3.3
GLIBC_2.3.4
GLIBC_2.4
GLIBC_2.5
GLIBC_2.6
GLIBC_2.7
GLIBC_2.8
GLIBC_2.9
GLIBC_2.10
GLIBC_2.11
GLIBC_2.12
GLIBC_2.13
GLIBC_2.14
GLIBC_2.15
GLIBC_2.16
GLIBC_2.17
GLIBC_PRIVATE
and the other information is :
Linux version 3.10.0-1127.18.2.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) ) #1 SMP Sun Jul 26 15:27:06 UTC 2020
conda 4.9.2
Python 3.7.6

i really hope you can help me.

**Comment by wharvey31** [comment]
Your version of CentOS does not contain a recent enough GLIBC. It is not listed in your strings output. To my knowledge there is no way to change this without updating your OS. 

I have had success using singularity without sudo to run the Docker image as described here: https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md#notes-on-singularity

**Comment by masen0407** [comment]
hello @wharvey31 
i try https://github.com/google/deepvariant/blob/r1.0/docs/deepvariant-quick-start.md#notes-on-singularity
but when i run singularity shell  deepvariant_1.0.0.sif, i get this :

INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting deepvariant_1.0.0.sif: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

singularity version 3.7.0

**Comment by masen0407** [comment]
Thanks for you reply
i try to use singularity,but i get some bug and i know it not cause by deepvariant .so i  try to ask on singularity hub.
i hope singularity can work wo my problem.
Thanks again
