### ISSUE TITLE
Simple suggestion

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#398]
Hello! 

not an issue, a simple suggestion: several persons I know are put off by DeepVariant because they can't get a gVCF with a line per base, basically they would like to deactivate the formation of blocks. Personally, blocks have never worried me and I guess computationally it has its advantages. 

But just to tlet you know as a "user experience"

Cheers and stay safe. DeepVariant is a very awesome tool.

**Comment by AndrewCarroll** [comment]
Hi @aderzelle 

If I correctly understand the question, this would be effectively equivalent to the setting EMIT_ALL_SITES options in GATK. Across an entire genome, emitting the data at all sites takes quite a bit longer and generates a gVCF file which is much larger. 

It is likely more compact and faster to get coverage information from a method like mosdepth. 

The option to emit all sites could make sense, but probably only for gene panels where the size of the output would not be unmanageable.

Please let me know if I mis-understand your suggestions

Thanks,
Andrew

**Comment by aderzelle** [comment]
Hello;

you perfectly understood my question and the answer makes sense. I do not close yet because there might be an additional reason the emit all sites option would have some interest (I am transferring the thread to a colleague).

Thanks for your answer.

**Comment by pichuan** [comment]
Hmm, I closed this but then noticed that @aderzelle said you're not closing on purpose.

@aderzelle Is there anything else we can help here? You mentioned that you'll get a colleague to give more suggestions. Just to make it easy to triage for the next teammate on rotation, I'm going to close this for now. But please feel free to open again as needed.
