### ISSUE TITLE
Discrepancies with Deepvariant instructions for Google Cloud

### ISSUE THREAD

**Issue by ArielPaulson** [google/deepvariant#399]
Hi,

I don't know if this is the place to report issues with running the docker pipeline on the google cloud, I have been following instructions at [https://cloud.google.com/life-sciences/docs/tutorials/deepvariant#console_1](https://cloud.google.com/life-sciences/docs/tutorials/deepvariant#console_1) and it mostly works, but the second command within the big docker call dies with some python error.  

That page indicates I should email google directly at google-genomics-contact@google.com, but this address bounces, which is why I came here.

Anyway I have all the commands and error messages etc, so let me know if this is the right place for that and I will post.

Thanks,
Ariel

**Comment by akolesnikov** [comment]
Hi Ariel,

Thank you for submitting the issue. This is the right place so please submit the output and other info you may have.

**Comment by ArielPaulson** [comment]
I followed the directions on that page, and for the most part everything seemed to work, but the docker install commands failed:

sudo apt-get -qq -y update
E: The repository 'https://download.docker.com/linux/ubuntu buster Release' does not have a Release file.

sudo apt-get -qq -y install docker-ce
E: Package 'docker-ce' has no installation candidate

So instead I ran an alternate docker installation, which succeeded (sudo apt install docker.io).  I don't know if this is the ultimate problem.

The first command within the docker seems to complete with no errors:

***** Running the command:*****
time seq 0 1 | parallel -k --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/hs37d5.fa.gz" --reads "/input/HG002_NIST_150bp_chr20_downsampled_30x.bam" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@2.gz" --gvcf "/tmp/deepvariant_tmp_output/gvcf.tfrecord@2.gz" --regions "20" --task {}

It does take 40 minutes as opposed to the advertised 8, though.  I was using pre-emptible instances so perhaps this caused delay, but I did test it 3 times, and it is reliably ~40 mins each time.

The second command within the docker dies, this is all the output:

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --examples "/tmp/deepvariant_tmp_output/make_examples.tfrecord@2.gz" --
checkpoint "/opt/models/wgs/model.ckpt"
I1217 09:08:41.108182 139680301201152 call_variants.py:313] Set KMP_BLOCKTIME to 0
2020-12-17 09:08:41.511115: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-12-17 09:08:42.039849: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-12-17 09:08:42.070759: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5abc760 executing computations on platform Host. Devices:
2020-12-17 09:08:42.070838: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2020-12-17 09:08:42.092135: I tensorflow/core/common_runtime/process_util.cc:71] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for 
best performance.
I1217 09:08:42.442809 139680301201152 modeling.py:560] Initializing model with random parameters
W1217 09:08:42.445099 139680301201152 estimator.py:1760] Using temporary folder as model directory: /tmp/tmpKfC9_T
I1217 09:08:42.445868 139680301201152 estimator.py:201] Using config: {'_save_checkpoints_secs': 600, '_session_config': , '_keep_checkpoint_max': 100000, '_task_type': 'worker', '_tra
in_distribute': None, '_is_chief': True, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f09a30d11d0>, '_model_dir': '/tmp/tmpKfC9_T', '_protocol': Non
e, '_save_checkpoints_steps': None, '_keep_checkpoint_every_n_hours': 10000, '_service': None, '_num_ps_replicas': 0, '_tf_random_seed': None, '_save_summary_steps': 100, '_device_fn':
 None, '_experimental_distribute': None, '_num_worker_replicas': 1, '_task_id': 0, '_log_step_count_steps': 100, '_evaluation_master': '', '_eval_distribute': None, '_global_id_in_clus
ter': 0, '_master': ''}
I1217 09:08:42.446381 139680301201152 call_variants.py:381] Writing calls to /tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz
W1217 09:08:42.450340 139680301201152 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.
python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
I1217 09:08:42.537085 139680301201152 data_providers.py:367] self.input_read_threads=8
W1217 09:08:42.537606 139680301201152 deprecation.py:323] From /tmp/Bazel.runfiles_ik_chB/runfiles/com_google_deepvariant/deepvariant/data_providers.py:372: parallel_interleave (from t
ensorflow.contrib.data.python.ops.interleave_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.experimental.parallel_interleave(...)`.
I1217 09:08:42.568870 139680301201152 data_providers.py:373] self.input_map_threads=48
I1217 09:08:42.607381 139680301201152 estimator.py:1111] Calling model_fn.
W1217 09:08:42.607652 139680301201152 deprecation.py:323] From /tmp/Bazel.runfiles_ik_chB/runfiles/com_google_deepvariant/deepvariant/modeling.py:880: to_float (from tensorflow.python.
ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
W1217 09:08:42.611661 139680301201152 deprecation.py:323] From /tmp/Bazel.runfiles_ik_chB/runfiles/com_google_deepvariant/deepvariant/modeling.py:882: div (from tensorflow.python.ops.m
ath_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
I1217 09:08:46.069416 139680301201152 estimator.py:1113] Done calling model_fn.
I1217 09:08:47.837505 139680301201152 monitored_session.py:222] Graph was finalized.
W1217 09:08:47.838197 139680301201152 deprecation.py:323] From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.pytho
n.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
I1217 09:08:47.839556 139680301201152 saver.py:1270] Restoring parameters from /opt/models/wgs/model.ckpt
I1217 09:08:52.319547 139680301201152 session_manager.py:491] Running local_init_op.
I1217 09:08:52.393850 139680301201152 session_manager.py:493] Done running local_init_op.
I1217 09:08:53.199553 139680301201152 modeling.py:410] Reloading EMA...
I1217 09:08:53.200850 139680301201152 saver.py:1270] Restoring parameters from /opt/models/wgs/model.ckpt
I1217 09:09:35.048069 139680301201152 call_variants.py:399] Processed 1 examples in 1 batches [5258.970 sec per 100]
real    2m5.783s
user    0m49.664s
sys     0m7.008s
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 317, in <module>
    app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 307, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time /opt/deepvariant/bin/call_variants --outfile "/tmp/deepvariant_tmp_output/call_variants_output.tfrecord.gz" --examples "/tmp/deepvariant_tm
p_output/make_examples.tfrecord@2.gz" --checkpoint "/opt/models/wgs/model.ckpt"' returned non-zero exit status 247

I checked $OUTPUT_DIR after this, but it was empty.

Let me know how to proceed,

Thanks,
Ariel

**Comment by akolesnikov** [comment]
1. Docker installation is not DeepVariant specific. You may follow steps from the official docker website https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository
2. From the output it looks like you run it on a machine with 2 cores. In Google tutorial n1-standard-64 instance is used which has 64 cores. 
3. From the output of the last command it is not clear what the error is. Could you post the command you used for creating an instance? It could be that call_variants command ran out of memory.
4. Although Google tutorial page contains the pricing for pre-emptible instances it is only given for the reference. It is not recommended to run this tutorial on a pre-emptible instances because in the case the instance is preemted the job cannot restart automatically. More complex configuration (like Kubernetes) is required in order to use pre-emptible instances.
5. Recently a new version of DeepVariant was released, so instead of using 0.9.0 the new version 1.1.0 and docker path google/deepvariant should be used. Although, using the latest version is preferred the old 0.9.0 should work as well.

**Comment by akolesnikov** [comment]
There are multiple tutorials covering different scenarios of running DeepVariant on [DeepVariant GitHib page](https://github.com/google/deepvariant/blob/r1.1/docs/README.md).

**Comment by ArielPaulson** [comment]
The instructions at https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md run ok.  

I have no idea how I ended up with only 2 cores in that VM, especially after having to email support to even get the 64 requested cores allocated, since they quotaed me at 32.  Also, I realized that the docker install command involving "buster" referred to a Debian release, which would never have worked with the Google Cloud instructions, since they specifically indicate you should use Ubuntu 16.04.  Have someone fix that page!  It is still an important page for anyone wanting to deploy on google, if they are not experienced with that cloud platform.

Thnks,
Ariel
