### ISSUE TITLE
Cannot append to buffer file in /tmp. Is the disk full? Exit Status 255

### ISSUE THREAD

**Issue by husamia** [google/deepvariant#400]
I am running the Docker google/deepvariant:latest-deeptrio

**Setup**
  - Operating system: Docker Desktop 3.0 (Windows 10)
  - DeepVariant version: DeepTrio version 1.1.0

 Trio WGS data HG37 (bams aligned with BWA MEM)

Command: 
/opt/deepvariant/bin/deeptrio/run_deeptrio --model_type=WGS --ref=human_g1k_v37.fasta --reads_child=DS187706-DS187706_39743_S1_261735.bam --reads_parent1=19CT021737-19CT021737-20190619_64683_S7_346963.bam --reads_parent2=19CT021740-19CT021740-20190619_64686_S8_346962.bam --output_vcf_child DS187706_proband.vcf --output_vcf_parent1 19CT021737_mother.vcf --output_vcf_parent2 19CT021740_father.vcf --sample_name_child 'DS187706_proband' --sample_name_parent1 '19CT021737_mother.vcf' --sample_name_parent2 '19CT021740_father' --num_shards 6

  - Error trace: (if applicable)
parallel: Error: Output is incomplete. Cannot append to buffer file in /tmp. Is the disk full?
parallel: Error: Change $TMPDIR with --tmpdir or use --compress.
Warning: unable to close filehandle properly: No space left on device during global destruction.

real    438m45.227s
user    0m12.742s
sys     0m12.847s
I1220 22:21:36.502776 140568143795968 run_deeptrio.py:584] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 600, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 582, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 5 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref "human_g1k_v37.fasta" --reads_parent1 "19CT021737-19CT021737-20190619_64683_S7_346963.bam" --reads_parent2 "19CT021740-19CT021740-20190619_64686_S8_346962.bam" --reads "DS187706-DS187706_39743_S1_261735.bam" --examples "/tmp/tmpgyn9dtrr/make_examples.tfrecord@6.gz" --sample_name "DS187706_proband" --sample_name_parent1 "19CT021737_mother.vcf" --sample_name_parent2 "19CT021740_father" --pileup_image_height_child "60" --pileup_image_height_parent "40" --task {}' returned non-zero exit status 255.

It looks like there is memory in Docker and in my virtual folder so it shouldn't be running out.

CONTAINER ID   NAME          CPU %     MEM USAGE / LIMIT     MEM %     NET I/O       BLOCK I/O        PIDS
bc855d19a65d   musing_saha   0.00%     35.36GiB / 93.81GiB   37.69%    3.13kB / 0B   313MB / 28.7kB   1

**Comment by AndrewCarroll** [comment]
Hi @husamia 

It looks like the error message is indicating that the disk is full, which can occur even when there is memory. Can you check how much hard disk space is present on the machine.

If you are running low on space unexpectedly, you may want to check that you aren't accumulating space from Docker runs that weren't cleaned up by the system. It could be worth looking at [this page](https://docs.docker.com/config/pruning/) if that is the case.

**Comment by pichuan** [comment]
Hi @husamia 
Another thing to note is that DeepVariant doesn't currently support Windows. We recommend getting a Linux machine. Let us know if that works for you.

**Comment by husamia** [comment]
> Hi @husamia
> 
> It looks like the error message is indicating that the disk is full, which can occur even when there is memory. Can you check how much hard disk space is present on the machine.
> 
> If you are running low on space unexpectedly, you may want to check that you aren't accumulating space from Docker runs that weren't cleaned up by the system. It could be worth looking at [this page](https://docs.docker.com/config/pruning/) if that is the case.

the disk has more than 100X times the size. So it's not a disk space. I will rerun after pruning to see if it solves the problem.

> Hi @husamia
> Another thing to note is that DeepVariant doesn't currently support Windows. We recommend getting a Linux machine. Let us know if that works for you.

Docker Desktop linux containers run natively on Windows 10.

**Comment by husamia** [comment]
after cleaning up Docker space with prune and making sure there is space on disk and rerunning. I am getting the same exact error. I feel that the docker image itself is the issue but not the software. i.e. maybe the docker image needs to be modified which I am not familiar with. I pulled it from docker pull google/deepvariant:latest-deeptrio

**Comment by pichuan** [comment]
Hi @husamia ,
I see that you're running DeepTrio.
For both DeepVariant or DeepTrio, it will generate intermediate files for each step (make_examples, call_variants). 

For DeepTrio, the size of these intermediate files might even be bigger, which might fill up your disk in the process.

I guess it is possible that Docker setting has some limit. I'm not familiar enough Docker to help with that.

A few suggestions here:

1. Can you tell us how big your 3 BAM files are?  For comparison, what we used in WGS in https://github.com/google/deepvariant/blob/r1.1/docs/metrics-deeptrio.md is:
```
$ gsutil ls -lh gs://deepvariant/case-study-testdata/HG00?.novaseq.pcr-free.35x.dedup.grch38_no_alt.bam
 42.87 GiB  2020-07-16T22:57:42Z  gs://deepvariant/case-study-testdata/HG002.novaseq.pcr-free.35x.dedup.grch38_no_alt.bam
 43.59 GiB  2020-08-19T20:40:44Z  gs://deepvariant/case-study-testdata/HG003.novaseq.pcr-free.35x.dedup.grch38_no_alt.bam
 42.88 GiB  2020-08-19T20:40:34Z  gs://deepvariant/case-study-testdata/HG004.novaseq.pcr-free.35x.dedup.grch38_no_alt.bam
TOTAL: 3 objects, 138872581896 bytes (129.34 GiB)
```
2. You can try one run with just one chromosome first, e.g., just chr20 (using the `--regions` flag) to see if I can get that run to finish. 

I'm going to close this issue first. But if there are anything else we can help with, feel free to reopen or file a new issue.

**Comment by husamia** [comment]
1. my files are larger than the examples 

60G Dec  6  2019 19CT021737-19CT021737-20190619_64683_S7_346963.bam
60G Dec  6  2019 19CT021740-19CT021740-20190619_64686_S8_346962.bam
61G Dec  6  2019 DS187706-DS187706_39743_S1_261735.bam

2. I am going to try it with --regions 20

**3. I am only interested in the PASS variants, so is it possible to filter output to only those variants? this will reduce the size of the output considerably.**

**Comment by pichuan** [comment]
@husamia 

1. All the intermediate stages (make_examples, call_variants) output some files. For example, when we run our [DeepTrio WGS case study](https://github.com/google/deepvariant/blob/r1.1/docs/deeptrio-wgs-case-study.md), the `intermediate_results_dir` directory contains about 260G of data:
```
TOTAL: 387 objects, 277723436467 bytes (258.65 GiB)
```

2. Let me know if just chromosome 20 works or not. With that, the intermediate files should be smaller.

3. You can use the `--only_keep_pass` flag in postprocess_variants. But this won't significantly reduce the amount of output, because this filtering is only done right before writing to VCF files. 
https://github.com/google/deepvariant/blob/2dbebb4d97e15d0d5fcf303a4466314b1f313208/deepvariant/postprocess_variants.py#L124
If you're using run_deepvariant, you can add `--postprocess_variants_extra_args="only_keep_pass=true"`.

**Comment by husamia** [comment]
I was able to solve the problem by using `--intermediate_results_dir tmp/` option

the files are being written to the tmp folder on local drive instead of inside the Docker container thus not running out of disk space.
