### ISSUE TITLE
About 6 channels

### ISSUE THREAD

**Issue by xuxif** [google/deepvariant#401]
Incept V3 only accept no more than 3 channel. How deepvariant process 6 input channels

**Comment by pichuan** [comment]
Hi @xuxif 
When you said "Incept V3 only accept no more than 3 channel", what do you mean?
Do you mean for the sake of warmstarting from a model with 3 channels?

**Comment by xuxif** [comment]
Pileup images have 6 channels (base, quality,strand...) .  But I found inception V3 only accept 3 channels inpput. I mean if deepvariant  modify the inception v3 input channels?

**Comment by pichuan** [comment]
Hi @xuxif ,
I'm not sure which inception v3 implementation you're looking at.
If it helps:
The InceptioV3 implementation that the DeepVariant codebase uses is the one in tf-slim, which supports different number of channels:
https://github.com/google-research/tf-slim/blob/master/tf_slim/nets/inception_v3.py
