### ISSUE TITLE
DeepVariant+GLnexus

### ISSUE THREAD

**Issue by aardes** [google/deepvariant#405]
Dear,

I tried the combination of the DeepVariant and GLnexus and they are working perfectly fine.

I would like to know is there a way to incrementally add to the output of the pipeline? of course, if all the previous gvcfs are available in case of new variants.

I mean something like the genomicsDB which is now being used by GATK.

This will be a great help in case of a large cohort because it can save a lot of time and computation power to calculate frequencies.

Kind regards
Amin

**Comment by AndrewCarroll** [comment]
Hi @aardes 

Yes, this is exactly what GLnexus was designed for, to allow for efficient merging of the N+1 sample in a manner analogous to genomicsDB (the [GLnexus paper](https://www.biorxiv.org/content/10.1101/343970v1) is informative for understanding this.

The generation of a gVCF from DeepVariant is independent of its subsequent analysis by GLnexus, so you can incrementally add more sample, and later run GLnexus to merge these gVCFs.

Hopefully this answered your question. Please let me know if there is something that remains unclear.

Andrew

**Comment by aardes** [comment]
Dear @AndrewCarroll ,

Thank you very much for the description, and for sharing the paper.

I think I need to contact the GLnexux team because I am not able to find the necessary GLnexus documents/scripts regarding the pVCF and the database.

thank you very much.
Amin
