### ISSUE TITLE
Deepvariant tensor shape

### ISSUE THREAD

**Issue by xuxif** [google/deepvariant#406]
Hi, I notice deepvariant created image with 100 * 299 * 6 for a record.  I want to know if deepvariant  reshape the image to meet the shape requirement of inception v3 ?

**Comment by sgoe1** [comment]
Hi @xuxif, InceptionV3 works on images with different input sizes, so we don't need to do any special resizing/processing of our pileup images. [This file](https://github.com/google/deepvariant/blob/r1.1/deepvariant/modeling.py) contains the modeling code if you're interested.
