### ISSUE TITLE
ImportError: libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by attilagk** [google/deepvariant#41]
The code in [Download binaries, models, and test data](https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md#download-binaries-models-and-test-data) the of the DV quick start guide ran successfully.  However, running [make_examples](https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-quick-start.md#make_examples) using the quickstart-testdata failed with the following error:
```
Traceback (most recent call last):
attila-ThinkS:~/tools/deepvariant$ python bin/make_examples.zip \
>   --mode calling   \
>   --ref "${REF}"   \
>   --reads "${BAM}" \
>   --regions "chr20:10,000,000-10,010,000" \
>   --examples "${OUTPUT_DIR}/examples.tfrecord.gz"
  File "/tmp/Bazel.runfiles_pbJgd2/runfiles/genomics/deepvariant/make_examples.py", line 45, in <module>
    from deepvariant import variant_caller
  File "/tmp/Bazel.runfiles_pbJgd2/runfiles/genomics/deepvariant/variant_caller.py", line 50, in <module>
    from deepvariant.python import variant_calling
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```

**Comment by pichuan** [comment]
Hi,
can you tell us the operating system you're on? Did the step with run-prereq.sh finish without any error messages?

**Comment by attilagk** [comment]
OS: Debian 9 stretch.  I confirmed the 0 exit status of run-prereq.sh.

**Comment by attilagk** [comment]
I confirmed again that `cd bin; sudo ./run-prereq.sh` exits with `$?` set to 0.  Then I did another attempt with `make-examples.zip` and the test data but the result is still the same ImportError.

**Comment by attilagk** [comment]
Interestingly, if I run `cd bin; ./run-prereq.sh` (without `sudo`) I get a permission error:
```
========== [Fri Jan 26 11:13:59 EST 2018] Stage 'Install TensorFlow pip package' starting                                                   
Installing Google Cloud Platform optimized CPU-only TensorFlow wheel                                
Copying gs://deepvariant/packages/tensorflow/tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl...
OSError: Operation not permitted.                                                                                                           
```

**Comment by pichuan** [comment]
Currently our case studies are all done on Ubuntu 16.04.
The easiest way will be to try it on that.

We don't currently have plans to support other OS. If you do get it to work, please let us know!! I added an internal bug to track this, but currently the priority is not high.

**Comment by attilagk** [comment]
I see.  I have another computer running Ubuntu 16.04.  I'll try with that.

**Comment by pgrosu** [comment]
Hi Attila,

So your account would need `sudo` privileges, which you probably already figured out.  The `run-prereq.sh` itself [contains calls](https://github.com/google/deepvariant/blob/r0.4/run-prereq.sh) using `sudo`, which is why you are getting the `not permitted` OS error.  If you curious to see the trace of the script to determine where the issue might be arising from, just run it like this and that will provide you with an exact control-flow:

`sudo bash -x ./run-prereq.sh`

So these suggestions are just for curiosity purposes, and Pi-Chuan's recommendation is the correct one since it has been validated on Ubuntu 16.04.

Hope it helps,
Paul

**Comment by attilagk** [comment]
Hi Paul,

thanks for the explanation.  In the meantime I found out that Debian 9 stretch uses openssl v1.1 whereas Ubuntu 16.04 uses v1.0 and perhaps that's why I run into the issue.  I symlinked `ln -s libcrypto.so.1.1.0 libcrypto.so.1.0.0` and this hack solved the issue.  But then other issues emerged on Debian 9, which made me try to build everything from source.  However, the large number of dependencies prevented me from succeeding.

Anyhow, I'll try installation on Ubuntu 16.04.

**Comment by pgrosu** [comment]
Hi Attila,

Yeah it takes about a week to fully uncover how all the dependencies work together, which can be fun if you have the time.  The side-benefit is that then you'll discover that DeepVariant is just a basic collections of tools (and data-structures) with many possibilities to tweak, simplify and expand on - which can be even more fun to play with :)

~p

**Comment by depristo** [comment]
@pgrosu Thanks Paul, we appreciate the close eye you've given to the codebase. Unfortunately managing all of the dependencies is challenging, and we aren't super happy with how complex the build/run prereqs scripts are. And we agree with you that there's a lot of opportunity to explore extensions, simplifications, and optimizations of DeepVariant.

**Comment by pgrosu** [comment]
Hi Mark (@depristo),

There is a theme of elegance with the current implementation that I tend to appreciate, though I agree that streamlining it for support/growth is rich with opportunities to explore.  Let me know if you would like to work on it together - or just bounce off ideas - as some could be low-hanging fruit with simple remedies.

Best,
Paul

**Comment by animesh** [comment]
downloading http://security.debian.org/debian-security/pool/updates/main/o/openssl/libssl1.0.0_1.0.1t-1+deb8u10_amd64.deb followed by
```
sudo dpkg --install libssl1.0.0_1.0.1t-1+deb8u10_amd64.deb
```
seems to work on WSL debian 9
