### ISSUE TITLE
Error on Post processing from 2 different gvcf sources

### ISSUE THREAD

**Issue by leorippel** [google/deepvariant#413]
**Describe the issue:**
I'm doing a series of test of how can I run DV faster with my resources. I'm trying splitting the bam file - run make examples on separate - run Call Variants of both at the same time and call variants. Everything goes fine until the postprocess The 2 different gvcf are name as followed:

SPLIT2.gvcf.tfrecord-00000-of-00030.gz
SPLIT.gvcf.tfrecord-00000-of-00030.gz

Both in the same directory

I know that ideally would  run on separate all the way then merge the two gvcf, but I'm,m asking if there is any tweak I can do to overcome this problem... I tought on rename the files from 0:59-of-00060.gz but can someone also tell me the implications of that move?  

**Setup**
  - Linux
  - DeepVariant version: 1.0.0
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: WGS from shallow resequencing data

**Steps to reproduce:**
  - Command: " /opt/deepvariant/bin/postprocess_variants --ref "/ref/100kbPrad_v1_scaffolds.fasta" --infile "/input/call_variants_output.tfrecord.gz" --outfile "/output/MergedSplited.output.vcf.gz" --nonvariant_site_tfrecord_path "/input/gvcf.tfrecord@30.gz" --gvcf_outfile "/output/MergedSplited.output.g.vcf.gz" --vcf_stats_report=False" 
  
  - Error trace: 
Singularity> time /opt/deepvariant/bin/postprocess_variants --ref "/ref/100kbPrad_v1_scaffolds.fasta" --infile "/input/call_variants_output.tfrecord.gz" --outfile "/output/MergedSplited.output.vcf.gz" --nonvariant_site_tfrecord_path "/input/gvcf.tfrecord@30.gz" --gvcf_outfile "/output/MergedSplited.output.g.vcf.gz" --vcf_stats_report=False
2021-01-26 15:54:17.883294: I deepvariant/postprocess_variants.cc:88] Read from: /input/call_variants_output.tfrecord.gz
2021-01-26 16:15:59.645306: I deepvariant/postprocess_variants.cc:103] Total #entries in single_site_calls = 144590159
I0126 17:29:21.938455 140157300115200 postprocess_variants.py:1079] CVO sorting took 95.07083837985992 minutes
I0126 17:29:21.940265 140157300115200 postprocess_variants.py:1081] Transforming call_variants_output to variants.
I0126 17:29:22.052276 140157300115200 postprocess_variants.py:1108] Merging and writing variants to VCF and gVCF.
I0126 17:29:22.509974 140157300115200 genomics_writer.py:172] Writing /output/MergedSplited.output.vcf.gz with NativeVcfWriter
I0126 17:29:22.844680 140157300115200 genomics_writer.py:172] Writing /output/MergedSplited.output.g.vcf.gz with NativeVcfWriter
2021-01-26 17:29:22.919993: E third_party/nucleus/io/tfrecord_reader.cc:48] /input/gvcf.tfrecord-00000-of-00030.gz; No such file or directory
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1143, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1122, in main
    vcf_writer, gvcf_writer)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 953, in merge_and_write_variants_and_nonvariants
    nonvariant = next_or_none(nonvariant_iterable)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 948, in next_or_none
    return next(iterable)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/third_party/nucleus/io/tfrecord.py", line 139, in read_shard_sorted_tfrecords
    protos = Reader(path, proto, compression_type=compression_type).iterate()
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/third_party/nucleus/io/tfrecord.py", line 60, in Reader
    path, proto, compression_type=compression_type)
  File "/tmp/Bazel.runfiles_88m2azo2/runfiles/com_google_deepvariant/third_party/nucleus/io/genomics_reader.py", line 174, in __init__
    'Error trying to open %s for reading' % input_path)
OSError: [Errno 5] Error trying to open /input/gvcf.tfrecord-00000-of-00030.gz for reading

real    95m15.549s
user    89m30.039s
sys     5m49.495s

**Does the quick start test work on your system?**
yes

**Any additional context:**

Appreciate any help.

Cheers.

**Comment by pichuan** [comment]
Hi @leorippel 

In your log, the error says:
```
2021-01-26 17:29:22.919993: E third_party/nucleus/io/tfrecord_reader.cc:48] /input/gvcf.tfrecord-00000-of-00030.gz; No such file or directory
```
Can you confirm that you actually have this file? From what you described earlier, you're trying to rename files into this format, but I'm not sure what you actually rename them to.

**Comment by pichuan** [comment]
@leorippel Please let us know if you still need help with this issue.
I'll keep this open for a few more days.

**Comment by leorippel** [comment]
> Hi @leorippel
> 
> In your log, the error says:
> 
> ```
> 2021-01-26 17:29:22.919993: E third_party/nucleus/io/tfrecord_reader.cc:48] /input/gvcf.tfrecord-00000-of-00030.gz; No such file or directory
> ```
> 
> Can you confirm that you actually have this file? From what you described earlier, you're trying to rename files into this format, but I'm not sure what you actually rename them to.

Yes, Sorry for the late reply.

when I type the input command " --nonvariant_site_tfrecord_path "/input/gvcf.tfrecord@30.gz"   "  I understand that the script will look for this pattern, no? Because I tried *gvcf.tfrecord@30.gz also didn't work and as I mentioned before my entry files are "SPLIT2.gvcf.tfrecord-00000-of-00030.gz and SPLIT.gvcf.tfrecord-00000-of-00030.gz ". The "*" before the pattern should work? maybe two --nonvariant_site_tfrecord_pat flags? 

how Can I pass those 2 differents names to the argument?

Cheers.

**Comment by danielecook** [comment]
@leorippel

This specification:

>  --nonvariant_site_tfrecord_path "/input/gvcf.tfrecord@30.gz

Will not match the gvcf splits you created. When paths contain an `@` symbol, they are referencing sharded files - so the path above gets expanded to a collection of files to input:

```
/input/gvcf.tfrecord-00000-of-00030.gz
/input/gvcf.tfrecord-00001-of-00030.gz
/input/gvcf.tfrecord-00002-of-00030.gz
...
```

But your paths contain different prefixes (`SPLIT1` and `SPLIT2`).

Regarding your original question:

> I know that ideally would run on separate all the way then merge the two gvcf, but I'm,m asking if there is any tweak I can do to overcome this problem... I tought on rename the files from 0:59-of-00060.gz but can someone also tell me the implications of that move?

Although I think this is technically possible I would advise against renaming sharded files. Sharded files are not designed to be manually renamed.

Instead, if you are looking to speed up DeepVariant further I would recommend parallelizing the work across multiple CPUs. DeepVariant already parallelizes across cores when performing variant calling, but you can chunk the genome (e.g. by chromosome), and run each chunk on a different CPU, then combine the results at the end.

**Comment by danielecook** [comment]
@leorippel I am closing this for now as I believe your issue has been addressed, but if you have any further questions feel free to reopen.

**Comment by lvclark** [comment]
I was able to run `make_examples` multiple times and have `call_variants` use multiple sharded tfrecord files at once.  But I guess from this thread that the same is not possible for `postprocess_variants`?

If I run:

```
postprocess_variants --ref Homo_sapiens.GRCh37.dna.primary_assembly.fa \
--infile call_variants_mysample.tfrecord.gz --outfile mysample.vcf.gz \
--nonvariant_site_tfrecord_path gvcf1_parent1.tfrecord@32.gz,gvcf3_parent1.tfrecord@32.gz \
--gvcf_outfile mysample.gvcf.gz
```

I get errors like:

```
gvcf1_parent1.tfrecord@32.gz,gvcf3_parent1.tfrecord-00031-of-00032.gz; No such file or directory
```

So is the solution to loop through (or run in parallel) my gvcf tfrecord files, output multiple gvcfs, and then concat them with bcftools?

FYI, the `postprocess_variants` help page from docker://google/deepvariant:deeptrio-1.5.0-gpu implies that multiple tfrecord files will be accepted:

```
--nonvariant_site_tfrecord_path: Optional. Path(s) to the non-variant sites protos in TFRecord format to convert to gVCF file. This should be the complete set of outputs from the --gvcf flag of make_examples.py.
```

**Comment by pichuan** [comment]
Hi @lvclark 

For `--nonvariant_site_tfrecord_path`, multiple tfrecord files will be accepted, but not in a comma-delimited list.
You can use the sharded form (like gvcf1_parent1.tfrecord@32.gz). And I think you can use wildcard (like gvcf1_parent1.tfrecord@.gz). But the code doesn't currently split a comma-delimited list for that argument.

Hope this helps.

**Comment by lvclark** [comment]
Hi @pichuan.  I am already using the sharded form.  My problem is I have two sharded files from two separate runs of make_examples.  I tried using the wildcard of gvcf*_parent1.tfrecord@32.gz but it did not work.

**Comment by lvclark** [comment]
I'm running into this issue because I am using DeepTrio with a male child, so, per the instructions, I have to run the sex chromosomes separately with just one parent.  But then I want one combined VCF with all regions when I am done.

I'm doing this in Nextflow, and while I have been waiting I have come up with a solution anyway passing the sharded tfrecord files from one process to the next and looping through the genomic regions that were run separately.

**Comment by pichuan** [comment]
Thanks @lvclark for the context of why you're doing this. That's very helpful to know.

In that case, you'll want to run the whole pipeline separately as well (meaning, make_examples -> call_variants -> postprocess_variants separately), one using `gvcf1_parent1.tfrecord@32.gz` , the other one with `gvcf3_parent1.tfrecord@32.gz`. And not to combine them mid-way.

Our team is working on makeing chrX/Y calling a bit better for DeepVariant and DeepTrio. I'll make sure to pass this feedback as well so we'll think about the use case here a bit more later on.
