### ISSUE TITLE
ENH: add samtools to docker image

### ISSUE THREAD

**Issue by brentp** [google/deepvariant#414]
Since deepvariant allows sending cram directly, it's no longer strictly necessary to convert bam to cram. 
But, I find it's still faster to do the bam->cram conversion for exome data (especially when no regions file is specified). For that, it would be nice to have samtools binary in the official image.

I understand if you want to keep the docker image to a minimal size and it's easy to derive from your image but thought it might be generally useful to have samtools in the base DV docker image.

**Comment by AndrewCarroll** [comment]
Hi @brentp 

This is a reasonable request, and CRAM->BAM conversion is faster via a samtools command. I don't think it will add much to the size of the container to include this, so we'll look at doing this, and will probably plan to do so, likely in the next release.

**Comment by pichuan** [comment]
@brentp Thanks for the suggestion! As @AndrewCarroll mentioned, we'll look into adding it.
Adding it to our Docker image should be quite straightforward.

I have one more question:
Can you provide a specific example usage you have in mind? 
You mentioned bam -> cram. I wonder if you're expecting being able to call samtools manually from our docker image, or do you actually expect something integrated into the one-step run_deepvariant.py script.
In addition to adding it to our Docker image, it'll be nice for us to add corresponding documentation as well. So I'm trying to think through how our users would like to use this.

Thanks!

**Comment by brentp** [comment]
Hi, I use it like this:
```
samtools view --threads 32 -bT $fasta -o ${sample}.bam $cram
samtools index -@ 32 ${sample}.bam
/opt/deepvariant/bin/run_deepvariant \
    --reads=${sample}.bam \
    --intermediate_results_dir=$TMPDIR/$sample/ \
    --model_type=$model \
    --output_gvcf=${sample}.gvcf.gz \
    --output_vcf=${sample}.vcf.gz \
    --num_shards=48 \
    --ref=$fasta
```
so just having it in PATH for manual calling would be sufficient for my use-case. Though if a flag like --conv-cram-to-bam existed, I'd be happy to use that instead.

thanks for the responses.

**Comment by pichuan** [comment]
I've filed an internal issue to track. The update should come out in the next release. I'll close this comment for now, but will post an update once it's out.
Thanks for the feedback!

**Comment by brentp** [comment]
and note to anyone who finds this. there is a `--write-index` flag to samtools view which writes the index while viewing so the second pass by `samtools index` is not needed.
