### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by wharvey31** [google/deepvariant#422]
Hello, when running DeepVariant on a machine with a GPU, we get  
[the attached error](https://github.com/google/deepvariant/files/5947987/DeepVariantError.txt)
which seems to indicate that DeepVariant cannot find the samples in the working directory which is a solid state drive contained within the node. Oddly enough, when we rerun without removing the files in the /tmp directory, DeepVariant completes without error. Do you have any explanation for this? The submit command is below as system information.

**Setup**
  - Operating system: CentOS7, cuda/11.0
  - DeepVariant version: v1.1.0
  - Installation method: Singularity
  - Type of data: PacBio HiFi from SQII with hg38

**Steps to reproduce:**
  - Command: `singularity run --nv --bind $(readlink -f dv_wd):/wd /path/to/deepvariant/images/deepvariant_1.1.0-gpu.sif /opt/deepvariant/bin/run_deepvariant  --model_type=PACBIO --ref=/wd/hg38.ref.fasta --reads=/wd/${sample}.bam --output_vcf=/wd/${sample}.vcf --output_gvcf=/wd/${sample}.gvcf --novcf_stats_report --intermediate_results_dir=/tmp/deepvariant_tmp/$( whoami )_${sample}/ --num_shards=${threads}`
  - Error trace: Included above
  - We have also tried out a similar process running on another machine without a GPU, and we do not see this issue.

**Comment by akolesnikov** [comment]
Hello,
The way you run it looks correct. I don't understand how running it for the second time succeeded. Could you try to run it with the intermediate_results_dir set to the location inside /wd directory?
We will try to reproduce it and then update the thread.

**Comment by gunjanbaid** [comment]
@wharvey31 I'll close out this issue, but feel free to reopen if you have any remaining questions. Thanks!
