### ISSUE TITLE
"How DeepVariant works" figure on Github dark mode

### ISSUE THREAD

**Issue by brendanreardon** [google/deepvariant#423]
**Describe the issue:**
You may want to consider adding a white background to your diagram of stages in DeepVariant under "How DeepVariant works" in your README. Since Github added dark mode, SVG diagrams without set backgrounds are difficult to view for users with this setting. There is an [active feature request open for Github](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/38), but I thought that you all might appreciate the Github issue. 

Here is a screenshot of the figure on my screen - 
<img width="851" alt="Screen Shot 2021-02-10 at 7 28 19 PM" src="https://user-images.githubusercontent.com/9423424/107672807-547d6c00-6c63-11eb-9f46-9116b8adae56.png">

Thank you! Keep up the great work!

**Comment by MariaNattestad** [comment]
Thanks for bringing this up Brendan! I have added the white background to the diagram internally, so it will be fixed on GitHub in the next release.

If this is annoying to more people, I could cherry-pick it to fix it sooner. Leave the pair-of-eyes emoji here to vote for us to prioritize this.
