### ISSUE TITLE
Deepvariant does not pass to call variants stage

### ISSUE THREAD

**Issue by kostasgalexiou** [google/deepvariant#427]
I have run a couple of times deepvariant on Google cloud, following the steps described at the corresponding webpage, and obtained the expected results. However, for a specific sample only make_examples and gvcf.tfrecord files are generated. The VM instance is running for 10 hours at 100% CPU and suddenly drops to almost 0% without the generation of any new results.

Any help will be appreciated!

**Comment by pichuan** [comment]
Hi @kostasgalexiou , can you provide more information like:
- What type of machines are you working on (how many cores, how much RAM)
- Any error messages that you can share?

**Comment by kalexiou** [comment]
Hi @pichuan,

VM instance: n1-standard-16 (16 vCPUs, 60 GB memory)

I don't get any error messages. The instance is still on and not giving any errors....or at least I haven't found any logs myself...

Below is the structure of the contents in the VM instance:

├── [drwxrwxr-x 4.0K]  input
│   └── [drwxrwxr-x 4.0K]  data
│       ├── [-rw-rw-r-- 2.9G]  Annuum.v1.6.Total.fa
│       ├── [-rw-rw-r-- 1.6M]  Annuum.v1.6.Total.fa.fai
│       ├── [-rw-rw-r--  17G]  FC85.sort.pcr_rem.RG.kept.bam
│       └── [-rw-rw-r-- 9.2M]  FC85.sort.pcr_rem.RG.kept.bam.bai
└── [drwxrwxr-x 4.0K]  output
    └── [drwxr-xr-x 4.0K]  intermediate_results_dir
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00000-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00001-of-00016.gz
        ├── [-rw-r--r-- 337M]  gvcf.tfrecord-00002-of-00016.gz
        ├── [-rw-r--r-- 337M]  gvcf.tfrecord-00003-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00004-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00005-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00006-of-00016.gz
        ├── [-rw-r--r-- 337M]  gvcf.tfrecord-00007-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00008-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00009-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00010-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00011-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00012-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00013-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00014-of-00016.gz
        ├── [-rw-r--r-- 338M]  gvcf.tfrecord-00015-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00000-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00001-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00002-of-00016.gz
        ├── [-rw-r--r-- 9.9G]  make_examples.tfrecord-00003-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00004-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00005-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00006-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00007-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00008-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00009-of-00016.gz
        ├── [-rw-r--r--  10G]  make_examples.tfrecord-00010-of-00016.gz
        ├── [-rw-r--r--  10G]  make_examples.tfrecord-00011-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00012-of-00016.gz
        ├── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00013-of-00016.gz
        ├── [-rw-r--r--  10G]  make_examples.tfrecord-00014-of-00016.gz
        └── [-rw-r--r-- 10.0G]  make_examples.tfrecord-00015-of-00016.gz

Thanks
Kostas

**Comment by pichuan** [comment]
Hi @kostasgalexiou , from the log, does it look like all 16 make_examples have finished? (At the end it should have something like:
```
Task 1/16: Created ... examples
```
If that's hard to see, can you check how many of the make_examples are still running?

Thanks.

**Comment by kalexiou** [comment]
Hi @pichuan . Unfortunately, I do not have the log file. None of the make_examples is running. The last update occurred on March,1 at 18:44.

Can we say whether the make_example / gvcf process has finished? If yes, can I launch deevariant again and go directly to call_variants?

-rw-r--r-- 1 root        root          354156544 Mar  1 18:44 gvcf.tfrecord-00000-of-00016.gz
-rw-r--r-- 1 root        root          353894400 Mar  1 18:44 gvcf.tfrecord-00001-of-00016.gz
-rw-r--r-- 1 root        root          353632256 Mar  1 18:44 gvcf.tfrecord-00002-of-00016.gz
-rw-r--r-- 1 root        root          353107968 Mar  1 18:44 gvcf.tfrecord-00003-of-00016.gz
-rw-r--r-- 1 root        root          353894400 Mar  1 18:44 gvcf.tfrecord-00004-of-00016.gz
-rw-r--r-- 1 root        root          354156544 Mar  1 18:44 gvcf.tfrecord-00005-of-00016.gz
-rw-r--r-- 1 root        root          353894400 Mar  1 18:44 gvcf.tfrecord-00006-of-00016.gz
-rw-r--r-- 1 root        root          353370112 Mar  1 18:44 gvcf.tfrecord-00007-of-00016.gz
-rw-r--r-- 1 root        root          353894400 Mar  1 18:44 gvcf.tfrecord-00008-of-00016.gz
-rw-r--r-- 1 root        root          354156544 Mar  1 18:44 gvcf.tfrecord-00009-of-00016.gz
-rw-r--r-- 1 root        root          354942976 Mar  1 18:44 gvcf.tfrecord-00010-of-00016.gz
-rw-r--r-- 1 root        root          354942976 Mar  1 18:44 gvcf.tfrecord-00011-of-00016.gz
-rw-r--r-- 1 root        root          354418688 Mar  1 18:44 gvcf.tfrecord-00012-of-00016.gz
-rw-r--r-- 1 root        root          354680832 Mar  1 18:44 gvcf.tfrecord-00013-of-00016.gz
-rw-r--r-- 1 root        root          354680832 Mar  1 18:44 gvcf.tfrecord-00014-of-00016.gz
-rw-r--r-- 1 root        root          354156544 Mar  1 18:44 gvcf.tfrecord-00015-of-00016.gz
-rw-r--r-- 1 root        root        10704650240 Mar  1 18:44 make_examples.tfrecord-00000-of-00016.gz
-rw-r--r-- 1 root        root        10710417408 Mar  1 18:44 make_examples.tfrecord-00001-of-00016.gz
-rw-r--r-- 1 root        root        10699931648 Mar  1 18:44 make_examples.tfrecord-00002-of-00016.gz
-rw-r--r-- 1 root        root        10677649408 Mar  1 18:44 make_examples.tfrecord-00003-of-00016.gz
-rw-r--r-- 1 root        root        10692329472 Mar  1 18:44 make_examples.tfrecord-00004-of-00016.gz
-rw-r--r-- 1 root        root        10725359616 Mar  1 18:44 make_examples.tfrecord-00005-of-00016.gz
-rw-r--r-- 1 root        root        10707271680 Mar  1 18:44 make_examples.tfrecord-00006-of-00016.gz
-rw-r--r-- 1 root        root        10696880128 Mar  1 18:44 make_examples.tfrecord-00007-of-00016.gz
-rw-r--r-- 1 root        root        10711728128 Mar  1 18:44 make_examples.tfrecord-00008-of-00016.gz
-rw-r--r-- 1 root        root        10711203840 Mar  1 18:44 make_examples.tfrecord-00009-of-00016.gz
-rw-r--r-- 1 root        root        10742923264 Mar  1 18:44 make_examples.tfrecord-00010-of-00016.gz
-rw-r--r-- 1 root        root        10751836160 Mar  1 18:44 make_examples.tfrecord-00011-of-00016.gz
-rw-r--r-- 1 root        root        10715398144 Mar  1 18:44 make_examples.tfrecord-00012-of-00016.gz
-rw-r--r-- 1 root        root        10723262464 Mar  1 18:44 make_examples.tfrecord-00013-of-00016.gz
-rw-r--r-- 1 root        root        10745282560 Mar  1 18:44 make_examples.tfrecord-00014-of-00016.gz
-rw-r--r-- 1 root        root        10700980224 Mar  1 18:44 make_examples.tfrecord-00015-of-00016.gz

**Comment by pichuan** [comment]
Hi @kostasgalexiou ,
Looking at the file size, they look reasonable, but I can't tell exactly whether they're complete or not.
You can certainly try directly to run call_variants. If some of the records are not complete or corrupted, call_variants or postprocess_variants might give you an error later on.

I'm still curious on why it didn't finish though. If you have more new observations or logs that might be informative, please let me know. I suppose your input BAM file is not public? If it is public, I would love to try to reproduce your issue on a n1-standard-16 machine.

**Comment by kalexiou** [comment]
Yes, the bam file is not public, but I could send you the files through a private link. Thanks for your help!

**Comment by pichuan** [comment]
Hi @kalexiou ,
if the file is not public, unfortunately I cannot download it or test it. Thanks for offering though.

If you can share a bit more about what type of file this is (sequencing instrument, coverage, PCR-free or PCR-plus, etc) that might make this file unique, maybe I can try to see if I can reproduce the issue on another public file. Thanks!

**Comment by kalexiou** [comment]
Hi @pichuan ,

I think that the file is not especial in any way, since this sample has been sequenced with other samples that did not give me any problems.

How can I launch directly the call_variants function?

Thanks again
Kostas

**Comment by pichuan** [comment]
@kalexiou 

`call_variants` is a binary in our Docker image too. So you can run:
```
docker run google/deepvariant:1.1.0 /opt/deepvariant/bin/call_variants --help
```
to look at all relevant flags.

Your command should be probably something like:
```
...
/opt/deepvariant/bin/call_variants \
--outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" \
--examples "/output/intermediate_results_dir/make_examples.tfrecord@16.gz" \
--checkpoint "/opt/models/wgs/model.ckpt"
```

The checkpoint should be either wgs, wes, or pacbio depending on which type you were using.

**Comment by kalexiou** [comment]
Great! Thanks @pichuan

**Comment by pichuan** [comment]
Hi @kalexiou ,
I think what might have happened is that the make_examples stage ran out of memory.
I recently had a run on a different BAM, which had similar behavior as you described.

A few suggestions:
(1) If you're using the same type of machine, try running with fewer number of num_shards which should allow each make_examples to have more RAM.
(2) If you can try a different machine type, try n1-highmem-16 (104GB RAM) to see if that helps.

We're looking into how we can make our error messages informative if this is the key issue. Based on this observation, I suspect your intermediate make_examples output might not be complete.

**Comment by kostasgalexiou** [comment]
Hi @pichuan,

Thanks for the update! I will try your suggestions next time I come up with a "heavy" bam file.

Kostas
