### ISSUE TITLE
no  human model use

### ISSUE THREAD

**Issue by zhoudreames** [google/deepvariant#428]
in my project ,my species is pig——diploid,haploid genome size 2.5Gb,how to use deepvariant in my pig data ?

**Comment by zhoudreames** [comment]
@cdibona @dberlin @pichuan @AndrewCarroll  could you help me ? thanks ~

**Comment by pichuan** [comment]
Hi @zhoudreames ,
You can apply DeepVariant in this case. DeepVariant is trained on human data, but we've seen it generalized to other cases before. 
In addition to the BAM file you have, you'll need to provide a Pig reference file.
For the command here:
https://github.com/google/deepvariant#how-to-run-deepvariant

The two main inputs that have to come from your are these:
```
  --ref=/input/YOUR_REF \
  --reads=/input/YOUR_BAM \
```

Curious to hear how it works for you!
