### ISSUE TITLE
nVidia GPU Cuda 11 support in docker

### ISSUE THREAD

**Issue by znikasz** [google/deepvariant#430]
Is there a plan to support nVidia GPU Cuda 11 version in dockers available in the dockerhub? 

Current version of `google/deepvariant:latest-gpu` uses Cuda 10, which does not work on newest nVidia GPUs.

**Comment by sgoe1** [comment]
Hi @znikasz thanks for bringing this up. CUDA 11 support was added in the latest version of TensorFlow (2.4.0), so when we upgrade our version of TF, this support will be included. However, I don't have a specific timeframe for when this will happen.

**Comment by husamia** [comment]
does this mean we can potentially run future versions of deepvariant-GPU on Windows using Docker Desktop?

**Comment by sgoe1** [comment]
@husamia technically yes, I believe you should be able to run via Docker on Windows, even with current version (but not with CUDA 11, as mentioned).

However, this is not something we explicitly support/test against, so if you have issues running it feel free to let us know, but we may not be able to provide much support.
