### ISSUE TITLE
run_deeptrio missing child vcfs

### ISSUE THREAD

**Issue by husamia** [google/deepvariant#431]
I ran deeptrio on a trio WGS data. I got the gvcf and vcf for parent 1 and 2 but I didn't get output from child. There were no error messages that I could find as to why. The output seems complete.

**Setup**
  - Operating system: Windows 10
  - DeepVariant version: DeepTrio version 1.1.0
  - Installation method: Docker
  - Type of data: Illumina, GRCh38, trio WGS

**Steps to reproduce:**
  - Command:
 `/opt/deepvariant/bin/deeptrio/run_deeptrio 

- --model_type=WGS 
- --ref=GRCh38_full_analysis_set_plus_decoy_hla.fa 
- --reads_child=20A0012672_P_GRCh38.bam 
- --reads_parent1=20A0012673_M_GRCh38.bam 
- --reads_parent2=NBVY8432_GRCh38.bam
-  --output_vcf_child 20A0012672_P_GRCh38_deeptrio.vcf.gz 
- --output_vcf_parent1 20A0012673_M_GRCh38_deeptrio.vcf.gz 
- --output_vcf_parent2 NBVY8432_GRCh38_deeptrio.vcf.gz 
- --sample_name_child '20A0012672_P' 
- --sample_name_parent1 '20A0012673_M' 
- --sample_name_parent2 'NBVY8432' 
- --num_shards $(nproc) 
- --intermediate_results_dir ../home/tmp 
- --output_gvcf_child 20A0012672_P_GRCh38_deeptrio.gvcf.gz 
- --output_gvcf_parent1 20A0012673_M_GRCh38_deeptrio.gvcf.gz 
- --output_gvcf_parent2 NBVY8432_GRCh38_deeptrio.gvcf.gz`

  - Error trace: NA

**Comment by akolesnikov** [comment]
* Could you please check the intermediate directory ```../home/tmp``` to see if examples are generated for all 3 samples? 
* Also, could you please check that child BAM is mapped to the right reference and does contain reads overlapping parent1 and parent2 samples?

**Comment by husamia** [comment]
> * Could you please check the intermediate directory `../home/tmp` to see if examples are generated for all 3 samples?

`../home/tmp` contains 315 files. 105 for each sample.

> * Also, could you please check that child BAM is mapped to the right reference and does contain reads overlapping parent1 and parent2 samples?

I am not sure what you mean here.

**Comment by akolesnikov** [comment]
It looks like examples were created for all the samples but call_variants did not run for the child. 
Could you please check the sizes of all files with extension ```tfrecord``` for all samples? To make sure that parents' files are not empty.
Is there a chance you could share your BAM files or may be just a chr20? It would be easier to investigate the issue if we could reproduce it locally.
Also, could you try to run the test on Ubuntu OS?

**Comment by husamia** [comment]
> Could you please check the sizes of all files with extension `tfrecord` for all samples? To make sure that parents' files are not empty.

the files are non-empty 
422M Mar 10 05:32 call_variants_output_child.tfrecord.gz
430M Mar 10 17:02 call_variants_output_parent1.tfrecord.gz
253M Mar 10 23:58 call_variants_output_parent2.tfrecord.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00000-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00001-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00002-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00003-of-00052.gz
 39M Mar  9 17:56 gvcf_child.tfrecord-00004-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00005-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00006-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00007-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00008-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00009-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00010-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00011-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00012-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00013-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00014-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00015-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00016-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00017-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00018-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00019-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00020-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00021-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00022-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00023-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00024-of-00052.gz
 38M Mar  9 17:55 gvcf_child.tfrecord-00025-of-00052.gz
 39M Mar  9 17:55 gvcf_child.tfrecord-00026-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00027-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00028-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00029-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00030-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00031-of-00052.gz
 39M Mar  9 17:56 gvcf_child.tfrecord-00032-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00033-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00034-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00035-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00036-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00037-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00038-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00039-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00040-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00041-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00042-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00043-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00044-of-00052.gz
 38M Mar  9 17:53 gvcf_child.tfrecord-00045-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00046-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00047-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00048-of-00052.gz
 39M Mar  9 17:53 gvcf_child.tfrecord-00049-of-00052.gz
 38M Mar  9 17:54 gvcf_child.tfrecord-00050-of-00052.gz
 39M Mar  9 17:54 gvcf_child.tfrecord-00051-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00000-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00001-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00002-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00003-of-00052.gz
 18M Mar  9 17:56 gvcf_parent1.tfrecord-00004-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00005-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00006-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00007-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00008-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00009-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00010-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00011-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00012-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00013-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00014-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00015-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00016-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00017-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00018-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00019-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00020-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00021-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00022-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00023-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00024-of-00052.gz
 18M Mar  9 17:55 gvcf_parent1.tfrecord-00025-of-00052.gz
 18M Mar  9 17:55 gvcf_parent1.tfrecord-00026-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00027-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00028-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00029-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00030-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00031-of-00052.gz
 18M Mar  9 17:56 gvcf_parent1.tfrecord-00032-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00033-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00034-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00035-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00036-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00037-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00038-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00039-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00040-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00041-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00042-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00043-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00044-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00045-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00046-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00047-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00048-of-00052.gz
 18M Mar  9 17:53 gvcf_parent1.tfrecord-00049-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00050-of-00052.gz
 18M Mar  9 17:54 gvcf_parent1.tfrecord-00051-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00000-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00001-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00002-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00003-of-00052.gz
 42M Mar  9 17:56 gvcf_parent2.tfrecord-00004-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00005-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00006-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00007-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00008-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00009-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00010-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00011-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00012-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00013-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00014-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00015-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00016-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00017-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00018-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00019-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00020-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00021-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00022-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00023-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00024-of-00052.gz
 41M Mar  9 17:55 gvcf_parent2.tfrecord-00025-of-00052.gz
 42M Mar  9 17:55 gvcf_parent2.tfrecord-00026-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00027-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00028-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00029-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00030-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00031-of-00052.gz
 41M Mar  9 17:56 gvcf_parent2.tfrecord-00032-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00033-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00034-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00035-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00036-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00037-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00038-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00039-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00040-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00041-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00042-of-00052.gz
 42M Mar  9 17:53 gvcf_parent2.tfrecord-00043-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00044-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00045-of-00052.gz
 42M Mar  9 17:54 gvcf_parent2.tfrecord-00046-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00047-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00048-of-00052.gz
 41M Mar  9 17:53 gvcf_parent2.tfrecord-00049-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00050-of-00052.gz
 41M Mar  9 17:54 gvcf_parent2.tfrecord-00051-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00000-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00001-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00002-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00003-of-00052.gz
1.9G Mar  9 17:56 make_examples_child.tfrecord-00004-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00005-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00006-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00007-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00008-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00009-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00010-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00011-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00012-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00013-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00014-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00015-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00016-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00017-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00018-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00019-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00020-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00021-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00022-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00023-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00024-of-00052.gz
1.9G Mar  9 17:55 make_examples_child.tfrecord-00025-of-00052.gz
1.9G Mar  9 17:55 make_examples_child.tfrecord-00026-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00027-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00028-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00029-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00030-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00031-of-00052.gz
1.9G Mar  9 17:56 make_examples_child.tfrecord-00032-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00033-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00034-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00035-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00036-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00037-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00038-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00039-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00040-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00041-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00042-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00043-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00044-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00045-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00046-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00047-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00048-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00049-of-00052.gz
1.9G Mar  9 17:54 make_examples_child.tfrecord-00050-of-00052.gz
1.9G Mar  9 17:53 make_examples_child.tfrecord-00051-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00000-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00001-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00002-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00003-of-00052.gz
1.9G Mar  9 17:56 make_examples_parent1.tfrecord-00004-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00005-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00006-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00007-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00008-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00009-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00010-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00011-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00012-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00013-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00014-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00015-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00016-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00017-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00018-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00019-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00020-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00021-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00022-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00023-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00024-of-00052.gz
1.9G Mar  9 17:55 make_examples_parent1.tfrecord-00025-of-00052.gz
1.9G Mar  9 17:55 make_examples_parent1.tfrecord-00026-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00027-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00028-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00029-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00030-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00031-of-00052.gz
1.9G Mar  9 17:56 make_examples_parent1.tfrecord-00032-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00033-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00034-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00035-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00036-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00037-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00038-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00039-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00040-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00041-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00042-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00043-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00044-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00045-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00046-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00047-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00048-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00049-of-00052.gz
1.9G Mar  9 17:54 make_examples_parent1.tfrecord-00050-of-00052.gz
1.9G Mar  9 17:53 make_examples_parent1.tfrecord-00051-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00000-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00001-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00002-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00003-of-00052.gz
1.2G Mar  9 17:56 make_examples_parent2.tfrecord-00004-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00005-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00006-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00007-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00008-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00009-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00010-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00011-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00012-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00013-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00014-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00015-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00016-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00017-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00018-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00019-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00020-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00021-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00022-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00023-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00024-of-00052.gz
1.2G Mar  9 17:55 make_examples_parent2.tfrecord-00025-of-00052.gz
1.2G Mar  9 17:55 make_examples_parent2.tfrecord-00026-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00027-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00028-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00029-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00030-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00031-of-00052.gz
1.2G Mar  9 17:56 make_examples_parent2.tfrecord-00032-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00033-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00034-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00035-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00036-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00037-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00038-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00039-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00040-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00041-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00042-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00043-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00044-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00045-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00046-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00047-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00048-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00049-of-00052.gz
1.2G Mar  9 17:54 make_examples_parent2.tfrecord-00050-of-00052.gz
1.2G Mar  9 17:53 make_examples_parent2.tfrecord-00051-of-00052.gz


> Is there a chance you could share your BAM files or may be just a chr20? It would be easier to investigate the issue if we could reproduce it locally.

I don't have cloud storage for thi.

> Also, could you try to run the test on Ubuntu OS?

I can't run it on Ubuntu OS

**Comment by akolesnikov** [comment]
From the list of files you posted it looks like variants were created for child (file call_variants_output_child.tfrecord.gz). The last stage of DeepTrio pipeline is postprocess_variants where data is converted from tfrecord to VCF. I suggest to try running postprocess_variants manually. 

To generate a VCF:
```
/opt/deepvariant/bin/postprocess_variants --infile call_variants_output_child.tfrecord.gz --outfile <child VCF file name> --ref GRCh38_full_analysis_set_plus_decoy_hla.fa
```

To generate a g.VCF:
```
/opt/deepvariant/bin/postprocess_variants --infile call_variants_output_child.tfrecord.gz --outfile <child VCF file name> --ref --gvcf_outfile <child G.VCF file name> GRCh38_full_analysis_set_plus_decoy_hla.fa --nonvariant_site_tfrecord_path gvcf_child.tfrecord-*.gz
```

These commands are generated by run_deeptrio.py file. You may also look into this file to get a better insight on how each command is run.

**Comment by husamia** [comment]
> From the list of files you posted it looks like variants were created for child (file call_variants_output_child.tfrecord.gz). The last stage of DeepTrio pipeline is postprocess_variants where data is converted from tfrecord to VCF. I suggest to try running postprocess_variants manually.
> 
> To generate a VCF:
> 
> ```
> /opt/deepvariant/bin/postprocess_variants --infile call_variants_output_child.tfrecord.gz --outfile <child VCF file name> --ref GRCh38_full_analysis_set_plus_decoy_hla.fa
> ```
> 
> To generate a g.VCF:
> 
> ```
> /opt/deepvariant/bin/postprocess_variants --infile call_variants_output_child.tfrecord.gz --outfile <child VCF file name> --ref --gvcf_outfile <child G.VCF file name> GRCh38_full_analysis_set_plus_decoy_hla.fa --nonvariant_site_tfrecord_path gvcf_child.tfrecord-*.gz
> ```
> 
> These commands are generated by run_deeptrio.py file. You may also look into this file to get a better insight on how each command is run.

This suggestion works for me. Thank you
