### ISSUE TITLE
name 'optimize_for_inference_lib' is not defined when running call_variants

### ISSUE THREAD

**Issue by ajsa-nukovic** [google/deepvariant#432]
I tried to build deepvariant through my own docker image. I installed deepvariant and openvino toolkit. But, when I run _call_variants.zip_ script, I get the error **_name 'optimize_for_inference_lib' is not defined_**. I was retracing steps and came to conclusion that  `from openvino.inference_engine import StatusCode` part of the code is failing. StatusCode cannot be imported. Have you ever encountered the same problem ?

I installed DeepVariant1.1.0 version via Docker using Ubuntu 18.04.

The command I run was 
`python /opt/DeepVariant-1.1.0/call_variants.zip --outfile ./call_variants_output.tfrecord.gz --examples ./examples.tfrecord@${N_SHARDS}.gz --checkpoint /opt/DeepVariant-1.1.0/models/DeepVariant-inception_v3-1.1.0+data-wes_standard/model.ckpt --use_openvino --num_readers 32 ` 

and got this error:
```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 502, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/absl_py/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/absl_py/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 492, in main
    use_tpu=FLAGS.use_tpu,
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 409, in call_variants
    checkpoint_path, input_fn=tf_dataset, model=model)
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 89, in __init__
    freeze_graph(model, checkpoint_path, tensor_shape)
  File "/tmp/Bazel.runfiles_xn6q5j3y/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 77, in freeze_graph
    graph_def = optimize_for_inference_lib.optimize_for_inference(
NameError: name 'optimize_for_inference_lib' is not defined
```

**Comment by pichuan** [comment]
Hi @ajsa-nukovic , thanks for reporting the issue.

First, I tried to reproduce your issue. I haven't been able to reproduce it yet. I wrote down my commands below:

Get a Ubuntu18.04 machine 
```
gcloud compute instances create "${USER}-test" \
   --scopes "compute-rw,storage-full,cloud-platform" \
  --image-family "ubuntu-1804-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "e2-medium" \
  --zone "us-west1-b"
```

After ssh into the machine, I ran:

```
sudo apt -y update && sudo apt -y install docker.io
```

And then followed the steps here:

https://github.com/google/deepvariant/blob/r1.1/docs/deepvariant-quick-start.md

For the main DeepVariant command, I ran:

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=1  \
  --call_variants_extra_args="use_openvino=true" \
  2>&1 | tee /tmp/deepvariant.log
```

With this run above, all steps (including call_variants) completed without errors.

After that run, I repeated the call_variants step:
```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/call_variants \
  --outfile "/output/intermediate_results_dir/call_variants_output.tfrecord.gz" \
  --examples "/output/intermediate_results_dir/make_examples.tfrecord@1.gz" \
  --checkpoint "/opt/models/wgs/model.ckpt" \
  --use_openvino
```
which worked fine too.

You mentioned you used DeepVariant1.1.0 version via Docker, but you also mentioned your command was:
`python /opt/DeepVariant-1.1.0/call_variants.zip --outfile ./call_variants_output.tfrecord.gz --examples ./examples.tfrecord@${N_SHARDS}.gz --checkpoint /opt/DeepVariant-1.1.0/models/DeepVariant-inception_v3-1.1.0+data-wes_standard/model.ckpt --use_openvino --num_readers 32`

Can you be more specific about how you run this command?


And, another pointer for you:
In our Dockerfile, we set these environment variables:
https://github.com/google/deepvariant/blob/r1.1/Dockerfile#L156-L157

You should probably first check whether those directories exist in your environment. And if they do exist, you'll need to set those environment variables too.

Hope this helps.

**Comment by pichuan** [comment]
Closing this issue. @ajsa-nukovic , feel free to follow up.

**Comment by ajsa-nukovic** [comment]
Thanks a lot @pichuan, I am working on this - apparently my OpenVino installation wasn't good. Your answer was very helpful.
