### ISSUE TITLE
Binaries for v1.1 necessary to update bioconda package

### ISSUE THREAD

**Issue by nikostr** [google/deepvariant#436]
Hi! The current bioconda recipe requires precompiled binaries to be available at `https://github.com/google/deepvariant/releases/download/v{{ version }}/deepvariant.zip`. I've updated the bioconda recipe to work with v1.0.0, but for a smooth update to v1.1.0, it would be excellent if you could provide zipped binaries with the release.

The bioconda recipe: https://github.com/bioconda/bioconda-recipes/tree/master/recipes/deepvariant

**Comment by pichuan** [comment]
Thanks @nikostr for reporting this.
The zip file for 1.1.0 should be avaiable at https://github.com/google/deepvariant/releases/download/v1.1.0/deepvariant.zip now.
