### ISSUE TITLE
A quick start guide issue

### ISSUE THREAD

**Issue by MainTankJerry** [google/deepvariant#44]
I was trying to follow the quick start guide. While running the run-prereq.sh file, I got
`========== Load config settings.`
`========== [Sun Jan 28 13:47:50 EST 2018] Stage 'Misc setup' starting`
`========== [Sun Jan 28 13:47:50 EST 2018] Stage 'Update package list' starting`
`sudo: apt-get: command not found`
Then, I realize it is because I am running it on mac. Is there any quick fix to this problem?

**Comment by pichuan** [comment]
Hi,
We ran our case studies on Ubuntu 16.04. Can you try it on Ubuntu?

**Comment by MainTankJerry** [comment]
Okay!
