### ISSUE TITLE
Build from source Ubuntu 1.18.04 problem

### ISSUE THREAD

**Issue by mkazanov** [google/deepvariant#443]
Hello,

I am trying to install DeepVariant from source on Ubuntu 1.18.04. The build-prereq.sh script finished well,
but  build_and_test.sh has stopped unexpectedly do not displaying any error:

```
(18:54:51) INFO: Found applicable config definition build:linux in file /data1/SOFT/tensorflow/.bazelrc: --copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
(18:54:51) INFO: Found applicable config definition build:dynamic_kernels in file /data1/SOFT/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
(18:54:51) INFO: Current date is 2021-04-16
(18:54:51) INFO: Build option --build_python_zip has changed, discarding analysis cache.
(18:54:51) INFO: Analyzed target //:licenses_zip (0 packages loaded, 22 targets configured).
(18:54:51) INFO: Found 1 target...
(18:54:51) INFO: Elapsed time: 0.224s, Critical Path: 0.00s
(18:54:51) INFO: 0 processes.
+ echo 'Expect a usage message:'
Expect a usage message:
+ python3 bazel-out/k8-opt/bin/deepvariant/call_variants.zip --help
+ grep /call_variants.py:
/tmp/Bazel.runfiles_5qjtwbro/runfiles/com_google_deepvariant/deepvariant/call_variants.py:
+ :
```

**Comment by pichuan** [comment]
Hi @mkazanov 
Internally we've updated to Ubuntu18.04 and made a bunch of updates accordingly too. It will come out in the next release.

Given that there's another similar question in https://github.com/google/deepvariant/issues/441 , I can try to see if it's easy for me to share some of the updated files (I'll need to test it with the v1.1 repo first).
Otherwise, I can try to push a bit more on the timeline for the next release.

**Comment by pichuan** [comment]
Hi @mkazanov ,

Update:
First, I want to remind you that:
  * Our next release (r1.2) will be on Ubuntu 18.04. 
  * And, even right now (with r1.1), you should be able to run our `google/deepvariant:1.1.0` on Ubuntu18.04.

Just in case you really need to build your own on a Ubuntu18.04 now, I put together some changes that we already made internally to update to Ubuntu 18.04 here:
https://github.com/pichuan/deepvariant/tree/r1.1-ubuntu18
(**Note**: This is my own fork. In the future I might delete it. But at least before r1.2 comes out, I'll keep it there.)

If you want to understand what changes have been made, you can see this:
https://github.com/google/deepvariant/compare/r1.1...pichuan:r1.1-ubuntu18
