### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by woodoo46** [google/deepvariant#444]
Hi there,

We ran deepvariant on test data, and we had the following error:

I0416 16:33:15.202579 46954465520640 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 3 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "reference/GRCh38_no_alt_analysis_set.fasta" --reads "input/HG003.GRCh38.chr20.pFDA_truthv2.bam" --examples "/tmp/tmpmxakjtgh/make_examples.tfrecord@4.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --noparse_sam_aux_fields --norealign_reads --regions "chr20" --nosort_by_haplotypes --vsc_min_fraction_indels "0.12" --task {} )' returned non-zero exit status 2.

We converted docker image to singularity sandbox. And our command is like this:
singularity exec -B /data -B /home -B /localhd/ \
    ../deepvariant-cpu.sif  \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref reference/GRCh38_no_alt_analysis_set.fasta \
    --reads input/HG003.GRCh38.chr20.pFDA_truthv2.bam \
    --output_vcf deepvariant1/output.vcf.gz \
    --num_shards ${nproc} \
    --regions chr20

I am guessing we may have misconfigured some module. Any idea how to fix it?

Thanks.

George

**Comment by pichuan** [comment]
Hi @woodoo46 
Can you give me more information like:
Which OS you're using, what singularity version, etc.

And, are there more logs before the first line?
```
I0416 16:33:15.202579 46954465520640 run_deepvariant.py:416] None
```

It'll help if I can try reproducing the error first.

**Comment by woodoo46** [comment]
I think it is a misconfiguration on our side, sorry about that.
