### ISSUE TITLE
ENH: support python3.7+

### ISSUE THREAD

**Issue by brentp** [google/deepvariant#445]
Hi, it's getting harder to build deepvariant, even using bioconda as everything it moving to python3.7 or higher.
Would it be possible to get the build and Dockerfile updated to 3.7? And/or could you provide some guidance on what is needed?

Using the docker container works perfectly. But I want to add bcftools and samtools (for example) to the container and also have it work on singularity.
thanks,
-B

**Comment by danielecook** [comment]
Hi Brent I will check in on this and get back to you. Just to be clear, are using `FROM google/deepvariant` and then installing bioconda and using that to install bcftools / samtools or are you using bioconda to install deepvariant, samtools, and bcftools?

**Comment by danielecook** [comment]
@brentp what version of singularity are you using? I have had issues with older versions of Singularity in the past and was able to get things to work by using 3+.

I can experiment with this for a bit and try to put together a Dockerfile that install Samtools and Bcftools.

**Comment by brentp** [comment]
```
$ singularity --version
2.4.2-dist
```
thanks for looking into it! I will also try newer singularity.

**Comment by brentp** [comment]
Yes, it works simply updating singularity. Thanks for figuring this out!
