### ISSUE TITLE
PACBIO model error

### ISSUE THREAD

**Issue by ruolin** [google/deepvariant#446]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.1/docs/FAQ.md**:

**Describe the issue:**
```
Deepvariant failed on PACBIO data. 
```

**Setup**
  - Operating system:
  `google cloud through [Terra](https://terra.bio/)`
  - DeepVariant version:
  `1.1.0`
  - Installation method (Docker, built from source, etc.):
  `google/deepvariant:1.1.0`
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  ```
Pacbio bam from GIAB 
https://ftp-trace.ncbi.nlm.nih.gov/ReferenceSamples/giab/data/NA12878/PacBio_SequelII_CCS_11kb/HG001.SequelII.pbmm2.hs37d5.whatshap.haplotag.RTG.trio.bam
reference from Broad GCP
gs://gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta
Though this is a slight ref mismatch, B37 vs hs37. I don't think that should cause that problem? The make_examples step finished successfully.
```
**Steps to reproduce:**
  - Command:
 ```
/opt/deepvariant/bin/run_deepvariant \
        --model_type=PACBIO \
        --ref=${REF_GENOME_FASTA} \
        --reads=${input_read} \
        --num_shards=${NUM_THREADS} \
        --output_vcf=${basename}.vcf.gz
```
  - Error trace: (if applicable)
```parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /cromwell_root/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta --reads /cromwell_root/fc-13e1404e-623c-489f-956c-b388fa9fb975/bams/HG001.SequelII.pbmm2.hs37d5.whatshap.haplotag.RTG.trio.bam --examples /cromwell_root/tmp.e4eeba80/tmpphthddeo/make_examples.tfrecord@20.gz --add_hp_channel --alt_aligned_pileup diff_channels --parse_sam_aux_fields --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 6
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /cromwell_root/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta --reads /cromwell_root/fc-13e1404e-623c-489f-956c-b388fa9fb975/bams/HG001.SequelII.pbmm2.hs37d5.whatshap.haplotag.RTG.trio.bam --examples /cromwell_root/tmp.e4eeba80/tmpphthddeo/make_examples.tfrecord@20.gz --add_hp_channel --alt_aligned_pileup diff_channels --parse_sam_aux_fields --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 7

real    133m6.986s
user    230m53.643s
sys 1m59.690s
I0425 04:55:14.754644 140234455082752 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 19 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/cromwell_root/gcp-public-data--broad-references/hg19/v0/Homo_sapiens_assembly19.fasta" --reads "/cromwell_root/fc-13e1404e-623c-489f-956c-b388fa9fb975/bams/HG001.SequelII.pbmm2.hs37d5.whatshap.haplotag.RTG.trio.bam" --examples "/cromwell_root/tmp.e4eeba80/tmpphthddeo/make_examples.tfrecord@20.gz" --add_hp_channel --alt_aligned_pileup "diff_channels" --parse_sam_aux_fields --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels "0.12" --task {} )' returned non-zero exit status 247.
2021/04/25 04:55:23 Starting delocalization.
```
**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
`Yes. I tested the PacBio case study on chr20 on my system. It ran through without any problems`
**Any additional context:**
`The total error log is quite lengthy but mostly just logging make_examples.py. I can share with you the Terra workflow which you can reproduce. To do that, I probably need your email address. `

**Comment by danielecook** [comment]
@ruolin I can take a look at the Terra workflow. Send an email to my username `@google.com`.

If I had to guess, this is likely an issue with memory usage or storage resources.

**Comment by ruolin** [comment]
@danielecook Thanks. Just shared with you. The submission id is `ac89cde6-db3a-4af6-85e5-334f0c74efae`. Let me know if it does not work.

**Comment by danielecook** [comment]
@ruolin I don't see any issues with the inputs. Are you able to run this with more memory?

**Comment by ruolin** [comment]
@danielecook Thanks for looking into this! I have 320GB (20 cores x 16G per core) memory now. How large do you think is needed?

**Comment by pichuan** [comment]
Hi @ruolin ,
thanks for reporting this issue. I'll try running on your BAM and reference and see if we can reproduce the issue.
We have in the past seen cases where the jobs run out of memory, and our error messages in that situation isn't very clear. So @danielecook 's guess of OOM makes sense. But the memory you're reporting sounds like it should be enough. So let me see if I can reproduce this issue.

**Comment by pgrosu** [comment]
Hi Pichuan,

Maybe this might help.  Try to launching the `free` command in the background on some interval like 60 sec, before all the deepvariant ones:

  `free -s 60 > dv_mem_usage.txt`

Then when deepvariant completes have the command be auto-terminated so it doesn't run indefinitely.

Then you'll know for sure if memory is the culprit based on the memory profile.

Hope it helps,
~p

**Comment by ruolin** [comment]
@pichuan @danielecook Thank you guys for such a quick response. It is something I feared. The Cromwell dispatcher is a black box to me. I will try your configurations and some others too to see if it solves the problems.

**Comment by pichuan** [comment]
Thanks @ruolin . If you have suggestions on how to reproduce this issue so we can take a look, please feel free to re-open this issue.
