### ISSUE TITLE
build from source

### ISSUE THREAD

**Issue by yanyang1989** [google/deepvariant#448]
Run a interactive mode of docker container (different than deepvariant container) and plan to build the deepvariant from source:

run the build-prereq.sh and run build_and_test.sh. Then how to test deepvariant function?

**Comment by yanyang1989** [comment]
then I found the call_variants.py is listed in /root/.cache/bazel/_bazel_root/617054f44dc1f1e9b3fe3174f8eb2580/execroot/com_google_deepvariant/bazel-out/k8-opt/bin/deepvariant/call_variants_test.runfiles/com_google_deepvariant/deepvariant/call_variants.py

**Comment by yanyang1989** [comment]
when I build_and_test.sh, there showing error:
bazel-out/k8-opt/bin/external/com_google_protobuf/src: warning: directory does not exist.

where is this directory?

**Comment by akolesnikov** [comment]
I'm not sure I understand what you are trying to do. If you'd like to build your own docker image that includes DeepVariant you may follow commands in DeepVariant docker config - deepvariant/Dockerfile

**Comment by gunjanbaid** [comment]
@yanyang1989 closing this out, but feel free to reopen if you are still running into trouble. Thanks!
