### ISSUE TITLE
Searching for the 6 channel code :)

### ISSUE THREAD

**Issue by mvilsker** [google/deepvariant#449]
Hi,

I am searching for the code that converts the input files (BAM) to the 6 channels that you used in CNN. Can you help me out please?

**Comment by danielecook** [comment]
@mvilsker The pileup_image python and C++ code here contains most of the logic for constructing the channels

https://github.com/google/deepvariant/blob/r1.1/deepvariant/pileup_image.py
https://github.com/google/deepvariant/blob/r1.1/deepvariant/pileup_image_native.h
https://github.com/google/deepvariant/blob/r1.1/deepvariant/pileup_image_native.cc

This script does the work of generating tensors for each example:

https://github.com/google/deepvariant/blob/r1.1/deepvariant/python/clif_converters.cc

**Comment by mvilsker** [comment]
Thanks!
