### ISSUE TITLE
Joint genotyping tool

### ISSUE THREAD

**Issue by llllaaaa** [google/deepvariant#45]
Is there a recommended tool for joint genotyping the gvcfs of a trio?

Thanks

**Comment by llllaaaa** [comment]
@rpoplin Do you have any suggestions?  Thanks

**Comment by cmclean** [comment]
At present we do not have a specific recommendation for joint genotyping DeepVariant gVCFs. Given the accurate genotype likelihood calibration of single-sample DeepVariant calls it may be better to simply merge calls without computing genotype posteriors based on population allelic frequencies and then altering the genotypes. We are actively investigating the performance of different methods to be able to provide a set of best practices.

That said, the gVCF outputs of DeepVariant are syntactically and semantically equivalent to those produced by other tools like GATK, so can be used by any existing joint genotyping tools.

**Comment by jaqueytw** [comment]
Hi there!

I tried to combine the deepvariant's gvcf files using GATK and it returned a error because of the "NON_REF".
Do you have any other recommendation? Or did you tested your gvcf in GATK?

This is the error:
A USER ERROR has occurred: The list of input alleles must contain <NON_REF> as an allele but that is not the case at position 10325413; please use the Haplotype Caller with gVCF output to generate appropriate records

The DeepVariant "<NON_REF>" allele is "<*>"

**Comment by AndrewCarroll** [comment]
Hi @jaqueytw 

To combine DeepVariant gVCFs together, we currently recommend using [GLnexus](https://github.com/dnanexus-rnd/GLnexus) with the --config deepvariant flag. This should combine DeepVariant gVCFs in a valid manner without filtering or re-genotyping.

We have used GLnexus in this way in some of our early cohort investigations (for example in [this blog](https://google.github.io/deepvariant/posts/2018-12-05-improved-non-human-variant-calling-using-species-specific-deepvariant-models/) on a mosquito pedigree).

We are currently in the process of more fully evaluating the optimal ways to use GLnexus to merge DeepVariant calls. As this functionality matures, we will update our recommendations.

Finally, to clarify our recommendations regarding GATK-based methods to combine gVCFs. Although these may run, in these sense that the gVCF format used by DeepVariant can be successfully used, we do not currently recommend their use to combine DeepVariant gVCFs.

**Comment by AndrewCarroll** [comment]
Hi @llllaaaa 

I wanted to update this issue with recent developments for cohort merging. With the DeepVariant v0.9 release, we recommend [Best practices for multi-sample variant calling with DeepVariant](https://github.com/google/deepvariant/blob/r0.9/docs/trio-merge-case-study.md)

We encourage you or other users interested in multi-sample calling to follow these recommendations to combine multiple DeepVariant gVCFs

Thank you.
