### ISSUE TITLE
DeepTrio and type 2 error question

### ISSUE THREAD

**Issue by husamia** [google/deepvariant#450]
Well, this is not really a problem. It's rather a question. Someone asked about the de novo germline calling last year [#377](https://github.com/google/deepvariant/issues/377). Deeptrio is now available and I want to ask general question in regards with denovo variants in the child. 

Background: the biggest issue with calling de novo variants (i.e. variants that are found in proband, generally as heterozygous, negative in parents) is there are ton's of false negative calls (Type II error) (i.e. variants not called in parents but are visually obvious in the alignment). 

It seems to me that DeepTrio should address this issue particularly well but I am not sure if that is the motivation behind DeepTrio. How does DeepTrio handle type 2 errors for de novo germline variant calling? can this be added as an enhancement?

Thank you

**Comment by husamia** [comment]
Yes, it's a fine balance indeed. Looking at it from different perspective. Higher than normal (in matched trios) of presumed "de novo germline variants in the child" , generally indicates sample QC problem. Another perspective, 99.9% of the de novo germline candidates in the child are false positives due to the type II error that I described. It's pretty significant!

In the context of the calling de novo germline variants in child. When there is QC issue, the will be way too many false positivies. Samples should be flagged. When it's just mapping quality issues, the variants should be execluded in the search i.e. don't call them as de novo. This would make the search much smaller. 

This would be a model for the "de novo germline in the child"

**Comment by AndrewCarroll** [comment]
Hi @husamia 

I am curious, are you working with human sequence data, or do these come from non-human species?

I will take a look at the ratio of these events in our sample. If we could provide a simple filtering script to postprocess a callset, would this be something that you might use?

Thank you,
Andrew

**Comment by husamia** [comment]
@AndrewCarroll I am working with human data. Called for clinical diagnosis. There is great interest in the clinical community to call de novo variants in the child from trio data. There is data about the rates of those events. In 1% of the human genome there is only one real de novo. If it's more than two there is sample QC problem.

**Comment by AndrewCarroll** [comment]
Hi @husamia 

Thank you for the extra information. If there is any feedback that you can provide, I would be very grateful for examples. If you would like to follow up by email, you can reach me at awcarroll@google.com

Thank you,
Andrew

**Comment by husamia** [comment]
Hi @AndrewCarroll 

Is it possible to de novo variant call in the trio starting with the make examples step? Not a filtering script. 

Here is the reason:
When you call variants in the context of the child, parent 1 and parent 2 you can capture more information about the variants that you can not from individually calling the variants in each individual.

**Comment by AndrewCarroll** [comment]
Hi @husamia 

This is a reasonable idea, I have some idea of how to accomplish it. I am going to close this issue for now and follow up with you by email around some of the possible examples.
