### ISSUE TITLE
deepvariant is very slow on alignements produced by hisat2 and reports only half of expected SNPs/INDELs

### ISSUE THREAD

**Issue by lpryszcz** [google/deepvariant#460]
Hi, is there any recommendation regarding short-read aligner that works the best with deepvariant? I have looked into your tutorials, but they always start from BAM files... 

I aligned HG002 (Illumina, 30x) using hisat2, bwa-mem2 and snap-aligner. Initially I've looked at 3 Mb (chr20:10,000,000-13,000,000). 
To my big surprise deepvariant was running ~100x slower on BAM file produced by hisat2 (duplicates were marked using `samtools markdup`) compared to the BAM produced by either bwa-mem2 or snap-aligner. And it reported only ~half of expected SNPs/INDELs from hisat2 alignments (recall ~0.5, while precision ~0.99).   
Deepvariant reached expected precision/recall (over 0.99) when using BAM produced by bwa-mem2 (duplicates were marked using `samtools markdup`) or snap-aligner.  

So the issue seems to be related to hisat2 alignemnts (as marking duplicates using samtools is the same for hisat2 and bwa-mem2). Have anyone experienced similar problem before? 

I'm using default settings for all programs. For hisat2 I'm using SNP-aware reference  (grch38_snp) that suppose to align better SNP/INDEL containing reads.

**Comment by AndrewCarroll** [comment]
Hi @lpryszcz 

With respect to your aligner question, we have evaluated DeepVariant with BWA-MEM/BWA-MEM2, minimap2, DRAGEN, and the graph mapper Giraffe.

For mapping to a linear reference, we would recommend BWA-MEM/BWA-MEM2 or DRAGEN. DeepVariant is trained on BWA MEM data. Minimap2 will work, but has slightly lower accuracy. 

We have not evaluated HISAT2. If I had to guess, I would suspect that there might be split read mapping which is creating more candidates. The difference in speed that you encounter suggests that this has something to do with our candidate generation logic, as opposed to something about the neural network. This would probably require us to look at what in HISAT2 is causing an edge case with our candidate generation logic. It's possible there is a flag in HISAT2 that could be altered, but failing that it would probably take us some time to prioritize supporting HISAT2. 

We typically find that marking duplicates is not necessary, but it does not have a negative effect on accuracy to do so for typical coverages (25x-50x).

Thank you,
Andrew

**Comment by lpryszcz** [comment]
Hi Andrew, this answers all my questions! Since deepvariant is trained on bwa-mem2, I guess it's makes sense to stick to it. And it's good to know marking duplicates isn't necessary - this will save some time & electricity :) 
And big thanks to all people involved in deepvariant - it's truly groundbreaking tool! 
All the best, 
Leszek
