### ISSUE TITLE
Calling Germline variants in Tumor samples.

### ISSUE THREAD

**Issue by kokyriakidis** [google/deepvariant#466]
Hi everyone,

I wanted to ask if I could use DeepVariant with **Tumor Illumina samples** to accurately detect **Germline** variants? Can it accurately distinguish them from the Somatic ones? I am interested in Germline variants only.

Thank you for your time,
Konstantinos Kyriakidis

**Comment by pichuan** [comment]
Hi @kokyriakidis ,
I think it's worth giving it a try. But given DeepVariant isn't trained to tell somatic variants apart from germline ones, it is possible that DeepVariant might still end up calling some other somatic variants if they look similar enough.
