### ISSUE TITLE
Candidate variants

### ISSUE THREAD

**Issue by kokyriakidis** [google/deepvariant#467]
Hi!

Is it possible to get a vcf with **all candidate variants** only?

**Comment by danielecook** [comment]
@kokyriakidis currently we do not have a way of doing this, but we are working on an option to output candidate alleles in an upcoming release.

**Comment by pichuan** [comment]
If you want to directly take from the output of make_examples and create vcf from there, you can see this implementation here:
https://github.com/google/deepvariant/blob/r1.1/deepvariant/labeler/labeled_examples_to_vcf.py

Note that this currently requires the examples to have labels (i.e., generated with `training` mode). But you can relax the constraint here:
https://github.com/google/deepvariant/blob/r1.1/deepvariant/labeler/labeled_examples_to_vcf.py#L123-L127

But, also note that I'm not sure if this code properly deals with multi-allelics. So, waiting for the next release to use the new option that @danielecook mentioned might be a better solution.

**Comment by kokyriakidis** [comment]
Thanks a lot, both of you, for your reply. I will for the next release.
