### ISSUE TITLE
Check failed: collection_function Requires collection_function to contain an implementation

### ISSUE THREAD

**Issue by canna1998** [google/deepvariant#471]
**Describe the issue:**
I follow the quick start guidelines, and meet this error.

**Setup**
  - Operating system: MacBook Air (M1, 2020)
  - DeepVariant version: 19.03.14
  - Installation method (Docker, built from source, etc.): Docker  
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) quick start data 

**Steps to reproduce:**
  - Command:   sudo docker run  --platform linux/amd64 google/deepvariant /opt/deepvariant/bin/run_deepvariant --model_type=WGS --ref=/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta --reads=/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam --regions "chr20:10,000,000-10,010,000" --output_vcf=/quickstart-output/output.vcf.gz --output_gvcf=/quickstart-output/output.g.vcf.gz --intermediate_results_dir /quickstart-output/intermediate_results_dir --num_shards=1
  - Error trace: (if applicable)  I0712 04:14:17.889120 274906666752 run_deepvariant.py:313] Creating a directory for intermediate results in /quickstart-output/intermediate_results_dir

***** Intermediate results will be written to /quickstart-output/intermediate_results_dir in docker. ****

***** Running the command:*****
( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/quickstart-output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/quickstart-output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {} )

2021-07-12 04:14:21.223394: F tensorflow/core/lib/monitoring/collection_registry.cc:70] Check failed: collection_function Requires collection_function to contain an implementation.
qemu: uncaught target signal 6 (Aborted) - core dumped
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /quickstart-testdata/ucsc.hg19.chr20.unittest.fasta --reads /quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam --examples /quickstart-output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /quickstart-output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions chr20:10,000,000-10,010,000 --task 0

real	0m3.353s
user	0m3.542s
sys	0m0.718s
I0712 04:14:21.282448 274906666752 run_deepvariant.py:416] None
Traceback (most recent call last):
  File "/opt/deepvariant/bin/run_deepvariant.py", line 421, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/opt/deepvariant/bin/run_deepvariant.py", line 414, in main
    subprocess.check_call(command, shell=True, executable='/bin/bash')
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '( time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta" --reads "/quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam" --examples "/quickstart-output/intermediate_results_dir/make_examples.tfrecord@1.gz" --gvcf "/quickstart-output/intermediate_results_dir/gvcf.tfrecord@1.gz" --regions "chr20:10,000,000-10,010,000" --task {} )' returned non-zero exit status 250.

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?
no
**Any additional context:**

**Comment by gunjanbaid** [comment]
@canna1998 does the command used in our quickstart document for you? I noticed that your command is slightly different and is not mounting the necessary directories using `-v`. 

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \ **Replace this string with exactly one of the following [WGS,WES,PACBIO]**
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --num_shards=1 \ **How many cores the `make_examples` step uses. Change it to the number of CPU cores you have.**
```

**Comment by gunjanbaid** [comment]
@canna1998 I'm closing this issue out, but feel free to reopen if you have any other questions. Thanks!

**Comment by canna1998** [comment]
I finally run DeepVariant using docker in a ubuntu system, and it's very easy.  I guess DeepVariant is not suitable for Mac M1 due to its special chip...
