### ISSUE TITLE
Questions about GLnexus integration and DeepTrio training data for config evaluation

### ISSUE THREAD

**Issue by maca8e** [google/deepvariant#475]
Hello,

We have found that a known de novo variant was missed when using DeepTrio and GLnexus in our pipeline (WGS, hg38). I know that a similar issue has already been raised and appreciate the interesting discussion on this (i.e. https://github.com/google/deepvariant/issues/440), but to recap for others this was the result of two contributing factors:

1. DeepTrio being less confident in the de novo call for the proband than when DeepVariant is run in singleton mode on the proband. In our case, comparing the output VCFs from these two different runs we saw a reduction in the GQ score assigned to the variant from 56 when using DeepVariant in singleton mode, to only 10 when using DeepTrio.
2. GLnexus filtering, according to the `DeepVariantWGS` configuration we were using, removing our variant of interest in the case of DeepTrio due to the low likelihood assigned to the call.

To partly overcome this we are looking to switch the GLnexus configuration to `DeepVariant_unfiltered` as mentioned in https://github.com/google/deepvariant/issues/440. However we would like to further evaluate this change on a known truth set to determine the increase in false-positive calls (similar to [1] with DV-GLN-NOMOD vs DV-GLN-OPT, but for DeepTrio instead... because from what I understand that paper evaluated DeepVariant).

I have seen that all three GIAB/NIST benchmark trios have been used as training data for DeepTrio so would like to ask:

1. Were all chromosomes from these trios used to train the DeepTrio models? I believe the DeepVariant WGS training data excluded chr20-22, and the deeptrio test data uses HG001 Chr20 [2], so I assume chr20-22 were excluded from the Deeptrio models for each of the trios too and would be suitable for testing? Or any alternative suggestions for this?
2. I understand that the DeepTrio docs aren't officially released yet, but would it be possible please to provide an overview of the workings and differences between the Child and Parent models for DeepTrio? Is there a reason why the HG001/NA12891/NA12892 trios were used as training for the child model but not the parent model?

<br>

Many thanks,
Macabe.

<br>

![image](https://user-images.githubusercontent.com/37773554/128098808-740a1ab0-a6af-452f-8bed-d1f4ba0ceb80.png)
Current DeepTrio training info (likely typo for Ashkenazim trio, cf. HG002/HG00**3**/HG004)

[1] https://academic.oup.com/bioinformatics/article/36/24/5582/6064144 
[2] https://github.com/google/deepvariant/tree/r1.2/deeptrio/testdata/input

**Comment by AndrewCarroll** [comment]
Hi @maca8e 

You are correct that DeepVariant_unfiltered is a preferable preset for DeepTrio calling. We had meant to update that in the case study documentation for the most recent release, and failing to do so is an oversight that we will correct. The DeepTrio paper does describe the unfiltered preset as preferable, and it should be reflected here. 

With respect to a reference for DeepTrio's workings, have you seen the [DeepTrio preprint](https://www.biorxiv.org/content/10.1101/2021.04.05.438434v1)? If so, is there an item you would like described in greater detail.

With respect to why NA12891/NA12892 are not used for training the parent model, this is simply because NIST does not have a truth set for these samples, while a truthset from NIST is available for HG001.

**Comment by AndrewCarroll** [comment]
Hi @maca8e 

To update this issue, we have now made the change to DeepVariant_unfiltered GLnexus preset in the DeepTrio documentation. Thank you again for pointing this out.

**Comment by maca8e** [comment]
Hi @AndrewCarroll 

Thanks for pointing out the preprint, I hadn't come across that yet so it helped a great deal understanding the differences between the parent-child models and the training. Glad to hear that the `DeepVariant_unfiltered` config is now the recommended preset.

Many thanks,
Macabe
