### ISSUE TITLE
Deal with multiple samples

### ISSUE THREAD

**Issue by a7032018** [google/deepvariant#48]
Hi,
I have couple dozens of samples (bam files) to do the phylogenetic analysis. Do I treat the sample individually and merge the VCF files afterward, or there is something like SAMtools mpile to merge bam files before feeding to deepvariant workflow?

Thanks for answering this question

**Comment by cmclean** [comment]
Process each sample individually, and then merge the results.

When you process each sample, be sure to create gVCF outputs (see https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-gvcf-support.md for details). The single-sample gVCF files can then be merged into a single cohort-level VCF using existing tools (see https://github.com/google/deepvariant/issues/45#issuecomment-363913008 for our current thoughts on merging tools).

**Comment by a7032018** [comment]
Thanks!
