### ISSUE TITLE
multiallele detection

### ISSUE THREAD

**Issue by yanyang1989** [google/deepvariant#480]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.2/docs/FAQ.md**:

**Describe the issue:**
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system:
  - DeepVariant version:
  - Installation method (Docker, built from source, etc.):
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
can deepvariant detect multiallelic positions, for example, Ref is A, and Alt is C, G. And the GT is denoted as 1/2

**Comment by pichuan** [comment]
Hi @yanyang1989 ,
Yes! :)

**Comment by pichuan** [comment]
If you're curious about how the underlying multiallelic variants are represented, you can see the "Multiallelic variants" section in https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/ .
Another good blog post is https://blog.dnanexus.com/2019-02-19-deep-dive-into-deepvariant/.

But to answer your question - Yes, DeepVariant is designed to be able to make calls like the one that you described, assuming there's signal form the BAM file to support it.

Closing this now. Feel free to reopen if you have more questions.
