### ISSUE TITLE
Feature request: bam csi index support

### ISSUE THREAD

**Issue by duceppemo** [google/deepvariant#481]
I would like to use DeppVariant on organisms with chromosomes larger than 512Mbp. Currently, DeepVariant only supports `.bai` bam indexes.

**Comment by pichuan** [comment]
Hi @duceppemo , can you clarify what error message you were seeing when you try with a BAM file with `.csi` indices?

I just tested with data from https://github.com/google/deepvariant/blob/r1.2/docs/deepvariant-quick-start.md

And I deliberately deleted the `.bai` index file and created a `.csi` instead:

```
$ rm -f quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam.bai
$ samtools index -c quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam
$ ls quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam*
quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam
quickstart-testdata/NA12878_S1.chr20.10_10p1mb.bam.csi
```

After that, it seems like I was still able to go through the Quick Start steps without any issues.

DeepVariant is using htslib to read BAM files, and it seems like `.csi` is already supported there. Can you give me an reproducible example, if you're seeing any issues?

Thanks!

**Comment by duceppemo** [comment]
You are totally right! I should have tested it before creating an issue...

I also tested DeepVariant using `cram` and `crai` index files and it worked also. Maybe that information could be explicitly added to the documentation to prevent other (lazy) users to report same "issues".

Thanks a million!
