### ISSUE TITLE
Parallel this job failed

### ISSUE THREAD

**Issue by tova-hallas** [google/deepvariant#483]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.2/docs/FAQ.md**: yes

**Describe the issue:**
I have tried to run in my personal computer the WES deepvariant case. However I get the following error:
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/wes_deepvarfast_38.sorted.bam --examples /output/inter_res/make_examples.tfrecord@16.gz --gvcf /output/inter_res/gvcf.tfrecord@16.gz --regions /input/wes2_38_3col.sorted.bed --task 2

I have ran the following command with a successful docker installation:
	BIN_VERSION="1.2.0"

	sudo docker run \
  	-v "${PWD}/input":"/input" \
  	-v "${PWD}/output":"/output" \
  	-v "${PWD}/reference":"/reference" \
  	google/deepvariant:"${BIN_VERSION}" \
  	/opt/deepvariant/bin/run_deepvariant \
  	--model_type WES \
  	--ref /reference/GRCh38_no_alt_analysis_set.fasta \
  	--reads /input/wes_deepvarfast_38.sorted.bam \
	--regions /input/wes2_38_3col.sorted.bed \
  	--output_vcf /output/output_38.vcf.gz \
  	--output_gvcf /output/output_38.g.vcf.gz \
  	--num_shards=8 \
  	--intermediate_results_dir /output/intermediate_results_dir
with bam and bed files I've created of my own sample (paired end sequencing result of a human genome). The alignment of the bam file was successful (used bwa and samtools) and created the bed file out of the bam file by bedtools. 

I've further checked FAQ and tried to run the following command, to better understand what is the error or where it fails:
	BIN_VERSION="1.2.0"

	sudo docker run
	-v "${PWD}/input":"/input"
	-v "${PWD}/output":"/output"
	-v "${PWD}/reference":"/reference"
	google/deepvariant:"${BIN_VERSION}"
	/opt/deepvariant/bin/make_examples
	--mode calling
	--ref /reference/GRCh38_no_alt_analysis_set.fasta
	--reads /input/wes_deepvarfast_38.sorted.bam
	--examples "/output/make_examples.tfrecord@1.gz"
	--gvcf "/output/gvcf.tfrecord@1.gz"
	--regions "/input/wes2_38_3col.sorted.bed" \

However I get no error message, some lines of this kind are printed: "Adding interval chr1:1523790-1523940 to intervaltree" and than it finishes without creating any files.

Any Idea of what happens and how can I make deepvariant work on my sample and create a vcf file?

(**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start? Yes it works)

**Comment by MariaNattestad** [comment]
It might have something to do with the `--regions`. Can you try just running on just one small region, something like '--regions="chr20:10000000-10010000"`?
What was the bedtools command you used for making that bed file?
The bed file to use for `--regions` in a WES run should be the exome regions from the capture protocol.

**Comment by tova-hallas** [comment]
Hi Maria,
Thank you very much for your answer, this is exactly what I've thought and tried to do. For a specific region (for example: "chr15:98707564-98707715") it worked well and produced a vcf file.

For the bed file I've used the command:
bedtools bamtobed [OPTIONS] -i <BAM>
It extracted the regions from the bam file and than I removed the last three columns (bedtools creates bed file with 6 columns)

The problem is that when I run the command  with the exome regions from the capture protocol it also not working for me
("idt_capture_novogene.grch38.bed"). Again I get the error:
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/wes_deepvarfast_38.sorted.bam --examples /output/inter_res/make_examples.tfrecord@8.gz --gvcf /output/inter_res/gvcf.tfrecord@8.gz --regions /input/idt_capture_novogene.grch38.bed --task 1

**Comment by tova-hallas** [comment]
Another test-
I've ran the WES exactly like it is with your test files (fasts bam and bed) and again I get this same error: 
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@8.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@8.gz --regions /input/idt_capture_novogene.grch38.bed --task 3

it seems that works for me only at a specific region and not on bed files.

**Comment by MariaNattestad** [comment]
I'm happy to hear you have enjoyed my YouTube videos :)

Hmm, there should be a more informative error message above the one that says "parallel: This job failed". If you don't see it, try running it without parallel and without the "@" sharding in the output file names.

I wouldn't recommend using `bedtools bamtobed` to generate the bed file, even if other ways aren't working. That is because it would generate a region for every read, which is definitely not the --regions DeepVariant is expecting! Since you do have the exome capture bed file, then let's get that working instead :)

Also, does it work for one of the regions in the `idt_capture_novogene.grch38.bed` file?

**Comment by tova-hallas** [comment]
You are right I've found the error: "[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2021-09-11 06:41:18.592077: F ./third_party/nucleus/vendor/statusor.h:231] Non-OK-status: status_ status: Invalid argument: Couldn't fetch bases for reference_name: "chr1" start: 4655405 end: 4655474
Fatal Python error: Aborted" few lines above the parallel error. I get this error with the original files of the WES run. (parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@1.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@1.gz --regions /input/idt_capture_novogene.grch38.bed --task 0)

**Comment by MariaNattestad** [comment]
if you do `samtools faidx` with "chr1:4655405-4655474" on your reference fasta file, what happens?

**Comment by tova-hallas** [comment]
my command:
samtools faidx GRCh38_no_alt_analysis_set.fasta "chr1:4655405-4655474"
I get this:
>chr1:4655405-4655474
CCCGCTCCCCGAAACGTGACCATGTGGATTCAACAGCTTTTAGGACTCAGGTGAGCGACC
CGGCCGGCGC

**Comment by tova-hallas** [comment]
T

> I'm happy to hear you have enjoyed my YouTube videos :)
> 
> Hmm, there should be a more informative error message above the one that says "parallel: This job failed". If you don't see it, try running it without parallel and without the "@" sharding in the output file names.
> 
> I wouldn't recommend using `bedtools bamtobed` to generate the bed file, even if other ways aren't working. That is because it would generate a region for every read, which is definitely not the --regions DeepVariant is expecting! Since you do have the exome capture bed file, then let's get that working instead :)
> 
> Also, does it work for one of the regions in the `idt_capture_novogene.grch38.bed` file?

for your last question here I've tried to run with region "chr1:450739-451678" from the `idt_capture_novogene.grch38.bed` file and it produced vcf both for the test bam file in the WES run and for my personal bam file.

**Comment by tova-hallas** [comment]
A summary of last trials:
1. Downloaded fasta file again from repository (since it had an error with chr1:4655405-4655474)
2. Ran again the WES run with the original files 
3. Got again the "parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /reference/GRCh38_no_alt_analysis_set.fasta --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam --examples /output/intermediate_results_dir/make_examples.tfrecord@8.gz --gvcf /output/intermediate_results_dir/gvcf.tfrecord@8.gz --regions /input/idt_capture_novogene.grch38.bed --task 3" Error without the more informative error message.
4. Ran again the command without num shards flag:
BIN_VERSION="1.2.0"

  ```
sudo docker run \
    -v "${PWD}/input":"/input" \
    -v "${PWD}/output":"/output" \
    -v "${PWD}/reference":"/reference" \
    google/deepvariant:"${BIN_VERSION}" \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type WES \
    --ref /reference/GRCh38_no_alt_analysis_set.fasta \
    --reads /input/HG003.novaseq.wes_idt.100x.dedup.bam \
    --regions /input/idt_capture_novogene.grch38.bed \
    --output_vcf /output/HG003.output.vcf.gz \
    --output_gvcf /output/HG003.output.g.vcf.gz \
    --intermediate_results_dir /output/intermediate_results_dir
```
5.  It ran and created only three intermediate files: call_variants_output.tfrecord, gvcf.tfrecord-00000-of-00001.gz, make_examples.tfrecord-00000-of-00001.gz  without any Error message. I'm copying the last lines here:

```
/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/engine/base_layer_v1.py:1692: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  warnings.warn('`layer.apply` is deprecated and '
INFO:tensorflow:Done calling model_fn.
I0911 15:27:04.863512 139825053296448 estimator.py:1164] Done calling model_fn.
INFO:tensorflow:Graph was finalized.
I0911 15:27:05.510090 139825053296448 monitored_session.py:247] Graph was finalized.
INFO:tensorflow:Restoring parameters from /opt/models/wes/model.ckpt
I0911 15:27:05.510811 139825053296448 saver.py:1298] Restoring parameters from /opt/models/wes/model.ckpt
INFO:tensorflow:Running local_init_op.
I0911 15:27:06.189059 139825053296448 session_manager.py:531] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0911 15:27:06.217319 139825053296448 session_manager.py:534] Done running local_init_op.
2021-09-11 15:27:06.477138: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
INFO:tensorflow:Reloading EMA...
I0911 15:27:06.498517 139825053296448 modeling.py:416] Reloading EMA...
INFO:tensorflow:Restoring parameters from /opt/models/wes/model.ckpt
I0911 15:27:06.499074 139825053296448 saver.py:1298] Restoring parameters from /opt/models/wes/model.ckpt
I0911 15:27:17.529355 139825053296448 call_variants.py:452] Processed 1 examples in 1 batches [1611.487 sec per 100]
```

```
real	0m53.331s
user	0m35.346s
sys	0m22.537s
```
It seems there is an error that I don't find or understand

**Comment by MariaNattestad** [comment]
## When there isn't an error message at all:
Is it possible that it could be running out of memory? That could be why running on an individual region succeeds while it fails on the whole bed file. Out of memory issues are hard to catch because they don't result in error messages. I ran the exome case study myself just now and it worked fine. In terms of compute resources, our testing system goes as low as "n1-standard-8" on Google Cloud, which is 8 vCPUs and 30 GB of memory. If your setup is less than 30GB of memory that might be the cause of the issue. Reducing the number of shards to 1 might help, but if it doesn't, you might just need to use a machine with more resources.

## When faidx also fails
Check that the fasta looks okay and perhaps redo the `samtools faidx` that created the `.fai` in the first place just in case. Is the "chr1" the exact sequence name of one the sequences in the fasta?

**Comment by tova-hallas** [comment]
Thank you very much for your answer and help. I looked out at the memory of the docker and increased it to 32 GB. It seems that it runs further and creates more intermediate files. However I keep getting errors such as: 
```
I0912 07:26:29.443329 140104987477824 make_examples_core.py:236] Task 5/16: 200 candidates (216 examples) [38.25s elapsed]
[E::fai_retrieve] Failed to retrieve block: unexpected end of file
2021-09-12 07:26:29.590972: F ./third_party/nucleus/vendor/statusor.h:231] Non-OK-status: status_ status: Invalid argument: Couldn't fetch bases for reference_name: "chr1" start: 184974281 end: 184974376
Fatal Python error: Aborted 
```
I delete files and download again however it seems to fall all over again each time on different positions. Do you know what can I do to prevent these errors?

Many thanks

**Comment by tova-hallas** [comment]
Thank you so much Maria! It finally worked. I've changed the docker memory settings to be 32 GB, it was indeed the problem. The fasta file still had problems of EOF each time at different position, however I've downloaded it again and again until it finally worked !

Thank you again for the support :) !

**Comment by MariaNattestad** [comment]
Great! Glad to hear you got it working!
