### ISSUE TITLE
postprocess variants failed !!!

### ISSUE THREAD

**Issue by leedchou** [google/deepvariant#485]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.2/docs/FAQ.md**: **YES**

**Describe the issue:**

Manually selected regions (a single region is formed by a locus extending 500 bp to both sides) were used in my project to make examples, and it was also succeed in calling variants. However, when I running postprocess_variants, something went wrong. I check the log, and I guess it was related to the wrong "call_variant_outputs". So I printed one "call_variant_outputs" out of the whole tfrecord, and found out there are several repeated variant in one call. Where did I go wrong?

**The log file is attached.**
[postprocess_variants.log](https://github.com/google/deepvariant/files/7149887/postprocess_variants.log)

**Setup**
  - Operating system: ubuntu **16**
  - DeepVariant version: **0.7.0**
  - Installation method (Docker, built from source, etc.): **built from source**
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) **NO**

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

> W0912 23:51:01.891268 140429229119232 postprocess_variants.py:331] Alt allele indices found from call_variants_outputs for variant reference_bases: "C"
alternate_bases: "A"
calls {
  info {
    key: "AD"
    value {
      values {
        int_value: 17
      }
      values {
        int_value: 4
      }
    }
  }
  info {
    key: "DP"
    value {
      values {
        int_value: 21
      }
    }
  }
  info {
    key: "VAF"
    value {
      values {
        number_value: 0.190476190476
      }
    }
  }
  genotype: -1
  genotype: -1
  call_set_name: "XY406-1"
}
end: 10147
reference_name: "1"
start: 10146
 is [[0], [0], [0]], which is invalid.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 874, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 851, in main
    header=header)
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 595, in write_variants_to_vcf
    for variant in variant_generator:
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/haplotypes.py", line 91, in maybe_resolve_conflicting_variants
    for overlapping_candidates in _group_overlapping_variants(sorted_variants):
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/haplotypes.py", line 110, in _group_overlapping_variants
    for variant in sorted_variants:
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 631, in _transform_call_variants_output_to_variants
    outputs, multi_allelic_qual_filter)
  File "/tmp/Bazel.runfiles_4jh3iyl1/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 559, in merge_predictions
    raise ValueError('`call_variants_outputs` did not pass sanity check.')
ValueError: `call_variants_outputs` did not pass sanity check.

**Does the quick start test work on your system?**
YES

**Comment by MariaNattestad** [comment]
Can you include all the commands you ran? Also can you try with the latest version of DeepVariant?

**Comment by leedchou** [comment]
Hi, @MariaNattestad 

Thank you very much for your kind advice. I have figured out what caused this error and it did works.

Additionally, I don't understand how DeepVariant defines those candidate variants when making examples. I know it is implemented by the file "allelecounter.cilf", but I get limited information from this file. 
Could you please tell me more information about the candidate variants part?

Thank you again for your help.

**Comment by akolesnikov** [comment]
For the detailed explanation of how candidates are generated please see https://www.biorxiv.org/content/10.1101/092890v6.full.pdf (starting at page 14). 
Also, main code is in allelecounter.cc and variant_calling.cc.

**Comment by leedchou** [comment]
Soga, thank you@akolesnikov

**Comment by MariaNattestad** [comment]
@leedchou can you share what you figured out was the cause of the error?
