### ISSUE TITLE
Support for Multi-nucleotide Variant (MNV) Calling

### ISSUE THREAD

**Issue by maca8e** [google/deepvariant#486]
Hello,

We noticed that adjacent variants of the same haplotype (i.e. MNVs) are being called as separate variants in the DeepVariant and DeepTrio outputs with VCF and gVCF files. During downstream processing these MNVs are then treated as two individual SNVs at two different loci, leading to faulty assessments. 

For example two variants for a site of interest (reference TCG -> Serine) were separated between two lines in the DeepVariant/DeepTrio output VCF and then categorised as containing a nonsynonymous (T**G**G -> Tryptophan) and synonymous mutation (TC**A** -> Serine). Whereas the correct and desired way to handle this, at least for us but I imagine others too, would seem to be to recognise both mutations on a single line in the VCF as a combined substitution, which could then be identified as resulting in a stopgain (T**GA** -> Nonsense mutation).

Are there plans to support these MNV calls in the DeepVariant/DeepTrio outputs? Or alternatively are there any current post-processing approaches that you may be using and can recommend to handle these cases? Can understand these may be challenging to manage in some aspects but could be important to flag given some recent literature around this topic.

For reference this was using hg38 with WGS. We initially identified this using the original DeepTrio release (docker image deeptrio:1.0.1rc), but then also using the most recent DeepVariant release (via docker, v1.2). We also tested this to see whether the change to the unfiltered GLnexus config could be contributing to this for processing of DeepTrio gVCFs due to the joint genotyping parameter, but reverting back to the WGS config did not result in a merged MNV in this instance. 

Many thanks,
Macabe.

**Comment by AndrewCarroll** [comment]
Hi @maca8e,

Thank you for your question and for noticing this. 

Yes, the way that DeepVariant generates candidate variants does not directly represent adjacent substitution events as a single MNV event. This can result in some sub-optimal representations in the VCF.

We have flagged this as an area for improvement, but we have not been able to prioritize this area for awhile. I think that fixing this in the most principled way (at the level of candidate generation) would be a fair amount of work. The fastest solution would be post-calling phasing and allele reconciliation. I have not sufficiently looked into this, but I will do so and see if I have any recommendations to make.

**Comment by maca8e** [comment]
Hi @AndrewCarroll, 

Thanks for your response and yes indeed, imagine it could take some significant reworking. Appreciate any thoughts you might have on it.

**Comment by Ahhgust** [comment]
Apologies in advance for inviting myself into the conversation. I think it's worth mentioning that while there are merits to doing MNV calling, the use-case given (calling amino acid variation from SNPs) isn't the greatest. There's no guarantee that codons occur as triplets in the genome (though they tend to, they can also get split across exons). which suggests that MNV calling doesn't actually solve the problem in general. Phase-aware consequence predictors (bcftools csq) should, on the other hand, work just fine (neglecting phasing errors of course).

FWIW, we use the following pipeline: deepvariant or gatk4 -> whatshap -> shapeit4 -> bcftools csq to predict protein polymorphisms (or really, whole proteomes from whole genomes) and that approach should work in this case too.

To be clear, having MNV calling would make an excellent addition to DeepVariant, it just may not be a total solution to the problem posed.
-August

**Comment by pichuan** [comment]
Thanks all for your thoughts.
Like @AndrewCarroll mentioned, we still won't be able to prioritize this in the near future. I'll close this for now, and I've opened an internal tracker for this.

**Comment by CaptainLabMan** [comment]
Are there any updates on this? It's been 5 years.

**Comment by AndrewCarroll** [comment]
Hi @CaptainLabMan 

For long reads, DeepVariant now phases the output variant calls, which allows the resolution of MNPs by haplotype. We have a prototype of this for short reads as well, and it may go out in the next release.

Do you consider a phased VCF output to be sufficient for this purpose?

Thank you,
Andrew
