### ISSUE TITLE
How do I control the number of threads for call_variants?

### ISSUE THREAD

**Issue by oskarvid** [google/deepvariant#49]
I'm trying to build a scatter gather implementation of make_calls -> call_variants -> post_processing, without using GNU parallel, and since multiple shards of call_variants, even with num_readers set to 1, increases the system load well beyond the number of cores, I'd like to try to limit this to a 1:1 ratio where one shard produces a system load of 1. Is this possible?

This is essentially what my pipeline looks like today: https://github.com/oskarvid/wdl_deepvariant/blob/master/deepvar-simple-SG.wdl
I say essentially because I've made insignificant changes, like added --num_readers for example. 

One way would be to try to combine all tfrecord files into one, because wdl cannot use your method of using all output files from make_calls as input files for call_variants, inputFile@#shards.gz doesn't compute for wdl, and using wdl's normal way of handling multiple input files, i.e "--examples ${sep=" --examples " InputFile}" doesn't work either since call_variants only takes the last "--examples" as input when there are many "--examples" in the command.

Regarding combining the tfrecord files before they're used as input for call_variants, I'm not familiar enough with tensorflow to know if it's at all possible, and a quick google search didn't return anything fruitful. Is it possible to combine many tfrecord files into one?

Is it easier to try to limit the number of threads per process instead of trying to combine the tfrecord files? Or is there a third method that solves this problem better?

And thanks for a great tool!

**Comment by pgrosu** [comment]
Hi Oskar,

Since your WDL workflow is using Docker, the simplest approach is to include a Docker-specific argument for `--cpuset-cpus`, or change the Session configuration which I've detailed at, the following location:

https://github.com/google/deepvariant/issues/42#issuecomment-360510853

For information regarding the `--cpuset-cpus` here's a reference:

https://docs.docker.com/config/containers/resource_constraints/#configure-the-default-cfs-scheduler

There are many ways to change DeepVariant, but I think this will will get you the quickest results for the issue you're facing.

Hope it helps,
Paul

**Comment by oskarvid** [comment]
Is it possible to merge the tfrecords files though?

**Comment by pgrosu** [comment]
Well, what do you think might be happening at this line in the code :)

https://github.com/google/deepvariant/blob/r0.5/deepvariant/call_variants.py#L170

Here's a link describing the `TFRecordDataset` semantics:

https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset

`p

**Comment by pichuan** [comment]
If you're looking for simply merging the tfrecord files (without having to touch Python code) to one, you can actually just concatenate tfrecord files together.
Something like:
`cat shard.*.tfrecord > merged.tfrecord`

or you can also concatenate zipped tfrecord files:
`cat shard.*.tfrecord.gz > merged.tfrecord.gz`
will work.

**Comment by rpoplin** [comment]
Great! Looks like this issue might be resolved but let us know if there is anything else we can help with.
