### ISSUE TITLE
confused for SNP INDEL result

### ISSUE THREAD

**Issue by gevin-MB** [google/deepvariant#494]
Confused while checking SNP VCF file from deepvariant：
the number of reads supporting ALT is more than REF, but the genotype is 0/0. WHY? 
![image](https://user-images.githubusercontent.com/32149026/143169794-d398c8de-0dff-496f-91f3-ff088d309814.png)
even, the number of reads supporting ALT  is 9 and REF is 0, but the genotype is 0/0.
![image](https://user-images.githubusercontent.com/32149026/143170163-228821a1-509c-48ec-8528-57c1b8af5e5b.png)

**Comment by pichuan** [comment]
Hi @gevin-MB , 

can you take a look at the "Missing variants where a candidate is generated:" section in [this FAQ question](https://github.com/google/deepvariant/blob/r1.2/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data), and see if that answers your question?

If not, feel free to follow up here again. Thanks!

**Comment by Suke-fudan** [comment]
I have similiar questions.
When I ran DeepVariant for each sample(illumina,WES data) to generate gVCF and ran GLnexus to merge gVCFs,I found the genotype of some SNPs in  some samples like this:  GT:DP:AD:GQ:PL:RNC ./.:9:9,0:1:2,0,212:II (DP=9,AD=9,0,but the genotype is ./.,and RNC=II).
The normal genotypes like this:
1/1:89:0,89:27:38,28,0:..
0/0:0:0,0:1:0,0,0:..
0/0:4:4,0:12:0,15,149:..

**Comment by Suke-fudan** [comment]
I found more cofusing genotypes:
./.:136:116,20:5:0,3,28:II  (0/1?)

./.:137:.:.:0,0,0,0,0,0:UU   (DP=137,but the ref reads and alt reads is .)

./.:137:.,0:8:0,0,0:11   (DP=137,but the ref readsis .)

./.:137:.:.:0,0,0:OO   

./.:137:2,129:5:0,13,4:II  (1/1?)

./.:137:86,50:6:0,4,39:II  (0/1?)

./.:137:99,38:6:0,4,31:II  (0/1?)

./.:13:10,3:4:0,1,26:II

./.:141:9,132:3:0,12,0:II  (1/1?)

How can I deal with the situation(RNC= II  OO  UU...)? Many thanks for your help!

**Comment by pichuan** [comment]
Hi @Suke-fudan , 
to answer your question about `./.`, please refer to https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md , specifically this section and the first sentence:
"Missing variants where a candidate is generated:"

As explained there, DeepVariant makes a prediction which is probabilistic, based on the evidence it has, it might not always be as confident about its prediction. Our postprocessing logic can change a less confident call to a `./.` call. See this flag here:
https://github.com/google/deepvariant/blob/r1.3/deepvariant/postprocess_variants.py#L86-L89

As for "RNC" , I don't think that comes from DeepVariant. I wonder if it comes from GLnexus? But I'm not sure actually.

**Comment by Suke-fudan** [comment]
##FORMAT=<ID=RNC,Number=2,Type=Character,Description="Reason for No Call in GT: . = n/a, M = Missing data, P = Partial data, I = gVCF input site is non-called, D = insufficient Depth of coverage, - = unrepresentable overlapping deletion, L = Lost/unrepresentable allele (other than deletion), U = multiple Unphased variants present, O = multiple Overlapping variants present, 1 = site is Monoallelic, no assertion about presence of REF or ALT allele">

**Comment by Suke-fudan** [comment]
<html>
<body>
<h3 style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Reasons for No Call</h3><p style="color: rgb(0, 0, 0); font-family: &quot;Microsoft YaHei&quot;; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">All entries in the GLnexus pVCF include a Reason for No Call (RNC) field, which is filled in if either GT entry is not called (.). The possible values of RNC include:</p>

Code | Reason | Explanation
-- | -- | --
. | N/A | corresponding allele is called
M | Missing data | input (gVCF) had no data at this genome position
P | Partial data | input only partially covered this genome position
D | Depth | read depth too low to call
– | deletion | sample carries a deletion allele that couldn't be unified into this site; there may be more information in overlapping monoallelic site(s).
L | Lost allele | ^ but other than deletion allele
U | Unphased variants | sample carries multiple non-overlapping variants at this position*, whose phase is not known, so the diploid genotype cannot be called safely. There may be more information in overlapping monoallelic site(s).
O | Overlapping variants | sample carries multiple overlapping variants at this position, so the diploid genotype cannot be called safely. (GLnexus does deal with several common, but not all, cases of overlapping variants output by gVCF callers.) There may be more information in overlapping monoallelic site(s).
1 | monoallelic | this is a monoallelic site; no assertion about presence/absence of any allele here


</body>
</html>

**Comment by pichuan** [comment]
Hi @Suke-fudan ,
Thanks for finding where RNC comes from.

For `./.` , it means that our classifier wasn't as confident about the call. The way that the classifier makes the probabilistic call is based on all the information from the input signals that we encoded into the channels. You can see the blog post [Looking Through DeepVariant's Eyes](https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/) for more details on that topic.

In a way, you can think of the decision for us to label it as `./.` as a heuristic. We could have exposed the original call (which is 0/0), but the probability given to 0/0 wasn't high enough, so we decide to give it `./.`. In this case, if you like, you could have a postprocessing step that takes all the `./.` calls, and make a different decision, if you decide that there are overwhelming evidence to be another genotype. If you do decide to go with such a postprocessing step, I'd recommend that you evaluate the whole pipeline (including your postprocessing step) to make sure the accuracy is better systematically.

I hope this helps. Feel free to follow up.
