### ISSUE TITLE
Support Request: retraining final layer

### ISSUE THREAD

**Issue by ed5152** [google/deepvariant#495]
I am looking to retrain just the final classification layer of the model (DeepVariant WGS) and add an extra class, so the model outputs 4 probabilities instead of the usual 3. 

I have been looking at these instructions: https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-training-case-study.md but they don't quite correspond to my use case scenario.

Would someone be able to point me towards the scripts/functions of relevance please?
Thank you

**Comment by danielecook** [comment]
Hi @ed5152 - adding an additional class may require a substantial amount of work.

You will likely need to update the make_examples step, the training/inference step, and the postprocessing step. Can you provide additional context for what you are trying to do?

[make_examples_core.py](https://github.com/google/deepvariant/blob/r1.2/deepvariant/make_examples_core.py#L1504-L1519) contains the logic for generating examples. You would modify the code to allow for an additional class here.

Then you would need to subclass the DeepVariant model to modify the final layer and add an extra output.

https://github.com/google/deepvariant/blob/b6a91d5f8514cc09a4f059b9980ac80043a899c3/deepvariant/modeling.py#L420-L426

Finally, you would need to update [postprocess_variants.py](https://github.com/google/deepvariant/blob/r1.2/deepvariant/postprocess_variants.py) to handle an additional class output.

**Comment by MariaNattestad** [comment]
For the part of changing the output classes, we have a parameter in make_examples that enables that without code changes: look for "customized_classes" in https://github.com/google/deepvariant/blob/r1.2/deepvariant/make_examples_options.py

However, I don't think we have a set way to enable retraining just the final layer of the model, although @pichuan might know more.

**Comment by pichuan** [comment]
Hi @ed5152 ,
Thanks for your question.
Our codebase pretty much hardcoded the number of classes as 3. Even the customized_classes option is currently just a way to fill the labels with different fields in the truth VCF, but still assumes 3 classes.
In the future we might support more flexible number of classes, but this is not currently on our roadmap.
Our codebase also doesn't currently support just retraining the final layer.

Our codebase uses an old library https://github.com/google-research/tf-slim . It is possible that you could modify our codebase to make it happen, but this is outside of our support for DeepVariant.
