### ISSUE TITLE
Variant Calling in Low-Complexity Regions

### ISSUE THREAD

**Issue by zhoudreames** [google/deepvariant#498]
there are some variants where located in Low-Complexity Regions can not be identified by using DeepVariant Illmina and hifi mode . how to solve it ？ thanks ~
![image](https://user-images.githubusercontent.com/54714639/145783707-493a6c3d-c1ca-4f4e-9981-1b7631e165cb.png)

**Comment by pichuan** [comment]
Hi @zhoudreames ,
Can you read this section and see if it answers your question? https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

In this particular case, many of the reads seem to have low mapping quality. DeepVariant has a min_maping_quality flag which can be lowered. Depending on the sequencer and the mapping software, if you think lowering it from the default (5) to a lower number makes sense, you can try adding the --min_mapping_quality flag to your make_examples step.

**Comment by zhoudreames** [comment]
thanks~
