### ISSUE TITLE
'/tmp/tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl'

### ISSUE THREAD

**Issue by student-t** [google/deepvariant#5]
I download the source code and then simply ran:

`./build-prereq.sh`

I got the error: '/tmp/tensorflow-1.4.1.deepvariant_gcp-cp27-none-linux_x86_64.whl'.

![screen shot 2017-12-07 at 11 24 47 am](https://user-images.githubusercontent.com/7627987/33692414-469c85d2-db41-11e7-909e-1a5b53356481.png)

**Comment by depristo** [comment]
Unfortunately it's not clear from your post what might be going wrong here. Is this on a clean install of Ubuntu 16? We'd recommend starting there first to make sure everything is working and then moving to whatever environment you are running on.

**Comment by scott7z** [comment]
I think you are getting the wrong "gsutil".   There is an Ubuntu package with that name and matching error messages, but what you need is the "Google Cloud SDK" (see https://cloud.google.com/sdk/downloads).

**Comment by rpoplin** [comment]
We added a note about needing the `gsutil` from Google Cloud SDK to our [Build and Test guide](https://github.com/google/deepvariant/blob/r0.4/docs/deepvariant-build-test.md). Let us know if you are still having issues.
