### ISSUE TITLE
A low number of calls generated

### ISSUE THREAD

**Issue by kriestof** [google/deepvariant#501]
**Describe the issue:**
When calling I get a low number of records in a vcf file (20-40k variants). In comparison with GATK there are at last 10 times less variants generated. Also, it is much less than from 1 thousand genomes deepvariant dataset truncated to the same exome region - 1.7 mln records.

**Setup**
  - Operating system:
  CentoOS 7
  - DeepVariant version:
  1.3.0
  - Installation method (Docker, built from source, etc.):
  podman/singularity
  - Type of data:
The data are human's whole exome sequences from Illumina. As a reference I use hg38 with alt contigs. I use truseq v1.2 exome bed file. Besides using bwa-mem2, samtools merge and sort there is not much preprocessing.

**Steps to reproduce:**
  - Command:
```
/opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --ref=\$PWD/$idxbase \
  --reads=\$PWD/${sample_id}.bam \
  --regions=\$PWD/$bed_file \
  --output_vcf=\$PWD/${sample_id}.vcf.gz \
  --output_gvcf=\$PWD/${sample_id}.g.vcf.gz \
  --num_shards=${task.cpus}

```

I also used glnexus
```
glnexus_cli 
  --bed /in/truseq-dna-exome-targeted-regions-manifest-v1-2.bed 
  --config DeepVariantWES /in/vcf_deepvariant/*.g.vcf.gz > merged.bcf
```

**Comment by kriestof** [comment]
I've just discovered that when I change glnexus config from `DeepVariantWES` to `DeepVariant` (which is the case for 1KG) I got around 115k calls which seems more probable in relation to 1kg 1.7 mln from 3500 samples. Anyway, would be nice to hear if it sounds reasonable for exome.

**Comment by pichuan** [comment]
Hi @kriestof 
Sorry for the delay of response, we are off work until tomorrow so we haven't responded.

If you can help with a few clarifications that will be great:
1. I don't expect the variants in the VCF from DeepVariant to be 10x less. Are you seeing 10x less variants even just from the VCF files?
2. You later mentioned "when I change glnexus config from DeepVariantWES to DeepVariant (which is the case for 1KG) I got around 115k calls from 75 samples (same ethnicity)" -- how many calls did you get from 75 samples when you used "DeepVariantWES"?

Thanks

**Comment by kriestof** [comment]
Hello @pichuan ,

Thank you for your response! Right now I get the right bed file from my data provider. It seems far better: ~320k calls in a single file, while ~420k after joint calling with glnexus and DeepVariantWES config. I remember the first time I got this data Deepvariant has much less calls than GATK, but then calling was made by our data provider and I don't possess any details on that. I can't remind the exact number, but I think it was far below 300k calls. Most of my comparison was based on that *legacy* data. Sorry for that unfair and unchecked comparison.

In case you are interested I could try to generate fresh GATK calling with same bed file according to GATK best practices. Otherwise I could let you know if I give a try to GATK in the future.

**Comment by pichuan** [comment]
Actually, I believe this was resolved by @kriestof  based on the comment earlier.
If there are any more follow-up questions,  feel free to reopen.
