### ISSUE TITLE
DeepVariant filter-QUAL/GQ

### ISSUE THREAD

**Issue by Suke-fudan** [google/deepvariant#503]
I ran DeepVariant(r1.1.0) and merged 1305 gvcfs by GLnexus (WES data).
I found one important site：
- QUAL（the 6th column)  25
- AQ（the 8th column)  25
- the genotype of 4 samples(controls and cases) :  ./.
- the genotype of 1296 samples(controls and cases) :  0/0
- the genotype other 5 samples(cases) : 0/1
- the DP and alt allele ratio in 0/1 samples:
   11,0.18     10,0.20      5,0.60      5,0.40      11,0.18
- the GQ in 0/1 samples:
    14    23    20    23    25
- the PL  in 0/1 samples:
    14,0,46     23,0,43       21,1,0       23,0,30       25,0,49

Should I consider the 0/1 variant may a true site in the 5 samples?
In some articles,the authors think the QUAL threshold should be set to 30(QUAL>30).
How can I set thresholds for QUAL,AQ and GQ to make sure the genotype(0/1) is true ?
Thank you!

**Comment by Suke-fudan** [comment]
Hi!I did some PCR and Sanger sequencing.
<html xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=PowerPoint.Slide>
<meta name=Generator content="Microsoft PowerPoint 15">
<style>

</style>
</head>

<body>




Caller | Sanger | QUAL | AQ | DP,alt   ratio | GQ | PL
-- | -- | -- | -- | -- | -- | --
Deep   Variant | √ | 43 | 43 | 47,0.57 | 42 | 43,0,50
38 | 38 | 91,0.41 | 38 | 38,0,50
48 | 48 | 136,0.51 | 48 | 48,0,62
43 | 43 | 31,0.42 | 19 | 19,0,46
43 | 43 | 33,0.45 | 41 | 41,0,55
43 | 43 | 41,0.20 | 17 | 16,0,49
× | 43 | 43 | 10,0.20 | 12 | 12,0,34
43 | 43 | 16,0.12 | 13 | 13,0,45
38 | 38 | 13,0.15 | 24 | 24,0,46




</body>

</html>

**Comment by AndrewCarroll** [comment]
Hi @Suke-fudan 

The best value to filter on is the GQ value of the variant call itself. We know from empirical investigation that the GQ value is very well-calibrated with the empirical error rate (See Figure 2 of - https://www.nature.com/articles/nbt.4235). This error probability is in the PHRED scale, so a GQ of 10 means DeepVariant indicates a 90% probability the call is correct, while a GQ of 20 indicates a 99% probability the call is correct. The formula for PHRED and correctness probability can be [found here](https://en.wikipedia.org/wiki/Phred_quality_score). 

Beyond this information about the relationship between estimated and empirical error, I can't help much more.
