### ISSUE TITLE
SNP calls missing from the terminal parts of the reference

### ISSUE THREAD

**Issue by chregu1971** [google/deepvariant#505]
Hi,
I am analysing long amplicons, but I do not get calls on known positions towards the end of the amplicon.
The missing positions are less than 110 bp from the end, but as it is an amplicon analysis I have full coverage to the last base.
I tried with setting the region parameter to start and end of the amplicon, but I still do not get the calls.
Is there a way to get these calls towards the end of the reference?

Best regards,
Christian

**Comment by AndrewCarroll** [comment]
Hi @chregu1971 

Are the calls missing from the end of the reference genome itself (meaning, these are at the boundary of the contig that yuo provided)? Or are they at the end of the amplicon, but still within the reference genome? 

DeepVariant does not generate pileup windows for sequence that is less than 110 bp from the edge of a reference contig. If this is the case, the only way to get calls here would be to pad the reference sequence (note that at the contig start this would alter the coordinate system of all calls).

Can you let me know whether these regions are at the edge of contigs or not?

Thank you,
Andrew

**Comment by chregu1971** [comment]
Hi @AndrewCarroll,
Thank you for the answer. This explains my observation. Did I miss this in some documentation?
The missing calls are from the end of the amplicon which corresponds to the end of the reference. It is actually a circular reference. 
Duplicating the reference solved the problem, as it effectively works like padding.
Best regards,
Christian

**Comment by pichuan** [comment]
Thanks @chregu1971 . I'll plan to add this to the FAQ.
