### ISSUE TITLE
Question: Usage WGS with intervals

### ISSUE THREAD

**Issue by FriederikeHanssen** [google/deepvariant#510]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md**:

**Describe the issue:**
Not an issue but a usage question:

GATK recommends [here](https://gatk.broadinstitute.org/hc/en-us/articles/360035889551-When-should-I-restrict-my-analysis-to-specific-intervals-) to use intervals also for whole genome sequencing analysis to blacklist certain areas but also allowing to process each interval in parallel and merging the vcfs later. I was wondering if it is also possible to do the same with deepvariant by using the `--regions` parameter for each region in parallel or if you would rather recommend to input all intervals in a single bed file and providing them all at once.

**Comment by MariaNattestad** [comment]
You don't have to split up the regions into a bunch of separate bed files because DeepVariant does that on its own. When you run DeepVariant with `run_deepvariant` you can set the `--num_shards` parameter, which automatically assigns a subset of regions to the different shards to make them even. Does that answer your question?

**Comment by FriederikeHanssen** [comment]
Thank you for the fast reply.

Almost, I think. Would it change results though to start deepvariant in parallel with a few interval files? I am thinking of using deepvariant within a nextflow script and using multiple smaller machines in parallel

**Comment by MariaNattestad** [comment]
You can definitely do your own sharding by supplying different `--regions` to each machine if that is convenient for you. The results should effectively be the same.
Another option I want to call out is calling the stages (make_examples, call_variants, postprocess_variants) separately. One thing you might want to try is running `run_deepvariant` with `--dry_run` and the number of shards you want, and then you can see the steps that are actually run underneath. Running stages separately is mostly only worth it if you are processing many samples and want to take advantage of many CPUs for make_examples and separate instances with more GPU for call_variants. With one sample, it's probably faster to run it on one machine, which takes about 7 hours.

Are you trying to run on many samples or some other reason why running on one machine is not fast enough and needs parallelization?

**Comment by FriederikeHanssen** [comment]
Thanks a lot. We want to support both to run many patients as well as single ones within a pipeline.
