### ISSUE TITLE
Update TensorFlow

### ISSUE THREAD

**Issue by Stikus** [google/deepvariant#511]
Hello, latest bazel build (5.0.0) dropped support of `--incompatible_prohibit_aapt1` flag ass you can see in patch notes https://blog.bazel.build/2022/01/19/bazel-5.0.html#android and here is my error:
```
+ bazel test -c opt --copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api deepvariant/...
[0m[91mINFO: Reading rc options for 'test' from /soft/tensorflow/.bazelrc:
  Inherited 'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2
[0m[91mERROR: --noincompatible_prohibit_aapt1 :: Unrecognized option: --noincompatible_prohibit_aapt1
```

Tensorflow removed this flag from their `.bazelrc` in June 2021 https://github.com/tensorflow/tensorflow/pull/50310 

Now deepvariant image cannot be build with latest `bazel` due to this - I ask you to update tensorflow version where this is fixed.

**Comment by MariaNattestad** [comment]
Thanks for letting us know. I've made a note of this to look into it for the next release.

**Comment by pichuan** [comment]
@Stikus A quick update for you: In our next release (v1.4.0), we'll update TensorFlow to v2.7.0.
Our Bazel version is still going to be 3.7.2 though (see: https://www.tensorflow.org/install/source#tested_build_configurations)

But we'll keep in mind to update bazel version when we do future TensorFlow version updates!
