### ISSUE TITLE
singularity pull 

### ISSUE THREAD

**Issue by javadgh6** [google/deepvariant#513]
Hi

when I try to pull the deepvariant docker image via singularity using the following command:
singularity pull docker://google/deepvariant:"1.3.0"
it return the following error:
WARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
ERROR Authentication error, exiting.
Cleaning up...
ERROR: pulling container failed!

could you please help. I don't have the permission to install docker.
Thanks

**Comment by pichuan** [comment]
Can you check whether you're able to pull other public images on this machine?

From the error above it seems to have an "Authentication error", which doesn't quite make sense to me because our Docker hub image should be public.


I just tried:
```
singularity pull docker://google/deepvariant:"1.3.0"
```
as a sanity check. I confirmed it worked for me (so at least hopefully there isn't an obvious mistake here on permission)

**Comment by javadgh6** [comment]
Thank you very much for your quick replay.
I have changed the version of the singularity to > 3 the problem was solved. however when I try to run the image using following command 
singularity run  -B /usr/lib/locale/:/usr/lib/locale/  /home/my_username/deepvariant_1.3.0.sif  --model_type=WES  --ref=input/Homo_sapiens_assembly38.fasta  --reads=/oldHome/my_username/exome_data/EX2015.sorted.bam \ --output_vcf=output/output.vcf.gz  --intermediate_results_dir=outout  --num_shards=10
it with return the following error and stop
INFO:    Convert SIF file to sandbox...
ERROR  : Failed to create user namespace: user namespace not supported by your system
Thanks

**Comment by pichuan** [comment]
Hi @javadgh6 , this seems like a Singularity related issue. Can you see if this is relevant? https://github.com/apptainer/singularity/issues/5240

**Comment by pichuan** [comment]
Hi @javadgh6 , hopefully you were able to resolve your issue. Let us know if you have more questions.
