### ISSUE TITLE
Adjacent deletions > 100% allele depth

### ISSUE THREAD

**Issue by JoshDLane** [google/deepvariant#516]
I have a sample with a 4bp deletion at pos 775 and 1bp del at 779. Looking at the raw reads they seem to always be separate, and I confirmed there are no 5bp deletions called in this region in the alignment (via analyzing cigarStrings). DeepVariant is calling the 4bp del at 40% AD and the 1bp del at 77% AD. How could these logically add up to > 100%? Wouldn't that imply instances of 5bp deletion, but that would be reported separately, no? If someone could help me interoperate this that would be great.

<img width="113" alt="ComplimentaryIndelsP01-24" src="https://user-images.githubusercontent.com/65191963/153235606-e34c7406-d339-4b20-8ba7-fb29b42c713d.PNG">

**Comment by pichuan** [comment]
> Thanks for the reply,
> 
> 1. samtools is having trouble indexing the output realigned bam file, do you know why this may be?

Hi @JoshDLane ,
I think you might need to sort the BAM file first before indexing it.

> 2. despite what the realignment is, wouldn't this not make sense as a result?

Can you clarify what didn't make sense? I wasn't sure if you're responding to @akolesnikov 's point two, or is it a separate point. Thanks!

**Comment by pichuan** [comment]
Given that there has been no responses for a while, I'll close this issue.
Please feel free to reopen as needed.
