### ISSUE TITLE
Polyploid support?

### ISSUE THREAD

**Issue by jguhlin** [google/deepvariant#519]
Hello, I'm just reaching out to see what it would take to add polyploid support to DeepVariant. I see this has been addressed a few times, but want to bring it up again. It looks like utility functions are there, is the only thing remaining the model to be changed, or what else would need to be changed? Any pointers greatly appreciated. Cheers.

**Comment by MariaNattestad** [comment]
The main obstacle is getting good data for training. We use GIAB truth sets for human, but we would need similar quality true variants along with data in polyploid genomes, and even then to support various ploidy levels you might to train multiple models. We also don't have enough bandwidth to prioritize this work within the team for the foreseeable future.

**Comment by jguhlin** [comment]
Hey, thanks for the response! I may have access to a high-quality dataset in the near future. Also, training multiple models for each level of ploidy makes sense. I've got some experience with TF and programming in general (Python and Rust, lately), so curious if you can give some feedback on specific areas that may need to be adjusted for ploidy? Or, if it would be too much for one person I understand too.

I've done re-training of DV models for non-model species and have seen great improvements so far, so I'm familiar with that as well. Thanks again!

**Comment by MariaNattestad** [comment]
I consulted with the team to get an idea of the effort required, and we came to the conclusion that the DeepVariant code is full of diploid assumptions, so this would likely take a lot of effort, and unfortunately it isn't something that we have enough bandwidth to advise anyone else through either. You're of course welcome to fork DeepVariant and play around with it, but it will likely require many changes to the code to make it work. It is definitely possible though. You could also consider whether other ML-based variant callers are easier to adapt to polyploid, or if any polyploid callers exist already, which could be fun to add ML on top of as well.

**Comment by jguhlin** [comment]
Ah, understood, and thanks very much for the guidance.
