### ISSUE TITLE
Running DeepVariant on large sample size

### ISSUE THREAD

**Issue by Virmani12** [google/deepvariant#526]
Hello,

I have tried following along the guidelines presented under [Best practices for multi-sample variant calling](https://github.com/google/deepvariant/blob/r1.3/docs/trio-merge-case-study.md#best-practices-for-multi-sample-variant-calling-with-deepvariant-wes-trio-demonstration) but am still unclear as to how to run DeepVariant on a large sample size (~200). The example provided only uses a trio and the paper cited doesn't provide any code for their large cohort experiment. Do you have any resources for adjusting the parameters/running the samples in parallel so as to not run all ~200 samples sequentially? Thanks!

**Comment by tedyun** [comment]
Closing this issue - please feel free to re-open if you have additional questions.
