### ISSUE TITLE
bed file for WES 

### ISSUE THREAD

**Issue by amyhouseman** [google/deepvariant#527]
Hello, 

Sorry me again! I was just wondering if a bed file is required for every WES analysis? I've ran deepvariant without adding one, but think I should have included one? Would I get this WES bed file from the manufacturer?

Thanks!
Amy

**Comment by pichuan** [comment]
Hi @amyhouseman 
It is not required that you provide a BED file, but then you'll end up having to process a lot more data if you don't filter with a BED file (and it's much slower).

For WES, I recommend that you use a BED file for the capture regions. If you want to pad the BED file a bit before using, you can.

Closing this issue. Feel free to open again if you have more questions.

**Comment by amyhouseman** [comment]
Thank you! When you say pad the bed file, what do you mean? Thanks

**Comment by pichuan** [comment]
@amyhouseman Sometimes people decide to extend the regions in the BED files a bit, something like: https://bedtools.readthedocs.io/en/latest/content/tools/slop.html

**Comment by amyhouseman** [comment]
**Thank you!** 

Once adding in the location of the bed file, which is definitely not empty (download link for bed file here: https://we.tl/t-7EXAoGz8RT). using this code:** 

```
#!/bin/bash --login
#SBATCH -J AmyHouseman_deepvariant
#SBATCH -o %x.stdout.%J.%N
#SBATCH -e %x.stderr.%J.%N
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH -p c_compute_wgp
#SBATCH --account=scw1581
#SBATCH --mail-type=ALL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=HousemanA@cardiff.ac.uk     # Where to send mail
#SBATCH --array=1-33
#SBATCH --time=72:00:00
#SBATCH --mem-per-cpu=64GB

module purge
module load parallel
module load singularity

# Set bash error trapping to exit on first error.
set -eu

cd /scratch/c.c21087028/

sed -n "${SLURM_ARRAY_TASK_ID}p" Polyposis_Exome_Analysis/fastp/All_fastp_input/List_of_33_exome_IDs | parallel -j 1 "singularity run -B /usr/lib/locale/:/usr/lib/locale/ containers/deepvariant_1.3.0.sif /opt/deepvariant/bin/run_deepvariant --model_type=WES \
--ref=Polyposis_Exome_Analysis/bwa/index/indexhumanrefseq_output/samtools_faidx/GRCh38_latest_genomic.fa.gz \
--reads=Polyposis_Exome_Analysis/picard/markduplicate/markedduplicates/{}PE_markedduplicates.bam \
--regions=Polyposis_Exome_Analysis/deepvariant/agilent_bedfile/agilent_human_region.hg38.bed \
--output_vcf=Polyposis_Exome_Analysis/deepvariant/vcf/{}PE_output.vcf.gz \
--output_gvcf=Polyposis_Exome_Analysis/deepvariant/gvcf/{}PE_output.vcf.gz \
--intermediate_results_dir=Polyposis_Exome_Analysis/deepvariant/intermediateresults/{}PE_output_intermediate"
```

**I get the error:** 
   
 ```
raise ValueError('The regions to call is empty. Check your --regions and '
ValueError: The regions to call is empty. Check your --regions and --exclude_regions flags to make sure they are not resulting in set of empty region to process. This also happens if you use "chr20" for a BAM where contig names don't have "chr"s (or vice versa).
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref Polyposis_Exome_Analysis/bwa/index/indexhumanrefseq_output/samtools_faidx/GRCh38_latest_genomic.fa.gz --reads Polyposis_Exome_Analysis/picard/markduplicate/markedduplicates/NG0921010_EKDN210018950-1A_HN2MGDSX2_L2_PE_markedduplicates.bam --examples Polyposis_Exome_Analysis/deepvariant/intermediateresults/NG0921010_EKDN210018950-1A_HN2MGDSX2_L2_PE_output_intermediate/make_examples.tfrecord@1.gz --gvcf Polyposis_Exome_Analysis/deepvariant/intermediateresults/NG0921010_EKDN210018950-1A_HN2MGDSX2_L2_PE_output_intermediate/gvcf.tfrecord@1.gz --regions Polyposis_Exome_Analysis/deepvariant/agilent_bedfile/agilent_human_region.hg38.bed --task 0
```

The error is quite descriptive, but I'm not sure how my file would be empty?
Thanks for all your help!
Amy

**Comment by pichuan** [comment]
What is the header in your BAM file (what are the names of the contigs)? I think this can happen if your reference FASTA file, your BAM file, and your BED file had different contig names.

**Comment by amyhouseman** [comment]
Okay so just taking one sequence:

> .the .sam file first line is (after doing head -1): @SQ     SN:NC_000001.11 LN:248956422

> the .bam file first line is (after doing samtools view -H): @HD     VN:1.6  SO:coordinate
and that same .bam's second line is: @SQ     SN:NC_000001.11 LN:248956422

> the reference fasta file first line is: >NC_000001.11 Homo sapiens chromosome 1, GRCh38.p13 Primary Assembly

> The .bed first line is chr1    12080   12251.

Thank you for all your help, I really appreciate it.

**Comment by pichuan** [comment]
Can you confirm that your BAM file header does have `chr1`, and that your FASTA file also have `chr1`?

**Comment by amyhouseman** [comment]
Hi sorry for the delay,

I reran my sequences with a new copy of the human reference genome from https://www.ncbi.nlm.nih.gov/genome/guide/human/ up until running deepvariant. 

I get the same headers as above, it doesn't seem like the bam, sam or even the reference start with the word 'chr1':

sam file header: @SQ	SN:NC_000001.11	LN:248956422
bam file (sorted picard): @HD	VN:1.6	SO:coordinate
@SQ	SN:NC_000001.11	LN:248956422
Original fasta reference file header: >NC_000001.11 Homo sapiens chromosome 1, GRCh38.p13 Primary Assembly
Bed file: chr1	12080	12251

All the code and steps I've done before are on my page under Exome_Pipeline/PE read analysis.

 I'm not sure! Ah, thank you!

**Comment by amyhouseman** [comment]
For anyone with the same problem: my bed file had the IDs labelled as chr1 whereas other files used the accession number (e.g NC_000001.11) - I used dplyr on R to recode the IDs to the accession number and then deepvariant worked :) Thanks!

**Comment by pichuan** [comment]
Hi @amyhouseman , thank you for sharing your solution!
