### ISSUE TITLE
parameters setting for somatic/germline variant calling

### ISSUE THREAD

**Issue by Qianwangwoo** [google/deepvariant#528]
Dear team,  may I know if there is any different parameters setting between somatic variant calling and germline variant calling? The reason why I posted this question is that I found one heterozygous variant called by deepvariant but seems homozygous supported in IGV. I'm wondering if my setting of deepvariant is too loose for this variant? (ps, I just run deepvariant by default pacbio data setting) 
Here is the result in VCF. The VAF is quite high, and`1,20` AD means only 1 read supported the widetype read? 
chr4        3079267        .        G        T        36.1        PASS        .        GT:GQ:DP:AD:VAF:PL        0/1:4:21:1,20:0.952381:33,0,1
Here is the screenshot of IGV
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/44595075/158147856-1ff7a5c8-d68f-4711-8e73-0c0806089783.png">
Thanks!!

**Comment by pichuan** [comment]
Hi @Qianwangwoo ,
First of all, DeepVariant is a germline variant caller - all our release models are trained for germline variant calling.

But if I read your question correctly, your question is more about "why does DeepVariant call this image as HET rather than HOM-ALT". To answer that question, it'll be similar to this FAQ here: https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

Once a candidate is identified, DeepVariant uses a classifier on it to generate a probability distribution for the 3 classes (0: HOM-REF, 1: HET, 2: HOM-ALT). 
 
From the `PL` field, it would look like HOM-ALT has lower priority than HET, but not necessarily by much `33,0,1`.

Let me know if this helps and if you have more questions.

**Comment by Qianwangwoo** [comment]
> 
Hi @pichuan , thanks so much for your reply!
Yes, I think I want to understand why this variant was called as HET instead of HOM-ALT. I got the idea of PL for this variant call, I'm wondering if there is a parameter for `VAF` to do the filtering? Thanks!!

**Comment by AndrewCarroll** [comment]
Hi @Qianwangwoo 

We don't do additional filtering beyond the probabilities from the classifier. In this case, DeepVariant does not have a high confidence in the correct genotype between HET and HOM-ALT (a GQ of 4 corresponds to a ~60% confidence in a correct genotype call). The QUAL value of 36.1 suggests that DeepVariant is at least pretty confident that the position is not REF

A few other points to keep in mind - first, are you using the two-pass DeepVariant-WhatsHap-DeepVariant method? If so, then DeepVariant may be using additional information about the phasing from longer range.

Second, this variant is at a junction between homopolymers (poly-T and poly-G) This represents the dominant error mode for PacBio HiFi, so it may nit be straightforward for a human to assess the probability of a G->T variant here as opposed to a sequencing error of Insertion T and deletion G. 

If you want to for sure have a higher precision, you can additionally filter for GQ value (e.g. 10 for a 90% confidence in the genotype call). However, if you do so, you will lose variant positions like this which are very likely not reference, but difficult to genotype.

**Comment by Qianwangwoo** [comment]
Thanks @AndrewCarroll , I didn't use two pass method for this variant calling. Do you think it's proper to apply this method to all Pacbio HiFi reads?

**Comment by AndrewCarroll** [comment]
Hi @Qianwangwoo 

Yes, the two-pass method generally improves accuracy with PacBio small variant calling, especially for Indels. Whether it is likely to improve this call, I am not sure. Note that we anticipate a future release of DeepVariant for PacBio in the near future which will have comparable accuracy with a single pass of variant calling, so you may prefer to keep your current workflow and wait for that version if you don't mind updating.
