### ISSUE TITLE
Inconsistent number of reference supporting reads.

### ISSUE THREAD

**Issue by leedchou** [google/deepvariant#529]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md**:
YES.

**Describe the issue:**
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system: ubuntu **16.04**
  - DeepVariant version: **1.1.0**
  - Installation method (Docker, built from source, etc.): **built from source**
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) **WGS**

**Here is the problem:** I was trying to count reference supporting reads by the class "**ReadSupportsAlt**" defined in pileup_image_native.cc. To make sure it was correct, I also printed out the first value of Allele Depth ("**AD**") for reference supporting reads. However, it turned out that there was an inconsistent number of reads counted by  these two ways. To be more specific, there were more reference supporting reads counted by "**ReadSupportAlt**" than “**AD**“ did in general. At the very beginning, I thought it was non-alternate-allele reads that made this kind of inconsistent, then I viewed log files. Unfortunately, I found that there were at least 2 more reference supporting reads counted by "**ReadSupportAlt**" than “**AD**“ did (SNP, min_counts_snps = 2). So I am confused with the result. I would appreciate it if someone help me with this issue.

**Comment by pichuan** [comment]
Hi @leedchou ,
usually when there's a question about reads count, it can be related to related to the fact that DeepVariant runs a realigner first. See this section of the FAQ: https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work

If you think this something more than that, can you give a small reproducible example, and give specific description of which position you're looking at, and what count you're getting (and what you're expecting)? Without that, it's a bit difficult to understand the details here. Thank you!

**Comment by leedchou** [comment]
> Hi @leedchou , usually when there's a question about reads count, it can be related to related to the fact that DeepVariant runs a realigner first. See this section of the FAQ: https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work
> 
> If you think this something more than that, can you give a small reproducible example, and give specific description of which position you're looking at, and what count you're getting (and what you're expecting)? Without that, it's a bit difficult to understand the details here. Thank you!

**Comment by leedchou** [comment]
``> Hi @leedchou , usually when there's a question about reads count, it can be related to related to the fact that DeepVariant runs a realigner first. See this section of the FAQ: https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work
> 
> If you think this something more than that, can you give a small reproducible example, and give specific description of which position you're looking at, and what count you're getting (and what you're expecting)? Without that, it's a bit difficult to understand the details here. Thank you!

Thanks for your reply @pichuan.
In the step of making examples, I'd like to get the reference supporting reads count when encoding pileup image for one variant. There are 2 ways to get the count, one is to get it from **Allele Depth (AD)** straightforward, the other is to traverse all reads of this variant through an iteration. The related code is as follows:

```
inline int ReadSupportsAlt(const DeepVariantCall& dv_call, const Read& read,
                           const std::vector<string>& alt_alleles) {
  string key = (read.fragment_name() + "/" +
                std::to_string(read.read_number()));

  // Iterate over all alts, not just alt_alleles.
  for (const string& alt_allele : dv_call.variant().alternate_bases()) {
    const auto& allele_support = dv_call.allele_support();
    const bool alt_allele_present_in_call =
        allele_support.find(alt_allele) != allele_support.cend();
   
 if (alt_allele_present_in_call) {
      const auto& supp_read_names = allele_support.at(alt_allele).read_names();
      for (const string& read_name : supp_read_names) {
        const bool alt_in_alt_alleles =
            std::find(alt_alleles.begin(), alt_alleles.end(), alt_allele) !=
            alt_alleles.end();
        // Read can support an alt we are currently considering (1), a different
        // alt not present in alt_alleles (2), or ref (0).
        if (read_name == key && alt_in_alt_alleles) {
          return 1;
        } else if (read_name == key && !alt_in_alt_alleles) {
          return 2;
        }
      }
    }
  }
  return 0;
}

// main function
std::unique_ptr<ImageRow>
PileupImageEncoderNative::EncodeRead(const DeepVariantCall& dv_call,
                                     const string& ref_bases,
                                     const std::vector<::nucleus::genomics::v1::Read>& reads,
                                     int image_start_pos,
                                     const vector<string>& alt_alleles) {
  const int ref_supporting_reads_1 = 0;
  ref_supporting_reads_1 = dv_call.variant().calls()[0].info().find("AD")->second.values()[0].int_value();

  int ref_supporting_reads_2 = 0;
  for (const Read& read : reads) {
    const int supports_alt = ReadSupportsAlt(dv_call, read, alt_alleles);
    if (supports_alt == 0) {
      ref_supporting_reads_2 += 1;
    }
  }
}
```
Reads are from AlleleCounter as you did. I did not change any other code. **However, ref_supporting_reads_1 is not equals to ref_supporting_reads_2.** Why the inconsistent reads count, this is what I really want to know.

**Comment by akolesnikov** [comment]
Hi @leedchou,

Using ```ReadSupportsAlt``` function from pileup_image_native.cc to count ref sporting reads is incorrect. If a given read does not support any of the alleles it doesn't mean that this read supports a reference (this is due to the specifics of the DeepVariant implementation). AD value should be used for the number of ref supporting reads. 
If you could share some details on what are you trying to achieve we will be able to provide a better suggestion.

**Comment by leedchou** [comment]
> Hi @leedchou , I'll ask my teammate @akolesnikov to take a look, maybe sometime next week.

Thank you very much for your help @pichuan .

**Comment by leedchou** [comment]
> Hi @leedchou,
> 
> Using `ReadSupportsAlt` function from pileup_image_native.cc to count ref sporting reads is incorrect. If a given read does not support any of the alleles it doesn't mean that this read supports a reference (this is due to the specifics of the DeepVariant implementation). AD value should be used for the number of ref supporting reads. If you could share some details on what are you trying to achieve we will be able to provide a better suggestion.

Thank you @akolesnikov , I completely understand now.
