### ISSUE TITLE
Documentation on quality scores

### ISSUE THREAD

**Issue by jordimaggi** [google/deepvariant#531]
Hi,

I have been looking for documentation about the quality scores and how to interpret those.

I am working on WGS data for human samples derived from patients affected by rare inherited disorders. I am looking to establish a filtering strategy on the raw VCF data, specifically for `RefCall` variants. I assume that simply getting rid of all those calls may reduce sensitivity. Therefore, I would like to figure out a quality score to use to filter these variants to maximize both sensitivity and specificity.
Any suggestion?

**Comment by splaisan** [comment]
thanks for the great piece of software!
I agree with Jordi and would add that some general guidelines on how to use the numerous INFO fields would be nice, do they live somewhere?
it is a pity to have so many metrics and ignore how to put them to good use

**Comment by pichuan** [comment]
Hi @jordimaggi 
For anything that is `RefCall`, that means: even though a candidate variant was proposed, our machine learning classifier decided the most likely class is 0 (which means reference). 
You can read this section to get a bit more background on this: https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

You could potentially take the finer-grained information (like `PL`) and try to adjust your own threshold. This could increase the sensitivity, but will likely hurt the specificity of DeepVariant's results. I'll ask @AndrewCarroll to add his thoughts here as well.

Hi @splaisan , for the existing fields we have in our VCF file, we follow the standard definitions you can find on https://en.wikipedia.org/wiki/Variant_Call_Format#Common_FORMAT_fields (and we only fill in a subset of them). Let us know if there's anything specific that is not clear to you. Happy to explain more.

**Comment by AndrewCarroll** [comment]
Hi @jordimaggi @splaisan 

I will add on a little to Pi-Chuan's answer with respect to filtering and quality scores. We consistently find that the genotype quality (GQ and PL fields) are extremely well-calibrated with the empirical probability of a call being correct. This is quantified in Figure 2 of the [original DeepVariant paper](https://www.biorxiv.org/content/10.1101/092890v6). This value is the best to use when determining whether a call is likely correct.

Both ourselves and other external groups who we work with have tried to identify other metrics of standard INFO and FORMAT fields which are more predictive of call quality or even additionally informative in a subset of contexts and cases. For basically everything we and these groups have looked at, GQ is more predictive of call correctness. 

If you are able to identify an annotation which is additionally informative beyond GQ (and also not already perfectly captured in the GQ field), it would be quite interesting to know, and we could consider incorporating it as an output field, or providing the annotation as an input during calling. 

In general, I'd encourage you to look at GQ and PL as the most informative fields if you would like to tune between sensitivity and specificity.

**Comment by splaisan** [comment]
Dear @AndrewCarroll, thanks a lot, this is exactly the answer I was looking for. 
I will plot the distribution of these metrics and see if I can cut the tail somewhere to increase the overall truth of my data.

Best regards
Stephane

**Comment by jordimaggi** [comment]
Dear @pichuan and @AndrewCarroll,
thansk for the replies! I will exclude `RefCall` calls and use `GQ` to filter out lower quality calls. Thanks for the clarification!
Also, great work on the amazing piece of software!

Best,
Jordi Maggi
