### ISSUE TITLE
Type of data

### ISSUE THREAD

**Issue by wylpython** [google/deepvariant#535]
Can I use DeepVariant on  NGS (Illumina) panel data(some genes)?panel data such as amplicon data ,target enrichment (hybridization probes) type of data。

Thanks!

lily

**Comment by MariaNattestad** [comment]
Short answer: Yes, try the "WES" model.
Long answer: DeepVariant isn't designed to work on super high coverage, so amplicon sequencing sometimes will produce way too many reads in each region. DeepVariant will only be able to show a random sample of the 95 reads at each putative variant locus to the model.
Also just to confirm this is still germline sequencing, right? Not somatic or trying to capture variants present in less than about half the reads -- these don't work with DeepVariant.

**Comment by wylpython** [comment]
Hi @MariaNattestad  , thanks so much for your reply!
Yes, I'm testing for germline variation.

**Comment by MariaNattestad** [comment]
Okay, great! I'll close this, but feel free to reopen if you run into problems running the WES model on your panel data.
