### ISSUE TITLE
Has DeepVariant been used on MGI Tech sequencing datasets?

### ISSUE THREAD

**Issue by avilella** [google/deepvariant#538]
Has DeepVariant been used on MGI Tech sequencing datasets?

**Comment by AndrewCarroll** [comment]
Hi @avilella 

DeepVariant has been used on MGI datasets, both using the standard Illumina model, as well as retrained models. There is some complexity that the MGI/BGI technologies have evolved over time, so some demonstrations may not reflect the newest methods.

The general finding is that the Illumina models tend to work well for MGI data, though we find examples of retraining for certain datasets improve further.

Our [advanced training tutorial ](https://github.com/google/deepvariant/blob/r1.3/docs/deepvariant-training-case-study.md) walks through retraining an Illumina model for data from BGISEQ 500 and [this comparison](https://blog.dnanexus.com/2018-07-02-comparison-of-bgiseq-500-to-illumina-novaseq-data/) was conducted several years ago using the out-of-the-box Illumina model.

If you know of any genome in a bottle sequencing datasets that are available from more recent MGI platforms, I'd be interested in pointers to those locations. I would be quite curious to see how the technology has evolved over the last several years.

**Comment by avilella** [comment]
Fantastic information, thank you.

**Comment by PlatonB** [comment]
@AndrewCarroll It would be cool to have the option `--model_type=MGI`. Now, unfortunately, there are a lot of variants being missed when working with MGI data.

**Comment by pichuan** [comment]
Hi @PlatonB ,
In v1.6, we have added documentation on how to run on MGI data.

Please see the links "Complete Genomics data: T7 case study; G400 case study" which was also linked from our GitHub main page.

**Comment by karoliinas** [comment]
Hi, I'm also interested in this. I have some MGI data, for which I called variants using the default model. Do you recommend I run variant calling again with the custom model, and if so, which model (T7 or G400)? I have data from ~150 samples but don't have a reference sample to run any benchmarking.

**Comment by karoliinas** [comment]
Thanks @pichuan, I'll go ahead and re-call the variants according to the tutorial. And just to clarify, can I use the T7 case study -model with the latest deepvariant release, or do I have to use version 1.6.1, as stated in the model's json -file? I have MGI T7 data.
