### ISSUE TITLE
Could not read base quality scores

### ISSUE THREAD

**Issue by ziphra** [google/deepvariant#539]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.3/docs/FAQ.md**: yes 

**Describe the issue:**
I am running deep-variant trough a docker installation of the pepper-margin-deepvariant pipeline `kishwars/pepper_deepvariant:r0.8-gpu` on data aligned with minimap2 and data aligned with lra. It is working fine with the minimap2 aligned data, but deepvariant does not produce a final VCF with lra aligned data. 

It seems that deep-variant cannot read the base quality score during SNP calling:

```
2022-05-26 00:08:16.416812: W third_party/nucleus/io/sam_reader.cc:599] Could not read base quality scores 2e95d959-f3f1-403f-acff-a2bf4f2c12fe: Not found: Could not read base quality scores
2022-05-26 00:08:16.450548: F deepvariant/allelecounter.cc:198] Check failed: offset + len <= read.aligned_quality_size() (81 vs. 0)
Fatal Python error: Aborted
```
and the job eventually fails:

```
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref /media/euphrasie/DATA/reference_genome/hg38/hg38_GenDev.fa --reads /media/euphrasie/Alienware_May202/HG002_PAG07506/pmdv/HG002_PAG07506_38_lra/output/intermediate_files/PHASED.PEPPER_MARGIN.haplotagged.bam --examples /media/euphrasie/Alienware_May202/HG002_PAG07506/pmdv/HG002_PAG07506_38_lra/output/dv_intermediate_outputs/make_examples.tfrecord@16.gz --add_hp_channel --alt_aligned_pileup none --min_base_quality 1 --min_mapping_quality 5 --parse_sam_aux_fields --partition_size 10000 --proposed_variants /media/euphrasie/Alienware_May202/HG002_PAG07506/pmdv/HG002_PAG07506_38_lra/output/intermediate_files/PEPPER_VARIANT_OUTPUT_VARIANT_CALLING_SNPs.vcf.gz --norealign_reads --sample_name Sample --sort_by_haplotypes --variant_caller vcf_candidate_importer --task 7
```

I checked the lra bam with samtools view and the base quality scores are there.
I wonder what is wrong with my lra aligned reads. The full `5.1_DeepVariant_SNP.log` is attached.

**Setup**
  - Operating system: Ubuntu 20.04.4
  - DeepVariant version: pepper_deepvariant:r0.8-gpu
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) 

**Steps to reproduce:**
  - Command: 
  ```
  	docker run --ipc=host \
	--gpus all \
	-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
	-v "${BASE}":"${BASE}" \
	-v "${REF}":"${REF}" \
	-v "${BAMPATH}":"${BAMPATH}" \
	kishwars/pepper_deepvariant:r0.8-gpu \
	run_pepper_margin_deepvariant call_variant \
	-o "${OUTPUT_DIR}" \
	-b "${BAM}" \
	-f "${REF}" \
	-p "${OUTPUT_PREFIX}" \
	-t ${THREADS} \
	-g \
	--ont_r9_guppy5_sup
  ```

  - Error trace: (if applicable)
  
[5.1_DeepVariant_SNP.log](https://github.com/google/deepvariant/files/8785347/5.1_DeepVariant_SNP.log)

**Does the quick start test work on your system?** yes 
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start? no

**Any additional context:** Ultra-long reads

**Comment by ziphra** [comment]
According to #434:

my bam is not truncated. 

`samtools view bam | grep 2e95d959-f3f1-403f-acff-a2bf4f2c12fe`  outputs:

```
1f03af87-9f29-4d0a-89af-642fd540a930	16	chr1	1897387	60	15S185=1I111=2D148=1D1X1=1X24=1D1X118=1D2=1X1=1I146=1X17=1X30=1I1X47=1D126=84S	*	0	969	GACAGACCTTGGTTTAAAATACAAACCTTGGCCAGGCGCGGTGGTTCACAGCTGCAGTCTCAGCACTCTGGGAGGCCAAGGTGGGCGGATCATCTGAGGTGGAGAGTTTGAGACCAGCCTGATTAACATGGAGAAACCCCGTCTCTACTAAAAATACAAAATTAGCTGGGCGTGGTGGTGCATGCCTGTAATCCCAGCTACCTCGAGAGGCTGAGGCAGGAGAATCGCTTGAACCCGGGAGGCAGAGGTTGCGGTGAGCTGACATTGCGCTATTGCACTCCAGCCTGGGCAACAAGAGTGAAACTCCGTCTCAAAAAAAAAACAACAAAAAACACCTCTTGGCTGGGTGCCATGGTTCACGCCTACAATTCCAGCTCTTTAGGAGGCTGAGGCTGGAGCATTACTTCAGACCAGGAGTTTGAGACTAACATAGTGAGTGAGACCCCATCTCTGCTAAATACATAAAATTAGCCAGGCATGATGTCTCAGCCTCAGGTACCCGCTACTCAGGAAGCTGAGGTGGGAGGATCGCTTGGGCAGGGGAGGTTGAGGCTGCAGTGAGCCATCATCGCGCCACTGCACTCAAACCTGGGTGACAGAGTGAGACTCCTTCTCAAAAACAAACAAAAACCCCACAAACCTCCCTAACAGTGAAAGATGCAAAACCATGAATGGAAAGAGCATCGTCCCCTGCCTGTAGACCCAGAAGCCGTGCACAGACAGGTACGTGTGCATGTGCACATACATTCACAATCTGGGTATATATGCATGTGCGCACATGGGAGCTGGTGATATGCACATGTGCACAGCACACCCAAGCTGGGTATATGTGCATGTGAACAAACACACATAAGCGTGTATATACACATGTGCACACACAAGCTGGATATACACACATGTATGTACATGAGCTGGGTGTATACACACACCCAAGCTAGGTATACATGCATGTGGACAAACACGAGCTGGATATACATGCATGAAGCGGCGCACGAAAACGCGAAAGCGTTTCACGATAAATGCGAAAACGGTTAAACACCTACCGTAACTGAAATCCATACGGTT	*	NM:i:15	MM:i:15	NX:i:7	ND:i:3	TD:i:6	NI:i:5	TI:i:3	NV:f:940	AS:i:940	AO:i:0	N0:i:20	RT:i:1	TP:A:P	SD:i:5	ME:i:0	LD:i:0	SI:i:6	MI:i:0	LI:i:0
```
My reads were aligned as follow: 

```
zcat $FASTQ | lra align -ONT -t 24 $REF - -p s | samtools sort -@ 14 -o $BAM
samtools index $BAM -@ 34
```

**Comment by kishwarshafin** [comment]
@ziphra ,

Reads without any quality score provided to DeepVariant would cause this issue. One thing you can quickly see from your `samtools view` output is the flag of this read is `0x16`, you can go to this website: https://broadinstitute.github.io/picard/explain-flags.html and put in `0x16` and it'd say the read is unmapped. 

A quick way to remove any improper reads would be to run this:
```
INPUT_BAM=/path/to/input.bam
OUTPUT_BAM=/path/to/input.F0x904.bam
samtools view -@42 -F 0x904 ${INPUT_BAM} > ${OUTPUT_BAM}
```
This will remove all non-primary reads and should get rid of the errors for you. You can put `0x904` on the explain-flags website to see which reads you will only keep.

**Comment by ziphra** [comment]
Hello @kishwarshafin, 

Thank you for your response and for the useful tips!

It appears that I have several types of flags for my reads presenting no quality score: 
```
0
16
2048
2064
4
```
All the above flags are also present in my reads having a quality score sequence, except for the flag `4` (= read unmapped), which is absent.

Also, it seems that in this case flags should be written without the `0x` prefix, which converts them to hexadecimal when they are written in decimal in the sam file, as I understand. 
`0x16` in https://broadinstitute.github.io/picard/explain-flags.html output a flag  that cannot be set when read is not paired, and my read are not paired.

However, it now seems clear that something went wrong with the alignment since I have all types of reads with no quality score sequence, not only `0x904` type reads (which are  read unmapped `0x4`, not primary alignment `0x100`, and supplementary alignment `0x800`).

**Comment by kishwarshafin** [comment]
@ziphra ,

You are correct. It does seem like something went wrong with your mapping and you have reads without base-qualities. My suspicion was that the aligner was removing base-qualities from non-primary reads, but that's clearly not the case.
