### ISSUE TITLE
v1.4 deepvariant-cpu docker image does not contain openvino

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#541]
I've been trying out the new v1.4 docker image through singularity, but have been running into openvino issues again (#404 and #416, maybe I should just move on :wink:).

The error during call_variants is below (and similar to #432)
```
 File "/tmp/Bazel.runfiles_ya87e4x1/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 416, in call_variants
    ie_estimator = OpenVINOEstimator(
  File "/tmp/Bazel.runfiles_ya87e4x1/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 90, in __init__
    freeze_graph(model, checkpoint_path, tensor_shape, openvino_model_pb)
  File "/tmp/Bazel.runfiles_ya87e4x1/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 77, in freeze_graph
    graph_def = optimize_for_inference_lib.optimize_for_inference(
NameError: name 'optimize_for_inference_lib' is not defined
```

Which comes from [here](https://github.com/google/deepvariant/blob/d2a3aca8691318221e794594ea08e7c88e21359b/deepvariant/openvino_estimator.py#L42). However, after playing around inside the image, the line `from tensorflow.python.tools import optimize_for_inference_lib` works fine as I can successfully run
```
python -c 'from tensorflow.python.tools import optimize_for_inference_lib'
```

The real issue is openvino is not installed 
```
python -c 'from openvino.runtime import Core, AsyncInferQueue, Type'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'openvino'
```

which triggers the ImportError and pass statement skipping the import of optimize_for_inference_lib.

Not to expose my limited understanding of dockerfiles, but [here](https://hub.docker.com/layers/deepvariant/google/deepvariant/latest/images/sha256-83ce0d6bbe3695bcbaa348b73c48737bdbfaeaea2272b0105dd4bdfa7a804f18?context=explore) it appears that the current latest build has ` ENV DV_OPENVINO_BUILD=0`. I've seen a lot of back and forth with openvino no longer being as helpful, but then there has been some recent updates, so not sure if it is still recommended or deprecated as it has disappeared from some docs.

Best,
Alex

**Comment by pichuan** [comment]
Hi @ASLeonard ,

Thanks for reporting this issue.

We actually made a deliberate decision to not include OpenVINO this time, because in our test setting we were not able to get faster runtime. We did talk to @dkurt about this and tried https://github.com/google/deepvariant/pull/523. We will still plan to try OpenVINO again in the next release. But given that we didn't see faster runtime, we decided to leave it out of the default.

If you would like to use it, please use our Dockerfile and build with the option on.

I'm curious - were you seeing a speedup by using OpenVINO in DeepVariant v1.3.0? If so, what is the type of machine you're using?

Thank you!

**Comment by ASLeonard** [comment]
I was using OpenVINO from v1.1 when it was still faster, and mainly haven't bothered to remove the flags since at worst it doesn't seem to make it slower. I didn't benchmark in v1.3 when not including the flag, so it may well be the case it isn't as helpful anymore.

It would get tricky since users can easily build their own image with `DV_OPENVINO_BUILD=1`, so the flags to run with OpenVINO can't be easily removed. But if the default google/deepvariant image doesn't have OpenVINO support, it would be nice if there was more of a user warning+exit or a warning+ignore the flag and run as if `--use_openvino=False` anyway since it is currently a legitimate flag to use.

**Comment by pichuan** [comment]
Yeah, we could remove `use_openvino` completely from call_variants.py. But given that I do still want to try it again in the future, it would be nice to keep it as a flag. (And like you said, users who build their own binaries or own Docker images, they can still enable it)

@ASLeonard  Will it be helpful if we add a bullet point in https://github.com/google/deepvariant/releases/tag/v1.4.0 to specifically call out that we're not building OpenVINO into out default Docker image?

**Comment by ASLeonard** [comment]
Yeah I think that would be fine. This case was more unfortunate as the missing OpenVINO leads to the missing `from tensorflow.python.tools import optimize_for_inference_lib` dependency, and so I assumed I had really messed something up as I hadn't changed anything with tensorflow.

On a slightly different note, the memory usage for call_variants (open_vino=False) in v1.4 is much better than v1.3 (open_vino=True) at  ~ 7gb compared to ~20gb RAM for a lot of medium coverage samples. Also postprocessing seems to be about 70% faster (although the previous runs had IO issues so probably inflated). Great improvements this release!
