### ISSUE TITLE
Error - reference genome files don't exist

### ISSUE THREAD

**Issue by Magpie1** [google/deepvariant#543]
Hello, 

When running DeepVariant I have a persistent error that the .fa and .fai reference genome files don't exist. I have checked that the given path is correct by displaying the files via copying the path given in the error sheet - the paths are correct and I don't have this problem with the input bam files,  

I'm running the program via a script on a Linux Ubuntu server. I'm using singularity v3.5.3, which is pre-installed and loaded as a module. The data is Illumina short read which has been mapped with BWA-Kit

The following is the script I'm using is: 

# Load modules needed
. /etc/profile.d/modules.sh
module load xxxxx/singularity/3.5.3

# inputs
reference=$2
bam=$1.final.bam
sampleid=$1
outdir=deepvar

# Create output directories
if [ ! -e deepvar ]; then mkdir deepvar; fi
if [ ! -e deepvar/$sampleid ]; then mkdir deepvar/$sampleid; fi

# Set singularity caches
if [ ! -e ${PWD}/.singularity ]; then mkdir ${PWD}/.singularity; fi
export SINGULARITY_TMPDIR=$PWD/.singularity
export SINGULARITY_CACHEDIR=$PWD/.singularity

# Download the image
if [ ! -e deepvariant.sif ]; then singularity build deepvariant.sif docker://google/deepvariant:latest; fi

# Run Deepvariant
singularity exec -p -B ${TMPDIR} -B ${PWD} deepvariant.sif /opt/deepvariant/bin/run_deepvariant \
            --model_type=WGS \
            --ref=${reference} \
            --reads=${bam} \
            --output_vcf=deepvar/${sampleid}/${sampleid}.vcf.gz \
            --output_gvcf=deepvar/${sampleid}/${sampleid}.g.vcf.gz \
            --num_shards=${NSLOTS}

I can run the test data on the command line but have the same problem when I use the above script to run it. I've not been able to find a fix, and have tried fixes suggested for similar issues on this site. 

Very appreciative of any suggestion for a solve. 

[runDV.sh.o21362497.txt](https://github.com/google/deepvariant/files/8985669/runDV.sh.o21362497.txt)

**Comment by Magpie1** [comment]
Solved

**Comment by MjelleLab** [comment]
How did you solve this? Same error here.
