### ISSUE TITLE
DeepTrio : using the flag --output_gvcf_merged does not create a merged file

### ISSUE THREAD

**Issue by Fred-07** [google/deepvariant#544]
Hello,

Please find below the description of an issue with the flag --output_gvcf_merged in DeepTrio.
Thanks for considering this request
Fred-07

**Describe the issue:**
Running the "DeepTrio quick start" commands with the additional flag --output_gvcf_merged produces no error but the"merged" file is not created.
https://github.com/google/deepvariant/blob/r1.4/docs/deeptrio-quick-start.md
All other expected files are created

**Setup**
  - Operating system: Linux 3.10.0-1160.71.1.el7.x86_64
  - DeepVariant version: 1.4.0
  - Installation method: singularity pull from docker, LSF as batch system
  - Type of data: "DeepTrio quick start" data

**Steps to reproduce:**
  - Command: additional flag
`--output_gvcf_merged "${OUTPUT_DIR}"/ALL.g.vcf.gz`

**Comment by kishwarshafin** [comment]
@Fred-07 ,

Can you please change your command from:
```
--output_gvcf_merged "${OUTPUT_DIR}"/ALL.g.vcf.gz
```
to:
```
--output_gvcf_merged /output/ALL.g.vcf.gz
```
And see if you see the file there?

Also, can you please put down the full command here to see if this is a directory mounting issue.

**Comment by akolesnikov** [comment]
Merging VCFs can be done using [GLnexus](https://github.com/dnanexus-rnd/GLnexus) which has been optimized for use with DeepVariant gVCFs. The process is described in the DeepTrio case studies ([DeepTrio whole genome sequencing case study](https://github.com/google/deepvariant/blob/r1.4/docs/deeptrio-wgs-case-study.md) and [Using DeepTrio for small variant calling from the trio sequenced with PacBio HiFi](https://github.com/google/deepvariant/blob/r1.4/docs/deeptrio-pacbio-case-study.md)), and in the manuscript, ["Accurate, scalable cohort variant calls using DeepVariant and GLnexus"](https://www.biorxiv.org/content/10.1101/2020.02.10.942086v2).

--output_gvcf_merged flag in run_deeptrio.py script is not supported.

**Comment by Fred-07** [comment]
Thank you for the explanations.
As this flag is proposed in the options of run_deeptrio.py, I thought it might be useful to get the merging at the time of calling.

I used GLnexus but some calls/merging are problematic, like this "denovo" one:
X       7811586 X_7811586_C_T   C       T       99      .       AF=0.166667;AQ=99;AB=0.285714;x_denovo=mysample1       GT:DP:AD:GQ:PL:RNC:VAF  0/1:35:25,10:67:99,0,67:..:0.285714     0/0:17:17,0:50:0,54,539:..:0    0/0:32:20,12:43:0,43,50:..:0.375
