### ISSUE TITLE
Issue with running using docker

### ISSUE THREAD

**Issue by tongh18** [google/deepvariant#545]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:**
(A clear and concise description of what the issue is.)
Issue encountered during running with Docker, thinking it is possibly due to tf not supported by m1 chip, here is the issue. 
The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
qemu: uncaught target signal 6 (Aborted) - core dumped

**Setup**
  - Operating system: MacOs (Mac mini/ m1 chip)
  - DeepVariant version:1.4.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  The test data from GitHub
**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by pichuan** [comment]
Hi @tongh18 ,
Unfortunately DeepVariant isn't designed to run on MacOS.
Can you run on other Unix machines (not MacOS)? Thank you!
