### ISSUE TITLE
Issues with parallelization of singularity-gpu image

### ISSUE THREAD

**Issue by davidecarlson** [google/deepvariant#546]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**: Yes

**Describe the issue:**

When using the singularity-gpu version, the make_examples step will only run sequentially (i.e., one shard processed at a time using only a single CPU) no matter what value I supply to ```--num_shards```

**Setup**
  - Operating system: CentOS 7
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  WES data from the tutorial

**Steps to reproduce:**
  - Command:
  
  ```
  #!/usr/bin/env bash

INPUT_DIR="input"
OUTPUT_DIR="output"

BIN_VERSION=1.4.0
export TMPDIR="$PWD/tmp_dir"

singularity run \
--nv -B /usr/lib/locale/:/usr/lib/locale/ \
docker://google/deepvariant:"${BIN_VERSION}"-gpu \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WES \
--ref=reference/GRCh38_no_alt_analysis_set.fasta \
--reads="${INPUT_DIR}"/HG003.novaseq.wes_idt.100x.dedup.bam \
--regions="${INPUT_DIR}"/idt_capture_novogene.grch38.bed \
--output_vcf="${OUTPUT_DIR}"/HG003.output.vcf.gz \
--output_gvcf="${OUTPUT_DIR}"/HG003.output.g.vcf.gz \
--intermediate_results_dir="${OUTPUT_DIR}/intermediate_results_dir" \
--num_shards=28
```

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Yes, though only sequentially.

**Any additional context:**

Based on the the documentation and by looking at the code, I _assume_ that the value for ```--num_shards``` is supposed to indicate how many chunks of sequence should be processed in parallel by the ```make_examples``` command, but this does not seem to be working for me.  Any suggestions or ideas?

Thanks!
Dave

**Comment by davidecarlson** [comment]
Hi Daniel,
Thanks for your response!

If I run that exact command, I get the following error:

> FATAL:   failed to retrieved path for /gpfs/scratch/decarlson/deepvariant_test/nproc: lstat /gpfs/scratch/decarlson/deepvariant_test/nproc: no such file or directory
> ERROR  : Child exit with status 255

However, if I specify the image:

```
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/ \
docker://google/deepvariant:"${BIN_VERSION}"-gpu nproc
```
The value returned is:

> 1

That said, I think this is some weird interaction with the Slurm HPC scheduler I'm using.  I'm doing this in an interactive job, where I've set `--ntasks-per-node=28`.  But I'm not seeing 28 available CPUs.

But if I open up a new terminal and ssh directly to the node my interactive job is running on, and then do

`singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/ docker://google/deepvariant:"${BIN_VERSION}"-gpu nproc`

The value returned is now:

> 28

Moreover, when I run the same command that I listed in my first post in this second terminal, make_examples is parallelized across all 28 shards as expected.

I think this is probably a configuration issue with our cluster, not something related to DeepVariant specifically.  If you agree, feel free to close the ticket.

Thanks for your help!
Dave

**Comment by danielecook** [comment]
ah good catch sorry I missed the image!

It has been a while since I have used slurm, but you could try:

```
#SBATCH --cpus-per-task=28
#SBATCH --ntasks-per-node=1 # Or don't set this.
```

See the explanation for `--ntasks-per-node`:

```
--ntasks-per-node=<ntasks>
Request that ntasks be invoked on each node. If used with the --ntasks option, the --ntasks option will take precedence and the --ntasks-per-node will be treated as a maximum count of tasks per node. Meant to be used with the --nodes option. This is related to --cpus-per-task=ncpus, but does not require knowledge of the actual number of cpus on each node. In some cases, it is more convenient to be able to request that no more than a specific number of tasks be invoked on each node. Examples of this include submitting a hybrid MPI/OpenMP app where only one MPI "task/rank" should be assigned to each node while allowing the OpenMP portion to utilize all of the parallelism present in the node, or submitting a single setup/cleanup/monitoring job to each node of a pre-existing allocation as one step in a larger job script.
```

I think the issue is that `--ntasks-per-node` is not allocating CPUs

**Comment by davidecarlson** [comment]
Thanks, Daniel.

Setting `--cpus-per-task=28` (or just not setting --ntasks at all) did the trick.

I'll go ahead and close this.
Thanks!
Dave
