### ISSUE TITLE
What hg38 would you suggest?

### ISSUE THREAD

**Issue by amyhouseman** [google/deepvariant#549]
Hello, 

I'm sorry this is not 100% related to deepvariant, but because it will likely impact the deepvariant results I was wondering what hg38 reference sequence you suggest to use for WES germline analysis. 

I see here:  https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/

I have been told two different things for which fna.gz to use, so it is getting a bit confusing. 

Do you have any ideas? 
Thanks!
Amy

**Comment by kishwarshafin** [comment]
Hi @amyhouseman ,

Please use: GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz

You can read further explanation of why this is the best version to use in this blog by Heng Li: https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use

**Comment by amyhouseman** [comment]
Amazing, thank you!
Amy

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
