### ISSUE TITLE
Quick Start Creates Files as Root, Now I can't delete them.

### ISSUE THREAD

**Issue by IndyHouseGuy** [google/deepvariant#550]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:**
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system: CentOS Linux release 7.9.2009
  - DeepVariant version: deepvariant:0.9.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  - Illumina, HG38, standard capture panel

**Steps to reproduce:**
  - Command: Snakemake command:
  - docker --rm -v {params.input_dir}/:/input -v {params.output_dir}/{params.sample}_DeepVariant:/output -v /data:/data -v {params.bed_dir}:/bed --user $CURRENT_UID google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WES --ref=/data/hg38.fa.gz --reads=/input/{params.sample}.bam  --regions=/bed/{params.primary_bed} --output_vcf=/output/{params.sample}_DeepVariant.vcf.gz --output_gvcf=/output/{params.sample}_DeepVariant.gvcf.gz --num_shards=12
  - actual command (XXXXX = removed for security purposes) 
  - docker --rm -v XXXXXXXXX/gatk_align_metrics_t/:/input -v XXXXXXXXX/deep_variant2/xGENIDTn2_DeepVariant:/output -v /XXXXXXXXX/deepvariant/data:/data -v XXXXXXXXX/bed:/bed google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WES --ref=/data/hg38.fa.gz --reads=/input/xGENIDTn2.bam  --regions=/bed/xgen-exome-hyb-panel-v2-targets-hg38.bed --output_vcf=/output/xGENIDTn2_DeepVariant.vcf.gz --output_gvcf=/output/xGENIDTn2_DeepVariant.gvcf.gz --num_shards=12
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

Yes, the quickstart creates files as root.  As it's a high performance computing cluster, I am no longer able to delete these files.  How do I stop it from creating files as root?

**Any additional context:**

**Comment by kishwarshafin** [comment]
hi @IndyHouseGuy ,

You can add 
```
docker run -it -v /data:/data \
-u `id -u`:`id -g`
```
to your docker command to avoid this issue.

**Comment by IndyHouseGuy** [comment]
Thank you for the quick response.

I tried that and still got files by root.  I tried setting the uid and
groupid explicitly and using the dynamic method you recommended.

Please advise.

command:

deep_dir=deep_variant_id80429g20

mkdir -p XXXXXXXXXXXXXXXXXX/$deep_dir

docker pull google/deepvariant:0.9.0


# This was ran, XXXXXXX are directories marked out for security purposes.

docker run -it -u 80429:20 -v
XXXXXXXXXXXXXXXXXX/gatk_align_metrics_t/:/input -v
XXXXXXXXXXXXXXXXXX/$deep_dir/xGENIDTn2_DeepVariant:/output -v
/XXXXXXXXXXXXXXXXXX/analysis/deepvariant/data:/data -v
XXXXXXXXXXXXXXXXXX/bed:/bed google/deepvariant:0.9.0
/opt/deepvariant/bin/run_deepvariant --model_type=WES
--ref=/data/hg38.fa.gz --reads=/input/xGENIDTn2.bam
--regions=/bed/xgen-exome-hyb-panel-v2-targets-hg38.bed
--output_vcf=/output/xGENIDTn2_DeepVariant.vcf.gz
--output_gvcf=/output/xGENIDTn2_DeepVariant.gvcf.gz --num_shards=12

Results:

ls -ltrh deep_variant_id80429g20/
drwxr-sr-x 2 root root 4.0K Aug  4 12:15 xGENIDTn2_DeepVariant

And I've set the command dynamically:

command:

deep_dir=deep_variant_dynamic1b
mkdir -p /XXXXXXXXXXXXXXXXXXXXX/$deep_dir
docker pull google/deepvariant:0.9.0
# this was ran, some directories censored by XXXXXXXXXX for security reasons
LINE='docker run -it -u `id -u`:`id -g` -v
/XXXXXXXXXXXXXXXXXXXXX/gatk_align_metrics_t/:/input -v
/XXXXXXXXXXXXXXXXXXXXX/$deep_dir/xGENIDTn2_DeepVariant:/output -v
/XXXXXXXXX/deepvariant/data:/data -v /XXXXXXXXXXXXXXXXXXXXX/bed:/bed
google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant
--model_type=WES --ref=/data/hg38.fa.gz --reads=/input/xGENIDTn2.bam
--regions=/bed/xgen-exome-hyb-panel-v2-targets-hg38.bed
--output_vcf=/output/xGENIDTn2_DeepVariant.vcf.gz
--output_gvcf=/output/xGENIDTn2_DeepVariant.gvcf.gz --num_shards=12'
echo "$LINE"
eval $LINE


Results:

ls -ltrh deep_variant_dynamic1b
drwxr-sr-x 2 root root 4.0K Aug  4 12:24 xGENIDTn2_DeepVariant

**Comment by IndyHouseGuy** [comment]
Trying to make this more legible.   Replying via email is convenient but not the most effective:

I've tried using `--user`

```
docker --rm  --user $CURRENT_UID
```

and the `-u` function recommended but dynamic:

```
docker run -it -u `id -u`:`id -g`

```
And explicit:
```
docker run -it -u 80429:20
```

Both output root owned files.

Full commands

Explicit user assignment:
```
0.9.0: Pulling from google/deepvariant
Digest: sha256:831ca296035d5317d98cb33034b484cabccc3c7210c5353c8f132c52a7705046
Status: Image is up to date for google/deepvariant:0.9.0
docker.io/google/deepvariant:0.9.0
docker run -it -u 80429:20 -v /XXXXXX/gatk_align_metrics_t/:/input -v /XXXXXX/$deep_dir/xGENIDTn2_DeepVariant:/output -v /XXXXXX/analysis/deepvariant/data:/data -v /XXXXXX/bed:/bed google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WES --ref=/data/hg38.fa.gz --reads=/input/xGENIDTn2.bam  --regions=/bed/xgen-exome-hyb-panel-v2-targets-hg38.bed --output_vcf=/output/xGENIDTn2_DeepVariant.vcf.gz --output_gvcf=/output/xGENIDTn2_DeepVariant.gvcf.gz --num_shards=12
```

Dynamic user assignment:

```
0.9.0: Pulling from google/deepvariant
Digest: sha256:831ca296035d5317d98cb33034b484cabccc3c7210c5353c8f132c52a7705046
Status: Image is up to date for google/deepvariant:0.9.0
docker.io/google/deepvariant:0.9.0
docker run -it -u `id -u`:`id -g` -v /XXXXXX/gatk_align_metrics_t/:/input -v /XXXXXX/$deep_dir/xGENIDTn2_DeepVariant:/output -v /XXXXXX/analysis/deepvariant/data:/data -v /XXXXXX/bed:/bed google/deepvariant:0.9.0 /opt/deepvariant/bin/run_deepvariant --model_type=WES --ref=/data/hg38.fa.gz --reads=/input/xGENIDTn2.bam  --regions=/bed/xgen-exome-hyb-panel-v2-targets-hg38.bed --output_vcf=/output/xGENIDTn2_DeepVariant.vcf.gz --output_gvcf=/output/xGENIDTn2_DeepVariant.gvcf.gz --num_shards=12
```

All create root files.

Any help is most welcome.

**Comment by IndyHouseGuy** [comment]
Results:

Explicit:
```
ls -tlrh deep_variant_id80429g20/
drwxr-sr-x 2 root root 4.0K Aug  4 12:15 xGENIDTn2_DeepVariant
```

Dynamic:
```
ls -tlrh deep_variant_id80429g20/
drwxr-sr-x 2 root root 4.0K Aug  4 12:15 xGENIDTn2_DeepVariant
```

**Comment by kishwarshafin** [comment]
@IndyHouseGuy ,

I see that your files have the same timestamp. Are you asking about how to remove the existing files that you have already created with root? 

To check if `-u` parameters are working, can you please output to a new directory to see if that helps.

**Comment by kishwarshafin** [comment]
@IndyHouseGuy , 

Can you please do a simpler test? According to [this](https://stackoverflow.com/questions/50317119/docker-container-creating-directories-owned-by-root-i-need-them-owned-by-10001), there can be a number of things that might cause this behavior, including implicitly running docker as root in the system.

In my local test, I have this behavior
```
# Command 1
time docker run -it -v /data:/data \
google/deepvariant:0.9.0 \
mkdir /data/kishwar/test_ubuntu_docker

# Command 2
docker run -it -u `id -u`:`id -g` -v /data:/data \
google/deepvariant:0.9.0 \
mkdir /data/kishwar/test_ubuntu_docker_u
```
Output:
```
root   root                  4.0K Aug  5 14:55 test_ubuntu_docker/
shafin primarygroup 4.0K Aug  5 14:55 test_ubuntu_docker_u/
```
Can you please run this and see if you get the same behavior?

**Comment by IndyHouseGuy** [comment]
I've got it working now.  What I reported earlier was correct and I'm happy to explore this further.  Oddly enough, I now have a bed file owned by root as well.  I do not have root access on this machine which explains why some HPC's have banned docker.

I'll investigate the differences and report back.  Good new is I have it working so there is no action need on your end.

**Comment by danielecook** [comment]
I will close this for now given that it seems to be resolved. Feel free to reopen later if needed.
