### ISSUE TITLE
Overlapping regions in bed file

### ISSUE THREAD

**Issue by amyhouseman** [google/deepvariant#551]
Hello!

I've just realised that my bed file has some overlapping regions (I suspect from converting it from hg19 to hg38 with Liftover).

Will this impact deep variants results? Should I merge these regions before use? 

Thanks!
Amy

**Comment by danielecook** [comment]
@amyhouseman I believe we merge overlaps when processing bedfiles. See this snippet: https://github.com/google/deepvariant/blob/d2a3aca8691318221e794594ea08e7c88e21359b/third_party/nucleus/util/ranges.py#L123-L125

So you should not have to merge those regions.
