### ISSUE TITLE
Hybrid model with ONT + Illumina

### ISSUE THREAD

**Issue by imdanique** [google/deepvariant#554]
Hello! Thank you for such a wonderful tool.

We have ONT and Illumina reads for the same samples. Can I use DeepVariant Hybrid model but with ONT reads instead of Pacbio? Has someone tried this?

**Comment by kishwarshafin** [comment]
hello @imdanique ,

The hybrid model is trained on PacBio HiFi + Illumina data, currently there's no model/mode available that supports ONT+Illumina data in the manner this hybrid mode is used.
