### ISSUE TITLE
--regions results in 'parallel: Error: Command line too long (<num> >= 65524)'

### ISSUE THREAD

**Issue by dennishendriksen** [google/deepvariant#556]
Running DeepVariant/DeepTrio 1.4.0 using singularity, based on the provided docker images, with many regions results in a `'parallel: Error: Command line too long (<num> >= 65524)` error.

My use case is processing .bam files aligned against `GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz` (containing 2500+ contigs) in parallel. Splitting by contig would result in 2500+ chunks which introduces too much overhead so I group contigs together based on the number of reads. In practice this results in chunks for chr1, ... chr22, chrX, chrY, chrM and one chunk for the other ~2500 contigs. This results in a very long command-line arg for `--regions` and thus the error.

What would you think of adding an additional `--regions-file` command-line argument similar to e.g. [bcftools](https://samtools.github.io/bcftools/bcftools.html) which accepts a text file containing one region per line?

**Comment by kishwarshafin** [comment]
@dennishendriksen ,

Sorry, I want to make sure that I understand you question correctly. Are you trying to set up your own parallelization scheme or you are having this issue with the scheme we have already set up for DeepVariant?

**Comment by dennishendriksen** [comment]
hello @kishwarshafin, thank you for your quick reply. I'm trying to run DeepVariant on a cluster of compute nodes and in order to benefit from that I indeed parallelize the work on the different nodes by using the `--regions` command-line argument of DeepVariant.

**Comment by kishwarshafin** [comment]
@dennishendriksen ,

You can possibly achieve this by converting your regions from string to a bed file. Please see the specification of the regions parameter:
```
--regions: Optional. Space-separated list of regions we want to process. Elements can be region literals (e.g., chr20:10-20) or paths to BED/BEDPE files.
    (default: '')
```

**Comment by dennishendriksen** [comment]
@kishwarshafin,
thank you for the suggestion, I hadn't thought of that and will give it a try.

**Comment by kishwarshafin** [comment]
@dennishendriksen ,

Closing this issue. Please reopen if you have further questions.
