### ISSUE TITLE
Mishandling of IUPAC ambiguous bases sometimes causes malformed VCF outputs

### ISSUE THREAD

**Issue by rickymagner** [google/deepvariant#560]
Hi,

I have a few VCFs on ONT data called with DV (technically [Pepper](https://github.com/kishwarshafin/pepper) but I suspect this is an upstream issue). On a number of these files, it just happens that a deletion is called over a region of HG38 which contains one of the [IUPAC ambiguous base codes](https://www.bioinformatics.org/sms/iupac.html). This means there is a reference allele which looks like e.g. `TW` and the variant is `T`, so there is a deletion of a `W` base. However, because `W` is not an allowed base by htsjdk (and VCF Spec 4.2 / 4.3), this causes a ton of genomics tools to throw an exception when they get to those lines. 

There are fewer than 100 places in HG38 where a non-standard base (not A/C/G/T/N) is placed (see e.g. `chr3:16902883`), but for some reason it seems the long reads DV data I've been using hits deletions on these sites somewhat frequently. I don't know what the best solution might be, whether replacing them with `N` bases, or substituting them as recommended in [VCF Spec 4.3](https://samtools.github.io/hts-specs/VCFv4.3.pdf), or something else. But it would be great to have a fix with documentation about how it's resolved.

**Comment by kishwarshafin** [comment]
@rickymagner ,

Can you please fetch one line of such VCF record? I think the issue is upstream of DeepVariant and it's happening because PEPPER allows non A/C/G/T bases. Filtering needs to happen upstream.

**Comment by rickymagner** [comment]
Hi, thanks for getting back about this. Here is a sample line:

`chr3    16902881        .       TGB     T       1.4     RefCall .       GT:GQ:DP:AD:VAF:PL      ./.:6:26:24,0:0:0,16,4`

Here we see a deletion of `B` in reference. Are you saying that this is technically not allowed to be output by DeepVariant, but rather an issue with Pepper? If that's the case, I can migrate this issue over to that repo.

**Comment by kishwarshafin** [comment]
@rickymagner ,

In this case the candidates are generated by PEPPER, so this call is happening because PEPPER picked this as a candidate. One quick fix on your end would be to filter the VCF for 'PASS' variants only as DeepVariant would assign RefCall to all of these candidates.

**Comment by rickymagner** [comment]
Thanks, that's a good suggestion. I'll pass this issue over to PEPPER to see if they want to address it in their codebase.
