### ISSUE TITLE
No output file generating in quick start

### ISSUE THREAD

**Issue by aalfi** [google/deepvariant#561]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:** After running the code in the deepvariant docker container (quick start), the output vcf files have not been generated.
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system:Mac OS 
  - DeepVariant version: Latest
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: Test files(sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command: sudoa docker run \-v "${INPUT_DIR}":"/input" \-v "${INPUT_DIR}":"/output" \google/deepvariant:"${BIN_VERSION}" \/opt/deepvariant/bin/run_deepvariant \--model_type=WES \--ref=/input/ucsc.hg19.chr20.unittest.fasta \--reads=/input/NA12878_S1.chr20.10_10p1mb.bam \--regions "chr20:10,000,000-10,010,000" \--output_vcf=/output/output.vcf.gz \--output_gvcf=/output/output.g.vcf.gz \--num_shards=1  \--dry_run=true
  - Error trace: No error.(if applicable)

**Comment by kishwarshafin** [comment]
@aalfi ,

Please follow the instructions here: https://github.com/google/deepvariant/blob/r1.4/docs/deeptrio-pacbio-case-study.md

I see that you have `--dry_run=true` which would not run anything and would simply print out the commands:
```
--[no]dry_run: Optional. If True, only prints out commands without executing them.
    (default: 'false')
```

**Comment by aalfi** [comment]
Got it! Thank you!!
