### ISSUE TITLE
Adaptation to polyploid organisms.

### ISSUE THREAD

**Issue by RaphaelSanchesUSP** [google/deepvariant#562]
Is it possible to modify the DeepVariant source code to get correct CNN outputs for polyploid organisms?

**Comment by AndrewCarroll** [comment]
Hi @RaphaelSanchesUSP 

It will likely be very difficult to do so regardless of the approach. However, I'd like to better understand what sort of output you would look for? Would it be to extend DeepVariant's output classes beyond REF, HET, HOM into more than diploid output, or is it instead to train on polyploid species and repurpose HET to be (some number of non-ref and non-hom alleles without further specification)?

Thank you,
Andrew

**Comment by RaphaelSanchesUSP** [comment]
Hi @AndrewCarroll 

Thank you very much for your promptness and attention.
I verified that DeepVariant has in several parts of the code, parameters for diploid organisms and two alleles. Like the small example function below:

`def most_likely_genotype(predictions, ploidy=2, n_alleles=2):`

The mentioned function is used in the post-processing process of calling variants.

My goal is to modify the DeepVariant so that the user can enter the ploidy and alleles needed for the CNN to provide the expected results, as well as the VCF files. Ploidy would be possible to obtain from the input VCF file, but alleles wouldn't.

**Comment by RaphaelSanchesUSP** [comment]
Hi @AndrewCarroll 

The most likely and specific choice would be the following:

_**is it instead to train on polyploid species and repurpose HET to be (some number of non-ref and non-hom alleles without further specification)?**_

I analyzed some publications comparing DeepVariant with other tools in terms of results, but I identified some flaws in the DeepVariant's execution in these comparisons on human data.

My reference for the modifications follows below:

[Reference](https://genome.sph.umich.edu/wiki/Relationship_between_Ploidy,_Alleles_and_Genotypes)

**Comment by AndrewCarroll** [comment]
Hi @RaphaelSanchesUSP 

Between the two approaches, this - **repurpose HET to be (some number of non-ref and non-hom alleles without further specification)?** is the one which would require much less work. Of the approaches, this might not require large changes and might be possible with training alone.

One component that could be limiting for this approach is the ability to identify extremely well characterized samples that could be used as truth examples. Is there a polyploid species where the variants relative to the reference are known without almost any error, as is the case for the genome in a bottle samples for humans?

**Comment by pichuan** [comment]
I'm closing this issue. Feel free to open another issue if you still have any questions. And feel free to add more comments if you want to discuss further.
