### ISSUE TITLE
Optionally drop channel 18

### ISSUE THREAD

**Issue by JosephLalli** [google/deepvariant#563]
**Describe the issue:**
I am attempting to use DeepVariant 1.4 with a model trained on DeepVariant 1.3. I encounter the error:
"ValueError: The number of channels in examples and checkpoint should match, but the checkpoint has 6 channels while the examples have 7."

**Setup**
  - Operating system: Linux Ubuntu 20.04
  - DeepVariant version: 1.4
  - Installation method: Docker
Just regular bam files being called on the T2T reference fasta.

**Steps to reproduce:**
/opt/deepvariant/bin/run_deepvariant \
    --ref=hprc-jun1-mc-chm13-minaf.0.1.fasta \
    --reads=HSB340-CHM13v2.chrY.sorted.deduped.cram \
    --customized_model=model.ckpt-364300 \
    --output_vcf=HSB340-CHM13v2.chrY.deepvariant.vcf.gz \
    --output_gvcf=HSB340-CHM13v2.chrY.deepvariant.g.vcf.gz \
    --model_type WGS \
    --make_examples_extra_args phase_reads=true,channels=blank \
    --regions CHM13v2.chrY \
    --num_shards=24

parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "hprc-jun1-mc-chm13-minaf.0.1.fasta" --reads "HSB340-CHM13v2.chrY.sorted.deduped.cram" -examples "/tmp/tmpwn2kfxca/make_examples.tfrecord@24.gz" --channels "blank" --gvcf "/tmp/tmpwn2kfxca/gvcf.tfrecord@24.gz" --phase_reads --regions "CHM13v2.chrY" --task {}

time /opt/deepvariant/bin/call_variants --outfile "/tmp/tmpwn2kfxca/call_variants_output.tfrecord.gz" --examples "/tmp/tmpwn2kfxca/make_examples.tfrecord@24.gz" --checkpoint "model.ckpt-364300" --openvino_model_dir "/tmp/tmpwn2kfxca"
I0901 22:59:14.275113 140554215814976 call_variants.py:317] From /tmp/tmpwn2kfxca/make_examples.tfrecord-00000-of-00024.gz.example_info.json: Shape of input examples: [100, 221, 7], Channels of input examples: [1, 2, 3, 4, 5, 6, 18].
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_2ucnuw5e/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_2ucnuw5e/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_2ucnuw5e/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_2ucnuw5e/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
    call_variants(
  File "/tmp/Bazel.runfiles_2ucnuw5e/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 363, in call_variants
    raise ValueError('The number of channels in examples and checkpoint '
ValueError: The number of channels in examples and checkpoint should match, but the checkpoint has 6 channels while the examples have 7.

**Any additional context:**
DeepVariant 1.4 added an additional default channel. This appears to have broken all previously trained models. Using the convenient "run_deepvariant" script with the channels=blank options does not result in make_examples generating input examples with only six features.

***Desired Output:***
An option in run_deepvariant that will allow for the creation of example files with the previously standard six input channels.

**Comment by AndrewCarroll** [comment]
Hi @JosephLalli 

The number of channels in the input establishes the shape of the input. A given model also has a shape based on the channels that it expects to see. In v1.4, we added a new channel for WGS and WES models to represent the insert size between read pairs. This occupies the 7th channel. Our default model for v1.4 expects that channel to be there.

If you want to run with the v1.4 model, you will have to use the v1.4 Docker image to make the examples. Is there a reason this would be a problem?

**Comment by pichuan** [comment]
@JosephLalli I'll close this issue because we haven't heard back from you. Please feel free to reopen , or open another issue as needed. Thanks!
