### ISSUE TITLE
locale setting failed with latest docker image. 

### ISSUE THREAD

**Issue by yangyxt** [google/deepvariant#566]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:**
According to the running log: the setlocale failed when trying to change LC_ALL to 'en_US.UTF-8'

**Setup**
  - Operating system: CentOS7
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): docker pull 
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) DNA seq

**Steps to reproduce:**
  - Command: 
  - singularity run \
    -B "/paedyl01/disk1/yangyxt,/usr/lib/locale" \
    --env LANG="en_US.UTF-8" \
    --env LC_ALL="C" \
    --env LANGUAGE="en_US.UTF-8" \
    --env LC_CTYPE="UTF-8" \
   ......

  - Error trace: (if applicable)
![image](https://user-images.githubusercontent.com/40780228/190950415-84faaa5d-7371-42a7-9e13-f6caf53a3dea.png)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by pichuan** [comment]
Hi @yangyxt ,
can you try a command like:
https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-quick-start.md#notes-on-singularity ?

**Comment by yangyxt** [comment]
> Hi @yangyxt , can you try a command like: https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-quick-start.md#notes-on-singularity ?

Thanks for the response. I tried a command without --env argument in the very beginning and the warning logs were still what is in the screenshot above. Then I started to alter the env variable with --env argument and still got the same warning messages.

**Comment by pichuan** [comment]
If i recall correctly, there might be warnings but it didn't seem to affect the run.
Can you confirm whether you're actually getting unexpected results or not? Thank you!

**Comment by yangyxt** [comment]
> 

Yes. I didn't get unexpected results when only warning messages are shown. I just wonder whether the warning message would affect the results in some hidden way that I'm not aware of. So I tried to remove the warning message and ended up finding out it's somehow due to the lack of a dependency, locale, in the docker image.

**Comment by pichuan** [comment]
Thanks @yangyxt . Good to know that you're not seeing strange behaviors despite the warning messages. I'll close this issue now.
