### ISSUE TITLE
How can I use fastq files as an input?

### ISSUE THREAD

**Issue by Rvvijays** [google/deepvariant#570]

**Comment by Rvvijays** [comment]
Every where I have seen deepvariant example with .bam files. is there any way I can use fastq files as input?

**Comment by AndrewCarroll** [comment]
Hi @Rvvijays 

DeepVariant always takes either BAM or CRAM files as input. It won't take FASTQ directly as input, so you will need to map your FASTQ reads to a reference genome with a method like BWA for Illumina data or pbmm2/minimap2 for PacBio data.

**Comment by pichuan** [comment]
Hi @Rvvijays ,
thanks for your questions. With Andrew's answer above, I'll close this issue.

**Comment by Rvvijays** [comment]
Will anyone help me with the whole process to convert fastq files to vcf using deepvariant, along with conversation of fastq to bam,

please i will be grateful

**Comment by pichuan** [comment]
@Rvvijays 
Please take a look at https://github.com/lh3/bwa for FASTQ --> BAM.
Once you have a BAM file, you can use DeepVariant.
