### ISSUE TITLE
Outputting basepair resolution in DeepVariant

### ISSUE THREAD

**Issue by mdriller** [google/deepvariant#571]
I was planning to analyse runs of homozygosity in a genome assembly with Plink using DeepVariant for the variant calling. Unfortunately Plink needs basepair resolution in the input vcf file, e.g. a vcf/gvcf file that includes homozygous reference calls as well. I tried different options in DeepVariant but there seems to be no option for basepair resolution. GATK has the option to output this (-ERC BP_RESOLUTION) but since DeepVariant is more accurate and much faster I was wondering if would it be possible to add such a feature in the future? 

**Setup**
  - Operating system: CentOS
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) Genome assembly plus PacBio HIFI or Illumina WGS

**Comment by akolesnikov** [comment]
Hello,
I created a tracking bug to add this feature to DeepVariant. We will post an update once we finalize the plan for the next release.

**Comment by AndrewCarroll** [comment]
Hi @mdriller 

My answer to your question will depend on what exactly you will need from Plink and what sort of cohort approach you have. 

If you just want to be able to run Plink on the joint genotype results, I wonder if you can try following the process which was performed for UKBiobank to convert their DeepVariant exome joint calls into PLINK format. That is the section *Conversion of pVCF to PLINK and BGEN files* [from the UKBiobank WES Protocol](https://biobank.ctsu.ox.ac.uk/crystal/ukb/docs/UKB_WES_Protocol.pdf)

I hope this will work, as it is not generally our preference to replicate the functionality of -ERC BP_RESOLUTION, and this is likely to make writing output much slower.

If, instead, you want calls at specific sites (similar to a genotyping chip approach but with NGS data), I would say that is is possible to force genotyping at a given set of alleles with one of the modules of DeepVariant (VCF candidate importer). I suspect this isn't what you want though.

Thank you,
Andrew

**Comment by pichuan** [comment]
Hi @mdriller ,
It'll be great if you can help us understand your use case a bit more (see @AndrewCarroll 's reply above) so we can follow up with you. Thanks!

**Comment by mdriller** [comment]
Hi all,

sorry about the late reply I was testing the UKBiobank WES Protocol provided by Andrew but unfortunately it does not seem fix our problem.
The general issue is that to identify runs of homozygosity(ROH) with plink you can also just provide a vcf file but this vcf file needs a base resolution e.g. an entry for each position, whether it is variable or not:
`
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  PacBio_CCS
SUPER_1 1       .       C       .       .       .       DP=49   GT:AD:DP:RGQ    0/0:49:49:99
SUPER_1 2       .       C       .       .       .       DP=50   GT:AD:DP:RGQ    0/0:50:50:99
SUPER_1 3       .       T       .       .       .       DP=54   GT:AD:DP:RGQ    0/0:54:54:99
SUPER_1 4       .       A       .       .       .       DP=61   GT:AD:DP:RGQ    0/0:61:61:99
...
`
And we were just wondering if there is a possibility to generate such a vcf file using DeepVariant.

Thanks again for all the replies and help.

best reagrds,

Max

**Comment by AndrewCarroll** [comment]
Hi @mdriller 

DeepVariant itself does not have this option. 

However, as I understand you really just want to convert a single sample gVCF to a reference expanded VCF. bcftools may allow you to efficiently do this with the option:

bcftools convert --gvcf2vcf ${VCF} --fasta-ref ${REF}

**Comment by BeGenDiv** [comment]
Hi @AndrewCarroll,

thank you very much this solves the issue. DeepVariant is using the minimum coverage/depth for the "summed up" homozygous regions in the gvcf right? 

thanks again for all the help,

Max

**Comment by mdriller** [comment]
Hi @AndrewCarroll,

thank you very much this solves the issue. DeepVariant is using the minimum coverage/depth for the "summed up" homozygous regions in the gvcf right?

thanks again for all the help,

Max

**Comment by AndrewCarroll** [comment]
@mdriller 

Yes, I believe that is correct. The reference blocks of the GVCF have the minimum coverage over the span of the reference block.

**Comment by pichuan** [comment]
Hi @mdriller ,
I'm closing this issue now.
My understanding is that your issue is resolved by @AndrewCarroll 's suggestion. So we'll also close the internal tracking issue, and we won't plan to build this directly into DeepVariant.
