### ISSUE TITLE
The deep variant wrapper dv_call_variants.py crushing when installed using conda.

### ISSUE THREAD

**Issue by akiss-me** [google/deepvariant#573]
the deep variant wrapper dv_call_variants.py crushing when installed using conda.

**Setup**
  - Ubuntu 20.04:
  - DeepVariant version - 1.4.0:
  - Installation method - Conda
  - Type of data - sequencing, illumina

**Steps to reproduce:**
  - Command:
dv_call_variants.py --outfile OUTFILE --examples EXAMPLES --sample SAMPLE

  - Error trace: (if applicable) 
Traceback (most recent call last):
File "/tmp/Bazel.runfiles_zviaa5zy/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 39, in <module>
import numpy as np
ModuleNotFoundError: No module named 'numpy'

numpy installed in enviroment

**Comment by akolesnikov** [comment]
Hi akiss-me,

The conda-deepvariant package is a community contribution by @chapmanb and is not maintained directly by the DeepVariant team -- we are not experts on Conda, unfortunately.
You may try to run using [Singularity](https://sylabs.io/docs/). See [Quick Start](https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-pacbio-model-case-study.md)
