### ISSUE TITLE
DeepTrio

### ISSUE THREAD

**Issue by ankurc17** [google/deepvariant#574]
Hello Team,

This is regarding deepTrio. I have tried creating the docker images for version 1.2, 1.4 as well as gpu-latest. However, running into issues at all the versions. Is there a way to connect with the team to understand the issues and help in running it?

I can be reached at ankur.a@lifecell.in

Looking forward to hearing from you.

**Comment by pichuan** [comment]
Hi @ankurc17 
Can you tell us more about what the issues are?
For example, what OS are you using, what command did you run and what error messages you've seen.
It'll be great if we can assist you here, because then other users can learn from our conversation too.

**Comment by ankurc17** [comment]
Command Used: sudo docker run -v "${PWD}":"/input" -v "${PWD}/output":"/output" -v /Resources/:/Res deeptrio_gpu:latest /opt/deepvariant/bin/deeptrio/run_deeptrio --model_type WGS --call_variants_extra_args="use_openvino=true" --ref=/Res/Hg19_chr/hg19.fa --reads_child /input/41420446-BABY.bam --reads_parent1 /input/41420446-FB.bam --reads_parent2 /input/41420446-MB.bam --output_vcf_child /output/Baby.deeptrio.vcf.gz --output_vcf_parent1 /output/Fb.deeptrio.vcf.gz --output_vcf_parent2 /output/Mb.deeptrio.vcf.gz --sample_name_child 'Baby' --sample_name_parent1 'Fb' --sample_name_parent2 'Mb' --num_shards=38 --output_gvcf_child /output/Baby.deeptrio.g.vcf.gz --output_gvcf_parent1 /output/Fb.deeptrio.g.vcf.gz --output_gvcf_parent2 /output/Mb.deeptrio.g.vcf.gz

I have captured the outputs in a log file. Do suggest how to share the same with you?

![image](https://user-images.githubusercontent.com/27851922/195591985-6c022925-816b-4bce-af50-8d31377b84d9.png)

![image](https://user-images.githubusercontent.com/27851922/195592082-e7e60d2d-92d6-431e-b4a2-a35c22314417.png)

**Comment by ASLeonard** [comment]
This is probably causing the issues `--call_variants_extra_args="use_openvino=true"` as openvino is not currently supported (#541) and throws the same error you see here. Running without that extra arg should then work.

**Comment by pichuan** [comment]
Hi @ankurc17 ,
@ASLeonard 's answer above is likely the issue. I'll close this bug, but if it still doesn't work, please feel free to re-open, or open a new issue!
