### ISSUE TITLE
Is it possible to produce one html file for a combination of sequences?

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#575]
Is it possible to produce the html file plots for a combination of sequences ran through deepvariant?

Thanks!
Amy

**Comment by akolesnikov** [comment]
Hi Amy,
Unfortunately, there is not direct way to combine multiple runs. Could you please provide more details what kind of plots you'd like to generate?

**Comment by kishwarshafin** [comment]
hi @amy-houseman , I'm closing this issue for now. Please reopen/comment if you have further suggestions or questions.

**Comment by amy-houseman** [comment]
Hello, sorry for the late reply, I was away! Maybe something like the initial average variant types plot for the different vcf files called by deepvariant? Just something to easily give a nice overview of a dataset, no worries if not though! Thanks! Amy

**Comment by pichuan** [comment]
Hi @amy-houseman ,
Can you take a look at https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-vcf-stats-report.md and see if this is helpful for you?
As @kishwarshafin said, we don't have tools that run on multiple VCFs. But it is possible to just run the analysis tool on existing VCF file. (If that's what you're looking for)
