### ISSUE TITLE
Trouble with DeepVariant after running Minimap2

### ISSUE THREAD

**Issue by moyarod** [google/deepvariant#579]
Hello,

I am trying to run Deepvariant in Galaxy with a bam file from Minimap2 but it sais there is a problem with the vcf format. Quite new using these tools and I am lost! please anyone could help me?
![Captura](https://user-images.githubusercontent.com/116640228/197752262-65531e02-1092-46cb-9f8a-aa3ca3c75567.JPG)

**Comment by kishwarshafin** [comment]
Hello, as you can see the error message is "samtools: command not found". Can you please see if there's a way you can install samtools for your environment?

**Comment by moyarod** [comment]
> 

Thanks for answering. I forgot to say that the samtools are already installed.

**Comment by kishwarshafin** [comment]
@moyarod ,

In that case, it would be ideal if you seek help from the galaxy community: https://help.galaxyproject.org/ as this is a platform-specific error and we can't reproduce this on our end.
