### ISSUE TITLE
Can you determine why a variant was refcalled based on scores or stats in the vcf?

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#582]
Hello, 

This might be naive question but in the outputted vcf files are there any scores or outputs that can be used to determine why a variant may have been called as refcall or not, in comparison to those called as passed? I have read other answers in relation to this topic but I am still a bit confused.

Thanks!
Amy

**Comment by danielecook** [comment]
Hi @amy-houseman 

Here is an example refcall:

```
chr20   64096963        .       G       C       0       RefCall .       GT:GQ:DP:AD:VAF:PL      0/0:61:15:11,3:0.2:0,65,63
```

The FORMAT fields are `GT:GQ:DP:AD:VAF:PL`

These are defined in the header:

```
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
##FORMAT=<ID=GQ,Number=1,Type=Integer,Description="Conditional genotype quality">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read depth">
##FORMAT=<ID=MIN_DP,Number=1,Type=Integer,Description="Minimum DP observed within the GVCF block.">
##FORMAT=<ID=AD,Number=R,Type=Integer,Description="Read depth for each allele">
##FORMAT=<ID=VAF,Number=A,Type=Float,Description="Variant allele fractions.">
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
##FORMAT=<ID=MED_DP,Number=1,Type=Integer,Description="Median DP observed within the GVCF block rounded to the nearest integer.">
```

* `AD` (11,3) gives a hint as to why this is probably a ref call. 11 reads support the reference allele (G), whereas only 3 support the ALT allele (C). 
* `VAF` - Similarly, the VAF is 0.2, so there is limited support for the ALT allele.
* `PL` (0,65,63) - The phred-scaled genotype likelihoods are derived from the model outputs for the three possible diploid states (HOM-REF, HET, HOM-ALT). Lower values indicate a greater likelihood for a given genotype. 

One thing you might consider is looking at the distribution of PL values. If you suspect a refcall might be incorrect, you can examine PL values to get a sense of how much confidence our model has for a given variant call. In practice, we observe that these values are well calibrated. See Figure 2 of the [DeepVariant paper](https://www.biorxiv.org/content/10.1101/092890v6.full.pdf) for further details.

**Comment by amy-houseman** [comment]
Thank you so much!
