### ISSUE TITLE
Use of deepvariant for targeted haloplex data?

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#583]
Hello,

I have inherited some haloplex data, and ideally I would like to use deepvariant for its analyses as I have used this for my WES. 

Do you think deepvariant would work proficiently for haloplex data?

Thanks!
Amy

**Comment by akolesnikov** [comment]
Hello Amy,

We haven't tested DeepVariant with HaloPlex data. WES model would be the best fit for this kind of data but there is no guaranty. Please let us know if you have any further questions. 

Thanks
Alex
