### ISSUE TITLE
Problem encountered while make_example 

### ISSUE THREAD

**Issue by guoquankisscall** [google/deepvariant#589]
Hello, I am trying to train my pacbio model using ”DeepVariant-inception_v3-1.4.0+data-pacbio_standard“ on ”HG003.pacbio-hifi.21x.haplotag.grch38.bam“.  I noticed that the pre-trained model accepted the following channels: "channels": [1, 2, 3, 4, 5, 6, 7, 9, 10]}. I tried the following command:

( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --line-buffer \
    sudo docker run \
      -v ${BASE}:${BASE} \
      google/deepvariant:"${BIN_VERSION}" \
      /opt/deepvariant/bin/make_examples \
      --mode training \
      --ref "${REF}" \
      --reads "${BAM_003}" \
      --examples "${MEDATA_DIR}/validation_set.hg003.tfrecord@${N_SHARDS}.gz" \
      --truth_variants "${TRUTH_VCF_003}" \
      --confident_regions "${TRUTH_BED_003}" \
      --task {} \
      --regions ' "chr20" ' \
	  --sort_by_haplotypes \
	  --parse_sam_aux_fields \
	  --add_hp_channel \
	  --channels ' "read_mapping_percent,avg_base_quality,identity,gap_compressed_identity,gc_content,is_homopolymer,homopolymer_weighted,blank,insert_size" ' \
) 2>&1 | tee "${LOG_DIR}/validation_set.with_label.make_examples.log"

get ”example_channels = [1, 2, 3, 4, 5, 6, 7, 11, 12, 13, 14, 15, 16, 17, 18, 19]“

I'm curious how do I get channels 9 and 10？Thanks！

**Comment by kishwarshafin** [comment]
@guoquankisscall , please see the channel enums defined here: https://github.com/google/deepvariant/blob/r1.4/deepvariant/protos/deepvariant.proto#L1048

Channel 9, 10 refers to diff_channels setup, please set the`--alt_aligned_pileup="diff_channels"` to populate those channels.

**Comment by guoquankisscall** [comment]
@kishwarshafin , i get it, thank you!

**Comment by kishwarshafin** [comment]
@guoquankisscall , welcome, closing this issue. Please reopen if you have further questions.
