### ISSUE TITLE
Is ubuntu20.04 a must to build DV-1.4?

### ISSUE THREAD

**Issue by leedchou** [google/deepvariant#591]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**: **YES**

**Describe the issue:**

_Building release binaries of DV-1.4 on ubuntu16.04 failed.
I modified scripts to install packages that is need to build DV-1.4, which didn't work for me.
Updating operating system is not allowed for me, so I am eager to know whether there is any chance that I build DV-1.4 on ubuntu16.04 technically?_

**Setup**
  - Operating system: **Ubuntu16.04**
  - DeepVariant version: **1.4**
  - Installation method (Docker, built from source, etc.): **built from source**

**Comment by danielecook** [comment]
@leedchou is it possible for you to install Docker and/or singularity and run DeepVariant using that? 

This may be an easier route than enabling builds on Ubuntu16.04. Currently we only build/test on Ubuntu 20.04.

**Comment by leedchou** [comment]
> @leedchou is it possible for you to install Docker and/or singularity and run DeepVariant using that?
> 
> This may be an easier route than enabling builds on Ubuntu16.04. Currently we only build/test on Ubuntu 20.04.

thanks@danielecook. Yes, I am able to run DV using Docker, which did work.
I need to debug some parts of this project to better understand it, so I have to build it from source.
Do you mean there is a route to build DV using Docker or Singularity?

**Comment by leedchou** [comment]
> @leedchou is it possible for you to install Docker and/or singularity and run DeepVariant using that?
> 
> This may be an easier route than enabling builds on Ubuntu16.04. Currently we only build/test on Ubuntu 20.04.

Sorry, I am a beginner of Docker. I've learned something about docker technology  in the past two days, figuring out what you mean. Now I can build an iamge that does not depend on operating system of my device.

Thank you.
