### ISSUE TITLE
Ran into a compilation issue when running DeepVariant model on MacOS

### ISSUE THREAD

**Issue by sivianil** [google/deepvariant#596]
After creating the directories and downloading the required files in their respective folders, I used the single command run_deeppvariant script. But it not's working. I'm attaching the screenshot. 

  - Operating system: MacOS
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: Illumina seq, short reads

<img width="1510" alt="Screenshot 2022-12-05 at 12 09 45" src="https://user-images.githubusercontent.com/75676816/205648651-e8ad6b73-7139-4fa6-9b5d-b496cdcf7bc2.png">

**Comment by akolesnikov** [comment]
nproc command is not available on your machine. You may replace $(nproc) with the number of cores on your computer.
