### ISSUE TITLE
optimize_for_inference_lib' is not defined error

### ISSUE THREAD

**Issue by serverchief** [google/deepvariant#597]
Hello, I'm getting error below - please let me know if I can fix it in anyway.. 

[root@localhost processed]# docker run -v /home/imusayev/Documents/RNAseq:/input -v /home/imusayev/Documents/RNAseq:/output google/deepvariant:1.4.0 /opt/deepvariant/bin/run_deepvariant --model_type=WES --regions=chr16:56191390-56357444 --ref=/input/hg38/hg38.fa --reads=/input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam --output_vcf=/output/MUT60d.sorted.bam.vcf --output_gvcf=/output/MUT60d.sorted.bam.gvcf --call_variants_extra_args=use_openvino=true --num_shards=2 --logging_dir=/output/logs
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.

I1214 05:45:20.217978 140442762327872 run_deepvariant.py:342] Re-using the directory for intermediate results in /tmp/tmpiy9bfzyx

***** Intermediate results will be written to /tmp/tmpiy9bfzyx in docker. ****

***** Running the command:*****
time seq 0 1 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/input/hg38/hg38.fa" --reads "/input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam" --examples "/tmp/tmpiy9bfzyx/make_examples.tfrecord@2.gz" --channels "insert_size" --gvcf "/tmp/tmpiy9bfzyx/gvcf.tfrecord@2.gz" --regions "chr16:56191390-56357444" --task {}

I1214 05:45:33.914664 140555214505792 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:33.947415 140555214505792 make_examples_core.py:243] Task 1/2: Preparing inputs
I1214 05:45:34.038768 140555214505792 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:34.078675 140555214505792 make_examples_core.py:243] Task 1/2: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I1214 05:45:34.198254 140555214505792 make_examples_core.py:243] Task 1/2: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-12-14 05:45:34.198784: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1214 05:45:33.916420 140052653934400 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:33.947322 140052653934400 make_examples_core.py:243] Task 0/2: Preparing inputs
I1214 05:45:34.025260 140052653934400 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:34.073680 140052653934400 make_examples_core.py:243] Task 0/2: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM']
I1214 05:45:34.124348 140052653934400 make_examples_core.py:243] Task 0/2: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
2022-12-14 05:45:34.124915: I third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
I1214 05:45:40.845054 140555214505792 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:40.834452 140052653934400 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:43.058780 140555214505792 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:43.070213 140555214505792 make_examples_core.py:243] Task 1/2: Writing gvcf records to /tmp/tmpiy9bfzyx/gvcf.tfrecord-00001-of-00002.gz
I1214 05:45:43.072572 140555214505792 make_examples_core.py:243] Task 1/2: Writing examples to /tmp/tmpiy9bfzyx/make_examples.tfrecord-00001-of-00002.gz
I1214 05:45:43.072886 140555214505792 make_examples_core.py:243] Task 1/2: Overhead for preparing inputs: 9 seconds
I1214 05:45:43.768549 140555214505792 make_examples_core.py:243] Task 1/2: 2 candidates (2 examples) [0.70s elapsed]
I1214 05:45:43.182209 140052653934400 genomics_reader.py:222] Reading /input/60d/processed/work/89/e7822adaaaf824f73f3d6acd1334bb/MUT60d.sorted.bam with NativeSamReader
I1214 05:45:43.196409 140052653934400 make_examples_core.py:243] Task 0/2: Writing gvcf records to /tmp/tmpiy9bfzyx/gvcf.tfrecord-00000-of-00002.gz
I1214 05:45:43.198944 140052653934400 make_examples_core.py:243] Task 0/2: Writing examples to /tmp/tmpiy9bfzyx/make_examples.tfrecord-00000-of-00002.gz
I1214 05:45:43.199340 140052653934400 make_examples_core.py:243] Task 0/2: Overhead for preparing inputs: 9 seconds
I1214 05:45:45.989331 140052653934400 make_examples_core.py:243] Task 0/2: 7 candidates (12 examples) [2.79s elapsed]

I1214 06:02:02.274300 140052653934400 make_examples_core.py:243] Task 0/2: Writing example info to /tmp/tmpiy9bfzyx/make_examples.tfrecord-00000-of-00002.gz.example_info.json
I1214 06:02:02.278903 140052653934400 make_examples_core.py:1883] example_shape = [100, 221, 7]
I1214 06:02:02.279304 140052653934400 make_examples_core.py:1884] example_channels = [1, 2, 3, 4, 5, 6, 19]
I1214 06:02:02.320155 140052653934400 make_examples_core.py:243] Task 0/2: Found 77 candidate variants
I1214 06:02:02.320545 140052653934400 make_examples_core.py:243] Task 0/2: Created 89 examples
I1214 06:10:23.735674 140555214505792 make_examples_core.py:243] Task 1/2: Writing example info to /tmp/tmpiy9bfzyx/make_examples.tfrecord-00001-of-00002.gz.example_info.json
I1214 06:10:23.736027 140555214505792 make_examples_core.py:1883] example_shape = [100, 221, 7]
I1214 06:10:23.736302 140555214505792 make_examples_core.py:1884] example_channels = [1, 2, 3, 4, 5, 6, 19]
I1214 06:10:23.748708 140555214505792 make_examples_core.py:243] Task 1/2: Found 77 candidate variants
I1214 06:10:23.748840 140555214505792 make_examples_core.py:243] Task 1/2: Created 84 examples

real	25m4.324s
user	39m40.647s
sys	0m24.239s

***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "/tmp/tmpiy9bfzyx/call_variants_output.tfrecord.gz" --examples "/tmp/tmpiy9bfzyx/make_examples.tfrecord@2.gz" --checkpoint "/opt/models/wes/model.ckpt" --openvino_model_dir "/tmp/tmpiy9bfzyx" --use_openvino
I1214 06:10:30.972710 140363019278144 call_variants.py:317] From /tmp/tmpiy9bfzyx/make_examples.tfrecord-00000-of-00002.gz.example_info.json: Shape of input examples: [100, 221, 7], Channels of input examples: [1, 2, 3, 4, 5, 6, 19].
I1214 06:10:30.995939 140363019278144 call_variants.py:317] From /opt/models/wes/model.ckpt.example_info.json: Shape of input examples: [100, 221, 7], Channels of input examples: [1, 2, 3, 4, 5, 6, 19].
2022-12-14 06:10:31.060396: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-14 06:10:31.101084: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
I1214 06:10:31.288279 140363019278144 openvino_estimator.py:55] Processing ckpt=/opt/models/wes/model.ckpt, tensor_shape=[100, 221, 7]
/usr/local/lib/python3.8/dist-packages/tf_slim/layers/layers.py:1083: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs)
/usr/local/lib/python3.8/dist-packages/tf_slim/layers/layers.py:678: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
/usr/local/lib/python3.8/dist-packages/tf_slim/layers/layers.py:2441: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs)
/usr/local/lib/python3.8/dist-packages/tf_slim/layers/layers.py:118: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs)
/usr/local/lib/python3.8/dist-packages/tf_slim/layers/layers.py:1638: UserWarning: `layer.apply` is deprecated and will be removed in a future version. Please use `layer.__call__` method instead.
  outputs = layer.apply(inputs, training=is_training)
INFO:tensorflow:Restoring parameters from /opt/models/wes/model.ckpt
I1214 06:10:37.470187 140363019278144 saver.py:1399] Restoring parameters from /opt/models/wes/model.ckpt
WARNING:tensorflow:From /tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py:75: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
W1214 06:10:41.056998 140363019278144 deprecation.py:341] From /tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py:75: convert_variables_to_constants (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.convert_variables_to_constants`
WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:929: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
W1214 06:10:41.057430 140363019278144 deprecation.py:341] From /usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/convert_to_constants.py:929: extract_sub_graph (from tensorflow.python.framework.graph_util_impl) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
    tf.compat.v1.app.run()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/absl_py/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/absl_py/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
    call_variants(
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 416, in call_variants
    ie_estimator = OpenVINOEstimator(
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 90, in __init__
    freeze_graph(model, checkpoint_path, tensor_shape, openvino_model_pb)
  File "/tmp/Bazel.runfiles_oh47rpgj/runfiles/com_google_deepvariant/deepvariant/openvino_estimator.py", line 77, in freeze_graph
    graph_def = optimize_for_inference_lib.optimize_for_inference(
NameError: name 'optimize_for_inference_lib' is not defined

**Comment by serverchief** [comment]
Thanks for the feedback, I’m using a published docker image 1.4.0 which also latest at the time of this posting.How do I disable openvino?On Dec 13, 2022, at 11:51 PM, Pi-Chuan Chang ***@***.***> wrote:﻿
Hi, it seems like you're using the openvino flag. Please remove that flag and try again.
For context - in recent versions, we haven't been building in openvino because we haven't been able to see extra speedup.
In the next version, I'll try to make this more clear and show the proper message a bit earlier (or, just remove the flag)
Please let me know if it works after you remove the openvino flag.

**Comment by pichuan** [comment]
Can you share the command you run?
OpenVINO is off by default in v1.4. So you likely are adding a flag for it.

**Comment by pichuan** [comment]
Sorry, you did share the command in the first post.
It's this one - please just remove it `--call_variants_extra_args=use_openvino=true`

**Comment by pichuan** [comment]
I'll close this one for now. Please feel free to update and let me know if it worked or not.

**Comment by pichuan** [comment]
Hi @serverchief , 
a quick update for you:
In the next release, we'll make sure that if you accidentally run with `--call_variants_extra_args=use_openvino=true`, the program will exit earlier (before it starts make_examples) and warn you that openvino is no longer built in.
