### ISSUE TITLE
DeepVariant does not complete postprocess_variants

### ISSUE THREAD

**Issue by robertzeibich** [google/deepvariant#599]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:

**Describe the issue:** DeepVariant does not complete postprocess_variants (feels like stuck; already waiting for completion for two days; other SAMPLES have already finished runninig)

**Setup**
  - Operating system: HPC
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): Docker --> Singularity
  - Type of data: WGS data

**Steps to reproduce:**
  - Command: `run_deepvariant --model_type=WGS --ref=${FASTA} --reads=${BAMFILE} --output_vcf=${OUT_SAMPLE}.vcf.gz --output_gvcf=${OUT_SAMPLE}.g.vcf.gz`
  - Error trace: (if applicable) 

No error, but DeepVariant does not seem to continue processing:
```
***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/home/rzei0002/xm41_scratch/hg38_resources/resources_broad_hg38_v0_Homo_sapiens_assembly38.fasta" --infile "/tmp/tmp8vfbqj_y/call_variants_output.tfrecord.gz" --outfile "/scratch/xm41
/ct/bamsDown/30x/DEEPV/GRALF001.vcf.gz" --nonvariant_site_tfrecord_path "/tmp/tmp8vfbqj_y/gvcf.tfrecord@1.gz" --gvcf_outfile "/scratch/xm41/ct/bamsDown/30x/DEEPV/GRALF001.g.vcf.gz"
```

![image](https://user-images.githubusercontent.com/73748542/208531940-a0cbd86a-acb7-4ff4-9168-57c3b865625c.png)

Based on other processes, the final process should not take that long:

![image](https://user-images.githubusercontent.com/73748542/208532607-d0ae4fd2-38ac-48f9-889d-2d4343e60fe5.png)

Is there a way to only re-initiate the postprocess_variants process?

**Comment by kishwarshafin** [comment]
@robertzeibich ,

Yes, please run your previous command with `--dry_run` and you will see all the commands that are run. Then copy the the `post_process` command and run it like this:
```
time docker run -it -u `id -u`:`id -g` -v /data:/data \
google/deepvariant:1.4.0 \
**YOUR_COMMAND**
```

**Comment by robertzeibich** [comment]
Thanks. I just tried to execute the command, but I get the following error message `ValueError: Cannot find matching files with the pattern "/tmp/tmphskm66vr/call_variants_output.tfrecord.gz"`. The files in the tmp directory also seem to be gone.

**Comment by kishwarshafin** [comment]
@robertzeibich ,

Yes, unfortunately, you need to have the intermediate directory saved to have this working. The intermediate directory can be saved outside temp by setting `--intermediate_results_dir` parameter.

**Comment by pichuan** [comment]
Hi @robertzeibich ,
Hopefully our answer is helpful . In the future if you want to capture and keep the intermediate results, please add that flag. Thank you!
