### ISSUE TITLE
RNA seq file take too much time !

### ISSUE THREAD

**Issue by Rofidagamal** [google/deepvariant#600]
Until now it takes 60 hours !! 
That is the output on terminal, until now it runs , why it is like that?

  
* Running the command:* 
time seq 0 7 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "Homo_sapiens_assembly38.fasta" --reads "SRR10720227.RGG.marked.sorted.bam" --examples "/tmp/tmpe2z79_52/make_examples.tfrecord@8.gz" --split_skip_reads --task {} 
 
I1219 19:34:53.123960 140628390905664 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.243814 140628390905664 make_examples_core.py:236] Task 7/8: Preparing inputs 
I1219 19:34:53.094258 139794990966592 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.115872 139794990966592 make_examples_core.py:236] Task 1/8: Preparing inputs 
I1219 19:34:53.235279 139794990966592 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.134214 140309844559680 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.192481 140309844559680 make_examples_core.py:236] Task 6/8: Preparing inputs 
I1219 19:34:53.107017 140536106870592 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.122070 140536106870592 make_examples_core.py:236] Task 4/8: Preparing inputs 
I1219 19:34:53.226204 140536106870592 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.129359 140434427647808 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.162234 140434427647808 make_examples_core.py:236] Task 5/8: Preparing inputs 
I1219 19:34:53.209864 140434427647808 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.105211 139854300972864 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.131687 139854300972864 make_examples_core.py:236] Task 3/8: Preparing inputs 
I1219 19:34:53.201329 139691329734464 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.210919 139691329734464 make_examples_core.py:236] Task 2/8: Preparing inputs 
I1219 19:34:53.269506 139691329734464 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.152369 140549443307328 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.174761 140549443307328 make_examples_core.py:236] Task 0/8: Preparing inputs 
I1219 19:34:53.282668 140549443307328 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.454261 140628390905664 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.366882 140309844559680 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:53.342017 139854300972864 genomics_reader.py:222] Reading SRR10720227.RGG.marked.sorted.bam with NativeSamReader 
I1219 19:34:54.719705 140628390905664 make_examples_core.py:236] Task 7/8: Common contigs are ['chr1', 'chr2', 'chr3', 'chr4', 'chr5', 'chr6', 'chr7', 'chr8', 'chr9', 'chr10', 'chr11', 'chr12', 'chr13', 'chr14', 'chr15', 'chr16', 'chr17', 'chr18', 'chr19', 'chr20', 'chr21', 'chr22', 'chrX', 'chrY', 'chrM'] 
I1222 17:05:35.016938 140674909861696 make_examples_core.py:236] 115600 candidates (123081 examples) [152.69s elapsed] 
I1222 17:08:13.613651 140674909861696 make_examples_core.py:236] 115700 candidates (123187 examples) [158.60s elapsed] 
I1222 17:11:17.636787 140674909861696 make_examples_core.py:236] 115800 candidates (123291 examples) [184.02s elapsed] 
I1222 17:14:36.123843 140674909861696 make_examples_core.py:236] 115900 candidates (123396 examples) [198.49s elapsed]

I1222 17:24:15.065273 140674909861696 make_examples_core.py:236] 116402 candidates (123922 examples) [14.41s elapsed] 
I1222 17:28:23.640279 140674909861696 make_examples_core.py:236] 116501 candidates (124033 examples) [248.57s elapsed] 
I1222 17:36:04.357874 140674909861696 make_examples_core.py:236] 116602 candidates (124146 examples) [460.72s elapsed] 
I1222 18:10:43.444469 140674909861696 make_examples_core.py:236] 116700 candidates (124254 examples) [2079.09s elapsed] 
I1222 18:12:31.832537 140674909861696 make_examples_core.py:236] 116802 candidates (124369 examples) [108.39s elapsed] 
I1222 18:12:55.837079 140674909861696 make_examples_core.py:236] 116901 candidates (124474 examples) [24.00s elapsed] 
I1222 18:15:57.499845 140674909861696 make_examples_core.py:236] 117000 candidates (124581 examples) [181.66s elapsed] 
I1222 18:18:32.688332 140674909861696 make_examples_core.py:236] 117100 candidates (124699 examples) [155.19s elapsed] 
I1222 18:20:58.813500 140674909861696 make_examples_core.py:236] 117204 candidates (124809 examples) [146.12s elapsed] 
I1222 18:21:35.041635 140674909861696 make_examples_core.py:236] 117300 candidates (124905 examples) [36.23s elapsed] 
I1222 18:24:55.941922 140674909861696 make_examples_core.py:236] 117418 candidates (125041 examples) [200.90s elapsed] 
I1222 18:25:28.467675 140674909861696 make_examples_core.py:236] 117504 candidates (125129 examples) [32.53s elapsed] 
I1222 18:25:42.422913 140674909861696 make_examples_core.py:236] 117601 candidates (125232 examples) [13.96s elapsed] 
I1222 18:26:08.412047 140674909861696 ]

**Comment by danielecook** [comment]
It looks to me like a large number of candidate variants are being generated. This could be for a few reasons:

1. You are not restricting calling to a set of regions (e.g. exons)
2. Is this an FFPE sample? That could increase the number of candidates considerably. 

I recommend using a bed file to restrict calling to regions of interest. If that does not work we might increase thresholds for considering candidates, but it would be worth looking in IGV to see what the sequence data looks like and where candidates are being called.
