### ISSUE TITLE
AttributeError: deleter

### ISSUE THREAD

**Issue by kmarianski** [google/deepvariant#602]
Hi DeepVariant team,

I'm running DeepVariant via Singularity via Snakemake on a HPC cluster and overall, if I create an interactive session, my entire WES pipeline runs fine until an odd DeepVariant job fails (by that I mean that let's say 30 deepvariant jobs finish ok and the 31st fails). I can then restart the Snakemake run and the same job will run fine, followed by more jobs that will also run fine until another odd jobs fails. This is also particularly true when I use the --cluster command in Snakemake (i.e., send it to a SLURM job scheduler from the master node) - in this event every single job fails.

I could of course run all my samples on a single interactive session, keep checking the log file and restart the run every time it fails but I guess that's less than optimal plus this way I can really only run one sample at the time.

For the interactive sessions I request 180G and 64cpus (in my case it's: ```srsh --mem=180G --cpus-per-task=64 --partition=long```). 

I would request same parameters when using --cluster so:
```snakemake --cluster "sbatch --mem=180G cpus-per-task=64" --jobs 64 --profie profile/ ```(where profile holds singularity args etc.)

Singularity image is deepvariant_1.4.0.sif

my Snakemake rule:

```
rule deepvariant:
    input:
        bam=rules.apply_bqsr.output.bam,
        ref='/mnt/shared/scratch/kmarians/private/dyslexia_gatk/workflow/resources/genome.fasta'
    output:
        vcf="results/deepvariant/{sample}.vcf.gz"
    params:
        model="WES"
    threads: 
        64
    resources:
        mem_mb=163840
    log:
        "logs/deepvariant/{sample}/stdout.log"
    singularity:
        "singularity/deepvariant_1.4.0.sif"
        # "singularity/deepvariant_1.4.0-gpu.sif" # for GPU
    shell:
        """
        /opt/deepvariant/bin/run_deepvariant --model_type {params.model} --ref {input.ref} --reads {input.bam} --output_vcf {output.vcf} --num_shards {threads} --make_examples_extra_args='vsc_min_count_snps=3,vsc_min_fraction_snps=0.2,vsc_min_count_indels=3,vsc_min_fraction_indels=0.10'
        """
```

Below is the begening and end of the log file. I am happy to include the entire log file but there is nothing out of the ordinary between those lines below (same output as for jobs that finished successfully). Could you please advise on what parameters to change to successfully run DeepVariant by submitting it to the SLURM scheduler? 
I0104 18:49:24.340415 140179943589696 make_examples_core.py:243] Task 13/64: Found 2793 candidate variants
I0104 18:49:24.340478 140179943589696 make_examples_core.py:243] Task 13/64: Created 2879 examples

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 64
Rules claiming more threads will be scaled down.
Select jobs to execute...

> [Wed Jan  4 18:30:51 2023]
> rule deepvariant:
>     input: results/recal/s534_EKDN210017195-1A_HTTJ3DSX2_L2.bam, /mnt/shared/scratch/kmarians/private/dyslexia_gatk/workflow/resources/genome.fasta
>     output: results/deepvariant/s534_EKDN210017195-1A_HTTJ3DSX2_L2.vcf.gz
>     log: logs/deepvariant/s534_EKDN210017195-1A_HTTJ3DSX2_L2/stdout.log
>     jobid: 0
>     wildcards: sample=s534_EKDN210017195-1A_HTTJ3DSX2_L2
>     threads: 64
>     resources: mem_mb=163840, disk_mb=16401, tmpdir=/tmp/kmarians_4189323
> 
> Activating singularity image singularity/deepvariant_1.4.0.sif
> INFO:    Convert SIF file to sandbox...
> I0104 18:31:03.183642 139718628308800 run_deepvariant.py:342] Re-using the directory for intermediate results in /tmp/kmarians_4189323/tmpxrz5rqbp
> 
> ***** Intermediate results will be written to /tmp/kmarians_4189323/tmpxrz5rqbp in docker. ****
> 
> 
> ***** Running the command:*****
> time seq 0 63 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/make_examples --mode calling --ref "/mnt/shared/scratch/kmarians/private/dyslexia_gatk/workflow/resources/genome.fasta" --reads "results/recal/s534_EKDN210017195-1A_HTTJ3DSX2_L2.bam" --examples "/tmp/kmarians_4189323/tmpxrz5rqbp/make_examples.tfrecord@64.gz" --channels "insert_size" --vsc_min_count_indels "3" --vsc_min_count_snps "3" --vsc_min_fraction_indels "0.10" --vsc_min_fraction_snps "0.2" --task {}

> *
> *
> *
> I0104 18:49:24.340415 140179943589696 make_examples_core.py:243] Task 13/64: Found 2793 candidate variants
> I0104 18:49:24.340478 140179943589696 make_examples_core.py:243] Task 13/64: Created 2879 examples
> real	18m21.465s
> user	893m16.250s
> sys	15m57.561s
> 
> ***** Running the command:*****
> time /opt/deepvariant/bin/call_variants --outfile "/tmp/kmarians_4189323/tmpxrz5rqbp/call_variants_output.tfrecord.gz" --examples "/tmp/kmarians_4189323/tmpxrz5rqbp/make_examples.tfrecord@64.gz" --checkpoint "/opt/models/wes/model.ckpt" --openvino_model_dir "/tmp/kmarians_4189323/tmpxrz5rqbp"
> 
> I0104 18:49:26.695084 139646404110144 call_variants.py:317] From /tmp/kmarians_4189323/tmpxrz5rqbp/make_examples.tfrecord-00000-of-00064.gz.example_info.json: Shape of input examples: [100, 221, 7], Channels of input examples: [1, 2, 3, 4, 5, 6, 19].
> I0104 18:49:26.697470 139646404110144 call_variants.py:317] From /opt/models/wes/model.ckpt.example_info.json: Shape of input examples: [100, 221, 7], Channels of input examples: [1, 2, 3, 4, 5, 6, 19].
> Traceback (most recent call last):
>   File "/tmp/kmarians_4189323/Bazel.runfiles_zims94rl/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 513, in <module>
>     tf.compat.v1.app.run()
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/tmp/kmarians_4189323/Bazel.runfiles_zims94rl/runfiles/absl_py/absl/app.py", line 300, in run
>     _run_main(main, args)
>   File "/tmp/kmarians_4189323/Bazel.runfiles_zims94rl/runfiles/absl_py/absl/app.py", line 251, in _run_main
>     sys.exit(main(argv))
>   File "/tmp/kmarians_4189323/Bazel.runfiles_zims94rl/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 494, in main
>     call_variants(
>   File "/tmp/kmarians_4189323/Bazel.runfiles_zims94rl/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 389, in call_variants
>     init_op = tf.group(tf.compat.v1.global_variables_initializer(),
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 3319, in global_variables_initializer
>     return variables_initializer(global_variables())
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/ops/variables.py", line 3139, in global_variables
>     return ops.get_collection(ops.GraphKeys.GLOBAL_VARIABLES, scope)
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6605, in get_collection
>     return get_default_graph().get_collection(key, scope)
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 6231, in get_default_graph
>     return _default_graph_stack.get_default()
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 5742, in get_default
>     self._global_default_graph = Graph()
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/ops.py", line 3113, in __init__
>     self._scoped_c_graph = c_api_util.ScopedTFGraph()
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/c_api_util.py", line 50, in __init__
>     self.graph = c_api.TF_NewGraph()
> RuntimeError: random_device::random_device(const std::string&): device not available
> Exception ignored in: <function ScopedTFGraph.__del__ at 0x7f01d64378b0>
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/framework/c_api_util.py", line 58, in __del__
> AttributeError: deleter

**Comment by akolesnikov** [comment]
Hi kmarianski,

This line is suspicious. 
```
Re-using the directory for intermediate results in /tmp/kmarians_4189323/tmpxrz5rqbp
```

Each DeepVariant job needs a separate `intermediate_directory`. Could you verify that each job uses different temp directory?

The error in the log comes from TensorFlow library. Unfortunately, we are unable to help with TensorFlow (which is a third party tool).

**Comment by kmarianski** [comment]
Hi @akolesnikov,

Thanks! Indeed all jobs were pointing to the same `tmpdir`. Fixed now 👍
