### ISSUE TITLE
Availability of DeepVariant RNA-seq GTEx model

### ISSUE THREAD

**Issue by Argonvi** [google/deepvariant#605]
Hello DeepVariant team,

I am currently interested in using your software for variant calling from RNA-sequencing data. After reading the [preprint](https://doi.org/10.1101/2022.10.16.512451) I understand that there are two available models for such purpose: "DV RNA-seq [GTEx]" and "DV RNA-seq [GIAB]". I see that "DV RNA-seq [GIAB]" is used in the [RNA-seq case study](https://github.com/google/deepvariant/blob/r1.4/docs/deepvariant-rnaseq-case-study.md) and downloadable through the urls provided there, but I have not been able to find urls for the GTEx model. Is it yet to be made available?

**Comment by danielecook** [comment]
Actually, we only published the GTEx-based model given that it outperformed the GIAB trained model. The GTEx model is the only model we published and is what is used in the case study.

Let me know if you have any further questions. Thanks.

**Comment by Argonvi** [comment]
I was a misunderstanding on my part then. Thank you for you answer!
