### ISSUE TITLE
DeepVariant build fails with Tensorflow 2.11

### ISSUE THREAD

**Issue by SaurabhKalikar** [google/deepvariant#607]
Hello,

I am trying to build DeepVaraint with Tensorflow 2.11.0. I modified "settings.h" and "build-prereq.sh" to initialize the respective version of bazel and other dependencies. However, I am not able to build successfully. 
Could you please guide me towards upgrading Tensorflow to 2.11.0 and any required modifications to the source code?  

Thanks,
Saurabh

**Comment by akolesnikov** [comment]
Hello Saurabh,
What errors do you get? Could you paste the output?

**Comment by akolesnikov** [comment]
Updating TF version might not be straightforward. We're planning to update to TF 2.11 in the next release, which should be out in the next few months.

**Comment by SaurabhKalikar** [comment]
Thanks @akolesnikov and @pichuan 

Please find the details and the error-log below.

Please note that I have upgraded the following dependencies according to Tensorflow - 2.11. 

DV_BAZEL_VERSION="5.3.0"
DV_GCP_OPTIMIZED_TF_WHL_VERSION="2.11.0"
ABSL_VERSION=20210324.2
PROTOBUF_VERSION=3.19.6


**Error log:** 
(03:11:57) ERROR: /opt/deepvariant/third_party/nucleus/io/BUILD:1051:11: Compiling third_party/nucleus/io/gfile.cc failed: (Exit 1): gcc failed: error executing command
  (cd /root/.cache/bazel/_bazel_root/617054f44dc1f1e9b3fe3174f8eb2580/execroot/com_google_deepvariant && \
  exec env - \
    PATH=/root/bin:/root/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/local/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.8/dist-packages \
    TF2_BEHAVIOR=1 \
  /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-

Also, at an earlier point in the build, there is one more issue - 

Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned **404 Not Found**

**Comment by pichuan** [comment]
Hi @SaurabhKalikar ,
The latest release (v1.5.0) is now using TensorFlow 2.11. We'll also update Nucleus in a few weeks.
