### ISSUE TITLE
Can't copy the quickstart data

### ISSUE THREAD

**Issue by aderzelle** [google/deepvariant#61]
Hello, 
a rather simple issue, I am following this tutorial 
https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-docker.md

and at this step 
`gsutil -m cp gs://deepvariant/quickstart-testdata/* input/
`
I get
`zsh: no matches found: gs://deepvariant/quickstart-testdata/*`

Thanks a lot

**Comment by pgrosu** [comment]
Hi @aderzelle ,

Since you're using `zsh` as a shell just include single-quotes like this when you use wildcards:

`gsutil -m cp 'gs://deepvariant/quickstart-testdata/*' input/`

Paul

**Comment by aderzelle** [comment]
Indeed, solved my problem!

Thanks a lot
