### ISSUE TITLE
Missing a 1-bp deletion comparing to GATK (potential denovo variant)

### ISSUE THREAD

**Issue by yangyxt** [google/deepvariant#612]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md**:
Yes
**Describe the issue:**
A potential denovo variant is filtered out due to mendelian violation. While found the deletion in the same sample via GATK and IGV (both raw BAM file and realigned BAM file from GATK HaplotypeCaller). Wonder how to loosen the criteria to increase the recall of denovo variants.
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system: CentOS7
  - DeepVariant version: 1.4
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  - 150bp paired-end Illumina data

**Steps to reproduce:**
  - Command: 
  `/opt/deepvariant/bin/run_deepvariant \
    --model_type=${model_type} \
    --ref="${ref_genome}" \
    --reads="${bam_file}" \
    --make_examples_extra_args="normalize_reads=true" \
    ${region_arg} \
    --output_vcf="${output_vcf}" \
    --output_gvcf="${output_gvcf}" \
    --intermediate_results_dir "/paedyl01/disk1/yangyxt/test_tmp/${singularity_inter}" \
    --num_shards=${threads}`
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**
Here is the IGV screenshot of the position where DeepVariant failed to identify one bp deletion (Upper panel illustrates the alignment from raw BAM file, lower panel illustrates the alignment from the realigned BAM file from GATK HaplotypeCaller):
![image](https://user-images.githubusercontent.com/40780228/218404096-273ed999-6443-43c2-83b9-108661d738d4.png)

P.S. Please consider granting a parameter of DeepVariant to let users generate the realigned BAM file from DeepVariant. Thanks!

**Comment by kishwarshafin** [comment]
@yangyxt ,

Thank you for opening this issue. It'd be helpful if we could get a little more information about this variant. There could be a lot of reasons for a variant to be excluded. To start, can you please look at the VCF near this region to see if the candidate was generated and it is a RefCall or the candidate was not being picked at all?

Thanks.

**Comment by kishwarshafin** [comment]
@yangyxt ,

As for the request to emit realigned BAM. Please see the details how the realigner works: https://github.com/google/deepvariant/blob/r1.4/docs/FAQ.md#what-is-the-realigner-and-how-does-it-work 

Specifically this details maybe helpful for you:

There is also the option to output the realigned reads, e.g. to inspect the new alignments in IGV. This can be done by passing the following parameters: `--make_examples_extra_args="emit_realigned_reads=true,realigner_diagnostics=/output/realigned_reads"`

**Comment by pichuan** [comment]
Hi @yangyxt , I'll close this issue now. Feel free to open new issues if you have more questions for us.
