### ISSUE TITLE
Genotype of 1/2 and 0/2

### ISSUE THREAD

**Issue by amy-houseman** [google/deepvariant#615]
Hello,

I was wondering if you could provide anymore information on what it means when passed variants are called as 1/2 and 0/2?

Thanks!
Amy

**Comment by MariaNattestad** [comment]
I covered this in a video on my YouTube channel actually :)
It's right around this time point: https://youtu.be/MrVpn0vpIYU?t=885

You can also consult the VCF format specification for more details: https://samtools.github.io/hts-specs/VCFv4.2.pdf

**Comment by amy-houseman** [comment]
Amazing, thank you Maria! I had watched the webinar about how deepvariant classifies but hadn't seen your video yet, thank you lots! Amy
