### ISSUE TITLE
ONT Duplex Data

### ISSUE THREAD

**Issue by WenyuLiang** [google/deepvariant#617]
Thanks for the wonderful tool! It's exciting to know that DeepVariant supports ONT Duplex Data.
I wonder what tools you use to generate bam files for testing. Assuming you use minimap2, what parameters did you use to generate optimal input for DeepVariant? Given the high accuracy of Duplex data, the default setting should not work well anymore because that's for old ONT data.
Thanks!

**Comment by kishwarshafin** [comment]
Hi @WenyuLiang ,

We have used the standard ONT mapping command to map Duplex reads to fastq:
```
minimap2 -k 17 -ax map-ont -t <CPUS> <REF> <FASTQ>
```
We have not tested other mapping modes for R10.4  to see if it improves overall mapping.

If that is something you explore on your end and find improvements, please let us know by opening a github issue or reaching out over an email as we have not explored this extensively.

**Comment by WenyuLiang** [comment]
Sure! I will post it here if there are better parameters to use. Thanks

**Comment by pichuan** [comment]
Hi @WenyuLiang ,
I'll close this issue now. Feel free to give us update here if you have found anything that might be useful to share with other users too. Thank you!
