### ISSUE TITLE
Whether the WES model without the addition of region(bed) parameter is equal to the effect of WGS model?

### ISSUE THREAD

**Issue by zxy1555847** [google/deepvariant#622]
Hello
I wonder know something  about Deepvariant's **--model_type**  parameter
Whether the WES model without the addition of region(bed) parameter is equal to the effect of WGS model?
Thank you very much.

**Comment by kishwarshafin** [comment]
If you question is if WGS and WES are the exactly the same models then the answer is no, they are  not the same model, we train WGS model and WES models separately specific for each task.

**Comment by danielecook** [comment]
Closing this issue. Please reopen if there are any new questions.

Thank you.
