### ISSUE TITLE
Has DeepVariant been used on Element AVITI™ System sequencing dataset？

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#623]
hello，
I wonder if I can use deepvariant on FASTQ sequencing datasets from the Element AVITI™ System.

Looking forward to your reply.
Thanks!

**Comment by AndrewCarroll** [comment]
Hi @crazysummerW 

Thank you for your question. The most recent release of DeepVariant (v1.5) has been trained with both Illumina and Element data for the WGS model, and we found a single model performs well for both data.

Even in earlier releases before training with Element data, we observe that the DeepVariant Illumina model doesn't have issues operating on Element data.

**Comment by crazysummerW** [comment]
Hi @crazysummerW 
Thank you for your reply.
I have downloaded public WGS data from elementbiosciences website yesterday，and tested with google/deepvariant:1.4.0，it worked successfully.Then,I used jmcdani20/hap.py:v0.3.12 for analysis, but I got nothing. 
My code:
  /opt/deepvariant/bin/run_deepvariant \
  --model_type WGS \
  --ref hs37d5_m.fasta \
  --reads HG002.sorted.dedup.bqsr.bam \
  --output_vcf HG002.depv.wgs.vcf.gz \
  --output_gvcf HG002.depv.wgs.g.vcf.gz \
  --num_shards 64 \
  --intermediate_results_dir intermediate_results_dir_low

  /opt/hap.py/bin/hap.py \
  HG002_GRCh37_1_22_v4.2.1_benchmark.vcf.gz \
  HG002.depv.wgs.vcf.gz \
  -f HG002_GRCh37_1_22_v4.2.1_benchmark_noinconsistent.bed \
  -r hs37d5_m.fasta \
  -o happy.output \
  --engine=vcfeval \
  --pass-only

The result :
![1679626896057](https://user-images.githubusercontent.com/70870741/227413442-d4607611-d845-4954-abe3-10c068ea75db.jpg)
Result from file happy.output.summary.csv

I don't know what is wrong with my code. Could you help me?

Thanks!

**Comment by kishwarshafin** [comment]
@crazysummerW ,

Your truth file looks empty, see the TRUTH.TOTAL is 0. Can you please make sure that you have downloaded the right file and it contains records in the VCF?

**Comment by crazysummerW** [comment]
Thank you so much! I have got the correct output.
