### ISSUE TITLE
RNA-seq model availability for v1.5.0

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#624]
Hi,

The RNA-seq model in the case-study is available for version 1.4.0, but trying the download by simply replacing with 1.5.0 raises a file not found error. 

Is or will there be an RNA-seq model for v1.5.0, or was this only be available for v1.4.0?  

```
# works 
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-rnaseq_standard/model.ckpt.data-00000-of-00001 > model/model.ckpt.data-00000-of-00001
# fails
curl https://storage.googleapis.com/deepvariant/models/DeepVariant/1.5.0/DeepVariant-inception_v3-1.5.0+data-rnaseq_standard/model.ckpt.data-00000-of-00001 > model/model.ckpt.data-00000-of-00001
```

**Comment by danielecook** [comment]
For the v1.5.0 release we did not train a new RNA-seq model and therefore did not release a new model. You can stick with v1.4.0 model+codebase to run the RNA-seq model or you can use this v1.4.0 model with the v1.5.0 codebase (we have not tested directly, but it should work). Please let me know if you run into any issues.

**Comment by ASLeonard** [comment]
Great thanks. v1.5.0 codebase does run with the v1.4.0 model, so will compare the results soon. Hopefully no major differences

**Comment by danielecook** [comment]
Excellent! Please let us know if you have any other feedback. I will close this issue now.

**Comment by ASLeonard** [comment]
There is a slight change in performance, but since v1.5.0 already has slightly different output/performance to v1.4.0, I don't think there is any negative consequence to using RNA model v1.4.0 on DV v1.5.0.

**Comment by danielecook** [comment]
Thanks for the update.The differences could be related to a change in the Tensorflow version. We welcome any additional feedback you have.
