### ISSUE TITLE
dv_* file syntax error from bioconda installed 1.4.0 version DeepVariant

### ISSUE THREAD

**Issue by richard-nm** [google/deepvariant#627]
Upon running dv_make_examples.py -h , dv_call_variants.py -h , or dv_postprocess_variants.py -h , python told me there is a syntax error around a f-string.

**Setup**
  - Operating system: Centos
  - DeepVariant version: 1.4.0
  - Installation method (Docker, built from source, etc.): bioconda

**Steps to reproduce:**
  - Command: dv_make_examples.py -h

**Comment by akolesnikov** [comment]
Hi @richard-nm ,
Could you please paste the entire output?

**Comment by richard-nm** [comment]
Hi, here is the output:
`
dv_call_variants.py -h
Baseline DeepVariant arguments
  File "/tmp/Bazel.runfiles_dwq0j2la/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 356
    f'The file {input_shape_file} should contain 3 integers')
                                                           ^
SyntaxError: invalid syntax
`
If you check dv_make_examples.py and dv_postprocess_variants.py, you can find similar output.
I also tried to solve this syntax by replace f-strings to .format, and get another syntax error:
`Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_gxfcz7rb/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_gxfcz7rb/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 645
    options: deepvariant_pb2.SampleOptions
           ^
SyntaxError: invalid syntax
`

**Comment by pichuan** [comment]
@richard-nm Can you paste your command too?

I wonder if you're using older code with newer models.

In 1.3.0, we used to have this file that specifies the shape in 3 integers:

```
$ gsutil cat gs://deepvariant/models/DeepVariant/1.3.0/DeepVariant-inception_v3-1.3.0+data-wgs_standard/model.ckpt.input_shape
100 221 6
```

In the later moment, we changed the format. For example, 1.4.0:

```
$ gsutil cat gs://deepvariant/models/DeepVariant/1.4.0/DeepVariant-inception_v3-1.4.0+data-wgs_standard/model.ckpt.example_info.json
{"version": "1.5.0", "shape": [100, 221, 7], "channels": [1, 2, 3, 4, 5, 6, 19]}
```
(We also added one more channel, which is why the shape is now 100 221 7.)

From the error messages you're getting, it seems like you're using code version older than 1.4.0.

**Comment by richard-nm** [comment]
Sorry for my wrong posting of error messages.
I have tried different versions of deepvariant in conda, and messed up the conda environment.  
Actually I posted the deepvarint (1.3.0) error messages. : <(

Here is my attempts on the deepvariant 1.4.0: 
`
$ conda create -n deepvar python=3.7.5
$ conda install -c bioconda deepvariant=1.4.0
$ conda activate deepvar
$ dv_call_variants.py -h 

`
And I got the similar error messages:

Baseline DeepVariant arguments
  File "/tmp/Bazel.runfiles_j_t9fnwc/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 374
    raise ValueError(f'Shape mismatch in {example_info_json} and '
                                                                 ^
SyntaxError: invalid syntax


Wrapper arguments
usage: dv_call_variants.py [--cores CORES] --outfile OUTFILE --examples
                           EXAMPLES --sample SAMPLE
                           [--model {hybrid,pacbio,wes,wgs}] [-h]

DeepVariant call_variants wrapper

optional arguments:
  --cores CORES
  --outfile OUTFILE
  --examples EXAMPLES   Example directory from make_examples
  --sample SAMPLE       Sample name
  --model {hybrid,pacbio,wes,wgs}
                        DeepVariant trained model to use, defaults to wgs
  -h, --help
usage: dv_call_variants.py [--cores CORES] --outfile OUTFILE --examples
                           EXAMPLES --sample SAMPLE
                           [--model {hybrid,pacbio,wes,wgs}] [-h]
dv_call_variants.py: error: the following arguments are required: --outfile, --examples, --sample

**Comment by pichuan** [comment]
Hi @richard-nm , thanks for the update. Given that our team didn't build or maintain the bioconda version, I'm not familiar with many things here.

One question and one comment for you:
1. Question: Where can I find documentation of this tool? For example, "dv_call_variants.py" isn't part of our GitHub repo, so I'm not familiar with that at all.
2. Comment: Purely based on the error message you posted:
```
Baseline DeepVariant arguments
File "/tmp/Bazel.runfiles_j_t9fnwc/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 374
raise ValueError(f'Shape mismatch in {example_info_json} and '
^
SyntaxError: invalid syntax
```
The corresponding line would be this one:
https://github.com/google/deepvariant/blob/r1.4/deepvariant/call_variants.py#L374
I'm not exactly why that would cause a SyntaxError though. It's a bit hard for me to figure out given that it's wrapped in something that I'm not familiar with.

I did try to follow your steps above, but didn't succeed in installing:
```
$ conda create -n deepvar python=3.7.5
$ conda install -c bioconda deepvariant=1.4.0
```
gave me:
```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - deepvariant=1.4.0 -> python[version='>=3.6,<3.7.0a0']

Your python: python=3.7.5
```

@richard-nm One more question for you -- is it possible to use Docker or Singularity? Which our team can support more easily as well. Thank you!

**Comment by pichuan** [comment]
Hi @richard-nm , it seems like this thread has been inactive for a while.
I'll close it now, but feel free to reopen to follow up if you like.
