### ISSUE TITLE
How to work with it on Local system

### ISSUE THREAD

**Issue by vinaysb** [google/deepvariant#63]
Hello, I have installed all the binaries and ran all the shell scripts to install tensorflow and bazel, but after that I could not follow how to actually train the model or how to identify the snps for my files. I am sorry I am very new to deep learning.

Any help would be greatly appreciate

**Comment by pichuan** [comment]
Hi,
[Quick Start](https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-quick-start.md) provides a quick example of how you identify SNPs and Indels in a small region. [Case Study](https://github.com/google/deepvariant/blob/r0.5/docs/deepvariant-case-study.md) gives you a full example of how to identify SNPs and Indels in a whole genome on a single machine.

We don't currently have detailed documentation on how to train your own model. I recommend you start with running DeepVariant using the models we released.
