### ISSUE TITLE
Strands support for each allele

### ISSUE THREAD

**Issue by Wenfei-Xian** [google/deepvariant#630]
Hi, 

Is it possible to provide the number of forward-strand and reverse-strand reads supporting the reference allele and the alternate allele for each variant locus?

In short, if I want to keep the variant loci supported by both forward and reverse strands, what should I do? Because DeepVariant performs realignment, there may be differences between the alignment of the original BAM file and the after realigned.

Best,
Wenfei

**Comment by AndrewCarroll** [comment]
Hi @Wenfei-Xian 

DeepVariant already sees the strand of the input reads as one of the input. For more information on the inputs to DeepVariant, see: [our blog looking through DeepVariant's eyes](https://google.github.io/deepvariant/posts/2020-02-20-looking-through-deepvariants-eyes/)

DeepVariant will incorporate the strand information as a part of its estimation for the confidence in the variant call (e.g. in the QUAL field and the GQ value). The GQ value is the best-calibrated value to use for filtering or evaluation.

DeepVariant doesn't annotate the supporting information in the VCF, so if you want to directly access the support for strand, you will need to run some other program to annotate the VCF with the BAM information. For strand, realignment is unlikely to have a noticeable effect, as it will change the coordinates of read positions (and when doing so may alter which reads overlap a variant position), but it will not alter the forward or reverse orientation of a read.

Thank you,
Andrew

**Comment by Wenfei-Xian** [comment]
Many thanks !!!
