### ISSUE TITLE
Some questions about RNAseq data analysis

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#635]
hello,
I am testing RNA-seq data with deepvarian1.4. 
I have some questions about：
1. Is GATK SplitNCigarReads necessary for input bam?
2. Could you explain in detail what the parameter "--make_examples_extra_args="split_skip_reads=true, channels=''" dose?
3. Does the RNAseq model only apply to the CDS region?
Looking forward to your reply.

Thanks.

**Comment by danielecook** [comment]
1. No - this should not be necessary. This operation is handled by DeepVariant.
2. There are two arguments being passed here: `--make_examples_extra_args="split_skip_reads=true, channels=''`
  - `--make_examples_extra_args="split_skip_reads=true` - Turns on operation that splits reads. This is the equivalent of GATK SplitNCigarReads.
  - `channels=''` - Disables additional channels from being added. Currently we add an insert_size channel by default, but the RNA-seq model does not currently use this channel.
3. The RNAseq model can be applied in any region. However, if you look at our [preprint](https://www.biorxiv.org/content/10.1101/2022.10.16.512451v1.full), you will see that we restrict much of our analysis to CDS regions. The reason for this is that variant calling in CDS regions is a desirable use case where we can maintain relatively high accuracy in RNA-seq data. However, you can use a larger set of regions depending on what the goals of your analysis are. You can also apply filtering to increase precision in these regions (at a cost of reduced sensitivity). See the section `Selecting a cut-off for practical implementation` in our preprint for details on this idea.

<img width="633" alt="image" src="https://user-images.githubusercontent.com/1536935/234003967-3aa5abd4-f8f3-494d-8ada-79eef723548b.png">

I recommend following along with our [case study](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-rnaseq-case-study.md) to get started.

**Comment by crazysummerW** [comment]
hello,
I tested a sample with deepvariant1.4.
My code : 
step1.
STAR --twopassMode Basic --runThreadN $nt --genomeDir $star_fasta --outSAMtype BAM SortedByCoordinate $aln_para --readFilesIn $fastq_folder/$fastq_1 $fastq_folder/$fastq_2 --readFilesCommand zcat --outSAMattrRGline ID:$group SM:$sample PL:$platform
step2.
/opt/deepvariant/bin/run_deepvariant \
    --model_type WES \
    --customized_model model/model.ckpt \
    --ref hg19.fasta \
    --reads sorted.bam \ #from STAR result
    --output_vcf sorted.output.vcf.gz \
    --num_shards 64 \
    --regions allbed \ #CDS regions were not extracted
    --make_examples_extra_args="split_skip_reads=true,channels=''" \
    --intermediate_results_dir intermediate_results_dir
Then, I failed.
The log:
![1682412849532](https://user-images.githubusercontent.com/70870741/234226220-8d03e201-26d0-4b7f-a8ca-2802685d5efb.png)
I have confirmed that the parameter $star_fasta is from hg19. What is the problem with my data processing? Should I add the steps of “Remove Duplicate Reads” and “Base Quality Score Recalibration (BQSR)”? 

Looking forward to your reply.
Thanks.

**Comment by danielecook** [comment]
@crazysummerW the error seems to suggest that the contigs in your bam file do not match the contigs in the reference you provided. Can you double check that `$star_fasta` is pointing to the same file as `hg19.fasta`, and that the contigs present in both are the same?

One possibility here could be that the `$star_fasta` provided here removed the `chr` prefix from the chromosomes.

**Comment by crazysummerW** [comment]
Thanks a lot. It worked.
