### ISSUE TITLE
Facing issues while using "run_deepvariant_keras.py" 

### ISSUE THREAD

**Issue by SaurabhKalikar** [google/deepvariant#636]
Hello,

I tried running "_run_deepvariant_keras.py_" script from the latest release of deepvaraint and faced some issues while running the keras-based call variant module. 

I used the following command to run:

`
python bazel-out/k8-opt/bin/deepvariant/run_deepvariant_keras.py --model_type=WGS --ref=ref.fa --reads=reads.bam --regions "chr19" --output_vcf=${OUTPUT_DIR}/output.vcf.gz --output_gvcf=${OUTPUT_DIR}/output.g.vcf.gz --intermediate_results_dir ${OUTPUT_DIR}/intermediate_results_dir --num_shards=10
`

The above command successfully ran for _make_example_ module and failed at _call_varaint_keras.py_ with the following error message..

-------------

_Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_004ga1wn/runfiles/com_google_deepvariant/deepvariant/call_variants_keras.py", line 399, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles_004ga1wn/runfiles/absl_py/absl/app.py", line 312, in run_
    _run_main(main, args)
  File "/tmp/Bazel.runfiles_004ga1wn/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles_004ga1wn/runfiles/com_google_deepvariant/deepvariant/call_variants_keras.py", line 387, in main
    call_variants(
  File "/tmp/Bazel.runfiles_004ga1wn/runfiles/com_google_deepvariant/deepvariant/call_variants_keras.py", line 344, in call_variants
    model.load_weights(checkpoint_path).expect_partial()
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py", line 1047, in assert_consumed
    raise AssertionError(
AssertionError: Some objects had attributes which were not restored:
    <tf.Variable 'classification/kernel:0' shape=(2048, 3) dtype=float32, numpy=_

------------
Please note that I used the same checkpoint path as I was using while running _run_deepvariant.py_.
Could you please help me to resolve the issue and suggest if I am missing anything while using _call_varaint_keras.py_?

Thanks,
Saurabh

**Comment by kishwarshafin** [comment]
Hi Saurabh,

Currently the `run_deepvariant_keras` is experimental as we plan to develop this further in the future. The model for `run_deepvariant` is for tf-slim and would not simply extend to keras. For now, you should use `run_deepvariant` as that's the one we officially support.

**Comment by SaurabhKalikar** [comment]
Thanks for the clarification, Kishwar. Could you please let us know when we can expect the new keras-based model to be officially supported? 

Thanks
Saurabh

**Comment by pichuan** [comment]
@SaurabhKalikar We're aiming for this year.
