### ISSUE TITLE
I have bam files of tumor sample and paried normal sample. How can I combine the two bam files using DeepVariant?

### ISSUE THREAD

**Issue by Famingzhao** [google/deepvariant#637]
Hi,
I have WES bam files of tumor sample and paried normal sample. So, how can I combine the two bam files using DeepVariant like Varscan2 or MuTect2 do? 
Did DeepVariant only supprot calling variation for each sample,  respectively? Then I can use VCF files of tumor sample and paried normal sample for further analysis?

**Comment by kishwarshafin** [comment]
Hi @Famingzhao ,

DeepVariant is trained for germline variant calling and somatic variant calling is not officially supported. For your use case, you have to run DeepVariant on tumor and normal independently. However, as stated before, somatic calling is not officially supported.
