### ISSUE TITLE
Questions about WES or WGS data analysis

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#638]
hello,
I would like to know if BQSR data preprocessing is necessary when analyzing WES or WGS on deepvariant? Will it affect the result?

Looking forward to your reply.

Thanks.

**Comment by kishwarshafin** [comment]
Hi @crazysummerW ,

Please see this bug: https://github.com/google/deepvariant/issues/569, as stated, this is our recommendation:


> We have a strong recommendation NOT to run Variant Score Quality Recalibration (VQSR). We observe large reductions in accuracy, particularly in recall of rare variants.

**Comment by crazysummerW** [comment]
hi，
Thanks for your reply. I mean BQSR. I tested on WES data. The result : 
1. deal with deduplication and BQSR：
![1682582003166](https://user-images.githubusercontent.com/70870741/234796615-a5ce10c7-da7b-4542-8717-b2cde03fc478.jpg)
2. only deal with deduplication:
![1682582061403](https://user-images.githubusercontent.com/70870741/234796818-f7bb9a58-dc50-4a96-8848-6bd785b0b136.jpg)

Can I think BQSR processed results are better?

**Comment by kishwarshafin** [comment]
Hi @crazysummerW ,

Sorry it was my mistake. I misread BQSR as VQSR. Previously our experiments showed a slight decrease in accuracy with BQSR, but, we haven't done that for the latest models. Your numbers do look slightly improved. Are you using the latest version of DeepVariant?

**Comment by crazysummerW** [comment]
hi，
I used DeepVariant1.4 and GATK.4.2.0.0. I want to reduce the running time of the process overall. So I want to confirm Is there no problem with data preprocessing without deduplication and BQSR on DeepVariant?

**Comment by AndrewCarroll** [comment]
Hi @crazysummerW 

There is no problem with not using deduplication and BQSR. When we ourselves run DeepVariant, that is how we run it.

**Comment by crazysummerW** [comment]
@AndrewCarroll 
Thank you for your reply.
