### ISSUE TITLE
Training mode error: 'truth_variant needs genotypes to be used for labeling'

### ISSUE THREAD

**Issue by ksw9** [google/deepvariant#64]
Dear all,
Thanks for a fantastic tool! I'm trying to further train the deepvariant models on a truth VCF for a non-human genome. When I run the make_examples script in training mode with my truth vcf and confident regions BED, I get the following error:
```
 ValueError: ('truth_variant needs genotypes to be used for labeling', reference_bases: "A"
alternate_bases: "G"
end: 1977
reference_name: "NC_000962.3"
start: 1976
)
```
I'm wondering if the truth VCF needs to be in a particular format? Or is the problem because I am working with a haploid genome and thus my truth VCF is haploid?

Thank you in advance!

**Comment by depristo** [comment]
Yes, the truth_variants have to have genotypes, as these are used to compute the labels that DeepVariant trains to predict. It's not sufficient to just have sites. 

As a general comment, we are aware of the need for more information about how to train DeepVariant, which we hope to produce in a reasonable timeframe.

**Comment by ksw9** [comment]
Thank you! Yes - the newest release 0.6.0 has fixed this issue and my truth VCF now works.
