### ISSUE TITLE
Benchmark with low precision and recall on indels with HG002 PacBio Revio data

### ISSUE THREAD

**Issue by lijingjing1** [google/deepvariant#641]
I used DeepVariant to call SNPs and Indels with the HG002 Pacbio Revio benchmark data download from https://human-pangenomics.s3.amazonaws.com/submissions/80d00e88-7a92-46d8-88c7-48f1486e11ed--HG002_PACBIO_REVIO/, while the hap.py result showed Indels have very low precision (0.653927) and recall (0.884985) and SNPs seemed to be normal having 0.998 precision and recall.

Type	Filter	TRUTH.TOTAL	TRUTH.TP	TRUTH.FN	QUERY.TOTAL	QUERY.FP	QUERY.UNK	FP.gtMETRIC.Recall	METRIC.Precision	METRIC.Frac_NA	METRIC.F1_Score
INDEL	ALL	523034	462877	60157	1215487	252834	484908	16813	0.884985	0.653927	0.398941	0.75211
INDEL	PASS	523034	462877	60157	1215487	252834	484908	16813	0.884985	0.653927	0.398941	0.75211
SNP	ALL	3352818	3349190	3628	3960152	8899	597545	864	0.998918	0.997354	0.150889	0.998135
SNP	PASS	3352818	3349190	3628	3960152	8899	597545	864	0.998918	0.997354	0.150889	0.998135

I running the pipeline with aligner minimap2  v2.24 with parameters "-L --MD -Y -a -x map-hifi --secondary=no" and calling SNVs with deepVariant v1.3.0 with --model_type=PACBIO.

**Comment by MariaNattestad** [comment]
Thanks for the question!
We recommend you use DeepVariant v1.5.0 to get a model trained with Revio data.
See https://github.com/google/deepvariant/releases/tag/v1.5.0 
"Incorporated PacBio Revio training data in DeepVariant PacBio model. In our evaluations this single model performs well on both Sequel II and Revio datatypes. Please use DeepVariant v1.5 and later for Revio data."

**Comment by lijingjing1** [comment]
Thanks for your reply and i will try DeepVariant v1.5.0 to benchmark the HG002 Revio data.
