### ISSUE TITLE
How to filter a merged gvcf  file 

### ISSUE THREAD

**Issue by wangsb111** [google/deepvariant#642]
Hello:
     I have a population  with 35 indivuals , and called gvcf for each individual by the DeepVariant ,and then, combined all individual gvcfs file using the GLnexus. Although there are some basic filtering parameters when combining by the GLnexus, but they can't meet my subsequent analysis. so if there some ways or tools to further filter the combined gvcf (which are equivalent to filtering parameters with " --filter "QUAL <50.0" --filter-name LowQ --filter "DP <200  " --filter-name LowD --filter "DP> 10000 " --filter-name HigD --filter " MQ<40.0 " --filter-name SedT --filter "SOR > 50.0 " --filter-name LowSOR    --filter "AN <150 " --filter-name LowMiss"  by GATK software)

**Comment by AndrewCarroll** [comment]
Hi @wangsb111 

For filtering, it remains the case that filtering on the sample GQ field is the best way to increase specificity while losing the smallest number of true variants. 

Are you able to run the same postprocess tool you are using on the GLnexus calls? If so, here are some thoughts on your parameters:

**-filter "QUAL <50.0" --filter-name LowQ** The QUAL field can be used. DeepVariant is much more conservative and realistic about the QUAL values. Filtering at 50 will filter too many real calls. Figure 1 in our [DeepVariant-GLnexus paper](https://academic.oup.com/bioinformatics/article/36/24/5582/6064144) has a chart of the Predicted and Real qualities for GATK and DeepVariant. Matching the predicted-real accuracy by quality between the two would put the comparable QUAL threshold at 12-17. Note that DeepVariant's GQ values are well-calibrated over the range of 0-60, so you can map them directly onto your desired specificity (e.g. Q10 is 90% confidence in call, Q20 is 99% confidence, Q30 99.9% confidence, and so on).

**--filter-name LowQ --filter "DP <200 " --filter-name LowD** This field implies to me you are doing panel sequencing or deep exome sequencing, as this is a high value. The sample info should have DP present and it will not differ between GATK and DeepVariant output. You can use the same filter. 

** --filter "DP> 10000 " --filter-name HigD** This is again the DP field, which is present in the call file and can also be used.

** MQ<40.0 " --filter-name SedT** This filters low mappability regions. This is actually a fairly high value, which means this will aggressively filter low mappability regions. MQ is seen by DeepVariant and used in calling to determine the variant call and confidence, so it will be reflected in the GQ value. However, MQ is not reported into the VCF, so this filter cannot be used for filtering without additional annotation of the VCF. If you want to filter out low mappability regions, I would recommend intersecting with the high mappability BED file from genome in a bottle.

**--filter "SOR > 50.0 " --filter-name LowSOR** This filter relates to the strand of reads over a variant. Strand bias is something which DeepVariant can see in its inputs and will use this information to determine variant calls and assign confidence to those calls. However, strand bias is not reported a a separate value in the VCF, so this filter cannot be used for filtering without additional annotation of the VCF. I would say that use of this additional filter isn't needed.

**--filter "AN <150 " --filter-name LowMiss"** As I understand this filter, it quantifies the number of different alleles identified at a position. I suppose this is some measure of the error rate around a position. If I understand the annotation correctly, DeepVariant should never produce value which come remotely close to this value in the cohort. You can exclude this filter as I don't think it would ever trigger.
