### ISSUE TITLE
The question about the analysis of WES data

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#647]
hello,
When analyzing WES data, I want to force the output of some sites to ensure that they appear in the vcf file. Does deepvariant1.4 have a function similar to the sentieon --given parameter?
![1683857742780](https://github.com/google/deepvariant/assets/70870741/b8abded4-4325-4f07-9c72-8b2f40bae666)

Look forward to your reply.

Thanks.

**Comment by danielecook** [comment]
@crazysummerW you can try to use `--variant_caller=vcf_candidate_importer` with `--proposed_variants=<VCF>`

Here is a tutorial detailing how to run these two flags: https://gist.github.com/pichuan/baba6ee9bd9890be2a45076a4934dd38

**Comment by pichuan** [comment]
Hi @crazysummerW , feel free to reopen if you have any questions.
