### ISSUE TITLE
can DeepVariant be run on a merged bam file? or must each Bam have a seperate run and then the vcfs can be merged?

### ISSUE THREAD

**Issue by ChristinaMulch** [google/deepvariant#651]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md**:

**Describe the issue:**
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system:
  - DeepVariant version:
  - Installation method (Docker, built from source, etc.):
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by akolesnikov** [comment]
Hi @ChristinaMulch,

Could you please provide more details on what you are trying to achieve? 
Are you trying to analyze trios? Are these bam files generated by the same sequencers?

**Comment by AndrewCarroll** [comment]
@ChristinaMulch 

With respect to the mechanics of DeepVariant - You can merge a BAM file with multiple read groups or from several files with the same read group. When you do so, if there is only one Sample among these files (specifically, all read groups have the same SM: value), DeepVariant will call all of them together, and will use that sample name for the VCF header field.

If the read groups have more than one Sample, DeepVariant will give an error. If you really need to run on that file even so, there is a flag you can provide to apply a sample name to the BAM.

Does this answer your question?

**Comment by pichuan** [comment]
Hi @ChristinaMulch , if the answer above didn't answer your question, please feel free to reopen.

**Comment by tinyfallen** [comment]
> Hi @ChristinaMulch , if the answer above didn't answer your question, please feel free to reopen.

Hi @pichuan 

Thanks for the great tools. I have a set of pupolation resequencing data including 151 individuals for SNP calling. The reads were mapped to the genome by bowtie2 and marked duplications by GATK. I have used GATK HaplotypeCaller to call SNPs with 151 samples together. I would like to compare the results with deepvariant. However, deepvariant seemed to accept only one bam file as input. Will it work when I merge the 151 bams as input?

best ~

**Comment by pgrosu** [comment]
Probably the quickest way would be to process each sample individually and then combine them together, by first creating [gVCF outputs](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-gvcf-support.md) and then merging them using [GLnexus](https://github.com/dnanexus-rnd/GLnexus).  A nice tutorial on how to do this is available at the following link:

https://github.com/google/deepvariant/blob/r1.5/docs/trio-merge-case-study.md

**Comment by tinyfallen** [comment]
已收到您发送的邮件！

**Comment by tinyfallen** [comment]
> Probably the quickest way would be to process each sample individually and then combine them together, by first creating [gVCF outputs](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-gvcf-support.md) and then merging them using [GLnexus](https://github.com/dnanexus-rnd/GLnexus). A nice tutorial on how to do this is available at the following link:
> 
> https://github.com/google/deepvariant/blob/r1.5/docs/trio-merge-case-study.md

Thanks for your reply! It seems too time and resource consuming to separately run for each sample. If I got the resource, I would have a try.

Best ~

**Comment by pgrosu** [comment]
Google Cloud might be an option for additional resources: https://cloud.google.com/life-sciences/docs/tutorials/deepvariant

**Comment by AndrewCarroll** [comment]
Hi @tinyfallen 

@pgrosu is correct, the most efficient way is to run DeepVariant individually and then merge with GLnexus. One point to make, GLnexus runs quite quickly relative to the variant calling step. The joint calling operation won't add much cost relative to DeepVariant (scaling benchmarks for GLnexus can be found in Figure 7C of [the DeepVariant-GLnexus paper](https://academic.oup.com/bioinformatics/article/36/24/5582/6064144).

So the main resource use can be estimated from the single sample runtime multiplied by sample number.

If you are curious for a comparison, it might make sense to run a single sample and compare the calls for that sample with the extracted set of calls from the GATK joint calls.

**Comment by tinyfallen** [comment]
> Hi @tinyfallen
> 
> @pgrosu is correct, the most efficient way is to run DeepVariant individually and then merge with GLnexus. One point to make, GLnexus runs quite quickly relative to the variant calling step. The joint calling operation won't add much cost relative to DeepVariant (scaling benchmarks for GLnexus can be found in Figure 7C of [the DeepVariant-GLnexus paper](https://academic.oup.com/bioinformatics/article/36/24/5582/6064144).
> 
> So the main resource use can be estimated from the single sample runtime multiplied by sample number.
> 
> If you are curious for a comparison, it might make sense to run a single sample and compare the calls for that sample with the extracted set of calls from the GATK joint calls.

Many thanks for your reply! I would have a try

best ~
