### ISSUE TITLE
question about RNA-seq

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#652]
hello,
I would like to know if deduplication of BAM files is necessary when analyzing RNA-seq data on DeepVariant. Will it affect the results?

Looking forward to your reply.

Thanks.

**Comment by danielecook** [comment]
@crazysummerW my intuition is that it would not make a big difference, but we have not empirically tested this.

My guess is that It could make a difference in variants observed in regions with lower coverage.

Here is a similar issue (although, in the context of DNA-seq): https://github.com/google/deepvariant/issues/384

**Comment by pichuan** [comment]
Hi @crazysummerW , hopefully we've answered your question. I'll close this issue.
