### ISSUE TITLE
Genotype error in VCF result

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#655]
hello,
I tested a NGS sample on DV1.4. An error occurred in calling a variant at a specific locus.The VCF results show that the genotype at this locus is 1/1, but the first-generation sequencing results did not reveal a homozygous mutation. I checked the BAM file, and I couldn't draw a conclusion about the homozygous mutation either. How was the 1/1 result determined? Can you explain the reasons and methods to avoid the error from happening?
![image](https://github.com/google/deepvariant/assets/70870741/1c0710d4-f9a4-40ef-a2d7-c982e42eac1b)
![image](https://github.com/google/deepvariant/assets/70870741/4665a415-6236-46a2-ad0a-958ddf4ca2bf)
![image](https://github.com/google/deepvariant/assets/70870741/5433bce6-1b83-4d8a-88d3-8173708ac8ed)
Looking forward to your reply.

Thanks.

**Comment by AndrewCarroll** [comment]
Hi @crazysummerW 

Thank you for the pileup and for the trace. The trace makes it clear there isn't a variant here. 

With respect to this variant call, there are a few things that I see: 

First, DeepVariant has a very low confidence in this call. The GQ of 4 corresponds to a 40% chance of being incorrect. Interestingly, the second most likely call at this position according to DeepVariant is 0/0 (HomRef). This is in spite of a 0.27 variant allele frequency (something that most callers would probably consider as either 0/0 HomRef or 0/1 HET). 

This is an indication that DeepVariant may think that one of the haplotypes (either the Ref one or the Alt one) are unreliable (e.g. that they are reads which map from a different part of the genome), but doesn't know which to consider. Some other lines of evidence DeepVariant might use for that is the higher coverage (1200 is a coverage that would often be seen in duplicated parts of the genome) and the unusual allele frequency ratio (70% Ref, 30% Alt). Another piece of evidence we can't see but DeepVariant may use is the Insert Size channel if this is Illumina data. 

A few questions -

1) What is the sequencing technology used here, and which type of instrument. Is this PacBio or Illumina here? 
2) Is this some form of panel sequencing targeting the region? 

One suggestion to try (especially if this is panel short read sequencing) - downsample the region to ~80-100 coverage and see if the call changes. Especially look for the GQ confidence to go up as 4 is very low. If you want to avoid such situations more, you might want to put a higher GQ threshold for downstream filtering, and for a specific case like this look for cases where the PL values show higher probability for HOMREF and ALT than HET. A GQ threshold of 10 would be a 90% probability the call is correct, a GQ threshold of 20 would be a 99% threshold. 

Just from the evidence presented here, this site is going to be difficult to call, as  just on the VAF this look more like a HET (though the other factors mentioned here about copy number variants could be the factor in allowing a REF call.

**Comment by crazysummerW** [comment]
hi，@AndrewCarroll 
Thank you for your suggestion. This is a new platform panel data, we will consider filtering GQ to avoid this problem.
