### ISSUE TITLE
The coordinates for "--regions" in run_deepvariant

### ISSUE THREAD

**Issue by xunzhizhang** [google/deepvariant#656]
Hello,
The flag "--regions" of run_deepvariant sets the regions to be processed. When region literals (like chr20:10-20) are provided, are the coordinates 1-based or 0-based? Is this region an open or closed interval?

Thank you very much!

**Comment by pgrosu** [comment]
https://github.com/google/nucleus/blob/v0.6.0/nucleus/protos/range.proto#L18

```
// A 0-based half-open genomic coordinate range for search requests.
message Range {
```

**Comment by kishwarshafin** [comment]
Thank you @pgrosu. Yes, it's 0-based coordinate.
