### ISSUE TITLE
E: Unable to locate package python-wheel

### ISSUE THREAD

**Issue by msnoon** [google/deepvariant#66]
I am trying to install deepvariant within a singularity container using recipe build. I have successfully complied google-sdk within the container, when it comes to the point where its runs "./build-prereq.sh" script, it terminates with this error: 

**Setting up unzip (6.0-9ubuntu1) ...
Setting up zip (3.0-8) ...
Setting up zlib1g-dev:amd64 (1:1.2.8.dfsg-1ubuntu1) ...
Processing triggers for libc-bin (2.19-0ubuntu6) ...
Processing triggers for sgml-base (1.26+nmu4ubuntu1) ...
========== [Tue Apr 17 00:09:23 UTC 2018] Stage 'Install python packaging infrastructure' starting
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-wheel
ABORT: Aborting with RETVAL=255
Cleaning up...**

I am using singularity within in vagrant on my mac and here is my recipe file:

**Bootstrap: shub
From: singularityhub/ubuntu

%runscript
    exec echo "The runscript is the containers default runtime command!"

%files
#   /home/vanessa/Desktop/hello-kitty.txt        # copied to root of container
#   /home/vanessa/Desktop/party_dinosaur.gif     /opt/the-party-dino.gif #

%environment

    export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"

%labels
    AUTHOR mnoon@email.arizona.edu

%post
    apt-get update && apt-get -y install python2.7 git wget curl 
    mkdir /data
    echo "The post section is where you can install, and configure your container."

    echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" > /etc/apt/sources.list.d/google-cloud-sdk.list
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg |  apt-key add -

    apt-get update && apt-get install -y google-cloud-sdk
##download deepVariant scripts and run them
    git clone https://github.com/google/deepvariant.git
    cd deepvariant
 
    ./build-prereq.sh

    ./build_and_test.sh

    ./run-prereq.sh**

I have no idea whats causing this error. any help will be appreciated.

-M

**Comment by pichuan** [comment]
I'm not completely sure about your setting. Our installation guide currently is done on Ubuntu 16. 
In your case, it seems like you're unable to install python-wheel? I think that's outside the scope of DeepVariant support. A few possible ways to get unstuck : maybe you can see whether you can skip installing python-wheel, and see what you actually need to install to proceed to the next step.

I don't think we can be of more help on this issue. I'm closing this issue for now.
