### ISSUE TITLE
Do I need to do MarkDuplicates and BaseRecalibbrator on bam files with Gatk?

### ISSUE THREAD

**Issue by geng-lee** [google/deepvariant#665]
Hi Developer,

Do I need to do MarkDuplicates and BaseRecalibbrator on bam files with Gatk?

Best,
Jamie

**Comment by pgrosu** [comment]
Hi @geng-lee,

It is not necessary, and in fact BAM files with original quality scores is recommended.

~p

**Comment by geng-lee** [comment]
Ok, I get it now. Thanks！
 
 
Best,  
Jamie

**Comment by danielecook** [comment]
Thank you @pgrosu!
