### ISSUE TITLE
Can the pan-genome alignment bam file be used to call variation information by DeepVariant

### ISSUE THREAD

**Issue by wlhCNU** [google/deepvariant#667]
Hi deepvariant developer,
Is DeepVariant suitable for performing variation detection analysis, particularly **calling SNP and indel information**, using **bam formate** alignment results obtained from **vg software pan-genome analysis** and NGS resequencing data as input files?

Thanks

**Comment by pichuan** [comment]
@wlhCNU Can you see if this is helpful for you?
https://gist.github.com/pichuan/eedab4cf2e06fa7ceb2fad0f9b3f8066

**Comment by akolesnikov** [comment]
Closing the issue. Please feel free to reopen if needed.
