### ISSUE TITLE
Running dv_make_examples.py from conda

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#669]
Hi,
I installed deepvariant from conda. However, when I run dv_make_examples.py all jobs fail, and in their log is reported as:

```
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_v62e2j9f/runfiles/com_google_deepvariant/deepvariant/make_examples.py", line 38, in <module>
    from deepvariant import make_examples_core
  File "/tmp/Bazel.runfiles_v62e2j9f/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 41, in <module>
    from etils import epath
ModuleNotFoundError: No module named 'etils' 

```
Do you have any suggestions?

**Comment by AndrewCarroll** [comment]
Hi @gambalab 

We'll discuss this in the team today. We don't make or directly control the conda install for DeepVariant, that is done by external people. We'll try to assess our ability to debug or offer suggestions for conda issues like this today, but it might be a bit before we have a suggestion.

**Comment by gambalab** [comment]
There is a dependency conflict with etils package. Indeed if you try to install deepvariant with the following command:

`conda create -n deepV -c bioconda deepvariant etils -y`

It fails because it is not able to solve all the dependencies. Although I am not an expert of Phyton, It seems to me a problem related to the different phyton versions to use.

**Comment by pgrosu** [comment]
@gambalab You're most likely running Python 3.6 and DeepVariant needs Python 3.8.  What operating system and version of the OS are you running?  Do you have Docker or Singularity access?

**Comment by gambalab** [comment]
I am on cluster, I will ask the admin to install docker engine. Anyway, regarding the OS version below you can find it.

> cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by pgrosu** [comment]
Hi @gambalab,

Thank you for the information.  I tried using a Debian 11 docker image, and installed conda with python 3.8 but there seems to be other library conflicts.

In the meantime if you want to have fun while your sysadmin performs a proper Docker install, you can run Docker in user-space using `udocker` in the following way:

https://indigo-dc.github.io/udocker/installation_manual.html

You don't need to install it as it say in the instructions.  You can just do the following:

```
wget https://github.com/indigo-dc/udocker/releases/download/1.3.9/udocker-1.3.9.tar.gz
tar xzvf udocker-1.3.9.tar.gz
cd udocker-1.3.9/udocker/
./udocker pull google/deepvariant:1.5.0
./udocker run google/deepvariant:1.5.0
```

All the downloaded information is saved under the ` $HOME/.udocker` folder.

Hope it helps,
~p

**Comment by gambalab** [comment]
> Hi @gambalab,
> 
> Thank you for the information. I tried using a Debian 11 docker image, and installed conda with python 3.8 but there seems to be other library conflicts.
> 
> In the meantime if you want to have fun while your sysadmin performs a proper Docker install, you can run Docker in user-space using `udocker` in the following way:
> 

thank you! this is a great solution :)

**Comment by pgrosu** [comment]
Awesome!  Glad to hear it worked for you.

Thanks,
~p

**Comment by pichuan** [comment]
Thanks @pgrosu for the suggestion, and @gambalab for confirming it works.

I don't think our team has tried `udocker` before. So it's good to know about this. I'll add an internal task to try this out and consider adding a pointer to it in the future release.
