### ISSUE TITLE
Adding output classes to call_variant

### ISSUE THREAD

**Issue by masgouri** [google/deepvariant#67]
I've been using DeepVariant for about a few months, and it's been working great for me and has been providing me with very pleasing results.

I am currently at a stage where I want to add possible outcomes to the CNN in the call_variants script. Here is how I think I should proceed based on my understanding of the software:
-  When training, the VCF file (that is given to the make_examples script using the 'truth_variants' parameter) indicates the true label, which consists of 0/0, 0/1, or 1/1 for each of the three current classes.
- To train for a new class (e.g. something like classifying het-alt that is close to a splice region), I can modify the VCF file to specify the appropriate regions as a new unused value (e.g. '0/2')

This is as far as I could get unfortunately. I am not sure how to modify the CNN in order to look at this new class as a possible outcome. If I can get pointed in the right direction on how to do this I would appreciate it greatly!

**Comment by pichuan** [comment]
Hi,
we don't currently have a good tutorial for training mode yet. But a quick answer here - your understanding for the "labels" isn't quite correct.
0/0, 0/1, or 1/1 you're referring to is the representation in VCFs, which is HOM-REF, HET, and HOM-ALT.
However, that's not how the "labels" are represented in the training examples.

If you want to see examples of how each of the "training examples" that go into training, please look at this:
https://github.com/google/deepvariant/blob/r0.6/docs/visualizing_examples.ipynb
Specifically, this data here was generated with `make_examples` in training mode:
```
# This tfrecord comes from HG002 PFDA data. I ran make_examples in training mode so we also have the labels.
src = 'gs://deepvariant/datalab-testdata/make_examples_datalab.tfrecord.gz'
```

The "label" that represent the 3 classes are actually 0, 1, or 2, which represents HOM-REF, HET, and HOM-ALT. You can see the `get_label` function in the notebook.

**Comment by depristo** [comment]
Hi masgouri@, 

Thanks for the excellent question and for sharing that you've been having good experiences with DeepVariant. We are always interested in user stories so if you feel like sharing more about your experiences with DeepVariant please send them our way.

There are a few separate issues here; let me try to unpack them.

-- There are some engineering constraints in DeepVariant that assume we train only 3 classes. One example is https://github.com/google/deepvariant/search?utf8=%E2%9C%93&q=DEFAULT_NUM_CLASSES&type= but there may be others. If you want to change the number of classes you'll need to track these down and generalize them. If you do that please send us a CL and we'll make sure to incorporate the changes into the master codebase here. Once you do that it should be possible to train as with as many labels as you like.

-- You'll need to write your own labeler algorithm to provide a label for each training variant. These classes are in deepvariant/labeler. There are two (a PositionalLabeler and a HaplotypeLabeler) so you can use these as templates to hook up your own labeling algorithm. At the core these just need to return an integer label (0 ... N) for each example. Once you get that going it should be simple to label your own examples. Technically the labels can be anything. For example, if you emitted the reference base value as 0 for A, 1 for T, etc I'm pretty sure the machinery can learn to call the reference base from the image with perfect accuracy.

-- The machinery of training really doesn't know anything about NGS data. It just takes the examples and tries to learn to predict the label. Once you get your labels in and the machinery doesn't expect just 3 it should be possible to train anything you want. You can use standard evaluation machinery to decide if your DeepVariant training run is successfully learning something.

-- You'll likely need to write your own version of postprocess_variants (or extend it in some way) to bridge from the predicted labels and the information you want to export in the VCF (or other file format). In germline DeepVariant we learn to predict 0, 1, and 2 which mean hom-ref, het, and hom-alt, respectively, which is encoded in postprocess_variants. You'll need your own equivalent to this code.

Hope this helps!

Mark
--
