### ISSUE TITLE
Some of the sample result vcf files have the SRR suffix in the sample name

### ISSUE THREAD

**Issue by zxy1555847** [google/deepvariant#670]
Hello
I download 40 sample in 1kgp, first I use oqfe to BWA
Then I send the CRAM to Deepvariant to call variants.
But recently, I had found a concern problem, these 40 samples execute same pipeline exactly. But the sample name of result vcf, some of it is right, last have a SRR suffix just as the next figure. And I confirm that this is the SRR suffix exactly as downloaded fastq SRR of per sample from 1KGP. And I also confirm that they all have right and same CRAM.  I don't find the reason of this circumstances and I don't know there will lead to some error to my analysis?
So if someone give me some explain or advice?
very Thanks!
![1687788687108](https://github.com/google/deepvariant/assets/63234787/2aea3b53-babd-4874-9351-e2024fbc81df)

**Comment by pgrosu** [comment]
@zxy1555847 What happens when you run the following command on the CRAM files that show the suffix (just replace `CRAM_FILE` with your file names):

```
samtools samples -h CRAM_FILE
```

**Comment by AndrewCarroll** [comment]
Hi @zxy1555847 

It looks like this output is the result of running GLnexus on gVCFs. I believe you must be running DeepVariant on the 40 single samples and then GLnexus on the gVCF output as recommended in our best practices.

The sample name that occurs in the gVCF file comes from the sample name in the BAM file tag. (as @pgrosu suggests, that should be what follows the `SM:` tag from the output of `samtools view -H ${CRAM} | grep SM`

DeepVariant should take that value as its sample name. DeepVariant should raise an error if a single BAM file has multiple sample names, suggesting that if these files were able to run through and produce output, they should be using the reads appropriately. 

In either case, you can tell DeepVariant to over-ride any sample names present in a file and produce output from all reads with a sample name provided by you as a user. To do so, you can add the flag `--sample` with your sample name to the command.

**Comment by zxy1555847** [comment]
oh~~~yeap.I have find the cause of this problem! 
These samples did go through different pipelines where docker mounted to different containers
but it looks right except the sample name .
Thanks very much
