### ISSUE TITLE
How to filter SNPS

### ISSUE THREAD

**Issue by geng-lee** [google/deepvariant#671]
Hi Developer,

I used the hg38 reference genome, and I successfully ran deepvariant. 
I have the VCF file, how do I filter the SNPS next?
Which metrics should I use, and what is the appropriate threshold for filtering metrics for deepvariant results?

vcf file:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  TAM-42-6-6th
chr1    15274   .       A       G       21.90   PASS    .       GT:AD:DP:GQ:PL:VAF      1/1:0,16:16:19:21,22,0:1
chr1    15820   .       G       T       15.70   PASS    .       GT:AD:DP:GQ:PL:VAF      1/1:0,8:8:13:15,15,0:1
chr1    16841   .       G       T       4.90    PASS    .       GT:AD:DP:GQ:PL:VAF      0/1:12,11:23:4:2,0,9:0.478261
chr1    19004   .       A       G       5       PASS    .       GT:AD:DP:GQ:PL:VAF      0/1:1,3:4:2:0,0,0:0.75

Best,
Jamie

**Comment by pichuan** [comment]
Hi @geng-lee ,
DeepVariant's default should be good for achieving a good F1 metrics. Some of our users sometimes further filter the variants, but it depends on why you're doing it.
Can you tell us why you want filter the SNPs?

**Comment by pgrosu** [comment]
Hi @geng-lee,

Just to expand on a few things.  To understand the impact of the information, you would need to look at each one individually, for example:

- $`GQ`$ $`(genotype`$ $`quality)`$: Tells you the genotype is incorrect using a Phred-scaled $`-10*log_{10}(Error)`$ value.  So with low error you will get a higher score -- a higher score you are confident the call is correct.  In this case your highest is 19, which is borderline for DeepVariant which has it at 20.  A score of 20 means, an error of 0.01, so 99% probability that the call is correct.  This has a relationship to the PL value, which gives normalized Phred-scaled scores per genotype, but in this case would be too low to call confidently.

- $`DP`$ $`(read`$ $`depth)`$: This tells you the filtered reads that support the call.  Here your depth is a bit low for a couple of them.  For research purposes the cutoff is usually 10 or higher.  For clinical 30 would be nice but anything higher than 18 can be good.  You will see an AD value (which includes all reads at that position) as well, but that means you are including reads that could be problematic. 

- $`VAF`$ $`(variant`$ $`allele`$ $`frequency)`$: This is the percentage of reads for a specific variant divided by the overall coverage at that locus.  For heterozygous it would have a value of 50%, for homozygous close to 100% while matching the reference would be 0%.  You will notice one is 75% and it denotes it as heterozygous, but the GQ and PL values are very low to call it confidently.

- $`QUAL`$: These are Phred-scaled values that the probability the genotype is reference (0/0).  For instance a QUAL score of 20 means that your are 99% confident there is a variant at that site, but as before with much lower values you would not be.

You can read more about what these columns mean, and how to interpret them at the [following site](https://gatk.broadinstitute.org/hc/en-us/articles/360035531692-VCF-Variant-Call-Format).

As @pichuan mention, other metrics you can use are a tool such as [Illumina's Hap.py](https://github.com/Illumina/hap.py/tree/master), with which you can benchmark your VCF against gold standard truth datasets, to see the confidence of these calls in terms of number of F1 score, precision and recall.  

More details are provided in the [Hap.py Manual](https://github.com/Illumina/hap.py/blob/master/doc/happy.md).

Hope it helps,
Paul

**Comment by geng-lee** [comment]
@pichuan @pgrosu

Thank you very much for your reply！

Our work focuses on evaluating the off-target effect of base editors through WGS and RNAseq. The number of SNPS called by deepvariant is very large, so we need to filter the SNPS with low confidence to eliminate the noise. The above is very helpful to me！

Thanks!

Best,
Jamie

**Comment by pichuan** [comment]
Thanks @geng-lee for the context. It seems like you might have gotten enough pointers now. I'll close this issue. Feel free to open another issue if you have more questions.
