### ISSUE TITLE
ImportError: cannot import name 'path_helpers' from 'tensorflow.python.saved_model'

### ISSUE THREAD

**Issue by CWYuan08** [google/deepvariant#673]
Dear all,

I was trying to run deepvariant from singularity but I encountered this error:

time /opt/deepvariant/bin/call_variants --outfile "deepvariant/intermediate_results_dir/call_variants_output.tfrecord.gz" --examples "deepvariant/interm
ediate_results_dir/make_examples.tfrecord@12.gz" --checkpoint "/opt/models/wes/model.ckpt"

/mnt/.local/lib/python3.8/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this 
version of SciPy (detected version 1.24.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_nnuiry6u/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 45, in <module>
    from deepvariant import modeling
  File "/tmp/Bazel.runfiles_nnuiry6u/runfiles/com_google_deepvariant/deepvariant/modeling.py", line 56, in <module>
    from tensorflow.python.tpu import tpu_config   
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/tpu/tpu_config.py", line 18, in <module>
    from tensorflow_estimator.python.estimator.tpu.tpu_config import *
  File "/mnt/.local/lib/python3.8/site-packages/tensorflow_estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "/mnt/.local/lib/python3.8/site-packages/tensorflow_estimator/_api/v1/estimator/__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "/mnt/.local/lib/python3.8/site-packages/tensorflow_estimator/_api/v1/estimator/experimental/__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "/mnt.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/canned/dnn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "/mnt/.local/lib/python3.8/site-packages/tensorflow_estimator/python/estimator/estimator.py", line 40, in <module>
    from tensorflow.python.saved_model import path_helpers
ImportError: cannot import name 'path_helpers' from 'tensorflow.python.saved_model' (/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_mode
l/__init__.py)

Strangely, when I checked the Numpy installed in the conda environment it says 1.22.4.
  - Command: singularity exec  deepvariant.simg /opt/deepvariant/bin/run_deepvariant  --model_type WES  --ref  ref.fasta --reads aln_sncr_fc.bam --output_vcf deepvariant/deepvariant_calls.vcf --num_shards 12  --intermediate_results_dir deepvariant/intermediate_results_dir 

I am running it on a slurm cluster. 

Thank you very much!
Best,
CW

**Comment by kishwarshafin** [comment]
@CWYuan08 , 

Can you please see what version of Tensorflow you are using? Also can you try by binding the `/usr/bin/locale` in this following way:

```
singularity exec -B /usr/lib/locale/:/usr/lib/locale/
```
and see if that helps?

**Comment by CWYuan08** [comment]
Dear @kishwarshafin 
thank you for your help,  the Tensorflow version is:
tensorflow                2.12.0                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.32.0                   pypi_0    pypi


I tried singularity exec -B /usr/lib/locale/:/usr/lib/locale/
it only gives:
Usage:
  singularity [global options...] exec [exec options...] <container> <command>

and when I tried with the full command, it says FATAL Flags parsing error: Unknown command line flag 'B'

thanks again!
Best,
CW

**Comment by kishwarshafin** [comment]
So yes, it's a tensorflow version issue. Our current [tensorflow version is 2.11](https://github.com/google/deepvariant/blob/r1.5/settings.sh#L72)

Can you please try the [singulaity quickstart](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md#cpu-version) to see if that works for you. The command actually is `singularity run -B` not `singularity exec -B` which maybe the reason for the error.

**Comment by CWYuan08** [comment]
Dear @kishwarshafin,
many thanks for your help, it is working now! 
I am also wondering if there is a model_type for Nanopore R9.4.1 chemistry?

Best,
CW

**Comment by kishwarshafin** [comment]
@CWYuan08 , for Nanopore R9.4.1, we suggest using [PEPPER](https://github.com/kishwarshafin/pepper). DeepVariant supports R10.4 simplex and duplex modes.

Thank you for confirming that it is working for you now. I will close this issue.
