### ISSUE TITLE
Unable to get vcf output file

### ISSUE THREAD

**Issue by FraSilver** [google/deepvariant#675]
Describe the issue:
I can't get vcf output after bind mount a root directory

Setup
  - Operating system: Windows 11, but mount an Ubuntu VM through multipass
  - Type of data:  fasta, bam and vcf file

Steps to reproduce:
  - Command:
 #Configure the DeepVariant environment variables (missing input directory,...)
BIN_VERSION="1.5.0"

sudo apt -y update
sudo apt-get -y install docker.io
sudo docker pull google/deepvariant:"${BIN_VERSION}"

# Pull the image
singularity pull docker://google/deepvariant:"${BIN_VERSION}"
PWD=/mountpoint/fastQ
INPUT_DIR="${PWD}/testdata_input"
mkdir -p ${INPUT_DIR}
OUTPUT_DIR="${PWD}/04.deepvariant_out"
mkdir -p "${OUTPUT_DIR}"

sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --ref=/input/Homo_sapiens_assembly38.fasta \
  --reads=/input/$FQ.align.sort.marked.bam \
  --output_vcf=/output/$FQ.vcf.gz \
  --output_gvcf=/output/$FQ.g.vcf.gz \
  --num_shards=2 
  - Error trace: 
  
It displays: Task reading input the .bam file but it ends up with 0 candidates.
I suppose it can read the input files

Does the quick start test work on your system?
This the tutorial I've used: https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md

**Comment by pgrosu** [comment]
@FraSilver You are very close.  All you have to do is two things:

$`1)`$ First add the mapping of the output directory to the `docker run` command (below the one for input) as follows:
```
-v "${INPUT_DIR}":"/input" \
-v "${OUTPUT_DIR}":"/output" \
```

This basically makes the output directory visible from within the running Docker container, so that the results are available after Docker completes its run.

$`2)`$ Next define the `FQ` variable, as it seems to be referenced as `$FQ`, but I'm not seeing it defined.  If it is already defined previously, then that's fine.

If you have multiple lines, you will need to also add the backslash `\` as follows, so that the command doesn't get started before the last line gets pasted:

```
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --ref=/input/Homo_sapiens_assembly38.fasta \
  --reads=/input/$FQ.align.sort.marked.bam \
  --output_vcf=/output/$FQ.vcf.gz \
  --output_gvcf=/output/$FQ.g.vcf.gz \
  --num_shards=2 
```

Let me know if it helps.

Thanks,
Paul

**Comment by FraSilver** [comment]
I have copy-n-paste the wrong script. 
I have already written -v "${OUTPUT_DIR}":"/output", declared my $FQ variable and used backslash.
It doesn't work.
In my "/input" directory I have .fasta file, .fasta.fai, bam and .bai file. I suppose I don't require nothing else. (maybe, also VCF tools if the aim is the vcf output "prediction". 

Any suggestion?
singularity run doesn't work as well.
I get the "deepvariant_1.5.0.sif " image file after running singularity pull...

Thanks in advance,
Fra

**Comment by pgrosu** [comment]
Hi Fra,

So let me go through a few items:

$`1)`$ It fails to find variant candidates in the `make_examples` stage.  Assuming the reads were generated from Illumina whole-exome sequencing (WES), this BAM file is fairly large.  To troubleshoot, it is best to specify a smaller region you know candidates should be, as you will need significant memory for this to work for the the whole genome.  The flag specifying a region is of this format, and adjust accordingly for your best candidate region of your study: 

```
--regions "chr20:10,000,000-10,010,000"
```

You can just use Docker as you are running using that already (via `docker run`), to keep the number of variables small.  Before you run Docker again, please look at the next two items as well.

$`2)`$ Assuming you used the same reference sequence file (`Homo_sapiens_assembly38.fasta`) to perform the alignment, please run the following command (also you don't need to mark duplicates with DeepVariant):

``samtools view -H $FQ.align.sort.marked.bam``

You can provide this via a gist or an attachment.

$`3)`$ To perform a preliminary QC on your BAM file can you run the following command:

``samtools flagstat $FQ.align.sort.marked.bam``

You can provide this via a gist or an attachment.

If you have `fastQC` you can perform the following to generate the report, which you can attach a printed PDF file of the HTML output -- or you can attach the html with the accompanying zip file, if that is easier:

` fastqc $FQ.align.sort.marked.bam`

$`4)`$ When you run the `docker run` command for `run_deepvariant` could you please provide the full output, to see where it gets stuck with errors, or how it completes.  Also how much memory and disk space is freely available on the VM?  I'm assuming the BAM file is several gigabytes.

DeepVariant can read BAM files and will generate the VCF and GVCF, so no additional tools are required for it to work out of the box.  We are just using a few tools to troubleshoot, but usually they are not necessary.

Would you be willing to share the BAM file to get a better idea what is happening?

Thanks,
Paul

**Comment by FraSilver** [comment]
My BAM file is 300 MBytes. I have less than 100 Gb of disk space. I suppose is a lack of space.

**Comment by pgrosu** [comment]
Hi Fra,

That seems a bit small compared to other WES BAM files, which are between 5 - 10 GB:

https://ega-archive.org/datasets/EGAD00001005247/files

The disk space seems okay, though you have some memory-mapped file-systems, which should be okay if you have a good amount of memory.  

Memory on Ubuntu can be checked with `cat /proc/meminfo` or (`top`).  For example, when I ran the variant candidate selection, on just a small region of a chromosome and monitored memory usage, I saw the following trend:

![image](https://github.com/google/deepvariant/assets/6555937/7e200851-3fde-4ad6-bf75-477ccefb9e32)

You'll notice that it can be resource intensive.  This is the reason I was opting we troubleshoot by first trying with a smaller region of a chromosome using `--regions`, ideally one you know variants should be present.  A preliminary check with `samtools view -c BAM REGION` would ensure you have mapped reads there for DeepVariant to find, and with `samtools flagstat` to check on that subregion for the number of quality reads. 

Hope it helps,
Paul

**Comment by MariaNattestad** [comment]
Hi @FraSilver
As a sanity check, can you try running this quick start with no modifications at all? Try just copy-pasting it exactly as written without using your own files or making any other changes to the command:
https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md

**Comment by FraSilver** [comment]
I' m using Ubuntu Virtual-Machine mount on Windows 11.
Running "cat ${INPUT_DIR}/ucsc.hg19.chr20.unittest.fasta" it displays the fasta file, but after running:
sudo docker run...., it reports -bash: --ref=/mountpoint/fastQ/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta: No such file or directory.

Why?

**Comment by pgrosu** [comment]
Thank you Maria -- that's definitely a more elegant starting point.

Hi Fra,

The reason why you are seeing that is because there are additional characters after some of the backslash characters (`\`) at the end of each line.  So you need to make sure there are no spaces or characters after each backslash (i.e. it needs to be the last character on those lines) like this:

```
  --model_type=WGS \
  --ref="${INPUT_DIR}"/ucsc.hg19.chr20.unittest.fasta \
```

The strings that starts with ` **Replace this string...`, `  **Optional.` or ` **How many cores...` need to be removed, as they are there in the documentation only to provide additional clarity regarding those parameters.  Otherwise Bash interprets the next line as a separate new command to run, like this:

```
paul$ --ref=/mountpoint/fastQ/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta
-bash: --ref=/mountpoint/fastQ/quickstart-testdata/ucsc.hg19.chr20.unittest.fasta: No such file or directory
paul$
```

Paul

**Comment by FraSilver** [comment]
ValueError: NOT_FOUND: Could not open /input/SAMPLE01.align.sort.marked.bam
parallel: This job failed:
/opt/deepvariant/bin/make_examples

I have a right bam file. 
Can be that "make examples" require a python version incompatible with my python 3.10.x version installed on Unix-virtual machine?

**Comment by pgrosu** [comment]
Hi Fra,

The Docker container has it's own internal version of Python so it becomes independent any system it would run on.  

I have 4 questions:

1) Did the sanity check Maria suggested work successfully for you?  This is important to complete first as it gives context that your VM is compatible with a successful DeepVariant run.

2) Can you please provide the whole command that you just ran including any variables that were defined.  Without both of these it becomes impossible to eliminate possible causes of the error, as they provide context as to how the command was set up.  

3) Please provide the `ls -l ${INPUT_DIR}` output to make sure it lists the BAM file using that variable definition.

4) Can you provide the complete output of the run, including error.  This gives context as how far it ran before it stopped, which includes anything that worked.

Thanks,
Paul

**Comment by FraSilver** [comment]
It works. Both with the tutorial data and my data.
It doesn't read bam file with a variable previously declared. I've changed $FQ with SAMPLE01 and it works.

Thanks. 
Kind regard,
Fra

**Comment by pgrosu** [comment]
Hi Fra,

That's great to hear!  Hopefully you were able to detect some expected variant candidates, and ideally discover some novel and relevant ones as well.

Glad this helped you out -- it was a fun team effort!
Paul

**Comment by FraSilver** [comment]
Hi pgrosu, sorry again.
It works using the quickstart tutorial but not with my BAM and fasta file.
Running ls -l ${INPUT_DIR} it prints out: 
Homo_sapiens_assembly38-3.sorted.bed.gz.tbi
Homo_sapiens_assembly38.fasta
Homo_sapiens_assembly38.fasta.fai
SAMPLE01.align.sort.marked.bai
SAMPLE01.align.sort.marked.bam

Code I run:
PWD=/mountpoint/fastQ
INPUT_DIR="${PWD}/testdata_input"
mkdir -p ${INPUT_DIR}
OUTPUT_DIR="${PWD}/testdata_output"
mkdir -p "${OUTPUT_DIR}"

sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --ref=/input/Homo_sapiens_assembly38.fasta \
  --reads=/input/SAMPLE01.align.sort.marked.bam \
  --output_vcf=/output/SAMPLE01.vcf.gz \
  --output_gvcf=/output/SAMPLE01.g.vcf.gz \
  --num_shards=2 

It displays: Task 0/2: 0 candidates. Otherwise, using quick-start.md tutorial it showed 6 candidates.

How can I resolve?
Thanks,
Fra

**Comment by pgrosu** [comment]
Hi Fra,

If it cannot find candidates, that happens during the `make_examples` stage.   `make_examples` goes through an allele counter, and very sensitive variant caller to determine if there is enough read support for a candidate.  Was the same genome (fasta) used for the alignment phase (from fastq) when generating the BAM files?  When you load your BAM file in IGV to how many chromosomes and chromosomal regions does it show alignment for? 

In the [quickstart tutorial](https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md#run-deepvariant-with-one-command) it uses the WGS model not the WES one (as indicated by `--model_type=WES` above).  Also I believe your BAM file is only 300 Mb, which a bit small compared to other WES ones:

https://ega-archive.org/datasets/EGAD00001005247/files

Is your dataset a WES or WGS dataset?  

Thanks,
Paul

**Comment by pgrosu** [comment]
Hi Fra,

As far as I can infer, there is something in the BAM and reference files that the variant caller is unable to call variants for.  Can you please take a look in the chromosome 8 region with the [Integrative Genomics Viewer (IGV)](https://software.broadinstitute.org/software/igv/) using your BAM aligned to the same exact reference, to confirm that you see some variation and proper alignment.  I am looking at the call variant code, and the allele counts are dependent on the reference and read support by position.

You should also limit your analysis with the `--regions` flag so it is quicker as well.  If your data is WES then you should use the WES model, in order for the results to be scientifically valid.

Maybe it might help if you realign your FASTQ files to the reference used by DeepVariant to regenerate the BAM file and the subsequent BAI file, just to be sure nothing happened along the way.

Hope it helps,
Paul

**Comment by FraSilver** [comment]
Hi Paul,
it doesn't work. I have confirmed the presence of variants in my BAM file with IGV software and used --regions flag to be faster.
I do not think realign is the solution to the problem, unfortunately.

Thanks you all the same,
Fra

**Comment by pgrosu** [comment]
Hi Fra,

That is very interesting -- let me ask a few questions:

$`1)`$ Would you be willing to share the data?

$`2)`$ Do other BAM files that you have exhibit similar behavior?  I remember you mentioning that the quickstart tutorial worked for you.

$`3)`$ If you want to not filter out possible candidates, you can adjust this via the `--make_examples_extra_args=`, by setting some or all of the following parameters to your preference:

* vsc_min_count_snps (the default is 2)
* vsc_min_count_indels (the default is 2)
* vsc_min_fraction_snps (the default is 0.12)
* vsc_min_fraction_indels (the default is 0.06)
* vsc_min_fraction_multiplier (the default is 1.0)

Here is an example:

```
--make_examples_extra_args='vsc_min_count_snps=3,vsc_min_count_indels=3,vsc_min_fraction_snps=0.12,vsc_min_fraction_indels=0.06'
```

You can read more details about these parameters at the following links:

https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data

https://github.com/google/deepvariant/blob/r1.5/deepvariant/make_examples_options.py#L178-L202

$`4)`$ Have you tried to see if other variant callers such as [freebayes](https://github.com/freebayes/freebayes) exhibit similar behavior with your dataset?

$`5)`$  If you type on your Linux terminal (Bash command-line) the following command:

```
cat /proc/meminfo
```

What does it report back?

Thanks,
Paul
