### ISSUE TITLE
nvidia base image is no longer available

### ISSUE THREAD

**Issue by doron-st** [google/deepvariant#676]
**Describe the issue:**
nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04 docker image is no longer available to be used as a base-image

**Setup**
  - Operating system: linux
  - DeepVariant version: 1.5

**Steps to reproduce:**
  - Command: docker pull nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04
  - Error trace: Error response from daemon: manifest for nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04 not found: manifest unknown: manifest unknown
  
Do you have a recommendation for an alternative base-image that deepvariant docker could be built with GPU support?
Thanks!

**Comment by MariaNattestad** [comment]
Thanks for bringing this to our attention!
I'm running our tests with `nvidia/cuda:12.1.1-cudnn8-devel-ubuntu20.04` now and will update here when I have confirmed whether it's working.

**Comment by MariaNattestad** [comment]
The 12.1.1 base image did NOT work. I tested `nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04` instead, which did work correctly. 

# Please use `nvidia/cuda:11.3.1-cudnn8-devel-ubuntu20.04`
