### ISSUE TITLE
Is --dry_run not a flag with DeepTrio?

### ISSUE THREAD

**Issue by hosseinvk** [google/deepvariant#687]
When running deeptrio with `--dry_run=true`, the error message "FATAL Flags parsing error: Unknown command line flag 'dry_run'" pops up and run exits. 
Here is part of the command I used:

`
singularity run -B /usr/lib/locale/:/usr/lib/locale/ \
  docker://google/deepvariant:deeptrio-"${BIN_VERSION}" \
  /opt/deepvariant/bin/deeptrio/run_deeptrio \
  --model_type=WGS \
  --ref=Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta \
  --reads_parent1=markduplicates/S_500061.md.bam \
  --reads_parent2=markduplicates/S_500062.md.bam \
  --reads_child=markduplicates/S_500063.md.bam \
  --output_vcf_parent1 output/S_500061.output.vcf.gz \
  --output_vcf_parent2 output/S_500062.output.vcf.gz \
  --output_vcf_child output/S_500063.output.vcf.gz \
  --sample_name_parent1 'S_500061' \
  --sample_name_parent2 'S_500062' \
  --sample_name_child 'S_500063' \
  --num_shards $(nproc)  \
  --intermediate_results_dir output/intermediate_results_dir \
  --output_gvcf_parent1 output/S_500061.g.vcf.gz \
  --output_gvcf_parent2 output/S_500062.g.vcf.gz \
  --output_gvcf_child output/S_500063.g.vcf.gz \
  --output_gvcf_merged output/FAM1.g.vcf.gz\
  --dry_run=true \
  --vcf_stats_report=true
`

Thanks for advice.

**Comment by pgrosu** [comment]
Hi @hosseinvk,

So just a couple of things:

$`1)`$ The `--output_gvcf_merged` flag is not supported in `run_deeptrio.py`, and GLNexus should be used instead, as indicated by issue #544.

I have updated the command with the `--output_gvcf_parent1` and `--output_gvcf_parent2` flags.

$`2)`$  If I run it via Docker like this, I get the dry run to work:

```
docker run google/deepvariant:deeptrio-latest /opt/deepvariant/bin/deeptrio/run_deeptrio --model_type=WGS --ref=Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta --reads_parent1=markduplicates/S_500061.md.bam --reads_parent2=markduplicates/S_500062.md.bam --reads_child=markduplicates/S_500063.md.bam --output_vcf_parent1 output/S_500061.output.vcf.gz --output_vcf_parent2 output/S_500062.output.vcf.gz --output_vcf_child output/S_500063.output.vcf.gz --sample_name_parent1 'S_500061' --sample_name_parent2 'S_500062' --sample_name_child 'S_500063' --num_shards $(nproc) --intermediate_results_dir output/intermediate_results_dir --output_gvcf_parent1 output/S_500061.g.vcf.gz --output_gvcf_parent2 output/S_500062.g.vcf.gz --output_gvcf_child output/S_500063.g.vcf.gz --output_gvcf_parent1 output/parent1.g.vcf.gz --output_gvcf_parent2 output/parent2.g.vcf.gz --dry_run=true --vcf_stats_report=true
```

The output I get:

```
paul$ docker run google/deepvariant:deeptrio-latest /opt/deepvariant/bin/deeptrio/run_deeptrio --model_type=WGS --ref=Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta --reads_parent1=markduplicates/S_500061.md.bam --reads_parent2=markduplicates/S_500062.md.bam --reads_child=markduplicates/S_500063.md.bam --output_vcf_parent1 output/S_500061.output.vcf.gz --output_vcf_parent2 output/S_500062.output.vcf.gz --output_vcf_child output/S_500063.output.vcf.gz --sample_name_parent1 'S_500061' --sample_name_parent2 'S_500062' --sample_name_child 'S_500063' --num_shards $(nproc) --intermediate_results_dir output/intermediate_results_dir --output_gvcf_parent1 output/S_500061.g.vcf.gz --output_gvcf_parent2 output/S_500062.g.vcf.gz --output_gvcf_child output/S_500063.g.vcf.gz --output_gvcf_parent1 output/parent1.g.vcf.gz --output_gvcf_parent2 output/parent2.g.vcf.gz --dry_run=true --vcf_stats_report=true
I0726 08:57:43.023837 139824599930688 run_deeptrio.py:519] Creating a directory for intermediate results in output/intermediate_results_dir

***** Intermediate results will be written to output/intermediate_results_dir in docker. ****


***** Running the command:*****
time seq 0 0 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref "Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta" --reads_parent1 "markduplicates/S_500061.md.bam" --reads_parent2 "markduplicates/S_500062.md.bam" --reads "markduplicates/S_500063.md.bam" --examples "output/intermediate_results_dir/make_examples.tfrecord@1.gz" --sample_name "S_500063" --sample_name_parent1 "S_500061" --sample_name_parent2 "S_500062" --channels "insert_size" --gvcf "output/intermediate_results_dir/gvcf.tfrecord@1.gz" --pileup_image_height_child "60" --pileup_image_height_parent "40" --task {}


***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "output/intermediate_results_dir/call_variants_output_child.tfrecord.gz" --examples "output/intermediate_results_dir/make_examples_child.tfrecord@1.gz" --checkpoint "/opt/models/deeptrio/wgs/child/model.ckpt"


***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "output/intermediate_results_dir/call_variants_output_parent1.tfrecord.gz" --examples "output/intermediate_results_dir/make_examples_parent1.tfrecord@1.gz" --checkpoint "/opt/models/deeptrio/wgs/parent/model.ckpt"


***** Running the command:*****
time /opt/deepvariant/bin/call_variants --outfile "output/intermediate_results_dir/call_variants_output_parent2.tfrecord.gz" --examples "output/intermediate_results_dir/make_examples_parent2.tfrecord@1.gz" --checkpoint "/opt/models/deeptrio/wgs/parent/model.ckpt"


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta" --infile "output/intermediate_results_dir/call_variants_output_child.tfrecord.gz" --outfile "output/S_500063.output.vcf.gz" --nonvariant_site_tfrecord_path "output/intermediate_results_dir/gvcf_child.tfrecord@1.gz" --gvcf_outfile "output/S_500063.g.vcf.gz"


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta" --infile "output/intermediate_results_dir/call_variants_output_parent1.tfrecord.gz" --outfile "output/S_500061.output.vcf.gz" --nonvariant_site_tfrecord_path "output/intermediate_results_dir/gvcf_parent1.tfrecord@1.gz" --gvcf_outfile "output/parent1.g.vcf.gz"


***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "Sequence/WholeGenomeFasta/Homo_sapiens_assembly38.fasta" --infile "output/intermediate_results_dir/call_variants_output_parent2.tfrecord.gz" --outfile "output/S_500062.output.vcf.gz" --nonvariant_site_tfrecord_path "output/intermediate_results_dir/gvcf_parent2.tfrecord@1.gz" --gvcf_outfile "output/parent2.g.vcf.gz"

paul$
```

Are you running the latest version of DeepTrio?  Here's how you can find the version your are using via the `--version` flag:

```
paul$ docker run google/deepvariant:deeptrio-latest /opt/deepvariant/bin/deeptrio/run_deeptrio --version
DeepTrio version 1.5.0
paul$
```

Hope it helps,
Paul

**Comment by hosseinvk** [comment]
Thank you Paul. It seems I was using v1.1.0 and once changed it to v.1.5.0 the --dry_run command worked.
There is one thing I was going to ask and appreciate you kind help. I have mistakenly assigned 
```
S_500061 as child
S_500062 as parent1
S_500063 as parent2
```
all over the initial script (not shared here) whereas it should have been
```
S_500061 as parent
S_500062 as parent2
S_500063 as child
```
I reckon I will need to re-run the analysis?

Thanks.

**Comment by pgrosu** [comment]
Hi @hosseinvk,

Glad to hear it worked!  Regarding the analysis, yes you will need to run it again given the new assignment.  So there is both a parent and child model that was created, through which the tensor image (generated from your reads) is fed to provide inference about your child or parent variation.  The reason you will need to run it again is because these models were trained with the assumption that the child resides in the middle between the two parents, as in the pileup image shown below.   With such a trained configuration, your data would also need to be formatted with the same tensor configuration -- as provided through your assignments -- as it would be most informative when calling using the child model with the parents providing the supporting evidence -- and vice versa when processing the tensor through the parent model:

![image](https://github.com/google/deepvariant/assets/6555937/080684de-68b9-4f8b-8c45-1625484d96af)

This is provided in the [DeepTrio paper](https://www.biorxiv.org/content/10.1101/2021.04.05.438434v1.full.pdf) with additional details.

Hope it helps,
Paul

**Comment by hosseinvk** [comment]
Thanks for sharing the paper. I will re-run the analysis. Your help is appreciated.
