### ISSUE TITLE
No GPU usage when running GPU version of DV

### ISSUE THREAD

**Issue by GaianX39** [google/deepvariant#688]
Hi there,

I have no problem running the CPU version but the GPU version was not function normally either through slurm request or logging in to the GPU node. I found no GPU process through $nvidia-smi with my codes attached as follow:

```
singularity run --nv -B /usr/lib/locale/:/usr/lib/locale/ \
    --bind /cluster/home/cx/variant_calling/slurm/DV/in:/in \
    --bind /cluster/home/cx/variant_calling/slurm/DV/out:/out \
    docker://google/deepvariant:1.5.0-gpu \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type=WES \
    --ref=/in/GRCh37_primary/GRCh37.primary_assembly.genome.fa \
    --reads=/in/SRR2962694.sorted.bam \
    --regions=/in/all_19.bed \
    --output_vcf=/out/SRR2962694.vcf.gz
```

Here is the GPU status after running the code above, no process on GPU is running.
![微信图片_20230728102005](https://github.com/google/deepvariant/assets/80762999/ae17ac46-1c73-449e-9943-c627a9bc13a7)

**Comment by pgrosu** [comment]
Hi @GaianX39,

DeepVariant has three stages it progresses through: `make_examples`, `call_variants` and `postprocess_variants`.  

Only the `call_variants` stage uses a GPU, as noted in the following page:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-quick-start.md#notes-on-gpu-image

So it might be a while until you see it, which is only after the `make_examples` stage completes and the `call_variants` stage begins.

Hope it helps,
Paul

**Comment by GaianX39** [comment]
thanks for a quick reply and that helps a lot! I will try running again
