### ISSUE TITLE
Somatic Variant Calling for Long Reads PacBio

### ISSUE THREAD

**Issue by kiranpatil222** [google/deepvariant#692]
Hi,

I used DeepVariant for PacBio Germline variant calling, Just wondering if there is separate method for Somatic Variant Call ( Tumor/Normal or Tumor Only like in Mutect2/Strelka )  in DeepVariant?

**Comment by AndrewCarroll** [comment]
Hi Kiran,

We don't have a general release for this. If you are interested, you can email awcarroll@google.com and we can follow up on options.
