### ISSUE TITLE
GFF3 to BED coordinate incompatibility in DV RNA-seq case study

### ISSUE THREAD

**Issue by AldhairMedico** [google/deepvariant#693]
Hi, 
I am trying to run DV using the RNA-seq case study as an example before my actual runs
I found that at some point you used:
`curl -L https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_41/gencode.v41.basic.annotation.gff3.gz > data/gencode.v41.basic.annotation.gff3.gz
gzip -dc data/gencode.v41.basic.annotation.gff3.gz | \
awk -v OFS='\t' '$1 == "chr20" && $3 == "CDS"  && $4 < $5 { print $1, $4, $5, "CDS" }' | \
awk '!dup[$0]++' > data/chr20_CDS.bed`

To get the CDS coordinates from the GFF3 file. 

- But isn't GFF3 a 1-based coordinate system while BED is a 0-based one?
- Do we just need to subtract 1 from the start coordinate right? 

Thanks for your time and help

**Comment by pgrosu** [comment]
Hi @AldhairMedico,

Good catch and makes sense, but probably it's easier to use [`gff2bed` from bedops](https://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/gff2bed.html) and select the columns from there.

Hope it helps,
Paul

**Comment by AldhairMedico** [comment]
Thanks Paul! 
I'm closing this issue now. 
Jack
