### ISSUE TITLE
build_and_test.sh fail

### ISSUE THREAD

**Issue by TuBieJun** [google/deepvariant#7]
Hi, I get a fail info when i try run the build_and_test.sh. So the fail info  will affect my normal using?
![image](https://user-images.githubusercontent.com/15261087/33794972-3a17c480-dd11-11e7-9276-68e701695cd0.png)

the log info is 
![image](https://user-images.githubusercontent.com/15261087/33794983-50dbcc52-dd11-11e7-8f0d-bc1a80445beb.png)

**Comment by pichuan** [comment]
From the log it seems like there's something to do with your authentication to the Google Cloud Platform. But usually this shouldn't fail even if you didn't set that up. Can you give us a bit more description about your machine? (OS version, if you're running on cloud, where and what type of machine, etc)

**Comment by TuBieJun** [comment]
Here is my OS version:
![image](https://user-images.githubusercontent.com/15261087/33801703-8ccaeb16-dd9e-11e7-9ba8-cca6cc36556f.png)
When i build deepvariant，i set the TF_NEED_GCP to 0. But the make_smaple_test and the example of  make_samples in  "DeepVariant quick start" use GCP default, so Is there a parameter to  use local deepvariant, not in GCP.

**Comment by pgrosu** [comment]
@TuBieJun Try first resetting your credentials on your machine to be yours via either of the following commands:

`gcloud beta auth application-default login`

or

`gcloud auth login`

**Comment by TuBieJun** [comment]
hi  i have check the error. The error reason is  I can't connect the GCP, the make_samples.py need to run 
'htslib_gcp_oauth.init()', I remove this and install htslib in local. So build_and_test pass all. 
![image](https://user-images.githubusercontent.com/15261087/33802638-2bf6bb2c-ddb6-11e7-963e-950660e357ff.png)

![image](https://user-images.githubusercontent.com/15261087/33802647-66a7728e-ddb6-11e7-9279-80c1c79a37e0.png)

thanks everyone~

**Comment by depristo** [comment]
We've got a fix for the GCP dependency internally, and will sync it to the OSS github version on our next push. Thanks for the report.
