### ISSUE TITLE
The principle of genotype interpretation

### ISSUE THREAD

**Issue by jianqi-chen** [google/deepvariant#702]
The principle of PL, and sometimes the genotype and mutation ratio may not match, and after one generation of validation, some genotype results are incorrect.How should I handle it?

**Comment by pgrosu** [comment]
Hi @jianqi-chen,

I'm assuming you are working with germline diploid samples.

$`1)`$ Ti/Tv ratio is calculated as follows.  For every variant that is a biallelic SNP, it will check as follows:

```Python
 is_transition = if {'A' <-> 'G'} or {'C' <-> 'T'}
 is_transversion = not( is_transition )
 else is_transition = is_transversion = False
```

 The Ti/Tv ratio is calculated as `float(variant_counts(is_transition)) / variant_counts(is_transversion)`, or `if Tv = 0` then it will be reported as a string formatted as `'variant_counts(is_transition) / 0'`.

$`2)`$ The genotype is calculated as follows.  Reads are collected, and sometimes realigned based on the model selected.  Call sites are determined by an allele counter that goes through every position of aligned reads.  For every viable call site it will generate a set of matrices based on your sets of aligned reads in that region - for some models it will perform local realignment.  These matrices will limit themselves to a maximum of 95 reads (as it will downsample the reads if there are too many), with the first 5 rows representing the reference.  This will then go through the model, and it generate three genotype probabilities: homozygous ref, het, and homozygous alt.  Based on the maximum genotype probability, that will be used to generate the genotype (as the most likely).

$`3)`$ The PL is generated from the 3 probabilities to generate the -10*log10() of the genotypes and zeroing to the most likely one (i.e. normalized with the highest genotype probability having PL=0).

Now given the three steps above let's tie them together.  Simplifying to the common factors, those would be: read realignment, read quality, and predicted genotype likelihoods.  Read alignment and read quality determine the call site and type (i.e. SNP).  Then these (via a matrix representation processed through a model) determine predicted genotype likelihoods, which in turn determine the GQ, PL and GT.  TiTv counts depends strongly on how the call site was determined by the alignment of reads, and the [thresholds being set](https://github.com/google/deepvariant/blob/r1.5/docs/FAQ.md#why-does-deepvariant-not-call-a-specific-variant-in-my-data).  The GQ sometimes might be very low, which affects the GT (i.e. `./.`).  This happens with every run, and if you are seeing discrepancies there are other factors that can affect it such as local alignment and read generation.

Does that help?

Paul

**Comment by akolesnikov** [comment]
Hi @jianqi-chen,

In order to give you a more concrete answer it would be very helpful if you could provide couple of examples from your validation.
