### ISSUE TITLE
question about vcf FORMAT

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#707]
Hello! 
I would like to know if DeepVariant can provide strand bias information. For example, by adding additional parameters to output Read depth for each allele on the forward strand and the reverse strand in the VCF file.

Looking for your reply.
Thanks.

**Comment by pgrosu** [comment]
Hi @crazysummerW,

That might be tricky as its deeply encoded in the pileup image construction - and how it's processed - which would would require some code-rewrite to extract it properly.  If you have reads that don't span more than 95 for that specific variant position - or you downsample to 95 - you can reconstruct that from the BAM files. 

There might be other avenues I haven't thought about yet, though I'll keep thinking.

Paul

**Comment by kishwarshafin** [comment]
Hi @crazysummerW,

Currently we only report DP or depth for each allele/candidate variant. We do not report forward and reverse strand support for alleles. However, strand information is encoded in the example we create for each example that the neural network consumes. So intrinsically, it is considered during genotyping but not reported in the VCF file. Hope this helps.
