### ISSUE TITLE
Regarding the haplotagging paper

### ISSUE THREAD

**Issue by pgrosu** [google/deepvariant#709]
Hello Team,

Congratulations on the [nice haplotagging paper](https://www.biorxiv.org/content/10.1101/2023.09.07.556731v1)!  I have looked through the paper, algorithm and code, and there are some things that could be made a bit more clear in the paper.

Let me know if you would like me to help you with the paper.

Best regards,
Paul

**Comment by kishwarshafin** [comment]
Hi @pgrosu,

Thank you very much for looking into the paper. We always try to do our best to present the algorithm, code and experimental design that deliver to deliver the message most clearly. Any feedback on how to make it better and more understandable is always highly appreciated. However, as this is not a technical issue about DeepVariant, it would be helpful to do this over email. Please send an email to shafin@google.com at your convenience so we can discuss how to improve the manuscript.

**Comment by pgrosu** [comment]
Hello Kishwar (@kishwarshafin),

I followed your advice and have emailed you my review report.  It took a little bit longer than I thought, as I also rewrote the algorithm section besides suggested corrections.  If you think it would be more efficient, feel free to email me the LaTeX documents and figures.

Let me know over email what you think of the report.

Best regards,
Paul
