### ISSUE TITLE
make_examples: ValueError

### ISSUE THREAD

**Issue by ksw9** [google/deepvariant#71]
Hi,
I am running into an error when I try to use make_examples with a training VCF. The error does not occur when I run make_examples in training mode, without a truth VCF, so I believe the error occurs there. I call make examples with the following:
`/opt/deepvariant/bin/make_examples --mode training --ref refs/${ref} --reads ${BAM} --examples ${base}.tfrecord --truth_variants ${TRUTH_VCF} --confident_regions refs/confidence.bed `

I am using a simple test VCF attached here and I get the following error:
`
ValueError: Invalid argument: Invalid interval: reference_name: "NC_000962.3" start: -1 end: 22
`
Could you point me towards how to debug this issue? Thank you! 
[test.vcf.gz](https://github.com/google/deepvariant/files/1985941/test.vcf.gz)

**Comment by depristo** [comment]
I suspect there's a problem with your BED file. Is there a bad interval in that BED file? I wonder if there's an off-by-one error somewhere in the BED reader (I really hope not).

**Comment by ksw9** [comment]
Thank you - I'm attaching my BED file which simply defines the entire length of the chromosome (I am working on a bacterium):
NC_000962.3     0	4411531
Is this an issue with a non-human genome?

(Saved with a .txt so that I could upload.)
[confidence.bed.txt](https://github.com/google/deepvariant/files/1986525/confidence.bed.txt)

**Comment by depristo** [comment]
This seems like a genuine bug. Is there any way you can share the genome reference and reads along with a command line that reproduces the issue? It's not clear to me what the actual issue is and that would help a lot debugging the actual problem.

**Comment by ksw9** [comment]
Thank you for looking into this. I'm running DeepVariant on a docker image. Below is my command line.  My reference genome, reads, and truth VCF are 300Mb, so I will send via email if that is okay.
 ```
ref=H37Rv.fa
BAM=GCA_000193185.1_1_1.bowtie2.rmdup.bam
TRUTH_VCF=test.vcf.gz
base=${BAM%.rmdup.bam}

/opt/deepvariant/bin/make_examples --mode training --ref ${ref} --reads ${BAM} --examples ${base}.tfrecord --truth_variants ${TRUTH_VCF} --confident_regions confidence.bed 

```

**Comment by depristo** [comment]
Sounds great, I'll be on the lookout for it.

**Comment by depristo** [comment]
Just confirming I can reproduce the error myself. I think I know what the problem is. In the meantime you can use the previous labeling algorithm as a workaround. Just add ' --labeler_algorithm positional_labeler' to your command line, which is working for me just fine right now.

**Comment by ksw9** [comment]
Thank you! I'll test that out.

**Comment by depristo** [comment]
The fix for the issue with the haplotype_labeler is ready in the internal codebase and will appear in the next DeepVariant release. Thanks for working through these issues with us.
