### ISSUE TITLE
merge gvcf file

### ISSUE THREAD

**Issue by Tonitsk8264** [google/deepvariant#710]
I used deepvariant to call variant on HIFI and ONT sequencing data, and merged the generated gvcf files. When I used gatk to merge, an error occurred. When using glnexus to merge gvcf, its config options are only DeepVariantWGS and DeepVariantWES. Can you provide me with some help and suggestions about merging gvcf files? grateful.

**Comment by AndrewCarroll** [comment]
Hi @Tonitsk8264 

We recommend DeepVariantWGS preset for merging HiFi and ONT data. The practical differences between the DeepVariantWGS and DeepVariantWES presets are small, and we generally find that the effects of different choices for GLnexus preset tends to be different only for some edge cases.

In any case, for your use, DeepVariantWGS is the one to choose.

**Comment by Tonitsk8264** [comment]
I understand. Thank you for answering my questions.
