### ISSUE TITLE
calling variant

### ISSUE THREAD

**Issue by Tonitsk8264** [google/deepvariant#713]
I'm sorry to bother you again, but I have a few more questions for you. 

At present, the sequencing data we used are pacbio clr and ont r9.4. Can deepvariant be used to call varinat? If so, what should be selected for the --model_type parameter (HIFI / PACBIO ONT_R104).

There is another question mentioned above. According to your reply, my understanding is as follows: When merging gvcf with glnexus, regardless of what deepvatriant's --model_type parameter selects (WGS,PACBIO,HIFI, etc.), glnexus's --config can select DeepVariantWGS. If not, please correct.

Thank you again and look forward to your reply

**Comment by AndrewCarroll** [comment]
Hi @Tonitsk8264 

PacBio CLR and ONT R9.4 have higher base error rates. It is possible to call variants on this, but you will need to use [PEPPER-Margin-DeepVariant](https://github.com/kishwarshafin/pepper)  instead. Please see that GitHub link for details. The preset there to call variants with R9.4 data should be either `--ont_r9_guppy5_sup` or `--ont_r9_guppy4_hac` depending on how it is basecalled. The preset for CLR should be `--clr`

For GLnexus outputs, you can use DeepVariantWGS for merging general sequencing results.

**Comment by AndrewCarroll** [comment]
Hi @Tonitsk8264 

One correction to my answer above. Those ONT models should be valid, but I had misremembered CLR. PEPPER-DeepVariant doesn't have a CLR mode to take advantage of that preset. However, you should use PEPPER-DeepVariant for ONT R9.4. We don't have a suggestion for CLR.

**Comment by Tonitsk8264** [comment]
Thank you for clearing my doubts despite your extremely busy schedule, I hereby present to you my most sincere appreciation
