### ISSUE TITLE
[question] interpreting PL in gVCF reference bands

### ISSUE THREAD

**Issue by mlin** [google/deepvariant#714]
RE: https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-gvcf-support.md

That documents that the GQ value reported in a gVCF reference band is the lowest GQ out of all the positions covered by the reference band -- this is nice and intuitive along with MIN_DP. It would be nice to document how to think about the PL vector in a reference band as well. since it's a vector, it's not so obvious how one would combine information from all the covered positions.

In `variant_caller.make_gvcfs()`:

https://github.com/google/deepvariant/blob/ab068c4588a02e2167051bd9e74c0c9579462b51/deepvariant/variant_caller.py#L308-L314

I *think* this code says to fill in the PL just from the *first* position of the reference band; which seems slightly weird (unless please correct me if I misread!).

I don't think this is a significant problem, to be clear, since the quantities are in any case not very useful from reference bands, and (I often argue) essentially a waste of storage space. Main interest here is just documenting what in fact occurs!

**Comment by akolesnikov** [comment]
Hi @mlin,

In the block of code your referenced earlier `first_record` represents a first record of a grouped positions (sharing the same quantized_gq value) therefore PL is set  with the correct value. In the documentation it is stated  `To minimize output file size, adjacent records with equal (or similar, see discussion below) genotype qualities are merged into a single record.`
I hope it addresses your comment.

**Comment by mlin** [comment]
@akolesnikov Thanks, that's great! One further clarification would be helpful...in a reference band,

* `MIN_DP` = minimum read depth across covered positions
* `GQ` = lowest GQ across covered positions
* `PL` = ??? across covered positions (?)

IOW how is info combined/selected from all the positions covered by the reference band, if indeed it is, to generate one representative PL vector?

**Comment by AndrewCarroll** [comment]
Hi @mlin 

We'll work on some documentation covering how these are calculated, give us a few weeks to get a first pass on those docs.

**Comment by cmclean** [comment]
@mlin FWIW your interpretation is correct -- it's just taking the PLs from the first position in the combinable block of the reference band, not doing any aggregation across the combinable sites. So it is semantically different from MIN_DP, MED_DP, and GQ.

Arguably for consistency with GQ being from the minimum position, this should maybe take that position's PL vector as well.

**Comment by pichuan** [comment]
Hi all,
@akolesnikov has pushed a fix internally on Nov 3rd based on @cmclean 's suggestion in the previous comment. The change also includes a documentation change in deepvariant-gvcf-support.md.

For now I'll close this issue. The change should come out officially in the next release.

(@mlin if you'd like to see the change earlier, we can also push it to the `dev` branch. Let me know)
