### ISSUE TITLE
Issue on using region

### ISSUE THREAD

**Issue by BowenKwan** [google/deepvariant#72]
I have been trying to run the whole genome case study with  --regions in make_example, with the following command. I have copied all command in the genome case study page and added the regions to the make example as follow.
```
( time seq 0 $((N_SHARDS-1)) | \
  parallel --halt 2 --joblog "${LOG_DIR}/log" --res "${LOG_DIR}" \
    python "${BIN_DIR}"/make_examples.zip \
      --mode calling \
      --ref "${REF}" \
      --reads "${BAM}" \
      --examples "${EXAMPLES}" \
      --regions '"chr20:10,000,000-10,010,000"'\
      --gvcf "${GVCF_TFRECORDS}" \
      --task {}
) >"${LOG_DIR}/make_examples.log" 2>&1 
```
I have also tried 
`` --regions "chr20:10,000,000-10,010,000"\`` 
and 
`` --regions chr20:10,000,000-10,010,000\`` 
However, in all cases, it seems like the whole data set is used in make example instead of the specific region. I am not sure what the problem is.

**Comment by depristo** [comment]
This is a known bug, which we will prioritize fixing now, that occurs when the provided regions chromosome name isn't present in the BAM file. The solution is to provide `--regions "20:10,000,000-10,010,000"` since this BAM is aligned to b37. Can you try that an see if it works?

**Comment by BowenKwan** [comment]
Further to this question, I am trying to run 2 chromosome for the whole genome case study. 

The user guide said that we can do ```--regions " chr20 chr21" ```  to run both chromosome, however, I get the following error when I the make sample with ``` --regions "chr20 chr21" ```. I have also tried ```--regions "20 21"```, but none of these works. 

```
E0814 18:04:05.051175 140174423590656 errors.py:64] Command line parsing failure: make_examples does not accept positional arguments but some are present on the command line: "['/tmp/Bazel.runfiles_D92FlN/runfiles/com_google_deepvariant/deepvariant/make_examples.py', '21']".
parallel: This job failed:
python /HD_disk/real-case-study-chr/input/bin/make_examples.zip --mode calling --ref /HD_disk/real-case-study-chr/input/data/hs37d5.fa.gz --reads /HD_disk/real-case-study-chr/input/data/HG002_NIST_150bp_50x.bam --examples /HD_disk/real-case-study-chr/output_1_2_3/HG002.examples.tfrecord@8.gz --regions 20 21 --gvcf /HD_disk/real-case-study-chr/output_1_2_3/HG002.gvcf.tfrecord@8.gz --task 2
```

Would you please suggest how I should specify the region to get multiple chromosome running at the same time. For single chromosome, ``` --regions "20" ``` works fine.

**Comment by BowenKwan** [comment]
Thank you for the reply. I have included the " " in the code however it appears missing at runtime.It worked when I replace that with ``` --regions ' "20 21" ' ```.

However, a further question is that when should we include the chr in the region. Apparently ``` --regions ' "chr20:10,000,000-10,001,000 chr20:10,002,000-10,003,000" ' ``` does not work but ``` --regions ' "20:10,000,000-10,001,000 20:10,002,000-10,003,000" ' ``` is fine. 

One more problem is about the log file of the make sample. 

It appears to show variant candidate in each region and finally display the total number of variant, i.e.
``` I0815 12:48:59.877676 140644793067264 make_examples.py:782] Found 7 candidates in 20:10000000-10000999 [1.56s elapsed]
I0815 12:48:59.899951 140644793067264 make_examples.py:1053] Found 7 candidate variants ``` 

However, for region 20:10,002,000-10,003,000, I get
``` I0815 12:48:59.877676 140644793067264 make_examples.py:782] Found 9 candidates in 20:10002000-10002999 [1.56s elapsed]
I0815 12:48:59.899951 140644793067264 make_examples.py:1053] Found 7 candidate variants ``` 
which the final candidate variant is less than the candidate in the region.

When I run  with region 20:10,000,000-10,001,000 20:10,002,000-10,003,000, 
``` I0815 12:48:59.877676 140644793067264 make_examples.py:782] Found 9 candidates in 20:10002000-10002999 [1.56s elapsed]
I0815 12:48:59.899951 140644793067264 make_examples.py:1053] Found 7 candidate variants ``` 
which is the same as just running region 20:10,002,000-10,003,000 only.

But when I check the call variant log file, it indicated that 16 samples are run, which is correct (7 for first region and 9 for second region). 

I am not sure if I misunderstand the log file, or the make sample log does not really reflect the total number of variant. Should I only refer to sample number shown in Call Variant log file to get the total number of candidate variant?

**Comment by BowenKwan** [comment]
Also, when I try to run the hap.py to verify the result, I cannot specify the region with ``` -l "20:10000000-10001000 20:10002000-10003000" ``` or ``` -l  '"20:10000000-10001000 20:10002000-10003000"' ```.

Do you know how I should set the region for hap.py for multiple chromosome?

**Comment by depristo** [comment]
The exact name for the chromosome depends on your reference file. If the reference FASTA names its chromosomes chr1, chr2 you need to use "chr" in the prefix. If the reference FASTA calls them 1, 2, etc you need to use that name.

**Comment by BowenKwan** [comment]
Thank you for the reply. 
I have one more question about using regions.
When I try to run the hap.py to verify the result, I cannot specify the region with ```-l "20:10000000-10001000 20:10002000-10003000"``` or ``` -l '"20:10000000-10001000 20:10002000-10003000"'```.

Do you know how I should set the region for hap.py for multiple chromosome?

**Comment by akmohtashami** [comment]
Even if I only set the mode(which should fail by asking for other flags) the same error appears. Using 0.7.0: 

Command line parsing failure: make_examples does not accept positional arguments but some are present on the command line: "['/tmp/Bazel.runfiles_TAWAeF/runfiles/com_google_deepvariant/deepvariant/make_examples.py', '--mode', 'calling']".

**Comment by pichuan** [comment]
@akmohtashami your question seems to be more relevant to the earlier ones:
https://github.com/google/deepvariant/issues/72#issuecomment-412946034
and the relevant answer is : https://github.com/google/deepvariant/issues/72#issuecomment-412948943

When there's something related to positional arguments, it's often becomes something wasn't quoted correctly. What's your full command line?
