### ISSUE TITLE
question about deepTrio1.4

### ISSUE THREAD

**Issue by crazysummerW** [google/deepvariant#720]
hello, 
I tested PacBio data on version 1.4 of the deepTrio image. But I received an error message after more than 100 minutes.

parallel: This job failed:
/opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref hs37d5.fasta --reads_parent1 HG003.haplotagged.bam --reads_parent2 HG004.haplotagged.bam --reads HG002.haplotagged.bam --examples intermediate_results_dir/[make_examples.tfrecord@32.gz](mailto:make_examples.tfrecord@32.gz) --sample_name HG002 --sample_name_parent1 HG003 --sample_name_parent2 HG004 --add_hp_channel --alt_aligned_pileup diff_channels --gvcf intermediate_results_dir/[gvcf.tfrecord@32.gz](mailto:gvcf.tfrecord@32.gz) --parse_sam_aux_fields --pileup_image_height_child 60 --pileup_image_height_parent 40 --pileup_image_width 199 --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels 0.12 --task 0

real 113m56.944s
user 112m32.542s
sys 0m37.407s
I1020 05:16:02.013775 140329939375936 run_deeptrio.py:674] None
Traceback (most recent call last):
File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 688, in
app.run(main)
File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 312, in run
_run_main(main, args)
File "/usr/local/lib/python3.8/dist-packages/absl/app.py", line 258, in _run_main
sys.exit(main(argv))
File "/opt/deepvariant/bin/deeptrio/run_deeptrio.py", line 672, in main
subprocess.check_call(command, shell=True, executable='/bin/bash')
File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'time seq 0 31 | parallel -q --halt 2 --line-buffer /opt/deepvariant/bin/deeptrio/make_examples --mode calling --ref "hs37d5.fasta" --reads_parent1 "HG003.haplotagged.bam" --reads_parent2 "HG004.haplotagged.bam" --reads "HG002.haplotagged.bam" --examples "intermediate_results_dir/[make_examples.tfrecord@32.gz](mailto:make_examples.tfrecord@32.gz)" --sample_name "HG002" --sample_name_parent1 "HG003" --sample_name_parent2 "HG004" --add_hp_channel --alt_aligned_pileup "diff_channels" --gvcf "intermediate_results_dir/[gvcf.tfrecord@32.gz](mailto:gvcf.tfrecord@32.gz)" --parse_sam_aux_fields --pileup_image_height_child "60" --pileup_image_height_parent "40" --pileup_image_width "199" --norealign_reads --sort_by_haplotypes --vsc_min_fraction_indels "0.12" --task {}' returned non-zero exit status 247.
Fri Oct 20 05:16:03 UTC 2023 end

What went wrong?

**Comment by pichuan** [comment]
Hi @crazysummerW ,

Can you tell us how much RAM your memory has?

(btw, r1.6 was out yesterday. We have introduced the built-in read phasing to DeepTrio, so I'd encourage you to try that!)

**Comment by crazysummerW** [comment]
Hi @pichuan 
Thank you for your response. 

I have completed the testing of NGS-WES data and Pacbio-WGS data on deeptrio1.6, and performed single sample analysis using deepvariant1.6. I have some questions that I would like to confirm with you. 

1. If I want to test 3 Pacbio WGS datasets using deeptrio1.6, how much memory should I allocate at least? 

2. Regarding NGS-deeptrio1.6 analysis, I only saw the benchmark comparison results for WGS-chr20. Do you have any results (METRIC.Recall, METRIC.Precision, METRIC.F1_Score) to share for WES data? 

3. For Pacbio-deeptrio1.6 analysis, I tested the official HiFi data (HG002, HG003, HG004). The reference genome used for alignment was hs37d5.fa. The bam was hifi_reads_aligned.haplotagged.bam (pbmm2+whatshap). However, the benchmark comparison results were worse than the data you published. Does the choice of reference genome affect the precision of the results? 

4. Whether it is NGS-WES or Pacbio-WGS, the results from using deeptrio1.6 for analysis are slightly less precision than using deepvariant1.6. Is this normal? In theory, should the results from deeptrio1.6 be better than those from deepvariant1.6?

**Comment by pichuan** [comment]
> Hi @pichuan Thank you for your response.
> 
> I have completed the testing of NGS-WES data and Pacbio-WGS data on deeptrio1.6, and performed single sample analysis using deepvariant1.6. I have some questions that I would like to confirm with you.
> 
> 1. If I want to test 3 Pacbio WGS datasets using deeptrio1.6, how much memory should I allocate at least?

In our https://github.com/google/deepvariant/blob/r1.6/docs/metrics-deeptrio.md documentation, all experiments were done with n1-standard-64 GCP machines, which has 240 GB memory, and 64 vCPUs. I have not specifically tried machines with smaller memory. Can you tell me what kind of memory constraints you're considering?

> 2. Regarding NGS-deeptrio1.6 analysis, I only saw the benchmark comparison results for WGS-chr20. Do you have any results (Recall, Precision, F1_Score) to share for WES data?

Please see:
https://github.com/google/deepvariant/blob/r1.6/docs/metrics-deeptrio.md#whole-exome-sequencing-illumina

> 3. For Pacbio-deeptrio1.6 analysis, I tested the official WGS HiFi data (HG002, HG003, HG004). The reference genome used for alignment was hs37d5.fa. The bam was hifi_reads_aligned.haplotagged.bam (pbmm2+whatshap haplotag). The region is chr20. However, the benchmark comparison results were worse than the data you published. Does the choice of reference genome affect the precision of the results?

If you're using different reference genome, the numbers are not directly comparable because the truth sets are also different.

> 4. Whether it is NGS-WES or Pacbio-WGS, the results from using deeptrio1.6 for analysis are slightly less precision than using deepvariant1.6. Is this normal? In theory, should the results from deeptrio1.6 be better than those from deepvariant1.6?

I suppose you're comparing numbers like https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-pacbio-model-case-study.md#benchmark-output and https://github.com/google/deepvariant/blob/r1.6/docs/metrics-deeptrio.md#hg003-1.
The former has 77+69+25+23=194 total FNs+FPs, and the latter has 53+78+21+35=187. Overall there are fewer errors, even though it is true that not all the error types were better on DeepTrio. We hope to improve all our models in the future.

**Comment by crazysummerW** [comment]
hi, @pichuan 
Thanks for your reply.
I noticed in your documentation(https://github.com/google/deepvariant/blob/r1.6/docs/metrics-deeptrio.md) that the description of PacBio data analysis is as follows: 'In v1.6.0, we introduced read haplotagging in DeepTrio PacBio. You no longer need to run DeepVariant->WhatsHap->DeepTrio, and can just run DeepTrio once.' However, in another document (https://github.com/google/deepvariant/blob/r1.6/docs/deeptrio-pacbio-case-study.md), I saw that the input BAM file had phasing applied (input/HG002.pfda_challenge.grch38.phased.chr20.bam). So, for the input BAM file in DeepTrio 1.6, is it sufficient to use only the pbmm2 alignment? Will there be any other effects if a BAM file processed with pbmm2+WhatsHap is used?

**Comment by pichuan** [comment]
Hi @crazysummerW ,

DeepTrio will ignore the existing HP value from the BAM, and will use our internal read phasing.
Specifically, this block of logic deals with that:
https://github.com/google/deepvariant/blob/r1.6/deepvariant/make_examples_core.py#L2133-L2135

I agree that the way our case study is written is confusing. We should at least mentioned that the HP information from the BAM would be discarded, or use an unphased BAM as an example.

I will file an internal issue to track this, so we can update it in the future. Thanks for noticing this!
