### ISSUE TITLE
training an hybrid model

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#721]
Hi,
thank you for the tool and the very detailed documentation of it. I was wondering if there are details on how the hybrid model was trained. Is there any page that contains these details?
thank you in advance,

**Comment by pichuan** [comment]
Hi @gambalab 

The data for our hybrid model is described here: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-hybrid-case-study.md . It's merged from PacBio and Illumina data.

We have a page that describes the amount of training data we used for the models for each release, you can find them in https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-details-training-data.md

If you need some BAM files to train on, you can also see our [An Extensive Sequence Dataset of Gold-Standard Samples for Benchmarking and Development](https://doi.org/10.1101/2020.12.11.422022) manuscript. (Data can be found in `gs://brain-genomics-public/research/sequencing` ) For Hybrid, you'll need to make the hybrid BAM files yourself following the instructions in the first documentation.

Hope this helps.

**Comment by pichuan** [comment]
I'll close this issue now. But if you have more questions, feel free to follow up.
