### ISSUE TITLE
Emit PASSED Variants only

### ISSUE THREAD

**Issue by stefandiederich** [google/deepvariant#723]
Dear Sir or Madame, 
is it possible to emit only passed Variants to the output VCF file? This would save disk space and runtime for me.

Bests
Stefan

**Comment by pichuan** [comment]
Hi @stefandiederich ,
You can try the `--only_keep_pass` flag for postprocess_variants.

If you're using `run_deepvariant` to do things in one step, you can add:


```
  --postprocess_variants_extra_args="only_keep_pass=true"
```

For example, if you're running [Quick Start](https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md), you can run:

```bash
sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc.hg19.chr20.unittest.fasta \
  --reads=/input/NA12878_S1.chr20.10_10p1mb.bam \
  --regions "chr20:10,000,000-10,010,000" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=1 \
  --postprocess_variants_extra_args="only_keep_pass=true"
```

Hope this helps. I'll close this issue, but feel free to reopen if needed.

**Comment by stefandiederich** [comment]
Hi @pichuan 
I will test that option. But sounds exactly like what I'm looking for.
Thanks
Stefan
