### ISSUE TITLE
Results are different between v1.5 and v1.6

### ISSUE THREAD

**Issue by ZuyaoLiu** [google/deepvariant#726]
Dear Developers,

I compared the Snp calling results between V1.5 and V1.6 with a trio from a non-model species (a pair of parents and offspring).

I used percentages of sites with violations of Mendelian error as a proxy.

Results from V1.5 (WGS default model):  24%
Results from V1.6 (WGS default model):  40%.

Also, results from V1.6 with the SLIM model (WGS default) from V1.5 show 24% of Mendelian errors.

All other parameters and settings are the same except for the version.
It seems the newly trained model from V1.6 has a huge influence, and I'm not sure if this is a good sign (with significantly more Mendelian errors).

Could you please look into this?

Any help and discussion would be appreciated.

Thank you
Zuyao

**Comment by AndrewCarroll** [comment]
Hi @ZuyaoLiu 

The number of Mendelian violations does seem unusually high. Here, are you using DeepTrio or DeepVariant?

Would you be willing/able to share the non-model organism trio for us to replicate the results and take a look?

Thank you,
Andrew

**Comment by ZuyaoLiu** [comment]
Hi @AndrewCarroll ,

I used DeepVariant 1.6.0.
Here is the link to bam files.
https://1drv.ms/f/s!AhAQj0fn-tVynE0Z2qTLsfBVaNex?e=2WlQ8g

As a reference, the number of Mendelian violations from GATK 4.4.1 is ~25%. 

Best,

Zuyao

**Comment by kishwarshafin** [comment]
@ZuyaoLiu ,

Can you please give some insight on how you merged the VCFs for the analysis? Would be great if you have something where we can look how the post-processing was done to generate the stats.

**Comment by ZuyaoLiu** [comment]
> @ZuyaoLiu ,
> 
> Can you please give some insight on how you merged the VCFs for the analysis? Would be great if you have something where we can look how the post-processing was done to generate the stats.

Hi @kishwarshafin ,

Sure.
I used GLnexus and default DeepvariantWGS settings to merge GVCFs from Deepvariant.   And no further processing was performed.

Best,
Zuyao

**Comment by akolesnikov** [comment]
@ZuyaoLiu,

Could you also provide a matching reference file?

**Comment by akolesnikov** [comment]
@ZuyaoLiu,

We are still evaluating your data. Meanwhile I tried to run the trio with DeepTrio 1.6 (which is an extension of DeepVariant) and as expected the results are much better. I got 0.27% Mendelian violation rate for your data. Another difference is that I used `DeepVariant_unfiltered` filter in GLNexus to merge VCFs.

**Comment by ZuyaoLiu** [comment]
> @ZuyaoLiu,
> 
> We are still evaluating your data. Meanwhile I tried to run the trio with DeepTrio 1.6 (which is an extension of DeepVariant) and as expected the results are much better. I got 0.27% Mendelian violation rate for your data. Another difference is that I used `DeepVariant_unfiltered` filter in GLNexus to merge VCFs.

@akolesnikov ,

Good to know.

I used DV 1.5 to train my data and the Mendelian violation rate is 0.4%.

**Comment by pichuan** [comment]
Hi @ZuyaoLiu ,
To confirm what you said -- do you mean that you train your own model (on your own data) and was able to get a much lower Mendelian violation rate?  If so, that's great!!

Given that this is a non-human sample (not what we trained on), it seems like the right way to proceed is either to use our DeepTrio model, or like you said, to use your own customized model. So far both approaches seem like they would produce quite decent Mendelian violation rate.

In the future, our team is interested in thinking more about making our model more generally robust to all non-human species as well. So thank you for your feedback. Hopefully the two options (either DeepTrio or your own model) will work for you for now.

I'll close this issue now, but please feel free to share more thoughts.
