### ISSUE TITLE
questions about retraining DeepVariant

### ISSUE THREAD

**Issue by sophienguyen01** [google/deepvariant#728]
Hi,

I‘ve been working on  training Deepvaraint using mulitiple BAM files for samples HG001 to HG007, except HG003 for evaluation, with different coverages. I’ve experimented with different parameters for the **make_examples** step, either using default parameters or adding **min_base_quality=5, vsc_min_Fraction_snps 0.02, vsc_min_count_snps 2**. However, I am still not able to get the expected low VAF variants for our evaluation sample. We use Horizon sample and here is the truthset of it https://horizondiscovery.com/en/reference-standards/products/truq-1-5-tier-reference-standard
 
By setting the parameters **vsc_min_Fraction_snps 0.02** and **min_base_quality=5**, I am able to identify 9 variants out of 14 variants. However, the majority of these variants are considered as REF variants. In the attached screenshot, you can observer the result generated by the retrained model. There is only one change in variant **BRAF** that the **FILTER** value goes from **RefCall** to **PASS** and the rest remains consistent with those produced by the default model.
 
I am seeking for strategies to increase number of candidate variants generated, with the goal of capturing missing variants. Your insights or suggestions would be greatly appreciated.

![image](https://github.com/google/deepvariant/assets/135994439/f537faae-220c-476b-ab0b-d5dec2d45597)

**Comment by danielecook** [comment]
@sophienguyen01 it looks like you are trying to call somatic mutations here. If this is the case, please have a look at https://github.com/google/deepsomatic. DeepSomatic is still experimental, and we don't currently support retraining. However, it is designed to call somatic variants. 

We would be very interested in the results you observe with this dataset if you are able to provide feedback.

**Comment by sophienguyen01** [comment]
HI @danielecook , I took a look at DeepSomatic's command and it requires 2 BAM files: one from normal sample file and one from tumor sample file. I don't think I can run this program because I only have one BAM file for this type of sample

**Comment by danielecook** [comment]
@sophienguyen01 thanks for the update. For now, I would recommend an alternative tumor-only caller. We may explore a tumor-only approach in the future. I will close this issue now.
