### ISSUE TITLE
ONT and PacBio hifi hybrid model

### ISSUE THREAD

**Issue by tbenavi1** [google/deepvariant#729]
Hello,

I was wondering if there are any plans to add a hybrid model which uses ONT and PacBio hifi reads. Thanks.

**Comment by danielecook** [comment]
@tbenavi1 I do not believe we have any plans currently to develop a hybrid ONT/PacBio model. However, if there is a lot of interest in such a model we could consider training such a model in the future.

**Comment by tbenavi1** [comment]
Thanks for your response. I have a sample with ultra long ONT data and PacBio hifi data. I am trying to figure out the best way to get a final phased vcf and phased bam from the deepvariant/margin pipeline. I can get a phased bam and vcf for the ONT data and a phased bam and vcf for the hifi data, but then there is no easy way to combine these into a single phased vcf and bam file. I would be very grateful if you were to consider a hybrid model in the future. Thank you.
