### ISSUE TITLE
Runtime for a WES sample

### ISSUE THREAD

**Issue by mallikag9** [google/deepvariant#735]
I've been trying to replicate the runtime of a WES sample using the same BAMs as the ones specified in https://raw.githubusercontent.com/google/deepvariant/r1.6/scripts/inference_deepvariant.sh 

  - Operating system: google cloud vertex AI jupyer notebook 
  n1-standard-64 - 64v CPUs - 240GB RAM
  - DeepVariant version: 1.5.0
  - Installation method (Docker, built from source, etc.): docker deepvariant 
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
BAMs: https://storage.googleapis.com/deepvariant/exome-case-study-testdata/HG003.novaseq.wes_idt.100x.dedup.bam

  - Command:
  export BIN_VERSION="1.5.0"
export INPUT_DIR="/home/jupyter/input"
export REF="GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
export BAM="HG003.novaseq.wes_idt.100x.dedup.bam"
export OUTPUT_DIR="/home/jupyter/output"
export OUTPUT_VCF="HG003.deepvariant.vcf.gz"
export OUTPUT_GVCF="HG003.deepvariant.g.vcf.gz"

docker run -v "${INPUT_DIR}":"/input" -v "${OUTPUT_DIR}":"/output" google/deepvariant:"${BIN_VERSION}" /opt/deepvariant/bin/run_deepvariant --model_type=WES --ref="/input/${REF}" --reads="/input/${BAM}" --output_vcf="/output/${OUTPUT_VCF}" --output_gvcf="/output/${OUTPUT_GVCF}" --num_shards=64

 its taking 53 mins to finish running when it should take 8mins according to https://github.com/google/deepvariant/blob/r1.6/docs/metrics.md
 
 I've also tried to run a WES sample of 23GB with the same cloud configuration, but it takes close to 2hrs to complete. 
 Is there a reason for the differences in runtime? 
 
 Is there another way to decrease runtime and match the runtimes specified https://github.com/google/deepvariant/blob/r1.6/docs/metrics.md

**Comment by AndrewCarroll** [comment]
Hi @mallikag9 

I don't see a BED file for the exome regions in your command. For exome, we typically restrict to the capture regions of the exome (sometimes with a 100bp pad region). 

You can download the capture regions with this command:

```
HTTPDIR=https://storage.googleapis.com/deepvariant/exome-case-study-testdata

curl ${HTTPDIR}/idt_capture_novogene.grch38.bed > input/idt_capture_novogene.grch38.bed
```

and add `--regions /input/idt_capture_novogene.grch38.bed` to the command.

**Comment by kishwarshafin** [comment]
@mallikag9 ,

As @AndrewCarroll , if you don't specify the bed file then the DV runs on the entire genome which is the reason you are seeing the runtime being so high. If you see different behavior after applying the parameter, please reopen the issue with the command you used.
