### ISSUE TITLE
Conda installation fails

### ISSUE THREAD

**Issue by tgelafr-btx** [google/deepvariant#736]
**Describe the issue:**
Attempting to install deepvariant using conda and python 3 fails due to missing `tensorflow` and `tensorflow-estimator` dependencies.

**Setup**
  - Operating system: Amazon Linux 2023
  - DeepVariant version: N/A, but we can narrow the focus down to 1.5, which is the latest available on conda
  - Installation method (Docker, built from source, etc.): Conda (mamba)

**Steps to reproduce:**
  - Command: `mamba install deepvariant -c bioconda`
  - Error trace: 
```
Pinned packages:
  - python 3.10.*


Could not solve for environment specs
The following packages are incompatible
└─ deepvariant   is installable with the potential options
   ├─ deepvariant [0.10.0|0.7.2|0.8.0|0.9.0] would require
   │  └─ tensorflow 1.12.* , which does not exist (perhaps a missing channel);
   ├─ deepvariant [0.10.0|1.0.0] would require
   │  └─ tensorflow 2.0.* , which does not exist (perhaps a missing channel);
   ├─ deepvariant [0.4.1|0.6.0|0.6.1|0.7.0] would require
   │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
   ├─ deepvariant [0.7.1|0.7.2] would require
   │  └─ tensorflow 1.11.* , which does not exist (perhaps a missing channel);
   └─ deepvariant [1.0.0|1.1.0|...|1.5.0] would require
      └─ tensorflow-estimator 2.0.* , which does not exist (perhaps a missing channel).
```

**Does the quick start test work on your system?**
N/A

**Any additional context:**
My goal was to install the latest version available (1.5.0). Looking at the `tensorflow-estimator` releases on conda-forge, version 2.0 is skipped entirely, which explains the error. https://anaconda.org/conda-forge/tensorflow-estimator/files?page=8

**Comment by pichuan** [comment]
Hi @tgelafr-btx ,
I'm not familiar with the conda setup, but I can give it a try and report back to see if I'm able to get it to work.

**Comment by pichuan** [comment]
Hi @tgelafr-btx , thanks for waiting. It took me a while to get back to this.

Before I share my work log, one observation from your error earlier:
It seems like you're using Python 3.10. Note that DeepVariant 1.5.0 is bulit with Python 3.8. So, can you try with Python 3.8?

---

Here is what I tried.

On a GCE instance, I ran:

```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -u -p $HOME/miniconda
eval "$(${HOME}/miniconda/bin/conda shell.bash hook)"
```

Then, I ran:

```bash
conda config --add channels defaults && \
conda config --add channels bioconda && \
conda config --add channels conda-forge
conda create -y -n dv-env deepvariant
conda activate dv-env
```

Which seems to work (without error).

I don't actually know how to use conda (or deepvariant in conda). But I did see the files here: 

```
(dv-env) pichuan@pichuan-cpu:~$ ls /home/pichuan/miniconda/envs/dv-env/share/deepvariant-1.5.0-0/binaries/DeepVariant/1.5.0/DeepVariant-1.5.0/
call_variants.zip        licenses.zip               model_train.zip                runtime_by_region_vis.zip
call_variants_keras.zip  make_examples.zip          multisample_make_examples.zip  settings.sh
deeptrio                 make_examples_somatic.zip  postprocess_variants.zip       show_examples.zip
freeze_graph.zip         model_eval.zip             run-prereq.sh                  vcf_stats_report.zip
```

These are probably the files that were packaged with the last release: https://github.com/google/deepvariant/releases/tag/v1.5.0

@tgelafr-btx Question for you: Have you consider using Docker or Singularity, which are better supported by our team? Like the example in https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md or https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-pacbio-model-case-study.md .

Anyway, hopefully my test with conda install was somewhat informative. If you figure out how to install+use it, please update here. I don't think I would be able to provide further support on conda here though.

**Comment by pichuan** [comment]
Hi @tgelafr-btx ,
If you have more follow-up after my last comment, please feel free to comment or reopen. I'll close this issue for now.
