### ISSUE TITLE
There is something wrong while I building DeepVariant from source, I run the build-prereq.sh.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#737]
My environment  is Ubuntu20.04, python3.8. I look up for it, and find this problem happened at installing clif library, but the former sentences are successful, the protobuf3.13.0 have installed, I wonder how it happen and what can i do?

++ which python3
+ PYTHON=/usr/local/bin/python3
+ echo -n 'Using Python interpreter: /usr/local/bin/python3'
Using Python interpreter: /usr/local/bin/python3+ [[ '' -eq 1 ]]
+ mkdir -p /root/clif/build
+ cd /root/clif/build
+ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'protobuf'
--   No package 'protobuf' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  clif/cmake/modules/CLIFUtils.cmake:31 (pkg_check_modules)
  clif/CMakeLists.txt:22 (include)

**Comment by pioneer-pi** [comment]
> Hi @pioneer-pi ,
> 
> Can you please put some more details? Please follow the suggestions in this doc: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md, which suggests you to run `sudo su` before running `./build-prereq.sh`. One thing you can do is run:
> 
> ```shell
> ./build-prereq.sh 2>&1 | tee /tmp/dv_build.log
> ```
> 
> Then upload the `dv_build.log` here so a detailed log is available.

I pull the docker image of deepvariant:1.5.0, and then I start a container through `docker run -it deepvariant /bin/bash`. In this environment(I am root), I git clone the source code and try to build it from source according to the suggestions. The problem happened while I running the ./build-prereq.sh. The more detail information:

```
+ DV_PLATFORM=ubuntu-20.04
+ ln -sf /usr/bin/python3.8 /usr/local/bin/python3
+ cd
+ rm -rf clif
+ git clone https://github.com/google/clif.git
ProxyChains-3.1 (http://proxychains.sf.net)
Cloning into 'clif'...
+ cd clif
+ [[ ! -z 9ec44bde4f7f40de342a1286f84f5b608633a2d7 ]]
+ git checkout 9ec44bde4f7f40de342a1286f84f5b608633a2d7
Note: switching to '9ec44bde4f7f40de342a1286f84f5b608633a2d7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 9ec44bd Replace C++ `#import <...>` with `#include <...>`
+ git init
Reinitialized existing Git repository in /root/clif/.git/
+ ./INSTALL.sh
+++ dirname ./INSTALL.sh
++ cd .
++ pwd
+ CLIFSRC_DIR=/root/clif
+ BUILD_DIR=/root/clif/build
+ declare -a CMAKE_G_FLAG
+ declare -a MAKE_PARALLELISM
+ which ninja
+ CMAKE_G_FLAGS=()
+ MAKE_OR_NINJA=make
+ MAKE_PARALLELISM=(-j 2)
+ [[ -r /proc/cpuinfo ]]
++ cat /proc/cpuinfo
++ grep -c '^processor'
+ N_CPUS=32
+ [[ 32 -gt 0 ]]
+ MAKE_PARALLELISM=(-j $N_CPUS)
+ MAKE_INSTALL_PARALLELISM=(${MAKE_PARALLELISM[@]})
+ echo 'Using make for the clif backend build.'
Using make for the clif backend build.
+ [[ '' =~ ^-?-h ]]
+ [[ -n '' ]]
++ which python3
+ PYTHON=/usr/local/bin/python3
+ echo -n 'Using Python interpreter: /usr/local/bin/python3'
Using Python interpreter: /usr/local/bin/python3+ [[ '' -eq 1 ]]
+ mkdir -p /root/clif/build
+ cd /root/clif/build
+ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 /root/clif
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'protobuf'
--   No package 'protobuf' found
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643 (_pkg_check_modules_internal)
  clif/cmake/modules/CLIFUtils.cmake:31 (pkg_check_modules)
  clif/CMakeLists.txt:22 (include)
```

**Comment by kishwarshafin** [comment]
@pioneer-pi ,

The source installation instructions are for installing on your local machine. If you can run docker, you do not need to install DeepVariant. If you are starting a container with the provided docker then DeepVariant is already installed within it. Please see the quickstart: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md to see how to run DeepVariant through docker.

If you are starting a container then DeepVariant binaries should be in:
```bash
 /opt/deepvariant/bin/
```

**Comment by pioneer-pi** [comment]
> @pioneer-pi ,
> 
> The source installation instructions are for installing on your local machine. If you can run docker, you do not need to install DeepVariant. If you are starting a container with the provided docker then DeepVariant is already installed within it. Please see the quickstart: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md to see how to run DeepVariant through docker.
> 
> If you are starting a container then DeepVariant binaries should be in:
> 
> ```shell
>  /opt/deepvariant/bin/
> ```

I know it, but in /opt/deepvariant/bin/, The source code is different from the code in github. I want to change the source of [pileup](https://github.com/google/deepvariant/blob/r1.6/deepvariant/pileup_image_native.cc), but in container, this code have been a .so file. So I need to build it. The reason why I want to build it in docker container is that I have no root in my local machine.

**Comment by kishwarshafin** [comment]
@pioneer-pi ,

I don't believe you can develop within the Docker environment. At least, I have not tried that successfully. You need to have a local setup where you can `modify -> build -> test` your code. I am unsure how can achieve all that within the docker container.

The reason the github code is different because github is on `1.6.0` whereas you are using `1.5.0` for the docker.

**Comment by pioneer-pi** [comment]
@kishwarshafin Thank you for your replying, I will try on my local environment.
