### ISSUE TITLE
Running DeepTrio on top of DeepVariant results?

### ISSUE THREAD

**Issue by alanlamsiu** [google/deepvariant#738]
If DeepVariant has been used for variant calling per individual, is there a way to use DeepTrio on top of the vcf files generated by DeepVariant?

**Comment by kishwarshafin** [comment]
@alanlamsiu ,

You would need to run DeepTrio independently on the trio. Please see the [DeepTrio quickstart](https://github.com/google/deepvariant/blob/r1.6/docs/deeptrio-quick-start.md) for reference on how to run DeepTrio.

**Comment by alanlamsiu** [comment]
Thanks @kishwarshafin. I will close the issue.
