### ISSUE TITLE
Timing of the DeepVariant program

### ISSUE THREAD

**Issue by BowenKwan** [google/deepvariant#74]
I am working with the exome case study. In the documentation, it shows that make_examples uses 65 minutes while call_variants uses only 6 min, both run on a 64-core machine. 

I have tried that with my 8 core machine. The make_examples take around 8 hours, which scale according to the ratio of the cores. However, call_variants also takes 8 hours to run, which is almost 10 times slower than the expected 48min (scaling the 6min by a factor of 8). 

I have copied the entire script in the exome case study page and run, only changing ```N_SHARDS="64" ``` to ``` N_SHARDS="8" ```. I wonder what causes the call_variants function to run much slower than expected.

Thank you in advance for your help.

**Comment by BowenKwan** [comment]
Thank you for the reply. I am running it on a linux server instead of using GCE. 

The "sec per 100" is "2.68 sec per 100". My machine has 16Gb RAM and DeepVariant added 1-2 Gb RAM usage and total RAM usage peaks at 5Gb with 8 cores fully utilized. The data file, make_examples and call_variants result are all written to local storage instead of network storage. 

I was trying to get a timing profile and check if the program runs as expected. One thing I am curious is that the time taken to run make_examples matches the report time closely, however, the call_variants is much slower. I wonder if there is any problem in setting or configuration as the reported time of call_variants is much faster.

**Comment by depristo** [comment]
Hi Bowen, just an FYI that I'm looking into this a bit. I'm going to try running call_variants on a 8 core machine on GCE to see how the timing looks. Can you send us the details of the CPU you are trying to run on? For example:

$ head -n 26 /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 63
model name	: Intel(R) Xeon(R) CPU E5-2690 v3 @ 2.60GHz
stepping	: 2
microcode	: 0x3c
cpu MHz		: 1200.024
cache size	: 30720 KB
physical id	: 0
siblings	: 24
core id		: 0
cpu cores	: 12
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 15
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb invpcid_single kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm xsaveopt cqm_llc cqm_occup_llc ibpb ibrs stibp dtherm ida arat pln pts
bugs		: cpu_meltdown spectre_v1 spectre_v2
bogomips	: 5187.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

Also, just to confirm - you are using DV 0.6.1 with our gcp optimized TF wheel (this is downloaded by run-prereqs.sh)?

**Comment by BowenKwan** [comment]
Thank you for the reply. 

Following are the cpuinfo of my machine

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
stepping        : 3
microcode       : 0xc2
cpu MHz         : 1013.093
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single intel_pt rsb_ctxsw spec_ctrl retpoline kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 6816.62
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

I have used the preliminaries set in the exome case study, namely

```
BASE="/HD_disk/exome-case-study"
BUCKET="gs://deepvariant"
BIN_VERSION="0.6.1"
MODEL_VERSION="0.6.0"
MODEL_CL="191676894"

# Note that we don't specify the CL number for the binary, only the bin version.
BIN_BUCKET="${BUCKET}/binaries/DeepVariant/${BIN_VERSION}/DeepVariant-${BIN_VERSION}+cl-*"
MODEL_BUCKET="${BUCKET}/models/DeepVariant/${MODEL_VERSION}/DeepVariant-inception_v3-${MODEL_VERSION}+cl-${MODEL_CL}.data-wes_standard"
DATA_BUCKET="${BUCKET}/exome-case-study-testdata"
```

I have also run the run_prereq.sh, however, I am not entirely sure if I have the gcp optimized TF wheel. Can you show me which one is the gcp optimized TF wheel and how can I install that if I have not?

**Comment by depristo** [comment]
Hi @BowenKwan 

I dug into this a bit and I think it is working as expected. Here are some take aways:

There are 57238 total examples in the exome.

* On a batch_size 32 on 64 cores runs this runs at 0.67 sec per 100 [from pichuan] with total runtime 6m 21s. Expected runtime is 57238 / 100 * 0.67 seconds = 6m so this is all matching.

* With a batch_size 32 on a GCE 8 cores instance DV 0.6 runs at 2.53 sec per 100, so expected runtime is 57238 / 100 * 2.53 seconds = 24 min

* The expected run rate (assuming perfect scaling from 64 => 8) is 0.67 * 8 = 5.36 sec per 100. This is 2x larger than the observed rate [in the positive direction] because 64 cores isn't as well utilized as 8 cores. So we are in fact running more efficiently on the 8 cores, again as expected.

* I ran the 8 core call_variants end2end on the GCE instance and in fact it takes only 24 m.

* You are reporting a run rate of 2.68 sec per 100 in one comment, which is very close to my observed GCE rate.

* My guess: did you leave out the --regions ${CAPTURE_BED} argument? This changes how many examples are generated and could lead to a 8 hr runtime of call_variants even at 2.53 secs per 100. Leaving out that flag will result in candidates being generated genome-wide, so you'll have many more candidates and a concomitantly longer runtime.

**Comment by BowenKwan** [comment]
Thank you for the reply. You are right, the regions argument was left out. Sorry for the trouble.

On the other hand, is there a way we check how many candidates are generated?

**Comment by depristo** [comment]
Glad to help. Unfortunately there's no easy way to do it via the command line but you can use python and TF such as in https://lonelycoding.com/obtaining-total-number-of-records-from-tfrecords-file-in-tensorflow/
