### ISSUE TITLE
Building DeepVariant from sources on RedHat

### ISSUE THREAD

**Issue by spz1st** [google/deepvariant#740]
Sorry it's not an issue of the package per se, but is it possible for you to supply the shell scripts below for building the package on RedHat systems?  I tried to install the package with conda on a RedHat system, but it didn't work.  When I tried to build the package from the sources, I ran into some issues.  Many system libraries and utilities, such as zlib1g-dev, python3-distutils, are not available or possible in different names.  Without or not familiar with a Ubuntu system, it's hard to figure out what would be the equivalent.  It'd be enough to have the scripts working for one version of RedHat and it'd be much easier for people familiar with RedHat to modify the scripts for a different version of RedHat.  Thanks.

    build_and_test.sh
    build-prereq.sh
    build_release_binaries.sh
    run-prereq.sh
    settings.sh

**Comment by pichuan** [comment]
Hi @spz1st ,
Building on different systems can be tricky. Have you considered using solutions like Singularity (or directly using Docker if you have permission)?
An example of running with Singularity can be found in https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-pacbio-model-case-study.md.

**Comment by spz1st** [comment]
Many thanks.  I haven't tried Singularity, but I'll certainly give it a try.

**Comment by spz1st** [comment]
Hi @pichuan, I have tried singularity as suggested at the link and it worked fine.  But I got the message below.  The deepvariant version is 1.6.0 as used in the case at the link. Are there other versions available? How can I list the available versions?  Thank you very much for all your help.

    2023-11-24 20:50:47.554286: I tensorflow/core/platform/cpu_feature_guard.cc:193]
    This TensorFlow binary is optimized with oneAPI Deep Neural Network Library
    (oneDNN) to use the following CPU instructions in performance-critical operations:
    AVX2 AVX512F AVX512_VNNI FMA
    To enable them in other operations, rebuild TensorFlow with the appropriate comp
    iler flags.

> Hi @spz1st , Building on different systems can be tricky. Have you considered using solutions like Singularity (or directly using Docker if you have permission)? An example of running with Singularity can be found in https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-pacbio-model-case-study.md.

**Comment by pichuan** [comment]
Hi @spz1st ,
Was that just a warning and you're still able to run DeepVariant, or does the program actually crashed after that?
I think the message just means that your machine might not have certain optimized ops, but I think you should still be able to run it.

If the code did crash, please let me know if there are more error messages that you're seeing.

**Comment by spz1st** [comment]
HI @pichuan, the program worked fine and finished with results.  I was just wondering if there were other versions available because the docker image was specified with a version number (1.6.0).  Thanks again for all your help.

**Comment by pichuan** [comment]
Hi @spz1st ,
Thanks for checking. If you want to run 1.6.0, then the one with `1.6.0` is the version to use.
There are previous versions (like 1.5.0 or earlier), which corresponds to previous releases https://github.com/google/deepvariant/releases

I'm glad to hear that you're able to run the Docker image. I'll close this bug. Feel free to let us know if you have other questions.
