### ISSUE TITLE
CRAM v3.1 not supported in DV v1.6

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#741]
Hi,

There appears to be a regression in v1.6 compared to v1.5 for handling cram input. The reference is set in the `make_examples` call, but does not seem to propagate to nucleus. The [code](https://github.com/google/deepvariant/blob/764bad20cbfa178d757ae81bbe05860640f2d5d4/third_party/nucleus/io/clif_postproc.py#L141) that raises the error "ValueError: DATA_LOSS: Failed to parse SAM record" is 4 years old, so must be some intermediate flag not working.

The log in v1.6 looks like
```
make_examples_core.py:301] Task 1/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
genomics_reader.py:222] Reading sample.cram with NativeSamReader

```

while in v1.5 it has 2 extra lines for setting the CRAM reference.
```
make_examples_core.py:257] Task 1/4: Starting from v0.9.0, --use_ref_for_cram is default to true. If you are using CRAM input, note that we will decode CRAM using the reference you passed in with --ref
third_party/nucleus/io/sam_reader.cc:736] Setting HTS_OPT_BLOCK_SIZE to 134217728
third_party/nucleus/io/sam_reader.cc:764] Setting CRAM reference path to 'reference.fa'
genomics_reader.py:222] Reading sample.cram with NativeSamReader
```

the `nucleus/io/sam_reader.cc` file had changes in b8d6d11, but it still looks correct so not sure what is happening. For completeness, I tried converting the cram to bam and rerun with v1.6, and that did worked, so this is somehow localised to cram support.

Best,
Alex

**Comment by kishwarshafin** [comment]
Hi @ASLeonard ,

Is it possible to provide the input data so we can reproduce the error on our end? On our side, we didn’t update nucleus between versions so unsure why you are seeing this behavior. Would be very helpful if you can provide a small data to reproduce as all the tests involving cram files still passes on v1.6z

**Comment by lucasbrambrink** [comment]
Hi Alex,

Thank you for your patience. We were able to reproduce your issue and have determined that it is likely caused by `htslib`. In particular, DV uses `htslib` version `1.13` which only experimentally supports CRAM v3.1. Updating the `htslib` version to the latest (`1.18`) fixed this issue for me.

You can update `htslib` yourself for the time being by updating [this section](https://github.com/google/deepvariant/blob/r1.6/WORKSPACE#L24-L32).
```
http_archive(
    name = "htslib",
    build_file = "//:third_party/htslib.BUILD",
    sha256 = "f1ab53a593a2320a1bfadf4ef915dae784006c5b5c922c8a8174d7530a9af18f",
    strip_prefix = "htslib-1.18",
    urls = [
        "https://github.com/samtools/htslib/releases/download/1.18/htslib-1.18.tar.bz2",
    ],
)
```

Please note that I have not yet tried `htslib 1.18` in other workflows, and those might be affected by the change: there is a  chance this change has negative consequences in other circumstances. That said, if you are currently blocked in your workflow you can give that a try! Meanwhile, we are working on updating `htslib` on our end to be included it in the next release.

**Comment by ASLeonard** [comment]
Thanks Lucas,

I'm not exactly sure where the WORKSPACE build you shared would get used, but it currently uses `htslib` version `1.13`, which is different to the conda provided htslib version accessible within the container, which gives this information

```
Apptainer> samtools --version
samtools 1.10
Using htslib 1.18
Copyright (C) 2019 Genome Research Ltd.
```

Maybe there is some strange interaction between out-of-sync versions? Regardless, I already converted cram->bam to finish variant calling, so feel free to close the issue.

**Comment by lucasbrambrink** [comment]
Alex,
Thank you again for pointing out this issue with Cram v3.1. I'm happy to report that our next DV release will include htslib 1.18, which seems to handle these files without issue.

I'll mark this issue as closed!

**Comment by gevro** [comment]
Was this issue fixed? I'm having the same error:
```
[E::cram_decode_slice] MD5 checksum reference mismatch at #1:248741259-248759777
[E::cram_decode_slice] CRAM: 857e35c22e237f102003142abf430800
[E::cram_decode_slice] Ref : 550702c7390d3ead48df01da66f85854
[E::cram_next_slice] Failure to decode slice
Traceback (most recent call last):
  File "/state/partition1/job-44859747/Bazel.runfiles_warfxbvu/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 1817, in region_reads_norealign
    reads = reservoir_sample_reads(
  File "/state/partition1/job-44859747/Bazel.runfiles_warfxbvu/runfiles/com_google_deepvariant/deepvariant/make_examples_core.py", line 976, in reservoir_sample_reads
    return utils.reservoir_sample(iterable_of_reads, k, random)
  File "/state/partition1/job-44859747/Bazel.runfiles_warfxbvu/runfiles/com_google_deepvariant/third_party/nucleus/util/utils.py", line 117, in reservoir_sample
    for i, item in enumerate(iterable):
  File "/state/partition1/job-44859747/Bazel.runfiles_warfxbvu/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 95, in __next__
    record, not_done = self._raw_next()
  File "/state/partition1/job-44859747/Bazel.runfiles_warfxbvu/runfiles/com_google_deepvariant/third_party/nucleus/io/clif_postproc.py", line 154, in _raw_next
    not_done = self._cc_iterable.PythonNext(record)
ValueError: DATA_LOSS: Failed to parse SAM record
```
