### ISSUE TITLE
Error on testing deepvariant for WES

### ISSUE THREAD

**Issue by YogitaVerma123** [google/deepvariant#743]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md**:

**Describe the issue:**
(A clear and concise description of what the issue is.)

**Setup**
  - Operating system:
  - DeepVariant version:
  - Installation method (Docker, built from source, etc.):
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by pichuan** [comment]
Hi @YogitaVerma123 ,
Can you tell me where you got your customized model? It seems like your model only has 6 channels.
Our default WES channels have 7 channels. The 7th channel is insert_size.

**Comment by YogitaVerma123** [comment]
Hi @pichuan ,
Im running this for RNA seq study 
In the documentation itself the model is there, I have just downloaded those files

**Comment by pichuan** [comment]
Hi @YogitaVerma123 , please feel free to reach out if you have more questions. 
Hopefully using the matching version (1.4.0) and and adding the flag will resolve your issue!
