### ISSUE TITLE
I have built Deepvariant:1.6.0 successfully in my Ubuntu20.04. I want to know something about its usage.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#747]
1. How can i use deepvariant if I have built it from source?(By bazel-bin/deepvariant/*runfiles?)
2. If i want to change the source of deepvariant/pileup_image_native.cc, how can I test it after changing the source.(It means how can i rerun deepvariant if i change the source code, do i need to recompile and how?)
Thank you for your help and patience!

**Comment by pioneer-pi** [comment]
@pichuan Thank you very much. I wonder what the difference between bazel-in and bazel-out/k8-opt/bin? I found they are both runnable files.

**Comment by pichuan** [comment]
You should be able to use either of them in this setup after you build.
The zip files were built here https://github.com/google/deepvariant/blob/r1.6/build_release_binaries.sh
When you built it on the machine, I think both versions should run fine (and the behaviors are the same)

**Comment by pichuan** [comment]
Hi @pioneer-pi , https://github.com/google/deepvariant/issues/756#issuecomment-1865388872 can also relevant.
I'll close this issue now.
