### ISSUE TITLE
Using PAR region flag seems to log NativeBedReader endlessly

### ISSUE THREAD

**Issue by ASLeonard** [google/deepvariant#748]
Hi,

This is running v1.6 via singularity with a command like
```
/opt/deepvariant/bin/postprocess_variants         --ref ref.fa         --infile call_variants_output@1.tfrecord.gz         --outfile all.vcf.gz         --gvcf_outfile all.g.vcf.gz         --nonvariant_site_tfrecord_path gvcf.tfrecord@24.gz         --novcf_stats_report         --haploid_contigs "X,Y" --par_regions_bed "PAR.bed"         --cpus 2
```
where PAR.bed is
```
X       133300518       139009144
Y       1       6822380
```
Running this without the haploid contigs and bed args works fine (although seems to use a **lot** more memory compared to v1.5), but when I try with these flags, the log file just explodes with 
```
2023-12-08 16:13:45.044559: I deepvariant/postprocess_variants.cc:109] Total #entries in single_site_calls = 11203892
I1208 16:16:08.029405 47184308283200 postprocess_variants.py:1313] CVO sorting took 3.885532522201538 minutes
I1208 16:16:08.030001 47184308283200 postprocess_variants.py:1316] Transforming call_variants_output to variants.
I1208 16:16:08.030090 47184308283200 postprocess_variants.py:1318] Using 4 CPUs for parallelization of variant transformation.
I1208 16:16:08.959253 47184308283200 postprocess_variants.py:1211] Using sample name from call_variants output. Sample name: sample
I1208 16:20:43.170422 47184308283200 genomics_reader.py:222] Reading PAR.bed with NativeBedReader
I1208 16:20:43.188045 47184308283200 genomics_reader.py:222] Reading PAR.bed with NativeBedReader
I1208 16:20:43.189731 47184308283200 genomics_reader.py:222] Reading PAR.bed with NativeBedReader
I1208 16:20:43.205978 47184308283200 genomics_reader.py:222] Reading PAR.bed with NativeBedReader
... 
```
Within a couple of minutes it had written that "Reading PAR.bed with NativeBedReader" nearly 2 million times and the log file was already 200 Mb after a couple of minutes. I tried using `--logging_level FATAL` and `--logtostderr --stderrthreshold fatal`, but I couldn't find a way to turn off that logging.

**Comment by pichuan** [comment]
Hi @ASLeonard ,
@kishwarshafin will take a closer look later.

I have one question : if you try running postprocess_variants with an extra `--cpus 0` flag, what happens?

**Comment by ASLeonard** [comment]
Same issue, with `--cpus 0` (or 1) I still get endless printing of reading the bed. It appears to run much slower as well, so not sure if it is really having to re-read the bed file for every variant candidate being genotyped.

**Comment by ASLeonard** [comment]
For completeness, I let one of the jobs for longer until finished, and the calls inside the PAR can be heterozygous and outside are always homozygous ref/alt, so the regions are being respected correctly. On this one sample however, it took around 1 CPU to postprocess without the haploid contigs/PAR and 3 hours to postprocess with, so a substantial increase.

**Comment by kishwarshafin** [comment]
@ASLeonard , 

I was able to reproduce the issue. Currently there's no way to avoid this log. I am trying to push a patch soon. Thanks for your patience.

**Comment by kishwarshafin** [comment]
@ASLeonard , I have pushed the updated code in these two docker:

```bash
google/deepvariant:CL590726281
google/deepvariant:CL590726281-gpu
```

Hopefully this will unblock you for now. I will assess the feasibility of updating the current docker or providing a v1.6.1 with this fix. Thank you for reporting this issue, it was very helpful.
