### ISSUE TITLE
How to understand the running results of deepvariant?

### ISSUE THREAD

**Issue by gushenweiz** [google/deepvariant#750]
Hello,
When I tested Deepvariant, I found one site reported as Refcall by deepvariant.
`chr1	155205518	.	C	G	0.3	RefCall	.	GT:GQ:DP:AD:VAF:PL	./.:12:391:275,116:0.296675:0,11,29`
But the result of GATK is:   `0/1:581,245:826:99:4620,0,14057`

How should I understand RefCall? The VAF of these sites is less than 0.3 due to misalignment caused by high homology in this region. Is there a way for deepvariant to recognize them as PASS?

Looking forward to your reply.
Thanks.

**Comment by kishwarshafin** [comment]
Hi @gushenweiz,

A `RefCall` can happen for several reasons. Seems like you have a very high depth in this data. Would it be possible to downsample it to something between 90-100x and try again? It seems like the model does not think it's a variant based on the evidence.

If you want to manually change the RefCall to pass then you have to do it on the VCF as a post-processing.

**Comment by AndrewCarroll** [comment]
Hi @gushenweiz 

Just to add a bit to Kishwar's answer. Refcall here means that the neural network evaluated the most probable genotype of this position to be homozygous reference. It's not always possible to infer the predictive reason for a specific call being made. 

The GenotypeQuality here is 12, which means that DeepVariant's confidence in the call is something like 94%. 

Generally, when there is a RefCall with high coverage, we tend to observe that DeepVariant seems to suspect that there is a lot of mismapped reads from some other part of the genome. If you have WGS and are using the WGS model, this makes a lot of sense as that's a very high coverage for standard sequencing. If you are using exome or panel sequencing, it's good to make sure you are using the exome model. Ref calls can be made for this, but I presume the model will be more conservative about making them.

**Comment by pichuan** [comment]
Hi @gushenweiz , hopefully Kishwar and Andrew's answers from before have been helpful. I'll close this issue now.
