### ISSUE TITLE
docker pull from google/deepvariant:1.6.0-gpu  ,but the python version is 3.11 and the proto file cannot import

### ISSUE THREAD

**Issue by one-matrix** [google/deepvariant#753]
**Describe the issue:**
 i have  use docker pull from google/deepvariant:1.6.0-gpu  ,but the python version is 3.11 in this contain，i don't know why.

<img width="1165" alt="iShot_2023-12-14_15 23 49" src="https://github.com/google/deepvariant/assets/15654389/d61f07f0-b540-4bda-8a9e-ccb633cfe3e7">

I want to debug with source code, but there will be this error, does this deepvariant.proto need to be compiled manually？

`ironment variable `TF_ENABLE_ONEDNN_OPTS=0`.
Traceback (most recent call last):
  File "/code/deepvariant/deepvariant/call_variants.py", line 48, in <module>
    from deepvariant import dv_utils
  File "/code/deepvariant/deepvariant/dv_utils.py", line 44, in <module>
    from deepvariant.protos import deepvariant_pb2
ImportError: cannot import name 'deepvariant_pb2' from 'deepvariant.protos' (unknown location)
`

**Comment by kishwarshafin** [comment]
Hi @one-matrix ,

Are you trying to build deepvariant locally? If that's the case, then please follow the steps here: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md

**Comment by one-matrix** [comment]
i have excute build_and_test.sh  but the other error come.
`
(py38) root@30634345fd4a:/deepvariant# ./build_and_test.sh 
+ source settings.sh
++ export DV_USE_PREINSTALLED_TF=0
++ DV_USE_PREINSTALLED_TF=0
++ export TF_NEED_GCP=1
++ TF_NEED_GCP=1
++ export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ DV_BAZEL_VERSION=5.3.0
++ export PATH=/root/bin:/opt/conda/envs/py38/bin:/opt/conda/condabin:/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin:/opt/conda/envs/bio/bin:/opt/deepvariant/bin:/root/bin
++ PATH=/root/bin:/opt/conda/envs/py38/bin:/opt/conda/condabin:/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin:/opt/conda/envs/bio/bin:/opt/deepvariant/bin:/root/bin
++ export DEEPVARIANT_BUCKET=gs://deepvariant
++ DEEPVARIANT_BUCKET=gs://deepvariant
++ export DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ export DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ export DV_TF_NIGHTLY_BUILD=0
++ DV_TF_NIGHTLY_BUILD=0
++ [[ 0 = \1 ]]
++ export DV_CPP_TENSORFLOW_TAG=v2.11.0
++ DV_CPP_TENSORFLOW_TAG=v2.11.0
++ export DV_GCP_OPTIMIZED_TF_WHL_VERSION=2.11.0
++ DV_GCP_OPTIMIZED_TF_WHL_VERSION=2.11.0
++ export DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=2.11.0
++ DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=2.11.0
++ export DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=2.11.0
++ DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=2.11.0
++ export DV_GPU_BUILD=1
++ DV_GPU_BUILD=1
++ export DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ export GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-2.11.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-2.11.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ export GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ export GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ export DV_TF_NUMPY_VERSION=1.19.2
++ DV_TF_NUMPY_VERSION=1.19.2
++ export DV_INSTALL_GPU_DRIVERS=0
++ DV_INSTALL_GPU_DRIVERS=0
++ export PYTHON_VERSION=3.8
++ PYTHON_VERSION=3.8
+++ which python3.8
++ export PYTHON_BIN_PATH=/opt/conda/envs/py38/bin/python3.8
++ PYTHON_BIN_PATH=/opt/conda/envs/py38/bin/python3.8
++ export PYTHON_LIB_PATH=/usr/local/lib/python3.8/dist-packages
++ PYTHON_LIB_PATH=/usr/local/lib/python3.8/dist-packages
++ export USE_DEFAULT_PYTHON_LIB_PATH=1
++ USE_DEFAULT_PYTHON_LIB_PATH=1
++ export 'DV_COPT_FLAGS=--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11'
++ DV_COPT_FLAGS='--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11'
+ bazel
[INFO 01:15:28.107 src/main/cpp/option_processor.cc:407] Looking for the following rc files: /etc/bazel.bazelrc,/deepvariant/.bazelrc,/root/.bazelrc
[INFO 01:15:28.107 src/main/cpp/rc_file.cc:56] Parsing the RcFile /deepvariant/.bazelrc
[INFO 01:15:28.107 src/main/cpp/rc_file.cc:56] Parsing the RcFile /deepvariant/../tensorflow/.bazelrc
[FATAL 01:15:28.107 src/main/cpp/blaze.cc:1295] Unexpected error reading .blazerc file '/deepvariant/../tensorflow/.bazelrc'
+ PATH=/root/bin:/root/bin:/opt/conda/envs/py38/bin:/opt/conda/condabin:/root/.vscode-server/bin/0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2/bin/remote-cli:/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/conda/bin:/opt/conda/envs/bio/bin:/opt/deepvariant/bin:/root/bin
+ [[ 1 = \1 ]]
+ bazel test -c opt --local_test_jobs=1 --copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings --experimental_build_setting_api --java_runtime_version=remotejdk_11 deepvariant/...
[INFO 01:15:28.124 src/main/cpp/option_processor.cc:407] Looking for the following rc files: /etc/bazel.bazelrc,/deepvariant/.bazelrc,/root/.bazelrc
[INFO 01:15:28.124 src/main/cpp/rc_file.cc:56] Parsing the RcFile /deepvariant/.bazelrc
[INFO 01:15:28.125 src/main/cpp/rc_file.cc:56] Parsing the RcFile /deepvariant/../tensorflow/.bazelrc
[FATAL 01:15:28.125 src/main/cpp/blaze.cc:1295] Unexpected error reading .blazerc file '/deepvariant/../tensorflow/.bazelrc'
`
