### ISSUE TITLE
Updates to underlying tools in docker

### ISSUE THREAD

**Issue by dbrami** [google/deepvariant#755]
Hi,
I noticed that DeepTrio uses an older version of GLNexus. any plans on updating the docker image to include new version?
This is a bit of naive question but how can i ensure the Docker analysis solution is using Python >= 3.11? Does this mean my system has to be Python 3.11 or greater or is this a question of what is used to build docker image?
I ask because of significant speedups gained in this version of Python and beyond...
Thank you

**Comment by AndrewCarroll** [comment]
Hi @dbrami 

With respect to the python version, this software is contained within Docker, so you don't need to worry about what version is on your system. They python versions that we can use are a function of the requirements in the dependencies of DeepVariant. In this case, we need to use Python 3.8 as a result of those dependencies. You are right that updating to Python 3.11 might have speed advantages, but this is something we will have to look at over time as underlying libraries are updated. 

With respect to GLnexus, we are expecting that there may be further updates to GLnexus, and will look at updates to that when those might become available.

**Comment by pichuan** [comment]
Hi @dbrami , 
hopefully Andrew's answer from before was helpful. I'll close this issue.
