### ISSUE TITLE
Debug source code, but bazel compilation has some problems

### ISSUE THREAD

**Issue by one-matrix** [google/deepvariant#756]
**Describe the issue:**
I want to debug source code，and execute “python deepvariant/call_variants.py”

**Setup**
  i have execute build-prereq.sh and build_and_test.sh. In order to get the compilation result .
  i execute "bazel build ...",get the file like this :
<img width="529" alt="image" src="https://github.com/google/deepvariant/assets/15654389/50fbd52c-afed-4ade-a3fa-f2eaf0859b3d">
   
The same name comes from different directories.so,the error happy:
“from third_party.nucleus.io import sharded_file_utils ” from root workspace
“from third_party.nucleus.protos import variants_pb2” from bazel-bin

<img width="647" alt="image" src="https://github.com/google/deepvariant/assets/15654389/76e1373b-dbfb-48b6-95d1-59bd07badbcc">

`root@7065ad26b62a:/deepvariant# python deepvariant/call_variants.py
2023-12-19 06:28:51.254398: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "deepvariant/call_variants.py", line 53, in <module>
    from deepvariant import dv_utils
  File "/deepvariant/./deepvariant/dv_utils.py", line 47, in <module>
    from deepvariant.protos import deepvariant_pb2
  File "/deepvariant/bazel-bin/deepvariant/protos/deepvariant_pb2.py", line 17, in <module>
    from deepvariant.protos import realigner_pb2 as deepvariant_dot_protos_dot_realigner__pb2
  File "/deepvariant/bazel-bin/deepvariant/protos/realigner_pb2.py", line 21, in <module>
    from third_party.nucleus.protos import range_pb2 as third__party_dot_nucleus_dot_protos_dot_range__pb2
ImportError: cannot import name 'range_pb2' from 'third_party.nucleus.protos' (/deepvariant/./third_party/nucleus/protos/__init__.py)
`
How can i debug the source code in the right way?
How to correctly compile proto files and c++ with bazel？
Is there an easy way to reference third_party.nucleus packages ？

**Comment by one-matrix** [comment]
@danielecook hi danielecook ,I want to try to speed up the model inference myself.
Have been executed build-prereq.sh and build_and_test.sh.
debug in system docker image: google/deepvariant:1.6.0,  Ubuntu 20.04

**Comment by danielecook** [comment]
@one-matrix are you saying you are attempting to develop within the docker image?

**Comment by one-matrix** [comment]
@danielecook yes，to avoid version issues.i develop within the docker image.Previously I thought that the docker file had already executed build-prereq.sh and build_and_test.sh. I can debug it without having to do it again. But that doesn't seem to work either.

**Comment by pichuan** [comment]
Hi @one-matrix ,

From your original post, you mentioned you ran `python deepvariant/call_variants.py`. That won't work in DeepVariant setup. For DeepVariant, all binaries needs to be built with bazel. Unlike other pure Python setup, simply `python` a .py file won't execute it correctly.

This is documented in the https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md page that @danielecook mentioned before. But, for extra clarity, let me run through it again, and write it down below for your reference.

Here is an example of how I build and execute DeepVariant binaries:

# First, get a machine to run

In my example, I used a machine from GCP, using a command like this: https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-details.md#command-for-a-cpu-only-machine-on-google-cloud-platform

```bash
gcloud compute instances create "${USER}-cpu"  \
  --scopes "compute-rw,storage-full,cloud-platform" \
  --image-family "ubuntu-2004-lts" \
  --image-project "ubuntu-os-cloud" \
  --machine-type "n1-standard-64" \
  --boot-disk-size "300" \
  --zone "us-west1-b" \
  --min-cpu-platform "Intel Skylake"
```

# ssh into the machine, and get the latest DeepVariant repo

Then, I ssh into the machine:

```bash
gcloud compute ssh ${USER}-cpu --zone us-west1-b
```

Then I get the repo:

```bash
git clone https://github.com/google/deepvariant.git
cd deepvariant
```

Following in the instructions in https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md

I first run:

```bash
sudo su
```

and then:

```bash
./build-prereq.sh
```

This step does a lot of stuff, including checking out other repos such as clif and tensorflow, and using that as part of the build environment. On my machine that I tested with just now, it took me 10m56.021s.

and then run:

```bash
./build_and_test.sh
```

This step took about 7min on my machine. 

The [build_and_test.sh](https://github.com/google/deepvariant/blob/r1.6/build_and_test.sh) script is one that I recommend you actually read. The last line gave you an example of how you'd run `call_variants`. Something like:

```bash
python3 bazel-out/k8-opt/bin/deepvariant/call_variants.zip --help
```
should work.

---

# Further development and debugging

And, from here, if you want to continue to iterate, modify code and re-build. 

You can try:

```bash
source settings.sh
```

This should allow you to use `bazel` in your terminal.  At this point if you run `bazel --help` you should see the usage.

If you make any changes, you can run:

```bash
bazel build -c opt ${DV_COPT_FLAGS} deepvariant/...
```

to re-build all binaries. (And can use `bazel test` to run unit tests)

If you're specially looking into just one build target, you can also run something like:

```bash
bazel build -c opt ${DV_COPT_FLAGS} deepvariant/call_variants
```

And, if you want to run the built binary, in addition to the one of using python to run, you can also directly run something like

```bash
bazel-bin/deepvariant/call_variants --help
```

Hope this helps.

**Comment by one-matrix** [comment]
@pichuan  Thank you very much. That was very detailed. This post can help a lot of people.
This project is a bit complicated to debug in this way. DeepVariant is too coupled to Nucleus and hope future versions to be more generic. 
I have another idea, and here's how it works：
make-example-->file-->callvariant-->file-->postprocess
Can we consider this approach，Reduce the I/O read and write：
make_examples-->Internal memory--> call_variants-->Internal memory--> postprocess_variants

**Comment by pichuan** [comment]
Hi @one-matrix ,
In the past few months, our team member @akolesnikov has been experimenting with something conceptually similar to what you described. The work is not finalized, but hopefully in our next release in 2024 , some improved implementation will come out.
Thanks for the suggestion!

**Comment by pichuan** [comment]
I'll close this issue now. If you have more questions, feel free to open new issues.

**Comment by pichuan** [comment]
By the way, I'll add a pointer from deepvariant-build-test.md to https://github.com/google/deepvariant/issues/756#issuecomment-1865388872. The change will come out in the next release.

**Comment by one-matrix** [comment]
Ok, thanks danielecook and pichuan, I am very happy to follow the development of deepvariant.
