### ISSUE TITLE
GPU with less than 16GB memory

### ISSUE THREAD

**Issue by husamia** [google/deepvariant#759]
Per: https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md#how-much-gpu-memory-is-needed-for-the-keras-models

16GB. In our test, we observe the model occupying 16GB GPU memory.

I have a GPU NVIDIA RTX A2000 with 6GB memory, is there a way I can use it to do the call variants step with no problems?

**Comment by pichuan** [comment]
Hi @husamia ,
To load the Keras model with GPU, you'll need enough memory. 
In the future we can see if there are ways we could improve this, but for the current version, I don't think there is a lower-memory solution.

**Comment by kishwarshafin** [comment]
Hi @husamia,


Unfortunately, 6GB is too low. The data needs to load to RAM before being loaded to GPU. So there needs have sufficient memory for that and to load the model too.

**Comment by pichuan** [comment]
Thanks @kishwarshafin !

@husamia , I'll close this issue now. Feel free to follow up if you have more questions.
