### ISSUE TITLE
Can't Download print_F1.py

### ISSUE THREAD

**Issue by ssm0808** [google/deepvariant#76]
Hi,
I saw the file about Improve DeepVariant for BGISEQ germline variant calling:
https://github.com/SVAI/RecausalNucleotideNetworks/
There is an introduction how to pick a model in the page 11th of this file. When I try to pick a model, I can't download the python script print_F1.py frome https://gist.github.com/pichuan/fde73e263dba51230791d56e0b9396e1. How can I get print_F1.py with other way?

**Comment by pichuan** [comment]
Hi,
the link is a gist with a short python script. You should be able to just paste that into a file yourself.
Are you unable to see the content of the gist?
