### ISSUE TITLE
Left-normalization error

### ISSUE THREAD

**Issue by elcortegano** [google/deepvariant#762]
I have encountered the following error in several PacBio HiFi samples while running the docker image of deepvariant 1.4.0:

> F deepvariant/allelecounter.cc:872] Check failed: left_padding + right_padding < counts_.size() (5000 vs. 4022)
Fatal Python error: Aborted

Deepvariant was run while enabling read normalization:

    docker run -v "input_path":/input -v "output_path":/output google/deepvariant:1.4.0 /opt/deepvariant/bin /run_deepvariant --model_type=PACBIO --make_examples_extra_args="normalize_reads=true" --ref=/input/reference.fa --reads=/input/sample.bam --output_vcf=/output/sample.vcf --output_gvcf=/output/sample.gvcf --num_shards=16 --logging_dir=/output/logs

I know it is discouraged to enable read normalization due to potential excessive computational times, but I need it to make sure that I am capturing INDELs on the same conditions as my Illumina left-aligned samples.

Any ideas on how to solve this issue?
Thank you,
Eugenio

**Comment by kishwarshafin** [comment]
Hi @elcortegano ,

`--normalize_reads` is designed for short reads in which case the mapping wouldn't accurately left align all of the indels. For long reads, I do not believe that would be the case as most of the reads would span your INDELs accurately, so `--normalize_reads` for PacBio should not be required. In this, we are assuming you are using minimap2 as the mapper.

On the other hand, if you are trying to normalize the VCF then you can do it post variant calling. Please see `bcftools norm` https://vcftools.github.io/htslib.html#norm

**Comment by elcortegano** [comment]
Thank you for the clarifications,

So, if I understand correctly, in a multi-sample scenario I could left-align the deepvariant-produced VCFs with `bcftools norm` and then use GLnexus to combine them. For merging, should the gVCFs also be left-aligned? (those are required by GLnexus I believe)

**Comment by kishwarshafin** [comment]
@elcortegano , 

Please use this: https://github.com/mlin/gvcf_norm for gVCFs.

**Comment by elcortegano** [comment]
Thank you very much! will try that
