### ISSUE TITLE
There are bugs in version 1.6

### ISSUE THREAD

**Issue by ColinR01** [google/deepvariant#764]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md**:

**Describe the issue:**
When variant is not detected, the program will freeze in the last step；

**Setup**
  - Operating system:Centos7.6
  - DeepVariant version: 1.6 
  - Installation method (Docker, built from source, etc.): singularity
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) PACBIO-SMART；A reference sequence for a normal person；

**Steps to reproduce:**
  - Command: /bin/singularity run -B /work/:/work/ /work/deepvariant.sif /opt/deepvariant/bin/run_deepvariant --model_type=PACBIO --ref=human_geneA_reference.fa --reads=reference.align.bam --output_vcf=out.vcf --output_gvcf=out.gvcf --num_shards=32
  - Error trace: Last line： I0119 11:43:53.450599 47012502976320 call_variants.py:623] Complete: call_variants（Stuck at this step）.

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

[deepvariant_1.6.pdf](https://github.com/google/deepvariant/files/13986125/deepvariant_1.6.pdf)

**Comment by kishwarshafin** [comment]
@ColinR01 ,

Is it possible to provide the input files to reproduce this result?

**Comment by pichuan** [comment]
I believe @kishwarshafin was able to reproduce the issue and is currently looking into a fix.
Keeping this open for now.

**Comment by kishwarshafin** [comment]
Hi @ColinR01 ,

Please try the following docker that has the patch incorporated that should fix your issue:

```bash
docker pull google/deepvariant:CL602468145
docker pull google/deepvariant:CL602468145-gpu
```

**Comment by kishwarshafin** [comment]
@ColinR01 , Can you please try the v1.6.1 docker? If the issue isn't resolved, please feel free to reopen this bug.
