### ISSUE TITLE
DeepVariant with RNASeq Model "stuck"

### ISSUE THREAD

**Issue by bcantarel** [google/deepvariant#766]
I have tried running deepvariant (v1.6.0) using the rnaseq models using the example data with the google docker container:
`run_deepvariant --num_shards=32 --model_type=WES --customized_model=/opt/models/rnaseq/model.ckpt --regions=test.bed --ref=genome.fa --reads=hg005_gm26107.mrna.grch38.bam --output_vcf=deepvariantrna.vcf --logging_dir=logs --make_examples_extra_args="split_skip_reads=true,channels=''"`

But it seems to get stuck at the call_variant step

**Any additional context:**

<img width="1304" alt="image" src="https://github.com/google/deepvariant/assets/7647927/0c01d955-c1fa-4ede-9579-3f942c262c3a">

test.bed
chr1    13670   13966
chr1    14409   14501
chr1    15005   15038
chr1    15796   15947
chr1    16607   16765
chr1    16858   17055
chr1    17233   17368
chr1    17369   17436
chr1    17606   17742
chr1    17915   18061
chr1    18268   18366
chr1    24738   24891
chr1    29534   30039
chr1    30267   30667
chr1    30976   31109
chr1    34554   35174
chr1    35245   35481
chr1    35721   36081
chr1    52473   53312
chr1    57598   57653
chr1    58700   58856
chr1    62916   64116
chr1    65419   65433
chr1    65520   65573
chr1    69037   71585
chr1    89295   91629
chr1    92091   92240
chr1    110953  111357
chr1    112700  112804
chr1    120721  120932
chr1    129055  129223
chr1    131025  134836
chr1    135141  135895
chr1    137682  137965
chr1    139790  139847
chr1    140075  140339
chr1    141474  143011
chr1    146386  149707
chr1    155767  155831
chr1    157784  157887
chr1    160446  160690
chr1    161314  161525
chr1    164263  164791
chr1    165491  165942
chr1    167129  168165
chr1    168610  168767
chr1    169049  169264
chr1    172557  172688
chr1    173753  173862
chr1    182696  182746
chr1    183132  183216
chr1    183494  183571
chr1    183740  183901
chr1    183981  184174
chr1    185217  185350
chr1    185491  185559
chr1    186317  186469
chr1    187129  187287
chr1    187376  187577
chr1    187755  187890
chr1    187891  187958
chr1    188130  188266
chr1    188439  188584
chr1    188791  188902
chr1    195263  195411
chr1    257864  259025
chr1    261550  261634
chr1    263015  268655
chr1    268667  268816
chr1    289266  289370
chr1    297345  297502
chr1    347982  348366
chr1    356685  357586
chr1    358049  358183
chr1    358857  358957
chr1    359345  359681
chr1    360057  360168
chr1    365171  366151
chr1    368251  368450
chr1    373144  373323
chr1    379769  379972
chr1    439870  440232
chr1    450740  451678
chr1    476364  476945
chr1    484832  485208
chr1    487101  489553
chr1    489717  489906
chr1    491225  491989
chr1    492768  493241
chr1    494382  494898
chr1    494992  495049
chr1    495277  495476
chr1    496264  496605
chr1    497109  497299
chr1    498047  498305
chr1    498399  499369
chr1    501556  501620
chr1    502187  502243
chr1    502465  502955
chr1    504470  505103

**Comment by danielecook** [comment]
@bcantarel what type of machine are you running this on? I wonder if DeepVariant is resource-constrained.

What do you get when you type `nproc` ? Can you try to lower the value of `--num_shards` to this value if it is lower?

**Comment by kishwarshafin** [comment]
@bcantarel ,

Please use "1.5.0" for the RNA-seq model as it is trained with slim. Version 1.6.0 only works with Keras models.

**Comment by pichuan** [comment]
Hi @bcantarel ,
I hope using the right version resolved your issue. Closing this now.
