### ISSUE TITLE
Error running KMC in Giraffe case study

### ISSUE THREAD

**Issue by slzarate** [google/deepvariant#767]
Hi all,

This is not strictly a DeepVariant issue, but it is an issue I ran into while following the Giraffe case study using exome FASTQs from [here](https://www.internationalgenome.org/data-portal/sample/NA12878) (specifically, `SRR1518158_*.fastq.gz`). I'm running this on a DNAnexus cloud workstation (`mem1_ssd1_v2_x8`) and using the same version of KMC used in the case study. I am trying to run KMC using the following command:

```
TMPDIR=$(mktemp -d)
time ./kmc -k29 -okff -t8 sra.fq.paths ./sra.fq $TMPDIR
```

where `sra.fq.paths` is the result of `ls SRR1518158_*.fastq.gz > sra.fq.paths`.

The error message is simply `Error: unknown exception`. Have you seen this before? I thought I'd ask here before filing an issue with the KMC repo.

Thanks,
Samantha

**Comment by jltsiren** [comment]
If `sra.fq.paths` is a list of input files, it should be entered as `@sra.fq.paths`. KMC does not attempt to identify the input type. If not specified otherwise, it seems to assume that the input is (plain or gzipped) fastq.

**Comment by slzarate** [comment]
@pichuan @jltsiren Thank you! That did it.

**Comment by glennhickey** [comment]
You need to prefix your paths file with `@`.  So try
```
time ./kmc -k29 -okff -t8 @sra.fq.paths ./sra.fq $TMPDIR
```
