### ISSUE TITLE
How could I lower the Total %cpu when deepvariant running call_variant.py

### ISSUE THREAD

**Issue by Luosanmu** [google/deepvariant#768]
Hello,

I have a trouble to control the %cpu in Linux when deepvariant run call_variant.py step.
It makes %cpu is too high to affect another user to run his program.

![Pasted image 20240201133331(1)](https://github.com/google/deepvariant/assets/91660863/8f6a76bf-5d27-4a27-8175-417a644f396e)

How could I make it lower than this picture show?

Please look at my picture, And put my code down. 

docker run \
        -u $(id -u):$(id -g) \
        -v "${hg19}":"/home/luohaosen/ref" \
        -v "${INPUT_DIR}":"/home/luohaosen/input" \
        -v "${OUTPUT_DIR}":"/home/luohaosen/output" \
        luohaosen/deepvariant:v1 \
        /opt/deepvariant/bin/run_deepvariant \
        --model_type=WES \
        --ref=/home/luohaosen/ref/ucsc.hg19.fa \
        --reads=/home/luohaosen/input/TKQX230060435-1A.MarkDuplicates.bam \
        --output_vcf=/home/luohaosen/output/TKQX230060435.deepvariant.vcf.gz \
        --intermediate_results_dir=/home/luohaosen/output/intermediate_results_dir \
        --num_shards=$num_shards

(Note：luohaosen//deepvariant:v1 is based on google/deepvariant:1.6.0，It is almost the same as origin google/deepvariant:1.6.0 docker image)

**Comment by kishwarshafin** [comment]
@Luosanmu , 

Can you please add:

```bash
docker run --cpus=$num_shards
```

This way you set the CPU limits of the container you are running. It's explained more in [here](https://docs.docker.com/config/containers/resource_constraints/#cpu).

**Comment by Luosanmu** [comment]
@kishwarshafin ,

cool ！，It is useful work !!!  thanks.
