### ISSUE TITLE
Issue calling make_examples.py

### ISSUE THREAD

**Issue by helizabeth1103** [google/deepvariant#771]
Hello! I'm experiencing an issue when trying to run make_examples. Instead of Docker we're using Singularity, and deepvariant has run before with just calling the run_deepvariant.py. 

For example, this is what has worked for us in the past in our environment: 

> module load singularity
> source activate $condapath/DeepVariant

> singularity exec $softwarepath/Singularity_files/deepvariant_1.5.0.sif python3 $softwarepath/deepvariant/run_deepvariant.py [...]

When trying to run make_examples, this code:

> singularity exec $softwarepath/Singularity_files/deepvariant_1.5.0.sif python3 $softwarepath/deepvariant/deepvariant/make_examples.py [...] 

is now throwing this error code: 

> Traceback (most recent call last):
>   File "/$softwarepath/deepvariant/deepvariant/make_examples.py", line 35, in <module>
>     from deepvariant import dv_constants
> ModuleNotFoundError: No module named 'deepvariant'

Does this mean there is a problem with our install? Any ideas or suggestions? 

Thank you very much for any light you can shed on this issue!

Best, 
Haley

**Comment by akolesnikov** [comment]
Hello @helizabeth1103,

dv_constants.py is the part of DeepVariant installation. 
You may take a look at  https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md#notes-on-singularity for more details on DeepVariant with Singularity.
You may also check https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-training-case-study.md that shows how to run make_examples from docker.

**Comment by pichuan** [comment]
Hi @helizabeth1103 ,
Due to inactivity on this issue, I'll close it. Please feel free to follow up if you have more questions.
