### ISSUE TITLE
Maintain Barcode in Output

### ISSUE THREAD

**Issue by gneedle1** [google/deepvariant#772]
When running deepvariant on single cell Pacbio longread data, is it possible to have the output include the barcode where the SNP was found?

**Comment by kishwarshafin** [comment]
hi @gneedle1 ,

Currently it is not possible to have the barcodes output in the VCF. Thank you for the request.

**Comment by gneedle1** [comment]
Would it be valid to subset the original BAM by barcode and run each subset individually?

**Comment by gneedle1** [comment]
The experimental setup is roughly:

1. Hairy cell leukemia cells were isolated from the blood of patients.
2. Single-cell cDNAs were synthesized and barcoded by 10X Genomics platform (cDNAs of each cell are barcoded individually).
3. Direct RNA seq will be run for the single-cell cDNAs from one patient on the flow cell of ONT sequencer.
4. The goal is to call mutations for the cDNA in individual cells and then build single-cell phylogeny based on mutations.

**Comment by AndrewCarroll** [comment]
I see, so in this case, each barcode corresponds to a specific cell. If you have sufficient coverage, you can split by barcode and make the call, it's really just a question of coverage. For your purpose, you can split by barcodes.

**Comment by pichuan** [comment]
Thanks @AndrewCarroll for the follow-up answer. I will now close this issue.
