### ISSUE TITLE
The step of postprocess_variants cannot find the VCF file

### ISSUE THREAD

**Issue by Bank-tidy** [google/deepvariant#773]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6/docs/FAQ.md**:

**Describe the issue:**
The step of postprocess_variants cannot find the VCF file.

  - Operating system:Centos
  - DeepVariant version:1.6.0
  - Installation method :singularity
  - Type of data: (NGS sequence)

**Steps to reproduce:**
  - Command:
  mkdir /public1/home/yinhang/data/tmp/${SAMPLE}/
singularity exec /public/software/apps/deepvariant-1.6.0-cpu_singularity/deepvariant-1.6.0.sif \
/opt/deepvariant/bin/run_deepvariant \
--model_type=WGS \
--ref=${ref_genome} \
--reads="${SORTED_BAM_DIR}/${SAMPLE}/${SAMPLE}.sorted.bam" \
--output_vcf="${VCF_DIR}/${SAMPLE}/${SAMPLE}.vcf.gz" \
--output_gvcf="${VCF_DIR}/${SAMPLE}/${SAMPLE}.g.vcf.gz" \
--intermediate_results_dir=/public1/home/yinhang/data/tmp/${SAMPLE}/ \
--num_shards=60 \
--sample_name ${SAMPLE}

  - Error trace:

I0217 17:31:41.680527 139931052529472 call_variants.py:623] Complete: call_variants.

real	339m11.258s
user	13508m55.048s
sys	183m10.091s

***** Running the command:*****
time /opt/deepvariant/bin/postprocess_variants --ref "/public1/home/yinhang/projects/two_genomes/04_T2T/04_ragtag/03_syri/01_data/SH_N0.fasta" --infile "/public1/home/yinhang/data/tmp/SRR1572254/call_variants_output.tfrecord.gz" --outfile "/public1/home/yinhang/projects/two_genomes/04_T2T/11_snp/03_vcf/SRR1572254/SRR1572254.vcf.gz" --cpus "60" --gvcf_outfile "/public1/home/yinhang/projects/two_genomes/04_T2T/11_snp/03_vcf/SRR1572254/SRR1572254.g.vcf.gz" --nonvariant_site_tfrecord_path "/public1/home/yinhang/data/tmp/SRR1572254/gvcf.tfrecord@60.gz" --sample_name "SRR1572254"

/bin/bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (zh_CN.UTF-8)
I0217 17:31:47.293663 139808123168576 postprocess_variants.py:1211] Using sample name from call_variants output. Sample name: SRR1572254
I0217 17:31:47.294324 139808123168576 postprocess_variants.py:1216] --sample_name is set but was not used.
2024-02-17 17:31:47.310170: I deepvariant/postprocess_variants.cc:94] Read from: /public1/home/yinhang/data/tmp/SRR1572254/call_variants_output-00000-of-00001.tfrecord.gz
2024-02-17 17:33:25.282554: I deepvariant/postprocess_variants.cc:109] Total #entries in single_site_calls = 18154823
I0217 17:38:26.134845 139808123168576 postprocess_variants.py:1313] CVO sorting took 6.647122502326965 minutes
I0217 17:38:26.135649 139808123168576 postprocess_variants.py:1316] Transforming call_variants_output to variants.
I0217 17:38:26.135714 139808123168576 postprocess_variants.py:1318] Using 60 CPUs for parallelization of variant transformation.
I0217 17:39:46.024054 139808123168576 postprocess_variants.py:1211] Using sample name from call_variants output. Sample name: SRR1572254
I0217 17:39:46.024466 139808123168576 postprocess_variants.py:1216] --sample_name is set but was not used.
I0217 17:53:05.493927 139808123168576 postprocess_variants.py:1386] Processing variants (and writing to temporary file) took 7.4284539779027305 minutes
[E::hts_open_format] Failed to open file "/public1/home/yinhang/projects/two_genomes/04_T2T/11_snp/03_vcf/SRR1572254/SRR1572254.vcf.gz" : No such file or directory
2024-02-17 17:53:05.496309: E third_party/nucleus/io/merge_variants.cc:115] opening writer failedCould not open variants_path: /public1/home/yinhang/projects/two_genomes/04_T2T/11_snp/03_vcf/SRR1572254/SRR1572254.vcf.gz
2024-02-17 17:53:05.496469: F ./third_party/nucleus/core/statusor.h:230] Non-OK-status: status_ status: UNKNOWN: Could not open variants_path: /public1/home/yinhang/projects/two_genomes/04_T2T/11_snp/03_vcf/SRR1572254/SRR1572254.vcf.gz
Fatal Python error: Aborted

Current thread 0x00007f279d84a740 (most recent call first):
  File "/tmp/Bazel.runfiles_vibz8587/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1391 in main
  File "/tmp/Bazel.runfiles_vibz8587/runfiles/absl_py/absl/app.py", line 258 in _run_main
  File "/tmp/Bazel.runfiles_vibz8587/runfiles/absl_py/absl/app.py", line 312 in run
  File "/tmp/Bazel.runfiles_vibz8587/runfiles/com_google_deepvariant/deepvariant/postprocess_variants.py", line 1419 in <module>

real	27m34.677s
user	18m45.707s
sys	4m47.747s
**Any additional context:**
![image](https://github.com/google/deepvariant/assets/108465040/18d9cc45-ef3a-4f05-8a85-19eefac74034)
call_variants may be have done ,but postprocess_variants Failed to open file "file.vcf.gz" : No such file or directory

**Comment by kishwarshafin** [comment]
@Bank-tidy ,

Can you make sure: "${VCF_DIR}/${SAMPLE}/" directory exists before you run?

**Comment by Bank-tidy** [comment]
Thank you for your suggestion, I will confirm again！
