### ISSUE TITLE
DeepTrio from 1.6.0 : how to isolate de novo calls from trio VCF ?

### ISSUE THREAD

**Issue by francois-lecoquierre** [google/deepvariant#779]
Hi, 
I'm intersested in de novo variant identification from human Illumina WGS data. As DeepTrio seems very powerful for this task since the 1.6.0 verison of DeepVaraint, I have performed some tests and it indeed seems that it achieves great results. 

In my workflow, I apply an series of empirical filters with bcftools view to the glnexus merged trio vcf generated by DeepTrio. Filters include the following metrcs : GT, DP, VAF extracted using AD, and others. While results are OK, there are still false positive (particularly for indels) and a few false negatives too. 

In the blogpost you state that you have yield impressive resluts: "for chr20 at 30x HG002-HG003-HG004, false negatives reduced from 8 to 0 with DeepTrio v1.4, false positives reduced from 5 to 0". 
I imagine you must have applied a dedicated method to isolate de novo variants from trio data? If so, would you be willing to share this method? 

Thanks for your great software. 
François

**Comment by kishwarshafin** [comment]
Hi @francois-lecoquierre ,

There are a few ways you can find de novo mutations:

1) A pipeline-based approach can be found here: https://github.com/shlokanegi/denovo_snps

2) You can use [rtgtools](https://github.com/RealTimeGenomics/rtg-tools) to isolate de novo variants. Here's an example command for the HG002 trio:

```bash
rtg vcfmerge HG004.vcf.gz HG003.vcf.gz HG002.vcf.gz \
--add-header "##PEDIGREE=<Child=HG002,Mother=HG003,Father=HG004>" \
--add-header "##SAMPLE<ID=HG002,Sex-MALE>" \
--output HG002_trio.vcf.gz

rtg mendelian -t /path/to/ref.sdf --input HG002_trio.vcf.gz \
 --lenient --output-inconsistent trio-non-mendelian.vcf.gz
```

You can generate the SDF by running:
```bash
rtg format -o /path/to/ref.sdf /path/to/ref.fasta
```

This suggestion is from [biostars](https://www.biostars.org/p/329022/) that also lists few other solutions.

**Comment by francois-lecoquierre** [comment]
Thank you very much @kishwarshafin, I'll give these a go

**Comment by pichuan** [comment]
I'll close this. Feel free to open if you have more questions.

**Comment by srbehera** [comment]
@francois-lecoquierre just wanted to check if you tried the `rtgtools` steps. I am getting the following error when I tried those steps

```
When merging multiple samples the QUAL, FILTER, and INFO fields are taken from the first record at each position.
Error: Additional header line '##SAMPLE=<ID=XXXX, Sex-Male>', Could not parse VCF header line

```
