### ISSUE TITLE
model_train.py has flag message format error (crashes on --help)

### ISSUE THREAD

**Issue by tutufan** [google/deepvariant#78]
model_train --help crashes.

The help text for label_smooth in model_train.py contains a nonobvious "%m", which crashes the --help formatter.  The solution is either to double the '%' or reword.

'Amount of label smoothing to use. By default this is 0.0001%'
'm...'

**Comment by pichuan** [comment]
Hi. What OS are you running on? I actually don't see this crash on the Ubuntu 16 setup.
If you can let me know how to reproduce the error, we'll make sure to fix it and will come out with the next release. Thanks for reporting!

**Comment by tutufan** [comment]
Hi.  This is actually happening in the Docker image provided with DeepVariant.  (It's been converted to a Singularity image, but it's difficult to imagine that affecting this behavior.)

Doing a little testing, the "%m" seems to crash Python 2 but not Python 3.  Perhaps that's somehow the difference?  And this is (I think) coming via TensorFlow, which might also matter.

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.8.2] on linux
   'asdf %0.001mean' % (3,)
Traceback (most recent call last):
  File "python", line 1, in <module>
ValueError: unsupported format character 'm' (0x6d) at index 11
```

**Comment by pichuan** [comment]
I will add a space between % and m.  Do you think that will fix the problem you're seeing? There really should be a space anyway, so I will add it. When I try %%, it displays two %, which doesn't seem correct to me.

**Comment by tutufan** [comment]
Seems like it should work.  This is indeed an annoying corner case, but the `--help` message is pretty important.  :-)
