### ISSUE TITLE
Error running DeepVariant

### ISSUE THREAD

**Issue by malonzm1** [google/deepvariant#782]
Hi,

I encountered a problem running DeepVariant v1.5.0. I ran the following code:

```
singularity run -B /scratch \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --customized_model=${MODEL_DIR}/model.ckpt \
  --ref="${FASTA_DIR}"/genome.fa \
  --reads="${READ_DIR}"/SRR6006655Aligned.sortedByCoord.out.bam \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --make_examples_extra_args="split_skip_reads=true,channels=''" \
  --num_shards=${NCPU} #\ **How many cores the `make_examples` step uses. Change it to the number of CPU cores you have.**    
```

The error log is attached. 
[deepvariant_test.txt](https://github.com/google/deepvariant/files/14489514/deepvariant_test.txt)

The error is about numpy compatibility. `RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem`. I also got the same error with DeepVariant 1.6.0.

Please advise.

Thanks and good day.

**Comment by danielecook** [comment]
@malonzm1 it could be that your external environment is problematic. Can you try adding the `--cleanenv ` flag?

e.g. 

```
singularity run --cleanenv -B /scratch \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --customized_model=${MODEL_DIR}/model.ckpt \
  --ref="${FASTA_DIR}"/genome.fa \
  --reads="${READ_DIR}"/SRR6006655Aligned.sortedByCoord.out.bam \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --make_examples_extra_args="split_skip_reads=true,channels=''" \
  --num_shards=${NCPU} #\ **How many cores the `make_examples` step uses. Change it to the number of CPU cores you have.**    
```

**Comment by pichuan** [comment]
Search the error in our GitHub repo, it seems like https://github.com/google/deepvariant/issues/746 and https://github.com/google/deepvariant/issues/640 can be relevant.

@malonzm1 you can check your numpy version, and see if you can update it?

**Comment by kishwarshafin** [comment]
Hi @malonzm1 , I will close this issue for now. Please feel free re-open if you need further assistance on this.
