### ISSUE TITLE
Error running DeepVariant via singularity

### ISSUE THREAD

**Issue by malonzm1** [google/deepvariant#783]
Hi,

I am able to run the command below when the bash file is located in the same folder where the sif file was pulled. 

```
singularity run -B /scratch \
  docker://google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WES \
  --customized_model=${MODEL_DIR}/model.ckpt \
  --ref="${FASTA_DIR}"/genome.fa \
  --reads="${READ_DIR}"/SRR6006655Aligned.sortedByCoord.out.bam \
  --output_vcf="${OUTPUT_DIR}"/output.vcf.gz \
  --output_gvcf="${OUTPUT_DIR}"/output.g.vcf.gz \
  --intermediate_results_dir "${OUTPUT_DIR}/intermediate_results_dir" \
  --make_examples_extra_args="split_skip_reads=true,channels=''" \
  --num_shards=${NCPU} #\ **How many cores the `make_examples` step uses. Change it to the number of CPU cores you have.**    
```
Can I run the bash file if it is located in a folder other than the folder where the sif file is located? I tried adding `cd ${SINGULARITY_DIR}` in the bash file but it returns an error:

```
INFO:    /etc/singularity/ exists; cleanup by system administrator is not complete (see https://apptainer.org/docs/admin/latest/singularity_migration.html)
INFO:    Using cached SIF image
2024-03-05 05:27:15.547122: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
--ref is required.
Pass --helpshort or --helpfull to see help on flags.
/var/spool/slurmd/job29299921/slurm_script: line 24: --customized_model=/scratch/cs/pan-autoimmune/utilities/deepvariant/references/model/model.ckpt: No such file or directory
/var/spool/slurmd/job29299921/slurm_script: line 30: --make_examples_extra_args=split_skip_reads=true,channels='': command not found
```

Please advise.

Thanks and good day.

**Comment by pichuan** [comment]
Hi @malonzm1 , please let us know if you can clarify your setup a bit more. I am also not sure how to help with your question here.

**Comment by kishwarshafin** [comment]
@malonzm1 , I will close this bug. Please feel free to re-open if you need further assistance.

**Comment by mccafj02** [comment]
Has there been a solution to this error?  I'm seeing the same thing.  I'm running deepvariant:1.6.1-gpu in a WDL workflow.  It runs without error when I use it interactively but throws the error inside the WDL task.

**Comment by kishwarshafin** [comment]
@mccafj02,

Can you please send the command and logs for details? This issue is not related to GPU.

**Comment by mccafj02** [comment]
Thanks for the quick response.  This is the command and log file.
[stderr.log](https://github.com/google/deepvariant/files/14670380/stderr.log)

`/opt/deepvariant/bin/run_deepvariant \
    --model_type=~{model} \ 
    --ref= ~{ref_fasta} \
    --reads= ~{align_bam} \
    --make_examples_extra_args=~{MAKE_EXAMPLE_ARGS} \
    --output_vcf= ~{sampleID}.vcf.gz \
    --output_gvcf= ~{output_file_name} \
    --num_shards= ~{cpu_per_task} \
    --haploid_contigs="chrX,chrY" \ 
    --par_regions_bed= ~{par_bed} \ 
    --postprocess_variants_extra_args=~{POSTPROCESS_VARIANTS_ARGS} \
    --regions= ~{regions}`

**Comment by kishwarshafin** [comment]
please see the error has:

```bash
--ref is required.
Pass --helpshort or --helpfull to see help on flags.
```

Meaning your variable ~{ref_fasta} is either NULL or set to a value that is not accessible to the program.

**Comment by pichuan** [comment]
Hi @mccafj02 ,
This issue has been inactive for a few weeks, so I'll close it. Please feel free to reopen if you want to follow up with more details after the last suggestion. Thank you!
