### ISSUE TITLE
Somatic and germline variants

### ISSUE THREAD

**Issue by j0ntt** [google/deepvariant#784]
Hi,

Does DeepVariant attempt to distinguish germline and somatic variants?

If the VAF of a variant is low, will that mutation be then filtered out or does the tool report only variants of which VAF is close to 0.5 (heterozygous) or 1 (homozygous)?

**Comment by danielecook** [comment]
@j0ntt you should have a look at github.com/google/deepsomatic.

* DeepVariant is a germline caller.
* DeepSomatic is a somatic caller.

DeepSomatic will distinguish between germline and somatic variants.

**Comment by j0ntt** [comment]
Hi @danielecook 

Does this method have a tumor-only mode?

**Comment by danielecook** [comment]
Currently - no. But we may release a tumor only mode in the future.
