### ISSUE TITLE
model_type for ONT WGS data

### ISSUE THREAD

**Issue by HelloYanming** [google/deepvariant#785]
Hi, 

Thanks for developing this package.
It looks like there are both WGS and ONT model type, and I am wondering what model type is recommended for ONT WGS data? 

Best,
YM

**Comment by pichuan** [comment]
Hi YM, 

Please use ONT_R104. If you have older ONT data, you can consider https://github.com/kishwarshafin/pepper.

Our WGS model is for short-read data, for example Illumina or Element.

You can also see our Quick Start tutorials for examples.

Let me know if you have more questions!
