### ISSUE TITLE
Parallel execution of DeepVariant fails when using CRAM alignment files.

### ISSUE THREAD

**Issue by jjuhyunkim** [google/deepvariant#786]
**Describe the issue:**
I ran DeepVariant step by step using Illumina reads. I have a simple question : is it unable to run `make_examples` using `cram` file when running them in parallel? 

I generated my alignment file in CRAM format to reduce the file size. However, when I attempted to run the `make_examples` command in parallel, it failed with the error message `/dev/tty: No such device or address`.

Below is what I tried : 
1. non-parallel + bam ✅
2. non-parallel + cram ✅ 
3. parallel + bam ✅ 
4. non-parallel + cram 🔴   

I can run it using `BAM` file instead, but i'm just curious if this is the cause of this error. 

**Setup**
  - Operating system: Linux/4.18.0-513.18.1.el8_9.x86_64
  - DeepVariant version:  v1.6.0
  - Installation method (Docker, built from source, etc.): HPC, sorry I don't know
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)
  Not special, I used common toy data.

**Steps to reproduce:**
  - Command: 
 ```
seq 0 $((N_SHARDS-1)) \
    | parallel -P ${SLURM_CPUS_PER_TASK} --halt 2 \
        --joblog "$wd/logs-parallel-$SLURM_JOB_ID/log" --res "$wd/logs-parallel-$SLURM_JOB_ID" \
      make_examples --mode calling \
        --ref "${REF}" \
        --reads "${BAM}" \
        --regions "chr20:10,000,000-10,010,000" \
        --examples output/examples.tfrecord@${N_SHARDS}.gz\
        --channels insert_size \
        --task {} \
|| exit 1
```
  - Error trace: (if applicable)
```
META: 0s Left: 48 AVG: 0.00s  local:48/0/100%/0.0s ESC[Ksh: /dev/tty: No such device or address
```

**Comment by jjuhyunkim** [comment]
Oh, wait 
I think my data seems weird.. 

I will leave comment after double-checking

**Comment by pichuan** [comment]
Hi @jjuhyunkim ,
Please let me know whether there's still an issue after you double check.

**Comment by jjuhyunkim** [comment]
Hi @pichuan 

Thank you for your attention to this issue! 
There is no bug or issue in DeepVariant. The problem lies within my input file, which I haven't fully understand yet. However, it works using other dataset. 

I will close this issue, 
Thanks!
