### ISSUE TITLE
Question about retraining DeepVariant

### ISSUE THREAD

**Issue by rickymagner** [google/deepvariant#788]
Hi, I had a quick question involving [training](https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-training-case-study.md) DeepVariant from an existing one. On the training data [page](https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-details-training-data.md), the footnotes say that in v1.1 you exclude HG003 and chr20-22 from the training data. 

Is this true for all versions since then? Does that mean if I wanted to train a new model from an existing one, it's safe to train on chr1-19 and then validate on chr20-22 on NIST data without the model ever seeing the variants there? Is it safe to use HG003 everywhere even though they are a direct relative of HG002 (whose data is used extensively in the training)? 

Thanks!

**Comment by pichuan** [comment]
Hi, up to the latest version (1.6), we've been excluding HG003 and chr20-22 from the training data.

Building on that assumption, if you train a model (warmstarting our model) that also exclude those data from training, you can be sure that the model would never have seen those data.

And you're correct that it's still good to be aware that HG002 is the son of HG003. So it depends on what hypothesis you're testing, you'll want to think about that factor too.

**Comment by rickymagner** [comment]
Great, thank you!
