### ISSUE TITLE
Can it call variants on tetraploid species?

### ISSUE THREAD

**Issue by afzm** [google/deepvariant#79]

**Comment by pichuan** [comment]
No. The model we released is diploid. 

Long answer: in terms of the implementation, many of the utility functions try to take into account different ploidy. But in the actual case of DeepVariant we haven't done anything other than the diploid scenario.  so if you're looking for an already pre-packaged caller, the answer is no. But if you're looking for Python functions  that might help with your development, please feel free to look into the code in Nucleus and deepvariant, and let us know if you have any questions.
