### ISSUE TITLE
Developers notes / environment for modifying code

### ISSUE THREAD

**Issue by rickymagner** [google/deepvariant#792]
Hi, I wanted to try adding some custom channels to experiment with like in the tutorial [here](https://google.github.io/deepvariant/posts/2022-06-09-adding-custom-channels/). I was wondering if there were any developer's notes on setting up an environment for good syntax highlighting, autocomplete, etc. for C++ with this project so I can better understand how to use the Nucleus library.

The [build guide](https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-build-test.md) didn't seem to have anything to this effect. I tried using VSCode and CLion Nova, but can't seem to get the autocomplete to work on either. I'm guessing this is because the project is built using the Dockerfile and incorporates a few different languages, so it's not a "pure" C++ project. 

Could any developers share some tips on their setup, or point me to a developer's guide? Thanks!

**Comment by pichuan** [comment]
Hi @rickymagner ,
to share my own experience, I work at Google so currently use an Google internal IDE. And, I actually don't use autocomplete myself. During my earlier times at Google, I'm actually an emacs user (and I used `emacs -nw` a lot).

It's outside our support scope to provide suggestions for IDE. And of all the engineerings teams I've been on, people seem to have different preferences anyway.

I'll leave this open a bit to see if any other readers want to share your own setup :)

**Comment by kishwarshafin** [comment]
hi @rickymagner ,

In projects like these, I used to prefer CLion for an IDE. It has many customizable features. You can install the python extension for python support. You can also add some autocomplete extensions (at least last year it was the case). However, it's mostly personal preference in most cases. Hope you find something that works for you.

**Comment by akolesnikov** [comment]
DeepVariant is built with bazel. Internally we have an add-on in CLion to import bazel project. If this plug-in is available you can try to do that. Bazel project is in the file named "BUILD" which exists in all sub-directories. If importing bazel project is not available then you may need to create your project from scratch in your IDE and then add all source files.

**Comment by rickymagner** [comment]
Thanks for sharing your thoughts! I was able to get some syntax highlighting to work in VSCode (though not autocomplete). I might try out CLion and set it up to be configured with Bazel so that it might be more aware of dependencies for autocompleting. Thanks!
