### ISSUE TITLE
Singularity import issue and possible solution

### ISSUE THREAD

**Issue by YuheCheng62** [google/deepvariant#795]
Thank you for writing such a fantastic tool and I appreciate the effort! I was running DeepVariant on HPC using singularity and encountered the following error:

Traceback (most recent call last):
  File "/home/miniforge3/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/miniforge3/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/miniforge3/miniforge3/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

Which happens to resemble a number of the previous issues, like #782, and #132. It seems like at least in my case, the error is due to the fact that PYTHONPATH is set to a local path and passed to singularity, leading to numpy version incompatibility. In my case, I managed to resolve the issue by simply unset PYTHONPATH, and I can imagine that running singularity with --cleanenv may resolve a number of similar issues. 

I am sorry if the solution has already be proposed in some previous issues, but I am wondering if this fix can also be mentioned in documentation, as there may be more users having the issue since singularity is pretty much the only option to run containers on HPC without root privileges.

**Comment by lucasbrambrink** [comment]
Thanks for providing a solution! Adding something to the documentation seems like a good idea, I'll keep you posted if and when we make changes.

**Comment by lucasbrambrink** [comment]
The documentation has been updated and will be included in our next release. Thank you very much for the suggestion!
