### ISSUE TITLE
Training data v0.6

### ISSUE THREAD

**Issue by ksw9** [google/deepvariant#80]
We are interested in training DeepVariant and are wondering the source of the training data for v0.6? Could you direct us towards the BAM files for the replicates listed under WGS models in the [usage guide](https://github.com/google/deepvariant/blob/r0.6/docs/deepvariant-details.md)?

Thank you!

**Comment by HuanhuanXia-Fudan** [comment]
Dear DeepVariant team,

We are also interested in training and trying different models for DeepVariant. Could you please kindly let us know more details about sequencing and alignment data you are using to generate the labeled examples?

Look forward to hearing from you!

Thank you!

**Comment by pichuan** [comment]
Thanks for your interest in trying out training!

Currently, DeepVariant is trained using a combination of public and non-public data, as described in the release notes for each version. For public data sources, like Genome in a Bottle or BaseSpace, we encourage you to download the data directly from the original source. 

I'm currently working on a list of the public data sources that we're using. We'll plan to release that information in the next release.

**Comment by pichuan** [comment]
Hi,
In the latest release we added this page:
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-details-training-data.md
As well as a training tutorial:
https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-tpu-training-case-study.md

If you decide to train a model, we would love to hear your feedback as detailed as you are willing to provide us. Thank you!
