### ISSUE TITLE
I am confusion about your deep learning architecture.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#801]
I learned about the the input of Inceptionv3's channel number is 3, but your input's channel is 6 or more. So how do to deal with it? Are you changed the first layer of inceptionv3? 

Thank you!

**Comment by lucasbrambrink** [comment]
Thank you for the question! 

Take a look at how we instantiate InceptionV3 [keras_modeling.py](https://github.com/google/deepvariant/blob/r1.6.1/deepvariant/keras_modeling.py#L275-L364). The [input_shape](https://github.com/google/deepvariant/blob/r1.6.1/deepvariant/train_inceptionv3.py#L278-L280) is inferred from the examples. InceptionV3 can handle any number of channels provided you are not using the `imagenet` classifier. 

[documentation](https://keras.io/api/applications/inceptionv3/) mentions 3 channels if you are using the `imagenet` preset, and load the weights pre-trained on ImageNet. This is not the case if you set `weights=None`.

**Comment by pioneer-pi** [comment]
@lucasbrambrink  Thank you for your reply! Now If I want to use the pretrained Inceptionv3 of deepvariant, where can i get the model?

**Comment by lucasbrambrink** [comment]
Sure! You can find the checkpoints for each sequencing technology at `gs://deepvariant/models/DeepVariant/1.6.1/checkpoints/`. For example, the model for Illumina data can be found at `gs://deepvariant/models/DeepVariant/1.6.1/checkpoints/wgs/deepvariant.wgs.ckpt`. These models are mounted in our [Dockerfile](https://github.com/google/deepvariant/blob/r1.6.1/Dockerfile#L156-L200)

Take a look at our [custom training case study](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-training-case-study.md#advanced-case-study-train-a-customized-snp-and-small-indel-variant-caller-for-bgiseq-500-data) if you want to learn more.
