### ISSUE TITLE
Restarting from post process variants step of deeptrio

### ISSUE THREAD

**Issue by gevro** [google/deepvariant#803]
Hi, With the latest version of deeptrio, downloaded 3 days ago, run on singularity cpu, I got an out of memory error (despite having 64 Gb ram) on the post-process step of two parents.

Since the run took 3 days, I don't want to have to start from scratch.

I found the tmp directory containing all the make_examples files.

How do I restart from the postprocess variants step?

**Comment by gevro** [comment]
Thanks! Got it to work.

**Comment by gevro** [comment]
Also, after that step, is there anything else I need to run or is that the last step of the pipeline?

**Comment by lucasbrambrink** [comment]
`postprocess_variants` is the last step to generate a VCF. 

There's an additional optional step to generate a [vcf stats report](https://github.com/google/deepvariant/blob/r1.6.1/scripts/run_deeptrio.py#L269-L276) for further analysis, but like I said it is optional.
