### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by navishkumarb** [google/deepvariant#807]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:

**Describe the issue:**
Am getting the error as "Fatal Python error: Segmentation fault"

**Setup**
  - Operating system: Ubuntu 22.04.2 LTS 
  - DeepVariant version: 1.6.1
  - Installation method (Docker, built from source, etc.): Docker 
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) Its a Pabcio CLR data. Read Input is provided in Fastq format and reference in FASTA format. 

**Steps to reproduce:**
  - Command: sudo docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=PACBIO \
  --ref=/input/RILWLs1.fasta \
  --reads=/input/Out.fastq \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir \
  --num_shards=15

  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Yes. Test data works fine. 
![Screenshot from 2024-04-17 12-24-22](https://github.com/google/deepvariant/assets/68117296/41ac66ff-ff52-493f-b18f-f017921caa86)

Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by navishkumarb** [comment]
> **Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:
> 
> **Describe the issue:** Am getting the error as "Fatal Python error: Segmentation fault"
> 
> **Setup**
> 
> * Operating system: Ubuntu 22.04.2 LTS
> * DeepVariant version: 1.6.1
> * Installation method (Docker, built from source, etc.): Docker
> * Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?) Its a Pabcio CLR data. Read Input is provided in Fastq format and reference in FASTA format.
> 
> **Steps to reproduce:**
> 
> * Command: sudo docker run 
>     -v "${INPUT_DIR}":"/input" 
>     -v "${OUTPUT_DIR}":"/output" 
>     google/deepvariant:"${BIN_VERSION}" 
>     /opt/deepvariant/bin/run_deepvariant 
>     --model_type=PACBIO 
>     --ref=/input/RILWLs1.fasta 
>     --reads=/input/Out.fastq 
>     --output_vcf=/output/output.vcf.gz 
>     --output_gvcf=/output/output.g.vcf.gz 
>     --intermediate_results_dir /output/intermediate_results_dir 
>     --num_shards=15
> * Error trace: (if applicable)
> 
> **Does the quick start test work on your system?** Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md. Yes. Test data works fine. ![Screenshot from 2024-04-17 12-24-22](https://private-user-images.githubusercontent.com/68117296/323111309-41ac66ff-ff52-493f-b18f-f017921caa86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzcyOTIsIm5iZiI6MTcxMzMzNjk5MiwicGF0aCI6Ii82ODExNzI5Ni8zMjMxMTEzMDktNDFhYzY2ZmYtZmY1Mi00OTNmLWIxOGYtZjAxNzkyMWNhYTg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA2NTYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ZDQ3ZTBmNDFjYWQ4YWQyNmM4MDdmYTJiYjVjNzlhYmI1MDA2NzQxOGY3MjA1ZjU1ODY3ZDUzOTcyMTkyNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gtqyKpmVpHdy0Yw9XgACJqtqoRcB3SuNknzCYOE8y-g)
> 
> Is there any way to reproduce the issue by using the quick start?
> 
> **Any additional context:**

Its a 256GB RAM system.

**Comment by pichuan** [comment]
Hi @navishkumarb ,
It seems like you've marked this issue as closed.
If there's any findings that would be helpful to share with the forum here, please do.

If you have further questions, please feel free to reach out again.

**Comment by navishkumarb** [comment]
Hi 
Hi @pichuan 

Input I have provided was a raw FASTQ read files instead of aligned BAM file. 
So this was causing the error and it worked fine post that. 

Thanks
> Hi @navishkumarb , It seems like you've marked this issue as closed. If there's any findings that would be helpful to share with the forum here, please do.
> 
> If you have further questions, please feel free to reach out again.
