### ISSUE TITLE
Merging vcf files error with glnexus:v1.2.7 

### ISSUE THREAD

**Issue by poddarharsh15** [google/deepvariant#815]
**Have you checked the FAQ?  [](https://github.com/google/deepvariant/blob/r1.6.1/docs/deeptrio-wgs-case-study.md)

**Describe the issue:**
Merging vcf files error.
**Setup**
  - Operating system: working on cluster 
  - DeepVariant version:latest
  - Installation method (Docker):
  - Type of data: (GIAB AshkenazimTrio [HG002,HG003,HG004] analysis.)

**Steps to reproduce:**
  - Command: 
  ```
udocker run \
  -v "${PWD}/output":"/output" \
  quay.io/mlin/glnexus:v1.2.7 \
  /usr/local/bin/glnexus_cli \
  --config DeepVariant_unfiltered \
  /output/HG002.g.vcf.gz \
  /output/HG003.g.vcf.gz \
  /output/HG004.g.vcf.gz \
  | udocker run -i google/deepvariant:deeptrio-"${BIN_VERSION}" \
    bcftools view - \
  | udocker run -i google/deepvariant:deeptrio-"${BIN_VERSION}" \
    bgzip -c > output/HG002_trio_merged.vcf.gz
```
  - Error trace: (if applicable)
  
> Num BCF records read 118736378  query hits 14552613
> [E::bgzf_read_block] Invalid BGZF header at offset 265038798
> [E::bgzf_read] Read block operation failed with error 2 after 0 of 32 bytes
> [E::bgzf_read] Read block operation failed with error 3 after 0 of 32 bytes
> Error: BCF read err

![Screenshot from 2024-05-06 15-00-29](https://github.com/google/deepvariant/assets/45700858/2c6e5565-78aa-4e55-9488-82b2f5f04514)

**Comment by akolesnikov** [comment]
Looks like this is the GLnexus question. Could you please post the question at GLNexus [page ](https://github.com/dnanexus-rnd/GLnexus)
Also, from the log output it looks like GLnexus was completed successfully.

**Comment by pichuan** [comment]
Hi @poddarharsh15 

Actually, can you go back in your log and confirm that DeepTrio runs actually finish correctly?

If I remember correctly, our run_deeptrio one-step script might continue to run the following steps even when previous steps failed.

**Comment by pichuan** [comment]
And, follow up on @akolesnikov 's point, if you have gotten to this point, it would seem like these files should be complete?

```
/output/HG002.g.vcf.gz \
/output/HG003.g.vcf.gz \
/output/HG004.g.vcf.gz \
```

If you can examine those files and confirm, that will be great. (Or look at the log like I mentioned before. But given you have the files, checking the files directly might be easier :))

**Comment by poddarharsh15** [comment]
Hi @pichuan, @akolesnikov,

I'm new to DeepTrio and couldn't locate the log files, but I have intermediate results showing that DeepTrio ran successfully without errors. Additionally, I successfully benchmarked the .vcf files generated by DeepTrio. I've attached screenshots for reference. Your assistance is greatly appreciated.
Thank you

finished log
![Screenshot from 2024-05-07 09-52-02](https://github.com/google/deepvariant/assets/45700858/1f9f1b6d-bdd5-4d5d-87fd-a1416e8b4f22)
![Screenshot from 2024-05-07 09-52-32](https://github.com/google/deepvariant/assets/45700858/1c40eb86-018e-4df7-a290-963dccb767b8)

Benchmark
![Screenshot from 2024-05-07 09-52-59](https://github.com/google/deepvariant/assets/45700858/e98c8307-12ba-4c15-a26a-2323948e8f05)

**Comment by pichuan** [comment]
Hi @poddarharsh15 , it seems like you're certain that the DeepTrio run finished correctly.
In that case, I agree with @akolesnikov 's original assessment that this can be an issue for the downstream glnexus step, which we can't directly support.

One suggestion to try:
If you need to check your run a bit more closely, maybe breaking it down to just running this part first:

```bash
udocker run \
-v "${PWD}/output":"/output" \
quay.io/mlin/glnexus:v1.2.7 \
/usr/local/bin/glnexus_cli \
--config DeepVariant_unfiltered \
/output/HG002.g.vcf.gz \
/output/HG003.g.vcf.gz \
/output/HG004.g.vcf.gz
```

before piping to the next step. Maybe that could help you identify what the errors are coming out from that step?

**Comment by akolesnikov** [comment]
Closing the issue. Feel free to reopen as needed.
