### ISSUE TITLE
 CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by kunmonster** [google/deepvariant#820]
Hi , when i run call_variant , it arises this warn which means can't use the gpu,but i can make sure that the tensorflow can use  the gpu.There are the screen shots of the warn and the existence of the gpu.

- the gpu existence
![image](https://github.com/google/deepvariant/assets/71956115/367b1a98-123c-48fb-b170-3f8e4aae7d30)

```python
tensorflow.test.is_gpu_available()
WARNING:tensorflow:From <stdin>:1: is_gpu_available (from tensorflow.python.framework.test_util) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
2024-05-12 21:36:00.744470: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1639] Created device /device:GPU:0 with 15089 MB memory:  -> device: 0, name: Vega 20, pci bus id: 0000:26:00.0
True
```

- the warn 
![image](https://github.com/google/deepvariant/assets/71956115/246d5cfd-a9b3-4ac5-aea7-bf4c89401c76)

```shell
  warnings.warn(
2024-05-12 21:43:29.067332: E tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
```

  - Operating system: Linux 
  - DeepVariant version: 1.6.1-gpu
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Comment by akolesnikov** [comment]
Hi @kunmonster ,
Could you please provide a command line that you use to run DeepVariant?

**Comment by kunmonster** [comment]
> Hi @kunmonster , Could you please provide a command line that you use to run DeepVariant?

Sorry,the command line is in the top of the second picture. Actually,i run the docker container in interactive mode,then run the call_variants line within the container

**Comment by kunmonster** [comment]
> Hi @kunmonster , Could you please provide a command line that you use to run DeepVariant?

**Comment by akolesnikov** [comment]
Since sometimes warning messages from Tensorflow may be misleading. Could you please try running call_variants and at the same time monitor the GPU load to make sure the GPU is not used?
You can use `watch -n0.5 nvidia-smi` to check the GPU load in real time.

**Comment by kunmonster** [comment]
Happy to see the reply,actually, i run this on hpc and the usage of the gpu is very low , but the cpu and memory usage is extremely high , then i run this command line on my laptop with gtx 1050ti and compare the time of the prediction one batch ,the time in the hpc is longer than my laptop , but the truth is  the performance of the hpc gpu is better than gtx1050ti. So, the gpu don't work. I will post what you want later.Thx!

**Comment by akolesnikov** [comment]
Did you run `tensorflow.test.is_gpu_available()` from the DeepVariant docker?

Could you try the suggestion from this [thread](https://stackoverflow.com/questions/48658204/tensorflow-failed-call-to-cuinit-cuda-error-no-device)

**Comment by kunmonster** [comment]
> Did you run `tensorflow.test.is_gpu_available()` from the DeepVariant docker?

Yes i did , I have posted the result which shows that in python shell the gpu can be identified with tensorflow in the first comment.

> Could you try the suggestion from this [thread](https://stackoverflow.com/questions/48658204/tensorflow-failed-call-to-cuinit-cuda-error-no-device)

Actuallly i have tried to set ` CUDA_VISIBLE_DEVICES=0 ` in System ENV ,it did't work .So I  tried to find the place where sets the value of the env in your code , and want to set the ` CUDA_VISIBLE_DEVICES=0 ` , but i did't find. So ,i turn to ask for your help.

I think the reason why the error occurs may be in your code the value of the ` CUDA_VISIBLE_DEVICES` does't match with my device.

**Comment by pichuan** [comment]
Hi @kunmonster ,
if I understand correctly, we haven't been able to reproduce the issue on our side, therefore it has been difficult for us to help.

I know you've already run `tensorflow.test.is_gpu_available()`. can you also try this and see what you see?

```
sudo docker run --gpus all google/deepvariant:1.6.1-gpu python3 -c "import tensorflow as tf; print(tf.config.list_physical_devices('GPU'))"
```

When I run this on my machine, I see:

```
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
```

Given that your is_gpu_available is True, I think it'll also list something. Just want to double check here.

If there's any other information that you can provide, in order for us to reproduce on our side, please let us know.

**Comment by kunmonster** [comment]
Thanks @pichuan,
I think this problem may be caused by the hpc what i am using,actually the gpus of this hpc are not from nvidia,instead they are made for deeplearning specifically in specific frame, and i can't run docker directly on the hpc. It doesn't matter, i will find another computer with gpu from nvidia to run this . Thx.
