### ISSUE TITLE
Info ONT R10.4.1 data

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#821]
Hi,
I was wondering if the RAW data used to train the ONT model on R10.4.1 chemistry is publicly available. The ones on the GIAB FTP server are all R9.4.1. If so, could you point me to where these files are located?
Thank you in advance for any help :)

**Comment by kishwarshafin** [comment]
Hello,

The ONT R10.4 training data came from the HPRC project. Specifically this bucket: https://s3-us-west-2.amazonaws.com/human-pangenomics/submissions/3b9be4f8-a269-4f89-ab9c-a0a0b0a10af6--UCSC_HG002_R1041_nanopore/HG002_Sheared_R1041/

Hope this helps. Please close the issue if it answers your query.

**Comment by gambalab** [comment]
thank you! :)

**Comment by kishwarshafin** [comment]
The previous one was download link, if you want to see it on the web:

https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=submissions/3b9be4f8-a269-4f89-ab9c-a0a0b0a10af6--UCSC_HG002_R1041_nanopore/HG002_Sheared_R1041/
