### ISSUE TITLE
Error while using deepvariant with a bam file that is phased

### ISSUE THREAD

**Issue by eaooms** [google/deepvariant#823]
Describe the issue:
Hello, i am trying to recreate the steps done in this post: https://google.github.io/deepvariant/posts/2021-02-08-the-haplotype-channel/
I have a bam file with phasing information which a got by running whatshap on the data and now i want use deepvariant for a second time just like the steps in the post.
I have a illumina bam file which i phased with nanopore data.

I run this command:
singularity exec --bind /usr/lib/locale/
docker://google/deepvariant:${BIN_VERSION}
/opt/deepvariant/bin/run_deepvariant
--model_type PACBIO
--ref reference/GRCh38_no_alt_analysis_set.fasta
--reads whatshap/HG003.GRCh38.chr20.haplotagged.bam
--use_hp_information
--output_vcf deepvariant2/output.vcf.gz
--num_shards $(nproc)
--regions chr20

And get this error :
NotImplementedError: The --use_hp_information flag has been deprecated. DeepVariant now phases internally for PacBio mode.

I get what deprecated means but what is the thing i have to do to specify to deepvariant that my bam file is phased because i dont think it is using the haplotagged info in the bam file now?

Setup

DeepVariant version: latest
Installation method : source
Type of data: bam file with phasing information by whatshap

**Comment by pichuan** [comment]
Hi @eaooms ,
Starting in DeepVariant v1.4.0, wehave our read haplotagging built in.

To use the flag you mentioned, please use `BIN_VERSION=1.3.0`. You can read:
https://github.com/google/deepvariant/blob/r1.3/docs/deepvariant-pacbio-model-case-study.md

**Comment by pichuan** [comment]
I'll close this issue now. Please feel free to open as needed.

**Comment by eaooms** [comment]
Where can i find what Deepvariant does with the phasing information in the bam file?

**Comment by pichuan** [comment]
Hi @eaooms , 
DeepVariant adds an additional channel to represent the HP information.
If you have some intermediate output of make_examples available, you can try using https://github.com/google/deepvariant/blob/r1.6.1/docs/show-examples.md to visualize them.

In addition to the blog post, this preprint might provide the information that you need: https://doi.org/10.1101/2023.09.07.556731
