### ISSUE TITLE
gvcf with true depth and not (only) min_dp

### ISSUE THREAD

**Issue by ESDeutekom** [google/deepvariant#826]
Dear team deepvariant, 

I am wondering (I cannot find anything in the documentation) how it would be possible to get the true depth per site in the gvcf file and not only the min_dp. Currently I am converting the gvcf into vcf for comparisons, but is there a way to calculate back what the true depth is for a site by adding some additional output to the gvcf file? 

Kind regards, 
Eva

**Comment by lucasbrambrink** [comment]
Hi Eva,

Thanks for the question. This is convention for gVCF compression. If every depth change creates a new line, the gVCF files will get incredibly large, to the point that it would be larger than the BAM file itself. At that point, it is easier to calculate the read depth using the BAM file. 

In case it is helpful, there is a boolean flag `--include_med_dp` you can pass to `make_examples` as [make_examples_extra_args](https://github.com/google/deepvariant/blob/r1.6.1/scripts/run_deepvariant.py#L195-L203) when calling `run_deepvariant` that will include the median DP observed within the GVCF block rounded to the nearest integer.

Hopefully that helps!

**Comment by ESDeutekom** [comment]
Thank you Lucas for your answer. I understand it is for compression. I think I was looking for a similar function to GATK BP resolution. When you use targets, the output would be reduced by a lot. The gvcf becomes rather useless, since you cannot look at or filter individual sites on depth. Some sites might have a depth well over my threshold, but is filtered because the minimum depth is well under my threshold. I am thinking the median DP will have similar issues.

**Comment by kishwarshafin** [comment]
@ESDeutekom ,

If the purpose of this is filtering, you can run something like https://github.com/brentp/mosdepth to get bp resolution coverage. Then create a bed file based on your requirement. Finally, intersect the VCF file with the bed and it should give you the variants you are looking for.

**Comment by ESDeutekom** [comment]
Dear @kishwarshafin, thank you for the information. 

I opted for samtools depth. It also gives some option filter on base and mapping quality and such, next to target filtering.

**Comment by kishwarshafin** [comment]
@ESDeutekom , great, I will close the issue. Please feel free to reopen if you have further questions.
