### ISSUE TITLE
Use haplotagged bam file with WES model type 

### ISSUE THREAD

**Issue by eaooms** [google/deepvariant#828]
Dear developers, 

I am in the process of seeing if by adding phasing information I can increase the accuracy of my variants.
I have a Illumina haplotagged bam file which i phased with Nanopore data with the WhatsHap phasing tool.

When I run the phased illumina file through deepvariant I obtain the same results as the unphased illumina file. 
I seem to have lost the phasing information in the VCF file that comes out of deepvariant and have no changes between the two VCFs when looking at BCFtools stats function. When running Deepvariant i use the WES model as a parameter

My question now is whether Deepvariant's WES or WGS model does anything with the given phasing information or is it only possible with the PACBIO or ONT_R104 model?

kind regards,
Ewoud

**Comment by pichuan** [comment]
Hi @eaooms ,

Unfortunately, our released DeepVariant Illumina WES or WGS models will not work with phasing information.

This use case could be possible if you collect training data on your own, and train your own model accordingly. But that's an advanced use case that our team won't be able to provide much support.

**Comment by eaooms** [comment]
Thanks for the quick response, 

Is it possible to include phasing information with the ONT or PACBIO model?

**Comment by akolesnikov** [comment]
Yes, it is possible. In that case you would need to disable internal phasing. `----phase_reads=False`. You can pass this flag through `--make_examples_extra_args` if you use run_deepvariant.py script. With `phase_reads` set to False DeepVariants expects phasing information in `HP` field in the input BAM. Allowed HP values are 0 through 2.

**Comment by eaooms** [comment]
Thank you for this information, I have run deepvariant with this additional parameter: `--make_examples_extra_args=phase_reads=False` but do not see the phasing information in the vcf afterwards.
Is the phasing information not preserved after running deepvariant in the vcf?

**Comment by kishwarshafin** [comment]
@eaooms ,

DeepVariant uses the haplotagging information of reads to improve the quality of the variants. It will not produce a phased VCF. If you want to get a phased VCF, please use tools like [margin](https://github.com/UCSC-nanopore-cgl/margin) or [whatshap](https://whatshap.readthedocs.io/en/latest/) on the output of DeepVariant to get a phased VCF.

**Comment by pichuan** [comment]
(We'll add @kishwarshafin 's answer in our clarification in our FAQ in the next release!)
