### ISSUE TITLE
Cannot install latest DeepVariant via Conda

### ISSUE THREAD

**Issue by lok27395** [google/deepvariant#835]
**Describe the issue:**
Cannot install latest DeepVariant via Conda in my new environment

Error prompts, similar to that of #736

If having everything in default, I can have python=2.7 and deepvariant=0.7.0; but cannot update to 1.15 or latest

**Setup**
  - Operating system: CentOS Linux release 7.4.1708 (ssh to university, docker unavailable)
  - DeepVariant version: 0.7.0 installable, but cannot get 1.15 or latest
  - Installation method (Docker, built from source, etc.): conda
  - Type of data: N/A

**Steps to reproduce:**
  - Command:
$ create -n deepvariant python=3.8 (current version 3.8.19)
$ conda install deepvariant

  - Error trace: (if applicable)

> #warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY _- many times_
> warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
> warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY _- many times_
> failed
> 
> LibMambaUnsatisfiableError: Encountered problems while solving:
>   - package deepvariant-0.4.1-np113py27_0 requires python 2.7*, but none of the providers can be installed
> 
> Could not solve for environment specs
> The following packages are incompatible
> ├─ deepvariant is installable with the potential options
> │  ├─ deepvariant [0.10.0|0.7.2|0.8.0|0.9.0] would require
> │  │  └─ tensorflow 1.12.* , which conflicts with any installable versions previously reported;
> │  ├─ deepvariant [0.10.0|1.0.0] would require
> │  │  └─ tensorflow 2.0.* , which conflicts with any installable versions previously reported;
> │  ├─ deepvariant [0.4.1|0.6.0|0.6.1|0.7.0] would require
> │  │  └─ python [2.7* |>=2.7,<2.8.0a0 ], which can be installed;
> │  ├─ deepvariant [0.7.1|0.7.2] would require
> │  │  └─ tensorflow 1.11.* , which conflicts with any installable versions previously reported;
> │  └─ deepvariant [1.0.0|1.1.0|...|1.5.0] would require
> │     └─ tensorflow-estimator 2.0.* , which conflicts with any installable versions previously reported;
> └─ pin-1 is not installable because it requires
>    └─ python 3.8.* , which conflicts with any installable versions previously reported.

Thanks guys.

**Comment by lok27395** [comment]
have also tried instruction by 

> pichuan 

but still the same

**Comment by lucasbrambrink** [comment]
Hi,

Just to make sure I understand the issue: you are able to successfully install DeepVariant 0.7.0 with Python 2.7, but you are unable to install 1.15 or later; the goal is for you to install the latest version of DeepVariant, 1.6.0. 

The relevant error that I see is:
```
deepvariant [1.0.0|1.1.0|...|1.5.0] would require
│ └─ tensorflow-estimator 2.0.* , which conflicts with any installable versions previously reported;
```
Is it possible to resolve this conflict? I will try myself to see if I can get it to work on GCP, and report back.

**Comment by lok27395** [comment]
Hi Lucas,

yes, the only version I can install is DeepVariant 0.7.0.

I tried to install tensorflow-estimator first (v2.13.1) but still have same error as mentioned.

Thanks!

**Comment by pichuan** [comment]
Hi @lok27395 ,
unfortunately, our team doesn't officially support the Conda version. I'll close this issue now.
