### ISSUE TITLE
data resources path

### ISSUE THREAD

**Issue by zyxNo1** [google/deepvariant#842]
Sorry to bother, but could you please provide me with the original path for downloading the data in the exome case study? I am interested in exploring some related data. Thank you very much. 

Here's the code related to the data in case study:
```
HTTPDIR=https://storage.googleapis.com/deepvariant/exome-case-study-testdata
curl ${HTTPDIR}/HG003.novaseq.wes_idt.100x.dedup.bam > input/HG003.novaseq.wes_idt.100x.dedup.bam
```

**Comment by kishwarshafin** [comment]
@zyxNo1 ,

You can find the data here: https://www.biorxiv.org/content/10.1101/2020.12.11.422022v1.abstract
