### ISSUE TITLE
AssertionError: Some objects had attributes which were not restored:

### ISSUE THREAD

**Issue by esraaelmligy** [google/deepvariant#845]
**Describe the issue:**
Hello, I am trying to run the deepvariant RNA model on HG005 data locally (not restricted to chr20 like the Github example) but the model keeps generating this error while running the call_variants.py step

WARNING:tensorflow:From /usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py:1473: NameBasedSaverStatus.__init__ (from tensorflow.python.checkpoint.checkpoint) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
W0626 13:39:06.145823 140632388314944 deprecation.py:350] From /usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py:1473: NameBasedSaverStatus.__init__ (from tensorflow.python.checkpoint.checkpoint) is deprecated and will be removed in a future version.
Instructions for updating:
Restoring a name-based tf.train.Saver checkpoint using the object-based restore API. This mode uses global names to match variables, and so is somewhat fragile. It also adds new restore ops to the graph each time it is called when graph building. Prefer re-encoding training checkpoints in the object-based format: run save() on the object-based saver (the same one this message is coming from) and use that checkpoint in the future.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles__zgkztyv/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 633, in <module>
    app.run(main)
  File "/tmp/Bazel.runfiles__zgkztyv/runfiles/absl_py/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/tmp/Bazel.runfiles__zgkztyv/runfiles/absl_py/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/tmp/Bazel.runfiles__zgkztyv/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 618, in main
    call_variants(
  File "/tmp/Bazel.runfiles__zgkztyv/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 558, in call_variants
    model.load_weights(checkpoint_path).expect_partial()
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/checkpoint/checkpoint.py", line 1047, in assert_consumed
    raise AssertionError(
AssertionError: Some objects had attributes which were not restored: 
    <tf.Variable 'conv2d/kernel:0' shape=(3, 3, 7, 32) dtype=float32, numpy=
    
My knowledge in deep learning models is not the best, so if you could please tell me how to overcome this error, as the RNA model seems to have very promising results for RNA variant calling and i want to use it.

**Setup**
  - Operating system: Ubuntu 20.0
  - DeepVariant version: Latest version 1.6.1
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: GIAB benchmark data used in the deepvariant-rnaseq-case-study.md but not restricted to chr20

**Steps to reproduce:**
  - Command: 
docker run -v "$(pwd):$(pwd)" -w $(pwd) google/deepvariant:latest run_deepvariant --model_type=WES --customized_model=model/model.ckpt --ref=GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta --reads=STAR/Mapping/marked_split.bam --output_vcf=STAR/Mapping/deepvariant.rna.vcf --num_shards=$(nproc)

**Comment by kishwarshafin** [comment]
@esraaelmligy ,

The RNAseq model is trained and released for DeepVariant 1.4.0, please see [this documentation](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-rnaseq-case-study.md#running-deepvariant-rna-seq-on-a-cpu-only-machine) on how to run it.

**Comment by esraaelmligy** [comment]
I changed the version and the run finished went fine thank you. I just have to ask whether using a non-updated version will dramatically affect the results, and if you are planning to do any updates on the RNAseq model soon?

**Comment by kishwarshafin** [comment]
@esraaelmligy ,

The non updated version will not affect the results much. Any updates on RNASeq model is currently unplanned but I can give you an update closer to the next release date. Ideally, yes, we would want to train a new model. I just haven't assessed how much time and effort is required there vs other priorities. I have taken a note and will update you when we make a decision. 

Will close this bug for now. Thank you for confirming that it worked.
