### ISSUE TITLE
I have a question about how deepvariant create the vcf files?

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#846]
Hello, I wonder how do you create the vcf file?  
1. For example, how do deepvariant produce the value of QUAL of each variant?
2.  I see you use p_error while calculating the GQ? What's the p_error and how you get it ?
3. I see Filter filed has value : PASS, RefCall and so on. How did it decided?
4.  And I have no idea about what's  meaning of PL?

A vcf item:
`chr20   61098   .       C       T       48.9    PASS    .       GT:GQ:DP:AD:VAF:PL      0/1:49:34:17,17:0.5:48,0,66`

Thank you!!!

**Comment by kishwarshafin** [comment]
@pioneer-pi please see [how deepvariant works](https://github.com/google/deepvariant?tab=readme-ov-file#how-deepvariant-works) to see that the CNN provides a probability vector which we use to determine genotype likelihoods.


1. QUAL is the minimum probability of the genotype. Please see [here](https://github.com/google/deepvariant/blob/bf9ed7e6de97cf6c8381694cb996317a740625ad/deepvariant/postprocess_variants.py#L467) for details.
2. GQ and qual are synonymous one is just rounded. Please see how [this method](https://github.com/google/deepvariant/blob/bf9ed7e6de97cf6c8381694cb996317a740625ad/deepvariant/postprocess_variants.py#L446) determines both QUAL and GQ.
3. RefCall is called if the QUAL is below a set threshold which is 3. See [here](https://github.com/google/deepvariant/blob/bf9ed7e6de97cf6c8381694cb996317a740625ad/deepvariant/postprocess_variants.py#L387) for details.
4. PL is the genotype likelihoods. See [code](https://github.com/google/deepvariant/blob/bf9ed7e6de97cf6c8381694cb996317a740625ad/third_party/nucleus/io/vcf_conversion.cc#L1038) for details. Also described in header:
```
##FORMAT=<ID=PL,Number=G,Type=Integer,Description="Phred-scaled genotype likelihoods rounded to the closest integer">
```
