### ISSUE TITLE
Deepvariant run too long and fails on giraffe output

### ISSUE THREAD

**Issue by Han-Cao** [google/deepvariant#847]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:
Yes

**Describe the issue:**
I mapped the WGS data to pangenome graph with `vg giraffe`. When calling variant with deepvariant, it takes a very long time on `make_exmaples` and find a huge number of examples (~50X more than my previous data aligned to GRCh38). And finally, deepvariant fails.

**Setup**
  - Operating system: CentOS 7
  - DeepVariant version: 1.6.1
  - Installation method (Docker, built from source, etc.): Singularity
  - Type of data: PCR-free WGS data from 1000 Genomes, CHM13-based pangenome graph

**Steps to reproduce:**
  - Command:
```
singularity run \
        -B /usr/lib/locale/:/usr/lib/locale/ \
        -B $inpath \
        -B $outpath \
        -B ${TMPDIR}:${TMPDIR} \
        -B $(dirname $ref) \
        ~/container/deepvariant.1.6.1.sif \
        /opt/deepvariant/bin/run_deepvariant \
        --model_type=WGS \
        --ref=$ref \
        --reads=${inpath}/${sample}.cram \
        --output_vcf=${outpath}/${sample}.vcf.gz \
        --output_gvcf=${outpath}/${sample}.g.vcf.gz \
        --num_shards=${threads} \
        --intermediate_results_dir ${TMPDIR} \
        --make_examples_extra_args="min_mapping_quality=1,keep_legacy_allele_counter_behavior=true,normalize_reads=true"

```
  - Error trace: (if applicable)
```
I0706 12:06:34.396180 140036894541632 make_examples_core.py:301] Task 16/40: 20600183 candidates (20662757 examples) [6.77s elapsed]
I0706 12:06:34.020470 140496845215552 make_examples_core.py:301] Task 39/40: 20480581 candidates (20541819 examples) [9.70s elapsed]
parallel: This job failed:
/opt/deepvariant/bin/make_examples --mode calling --ref Reference/Human_genome/CHM13/chm13v2.0.fa --reads HG00438.hap48.cram --examples tmp/tmp_HG00438.hap48/make_examples.tfrecord@40.gz --channels insert_size --gvcf tmp/tmp_HG00438.hap48/gvcf.tfrecord@40.gz --keep_legacy_allele_counter_behavior --min_mapping_quality 1 --normalize_reads --task 24

real    1500m24.832s
user    1478m47.340s
sys     6m51.817s

```

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

Deepvariant previously work well with data aligned to linear reference genome. So, I think it could be some issue with pangenome-aligned data. I can share the cram (e.g., chr22) if you would like to test.

**Any additional context:**
Code I used to align to a haplotype sampled pangenome graph:
```
# vg giraffe to align reads to graph
rg="ID:1\tLB:lib_${sample}\tSM:${sample}\tPL:illumina\tPU:lib_${sample}.1"
time \
vg giraffe \
--progress \
--read-group $rg \
--sample ${sample} \
--output-format gam \
-f ${fqpath}/${sample%.hap*}_1_paired.fq.gz \
-f ${fqpath}/${sample%.hap*}_2_paired.fq.gz \
-Z ${gbzpath}/${sample}.gbz \
-t $threads  > ${outpath}/${sample}.gam

# vg surject to convert gam to bam
time \
vg surject \
-F $path_list \
-x ${gbzpath}/${sample}.gbz \
-t $(($threads - 10)) \
--sam-output \
--read-group '1' \
--sample ${sample} \
--prune-low-cplx \
--interleaved \
--max-frag-len 3000 \
${outpath}/${sample}.gam | \
sed 's/CHM13#0#//g' - | \
samtools view -hb - | \
samtools reheader ${outpath}/${sample}.tmp.header.sam - | \
samtools sort --write-index -@ 10 -m 4G -O CRAM --reference $ref -T ${outpath}/${sample}.cram -o ${outpath}/${sample}.cram
```

**Comment by pichuan** [comment]
Hi @Han-Cao ,

from your log, I'm surprised that your make_examples step was making that many examples.
Before it crashed, one shard already made 20480581 examples. And it seems like you have 40 shards.
So, that would mean 20480581*40 = 819,223,240 examples has already been made.

That is a surprising amount of examples! Is there anything unusual about your sample?

Thanks!

**Comment by Han-Cao** [comment]
Hi @pichuan,

The sample is HG00438 from 1000G, which downloaded from
```
/vol1/fastq/ERR398/008/ERR3988768/ERR3988768_1.fastq.gz
/vol1/fastq/ERR398/008/ERR3988768/ERR3988768_2.fastq.gz
```

I tried to reproduce this issue with an 1MB bam file: [HG00438.chr1_1000000_2000000.bam.txt](https://github.com/user-attachments/files/16170832/HG00438.chr1_1000000_2000000.bam.txt) (.txt is only for uploading to github). Deepvariant found 5115 examples on it. Do you think this data is normal?

If that 1MB region looks OK, then I guess this issue might be caused by some complex region in the graph, which cannot be well surjected to the bam file. I need some time to carefully check the data, and maybe is more likely an issue with the pangenome graph or `vg`.

Many thanks.

**Comment by pichuan** [comment]
Hi @Han-Cao , I looked at the BAM file you shared. From my IGV, they certainly do not look like they're mapped correctly to me.

![image](https://github.com/user-attachments/assets/4727d465-cc96-4ca0-a138-63027abee6b6)

Here is a more zoomed-in view:

![image](https://github.com/user-attachments/assets/4363f21f-cb96-4434-8d04-37e8bc8afb2d)

Please check how you map the files. I think the issue was before DeepVariant. Thank you! I'll close this issue now.

**Comment by Han-Cao** [comment]
Hi @pichuan ,

That is because I surjected it to CHM13 not GRCh38. If you switch to CHM13, it is well aligned.

![image](https://github.com/user-attachments/assets/1d35b184-70e3-4d3e-b073-22cb5d849377)

**Comment by pichuan** [comment]
I reopened and can take look next week.

**Comment by pichuan** [comment]
@Han-Cao , I ran on your BAM.

My command is something like:

```bash
docker run \
  -v /home/pichuan/wgs-case-study/input/data:/input \
  -v /home/pichuan/wgs-case-study/output:/output \
  google/deepvariant:1.6.1 \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/chm13v2.0_noY.fa.gz \
  --reads=/input/HG00438.chr1_1000000_2000000.bam \
  --output_vcf=/output/deepvariant.output.vcf.gz \
  --output_gvcf=/output/deepvariant.output.g.vcf.gz \
  --num_shards 64 \
  --logging_dir=/output/logs \
  --intermediate_results_dir /output/intermediate_results_dir \
  --make_examples_extra_args "min_mapping_quality=1,keep_legacy_allele_counter_behavior=true,normalize_reads=true" \
  --report_title test-githubissue \
  --regions chr1:1000000-2000000 \
  --runtime_report
```

Then, I checked how many variants there are:

```
$ zcat deepvariant.output.vcf.gz | grep -v '^#' | wc -l
4748
```

A few thoughts and observations:

1. Looking at IGV, it looks reasonable. (@AndrewCarroll also took a look and agreed)
2. The number of variants in this region didn't seem too unreasonable. 
3. Your BAM is higher coverage, which could also be why more candidates have been made.
4. I have not use CHM13 a lot myself. It is possible that CHM13 has regions that can take DeepVariant make_examples longer time to complete. If you notice specific regions being really slow (which you can use https://github.com/google/deepvariant/blob/r1.6.1/docs/runtime-by-region.md to check), please feel free to report those regions and we can take a closer look from there!
5. For the question of whether you're running Giraffe correctly, I don't think I'm able to help answer that question. I'd encourage you to run your Giraffe+DV setting through something where you have truths for, so you can check hap.py output and see if that's expected. And, to save your time, I recommend running DeepVariant on just one chr (e.g., chr20) to check.

Hope this helps!

**Comment by Han-Cao** [comment]
Hi @pichuan ,

I did some analysis on the bam file and it does have some issue. e.g., no reads can be found in chr2:145Mb-240Mb

After re-aligning the same data to a GRCh38-based graph, deepvariant works well now. The report is attached: [HG00438.hap8.visual_report.html.txt](https://github.com/user-attachments/files/16378354/HG00438.hap8.visual_report.html.txt)

So, it seems the issue is due to the CHM13-based graph not deepvariant.

Thank you so much!

**Comment by pichuan** [comment]
Thanks for the update. Good to know that it works.
