### ISSUE TITLE
Why all the GT of the PASS variant site  is 1/1? use deepsomatic

### ISSUE THREAD

**Issue by DayTimeMouse** [google/deepvariant#848]
Hi,

Why all the GT of the PASS variant site  is 1/1? use deepsomatic.

chr1	91748	.	C	T	10	PASS	.	GT:GQ:DP:AD:VAF:PL	1/1:10:61:48,13:0.213115:9,19,0

The command:

BIN_VERSION="1.6.1"
docker run \
  -v "${INPUT_DIR}":"/input" \
  -v "${OUTPUT_DIR}:/output" \
  google/deepsomatic:"${BIN_VERSION}" \
  run_deepsomatic \
  --model_type=PACBIO \
  --ref=/input/chm13v2.0.fa \
  --reads_normal=/input/hifi_normal.bam \
  --reads_tumor=/input/hifi_tumor.bam \
  --output_vcf=/output/somatic_output_vcf.gz \
  --output_gvcf=/output/somatic_output_g.vcf.gz \
  --sample_name_tumor="tumor" \
  --sample_name_normal="normal" \
  --num_shards=48 \
  --logging_dir=/output/logs \
  --intermediate_results_dir=/output/intermediate_results_dir

Best wishes.

**Comment by pichuan** [comment]
Hi @DayTimeMouse 
Please see https://github.com/google/deepsomatic/issues/16#issuecomment-2214935507 , which points to https://github.com/google/deepsomatic/issues/3

I kept your other question on DeepSomatic open: https://github.com/google/deepsomatic/issues/17 (which I also gave the same answer above. So I'll close this issue.
