### ISSUE TITLE
multiple bams as input?

### ISSUE THREAD

**Issue by ShrutiMarwaha** [google/deepvariant#85]
Hi all,

Does deepvariant accept multiple bams (and index files) as input? There were generated on multiple lanes for same sample. Or should I merge them and provide that as input to deepvariant.

Thanks,
Shruti

Shruti Marwaha, PhD.
Research Engineer,
Stanford Center for Undiagnosed Diseases
Stanford University

**Comment by pichuan** [comment]
Hi Shruti,
DeepVariant does not accept multiple BAM files as input. You'll need to preprocess them into one BAM as input to DeepVariant. Thanks.

**Comment by ShrutiMarwaha** [comment]
Thanks.
Shruti
