### ISSUE TITLE
No vcf output after running

### ISSUE THREAD

**Issue by lok27395** [google/deepvariant#850]
**Describe the issue:**
After running, no VCF is found, the logs however are available

**Setup**
  - Operating system: ubuntu 22.04 (WSL2)
  - DeepVariant version: 1.6.1
  - Installation method (Docker, built from source, etc.): docker
  - Type of data: (I find variant only in chr17 for easier reading and faster speed)
        - input read: aligned HG004 to CHM13 (https://downloads.pacbcloud.com/public/revio/2022Q4/HG004-rep1/)
        - reference genome: CHM13 (https://github.com/marbl/CHM13)

**Steps to reproduce:**
  - Command:
`docker run --volume "/root/deepvariant/input":"/input" --volume "/root/deepvariant/output":"/output" google/deepvariant:"1.6.1" /opt/deepvariant/bin/run_deepvariant --model_type=PACBIO --ref=/input/chm13v2.0.fa --reads=/input/aligntest.bam --regions "chr17" --output_vcf=/output.vcf.gz --output_gvcf=/output.g.vcf.gz --intermediate_results_dir /output/intermediate_results --logging_dir=/output`
 
**Any additional context:**
[make_examples.log](https://github.com/user-attachments/files/16189177/make_examples.log)
[call_variants.log](https://github.com/user-attachments/files/16189180/call_variants.log)
[postprocess_variants.log](https://github.com/user-attachments/files/16189182/postprocess_variants.log)
[vcf_stats_report.log](https://github.com/user-attachments/files/16189186/vcf_stats_report.log)

**Comment by kishwarshafin** [comment]
@lok27395 you mounted the output like this:

```bash
--volume "/root/deepvariant/output":"/output" 
```
But then wrote the output like this:
```bash
--output_vcf=/output.vcf.gz
```

Please change the outputs with correct prefix:
```bash
--output_vcf=/output/output.vcf.gz
```
And they will appear correctly.
