### ISSUE TITLE
ValueError: Reference contigs span 3137161264 bases but only 63025520 bases (2.01%) were found in common among our input files. Check that the sources were created on a common genome reference build.

### ISSUE THREAD

**Issue by pioneer-pi** [google/deepvariant#851]
I want to use deepvariant only on ucsc_hg19's chr20. So I execute:
```
docker run \
  -v "${PWD}":"/input" \
  -v "${PWD}/vg_deepvariant":"/output" \
  google/deepvariant:"${BIN_VERSION}" \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=/input/ucsc_hg19.fa.gz \
  --reads=/output/chr20_aln.sort.bam \
  --regions "chr20" \
  --output_vcf=/output/output.vcf.gz \
  --output_gvcf=/output/output.g.vcf.gz \
  --intermediate_results_dir /output/intermediate_results_dir
```
My bam file is from vg, and I want to use deepvariant to call variant. I check the header of bam and reference, they are matching.
The more detail error information:
`ValueError: Reference contigs span 3137161264 bases but only 63025520 bases (2.01%) were found in common among our input files. Check that the sources were created on a common genome reference build. Contig matches were: 
"chrM" is 16571 bp and IS MISSING, 
"chr1" is 249250621 bp and IS MISSING, 
"chr2" is 243199373 bp and IS MISSING, 
"chr3" is 198022430 bp and IS MISSING, 
"chr4" is 191154276 bp and IS MISSING, 
"chr5" is 180915260 bp and IS MISSING, 
"chr6" is 171115067 bp and IS MISSING, 
"chr7" is 159138663 bp and IS MISSING, 
"chr8" is 146364022 bp and IS MISSING, 
"chr9" is 141213431 bp and IS MISSING, 
"chr10" is 135534747 bp and IS MISSING, 
"chr11" is 135006516 bp and IS MISSING, 
"chr12" is 133851895 bp and IS MISSING, 
"chr13" is 115169878 bp and IS MISSING, 
"chr14" is 107349540 bp and IS MISSING, 
"chr15" is 102531392 bp and IS MISSING, 
"chr16" is 90354753 bp and IS MISSING, 
"chr17" is 81195210 bp and IS MISSING, 
"chr18" is 78077248 bp and IS MISSING, 
"chr19" is 59128983 bp and IS MISSING, 
"chr20" is 63025520 bp and matched, 
"chr21" is 48129895 bp and IS MISSING, 
"chr22" is 51304566 bp and IS MISSING, 
"chrX" is 155270560 bp and IS MISSING, 
"chrY" is 59373566 bp and IS MISSING, 
"chr1_gl000191_random" is 106433 bp and IS MISSING, 
"chr1_gl000192_random" is 547496 bp and IS MISSING, 
"chr4_ctg9_hap1" is 590426 bp and IS MISSING, 
"chr4_gl000193_random" is 189789 bp and IS MISSING, 
"chr4_gl000194_random" is 191469 bp and IS MISSING, 
"chr6_apd_hap1" is 4622290 bp and IS MISSING, 
"chr6_cox_hap2" is 4795371 bp and IS MISSING, 
"chr6_dbb_hap3" is 4610396 bp and IS MISSING, 
"chr6_mann_hap4" is 4683263 bp and IS MISSING, 
"chr6_mcf_hap5" is 4833398 bp and IS MISSING, 
"chr6_qbl_hap6" is 4611984 bp and IS MISSING, 
"chr6_ssto_hap7" is 4928567 bp and IS MISSING, 
"chr7_gl000195_random" is 182896 bp and IS MISSING, 
"chr8_gl000196_random" is 38914 bp and IS MISSING, 
"chr8_gl000197_random" is 37175 bp and IS MISSING, 
"chr9_gl000198_random" is 90085 bp and IS MISSING, 
"chr9_gl000199_random" is 169874 bp and IS MISSING, 
"chr9_gl000200_random" is 187035 bp and IS MISSING, 
"chr9_gl000201_random" is 36148 bp and IS MISSING, 
"chr11_gl000202_random" is 40103 bp and IS MISSING, 
"chr17_ctg5_hap1" is 1680828 bp and IS MISSING, 
"chr17_gl000203_random" is 37498 bp and IS MISSING, 
"chr17_gl000204_random" is 81310 bp and IS MISSING, 
"chr17_gl000205_random" is 174588 bp and IS MISSING, 
"chr17_gl000206_random" is 41001 bp and IS MISSING, 
"chr18_gl000207_random" is 4262 bp and IS MISSING, 
"chr19_gl000208_random" is 92689 bp and IS MISSING, 
"chr19_gl000209_random" is 159169 bp and IS MISSING, 
"chr21_gl000210_random" is 27682 bp and IS MISSING, 
"chrUn_gl000211" is 166566 bp and IS MISSING, 
"chrUn_gl000212" is 186858 bp and IS MISSING, 
"chrUn_gl000213" is 164239 bp and IS MISSING, 
"chrUn_gl000214" is 137718 bp and IS MISSING, 
"chrUn_gl000215" is 172545 bp and IS MISSING, 
"chrUn_gl000216" is 172294 bp and IS MISSING, 
"chrUn_gl000217" is 172149 bp and IS MISSING, 
"chrUn_gl000218" is 161147 bp and IS MISSING, 
"chrUn_gl000219" is 179198 bp and IS MISSING, 
"chrUn_gl000220" is 161802 bp and IS MISSING, 
"chrUn_gl000221" is 155397 bp and IS MISSING, 
"chrUn_gl000222" is 186861 bp and IS MISSING, 
"chrUn_gl000223" is 180455 bp and IS MISSING, 
"chrUn_gl000224" is 179693 bp and IS MISSING, 
"chrUn_gl000225" is 211173 bp and IS MISSING, 
"chrUn_gl000226" is 15008 bp and IS MISSING, 
"chrUn_gl000227" is 128374 bp and IS MISSING, 
"chrUn_gl000228" is 129120 bp and IS MISSING, 
"chrUn_gl000229" is 19913 bp and IS MISSING, 
"chrUn_gl000230" is 43691 bp and IS MISSING, 
"chrUn_gl000231" is 27386 bp and IS MISSING, 
"chrUn_gl000232" is 40652 bp and IS MISSING, 
"chrUn_gl000233" is 45941 bp and IS MISSING, 
"chrUn_gl000234" is 40531 bp and IS MISSING, 
"chrUn_gl000235" is 34474 bp and IS MISSING, 
"chrUn_gl000236" is 41934 bp and IS MISSING, 
"chrUn_gl000237" is 45867 bp and IS MISSING, 
"chrUn_gl000238" is 39939 bp and IS MISSING, 
"chrUn_gl000239" is 33824 bp and IS MISSING, 
"chrUn_gl000240" is 41933 bp and IS MISSING, 
"chrUn_gl000241" is 42152 bp and IS MISSING, 
"chrUn_gl000242" is 43523 bp and IS MISSING, 
"chrUn_gl000243" is 43341 bp and IS MISSING, 
"chrUn_gl000244" is 39929 bp and IS MISSING, 
"chrUn_gl000245" is 36651 bp and IS MISSING, 
"chrUn_gl000246" is 38154 bp and IS MISSING, 
"chrUn_gl000247" is 36422 bp and IS MISSING, 
"chrUn_gl000248" is 39786 bp and IS MISSING, 
"chrUn_gl000249" is 38502 bp and IS MISSING`

**Comment by kishwarshafin** [comment]
@pioneer-pi,

Citing from [this source](https://www.ebi.ac.uk/training/online/courses/human-genetic-variation-introduction/variant-identification-and-analysis/)

**What is variant calling?**
Variant calling is the process by which we identify variants from sequence data (Figure 11).

* Step 1: Carry out whole genome or whole exome sequencing to create **FASTQ** files.
* Step 2: Align the sequences to a reference genome, creating **BAM** or **CRAM** files.
* Step 3: Identify where the aligned reads differ from the reference genome and write to a **VCF** file.

For your issue:
DeepVariant is the software you use in step 3: " Identify where the aligned reads differ from the reference genome and write to a VCF file."

So, if you want to use HG19 reference genome, you have to go back to step 2 and align your fastq file to HG19 reference genome to get a bam where the reads are aligned to HG19 reference. Then if you supply that bam of reads aligned to HG19 and HG19 reference, it will work.

Currently, DeepVariant is saying that you have supplied it with a BAM where reads are **not** aligned to the reference you supplied. So it seems your bam is where reads are aligned to GRCh38 and you supplied HG19 as a reference, so it's not finding the contigs correctly. So, please align the reads to HG19 and provide the correct files and DeepVariant should work.
