### ISSUE TITLE
Error while running tests on Calling variants in non-autosomal contigs

### ISSUE THREAD

**Issue by poddarharsh15** [google/deepvariant#853]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:

**Describe the issue:**
I am having some errors while fetching variants from chrX, Could you please have a look I added a error.txt file for reference.   
Thank you

> INVALID_ARGUMENT: Couldn't fetch bases for reference_name: "chrX" start: 14000 end: 15000

**Setup**
  - Operating system:linux
  - DeepVariant version:latest
  - Installation method (Docker, built from source, etc.):udocker
  - Type of data: test file for checking Calling variants in non-autosomal contigs [this](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-xy-calling-case-study.md)

**Steps to reproduce:**
  - Command:
BIN_VERSION="1.6.1"

```
REF="GRCh38_no_alt_analysis_set.fasta"
BAM="HG002.pfda_challenge.grch38.chrXY.bam"
THREADS=$(nproc)
REGION="chrX chrY"
HAPLOID_CONTIGS="chrX,chrY"
PAR_BED="GRCh38_PAR.bed"

udocker run \
-v "${INPUT_DIR}":"${INPUT_DIR}" \
-v "${OUTPUT_DIR}":"${OUTPUT_DIR}" \
google/deepvariant:"${BIN_VERSION}" \
/opt/deepvariant/bin/run_deepvariant \
--model_type PACBIO \
--ref "${INPUT_DIR}/${REF}" \
--reads "${INPUT_DIR}/${BAM}" \
--output_vcf "${OUTPUT_DIR}/${OUTPUT_VCF}" \
--output_gvcf "${OUTPUT_DIR}/${OUTPUT_GVCF}" \
--num_shards "${THREADS}" \
--haploid_contigs "${HAPLOID_CONTIGS}" \
--par_regions_bed "${INPUT_DIR}/${PAR_BED}" \
--regions "${REGION}" \
--intermediate_results_dir "${OUTPUT_DIR}/${INTERMEDIATE_DIRECTORY}"  
```

- Error trace: 
  
[error.txt](https://github.com/user-attachments/files/16281125/error.txt)

**Comment by kishwarshafin** [comment]
@poddarharsh15, can you please check if the files were downloaded correctly and if their sizes look good. The case studies are designed in a way that you can simply copy-paste the commands and it should work. I just tested the case study and it worked on my end.

**Comment by poddarharsh15** [comment]
It worked thanks for the help :))

**Comment by kishwarshafin** [comment]
@poddarharsh15 ,

You are using `--regions=chrX_10001-44821.bed \` I see. Which means you will run DV on this region only. Can you remove this line and see if it fixes it?
