### ISSUE TITLE
[E::vcf_parse_format] Incorrect number of FORMAT fields at 1:19355\n. 

### ISSUE THREAD

**Issue by ShrutiMarwaha** [google/deepvariant#86]
Hi all,

I have encountered the following error when running deepvaraint on a wgs file. ‘[E::vcf_parse_format] Incorrect number of FORMAT fields at 1:19355\n.’ I have googled it but I am not sure what is causing this issue and how to resolve it. I will appreciate your help. 
I have attached the full error log, bash and yaml files. 

error:
  code: 10
  message: |-
    11: Docker run failed: ASS"\ncalls {\n  info {\n    key: "AD"\n    value {\n      values {\n        int_value: 8\n      }\n      values {\n        int_value: 7\n      }\n    }\n  }\n  info {\n    key: "DP"\n    value {\n      values {\n        int_value: 15\n      }\n    }\n  }\n  info {\n    key: "GQ"\n    value {\n      values {\n        int_value: 12\n      }\n    }\n  }\n…….
……….
………..Reading /mnt/data/output/gs/gbsc-gcp-project-udn-dev-deep-variant/UDN631726/gvcf/UDN631726_deepVariant_v0.6.1.g.vcf with NativeVcfReader\nI0806 01:37:07.984452 140434439055104 postprocess_variants.py:593] Writing output to VCF file: /mnt/data/output/gs/gbsc-gcp-project-udn-dev-deep-variant/UDN631726/gvcf/UDN631726_deepVariant_v0.6.1.g.vcf\nI0806 01:37:08.052251 140434439055104 genomics_writer.py:118] Writing /mnt/data/output/gs/gbsc-gcp-project-udn-dev-deep-variant/UDN631726/gvcf/UDN631726_deepVariant_v0.6.1.g.vcf with NativeVcfWriter\n**[E::vcf_parse_format] Incorrect number of FORMAT fields at 1:19355\n.** See logs at gs://gbsc-gcp-project-udn-dev-deep-variant/UDN631726/gvcf/deepvariant_staging_folder/logs/']].

Operation ID: ENqznd7QLBi1jMjtufCo3ckBIK2c48-5AyoPcHJvZHVjdGlvblF1ZXVl

Best,
Shruti

Shruti Marwaha, PhD.
Research Engineer,
Stanford Center for Undiagnosed Diseases
Stanford University

[UDN631726_gvcf_error_08052018.log](https://github.com/google/deepvariant/files/2263671/UDN631726_gvcf_error_08052018.log)
Since GIT does not allow me to attach .sh or .yaml files, I am saving them as text files and attaching.
[deepvariant_v0.6.1_UDN631726.yaml.txt](https://github.com/google/deepvariant/files/2263680/deepvariant_v0.6.1_UDN631726.yaml.txt)
[deepvariant_v0.6.1_UDN631726.sh.txt](https://github.com/google/deepvariant/files/2263674/deepvariant_v0.6.1_UDN631726.sh.txt)

**Comment by cmclean** [comment]
Hi Shruti,

I notice in your .yaml that both the --outfile and --gvcf_outfile flags are set to "${OUTPUT_BUCKET}"/"${OUTPUT_FILE_NAME}" . These flags should have different names set, as they are two distinct output files.

Please let us know if rerunning the pipeline with the distinct names does not resolve your issue.

regards,
Cory

**Comment by ShrutiMarwaha** [comment]
Thanks Cory. I will fix that and re-run. I shall update you if that resolves the issue.

Thanks,
Shruti

**Comment by ShrutiMarwaha** [comment]
Hi Cory,

After fixing the issue, the run completed without any error. 
My yaml file has arguments for both vcf and gvcf but different values.
--outfile "${OUTPUT_BUCKET}"/"${OUTPUT_FILE_NAME}" \
--gvcf_outfile "${OUTPUT_BUCKET}"/"${OUTPUT_GVCF_FILE_NAME}" \

However, the vcf generated by deepvariant seems to be small in size (495M), given that this is WGS. The vcf file that I received for this case from a clinical bioinformatics core that runs GATK3 is (2.7GB). I am wondering if I am missing something in my script for running deepvariant.
I am observing this trend on couple of other WGS cases for which I ran deepvariant.

I have attached my bash and yaml file for your reference. 

Will appreciate any suggestions/pointers from you.

Best,
Shruti

**Comment by cmclean** [comment]
Hi Shruti,

Glad to hear that the renaming fixed the prior error. I don't see the bash or yaml files attached, but I'm curious how many variants are present in the VCF output file and how that compares to the GATK3 output (and verifying that you're running on human samples). File sizes can vary due to additional annotations added or compression (and compression level) applied to the result. On a Unix system you can find the number of lines in the output VCF file using

wc -l "${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME}"

or, if it's gzip compressed,

zcat "${OUTPUT_BUCKET}/${OUTPUT_FILE_NAME}" | wc -l

**Comment by ShrutiMarwaha** [comment]
Thanks Cory for the quick response. 
Sorry that I forgot to attach the files last night. 
[deepvariant_v0.6.1_UDN631726.sh.txt](https://github.com/google/deepvariant/files/2303047/deepvariant_v0.6.1_UDN631726.sh.txt)
[deepvariant_v0.6.1_UDN631726.yaml.txt](https://github.com/google/deepvariant/files/2303048/deepvariant_v0.6.1_UDN631726.yaml.txt)

Yes, I am working with human samples.
I looked into the number of variants in deepvariant and gatk3 vcfs.
bcftools view -H UDN631726/UDN631726_deepVariant_v0.6.1.vcf | wc -l #Deepvaraint 6464222
bcftools view -H UDN631726-SL126751.vcf | wc -l #gatk3 9482899

Thanks,
Shruti

**Comment by ShrutiMarwaha** [comment]
Hi Cory,

I think I know why the file size of deepvariant and gatk3 vcfs are so different. The bioinformatics core vcf that is generated using gatk3 has a lot more reference calls in the vcf than deepvariant. 

If I filter out all homozygous-reference variants and also FILTER!="PASS", the number of SNVs and INDELS are comparable in both vcfs.

Thanks,
Shruti
