### ISSUE TITLE
What is deepvariant trained on?

### ISSUE THREAD

**Issue by ejc043** [google/deepvariant#860]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:
Yes.

**Describe the issue:**

Sorry, this might be a very naive question but I believe this isn't addressed in the 2018 publication. What dataset(s) is/are the deepvariant method trained on? I understand for the 2016 truth challenge, deepvariant was trained on the HG001 GIAB reference. Is this also true for the current standard deepvariant method?

**Comment by pichuan** [comment]
Hi @ejc043 , please take a look at https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-details-training-data.md, which contains some more information about our training data of each version.

**Comment by ejc043** [comment]
Thank you so much!! This is very helpful. I will close the issue :~)
