### ISSUE TITLE
DeepVariant Channel clarification

### ISSUE THREAD

**Issue by ejc043** [google/deepvariant#861]
Thank you for the wonderful tool + great user support! i'm wondering if someone might be able to clarify channel 5 (read supports variant) vs channel 6 (base differs from ref). 

Is the purpose of channel 6 to capture the context of the putative (centered) variant with reference to other mismatches on the same read? While channel 5 counts pileups with the putative (centered) variant?

**Comment by kishwarshafin** [comment]
@ejc043 , 

Channel 5, read supports variants highlight each read that supports the allele we are trying to predict.
Channel 6, base differs from ref highlights all the bases, irrespective of alleles that do not agree with the reference at that position.

Channel 5 captures read status vs reference against the proposed allele while channel 6 captures the base status against the reference irrespective of the allele proposed.

**Comment by pichuan** [comment]
Hi @ejc043 , hopefully your question is answered.
I'll close this issue now.
