### ISSUE TITLE
Info Singularity

### ISSUE THREAD

**Issue by gambalab** [google/deepvariant#862]
I would like to try to make a custom singularity version of deepvariant in which is integrated with some custom scripts, do you know where I could find the singularity recepie of deepvariant? It would be a good starting point for me.

Thank you in advance for any suggestion,

**Comment by akolesnikov** [comment]
Hi @gambalab,

We don't officially support Singularity container. But, you may check [this issue](https://github.com/google/deepvariant/issues/812#issuecomment-2076206716) where all the step to build and run with Singularity are described. Hope it helps.
