### ISSUE TITLE
dealing with chimeric alignments

### ISSUE THREAD

**Issue by alisamatisse** [google/deepvariant#863]
hello, 

sorry if this question is dumb or the answer is obvious. 
is there a plausible explanation on how deepvariant treats chimeric reads? 
I tried deepvariant on filtered .bam files (after `samtools view -h -F 2048`) and before that step w/o filtering, and the number of found variants is exactly the same before/after. just to check if I am not doing something weird, I also used bcftools, and the results for the numbers of called variants were affected. is deepvariant not considering chimeric reads? 

thank you for creating and supporting deepvariant,
alisa

**Comment by alisamatisse** [comment]
ah, forgot to mention, I filtered chimeric reads because I had around 60% of them in every tested sample, was curious how much it affects my results (using samplix enrichment + pacbio hifi)

**Comment by akolesnikov** [comment]
Hi @alisamatisse,

I'm not sure what `samtools view -h -F 2048` does. DeepVariant does not do any special processing for chimeric reads. What reads are used from the input BAM is controlled by the following flags: 
* `--keep_duplicates` default to False
* `--keep_supplementary_alignments` default to False
* `--keep_secondary_alignments` default to False
* `--min_mapping_quality` depends on the data, for PacBio it is set to 1

Variants are created for all positions where there are at least two reads support an alt allele.

**Comment by alisamatisse** [comment]
Hi @akolesnikov, very helpful answer, I appreciate it. 🫡
