### ISSUE TITLE
Question about RNA-seq

### ISSUE THREAD

**Issue by SirKuikka** [google/deepvariant#864]
This is from DeepVariant's documentation.

"For somatic data or any other samples where the genotypes go beyond two copies of DNA, DeepVariant will not work out of the box because the only genotypes supported are hom-alt, het, and hom-ref."

Does the same apply to the RNA-seq model of DeepVariant? If a mutation has a low VAF is it predicted as hom-ref?

Because in RNA-seq, low VAF doesn't necessarily mean the variant is hom-ref in the genome. 

### In RNA-seq:
- **Expression Levels**: RNA-seq measures gene expression, so the VAF of a mutation depends on the expression of the mutant and wild-type alleles. If a gene is highly expressed in some cells and not others, or if only one allele is expressed (allele-specific expression), the VAF may be skewed.
- **Variable Expression**: The VAF in RNA-seq data can be influenced by tissue-specific expression, transcriptional noise, or RNA degradation, making it less consistent compared to DNA-seq.
- **Allelic Imbalance**: In RNA-seq, you might observe allelic imbalance due to factors like imprinting or preferential expression of one allele, further complicating the interpretation of VAF.

**Comment by kishwarshafin** [comment]
Hi @SirKuikka, 

So the RNA-seq model we support is to identify germline variants through RNA-seq data. Details of that can be found in: https://academic.oup.com/bioinformaticsadvances/article/3/1/vbad062/7197031.

Similar to whole genome sequencing, if you are trying to identify Somatic variants with RNA-seq our model possibly won't be sensitive enough. For somatic variant calling we have DeepSomatic that you can try but we currently don't support an RNA-seq model for that.

**Comment by SirKuikka** [comment]
Hi,

So if there would be a rare somatic variant with e.g. 0.5 VAF, would that be classified as germline or something else? I'm just trying to understand what happens if there are mutations that are not true germline mutations. Can the tool really detect only germline mutations and not somatic mutations?

**Comment by kishwarshafin** [comment]
@SirKuikka ,

DeepVariant will try to "genotype" each candidate variant observed. Currently it does not have the ability to differentiate between "somatic" vs "germline". If a variant has high allele frequency then the likelihood to be classified as "het" or "hom-alt" is high. However, DeepVariant does not use strict heuristics for such classifications so it is difficult to answer what would happen to such variants. However, rare variant detection with high-sensitivity has been reported with DeepVariant (https://www.nature.com/articles/s41525-021-00227-3).

**Comment by pichuan** [comment]
Hi @SirKuikka ,
Hopefully your questions are answered. I'll close this issue now.

**Comment by SirKuikka** [comment]
![image-6](https://github.com/user-attachments/assets/b5d5ea7b-a8d5-4f61-8fc7-bafdcd002707)

I have one more question. How can VAF for a PASS mutation be sometimes close to 0 if it's germline? This is VAF distribution for an RNA-seq sample.
