### ISSUE TITLE
Running with Conda

### ISSUE THREAD

**Issue by lynnjo** [google/deepvariant#865]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.6.1/docs/FAQ.md**:
Yes
**Describe the issue:**
This isn't a code problem, but rather a documentation issue.  I've run DeepVariant via your docker with success.  To integrate it with our project I would like to install it via conda.  I was able to do that but it isn't clear how to run deep variant.  Do you have documentation/examples of what commands to send?  

When using docker, we invoke the google/deepvariant:1.6.1 image and send it the command "/opt/deepvariant/bin/run_deepvariant" with appropriate arguments.  What do we run when using conda?  

Note the docs/deepvariant-quick-start.md has examples for docker (very useful and they work with our data) but nothing for conda.

**Setup**
  - Operating system: linux
  - DeepVariant version: 1.5.0 (latest from conda)
  - Installation method (Docker, built from source, etc.): conda
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?)

**Steps to reproduce:**
  - Command:
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r1.6/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

Do you have plans to update conda with the latest deepvariant version?  It is still at 1.5.0.  Thanks

**Comment by akolesnikov** [comment]
Hi @lynnjo,

You may check [PacBio case study](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-pacbio-model-case-study.md) which uses Conda.

**Comment by lynnjo** [comment]
Thanks for the response @akolesnikov .  I must be missing something.  From your PacBio case study link above, I see conda being used to setup samtools, but deepvariant is still run via singularity.  Is it possible to run deepvariant only through conda, or is docker/singularity always required?  

singularity exec --bind /usr/lib/locale/ \
  docker://google/deepvariant:${BIN_VERSION} \
    /opt/deepvariant/bin/run_deepvariant \
    --model_type PACBIO \
    --ref reference/GRCh38_no_alt_analysis_set.fasta \
    --reads input/HG003.GRCh38.chr20.pFDA_truthv2.bam \
    --output_vcf deepvariant_output/output.vcf.gz \
    --num_shards $(nproc) \
    --regions chr20

**Comment by akolesnikov** [comment]
Please refer to [this](https://github.com/google/deepvariant/issues/736) issue that contains some information on Conda.
Unfortunately, we don't support Conda and there is no documentation on how to install through Conda.

**Comment by pichuan** [comment]
Hi @lynnjo , as @akolesnikov mentioned, we don't officially support Conda. I'll close this issue now.
