### ISSUE TITLE
Deepvariant Structural Variants for ONT

### ISSUE THREAD

**Issue by DineshRavindraRaju** [google/deepvariant#874]
Hi All,

When using the DeepVariant model type ONT_R104, does it also call structural variants (SVs), specifically ones between 0 and 30bp in length? We observe tools such as Sniffles and CuteSV typically identify SVs with a minimum length of 30bp, while Clair3 can detect SVs up to 50bp.

Thank you!

**Comment by kishwarshafin** [comment]
@DineshRavindraRaju, DeepVariant is a small variant caller and we do not train our models against the SV truth set. Generally SVs are defined to be variants that are 50bp+, so DeepVariant will not identify those. However, the INDEL length limit for DeepVariant is 50bp, so you can potentially see some variants called upto that range.
