### ISSUE TITLE
Mitochondial contig variants

### ISSUE THREAD

**Issue by sounkou-bioinfo** [google/deepvariant#875]
Hi,

I am opening this issue to follow up an issue already mentioned here https://github.com/google/deepvariant/issues/366 regarding calling of variants in the initial and last bases of the human mitochondria. Wanted to know if solutions exist for this issue or one should opt for specialized callers in the meantime.

Thank you

**Comment by kishwarshafin** [comment]
hi @sounkou-bioinfo,

Thank you for bringing up this issue. We have not worked on this specifically but I will try to give this a shot in our next release. It's a reasonable request and we may have the right logics to fix this in the next release.

**Comment by sounkou-bioinfo** [comment]
Thank you for this response dear  @kishwarshafin,
Will be looking forward for the coming release.
Cheers
