### ISSUE TITLE
Retraining DeepVariant without trios data?

### ISSUE THREAD

**Issue by desmodus1984** [google/deepvariant#878]
Hi,
I am doing a genomic analysis of bats, and I have WGS for about 13 individuals but with unknown ancestry or relatedness, many from different populations.
I read that DeepVariant is one of the best genotype-callers, but I would like to consult first about the reliability and confidence on calling variants on a non-human system (yet mammalian..??). I read the blog about doing the mosquito-specific model, but the problem, as stated, is that I don't have trios data to train a model, nor I think that I can get it (nor samples or money), which is a very hard request.
I would appreciate a lot your comments and suggestions on what can I do, or if DeepVariant can confidently call variants.

Thanks;

**Comment by pichuan** [comment]
Hi @desmodus1984 ,
For many of the non-human applications, we see many use cases where people just apply our release models. 
I think directly using our model would be a good enough start for your downstream application. If you have some way to evaluate (e.g., Mendelian violation), then you can do some comparison to assess how good the calls are.

If you have trio data, you can try to run DeepTrio (also using our release model) , which I think will be more accurate.

**Comment by desmodus1984** [comment]
Hi,
I would like to know how should I preprocess my samples to generate the bam files, since perhaps DeepVariant might never more or less preprocessing.
I have short-read data, and I plan to:
1. Merge the reads that overlap, and then map the nonoverlapping reads and the merged ones separately, and then combine the two sam files. Do I need to add any additional parameters during mapping with bwa-mem2?
2. Then convert the combined sam, to bam, and then coordinate-sort it. Should I filter the reads during conversion, like using a minimum mapping quality, or just proceed with all?
3. Next, I used to mark duplicate reads and eliminate them.

Thanks for your comment and suggestions.

**Comment by kishwarshafin** [comment]
@desmodus1984, I think in your process of creating the truth, you will dilute a lot of lineage information. Among the samples you have, do you have generational information among the sample? As in, can you tell which samples can be considered as ancestors vs which are children?

**Comment by kishwarshafin** [comment]
Ok, then this would probably be my approach:

1) Call variants individually on all of the samples indepedently (not using a trio caller, use DeepVariant or something) and create a combined gVCF using glnexus. Set parameters like minimum depth of 15 and GQ 20. Then find blocks that you can use as "confident regions".

2) Pick a few samples and apply the confident regions on them and see if you get mostly variants with GQ>=20 with them. At this point you may need to make sure they are not falling within an SV for some samples. This gives you truth VCFs.

3) Assess the F1-score of current DeepVariant using your truth vcf and bed and see how it looks.

Finally train a model and see if the F1-score improves. I am sure there are better ways to do this, but, this would be the simplest and least blocking path for this experiment.

**Comment by desmodus1984** [comment]
Hi,

Thanks for the reply, but it doesn't address my question.
My doubt is about how to generate the bam file for doing the variant calling.

For the checking/validation approach, I would like to ask a few questions.

> Ok, then this would probably be my approach:
> 
> 1. Call variants individually on all of the samples indepedently (not using a trio caller, use DeepVariant or something) and create a combined gVCF using glnexus. Set parameters like minimum depth of 15 and GQ 20. Then find blocks that you can use as "confident regions".

I did medium coverage sequencing based on some literature, but since my species might have high genetic diversity I used depth higher than recommended (1x), about ~10X per individual.
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0079667
https://onlinelibrary.wiley.com/doi/10.1111/mec.12105
https://pubmed.ncbi.nlm.nih.gov/34250668/

Then, I can't use the minimum depth you suggest of 15; my data should be good quality, hence GQ of 20 is fine, but depth of 15 is not achievable.

> 2. Pick a few samples and apply the confident regions on them and see if you get mostly variants with GQ>=20 with them. At this point you may need to make sure they are not falling within an SV for some samples. This gives you truth VCFs.
I am new in Bioinformatics, could you suggest a program to use to find those "confident blocks". I can't think of any program for doing it.
I have short-reads not long-reads, hence finding SV is not very reliable. Any suggestion on how to check if a variant falls within a SV?

> 3. Assess the F1-score of current DeepVariant using your truth vcf and bed and see how it looks.
> 
> Finally train a model and see if the F1-score improves. I am sure there are better ways to do this, but, this would be the simplest and least blocking path for this experiment.

As mentioned before, I do not have trios data. @pichuan , Is it possible to train a model without trios data?

**Comment by pichuan** [comment]
Hi @desmodus1984 ,

Fundamentally, training a DeepVariant requires truth data (truth variants and confident regions).
The core question here is: **Would you be able to get truth data for the bats you're studying**?

I quickly looked through your most discussion with @kishwarshafin .
I believe @kishwarshafin has been trying to give you some tips on some ways to construct truth. Note that this is an advanced topic. We don't expect most of our users to train DeepVariant models, or to construct truth data.

However, if you do have truth data (truth variants and confident regions), you should be able to follow the documentation https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-training-case-study.md to try to train a model.

From your description above, I still think the best way to proceed is to directly use DeepVariant release models. Once you have the callsets, try to evaluate the calls first. Even if you plan to train a model, it'll be good to have those baseline metrics available, so you know whether your trained model is working or not.

Does this help? If I'm misunderstanding your question, let me know.

**Comment by desmodus1984** [comment]
Hi,

Yes, my main question has not been addressed, it is about how to make the bam files for DeepVariant.

"DeepVariant is a deep learning-based variant caller that takes aligned reads (in BAM or CRAM format)"

The documentation doesn't say anything about how to make it/them.
For instance, one can filter reads based on mapping quality- which is not mentioned in the workflow of GATK, or mark PCR duplicates and also remove them.
For example, GATK needs read group information like sample ID, sequencing technology, etc.


Juan Pablo Aguilar

________________________________
From: Pi-Chuan Chang ***@***.***>
Sent: Friday, September 20, 2024 6:52:36 PM
To: google/deepvariant ***@***.***>
Cc: Aguilar Cabezas, Juan Pablo ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [google/deepvariant] Retraining DeepVariant without trios data? (Issue #878)

Use caution with links and attachments.

Hi @desmodus1984<https://github.com/desmodus1984> ,

Fundamentally, training a DeepVariant requires truth data (truth variants and confident regions).
The core question here is: Would you be able to get truth data for the bats you're studying?

I quickly looked through your recent discussion with @kishwarshafin<https://github.com/kishwarshafin> .
I believe @kishwarshafin<https://github.com/kishwarshafin> has been trying to give you some tips on some ways to construct truth. Note that this is an advanced topic. We don't expect most of our users to train DeepVariant models, or to construct truth data.

However, if you do have truth data (truth variants and confident regions), you should be able to follow the documentation https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-training-case-study.md to try to train a model.

From your description above, I still think the best way to proceed is to directly use DeepVariant release models. Once you have the callsets, try to evaluate the calls first. Even if you plan to train a model, it'll be good to have those baseline metrics available, so you know whether your trained model is working or not.

Does this help? If I'm misunderstanding your question, let me know.

**Comment by AndrewCarroll** [comment]
Hi @desmodus1984 

For short-read sequencing, we generally recommend BWA MEM. We've also observed that minimap2 in short read mode works fairly well. There is no need to additionally filter based on mapping quality as that is already a parameter within DeepVariant. For short read (WGS and WES) presets, this already applies a minimum mapping quality threshold of 5.

We don't observe any meaningful difference with or without duplicate marking, so we tend not to recommend that, but it's certain;y fine to add. DeepVariant doesn't require additional read group information either, though we add RGID and RGSM to be able to do things like populate the VCF header appropriately.
