### ISSUE TITLE
Question about intermediate_results

### ISSUE THREAD

**Issue by 0809zheng** [google/deepvariant#887]
Hello,

I have learned that DeepVariant is three steps at runtime.
To better understand DeepVariant, I want to know if there is a way to parse the output file of call_variants like the output file of make_examples ([Visualizing DeepVariant examples](https://github.com/google/deepvariant/blob/r1.6.1/docs/visualizing_examples.ipynb)), so that it becomes human readable instead of a binary string like below.

```
tf.Tensor(b'\nc2\x01T:\x01AZQ\x12\n\n\x02DP\x12\x04\n\x028\x1c\x12\x0e\n\x02AD\x12\x08\n\x028\x15\n\x028\x04\x12\x12\n\x03VAF\x12\x0b\n\t\x11\x92$I\x92$I\xc2?:\x14\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01J\tHG001_10Xh\xf7Nr\x011\x80\x01\xf6N\x12\x03\n\x01\x00\x1a\x18\x00\x00\x00\x00\xb6\xf8\xef?\x00\x00\x00@\x9e\x0fH?]F\xb5\xb9\x86a$?', shape=(), dtype=string)
```

Sorry for the interruption!

**Comment by kishwarshafin** [comment]
Hi @0809zheng ,

Currently, there is not solution provided by us to look at call variants output. However, call variants output go to postprocess variants and that converts the calls into a VCF which you can look into.

**Comment by 0809zheng** [comment]
Thank you very much for your comment, I will close this issue.
