### ISSUE TITLE
Call variant from bam file which includes methylation tags (MM/ML)

### ISSUE THREAD

**Issue by timizeng** [google/deepvariant#888]
Dear developers; 

Thanks for the great tool for variant calling. I use deepvariant 1.6.1 for small variant calling from picbio HIFI data (Revio system).  For HIFI data, there are two ways to get the input bam for deepvariant. The first, like we do in NGS data analysis, extracting  fastq reads from raw HIFI bam and  mapping the fastq reads to reference genome, eg. T2TCHM13v2, then get the input bam  ( fastq-mapping bam ) ```sample.pbmm2.bam```

```bash

bam2fastq -o sample.fastq raw.bam
pbmm2 align CHM13.fa sample.fastq sample.pbmm2.bam --preset HIFI

##
run deepvarint with sample.pbmm2.bam 

```

The second, mapping from bam data with methylation signal to reference genome directly (bam-to-bam mapping) , ```sample.pbmm2.jasmine.bam```

```bash

jasmine raw.bam raw.jasmine.bam  # get 5mC methylation informations
pbmm2 align CHM13.fa raw.jasmine.bam sample.pbmm2.jasmine.bam --preset HIFI  # bam-to-bam mapping, keep methylation tags in bam file

##
run deepvarint with sample.pbmm2.jasmine.bam

```

The first way bam for small variant calling makes no mistakes. But considering the following methylation analysis also needs to map reads to reference genome,  so if it is suitable for using mapped bam with methylation tags to call small variant, we only need to map once, this can save time and computational resources. So my question is, is that OK for us to use bam with methylation tags as the input of deepvariant? Is the performance difference between using ```fastq-mapping bam``` and ```bam-to-bam mapping bam```?

best, 

Wilson

**Comment by armintoepfer** [comment]
1. PacBio encourages to use `pbmm` on unaligned HiFi BAM files.
2. DeepVariant ignores MM/ML tags.

There's no need to map twice, proceed with your `bam-to-bam` workflow.
