### ISSUE TITLE
Is deepvariant appropriate for my data. 

### ISSUE THREAD

**Issue by abosco4406** [google/deepvariant#889]
I am currently looking to call very small minor variants (e.g. less than 1%) using super deep HiFi data with ~8000 coverage for pseudomonas aeruginosa, is deep variant appropriate to use in this case? If so are there any options/flags/parameters that should be set a particular way?

**Comment by pichuan** [comment]
Hi @abosco4406 , 
DeepVariant is a germline variant caller, so it's not suitable for this use case.

You can look at DeepSomatic: https://github.com/google/deepsomatic , but it's also not exactly the same as your use case which has very high coverage input data.
