### ISSUE TITLE
Build_and_test dis not work neither the binaries.

### ISSUE THREAD

**Issue by solokopi** [google/deepvariant#89]
Hi, i am new to deepvariant and kind of learning some programming languages too as a beginner,  i try to run these commands  on my ubuntu 16.04 and had the following errors, both with Build_and_test.sh, Build-prereq.sh. please i need help on how to fix these errors and get deepvariant running. thank you.

[sudo] password for solokopi: 
+ source settings.sh
++ export DV_USE_PREINSTALLED_TF=0
++ DV_USE_PREINSTALLED_TF=0
++ export TF_CUDA_CLANG=0
++ TF_CUDA_CLANG=0
++ export TF_ENABLE_XLA=0
++ TF_ENABLE_XLA=0
++ export TF_NEED_CUDA=0
++ TF_NEED_CUDA=0
++ export TF_NEED_GCP=1
++ TF_NEED_GCP=1
++ export TF_NEED_GDR=0
++ TF_NEED_GDR=0
++ export TF_NEED_HDFS=0
++ TF_NEED_HDFS=0
++ export TF_NEED_JEMALLOC=0
++ TF_NEED_JEMALLOC=0
++ export TF_NEED_MKL=0
++ TF_NEED_MKL=0
++ export TF_NEED_MPI=0
++ TF_NEED_MPI=0
++ export TF_NEED_OPENCL=0
++ TF_NEED_OPENCL=0
++ export TF_NEED_OPENCL_SYCL=0
++ TF_NEED_OPENCL_SYCL=0
++ export TF_NEED_S3=0
++ TF_NEED_S3=0
++ export TF_NEED_VERBS=0
++ TF_NEED_VERBS=0
++ export TF_CUDA_VERSION=8.0
++ TF_CUDA_VERSION=8.0
++ export CUDA_TOOLKIT_PATH=/usr/local/cuda
++ CUDA_TOOLKIT_PATH=/usr/local/cuda
++ export TF_CUDNN_VERSION=6
++ TF_CUDNN_VERSION=6
++ export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ DV_BAZEL_VERSION=0.15.0
++ export DEEPVARIANT_BUCKET=gs://deepvariant
++ DEEPVARIANT_BUCKET=gs://deepvariant
++ export DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ export DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ export DV_TF_NIGHTLY_BUILD=0
++ DV_TF_NIGHTLY_BUILD=0
++ [[ 0 = \1 ]]
++ export DV_CPP_TENSORFLOW_TAG=r1.9
++ DV_CPP_TENSORFLOW_TAG=r1.9
++ export DV_GCP_OPTIMIZED_TF_WHL_VERSION=1.9.0
++ DV_GCP_OPTIMIZED_TF_WHL_VERSION=1.9.0
++ export DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=1.9.0
++ DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=1.9.0
++ export DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=1.9.0
++ DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=1.9.0
++ export DV_GPU_BUILD=0
++ DV_GPU_BUILD=0
++ export DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ export GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.9.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.9.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ export GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ export GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ export DV_INSTALL_GPU_DRIVERS=0
++ DV_INSTALL_GPU_DRIVERS=0
+++ which python
++ export PYTHON_BIN_PATH=/usr/bin/python
++ PYTHON_BIN_PATH=/usr/bin/python
++ export USE_DEFAULT_PYTHON_LIB_PATH=1
++ USE_DEFAULT_PYTHON_LIB_PATH=1
++ export 'DV_COPT_FLAGS=--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings'
++ DV_COPT_FLAGS='--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings'
+ bazel
build_and_test.sh: line 39: bazel: command not found
+ PATH=/home/solokopi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
+ [[ 0 = \1 ]]
+ bazel test -c opt --copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings deepvariant/...
Unexpected error reading .blazerc file '/home/solokopi/Desktop/deepvariant-r0.7/../tensorflow/tools/bazel.rc'
solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ 

solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ sudo bash build-prereq.sh
[sudo] password for solokopi: 
========== Load config settings.
========== [2018年 08月 24日 星期五 19:30:03 CST] Stage 'Install the runtime packages' starting
========== Load config settings.
========== [2018年 08月 24日 星期五 19:30:03 CST] Stage 'Misc setup' starting
Hit:1 http://mirrors.aliyun.com/ubuntu xenial InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu xenial-updates InRelease                                                            
Get:3 http://mirrors.aliyun.com/ubuntu xenial-backports InRelease [107 kB]                                                 
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                               
Hit:5 http://ppa.launchpad.net/webupd8team/java/ubuntu xenial InRelease                                                    
Hit:6 http://dl.google.com/linux/chrome/deb stable Release                                                                 
Hit:7 http://mirrors.aliyun.com/ubuntu xenial-security InRelease                                             
Err:9 http://packages.cloud.google.com/apt cloud-sdk-xenial InRelease                                                      
  Cannot initiate the connection to packages.cloud.google.com:80 (2404:6800:4008:802::200e). - connect (101: Network is unreachable) [IP: 2404:6800:4008:802::200e 80]
Fetched 107 kB in 12min 0s (148 B/s)                        
Reading package lists... Done
N: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-xenial/InRelease  Cannot initiate the connection to packages.cloud.google.com:80 (2404:6800:4008:802::200e). - connect (101: Network is unreachable) [IP: 2404:6800:4008:802::200e 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sudo is already the newest version (1.8.16-0ubuntu1.5).
The following packages were automatically installed and are no longer required:
  libllvm5.0 linux-headers-4.13.0-36 linux-headers-4.13.0-36-generic linux-image-4.13.0-36-generic linux-image-extra-4.13.0-36-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
N: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
========== [2018年 08月 24日 星期五 19:42:05 CST] Stage 'Update package list' starting
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Failed to fetch http://packages.cloud.google.com/apt/dists/cloud-sdk-xenial/InRelease  Cannot initiate the connection to packages.cloud.google.com:80 (2404:6800:4008:801::200e). - connect (101: Network is unreachable) [IP: 2404:6800:4008:801::200e 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-i386/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/google-cloud-sdk.list:1 and /etc/apt/sources.list.d/google-cloud-sdk.list:2
========== [2018年 08月 24日 星期五 19:54:08 CST] Stage 'Install development packages' starting
Reading package lists... Done
Building dependency tree       
Reading state information... Done
pkg-config is already the newest version (0.29.1-0ubuntu1).
unzip is already the newest version (6.0-20ubuntu1).
zip is already the newest version (3.0-11).
curl is already the newest version (7.47.0-1ubuntu2.8).
zlib1g-dev is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
The following packages were automatically installed and are no longer required:
  libllvm5.0 linux-headers-4.13.0-36 linux-headers-4.13.0-36-generic linux-image-4.13.0-36-generic linux-image-extra-4.13.0-36-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
N: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
========== [2018年 08月 24日 星期五 19:54:08 CST] Stage 'Install python packaging infrastructure' starting
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-wheel is already the newest version (0.29.0-1).
python-dev is already the newest version (2.7.12-1~16.04).
python-pip is already the newest version (8.1.1-2ubuntu0.4).
The following packages were automatically installed and are no longer required:
  libllvm5.0 linux-headers-4.13.0-36 linux-headers-4.13.0-36-generic linux-image-4.13.0-36-generic linux-image-extra-4.13.0-36-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
N: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.0)
========== [2018年 08月 24日 星期五 19:54:09 CST] Stage 'Install python packages' starting
Requirement already satisfied: contextlib2 in /usr/local/lib/python2.7/dist-packages (0.5.5)
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (1.1.6)
Requirement already satisfied: sortedcontainers==1.5.3 in /usr/local/lib/python2.7/dist-packages (1.5.3)
Requirement already satisfied: intervaltree in /usr/local/lib/python2.7/dist-packages (2.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python2.7/dist-packages (from intervaltree) (1.5.3)
Requirement already satisfied: mock>=2.0.0 in /usr/local/lib/python2.7/dist-packages (2.0.0)
Requirement already satisfied: pbr>=0.11 in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0) (4.2.0)
Requirement already satisfied: funcsigs>=1; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0) (1.0.2)
Requirement already satisfied: six>=1.9 in /usr/local/lib/python2.7/dist-packages (from mock>=2.0.0) (1.11.0)
Requirement already satisfied: numpy==1.14 in /usr/local/lib/python2.7/dist-packages (1.14.0)
Requirement already satisfied: requests>=2.18 in /usr/local/lib/python2.7/dist-packages (2.19.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.18) (2018.8.13)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.18) (3.0.4)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.18) (1.23)
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.18) (2.7)
Requirement already satisfied: scipy==1.0 in /usr/local/lib/python2.7/dist-packages (1.0.0)
Requirement already satisfied: numpy>=1.8.2 in /usr/local/lib/python2.7/dist-packages (from scipy==1.0) (1.14.0)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python2.7/dist-packages (4.1.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0) (0.4.4)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0) (0.2.2)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0) (1.11.0)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0) (0.11.3)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0) (3.4.2)
Requirement already satisfied: crcmod>=1.7 in /usr/local/lib/python2.7/dist-packages (1.7)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (1.11.0)
Requirement already satisfied: sklearn in /usr/local/lib/python2.7/dist-packages (0.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python2.7/dist-packages (from sklearn) (0.19.2)
Requirement already satisfied: pandas in /usr/local/lib/python2.7/dist-packages (0.23.4)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from pandas) (1.14.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /usr/local/lib/python2.7/dist-packages (from pandas) (2.7.3)
Requirement already satisfied: pytz>=2011k in /usr/local/lib/python2.7/dist-packages (from pandas) (2018.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil>=2.5.0->pandas) (1.11.0)
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (5.4.7)
Requirement already up-to-date: google-api-python-client in /usr/local/lib/python2.7/dist-packages (1.7.4)
Requirement already satisfied, skipping upgrade: httplib2<1dev,>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client) (0.11.3)
Requirement already satisfied, skipping upgrade: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client) (3.0.0)
Requirement already satisfied, skipping upgrade: google-auth-httplib2>=0.0.3 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client) (0.0.3)
Requirement already satisfied, skipping upgrade: six<2dev,>=1.6.1 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client) (1.11.0)
Requirement already satisfied, skipping upgrade: google-auth>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client) (1.5.1)
Requirement already satisfied, skipping upgrade: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.4.1->google-api-python-client) (3.4.2)
Requirement already satisfied, skipping upgrade: cachetools>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.4.1->google-api-python-client) (2.1.0)
Requirement already satisfied, skipping upgrade: pyasn1-modules>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from google-auth>=1.4.1->google-api-python-client) (0.2.2)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from rsa>=3.1.4->google-auth>=1.4.1->google-api-python-client) (0.4.4)
========== [2018年 08月 24日 星期五 19:54:15 CST] Stage 'Install TensorFlow pip package' starting
Skipping tf-nightly as it is not installed.
Skipping tensorflow as it is not installed.
Skipping tf-nightly-gpu as it is not installed.
Skipping tensorflow-gpu as it is not installed.
Installing Google Cloud Platform optimized CPU-only TensorFlow wheel
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:04 --:--:--     0
curl: (56) GnuTLS recv error (-54): Error in the pull function.
solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ 

solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ sudo bash build_release_binaries.sh
[sudo] password for solokopi: 
build_release_binaries.sh: line 39: bazel: command not found
build_release_binaries.sh: line 43: bazel: command not found
solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$

**Comment by pichuan** [comment]
From the log, it seems like the issue is that `bazel` was not installed.
After you run `build-prereq.sh`, can you try typing in `bazel` as a command and see if it exits?
And, if install bazel failed for you, can you paste the part of log of how the installation failed for you?

By the way, is there a reason why you want to build your own binaries? In the latest instructions, we moved to using docker directly. I'm curious whether that worked for you or not. Would love to know if there's a reason to prefer building your own binaries.

**Comment by solokopi** [comment]
@pichuan thank you for your prompt response, i ran bazel as you instructed and and got the following error 
solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ bazel
Unexpected error reading .blazerc file '/home/solokopi/Desktop/deepvariant-r0.7/../tensorflow/tools/bazel.rc'

And i tried the installation and got this:

solokopi@solokopi-All-Series:~$ sudo apt-get install bazel
Reading package lists... Done
Building dependency tree       
Reading state information... Done
N: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unable to locate package bazel

**Comment by solokopi** [comment]
@pichuan thank you for your prompt response, i ran bazel as you instructed and and got the following error solokopi@solokopi-All-Series:~/Desktop/deepvariant-r0.7$ bazelUnexpected error reading .blazerc file '/home/solokopi/Desktop/deepvariant-r0.7/../tensorflow/tools/bazel.rc'
And i tried the installation and got this:
solokopi@solokopi-All-Series:~$ sudo apt-get install bazelReading package lists... DoneBuilding dependency tree       Reading state information... DoneN: Ignoring file 'google-chrome.list.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extensionE: Unable to locate package bazel

   On Friday, August 24, 2018, 8:40:23 AM PDT, Pi-Chuan Chang <notifications@github.com> wrote:  
 
 
From the log, it seems like the issue is that bazel was not installed.
After you run build-prereq.sh, can you try typing in bazel as a command and see if it exits?
And, if install bazel failed for you, can you paste the part of log of how the installation failed for you?

By the way, is there a reason why you want to build your own binaries? In the latest instructions, we moved to using docker directly. I'm curious whether that worked for you or not. Would love to know if there's a reason to prefer building your own binaries.

**Comment by pichuan** [comment]
Hi,
if you run `build-prereq.sh`, it should have installed it for you. This section is relevant:
https://github.com/google/deepvariant/blob/r0.7/build-prereq.sh#L88

But if that somehow didn't work for you, you can directly use the instructions on bazel's page:
https://docs.bazel.build/versions/master/install-ubuntu.html#install-with-installer-ubuntu

I would still recommend using our docker image instead of building your own binaries!! If you do that, you don't even need to install bazel!

**Comment by solokopi** [comment]
so, had been finding my ways around it but still. please can you give me more information on how to use the docker image, because the bazel installation is not just working out for me. thank you i so much appreciate.

**Comment by solokopi** [comment]
@pichuan thank you so much for your help on this, running it via docker is easier but i experienced some challenges  pulling the deepvariant container from the docker hub, which i presume is a proxy issue, i think i need a vpn because i am in china and google domains are blocked. trying to install a vpn on my ubuntu.

**Comment by pichuan** [comment]
@solokopi since you're already on Ubuntu 16, you can also try using the binaries that we built.
You can just get it from this zip file:
https://github.com/google/deepvariant/releases/download/v0.7.0/deepvariant.zip
which has the binaries and the model files.

You'll need to run `run-prereq.sh` first to set up your machine. But that will not require installing bazel.
Please let me know if that works for you!

**Comment by pichuan** [comment]
It seems like not having connection to "storage.googleapis.com" is the issue. And it seems like it's trying to get an optimized tensorflow wheel.
What if you try with `DV_USE_GCP_OPTIMIZED_TF_WHL=0` ?

**Comment by solokopi** [comment]
i still get the same previous errors.

**Comment by solokopi** [comment]
i still get the same previous errors.

**Comment by pgrosu** [comment]
@solokopi What country is the `solokopi-All-Series` host are you trying to access the `storage.googleapis.com` domain from?  Do you have root access on that machine?  If you cannot access the domain, try to get some VPN access on your machine that would allow you access to the `storage.googleapis.com` domain.

**Comment by solokopi** [comment]
thank you @pgrosu please could it had been same  vpn problem with this docker pulling command?

Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 64.233.187.82:443: i/o timeout
