### ISSUE TITLE
Recommendations for variant call from long-read RNA-seq

### ISSUE THREAD

**Issue by camelest** [google/deepvariant#890]
**Describe the issue:**
Thank you so much for the great tool. 

I'm working on a heterozygous mouse long-read RNA-seq dataset from PacBio and would like to perform variant call + phasing at read-level. I'm wondering whether you have some recommendations regarding the points below:
- I'm currently using `--model_type=PACBIO` with the bam files processed with `gatk SplitNCigarReads`. Does this model consider RNA editing? Or should I use `--model_type=WES`? I saw some discussions mentioning WES model considers RNA-editing in https://github.com/google/deepvariant/issues/775
- Is there anyway that I could integrate the known variants from genomic data into the variant calling? Or should it be integrated after `DeepVariant` variant call at vcf-level?

**Setup**
  - Operating system: Ubuntu 2.20
  - DeepVariant version: v1.6.1
  - Installation method (Docker, built from source, etc.): singularity
  - Type of data: PacBio HiFi, mm10, long-read RNA-seq data

**Steps to reproduce:**
  - Command:
```
singularity run -B /usr/lib/locale/:/usr/lib/locale/ docker://google/deepvariant:1.6.1 \
/opt/deepvariant/bin/run_deepvariant \
--model_type=PACBIO \
--ref=GRCm38.primary_assembly.genome.fa \
--reads=SNCR.bam \
--output_vcf=output.vcf.gz \
--num_shards 16
```

Thank you so much for your kind help!

**Comment by AndrewCarroll** [comment]
Hi @camelest 

Thanks for the issue. We have trained a DeepVariant isoseq model specifically for the type of data you have (I presume you have done: splitNCigarReads + FlagCorrection). We're planning to make that available to everyone soon. If you like, we can give you a custom model for this application in advance. If so, please email awcarroll@google.com and I can send you the files.

**Comment by camelest** [comment]
Hi, @AndrewCarroll,

Thank you so much for your kind offer. That would be really helpful.
I will send an email at the address.

Best,
