### ISSUE TITLE
License of the DeepVariant model

### ISSUE THREAD

**Issue by sanchit-misra** [google/deepvariant#891]
Hi,

Thank you for this great work!
I just wanted to learn about the license under which the Deepvariant model is shared?

**Comment by kishwarshafin** [comment]
Hi,

The license is here: https://github.com/google/deepvariant/blob/r1.6.1/LICENSE

**Comment by sanchit-misra** [comment]
Hi @kishwarshafin, 
As far as I understand, the license is for the DeepVariant software. Is the same license applicable for the DeepVariant model?

**Comment by kishwarshafin** [comment]
@sanchit-misra , yes, the license extends to the models.

**Comment by sanchit-misra** [comment]
Great, thank you for your quick response!
