### ISSUE TITLE
Variant not called although obvious in IGV

### ISSUE THREAD

**Issue by hagen-wende** [google/deepvariant#892]
Hello,

I have the issue that two obvious variations are not called. This is WGS nanopore sequencing of a transgenic mouse. The region in question is alien sequence (human for the most part) that was introduced in the genome, so these reads connect to a certain region in the genome. There are three variations in the region and only one is called:
![image](https://github.com/user-attachments/assets/857acbd1-991d-423a-a7f2-ccbaa5268ac3)

This is my command (version 1.6.1 or 1.5.0 give the same result) :

```
docker run \
     -v "${INPUT_DIR}":"/input" \
     -v "${OUTPUT_DIR}":"/output" \
     google/deepvariant:"${BIN_VERSION}" \
     /opt/deepvariant/bin/run_deepvariant \
     --model_type=ONT_R104 \
     --ref=/input/$FASTA_FILE \
     --reads=/input/$BAM_FILE \
     --output_vcf=/output/output.vcf.gz \
     --output_gvcf=/output/output.g.vcf.gz \
     --regions "my_region" \
     --intermediate_results_dir /output/intermediate_results_dir \
     --num_shards=$(nproc) \
     --postprocess_variants_extra_args="debug_output_all_candidates=ALT" \
     --make_examples_extra_args="vsc_min_count_snps=2,vsc_min_fraction_snps=0.06,vsc_min_count_indels=2,vsc_min_fraction_indels=0.06"
```

I initially thought it might be this issue [https://github.com/google/deepvariant/issues/366](url) but the borders are more than 110 bp away. So is there any way to tackle this issue?

**Comment by hagen-wende** [comment]
this is everything that is in the vcf, so the deviations are not picked up at all. I is just one line with the 5' deviation. If I include other genomic region, thatn I do see more variations there, but for this region it is not recognized at all.
![image](https://github.com/user-attachments/assets/cb092f42-5285-48f5-b2c8-dc1f9590e9c2)

[output.vcf.txt](https://github.com/user-attachments/files/17303859/output.vcf.txt)

However both positions (3948 and 3949) show up in the output.g.vcf
[output.g.vcf.txt](https://github.com/user-attachments/files/17303928/output.g.vcf.txt)

![image](https://github.com/user-attachments/assets/408893bd-27a6-48ac-9f6c-4260a96741c9)

**Comment by kishwarshafin** [comment]
@hagen-wende ,

Thank you for looking into this. In your use-case, variant calling would be extremely difficult as mapping is difficult. Also, you are operating at 5x coverage. We only see the performance of ONT that are considered to be good from 15x. With that said, you can use DeepVariant create alleles for your use. Just drop the values under the threshold and all alleles will be reported so it at least gives you some idea of where the variants could be.

**Comment by hagen-wende** [comment]
well 5x coverage is in part because I just look at one allele here and it is also underrepresented, our overall WGS coverage is usually between 20-30x.
I will also think of how to deal with this issue, but it is at least good to know, where the issue is. I can still align against the transgene in the genomic context and call the variants for this alignment and then do a separate alignment against the entire genome and call variants outside the transgene (if I need it).
Thanks!
