### ISSUE TITLE
ATAC-seq

### ISSUE THREAD

**Issue by westonelison** [google/deepvariant#895]
Hi!

Any advice for running deepvariant on single-cell ATAC-seq data? I assumed RNA-seq would be most similar but that is still quite different.

Thanks!

**Comment by AndrewCarroll** [comment]
Hi @westonelison ,

Thank you for the question. We have experimented with single cell models, but not with ATAC seq specifically. I think the most similar model should be the RNAseq model. I don't have an instinct for how this might perform.
