### ISSUE TITLE
Very slow performave for make_example

### ISSUE THREAD

**Issue by Lionward** [google/deepvariant#903]
I am running deepvariant using singularity:

I already tested it on the provided test files.

singularity run  --bind $bam_PATH/:/bam --bind $REFPATH:/ref deepvariant_1.6.1.sif  \
/opt/deepvariant/bin/run_deepvariant  --model_type=PACBIO  --reads=/bam/HG002.SequelII.merged_15kb_20kb.pbmm2.GRCh38.haplotag.10x.bam --ref=/ref/GCA_000001405.15_GRCh38_no_alt_analysis_set.fa \
--output_vcf variants_HG002.vcf.gz --logging_dir calls/deepvariant/GRCh38/NA12886_HG002/ --num_shards 10 &

I was wondering what is the expected time for deepvariant on CCS reads?

**Comment by kishwarshafin** [comment]
Please see https://github.com/google/deepvariant/blob/r1.6.1/docs/metrics.md page for details on expected runtime. The runtimes reported here are on `n2-standard-64` GCP instances with 64 vCPUs.

**Comment by Lionward** [comment]
Thanks for the fast reply! That answers my question.
