### ISSUE TITLE
Is it possible to run deepvariant in discreet stages with discreet resource requests?

### ISSUE THREAD

**Issue by CanWood** [google/deepvariant#905]
Hi folks,

Our users are running deepvariant on our HPC and resource requests are proving quite tricky for them as different stages of the pipeline seem to have different resource needs.  This leaves execution nodes essentially idle for much of the time of the jobs' running.  In the two days runtime you can see below that a user who has asked for 48 cpus doesn't use most of the cores for most of the time:

![Image](https://github.com/user-attachments/assets/c631a80d-a7b3-435a-ac50-97a1743f7638)

```
singularity run deepvariant_1.6.1.sif /opt/deepvariant/bin/run_deepvariant \
    --model_type ONT_R104 \
    --ref /path/to/their/reference.fasta \
    --reads /path/to/their/input.bam \
    --sample_name unique_name \
    --output_vcf /path/to/their/unique_name.vcf.gz \
    --output_gvcf /path/to/their/unique_name.g.vcf.gz \
    --num_shards 48
```
Is there a way that each stage of the pipeline with discreet resource requests so that the bits that can be cleanly parallelized can go in one job submission and the stages that don't can be in separate jobs/commands, to avoid having requested and reserved resources being idle?

Cheers

**Comment by pichuan** [comment]
Hi @CanWood , DeepVariant has multiple stages, as you observed.

If you ran with the `--dry_run=true` flag, the command above will instead just printing out the commands for each of the stages.
(We mentioned this in the https://github.com/google/deepvariant?tab=readme-ov-file#how-to-run-deepvariant section)

That way, you can adjust how to you want to run each of the stages. You could even run them on different machines if you like.

**Comment by CanWood** [comment]
Thank you, @pichuan .  I'll direct the users to your response. 

Cheers
