### ISSUE TITLE
Germline variant calling from amplicon sequencing

### ISSUE THREAD

**Issue by joowkim** [google/deepvariant#906]
Dear dev team,

I'd like to know if deepvariant supports germline variant calling from amplicon data. I found this answer, and wanted to know if there's any parameters to change in order to address amplicon sequencing data.

https://github.com/google/deepvariant/issues/535#issuecomment-1104202858

> Short answer: Yes, try the "WES" model.
Long answer: DeepVariant isn't designed to work on super high coverage, so amplicon sequencing sometimes will produce way too many reads in each region. DeepVariant will only be able to show a random sample of the 95 reads at each putative variant locus to the model.
Also just to confirm this is still germline sequencing, right? Not somatic or trying to capture variants present in less than about half the reads -- these don't work with DeepVariant.

Best,
JKim

**Comment by akolesnikov** [comment]
Hi @joowkim,

Yes, you should use the same parameters as for the WES model.

**Comment by joowkim** [comment]
Thanks!
