### ISSUE TITLE
report error when call variants based on RNA-seq data

### ISSUE THREAD

**Issue by ChenDepp** [google/deepvariant#909]
hello @pichuan 
    When I run deepvariants to identify variants based on RNA-seq data, the command is as follows

```
docker run -it --rm -u `id -u`:`id -g` -v /calculate:/calculate -w `pwd` google/deepvariant:latest /opt/deepvariant/bin/run_deepvariant --model_type=WGS --customized_model=/calculate/home/user/zhangtianyuan/Project/00.dv/model/model.ckpt --ref=Saccharomyces_cerevisiae.fa --reads=T2-3.sorted.bam --output_vcf=T2-3.vcf.gz --intermediate_results_dir output/intermediate_results_dir --num_shards=40
```
it report error as below
![Image](https://github.com/user-attachments/assets/39a9ee10-7430-4fe1-889d-9d0d527a3e09)
I don't know how to debug based on the error message, So I have to ask you for help

**Comment by AndrewCarroll** [comment]
Hi @ChenDepp 

The error message here indicates that the parameters to make examples is creating an image with 7 input channels (which is standard for the WGS model), but the custom model you provided was trained with 6 input channels. 

Can you tell me where your custom model came from? (e.g. either how you trained it or which case study you got it from)? That will help understand how to give the right make examples command for it.

**Comment by AndrewCarroll** [comment]
Hi @ChenDepp 

I was talking with Pi-Chuan and she reminded me that the RNA-Seq model was trained with DeepVariant v1.4, which was before we added one additional input channel. 

To run the model and solve your problem, you should specify the DeepVariant version as v1.4.0, which matches the training for that model. For an example, see how the command in the [RNA Case study](https://github.com/google/deepvariant/blob/r1.6.1/docs/deepvariant-rnaseq-case-study.md) page specifies the version.

That should enable you to run the model.

**Comment by ChenDepp** [comment]
@AndrewCarroll
I will try again as you said, thanks for your help
Have a nice day

**Comment by kishwarshafin** [comment]
@ChenDepp thanks, if you face any difficulty after you tried, please feel free to reopen the issue.
