### ISSUE TITLE
Retraining DV with custom channels

### ISSUE THREAD

**Issue by rickymagner** [google/deepvariant#910]
Hi folks, thanks for the new release! I was curious if there were still plans to make retraining a bit easier for users, as I think there was a discussion previously that this would be a goal for 1.7 (which seems to have been skipped). Currently I know there's a somewhat difficult way to edit some C files to add new channels, but I was wondering if there's still a goal to make that into a command line API to add extra channels from a custom set of alignment fields/tags.

Thanks!

**Comment by kishwarshafin** [comment]
Hi @rickymagner ,

Please follow https://github.com/google/deepvariant/blob/r1.8/docs/deepvariant-training-case-study.md, 

In the new version you can now set channels by providing a parameter `--channel_list` (please see [here](https://github.com/google/deepvariant/blob/r1.8/docs/deepvariant-training-case-study.md#training-set)). You can find the list of opt channels [here](https://github.com/google/deepvariant/blob/r1.8/deepvariant/pileup_channel_lib.h#L70) that you can set by that parameter or you can also look [here](https://github.com/google/deepvariant/blob/r1.8/deepvariant/dv_constants.py#L84).

**Comment by AndrewCarroll** [comment]
Hi @rickymagner 

A quick note on your question about where is DeepVariant v1.7. Because DeepVariant and DeepSomatic share the underlying code base, when we released a new DeepSomatic version, we needed to update GitHub. We decided to version both updates in a unified way. So the v1.7 update is mainly relevant to DeepSomatic. This is why from the perspective of the DeepVariant documentation, DeepVariant v1.8 appears to skip v1.7.

I am sorry if this is confusing, we couldn't think of a better way to handle the versioning.

**Comment by rickymagner** [comment]
@kishwarshafin Thanks for your reply. I think I've seen instructions on trying to add a new channel that way, but is a bit awkward from a user perspective since it requires digging into the C code. Back in https://github.com/google/deepvariant/issues/790 someone said the interface might get better due to some planned refactoring. For example, it would be nice if the `--channel_list` flag could handle some of the "under the hood" details of using a custom BAM tag for training/eval, but I understand if that's not planned for the future.

**Comment by kishwarshafin** [comment]
Hi @rickymagner,

Generalizing channel generation to custom bam tags is quiet a difficult task. Given the custom tags needs to have some standard representation and code needs to be present in `htslib` to parse and present the value of the tags properly at read level. I am uncertain on how much engineering is required to achieve such generalizable channel generation. Are there specific standard tags you are looking to use for your custom-channel training workflow? If it is something within the scope, we would be happy to take a look.

**Comment by rickymagner** [comment]
Thanks for clarifying. I think I was generally interested in the idea of experimenting with various tags, rather than having specific ones in mind. I'll look into the more detailed method if I have some specific channels to use in the future.
