### ISSUE TITLE
RNA-seq data reference file?

### ISSUE THREAD

**Issue by CSi-Ti** [google/deepvariant#911]
Hi DeepVariant team,

Thank you for creating this tool which I find very useful. 
I have a question regarding RNA-seq data analysis using DeepVariant. Please see the code below:

BIN_VERSION="1.4.0"

sudo docker run \
  -v "$(pwd):$(pwd)" \
  -w $(pwd) \
  google/deepvariant:"${BIN_VERSION}" \
  run_deepvariant \
    --model_type=WES \
    --customized_model=model/model.ckpt \
    **--ref=reference/GRCh38_no_alt_analysis_set.fasta** \
    --reads=data/hg005_gm26107.mrna.grch38.bam \
    --output_vcf=output/HG005.output.vcf.gz \
    --num_shards=$(nproc) \
    --regions=data/chr20_CDS_3x.bed \
    --make_examples_extra_args="split_skip_reads=true,channel_list='BASE_CHANNELS'" \
    --intermediate_results_dir output/intermediate_results_dir

In order to get accurate results, should the reference file be the same as the one used for alignment? In the example data,  "GRCh38_no_alt_analysis_set.fasta" was used, I wonder if I can change it to other versions of GRCh38 or GRCh37 fasta file? 

Many thanks in advance and I look forward to your reply.

Best,
Nico

**Comment by AndrewCarroll** [comment]
Hi @CSi-Ti 

You can change to other versions of the reference genome. We find the differences in performance between them to be relatively small, at least when looking at genome-wide statistics.

**Comment by CSi-Ti** [comment]
Sounds good, thank you, Andrew!
