### ISSUE TITLE
In r1.8.0, the training process only saves checkpoints instead of best saved model?

### ISSUE THREAD

**Issue by csyourui** [google/deepvariant#913]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.8/docs/FAQ.md**:
Yes

**Describe the issue:**
In r1.8.0, the training process only saves checkpoints rather than the best saved model. [only comment in here](https://github.com/google/deepvariant/blob/r1.8/deepvariant/train.py#L661-L663)

Additionally, the *[convert_to_saved_model](https://github.com/google/deepvariant/blob/r1.8/deepvariant/convert_to_saved_model.py)* does not appear to copy to the Docker directory /opt/deepvariant/bin.

Maybe it is not a bug, but i find it is not easy to convert the model to ONNX without the saved model format.
**Setup**
  - Operating system: ubuntu 22.02
  - DeepVariant version: r1.8.0
  - Installation method (Docker):
  - Type of data: 

**Steps to reproduce:**
  - Command: 
followd case study in [deepvariant-training-case-study](https://github.com/google/deepvariant/blob/r1.8/docs/deepvariant-training-case-study.md)
```
time docker run --gpus 2 \
    --rm \
    -v ${OUTPUT_DIR}/output:/output: \
    -v ${OUTPUT_DIR}/training_dir:/training_dir \
    -v ${OUTPUT_DIR}/dv_config.py:/dv_config.py \
    google/deepvariant:1.8.0-gpu \
    train \
    --config=/dv_config.py:base \
    --config.train_dataset_pbtxt="/output/train_data/training_set_gpu.pbtxt" \
    --config.tune_dataset_pbtxt="/output/validation_data/validation_set_gpu.pbtxt" \
    --config.init_checkpoint=/training_dir/wgs_checkpoints/deepvariant.wgs.ckpt \
    --config.num_epochs=10 \
    --config.learning_rate=0.0001 \
    --config.num_validation_examples=0 \
    --experiment_dir=/training_dir \
    --strategy=mirrored \
    --config.batch_size=512 \
> "train.log" 2>&1
```
  - Error trace: (if applicable)

**Does the quick start test work on your system?**
Please test with https://github.com/google/deepvariant/blob/r0.10/docs/deepvariant-quick-start.md.
Is there any way to reproduce the issue by using the quick start?

**Any additional context:**

**Comment by danielecook** [comment]
@csyourui apologies for this change. I will try to put together a custom docker image with the `convert_to_saved_model` script and restore storing the saved_model at the end of training. I will try to follow up on this in the next day or so.

**Comment by danielecook** [comment]
@csyourui we are still working on this - I will update you early next week.

**Comment by csyourui** [comment]
Thank you, @danielecook.
I’m looking forward to your updates and am grateful for the time you’ve taken to help resolve my concerns. Thanks again!

**Comment by csyourui** [comment]
@danielecook Thank you so much for providing the updated Docker images and detailed instructions! The new image works perfectly for me. Thanks again for your support and quick response!
