### ISSUE TITLE
No examples generated causes errors now in 1.8

### ISSUE THREAD

**Issue by mrvollger** [google/deepvariant#916]
**Have you checked the FAQ? https://github.com/google/deepvariant/blob/r1.8/docs/FAQ.md**:
Yes

**Describe the issue:**
When using the regions argument in v1.8, DeepVariant throws an error when there are no examples that can be generated in that region of the genome.

This is an issue because I use the region's argument to distribute processing over our cluster since we don't have powerful GPUs to run the whole sample. I think this behavior is new to 1.8 at least it was not happening in 1.6.1 and 1.5.0 in my pipeline.

**Setup**
  - Operating system: RedHat
  - DeepVariant version: 1.8
  - Installation method (Docker, built from source, etc.): Docker
  - Type of data: (sequencing instrument, reference genome, anything special that is unlike the case studies?): pacbio hifi

**Steps to reproduce:**
  - Command:
```
    /opt/deepvariant/bin/run_deepvariant             --model_type=PACBIO             --ref=/mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/Pac
Bio-Fiber-seq/PS30065/hg38/data/ref/reference.fa             --reads=/mmfs1/gscratch/stergachislab/sjn/projects/mitchell/other-dir/results/PS30065.SMRT1/pbmm2/PS30065.SMRT1
.bam             --regions chr1_KI270713v1_random:1-40745             --output_vcf=temp/PS30065/deepvariant/chr1_KI270713v1_random_chr_st_1_chr_en_40745/PS30065.deepvariant
.vcf.gz             --output_gvcf=temp/PS30065/deepvariant/chr1_KI270713v1_random_chr_st_1_chr_en_40745/PS30065.deepvariant.gvcf.gz             --num_shards=8
```
  - Error trace: (if applicable)
```
W1212 10:29:27.096191 23082305351680 call_variants.py:594] Unable to read any records from /tmp/tmp9w8wtloc/make_examples.tfrecord@8.gz. Output shards will contain zero rec
ords.
Traceback (most recent call last):
  File "/tmp/Bazel.runfiles_ddcjvg1g/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 976, in <module>
    app.run(main)                                                                                                                                                             File "/tmp/Bazel.runfiles_ddcjvg1g/runfiles/absl_py/absl/app.py", line 312, in run                                                                                            _run_main(main, args)
  File "/tmp/Bazel.runfiles_ddcjvg1g/runfiles/absl_py/absl/app.py", line 258, in _run_main                                                                                      sys.exit(main(argv))                                                                                                                                                      File "/tmp/Bazel.runfiles_ddcjvg1g/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 952, in main
    call_variants(
  File "/tmp/Bazel.runfiles_ddcjvg1g/runfiles/com_google_deepvariant/deepvariant/call_variants.py", line 738, in call_variants
    raise ValueError(                                                                                                                                                       ValueError: Examples file is empty. If you want to allow empty examples, please set --allow_empty_examples to True.
```

**Does the quick start test work on your system?**
Yes
**Is there any way to reproduce the issue by using the quick start?**
No

Thanks in advance for your help,
Mitchell

**Comment by lucasbrambrink** [comment]
Hi Mitchell,

Thanks for the question! As it happens, in `1.8.0`, we added a flag to `call_variants` to handle this case: 
[--allow_empty_examples](https://github.com/google/deepvariant/blob/r1.8/deepvariant/call_variants.py#L212-L217). 

You can set this in `run_deepvariant` via
```--call_variants_extra_args="allow_empty_examples=true"```. This case can happen if all variants in the region are called by the small model (see https://github.com/google/deepvariant/blob/r1.8/docs/deepvariant-small-model-details.md). We will be sure to handle this case by default.

Try:
```
/opt/deepvariant/bin/run_deepvariant \
--model_type=PACBIO \
--ref=/mmfs1/gscratch/stergachislab/userprod/production/fibertools-pipeline/PacBio-Fiber-seq/PS30065/hg38/data/ref/reference.fa \
--reads=/mmfs1/gscratch/stergachislab/sjn/projects/mitchell/other-dir/results/PS30065.SMRT1/pbmm2/PS30065.SMRT1.bam \
--regions chr1_KI270713v1_random:1-40745 \
--output_vcf=temp/PS30065/deepvariant/chr1_KI270713v1_random_chr_st_1_chr_en_40745/PS30065.deepvariant.vcf.gz \
--output_gvcf=temp/PS30065/deepvariant/chr1_KI270713v1_random_chr_st_1_chr_en_40745/PS30065.deepvariant.gvcf.gz \
--num_shards=8 \
--call_variants_extra_args="allow_empty_examples=true"
```

Let me know if that doesn't fix it!

**Comment by mrvollger** [comment]
Perfect, thanks! I had seen that option in the error msg but was trying to add `--allow_empty_examples` directly and that threw errors.

**Comment by mrvollger** [comment]
Just confirming this worked for me!

**Comment by indapa** [comment]
I was facing the same issue as, and 

`--call_variants_extra_args="allow_empty_examples=true"`

worked for me! 

I tried `allow_empty_examples=true` but it threw an error.
