### ISSUE TITLE
problems with bazel installation d.v. v0.7.0 on Ubuntu 16 

### ISSUE THREAD

**Issue by vendig** [google/deepvariant#92]
I am using Ubuntu 16. I got binaries from file:
https://github.com/google/deepvariant/releases/download/v0.7.0/deepvariant.zip

**I run run-prereq.sh first and warning message appears:** 
Cloning into 'tensorflow'...
Switched to a new branch 'r1.9'
Extracting Bazel installation...
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".

**When I run ./build_and_test.sh command, an error appears:**
./build_and_test.sh: line 54: bazel: command not found

**When I run ./run-prereq.sh command, it stops at "unable to re-open stdin:"** 
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin: 

As I can see the problem is bazel installation and already some ways of resolving the problem were suggested - one of suggestion was to change .txt.sh file, another one to manually install bazel package (which seems to me regarding instructions on bazel site not a straightforward approach). I am running DeepVariant on a cluster, therefore would be very grateful for any more straightforward
suggestion.

Thank you very much.

**Comment by pichuan** [comment]
(1) Have you considered using docker instead of the prebuilt binaries? In this version, we updated the quick start and case studies to use docker. I personally find that much more convenient. 
(2) For bazel, can you try the official instructions: https://docs.bazel.build/versions/master/install-ubuntu.html
Last time I tried our script on a Ubuntu 16 machine on GCP, it worked. But maybe I should try one not on GCP.
If you find out a more robust installation for bazel, please share and I can update our instructions.

**Comment by pichuan** [comment]
Closing this issue since there's no further information.
