### ISSUE TITLE
pyclif dependency 

### ISSUE THREAD

**Issue by ramcn** [google/deepvariant#93]
Hello,

I am trying to build deepavariant on a HPC node on which all the required dependency is met except pyclif.  I do not have root privileges to install it under /usr/local/clif. Hence I downloaded pyclif source code and ran the INSTALL.sh to get it successfully built and installed under $HOME and activated the pyclif virtualenv. 

(clif) [test-node]$ which pyclif
~/opt/clif/bin/pyclif

However build_and_test.sh fails with the below error. Any changes required to deepvariant build setup to pick up the pyclif installation in my home directory?
(18:02:14) ERROR: missing input file '@clif//:clif/bin/pyclif'

**Comment by pgrosu** [comment]
Hi @ramcn,

Just go into the WORKSPACE file at the following location:

https://github.com/google/deepvariant/blob/r0.7/WORKSPACE#L87

And update your path to the full path of `opt` - (below is an example):

```
new_local_repository(
    name = "clif",
    build_file = "third_party/clif.BUILD",
    path = "/home/ramcn/opt",
)
```

Paul

**Comment by ramcn** [comment]
Thanks Paul. That helped!

Cheers,
Ram
