### ISSUE TITLE
protobuf error

### ISSUE THREAD

**Issue by ramcn** [google/deepvariant#94]
Hello,

I am facing the below error when running built_and_test.sh. I have protocol buf built and installed in my home directory.

(19:11:12) ERROR: /uufs/chpc.utah.edu/common/home/u1142888/deepvariant/bazel_tmp/_bazel_u1142888/bc41070ad1d30708841b968fbd6bc540/external/com_google_protobuf/BUILD:104:1: C++ compilation of rule '@com_google_protobuf//:protobuf' failed (Exit 1): gcc failed: error executing command 

I have built the latest protobuf from source following the instructions [here](https://github.com/protocolbuffers/protobuf/blob/master/src/README.md) and have installed it under $HOME/protobuf and updated my PATH and LD_LIBRARY_PATH accordingly.

Looking for some pointers on how to resolve this issue by tweaking the build procedure.

Thank  you,
Ram

**Comment by ramcn** [comment]
[log1.txt](https://github.com/google/deepvariant/files/2393958/log1.txt)
Hi Paul,

Attached is the log with --verbose_failures. Yes I am using a node on our HPC cluster.

Some more details about my environment:
1. gcc version 4.8.5
2. centos 7
3. protobuf version 3.5.1 installed as module with PATH and LD_LIB_PATH set accordingly.
4. clif installed under HOME directory and WORKSPACE updated accordingly.

Thank you
Ram

**Comment by pgrosu** [comment]
Hi Ram,

I see what's happening.  You have protobuf 3.5.1 in your include paths, but this is trying to compile the protobuf 3.6 version.  You will notice in this line:

```
new (initial_block_) Block(options_.initial_block_size, NULL);
```

Which is only part of `3.6.x`:

https://github.com/protocolbuffers/protobuf/blob/3.6.x/src/google/protobuf/arena.cc#L77

Basically a bunch of conflicts between declarations and use.

So to simplify things, could you remove your protobuf 3.5.1 from your paths.  If you are on a university cluster, it's usually something like `module unload MODULE_NAME`.  After that try rerunning it again.

Thanks,
~p

**Comment by ramcn** [comment]
Hi Paul,

I simplified my setup a bit and have removed protobuf in my PATHs. I was able to complete the build, but most of the tests seem to be failing with the below error.

TypeError: __new__() got an unexpected keyword argument 'serialized_options'

Attached is the log with verbose failures. Please let me know if you have any clue.
[log2.txt](https://github.com/google/deepvariant/files/2397845/log2.txt)

**Comment by pgrosu** [comment]
Hi Ram,

You really do not want to have any errors show up in any of your tests, especially when performing variant calling.   It's an easily fixable issue where the Google folks would just need to update their TensorFlow Python package distributed with DeepVariant, which was probably compiled with an earlier version of protobuf, while currently the Tensorflow requires `3.6` of protobuf and the Protobuf version being compiled with DeepVariant is `3.6`.  Looking at your log file, you are using the CPU version.  The current version on PyPI of TensorFlow is 1.10.1, and DeepVariant uses version 1.9.  Here's the process by which I went about to determine what is happening:

1. If you download both `whl` files of Tensorflow like this:

```
wget https://storage.googleapis.com/deepvariant/packages/tensorflow/tensorflow-1.9.0.deepvariant_gcp-cp27-none-linux_x86_64.whl

wget https://files.pythonhosted.org/packages/1a/c4/8cb95df0bf06089014259b25997c3921a87aa08e2cd981417d91ca92f7e9/tensorflow-1.10.1-cp27-cp27mu-manylinux1_x86_64.whl
```

2. Next rename each of the `whl` files to `zip`, and then uncompress them in separate directories.  If you then look at one of the version `1.10.1` files that has the `serialized_options` such as `purelib/tensorflow/core/framework/resource_handle_pb2.py`, you will see the following difference between the versions, where the `serialized_options` keyword is present in the `1.10.1` version, but not in the `1.9.0` version:

#### _*For version 1.9*_

```Python
DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/core/framework/resource_handle.proto',
  package='tensorflow',
  syntax='proto3',
  serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
)

```

#### _*For version 1.10.1*_

```Python
DESCRIPTOR = _descriptor.FileDescriptor(
  name='tensorflow/core/framework/resource_handle.proto',
  package='tensorflow',
  syntax='proto3',
  serialized_options=_b('\n\030org.tensorflow.frameworkB\016ResourceHandleP\001Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\370\001\001'),
  serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
)
```

ProtoBuf 3.6 passes the `serialized_options` argument in the call to `__new__` as shown here:

https://github.com/protocolbuffers/protobuf/blob/3.6.x/python/google/protobuf/descriptor.py#L283

```Python
    def __new__(cls, name, full_name, filename, containing_type, fields,
                nested_types, enum_types, extensions, options=None,
                serialized_options=None,
                is_extendable=True, extension_ranges=None, oneofs=None,
                file=None, serialized_start=None, serialized_end=None,  # pylint: disable=redefined-builtin
                syntax=None):
      _message.Message._CheckCalledFromGeneratedFile()
      return _message.default_pool.FindMessageTypeByName(full_name)
```

3. If you look at the `METADATA` file of each TensorFlow package to see the protobuf version requirement, it will look like this:

```
paul:~/tensorflow$ cat unzip-1.9/tensorflow-1.9.0.dist-info/METADATA  | grep protobuf
Requires-Dist: protobuf (>=3.4.0)

paul:~/tensorflow$ cat unzip-1.10/tensorflow-1.10.1.dist-info/METADATA  | grep protobuf
Requires-Dist: protobuf (>=3.6.0)
```

Paul

**Comment by ramcn** [comment]
Thanks paul for the detailed analysis and explanation of how you went about it.

To confirm this analysis I tried out by changing TF_WHL_VERSION and other related symbols to 1.10.1 in settings.sh so that build-prereq.sh installs the matching tensorflow. Now, the build and test passes and I am able to run variant calling. I presume this is a good workaround to address this issue.

**Comment by depristo** [comment]
@ramcn I'm delighted you've gotten your build sorted out.
@ramcn If you are building DeepVariant from scratch, and in particular TF's wheels directly, I'd recommend looking into the exact version of TF you want to use with DeepVariant. In particular, if you are intending to run on CPUs, we've found that the MKL extensions to TF make call_variants 3-4x faster. It may be worth building yourself an optimized TF wheel for DeepVariant to maximize performance.

@pgrosu Thank you for all of your insights into these issues Paul. It is much appreciate by myself and the rest of the team here at Google

**Comment by pgrosu** [comment]
That's great news Ram, and glad to hear it all worked out.  The logs were basically guiding me through rules of implication, and it looked like we were getting close.  Let us know if you run into any other issues, as we would be happy to help you out.

@depristo Thank you Mark for the nice compliments, that means quite a lot.  I always enjoy helping out folks and the team.  I find exploring complex and challenging problems interesting and fun.

**Comment by pichuan** [comment]
I'll close this issue now.
Thanks Paul!

**Comment by pgrosu** [comment]
Sure thing Pichuan and congratulations on the [Nature paper](https://www.nature.com/articles/nbt.4235)!
