### ISSUE TITLE
Errors when building with Ubuntu 18.04

### ISSUE THREAD

**Issue by vinisalazar** [google/deepvariant#98]
I am following the [Building from sources](https://github.com/google/deepvariant/blob/r0.7/docs/deepvariant-build-test.md) tutorial. I cloned the repository, then started building and got the following errors:

```
viniws@woese:~/Code/deepvariant$ ./build-prereq.sh   
========== Load config settings.  
========== [qua set 26 16:42:55 -03 2018] Stage 'Install the runtime packages' starting   
========== Load config settings.   
========== [qua set 26 16:42:55 -03 2018] Stage 'Misc setup' starting   
========== [qua set 26 16:42:55 -03 2018] Stage 'Update package list' starting   
E: The repository 'http://apt.postgresql.org/pub/repos/apt YOUR_UBUNTU_VERSION_HERE-pgdg Release' does not have a Release file.     
E: The repository 'http://ppa.launchpad.net/gnome-terminator/ppa/ubuntu bionic Release' does not have a Release file       
```

And after:

```
+ source settings.sh
++ export DV_USE_PREINSTALLED_TF=0
++ DV_USE_PREINSTALLED_TF=0
++ export TF_CUDA_CLANG=0
++ TF_CUDA_CLANG=0
++ export TF_ENABLE_XLA=0
++ TF_ENABLE_XLA=0
++ export TF_NEED_CUDA=0
++ TF_NEED_CUDA=0
++ export TF_NEED_GCP=1
++ TF_NEED_GCP=1
++ export TF_NEED_GDR=0
++ TF_NEED_GDR=0
++ export TF_NEED_HDFS=0
++ TF_NEED_HDFS=0
++ export TF_NEED_JEMALLOC=0
++ TF_NEED_JEMALLOC=0
++ export TF_NEED_MKL=0
++ TF_NEED_MKL=0
++ export TF_NEED_MPI=0
++ TF_NEED_MPI=0
++ export TF_NEED_OPENCL=0
++ TF_NEED_OPENCL=0
++ export TF_NEED_OPENCL_SYCL=0
++ TF_NEED_OPENCL_SYCL=0
++ export TF_NEED_S3=0
++ TF_NEED_S3=0
++ export TF_NEED_VERBS=0
++ TF_NEED_VERBS=0
++ export TF_CUDA_VERSION=8.0
++ TF_CUDA_VERSION=8.0
++ export CUDA_TOOLKIT_PATH=/usr/local/cuda
++ CUDA_TOOLKIT_PATH=/usr/local/cuda
++ export TF_CUDNN_VERSION=6
++ TF_CUDNN_VERSION=6
++ export CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ CUDNN_INSTALL_PATH=/usr/lib/x86_64-linux-gnu
++ DV_BAZEL_VERSION=0.15.0
++ export DEEPVARIANT_BUCKET=gs://deepvariant
++ DEEPVARIANT_BUCKET=gs://deepvariant
++ export DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ DV_PACKAGE_BUCKET_PATH=gs://deepvariant/packages
++ export DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ DV_PACKAGE_CURL_PATH=https://storage.googleapis.com/deepvariant/packages
++ export DV_TF_NIGHTLY_BUILD=0
++ DV_TF_NIGHTLY_BUILD=0
++ [[ 0 = \1 ]]
++ export DV_CPP_TENSORFLOW_TAG=r1.9
++ DV_CPP_TENSORFLOW_TAG=r1.9
++ export DV_GCP_OPTIMIZED_TF_WHL_VERSION=1.9.0
++ DV_GCP_OPTIMIZED_TF_WHL_VERSION=1.9.0
++ export DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=1.9.0
++ DV_TENSORFLOW_STANDARD_GPU_WHL_VERSION=1.9.0
++ export DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=1.9.0
++ DV_TENSORFLOW_STANDARD_CPU_WHL_VERSION=1.9.0
++ export DV_GPU_BUILD=0
++ DV_GPU_BUILD=0
++ export DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ DV_USE_GCP_OPTIMIZED_TF_WHL=1
++ export GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.9.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ GCP_OPTIMIZED_TF_WHL_FILENAME=tensorflow-1.9.0.deepvariant_gcp-cp27-none-linux_x86_64.whl
++ export GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_PATH=gs://deepvariant/packages/tensorflow
++ export GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ GCP_OPTIMIZED_TF_WHL_CURL_PATH=https://storage.googleapis.com/deepvariant/packages/tensorflow
++ export DV_INSTALL_GPU_DRIVERS=0
++ DV_INSTALL_GPU_DRIVERS=0
+++ which python
++ export PYTHON_BIN_PATH=/home/viniws/anaconda3/bin/python
++ PYTHON_BIN_PATH=/home/viniws/anaconda3/bin/python
++ export USE_DEFAULT_PYTHON_LIB_PATH=1
++ USE_DEFAULT_PYTHON_LIB_PATH=1
++ export 'DV_COPT_FLAGS=--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings'
++ DV_COPT_FLAGS='--copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings'
+ bazel
./build_and_test.sh: line 39: bazel: command not found
+ PATH=/home/viniws/bin:/home/viniws/anaconda3/bin:/home/viniws/anaconda3/bin:/home/viniws/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
+ [[ 0 = \1 ]]
+ bazel test -c opt --copt=-march=corei7 --copt=-Wno-sign-compare --copt=-Wno-write-strings deepvariant/...
./build_and_test.sh: line 54: bazel: command not found
```

I don't know where to start troubleshooting this. In the first error, apparently the script couldn't retrieve my Ubuntu version, but I don't know where to edit it to place it there manually.

**Comment by pichuan** [comment]
I wonder if the installation for bazel is different on Ubuntu 18.04.
Can you try installing bazel separately, see https://docs.bazel.build/versions/master/install-ubuntu.html and see if you can install bazel?

**Comment by vinisalazar** [comment]
Hello @pichuan , thanks for the swift reply. I installed bazel manually, the installations is working, however I get the same error from ./build-prereq.sh

**Comment by pgrosu** [comment]
@vinisalazar Can you create a gist or attach a complete log of what you see when you run `./build-prereq.sh`?  Also if you type `which bazel` what does show up?  It might not be in your path.

Thanks,
~p

**Comment by vinisalazar** [comment]
`which bazel` returns `/usr/local/bin/bazel` (I installed with sudo)

Here it is: https://gist.github.com/vinisalazar/c68d290a68f12677211c1398ba3c6dcc

**Comment by pgrosu** [comment]
Hi @vinisalazar,

Out of curiosity, what happens if you type the following:

`conda install -c bioconda deepvariant`

Thanks,
Paul

**Comment by vinisalazar** [comment]
Hi @pgrosu ,

Thanks, that solved it. I had no idea there was a conda build for this package, otherwise it'd be the first way I'd try to install it. However, I'd recommend looking into these building problems.

Thank you very much, 
V

**Comment by pichuan** [comment]
Hi @vinisalazar , note that the current bioconda version seems to be 0.6.1. It's also not directly maintained by our team, but it's contribution from @chapmanb. I'll check with him to see if we can update it.

And yes, we'll look into the building issues.

**Comment by pichuan** [comment]
Hi @vinisalazar , I just tried to build DeepVariant on a Ubuntu 18.04 machine. I did encounter some issue, but it didn't seem to be the same as the one you have.

I suspect when you run `build-prereq.sh`, it actually failed already at this line:

```
sudo -H apt-get -qq -y update
```

Can you let me know if that works for you?
Maybe you can run it with out the `-qq` so it will actually report why it fails.

Thanks!

**Comment by vinisalazar** [comment]
Hello @pichuan, thank you, I will try this on Monday when I get back to my work machine and come back with an update.

**Comment by pgrosu** [comment]
Cool beans!  Thanks Brad for the quick turnaround.

**Comment by pichuan** [comment]
Hi,
I want to give an update on this - 
in the next minor release of DeepVariant, we'll plan to update the building script to allow you build on Ubuntu 18.04.

**Comment by pgrosu** [comment]
Wait, who is awesome?  You are Pichuan! :)

**Comment by vinisalazar** [comment]
Indeed @pgrosu, thank you @pichuan
